ceph/ceph-ansible

dummy-ansible-hosts

The Ansible YAML syntax checker needs an inventory file.

Add a dummy ansible host file for syntax checking

---

roles/ceph-mon/defaults/main.yml
roles/ceph-osd/defaults/main.yml

We do not need them since they get registered by the ceph-common role.

Remove the fsid vars from mon and osd roles

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Big cluster will easily reach the default limit so we need to increase
it and make it configurable.

Bump up max open file for big cluster

---

roles/ceph-common/tasks/main.yml

Large cluster will easily reach the default value so we increase it.

Bump up maximum number of open files

---

roles/ceph-mon/tasks/deploy_monitors.yml

Default behavior is to fail if a variable is not declared however this
can be disable in your ansible.cfg so we force this variable as
mandatory.

Make the monitor secret a mandatory variable.

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/os_tuning.yml

We now use a single task and loop over a set of params, it's easier to
add now params.
Setting zone_reclaim_mode to 0.
See the discussion on the Ceph ML:
http://lists.ceph.com/pipermail/ceph-users-ceph.com/2013-December/036211.html

Restructure OS tuning and add new value

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/os_tuning.yml

In storage world it's often recommended to disable transparent hugepages
as they will tend to lower performance.
Note that this change won't survive reboot. There are several ways to
disable this permanently such as:
* rc.local
* grub boot line
It's a bit tricky to do this in Ansible since it really depends on the
OS you're running on.

Ability to disable transparent hugepage

---

roles/ceph-common/tasks/install_on_redhat.yml

Without this plugin if a Ceph version is present in a repo (let's say
epel) it will install the epel version and not the ICE version.
We install yum-plugin-priorities.noarch to honor the 'priority=1' flag.

Add yum priority plugin

---

roles/ceph-common/defaults/main.yml

Using the largeio,inode64,swalloc options usually improves sequential
workloads.

Add more option to maximise sequential IO

---

roles/ceph-common/tasks/os_tuning.yml

The old path was meant for old kernels...

Fix transparent huge page sys path

---

roles/ceph-common/defaults/main.yml

On OSD servers we want to keep as much inodes and dentries in memory as
we can.

Decrease vfs cache pressure

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/os_tuning.yml

With enough memory we will probably not need any swap.

Ability to disable swap

---

Vagrantfile

Use a Trusty box instead of Precise.

Upgrade to Trusty box

---

Vagrantfile

The recently added Trusty box was build with a Controller named
"SATAController", we must reuse the same name while adding our devices.

Change disk controller name

---

roles/ceph-radosgw/tasks/main.yml

In a previous commit, key name changed, fixing this.

Fix RGW key fetching

---

Vagrantfile

When enabling radosgw virtual machines, we also need to enable the
radosgw variable. Same thing goes with the mds.

Enable proper options while activating rgw or mds with Vagrant

---

roles/ceph-common/templates/ceph.conf.j2

Use hostname in socket and log.
Improve jinja template so when a var doesn't exist we don't indent the
next line.

Improve RGW config section

---

roles/ceph-common/templates/ceph.conf.j2

If we use the hostname, the radosgw will lookup for a wrong secret.
Using the same name for all the gateways.

Fix the rgw section

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-radosgw/tasks/main.yml

Now we can setup multi-rgw with the playbook.
Each rgw instance has its own key.

Bring multi RGW support

---

.gitignore
Vagrantfile
vagrant_variables.yml

This is really handy when we are testing code since we don't need to
modify the Vagrantfile, which is tracked by git.
The next commit will ignore the vagrant_variables.yml file.

Use an external file to manage Vagrant variables

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-radosgw/defaults/main.yml
roles/ceph-radosgw/tasks/install_debian.yml
roles/ceph-radosgw/tasks/install_redhat.yml
roles/ceph-radosgw/tasks/main.yml

The default is now to use civet web since it has proven to be a bit more reliable and easy to setup than Apache.
We don't support multi backend yet.
Radow GW supports both CGI and civet web on the same machine.

Add support of civetweb for Rados Gateway

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

The path must be writable by QEMU and allowed by SELinux or AppArmor

Add RBD client logs support

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml

Now proper commands/actions are used per hosts and groups.
Closes: #220 

Improve Handler support

---

roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/main.yml

The ceph fs new command was introduced in Ceph 0.84. Prior to this
release, no manual steps are required to create a filesystem, and pools
named data and metadata exist by default.

Fix MDS creation for version >= 0.84

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-radosgw/tasks/pre_requisite.yml
roles/ceph-radosgw/tasks/start_radosgw.yml

Fix the usage of Upstart for Ubuntu machines instead of the init.d
script.
Note that because of the way upstart init script looks at the radosgw id
the command 'start radosgw id=' is broken, you should use 'start
radosgw-all' instead.
Keep backard compatibility with the radosgw init script as well by using
client prefixed by 'client.radosgw'.
Sorry this will probably break current RGW installations...

Rework radosgw keys and data dir path

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-restapi/tasks/main.yml
roles/ceph-restapi/tasks/pre_requisite.yml
site.yml

Now the Ceph REST API can be deployed.
Default implementation deploys it on the same nodes as the monitors
which should be fine.

Implement Ceph REST API

---

roles/ceph-mon/tasks/main.yml

Make sure that 'mds' is enabled before creating the filesystem.

Enforce var pool creation

---

roles/ceph-radosgw/tasks/start_radosgw.yml

If the distribution wasn't Ubuntu, the check wasn't performed so the
evaluation in the task later wasn't possible.

Fix RGW startup

---

roles/ceph-restapi/tasks/main.yml

Default client is already client.restapi

---

roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/start_monitor.yml

Depending on the distro, init scripts will look for different files to
be available on the ceph data dir.
Fixing the upstart support here.
Handler might have to be reworked (again...) eventually... #238

Activate either sysvinit or upstart

---

contrib/splitup.yml

Adds an ansible playbook to split the roles from this repo and keep them updated!
Use it like this:
```
$ ansible-playbook -i dummy-ansible-hosts contrib/splitup.yml \
--tags split --extra-vars github=username/ansible
$ ansible-playbook -i dummy-ansible-hosts contrib/splitup.yml \
--tags update --extra-vars github=username/ansible
```

Adds an ansible playbook to split the roles from this repo.

---

roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-radosgw/tasks/main.yml
roles/ceph-radosgw/tasks/pre_requisite.yml
roles/ceph-restapi/tasks/pre_requisite.yml

Once again and hopefully final commit to rework the support of both
upstart and sysvinit. As from now, Ubuntu systems will use upstart and
the others will use sysvinit.
A later commit might include the support of systemd as the unit files
come out. This will be for Hammer so probably soon.

Rework upstart and sysvinit

---

Vagrantfile
vagrant_variables.yml

The box can be configured thanks to a new var, look at vagrant_variables
and select your box.
Handy to test several distros deployment.

Make more boxes available

---

rolling_update.yml

Chain sed commands with ';' and add '-s' to grep for quiet output

Improve regex syntax

---

roles/ceph-restapi/tasks/main.yml
site.yml

Just a quick PR to allow specifying `restapi=false` in Ansible to skip the tasks in `ceph-restapi` role.

Allow restapi=false

---

rolling_update.yml

We don't really want to trigger any sort of scrubbing process while
performing the upgrade.

Add more OSD flags

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/install_on_debian.yml
roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/templates/ceph.conf.j2

More options.
We also now configure the rbd clients directories for logs and socket.

Add more flags to RBD clients

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-radosgw/tasks/pre_requisite.yml

Following the best practice, we don't create a key from the monitor but
we really on the initial keys created by the mons to bootstrap each
daemon.

Use a bootstrap key for rgw

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/templates/ceph.conf.j2

This will avoid some error messages from the client when running a
command with the CLI or other.

Create client socket path

---

group_vars/mdss
group_vars/mons
group_vars/osds
group_vars/rgws
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mds/tasks/docker.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/meta/main.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/secure_cluster.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/meta/main.yml
roles/ceph-osd/tasks/docker.yml
roles/ceph-radosgw/defaults/main.yml
roles/ceph-radosgw/meta/main.yml
roles/ceph-radosgw/tasks/docker.yml
roles/ceph-restapi/meta/main.yml

We now use ceph/daemon as a default container image so reflecting the
change here.

Update the Docker bootstrap part

---

roles/ceph-osd/tasks/raw_multi_journal.yml

The logic was broken here for repeated runs.  We only want to run
'ceph-disk prepare' when the disk does not contain a ceph partition, is
not a partition, and raw_multi_journal is set.  Previously it would
attempt to run 'ceph-disk prepare' when there was a ceph partition
because the second half of the 'or' was still true since it isn't a
partition.

Correct the logic for running 'ceph-disk prepare'

---

site.yml

Sinxe each Ceph role (except ceph-common) has a dependancy to
ceph-common we don't need to declare ceph-common again.
Prior to this change the ceph-common role was running twice, thing that
wasn't really elegant.

ceph-common was running twice

---

roles/ceph-common/tasks/main.yml

There is no need to apply these tuning flags to all the nodes.

Only apply os-tuning to OSD nodes

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/os_check.yml
roles/ceph-common/tasks/prerequisite_rh_storage.yml
roles/ceph-common/templates/redhat_storage_repo.j2

The new product version has jsut came out. ICE doesn't exist anymore and
Red Hat Storage is the name of the new product.

Add red hat storage support

---

roles/ceph-common/tasks/main.yml

`connection: local` opens an SSH connection to localhost, using whatever python interpreter in env. Ansible doesn't run under python3, which a lot of distributions have as default nowadays. Using `local_action` executes the action from the Ansible process on the host, so it's also more efficient.

Use local_action to ensure Ansible executes under python2

---

roles/ceph-common/tasks/main.yml

Without this, the subcription manager will run since the default value
for cdn is true...

Safer check

---

Vagrantfile
group_vars/all
group_vars/mons
group_vars/osds
roles/ceph-common/defaults/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-osd/defaults/main.yml

We want to force the user to only enable the options they need. Thus
they shouldn't have to enable one option and then disable another.

Change default options

---

roles/ceph-common/tasks/prerequisite_rh_storage_cdn_install.yml
roles/ceph-common/templates/ceph.conf.j2

Since the command is indempotent we don't need to check if the repo is
enabled as it will likely take twice the time.

Do not change when adding the repo

---

roles/ceph-osd/tasks/journal_collocation.yml
roles/ceph-osd/tasks/raw_multi_journal.yml
roles/ceph-osd/tasks/zap_devices.yml

Prior to this change, the zap was executed during every play, this was
not ideal. Now we do check if there is a 'ceph' partition. If so we skip
the zap.

Make zap option more secure

---

roles/ceph-common/tasks/install_on_debian.yml
roles/ceph-common/tasks/install_on_redhat.yml

While re-running the playbook we do not want to check for new packages.
We shouldn't perform upgrades, we leave this to the operators.

Do not use latest package

---

group_vars/all
roles/ceph-common/defaults/main.yml

We don't always have a dedicated cluster network so we can by default
re-use the public network value.
This is just laziness :).

Re-use public network for private network

---

purge-cluster.yml
roles/ceph-common/defaults/main.yml

We run a zap twice here since we can't combine with_items and
with_sequence yet. This will land in Ansible 2.0. We destroy all the
partitions and re-create new labels as well. We do this twice just
because sometimes one is not sufficient. We also call partprobe to make
sure that the kernel sees the changes.

Improve purge playbook

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

By default, we want to use format 2.
This closely works with rbd features as well.

Add support for image format

---

group_vars/all
group_vars/mons
roles/ceph-common/tasks/check_mandatory_vars.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-restapi/tasks/start_restapi.yml

Cool stuff :). We don't need to specify an initial monitor key anymore.
A key will automatically be generated.
The default key can always be overriden with the `monitor_secret`
variable.

Generate initial monitor key dynamically

---

roles/ceph-common/meta/main.yml

I'm currently getting a KeyError due to missing 'dependencies' on this
role when I attempt to install it with ansible-galaxy (ansible 1.9.2).
This commit simply defines an empty dependencies list so that
ansible-galaxy executes correctly.

Define dependencies in ceph-common's meta/main.yml

---

site.yml

If we don't do this we will hand up having N separate clusters.

Use serial to deploy ceph-mon in docker

---

roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

The 'ports' option was missing, so in order to expose a port we need
"expose" and "ports" options.

Expose rgw ports

---

purge-cluster.yml

If we call partprobe directly after the partition deletion the task will
get stucked.

Move parted to the end of the playbook

---

cluster-os-migration.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml
rolling_update.yml

Reverts ceph/ceph-ansible#367
Shoot. Real sorry about this, but I think it's best if we revert this for now. We were using a custom Ansible and it was working fine but upon testing with an old version of Ansible it appears one of the checks isn't working properly.

Revert "Use stat module instead of shell"

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Fix the logic for the mandatory devices check so that it applies to
raw_multi_journal and journal_collocation scenarios.

Fix devices check for raw_multi_journal

---

roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

Fix back the rolling update playbook.
However every single time the playbook will run it will check for new
packages and install the latest ones. I don't think this is always the
desired behaviour. We need to find a way to conciliate both...

Use latest packages

---

roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml

Currently the OpenStack pools that get created use the default pg_num.
This commit updates the ceph-mon role to allow the pg_num for each pool
to be customised.

Allow configurable pg_num for OpenStack pools

---

roles/ceph-osd/tasks/activate_osds.yml

I'm removing the ceph paritition check from `activate osd(s) when device is a disk` 
because the ceph parition does not exist when parted was registered (on a fresh install). 
This was causing the activate step to be skipped.

Remove parition check from ceph-osd role

---

roles/ceph-common/tasks/main.yml

When multiple monitor hosts attempt to create the fetch directory there
is the potential for the task to fail with:
"OSError: [Errno 17] File exists: 'fetch'"
This appear to be an issue with the file module trying to create the
same directory at the same time when the tasks has been delegated to a
single host.
This commit enables run_once on the affected task which should address
the issue.

Prevent failure from race creating fetch directory

---

Vagrantfile
vagrant_variables.yml.sample

Hi,
On many Vagrant boxes, default controller is not "SATAController". This PR provides a new option. You can use now every boxes you want without editing Vagrantfile.
Example:  "deb/wheezy-amd64" uses "SATA Controller".
Cheers!
Emilien

Vagrant storagectl as option

---

group_vars/all.sample
group_vars/mdss.sample
group_vars/mons.sample
group_vars/osds.sample
group_vars/restapis.sample
group_vars/rgws.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-restapi/defaults/main.yml
roles/ceph-restapi/tasks/docker/fetch_configs.yml
roles/ceph-restapi/tasks/pre_requisite.yml
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/fetch_configs.yml
roles/ceph-rgw/tasks/pre_requisite.yml

Currently, the fetch directory is created in your working directory
(where ansible is run from).  We prefer to not keep any state in this
directory and would prefer to have the fetch directory configurable so
we can store it outside of our code checkout.
This commit creates a new variable in each role called
`fetch_directory` (defaulting to the previous value of 'fetch/'), and
then updates each reference to 'fetch' to use the new variable instead.
Closes issue #383

Make fetch directory configurable

---

README.md
group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/install_on_debian.yml

Hi,
Some people prefers install package from their distro. This PR provides this feature as optional (default stays from ceph).
Cheers,
Emilien

Get Ceph from distro repository (debian-based)

---

roles/ceph-common/templates/ceph.conf.j2

This is a rare case but it happens. Since we're just calling
`monitor_interface` and not `hostvars[host]['monitor_interface'],
an error may occur when the current host's interface does not
exist on the other hosts. (eg. eth0 exists for node0, but it does
not exist on node1 and node2)
Fix for this is to use hostvars[host]['monitor_interface']

Fix for error when the nodes don't have the same interface name.

---

roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml

Hey @leseb 
An extra to #384 
Not sure if this is the solution we want or if we want to force optional-rpms onto the user at all. This is the only option if we want to install yum-plugin-priorities without adding non-RH repo's. (official RH support compliance, etc.)
Let me know what you think!
Timo

Enable optional-rpms on official RHEL for yum-plugin-priorities

---

roles/ceph-common/tasks/misc/system_tuning.yml

https://github.com/ceph/ceph-ansible/issues/397

fixing sysctl command to take whitespace-separated multi values for a key

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

It should be used to disable health warnings about number of PGs
being too low if some pools have very few objects bringing down
the average number of objects per pool. This happens when running RadosGW.
The default is 10 and since the warnings only occur with some use cases,
the default here is 10 as well. Set to 20 or more to silence the warnings.

Support setting the "mon pg warn max object skew" in ceph.conf

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Hi,
If you use `ceph_origin` == 'distro' and you don't set to true `ceph_stable`... `ceph_common` fails.
This PR fix this issue and manages well ceph_origin / "ceph sources" (when `ceph_origin` == 'upstream').
Cheers!
Emilien

Fix and improve checks when ceph_origin == 'distro'

---

roles/ceph-osd/tasks/check_devices.yml

Improve regular expression for recognizing partition name.  Regex now uses "or" syntax to represent different families of devices - SCSI, IDE, CCISS, NVM, and it's easy to add others.  The partition number is factored out at the end.  Learned from previous version that we could control how many letters or digits to allow - I allow for 2 digits in partition number so poor folk like me can have >= 10 disks/SSD in their journal device.  
In the future, should we just ask Linux if it's a block device, and then look for a partition number on the end?  That would be a much simpler regex to maintain.

fix regex for partition names, enhance for NVM

---

group_vars/all.sample
group_vars/mdss.sample
group_vars/mons.sample
group_vars/osds.sample
group_vars/restapis.sample
group_vars/rgws.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mds/tasks/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/meta/main.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/meta/main.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-restapi/defaults/main.yml
roles/ceph-restapi/meta/main.yml
roles/ceph-restapi/tasks/main.yml
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/meta/main.yml
roles/ceph-rgw/tasks/main.yml

Since we renamed the variables and removed the old 'docker' variable we
can now collocate container daemons with standard bare metal deployment.
For instance, monitors can be containerized but osds can be deployed
traditionally.

Ability  to collocate bare metal and container

---

roles/ceph-mon/defaults/main.yml

Without this, and if all these group name variables are commented out in ```group_vars/all```, then the handler in ```ceph-common``` that depends on the value of ```mon_group_name``` would fail:
```
NOTIFIED: [ceph-common | restart ceph mons] ***********************************
fatal: [ctrl-gprt] => error while evaluating conditional: socket.rc == 0 and ansible_distribution != 'Ubuntu' and mon_group_name in group_names
```
which does look like some sort of unexpected behaviour on Ansible because those ```*_group_name``` defaults are set in the ```ceph-common``` role. I'm using Ansible 1.9.4.

Defaults for the ceph-mon role should be setting the 'mon_group_name'

---

roles/ceph-rgw/tasks/start_radosgw.yml

* The explicit check of 'ansible_distribution' being 'RedHat'
will not work on CentOS hosts.
* Check the value of 'ansible_os_family' instead.

This change address radosgw not getting started on CentOS

---

roles/ceph-osd/tasks/check_devices.yml

Verify that partitions (for both osd disks and journal disks) are sane
before attempting to prepare the device. Fail if parted fails for
whatever reason.
Closes: #437

Check partition status

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-rgw/tasks/start_radosgw.yml

This makes the roles work on el7; the old sysv-initscript invocations no longer work. Unfortunately the "restart osd with systemd" handler is now a "restart everything on the node" handler at the moment (to fix this a list of OSD-ids would need to be generated somehow, there no longer is a "restart all osds" option like in SysV and Upstart).

Add systemd-specific start/restart tasks/handlers for el7/infernalis

---

site.yml.sample

This has the tendency to make the ceph-mon play unnecessary longer when not
activated.

Moving out the restapi from the mons

---

roles/ceph-mon/tasks/ceph_keys.yml

I have seen a number of failures on this task due to mismatch of
checksum of source file and destination.  I suspect this is due to a
race condition caused by several hosts simultaneously copying the same
file to single location on the deployment server.
This change simply updates the 'copy keys to the ansible server' task
by adding 'run_once', which limits the task to being run on a single
MON host.
Closes issue #410

Add run_once to 'copy keys to the ansible server'

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Adding osd_scrub_begin_hour and osd_scrub_end_hour to limit scrub window of 24h if needed Fixes-Bug: #451

Adding osd_scrub_begin_hour and osd_scrub_end_hour

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-restapi/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/pre_requisite.yml

fixes ceph_stable_release logic mentioned in issue #446
I changed the argument used for starting the mds server. (pre
infernalis)
```
service ceph start mds
```
errors, while
```
service ceph start mds.$hostname
```
correctly starts the service.
I also changed the mds directory ownership from ceph:cephh to root:root
again, for pre-infernalis.
And finally, add the ceph_stable_releases checks for the upstart
activation task `for or after infernalis release'.

fixes ceph_stable_release logic mentioned in issue #446

---

roles/ceph-common/templates/ceph.conf.j2

We should not bother having another directory for this. So we stick with
the default logging dir.

Use /var/log/ceph for rgw logs

---

roles/ceph-common/defaults/main.yml

Because of some permission issue, likely due to the recent ceph user, if
80 is used for civetweb we get:
set_ports_option: cannot bind to 80: 13 (Permission denied)
Changing the port to 8080 until this gets solved.

Change default civetweb port to 8080

---

.gitignore
ansible.cfg
group_vars/all.sample
library/config_template
plugins/actions/config_template.py
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/templates/ceph.conf.j2

Thanks to @cloudnull great patch at
https://github.com/ansible/ansible/pull/12555
we now have the ability to add more configuration options instead of
having to push a PR to add a new option to the template. So you can
dynamically add and remove flags.
To use it, edit `ceph_conf_overrides` in `group_vars/all` like so:
```
ceph_conf_overrides
global:
foo: 12345
bar: 6789
```

Using config_template

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml

EL7 needs python-setuptools as a dependency
when running under ceph user the /var/run/ceph directory needs to be owned by ceph

fixed for infernalis on EL7

---

roles/ceph-common/tasks/checks/check_system.yml

without this change, ceph-ansible immediately aborts.

use proper syntax for expanding variables

---

roles/ceph-common/tasks/checks/check_firewall.yml
roles/ceph-common/tasks/main.yml

As raised in #466 it is important in order to avoid unnecessary
troubleshooting to check that ceph ports are allowed on the platform.
The check runs a nmap command from the host running Ansible
to all the ceph nodes with their respective ports.

Check for blocked ports

---

roles/ceph-common/tasks/checks/check_firewall.yml

Use command module instead of shell since we do not do anything fancy
here. Remove the duplicate register.

Fix firewall check

---

roles/ceph-common/tasks/checks/check_firewall.yml

We can not force people to have nmap installed so instead we raise a
warning is not present.

Do not make nmap mandatory

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml

My ceph cluster is not connected to the internet and must use local repo sources. Unfortunately at this time that is not possible with this role. My change moves the repo url to a defaults variable to allow overriding it.

allow customization of debian ceph stable repo url

---

roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml

make sym link to `ceph-mon@.service` and `ceph-osd@.service`, so `systemctl enable` doesn't complain.
@leseb

systemd unit files fixes for infernalis

---

roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

here is a PR with just the change to the path for the repo template - if you run without this you get an error like this.  Ansible seems to be checking ../templates, assuming that all yaml files will run from inside tasks/ subdirectory and not a directory nested inside it.
fatal: [rhs-cli-01] => input file not found at /mnt/oldroot/home/ben/ceph/dm-cache/ceph-ansible/roles/ceph-common/tasks/templates/redhat_storage_repo.j2 or /mnt/oldroot/home/ben/ceph/dm-cache/ceph-ansible/redhat_storage_repo.j2
BTW a similar change would be needed for RHCS 1.2 (Inktank Ceph Enterprise).

help ansible find repo template from installs subdirectory

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml

This change allows for configurable Ceph Conf Directory permissions. This
is required for integrators of Ceph, like OpenStack Cinder, which needs to
read from /etc/ceph for operation.

Configurable Ceph Conf Directory Permissions

---

group_vars/all.sample

Ceph-detect-init requires python-setuptools, when using upstream repositories.

Adding python-setuptools dependency for CentOS 7.

---

README.md
Vagrantfile
vagrant_variables.yml.sample

I was going through the readme and trying to get things going with vagrant and virtualbox and having some difficulties. Specifically, the vm.* settings in ``os_tuning_params`` were locking up my OSDs and ansible was losing the ssh connection to the nodes.  With these updates I'm able to get everything up and running. I was using vagrant==1.8.1 and virtualbox==5.0.4
I have not tested yet if anything here causes trouble for libvirt.

updates related to using vagrant and virtualbox for testing

---

README.md
group_vars/all.docker
group_vars/all.sample
group_vars/mons.sample
roles/ceph-common/tasks/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
vagrant_variables.yml.atomic

- Add variable to allow containerized mon to run privileged mode. This is to allow ceph-authtool to read and write to /var/ and /etc on CentOS Atomic.
- Add doc on how to run containerized deployment on RHEL/CentOS Atomic

additional work to deploy containerized ceph on Atomic

---

Vagrantfile
roles/ceph-common/tasks/main.yml
roles/ceph-mon/tasks/deploy_monitors.yml

these variables will be created on the fly, there is no need to force
them.

remove unecessary variables

---

roles/ceph-common/defaults/main.yml

It seems that in ansible 2.0 even if a task is skipped by it's `when`
clause not evaluating to true the variables in the play are still
rendered. Because these were not defined in defaults/main.yml ansible
was failing in installs/install_on_redhat where those variables are
being used in a `with_items` stanza.
An example of this failure can be seen here: https://jenkins.ceph.com/job/ceph-ansible-pull-requests/39/console

Add defaults for ceph_stable_ice_tmp_path and ceph_stable_ice_kmod

---

roles/ceph-common/tasks/main.yml

as reported in #510 some systems don't have uuidgen installed so we
better use a more global way to generate it. It sounds like python
should be available in case uuidgen is not.
Otherwise we will have to find another way :)
closes #510

ceph-common: use a generic way to create uuid

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
rolling_update.yml

Currently, all the ceph package installation resources use
"state=latest", which means subsequent runs of the ceph playbooks
could result in ceph being upgraded if there are package updates
available in the selected repo.
This commit adds a new variable to ceph-common called
'upgrade_ceph_packages' which defaults to False.  This variable is used
in the package installation resources for ceph packages to determine if
the resource should use "state=present" or "state=latest".  If the
variable gets set to True, "state=latest" will be used.
Additionally, we update rolling_update.yml to override
upgrade_ceph_packages to true to permit package upgrades in this
context specifically.
Closes issue #506

Control when ceph packages get updated

---

roles/ceph-common/tasks/main.yml

We have a requirement to install the packages first without
configuration. These tags should allow us to target the tasks need to do
that.

Adds a package-install tag to all installation tasks

---

roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-restapi/tasks/docker/fetch_configs.yml
roles/ceph-rgw/tasks/docker/fetch_configs.yml
site.yml.sample

to avoid warning from ansible v2. works for both `1.9.4` and `2.0.0.2`.

ceph-common: replace 'sudo' by 'become'

---

roles/ceph-common/tasks/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/scenarios/osd_directory.yml
roles/ceph-restapi/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/pre_requisite.yml

At the moment, all the tasks using the file module are duplicated to have differents ownerships depending on the fact `is_ceph_infernalis`.
The goal of this commit is to have a new logic for this:
- First set facts depending on the `is_ceph_infernalis` fact
- Create the files or directories using the setted facts as ownerships.
There will be less evaluations of the concerned tasks.

Refact code using `set_fact` to handle 'legacy' versions

---

.gitignore
Vagrantfile
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/fetch_configs.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/fetch_configs.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml
site-docker.yml.sample
vagrant_variables.yml.sample

run containerized daemons in virtual machines.
to enable it simply do:
`cp site-docker.yml.sample site-docker.yml`
and set `docker: true` in `vagrant_variables.yml`

ceph-ansible: allow to run containerized daemons

---

roles/ceph-rgw/tasks/docker/pre_requisite.yml

ceph-rgw: fix docker typo

---

roles/ceph-common/tasks/main.yml

Currently deploying a MON fails with "bad symbolic permission for mode"
errors due to the file/directory modes not being interpreted as octal
values.  This commit updates roles/ceph-common/tasks/main.yml to set
the file/directory modes to strings so they can be interpreted
correctly.
Closes issue #525

Change modes to string values

---

roles/ceph-common/tasks/checks/check_system.yml

use the builtin variable to check the ansible version

use the ansible_version variable

---

Vagrantfile
group_vars/osds.sample
roles/ceph-osd/defaults/main.yml

use ceph_osd_docker_devices and not ceph_osd_docker_device

ceph-osd: docker: fix type

---

Vagrantfile

RGW and Client VMs were sharing a network range, causing vagrant
failure.  Bump the RGW range to the next value.
Note that this needs to be applied to the docker branch as well.

Allow RGW and client VMs together

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

While this is not widly used (AFAIK :p) the feature was broken. Thanks
to @zmc for reporting it. You can now set `osd_auto_discovery` to
true in your group_vars/osd and it will go through all the devices
available and will make them OSDs.

ceph-osd: fix the auto discovery scenario

---

roles/ceph-osd/tasks/check_devices.yml

the parted command wasn't getting the devices properly and the partition
count is not necessary.

ceph-osd: fix the autodiscovery osd scenario

---

roles/ceph-common/tasks/main.yml

This fails for me with "ERROR! no action detected in task" otherwise.
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
The error appears to have been in '/etc/ansible/include/ceph-ansible/roles/ceph-common/tasks/main.yml': line 149, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: generate ceph configuration file
^ here
```

ceph-common: use explicit action syntax for config_template

---

.gitignore
group_vars/agent.sample
roles/ceph-agent/LICENSE
roles/ceph-agent/README.md
roles/ceph-agent/defaults/main.yml
roles/ceph-agent/meta/main.yml
roles/ceph-agent/tasks/main.yml
roles/ceph-agent/tasks/pre_requisite.yml
roles/ceph-agent/tasks/start_agent.yml
roles/ceph-agent/templates/ceph_agent.j2
site.yml.sample

This implements the `ceph-agent` role which allows remote nodes to register with a Calamari master server by configuring salt to talk to a master server.
It tries to follow the same conventions as the other roles, hopefully I didn't miss anything!

rhscon (storage agent)

---

site.yml.sample

Mainly because some packages are still not there for upstream which will cause
it to break installs that would otherwise would succeed
Should fix issue #545

separate the agent so it doesn't break standard installs

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml

based on the os memory we calculate the value for vm.min_free_kbytes
we don't go over 4GB of memory, even for systems with more than 48GB of RAM.

ceph-common: calculate vm.min_free_kbytes

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

We have a use case where we won't be configuring mons and osds in the same call, so we want to allow the playbook to run and only check for variables when absolutely necessary. For example, there is no need to check ``journal_size`` when only configuring a mon.

adds some more --package-install tags; make check_mandatory_vars more specific

---

osd-configure.yml
roles/ceph-fetch-keys/LICENSE
roles/ceph-fetch-keys/README.md
roles/ceph-fetch-keys/defaults/main.yml
roles/ceph-fetch-keys/meta/main.yml
roles/ceph-fetch-keys/tasks/main.yml

This is a simple role that connects to monitors and downloads all the ceph keys into the local ``fetch_directory``. We use this so that we can add a new OSD to an existing cluster without the need to run ceph-common or ceph-mon against all of our monitors again. The existing monitors must exist in the ``mons`` group in your inventory so that the ceph.conf is created correctly for the new OSD.
Also adds a simple playbook for adding an OSD to an existing cluster.

Adds a new role, ceph-fetch-keys

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_firewall.yml

The firewall checks can fail for any number of reasons -- e.g., the
ceph cluster hostnames are unresolvable from the ansible host, or the
ports are filtered by some intermediate hop, etc. Make two changes to
make those checks better:
* Set pipefail when running the checks, so if nmap itself fails the
command will be marked as 'failed'. Specifically, this fixes the
case where the hostnames cannot be resolved.
* Add a new variable, check_firewall, which can be used to disable
checks entirely. Specifically, this fixes the case where some
intermediate firewall filters the ports, so nmap returns "filtered".

Improve firewall checks

---

roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_iso_install.yml

For .iso-based install only.
Ensure that contents of /etc/fstab are ALWAYS valid at boot time, no matter what.  Otherwise Linux will not boot at all.  I discovered this the hard way.  The ansible mount module left an entry in fstab even after I unmounted, and that mount option did not work at boot time.  I had to PXEboot to rescue mode to figure out why - Linux hung immediately after the grub entry was selected.  Only explanation I had was that the "passno" field of /etc/fstab record was set to 0, and apparently it tried to mount the .iso before root fs was mounted, very strange but legal. So this fix has multiple defenses against this kind of thing ever happening again.  We make mount entry "noauto" so it won't even attempt mount at boot time.  We make "passno" field 2 instead of 0 (why …

make sure /etc/fstab is always valid at boot time no matter what

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

Installs on RHEL with ceph_origin set to distro previously would fail
because no packages would get installed, but all of the checks passed
fine. This adds support for ceph_origin: distro, simply installing the
packages using yum/dnf and assuming that the sysadmin has provided a
repository containing them.
This also supports the use case where Satellite or a similar local
mirror is in use, and the admin does not or cannot use the additional
repositories the role would otherwise add.

Make RHEL installs honor ceph_origin: distro

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/openstack_config.yml

Previously, creating pools was skipped if cephx was disabled; instead,
we should only skip key creation if cephx is disabled, and create
pools any time openstack_config is true.

Fix openstack config skipping

---

roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml

Skip a number of ceph keyring-related tasks (or remove the keyring
portion of some tasks) when cephx is disabled. Specifically, avoid
generating the initial keyring, which only clutters up the ansible
repo if cephx is not in use.

Skip keyring tasks when cephx is disabled

---

roles/ceph-common/templates/redhat_storage_repo.j2

While doing RGW install using ceph-ansible with RHCS .iso image, I saw that ceph-radosgw RPM install step was failing, it is packaged in this Tools subdirectory of the .iso image.   This change adds the Tools subdirectory into /etc/yum.repos.d/ceph.repo.

help RGW install from RHCS .iso

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml

re-use the logic introduced in #512 for the ceph directory and the
`ceph.conf` file.

ceph-common: use saner defaults for ceph dir

---

group_vars/mdss.sample
group_vars/osds.sample
group_vars/rgws.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/pre_requisite.yml

This commit allows you to set a new variable to 'true' if you want to
have ceph admin key copied over different kind of hosts such as MDS,
OSD, RGW. To enable this just set `copy_admin_key` to true.
Closes: #555

ceph-: abitlity to copy admin on all the nodes

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml

If using another method to generate a consistent fsid, then we can
skip creation of an (unused) cluster UUID file. If cephx is disabled
as well, we can skip creation of the fetch directory entirely.
Skipping fetch directory creation when cephx is disabled requires #568 to be merged as well.

Add option to skip generating fsid

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

These three commits add a number of useful tunables for the ceph.conf template.

Use object map for xattrs with ext4

---

roles/ceph-common/tasks/main.yml

0644 should never be a directory mode. 1777 makes it so that any user
can create a ceph client, not just root. (This is helpful if, for
instance, nova-compute is running as non-root.)
I'm not entirely sure this is the right fix, but it works for me, and 0644 is plainly wrong.

Fix pre-infernalis RBD client directory mode

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

When autodiscovering disks, disks can be skipped if either they are
removable, or if they have partitions on them. Skipped actions have no
'rc' attribute, though, so the 'ceph prepare' conditional fails unless
we first check to ensure that the results were not skipped before
checking the return value.

Do not prepare skipped disks

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

We want this to enable testing with existing teuthology jobs.
https://github.com/ceph/teuthology

Optionally install ceph-test

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

this commit introduces the ability to use fqdn for mon/mds name while
generation the ceph.conf file from the template.
Simply turn mon_use_fqdn and or mds_use_fqdn to true to use FQDN.
closes: #565

ceph-common: allow usage of fqdn for mon/mds

---

roles/ceph-fetch-keys/meta/main.yml

ceph-fetch-keys: add dependencies flag to galaxy

---

purge-cluster.yml

purge-cluster.yml blows up for me on expression "osd_group_name in group_names".  This seems to be because it isn't reading roles/ceph-common/defaults/main.yml which defines osd_group_name.  By explicitly calling out ceph-common role I was able to work around this, but how does site.yml work then?
Also, it ignores rgws role so I tried to add that in, it gets farther but does not yet remove RPMs from rgws hosts, probably doesn't shut down services.
If you need one of these two fixes but not the other, let me know and I'll push separate PR.

extend to handle rgws, read in ceph-common defaults

---

roles/ceph-rgw/tasks/openstack-keystone.yml

ceph-rgw: install libnss3-tools for keystone

---

roles/ceph-osd/tasks/scenarios/osd_directory.yml

On systems with systemd enabled, "systemctl start ceph" does not work. It instead needs to be "systemctl start ceph.target". This takes that into account.

Use ceph.target if available

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/main.yml

Make the checks pass when you want to do a 'distro' install of RHCS.
Move ``get_rc_ceph_version`` into ``ceph-common/tasks/main.yml`` so it won't be skipped if you're wanting to configure a RHCS node without installing packages. Meaning you've passed ``--skip-tags package-install`` to your ansible-playbook command.

fixes for installing / configuring red hat ceph storage

---

roles/ceph-rgw/tasks/pre_requisite.yml

this is handled by the task after.

ceph-rgw: remove leftover for service activation

---

roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml
roles/ceph-common/tasks/main.yml

The packages aren't released yet, but this enables us to install them on Ubuntu when they are released.

support for the jewel version of red hat ceph storage on ubuntu

---

group_vars/mons.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/calamari.yml
roles/ceph-mon/tasks/main.yml

This enables monitors to have the "rest api" provided by `calamari-server`. It lives in the `ceph-mon` role because it requires to live where the monitors are.
Reference BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1305259

Allow to install the calamari-server on monitors

---

purge-cluster.yml

The problem with only doing "get osd numbers" task for OSD hosts is that subsequent tasks iterating on the "osd_ids" register variable will fail for non-OSD hosts, such as task "stop ceph-osd with systemd".  You would think that the when clause would be sufficient to prevent this problem, but it does not.  By defining "osd_ids" for all hosts (empty for non-OSD hosts), we avoid this problem.
The "ls" command will fail for non-OSD hosts (or for OSD hosts that have already been purged), but it's ok, return status from entire command is zero.

fix purge-request.yml so non-OSD hosts will not fail

---

roles/ceph-osd/tasks/activate_osds.yml

Currently we don't yet support runnings OSDs w/ selinux in
enforcing mode. Thus its better to ensure that ceph-ansible
explicitly makes selinux permissive. This should help in
scenarios such as hyperconverged where OSDs are colocated
with VMs on compute nodes which needs selinux enforcing, but
OSDs don't.
Signed-off-by: Deepak C Shetty <deepakcs@redhat.com>

ceph-osd: Set selinux to permissive

---

roles/ceph-common/tasks/installs/install_on_debian.yml

This should allow to not install ceph-mds on Debian platforms when it is not required.
Fixes #547

Install ceph-mds on Debian platforms only if mds_group_name is set

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

add libselinux-python as dependency pkg for centos

---

roles/ceph-rgw/tasks/pre_requisite.yml

* `/var/run/ceph/rbd-clients` is not created automatically
* because it is missing, ceph-rgw complains about missing client
socket on start up; it is because the containing directory is
not there
* so we just add it to the list of directory pre-requisite

Create the directory used for rbd-clients sockets

---

roles/ceph-rgw/tasks/start_radosgw.yml

* the client-name is actually `rgw.{{ ansible_hostname }}` instead
of just `{{ ansible_hostname }}`
* it matches the directory created under `/var/lib/ceph/radosgw`
* and, it matches the client-name used to create the keyring in
`pre_requisite.yml`

Address issue #632 with systemd unit rename

---

roles/ceph-osd/tasks/activate_osds.yml

Since we want to activate the OSD when it's a partition we are looking
for a return code that is equal to 0 which means the device is a
partition.
Thanks @dvusboy
closes: #636

ceph-osd: fix activate for osd on partitions

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-common/templates/client_restapi_address.j2
roles/ceph-common/templates/client_restapi_interface.j2
roles/ceph-common/templates/mon_addr_address.j2
roles/ceph-common/templates/mon_addr_interface.j2

This would allow users who don't know what interface to provide to
give an IP address to use for the monitor instead.
Note: the includes are needed in ceph.conf.j2 because without them
jinja2 can not properly evaluate the template and will complain about a
missing 'ansible_interface' variable. The includes allow the template to
be evaluated correctly and then the correct include will be used during
render time.

Provide the ability to provide monitor_address instead of an interface

---

purge-cluster.yml

This change has multiple enhancements:
- no longer uses ceph-common role
- works around open RHEL7.2 bz 1312676 that prevents removal of /var/lib/ceph/osd/* mountpoints after all OSDs are unmounted
Sorry this has multiple fixes in it, if necessary I can separate them out into separate PRs.  But I can now run this sequence as many times in a row as I want and it will come up clean every time with Hammer (RHCS 1.3.1) on RHEL7.2.
To eliminate ceph-common dependency, I had to eliminate the dependency on is_ceph_infernalis fact, which is generated inside roles/ceph-common/tasks/main.yml .  To do this, the "are we using systemd" task counts native systemd unit files and we use this fact instead.
To finish deleting /var/lib/ceph/osd/* mountpoints, unfortunately it is necessary to reboot the OSD …

make purge-cluster.yml both more reliable and faster

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

Some versions (?) of libvirt provide a 'libvirt' group instead of
'libvirtd'. (Observed with libvirt-daemon-1.2.17-13.el7_2.2.x86_64.)
This makes the RBD client directory owner and group configurable to
allow for this.

Make RBD client directory owner/group configurable

---

group_vars/osds.sample
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/scenarios/bluestore.yml

With Jewel comes a new store to store Ceph object: BlueStore. Adding an
extra scenario might seem like a useless duplication however the
ultimate goal is remove the other roles later. Thus this is easier to
add new role instead of modifying existing one. Once we drop the support
for release older than Jewel we will just remove all the previous
scenario files.

ceph-osd: add support for bluestore

---

roles/ceph-common/tasks/checks/check_firewall.yml

ceph-common: use variable rgw_group_name instead of hard coded group name `rgws` when checking rgw port.
Signed-off-by: runsisi <runsisi@hust.edu.cn>

ceph-common: use variable rgw_group_name instead of hard coded group name 'rgws'

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

ceph.conf file generation task in ceph-common role was getting failed
because it ansible cant find defination of varriable mon_containerized_deployment_with_kv
This fix declare mon_containerized_deployment_with_kv under ceph-common/defaults/main.yml which fixes this issue
Signed-off-by: ksingh7 <karan.singh731987@gmail.com>

ceph-common: Fix for issue no. 652

---

roles/ceph-common/templates/ceph.conf.j2

ceph.conf.j2 template requires a new line between mon_containerized_deployment_with_kv and fsid variables. With this commit , i have added a new line for better readablity

ceph-common: Newline separation in ceph.conf.j2

---

roles/ceph-rgw/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/start_radosgw.yml

now rgw can be enabled.
closes: #642 #261

ceph-rgw: fix rgw enable with systemd

---

group_vars/all.sample
purge-cluster.yml
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-mon/tasks/secure_cluster.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-osd/tasks/scenarios/bluestore.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml
roles/ceph-osd/tasks/scenarios/osd_directory.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml
roles/ceph-restapi/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/start_radosgw.yml

we now have the ability to enable the `cluster` variable with a specific
value that will determine the name of the cluster.

ceph: implement cluster name support

---

roles/ceph-mon/tasks/ceph_keys.yml

We unnecessarily wait for `/etc/ceph/{{ cluster }}.client.admin.keyring` to be created when `cephx: false` is set in `group_vars/all ` which causes this task to timeout resulting in an abort. 
Adding a `when: cephx` clause fixes this.

Added when: cephx to prevent waiting on keyring with cephx: false

---

roles/ceph-mon/tasks/ceph_keys.yml

Certain daemons will not start because of the wrong permissions.

ceph-mon: fix ceph keys permissions

---

ceph-aio-no-vagrant.sh
install-ansible.sh

Vagrant will not always be available everywhere, sometimes we want to
bootstrap a ceph on a virtual machine. This script will help you
bootstrapping a ceph cluster from a development branch only.
So you can run it like this: ./ceph-aio-no-vagrant.sh v10.1.0
To get the v10.1.0 version installed. If the first argument ($1) is
empty then master will be used in consequence.

misc: add a script for vm test env

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

We now set the value to 0, which means no specific default; ceph will
use size-size/2

ceph-common: let ceph handle pool_default_min_size

---

roles/ceph-mon/tasks/docker/create_configs.yml

As written, generating the config file for ceph-mon in Docker yielded:
ERROR: config_template is not a legal parameter in an Ansible task or
handler
This fixes that error condition.

Fix mis-use of config_template in docker tasks

---

roles/ceph-common/tasks/main.yml

This change deals with case where /etc/sysconfig/ceph doesn't already exist.  I ran into this while installing RHCS 1.3.1 iso image.  Perhaps later RPM versions create this file for you?  But the install errored out because of this.

create /etc/sysconfig/ceph if it doesn't already exist

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

This pull request is a cleaner (I hope!) commit for the issues discussed in PR 651, which should be closed.    The important thing is that the old code was in effect evaluating "ceph_stable_rh_storage and ceph_stable" but these should not both be true.  The new code changes the "and" to an "or".  This code was tested by installing with RHCS 1.3.1 .iso and 1.3.2 .iso.    It would be nice if there was a way to factor out the common when clause expression used here, but other than "set_fact" I can't think of one.

fix when clauses for installation of ceph RPM

---

rolling_update.yml

This update has the following changes for the rolling update playbook.
1. Change how sysvinit ceph is determined to be enabled
For mons, the playbook checks if sysvinit is enabled by trying to
stat /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/sysvinit [1].
However, that file is not created when a monitor is configured to
use sysvinit, instead, Ansible's service module is used [2]. Ansible
2.0 can verify if a service is enabled and does this by checking for
a glob, in this context it would be '/etc/rc?.d/S??ceph' [3]. Because
Ansible 1.9 does not support this feature, this change updates
rolling_update.yml by checking if sysvinit is enabled by having stat
glob for the same pattern and following the symlink. This is done only
for the mons.
2. Change how sysvinit ceph is restarted
The …

sysvinit changes to rolling update playbook 

---

roles/ceph-common/templates/ceph.conf.j2

This fixes a bug where monitor_interface might be set in your inventory
file and not by using group_vars or --extra-vars causing the template to
use the default address of 0.0.0.0 instead of the defined
monitor_interface.

look at monitor_interface in hostvars when choosing interface or address

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/main.yml

Instead of creating the RBD client socket path three different places
in three different ways, this creates it once. Ceph on OpenStack users
have the option to customize the permissions of the RBD client
directories.
Fixes #687

Deduplicate RBD client directory creation

---

roles/ceph-osd/tasks/activate_osds.yml

if ceph-disk fails to activate an OSD then bubble up the error

---

cluster-maintenance.yml

In cluster-maintenance.yml, the third of occurrence of &lt;your_host&gt; didn't have a closing tag. This is a tiny change to add the the missing '&gt;'. 
This will let people quickly update this file with sed. For example: `sed s/\<your_host\>/192.168.1.41/g -i cluster-maintenance.yml`.

Balance tags on <your_host

---

purge-cluster.yml

The task "check for a device list" causes non-OSD hosts to be skipped by purge-cluster.yml.  This task is making sure that purge-cluster is not applied in the case of osd_auto_discovery: true without devices var being defined.  The problem is that the when clause can only be evaluated in the context of the OSD role, since "devices" and "osd_auto_discovery" vars are defined in group_vars/osds .  This change restricts the task to only operate in the OSD role.  I tested with both my 8-host cluster and with a CI-like single-node cluster running ceph_stable Infernalis.
It would be nice if the fail action could apply to all hosts, since this seems to be the intent, but I don't know how to do that.  At least the user can now re-run the purge-cluster.yml after correcting the vars as requested, …

purge-cluster - fix osd_auto_discovery check

---

plugins/actions/_v1_config_template.py
plugins/actions/_v2_config_template.py

These changes address 2 issues:
* The config template plugin in v1 mode was not respecting a list
of integers and would cause a stacktrace because the ConfigParese
module expects everything written to be a string.
* The config template plugin in v2 mode was not properly handingly
the multi-string-op type due to an oversight in the ``_option_write``
method.
With these updates the config template is now able to better support
all of the potential options that could be thrown at it when writing
an INI config file.
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

Update the config_template plugin

---

roles/ceph-common/templates/ceph.conf.j2

This fixes https://github.com/ceph/ceph-ansible/issues/711

Check to see if hostvars[host]['monitor_interface'] is defined

---

roles/ceph-common/templates/ceph.conf.j2

This fixes the ceph.conf template so that it will look for an inventory
defined value for monitor_interface or for monitor_interface defined in
a group_vars file.

correctly set mon addr when monitor_interface is defined in group_vars

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Introducing a new config option: `radosgw_civetweb_bind_ip` which points
to the `ansible_default_ipv4` by default. You can override this
variable. Use ansible facts to put a proper value.

ceph-rgw: ability to bind civetweb on an IP

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

Changing these defaults will ensure that the rbd_client_directories are being created by default and will avoid the following warning when running ceph commands:
2016-04-19 15:20:05.128327 7fc0e4033700 -1 asok(0x7fc0dc001680)
AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen:
failed to bind the UNIX domain socket to
'/var/run/ceph/rbd-clients/ceph-client.admin.20455.140466301441968.asok':
(2) No such file or directory
See: https://bugzilla.redhat.com/show_bug.cgi?id=1328594

change defaults for rbd_client_directories and rbd_client_admin_socket_path

---

.gitignore
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml

These reference ceph_mon_docker_username instead of the corresponding one. Fixes #723

Modifies docker image variable being referenced

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

This is needed in order to make ceph-disk work. Fixes #730

bind-mounts /dev in osd containers

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

This will allow a user to conditionally install the ceph package on rpm
based systems. Installing this package is not required or wanted in
versions passed infernalis.

Adds a use_server_package_split var

---

Vagrantfile
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/main.yml
vagrant_variables.yml.openstack

These were the changes I had to make to get things to work on my OpenStack VMs with the rhcs docker image.   In the case of the Vagrantfile change, there is already a conditional that sets OSVM based on the box and that defaults to false so I am using OSVM to set the ceph_docker_on_openstack variable.  In the case of the roles/ceph-osd/tasks/docker/main.yml, this change is necessary in new VM creation cases to make sure that dirs_permisssions.yml is run before the fetch because dirs_permissions creates the directories that we are copying into as part of the fetch.  The roles/ceph-restapi/tasks/docker/dirs_permissions.yml change is to use the same logic to set the ceph version fact as we do in all the other roles.  The logic that was there did not work for me.

docker: fixes for OpenStack VMs

---

purge-cluster.yml

I got burned when I upgraded to RHCS 1.3.2 .iso image because old image still remained in /tmp/rh-storage-repo and so ceph-ansible skipped the step of copying from the (new) .iso image to /tmp/rh-storage-repo.   This fix clears out the old contents of /tmp/rh-storage-repo to ensure that new .iso image really gets used.

cleanup /tmp/rh-storage-repo so newer repos are actually installed

---

Vagrantfile
vagrant_variables.yml.atomic
vagrant_variables.yml.openstack
vagrant_variables.yml.sample

When running via Vagrant, rather than always starting RESTAPI on each
monitor, make it optional via a configuration option in
vagrant_variables.yml.

Allow RESTAPI to be optional

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

Since developement versions of Ceph are after infernalis a package split
happened. So basically ceph-mon, ceph-osd, ceph-mds need to be
installed.

ceph-common: install ceph-mon/osd for ceph dev

---

take-over-existing-cluster.yml

Introducing a playbook helper to control a ceph cluster that was not
deployed with ceph ansible.
The procedure is rather simple. If the cluster was deployed with the
following project there won’t be any issue:
* Ceph Deploy
* Puppet Ceph
* Chef Ceph
* Any other deployment tool that relies on ceph-disk
The procedure comes as fellow:
1. Install Ansible and add your monitors and osds hosts in it. For more
detailed information you can read the Ceph Ansible Wiki
2. Set  generate_fsid: false in group_vars
3. Get your current cluster fsid with ceph fsid and set cluster_fsid
accordingly in group_vars
4. Run the playbook called: take-over-existing-cluster.yml like this
ansible-playbook take-over-existing-cluster.yml.
5. Eventually run Ceph Ansible to validate everything by doing:
ansible-playbook …

take over an existing cluster with ceph ansible

---

purge-docker-cluster.yml

Also checks for the existence of gdisk and installs if necessary. fixes #727

docker: use ceph_docker_osd_devices variable for purging docker cluster

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/install_on_debian.yml

This adds support to allow the install of Ceph from the
Ubuntu Cloud Archive.  The Ubuntu Cloud Archive provides newer
release of Ceph than the normal Ubuntu distro repository.
Signed-off-by: Samuel Matzek <smatzek@us.ibm.com>

Add support for install from Ubuntu Cloud Archive

---

roles/ceph-common/tasks/facts.yml
roles/ceph-osd/tasks/scenarios/osd_directory.yml

The ceph-osd role currently uses ansible_service_mgr, which is a fact
only available on ansible 2.x and greater.  This commit sets a similar
fact called init_system which will store the contents of /proc/1/comm
(systemd, init, etc.) and then references it ceph-osd instead.
Closes #741

Set init_system fact and reference in ceph-osd role

---

roles/ceph-osd/tasks/activate_osds.yml

If the ceph cluster name includes numbers, the grep used to find the OSD
IDs from /var/lib/ceph/osd/ would also return the numbers that were in
the cluster name.
For example, if the cluster was named 'mine123' and there was only one
OSD on the node, then the task that finds the OSD IDs would return
'123' and '0'.

Get the correct OSD ID when the cluster name includes numbers

---

install-ansible.sh

Merge both lsb_release and /etc/redhat-release cases.
Also testing if epel is already installed or not.

install-ansible: refactor install on Red Hat

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/facts.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
roles/ceph-rgw/tasks/start_radosgw.yml
tests/inventories/single-machine.yml

This adds a helper fact that uses the ``init_system`` fact to determine if we should be using systemd to control services or not.

Adds an use_systemd fact

---

install-ansible.sh

We just add epel to conviently install Ansible. However we don't keep it
as it could disrupt ceph's installation and dependancies.

install: remove epel

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

We kinda ommitted this package, now Jewel is out and the metadata server
is considered as stable.

ceph-common: install ceph-mds package

---

group_vars/all.sample
install-ansible.sh
roles/ceph-common/defaults/main.yml

1. Just a small one to make it work with Linux Mint
2. I would like to see the swap enabled by default to guarantee a better resilience. Instead of turning swap completely of the way to go for better performance is to decrease vm.swappiness

Make install-ansible.sh work with Linux Mint and enable swap by default but decrease vm.swappiness

---

README.md
group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Since ##461 we have been having the ability to override ceph default
options. Previously we had to add a new line in the template and then
another variable as well. Doing a PR for one option was such a pain. As
a result, we now have tons of options that we need to maintain across
all the ceph version, yet another painful thing to do.
This commit removes all the ceph options so they are handled by ceph
directly. If you want to add a new option, feel free to to use the
`ceph_conf_overrides` variable of your `group_vars/all`.
Risks, for those who have been managing their ceph using ceph-ansible
this is not a trivial change as it will trigger a change in your
`ceph.conf` and then restart all your ceph services. Moreover if you did
some specific tweaks as well, prior to run ansible you should …

ceph-common: purge ceph.conf file

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/install_on_debian.yml

Add support to allow ceph-ansible to install and
configure Ceph on Debian on the ppc64le architecture.
Canonical has ppc64le Debian packages in Ubuntu distros
and on Ubuntu Cloud Archive.  Both of which can be installed
and configured using the 'distro' or 'uca' options in
ceph-ansible when this patch is used.
Signed-off-by: Samuel Matzek <smatzek@us.ibm.com>

Add Debian ppc64le support

---

README.md

Highlight the variables that were used prior to this path:
https://github.com/ceph/ceph-ansible/pull/694

ceph-common: update the README for purge config

---

roles/ceph-common/tasks/main.yml

In ceph version 10.2.1 a bug was fixed that corrects the path:
https://github.com/ceph/ceph/commit/791eba81a5467dd5de4f1680ed0deb647eb3fb8b

fix the /etc/default/ceph path on debian when setting cluster name

---

README.md

Fix spelling of `contributing` and formatting of file path.
Signed-off-by: RJ Nowling <rnowling@gmail.com>

Fix some spelling, formatting in README

---

roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
roles/ceph-rgw/tasks/start_radosgw.yml

Instead use 'systemctl enable' to create the symlinks.
This fixes: https://github.com/ceph/ceph-ansible/issues/779

Do not create symlinks for systemd manually

---

roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

Fixes issue #780 
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=1335938

ceph-osd: fail when ceph-disk fails to prepare an OSD

---

roles/ceph-common/tasks/main.yml

Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1337320 that tries to install RH storage ISO on Ubuntu

ceph-common: remove RedHat-only constraint for RH ISO install

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

We want just the address for ansible_default_ipv4, not the entire
dictionary in ceph.conf.

fix the radosgw_civetweb_bind_ip default value

---

roles/ceph-osd/tasks/check_devices.yml

ceph-osd: fix typo when calling sgdisk second time around

---

roles/ceph-common/templates/redhat_storage_repo.j2

It is no longer a distinct repo in RH Storage.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1337305

ceph-common: redhat repo template: remove the Calamari reference

---

roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1337320

ceph-common: on rh storage on debian add the repositories and keys (ISO)

---

roles/ceph-common/templates/redhat_storage_repo.j2

Reference Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1338548

ceph-common: there is no Installer repo, it is now the Tools repo

---

roles/ceph-common/tasks/main.yml

ceph-common: fix ceph options default path again

---

roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
roles/ceph-common/tasks/main.yml

Before the repo configuration for ISOs for RH Storage was in a file that would be included only when:
- name: configure ceph yum repository
include: redhat_ceph_repository.yml
when: ceph_origin == 'upstream'
Which would not work for rh_storage. This PR normalizes using the same convention for install_rh_storage_on_debian to create a new install_rh_storage_on_redhat.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1339096

Include rh_storage repo/installs when specified

---

group_vars/all.sample

Change from "only supported on RHEL 7.1" to "only supported on RHEL >= 7.1" for RHS

Ambiguous "version is only supported on RHEL 7.1"

---

roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml

Solves regression when fixing https://bugzilla.redhat.com/show_bug.cgi?id=1339096

ceph-common: ceph-base is not part of rhstorage, remove it

---

group_vars/all.docker.sample
group_vars/rgws.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
roles/ceph-rgw/templates/ceph-rgw.service.j2

This will allow RGW to be started by systemd when it is an Atomic host environment.  This is what is done for OSD and MON.

docker: enable rgw container on Atomic host environment

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml

The scenarios were not being accurately compared to ensure that:
* A single scenario was choosen
* ONLY a single scenario was choosen
This solution does not scale for long, but that can be addressed in a
different patchset.

The when conditional was improperly being checked

---

roles/ceph-common/tasks/installs/install_rgw_on_debian.yml
roles/ceph-common/tasks/installs/install_rgw_on_redhat.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
roles/ceph-mon/tasks/docker/create_configs.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml

In order to align all Ansible versions, we now use the full path for the
template. We rely on `role_path` variable. Now all the tasks using
the template module have a uniform syntax.
Might fix issue raised in #483

ceph-common: uniformize template path calls

---

purge-cluster.yml

This commit removes /etc/yum.repos.d/rh_storage.repo file
for RedHat OS with RHCS ISO install during cluster purge

Fix for #819

---

roles/ceph-common/tasks/main.yml

Without the parenthesis it did not work with python3

- prepare for python3

---

group_vars/all.docker.sample
roles/ceph-common/tasks/docker/fetch_image.yml
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-restapi/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/main.yml

Docker makes it difficult to use images that are not on signed
registries.  This is a problem for developers, who likely won't have
access to a registry with proper signed certificates.
This allows the ability to use any docker image on the machine running
vagrant/ansible.  The way it works is that the image in question is
exported locally, then sent to each target box and imported there.

Allow running on local dev docker images

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

Currently, the ceph-ansible scripts fail when targeting Centos7 machines, due to the installation of yum-plugin-priorities, which forces older package dependencies (provided by default distribution repositories) to take precedence over newer ceph packages as provided by the ceph-release-{version}.noarch.rpm.  This is true even when setting the ceph yum repo priority=1.
See this [cautionary note](https://wiki.centos.org/PackageManagement/Yum/Priorities#head-38b91468cc607d0243f463489c2334bf40bfaaee) from the upstream maintainer of yum.
The error causes newer package versions from the ceph repository to be silently ignored in favor of older package versions from the default distribution repos.  The error looks like the following, repeated many times.
```
Error: Package: …
```

Remove Centos7 dependency yum-plugin-priorities

---

group_vars/all.docker.sample
group_vars/mdss.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-mds/templates/ceph-mds.service.j2

These changes are similar to what I did for RGW to allow it to run the containter on Atomic host environment with systemd

docker: enable mds container on Atomic host environment

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_firewall.yml
roles/ceph-common/tasks/main.yml

The check to see if nmap is available was being run on the remote host, whereas the checks to see if the applicable Ceph ports were open were being run as local_actions.
Also included are various related fixes now that the above functionality has been corrected (tested on Ansible 2.x only).
Closes: https://github.com/ceph/ceph-ansible/issues/754

Various fixes for check_firewall task

---

roles/ceph-mon/tasks/docker/create_configs.yml

The config template is in ceph-common, not in the individual roles, so
roles referencing it need to use playbook_dir, not role_path.

Put path back to playbook_dir for common template

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml

Similar to what it was done for `ice` versions. This will help for the upcoming new version, enabling the repositories for the configured version (defaulting to 1.3)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1346812

Enable rhcs repos according to the released version

---

roles/ceph-agent/tasks/pre_requisite.yml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1348130

ceph-agent: install the correct package for the agent in Ubuntu

---

Vagrantfile
vagrant_variables.yml.sample

Vagrant has the ability to download images from an arbitraty URL.  Add
this support to the Vagrantfile and vagrant_varables.yml

Add URL option to vagrant

---

roles/ceph-common/tasks/docker/fetch_image.yml

If the docker image cannot be retrieved we will fail this task silently and the playbook ultimately succeeds without a successful deployment. This change makes it so we fail the playbook immediately.

Fail when we cannot retrieve docker image

---

roles/ceph-common-coreos/tasks/install_pip.yml
roles/ceph-common-coreos/tasks/install_pypy.yml

Default directory is /opt/bin. On CoreOS by default there is no /opt directory.

Fix not creating pypy_binary_directory.

---

roles/ceph-common/tasks/facts.yml

init_system was getting the value of "systemd\n"
and was later compared to be equal to "systemd"
making the wrong scripts to be executed.
Signed-off-by: Alberto Murillo <alberto.murillo.silva@intel.com>

Trim init_system var

---

group_vars/all.sample
roles/ceph-common/README.md
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

Add the ability to use a custom yum repo, rather than just upstream,
RHEL, and distro.  This allows ansible to be used for internal testing.

Add a custom yum repo ability

---

roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_iso_install.yml

Fixes issue: https://bugzilla.redhat.com/show_bug.cgi?id=1338551

ceph-common: ensure that destination iso paths exist before copying

---

roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/templates/redhat_storage_repo.j2

Standardize on the name "Red Hat Ceph Storage" everywhere

ceph-common: fix "Red Hat Ceph Storage" product name

---

roles/ceph-common/templates/redhat_storage_repo.j2

As far as I can tell, this is a SUSE-ism, not needed for RHCS.

ceph-common: rm "type=rpm-md" from RHCS repos

---

roles/ceph-osd/tasks/scenarios/osd_directory.yml

Fixes an issue where the directory scenario of the ceph-osd role fails to detect systemd.
Previously, the "init_system" fact was used. In our deployments (CentOS 7), this fact contains a trailing newline. This change switches to the use_systemd fact. This appears to be more consistent with the rest of the project as well.
I believe this is the same issue as #585

ceph-osd: Use the use_systemd fact when starting directory-scenario OSDs

---

roles/ceph-osd/tasks/check_devices.yml

I'm installing Ceph on Ubuntu 16.04 with Ansible v2.0.2.0-1. OSD options include:
```
#devices:
osd_auto_discovery: true
journal_collocation: true
```
The disk items in combined_osd_partition_status_results.results look like this:
```
"item": [
{
"_ansible_item_result": true, 
"_ansible_no_log": false, 
"changed": false, 
"cmd": "parted --script /dev/nvme6n1 print > /dev/null 2>&1", 
"delta": "0:00:00.031631", 
"end": "2016-07-12 09:47:48.194265", 
"failed": false, 
"failed_when_result": false, 
"invocation": {
"module_args": {
"_raw_params": "parted --script /dev/nvme6n1 print > /dev/null 2>&1", 
"_uses_shell": true, 
"chdir": null, 
"creates": null, 
"executable": null, 
"removes": null, 
"warn": true
}, 
"module_name": "command"
}, 
"item": {
"key": "nvme6n1", 
"value": {
"holders": …
```

Use correct object names when zapping GPT header

---

roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_iso_install.yml

This will help if the path to the iso exists in the originating server but not
in the remote paths. This issue is not seen if using /tmp/file.iso but does
show up when using nested paths.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1355762

ceph-common: explicitly create the directory portion of the iso path

---

roles/ceph-mon/tasks/docker/create_configs.yml

The docker case wasn't able to generate an FSID, it required it to be
set.  Allow generating it.
The better solution (which is in my TODO list) is to factor these bits + config generation in ceph-common and have the docker case include the common case.  However, this is a downstream QE PR (https://bugzilla.redhat.com/show_bug.cgi?id=1356105) , so I'd like to get a fix in ASAP.

Allow generating FSID for docker

---

roles/ceph-common/tasks/main.yml

Because the ISO installs would happen later in the playbook.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1357065

ceph-common: skip default installs on redhat if ISO needs to be used

---

take-over-existing-cluster.yml

This fixes a bug where mons added to a "taken over" cluster
will get a newly generated key and do not join the cluster.
Resolves: rhbz#1357292

Fetch keys from the mons when taking over a cluster

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_ntp_debian.yml
roles/ceph-common/tasks/checks/check_ntp_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/ntp_debian.yml
roles/ceph-common/tasks/misc/ntp_redhat.yml

This fixes: #845 only for non-containerized deployments
1. As it stands we install ntp on all nodes and this will enable it on all nodes as well. Is it necessary on all nodes?
2. I filed a feature idea on ansible's packaging modules in order to simplify the task of querying for the state of a package across different package managers. It would've helped simplify this code.
3. Do we want to install and enable ntp on container hosts? If so, I will enable the containerized part pending the answer to question 1.

Add option to enable ntp

---

Vagrantfile
group_vars/all.docker.sample
group_vars/osds.sample
group_vars/rbd-mirrors.sample
roles/ceph-rbd-mirror/defaults/main.yml
roles/ceph-rbd-mirror/meta/main.yml
roles/ceph-rbd-mirror/tasks/docker/checks.yml
roles/ceph-rbd-mirror/tasks/docker/dirs_permissions.yml
roles/ceph-rbd-mirror/tasks/docker/fetch_configs.yml
roles/ceph-rbd-mirror/tasks/docker/main.yml
roles/ceph-rbd-mirror/tasks/docker/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/docker/selinux.yml
roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
roles/ceph-rbd-mirror/tasks/main.yml
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
vagrant_variables.yml.sample

add the ability to deploy a containerized version of the rbd mirror
daemon.

rbd-mirror: container deployment support

---

roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/misc/system_tuning.yml

The ceph-common role fails when you run ansible with --check. Adding
always_run to a few tasks makes the check go through easier (although
it's not foolproof).

Added support for --check flag in ceph-common

---

purge-docker-cluster.yml

This removes containers, container images, packages, configuration files
and all the data. Removal of container image tasks are tagged with
'remove_img' to skip removal if desired.

Add ability to purge containerized Ceph cluster

---

plugins/actions/_v2_config_template.py

This change allows keys in INI format to be any case.
The default ConfigParse module sets this to be lower
however in some cases keys are needed to be upper and/or
mixed.
Change-Id: I4e0dedb1b73ee596929bd425af6b0aaefd3a6c27
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
(cherry picked from commit https://github.com/openstack/openstack-ansible-plugins/commit/f946160dd0f370efb792bf084c7c20b18cf27c98)

Added option to support case-insensitive keys

---

roles/ceph-osd/tasks/check_devices.yml

Option `-g` of sgdisk is duplicated with `--mbrtogpt`, so lets remove it.
This fix #896
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>

sgdisk: remove duplicated option `-g`

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Journal size is not mandatory anymore, a default from 5GB is being
added. A simple warning message will show up if the size is set to
something below 5GB.

common: set journal size to 5GB

---

purge-cluster.yml

In the `purge rh_storage.repo file in /etc/yum.repos.d` task, there is a check for `ceph_stable_rh_storage_iso_install` which, in many cases, is undefined and will cause the playbook to fail.  Given that the task will only delete the repo if it is present there is no need to check `ceph_stable_rh_storage_iso_install`.

Fix purge-cluster.yml fail by removing unnecessary ceph_stable_rh_storage_iso_install check.

---

roles/ceph-mds/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-rbd-mirror/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/main.yml

Update each role's task to use the respective role's username, image
name, and image tag to check if a container is already running. This was
causing false failures because we were not matching any running
containers and subsequently running checks.yml to check the status of
cluster files being left behind.

Fix to check if cluster is running

---

roles/ceph-mon/tasks/secure_cluster.yml

Deployment fails when the ``secure_cluster`` is false:
TASK [ceph-mon : secure the cluster]
*******************************************
fatal: [saceph-mon.vm.ceph.asheplyakov]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'stdout_lines'"}
fatal: [saceph-mon2.vm.ceph.asheplyakov]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'stdout_lines'"}
fatal: [saceph-mon3.vm.ceph.asheplyakov]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'stdout_lines'"}
A conditional include evaluates all included tasks with the (additional)
conditional applied to every task [1]. Thus all tasks from `secure_cluster.yml'
are always evaluated (with an additional 'when: secure_cluster' condition).
The `secure the cluster' task iterates over …

ceph-mon: fix the loop in `secure the cluster' task

---

purge-cluster.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

The "purge yum cache" task that is in purge-cluster.yml doesn't work as designed.  `yum clean all` will only clean caches for installed repos.  Since purge-cluster.yml removes the repo before purging the cache, it does not remove the `Ceph` repo cache.  I tested putting the task before the yum erase that removes the repo, but yum rebuilds the cache just before removing the repo.  The only way to purge the yum cache for the `Ceph` repo is to move it to the install.yml so it purges the cache just after installing the repo but before it uses it.
I verified this worked correctly by purging and reinstalling several different versions of ceph on the same hardware.  Without the change the install will fail trying to install a chached version of ceph rpm's that don't exist in the currently …

Fix purge yum cache

---

roles/ceph-common/templates/ceph.conf.j2

Prior to this change, each ceph cluster node would end up with several `qemu-client-$pid.log` files owned by root. The `[client]` section would capture *all* client activity (for example the "`ceph health`" command, etc), not just librbd-in-qemu.
Restrict this section to libvirt clients only so that we don't generate these spurious log files for other Ceph client traffic.

ceph-common: client settings are for libvirt

---

purge-cluster.yml

In purge-cluster.yml the `request data removal` task has a local_action that tries to run as root (At least on OS X).  Fixed by hard coding `become: false`.
Other fixes while I was in the file:
- fixed some ansible2 variable warnings
- replaced shell `rm` with ansible `file/absent` module

Fix local_action Requiring Root and Various Small Fixes

---

purge-cluster.yml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1339576

purge-cluster: remove -q flag from grep to prevent broken pipes

---

Vagrantfile
vagrant_variables.yml.atomic
vagrant_variables.yml.sample

-rsync directory was hardcoded previously and did not reflect the default /vagrant rsync directory

Changes to allow for flexible rsync directory

---

group_vars/all.sample
group_vars/osds.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-journal-collocation.yml

* changed s/colocation/collocation/
* declare dmcrypt variable in ceph-common so the variables check does
not fail

osd: fix collocation spelling and declare dmcrypt variables

---

shrink-mon.yml
shrink-osd.yml

We now have the ability to shrink a ceph cluster with the help of 2 new
playbooks. Even if a lot portions of those are identical I thought I
would make more sense to separate both for several reasons:
* it is rare to remove mon(s) and osd(s)
* this remains a tricky process so to avoid any overlap we keep things separated
For monitors, just select the list of the monitor hostnames you want to
delete from the cluster and execute the playbook like this. The hostname
must be resolvable. Then run the playbook like this:
ansible-playbook shrink-cluster.yml -e mon_host=ceph-mon-01,ceph-mon-02
Are you sure you want to shrink the cluster? [no]: yes
For OSDs, just select the list of the OSD id you want to delete from the
cluster and execute the playbook like this:
ansible-playbook …

add shrink playbook

---

roles/ceph-common/templates/ceph.conf.j2

I'm not sure if this is the preferred fix, but this was blocking me on container deployments during ceph-mon's `generate ceph configuration file` task in `roles/ceph-mon/tasks/docker/create_configs.yml`. I kept getting the below error caused by #815:
> 'dict object' has no attribute u'ansible_interface'
I did see the warnings that were heeded in the conversation.  :)

Fix ceph.conf template for containerized deployment

---

roles/ceph-rgw/tasks/pre_requisite.yml

For pre-infernalis installation of ceph-radosgw from RPM, run 'chkconfig'
to ensure systemd's ceph-radosgw.service is created.
This fixes issue #843.

Fix pre-infernalis RPM installation of ceph-radosgw

---

site-docker.yml.sample

If we don't do this we won't be able to get the ip address of the docker
interface.

docker: gather all the fact

---

roles/ceph-common/templates/ceph.conf.j2
site-docker.yml.sample

- Gather facts only for mons before processing ceph-mon role serially in
containerized playbook sample
- Updated ceph.conf in order to generate a valid ceph.conf

Restrict fact gathering to mons and update ceph.conf

---

README.md

Trivial fix. Referenced file exists, but naming of the link was not consistent with the actual file on disk.

Correct naming of referenced file

---

infrastructure-playbooks/rolling_update.yml

rolling_update.yml will not work if cluster name is other than  'ceph'. Adding --cluster will solve this problem
Fixes issue #969

rolling_update.yml will not work if cluster name is other than ceph

---

infrastructure-playbooks/rolling_update.yml

Users have reported this task to hang. Since this command is not
required to perform the upgrade, we remove it.

rolling updates: remove mon compact command

---

roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml

this allows us to test devices set with persistent naming such as
/dev/disk/by-*

ceph-osd: get full link path when testing if a partition

---

group_vars/mons.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml

By overriding the openstack_pools variable introduced by this commit, the deployer may choose not to create some of the openstack pools, or to add new pools which were not foreseen by ceph-ansible, e.g. for a gnocchi storage backend.
For backwards compatibility, we keep the openstack_glance_pool, openstack_cinder_pool, openstack_nova_pool and openstack_cinder_backup_pool variables, although the user may now choose to specify the pools directly as dictionary literals inside the openstack_pools list.

Allow deployer to customize openstack pools

---

docker/Linode.dockerfile
docker/README.md

This Dockerfile is for setting up a dev environment for launching Ceph
clusters on Linode.

docker: add Dockerfile for Linode cluster dev env

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

This RHCS version is now generally available. Default to using it.
Related to https://bugzilla.redhat.com/1357631

group_vars: default to version 2 of RHCS

---

roles/ceph-common/templates/ceph.conf.j2

1) Remove duplication of "osd crush chooseleaf type = 0"
2) Add osd_pool_default_size = 1 for a single node deployment
Signed-off-by: Proskurin Kirill <kproskurin@mirantis.com>

Small fix in config template

---

Vagrantfile
vagrant_variables.yml.linode

This enables running multiple clusters concurrently in the same Linode
account. Linode does not allow machines to have the same label.

vagrant: add label_prefix setting

---

infrastructure-playbooks/rolling_update.yml

This commit introduces the ability to configure delays and retries for
cluster health checks, for both monitors and OSDs.

upgrade: add custom timeout options

---

infrastructure-playbooks/purge-cluster.yml

Prior to this change we were purging all the partitions on the device
when using the raw_journal_devices scenario.
This was breaking deployments where other partitions are used for other
purposes (ie: OS system).

purge: only purge ceph partitions

---

roles/ceph-osd/tasks/check_devices.yml

This task was failing because the array lengths didn't match up within the two arrays under with_together because the previous task reduced the first array.
`fatal: [hpc7873.eng.fireeye.com]: FAILED! => {"failed": true, "msg": "The conditional check 'item.0.rc != 0' failed. The error was: error while evaluating conditional (item.0.rc != 0): 'None' has no attribute 'rc'\n\nThe error appears to have been in '/home/musee/automatons/ceph-poc2/roles/ceph-osd/tasks/check_devices.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: fix partitions gpt header or labels of the journal devices\n  ^ here\n"}
`

Remove dupes in raw_journal_devices in a consistent manner

---

infrastructure-playbooks/purge-cluster.yml

- Separated out one large playbook into multiple playbooks to run
host-type by host-type i.e. mdss, rgws, rbdmirrors, nfss, osds, mons.
- Combined common tasks into one shared task for all hosts where
applicable
- Fixed various bugs

Reworked purge cluster playbook

---

infrastructure-playbooks/rolling_update.yml

we now have pointer to default role so we don't miss any of the
variables defined.

rolling_update: improve variables import

---

Vagrantfile
vagrant_variables.yml.atomic
vagrant_variables.yml.linode
vagrant_variables.yml.openstack
vagrant_variables.yml.sample

- All Ceph instances now communication using public subnet and
additionally OSDs communicate with each other using private cluster
subnet
- Workaround for
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/645
- Fix for #952 to avoid concatenated MAC addresses caused by
vagrant-libvirt bug.

Create separate subnet for public/cluster networks

---

vagrant_variables.yml.sample

As per the variable in Vagrantfile and vagrant_variables.yml.linode
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

vagrant_variables.yml.sample: vagrant_url should be vagrant_box_url

---

Vagrantfile
vagrant_variables.yml.atomic
vagrant_variables.yml.sample

Found a Vagrant box image for xenial that works well.  The ubuntu and bento ones don't include python by default and have other issues as well.  geerlingguy/ubuntu1604 image is the 2nd most popular one on the atlas repo with 144K downloads.  The developer looks pretty legit and has the code posted in his git repo.  @leseb is this image ok for us to use?
I've added code to create a SCSI controller as part of the vagrant provisioning.  This makes us a little less dependent on the controller the box has built in.  Also it means we can rely on the controller name being a constant.

Updated to use xenial by default.  Added OSD specific controller.

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-nfs/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

This is to address the problem I found in issue #1030, in cases where (for whatever reason) the CentOS `Extras` repo is not enabled.

Ensure extras repo enabled on CentOS

---

Vagrantfile
vagrant_variables.yml.linode
vagrant_variables.yml.sample

This was a holdout from the Linode merge that shouldn't have been
included. The right way to set the installation source is through
group_vars.

vagrant: use group_vars for ceph pkg source

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/rbd_pool.yml

Users reported that pool_default_pg_num is not honoured for the default
pool 'rbd'. So now we check the pg num value for the RBD pool and if it
does not match pool_default_pg_num then we delete and recreate it.
We also make sure the pool is empty first, just in case someone changed
the value manually and didn't reflect the change in ceph-ansible.
Closes: #992

mon: destroy and recreate rbd pool if necessary

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-nfs/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

Fix the problems caused by my previous attempt to make sure the `extras` repo is enabled on `CentOS`.
Signed-off-by: Adam Huffman <bloch@verdurin.com>

Change enabling of extras repo for CentOS to use ini_file

---

site.yml.sample

Some modern distros ship without python2 so we need to install it blindly,
before any module is run. Fedora > 23 also requires some aditional packages be
installed.
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

site.yml.sample: Attempt to install python2

---

infrastructure-playbooks/ansible.cfg

Fixing: https://bugzilla.redhat.com/show_bug.cgi?id=1388295
- Updates to allow running infrastructure-playbooks both from within its
directory or root directory of ceph-ansible.
Signed-off-by: Ivan Font <ifont@redhat.com>

Update for infrastructure-playbooks execution

---

roles/ceph-osd/tasks/pre_requisite.yml

Fixes issue #1041
Resolves: issue#1041

ceph-osd: use ini_file instead of yum_repository to enable Centos extras

---

infrastructure-playbooks/rolling_update.yml

see: https://bugzilla.redhat.com/show_bug.cgi?id=1389456
Resolves: rhbz#1389456

rolling_update: define mon_group_name when upgrading the mons

---

roles/ceph-osd/tasks/scenarios/dmcrypt-dedicated-journal.yml

Fixes: https://github.com/ceph/ceph-ansible/issues/1054
Signed-off-by: Andrew Schoen aschoen@redhat.com

raw_multi_journal is not required when using dmcrypt_dedicated_journal

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-common/templates/mon_addr_interface.j2

https://github.com/ceph/ceph-ansible/issues/1038

now you can use a network link name with a hyphen

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-common/templates/mon_addr_address.j2
roles/ceph-common/templates/mon_addr_interface.j2

This does a few things:
- adds back support for ``monitor_address``
- allows for mons to have differing values for ``monitor_address`` or ``monitor_interface`` defined in the inventory
- reformats for better readability and easier to understand diffs when the file changes

various fixes for the ceph.conf template

---

roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml

Even for dmcrypt we need to check the "devices" status and
"raw_journal_devices" as well so we can fix them if there is something
wrong with them.

osd dmcrypt: add ability to check devices

---

infrastructure-playbooks/rolling_update.yml

My stupid self removed this crucial variable here: 217ce3ca thinking it
was another hard coded variable import where this is actually the
trigger for the upgrade.
Closes: #1071

rolling_update: add variable to upgrade ceph

---

tests/functional/ubuntu/16.04/mon/initial_members/group_vars/all
tests/functional/ubuntu/16.04/mon/initial_members/hosts
tox.ini

This allows for the ansible-playbook command to be reused by each scenario in tox.ini. It's also a nicer way to define your vars than using --extra-vars, imho.

functional test scenarios should include a group_vars dir

---

plugins/actions/_v1_config_template.py
plugins/actions/_v2_config_template.py
roles/ceph-common/plugins/actions/_v1_config_template.py
roles/ceph-common/plugins/actions/_v2_config_template.py

ansible 2.2 deprecates first_available_file option which is used in
the config_template module by 'generate ceph configuration file' task.
This change syncs the config_module files from their master repository
in github.com/openstack/openstack/ansible-plugins which includes the fix
https://github.com/openstack/openstack-ansible-plugins/commit/2f6cac2cf6ddebf462e21c70da7f60fa334b5f1e
Signed-off-by: Alberto Murillo Silva <alberto.murillo.silva@intel.com>

sync config_template plugin with master branch

---

tests/functional/centos/7/mon-osd/group_vars/all
tests/functional/centos/7/mon-osd/hosts
tests/functional/centos/7/mon-osd/vagrant_variables.yml
tests/functional/ubuntu/16.04/mon-osd/vagrant_variables.yml
tests/functional/ubuntu/16.04/mon/vagrant_variables.yml
tox.ini

Long term we'd like to build our own vagrant boxes, but these should work for now and gives us a way to test integration with the CI.
This also provides a way tell tox that we want to use libvirt in the CI with:
```
tox -- --provider=libvirt
```

use vagrant boxes that support libvirt and virtualbox

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

backward compatibility for ceph-ansible version running latest code but
using variables defined before commit: 492518a2
Signed-off-by: Sébastien Han seb@redhat.com

common: backward compatibility name for rhcs

---

roles/ceph-rgw/tasks/pre_requisite.yml

We have a fact that detects the package manager, so we can detect if
systemd is used. Radosgw was still using some old logic from Ubuntu.
Ubuntu 16.04 now has systemd so we don't need to configure rgw as it was
running on upstart.

ceph-rgw: add systemd condition

---

infrastructure-playbooks/rolling_update.yml

Services are restarted twice on upgrades because of the restarts in the ``ceph-common`` role and at the end of the upgrade process by the ``rolling_update.yml`` playbook. This sometimes exposes a bug which leaves the OSD process running but not marked up.
See:
https://bugzilla.redhat.com/show_bug.cgi?id=1394928
https://bugzilla.redhat.com/show_bug.cgi?id=1391675
https://bugzilla.redhat.com/show_bug.cgi?id=1394929

rolling update: stop services before upgrading and start afterwards

---

Vagrantfile
tests/functional/centos/7/mon-osd-mds-rgw/vagrant_variables.yml
tests/functional/centos/7/mon-osd/vagrant_variables.yml
tests/functional/ubuntu/16.04/mon-osd-mds-rgw/vagrant_variables.yml
tests/functional/ubuntu/16.04/mon-osd/vagrant_variables.yml
tests/functional/ubuntu/16.04/mon/vagrant_variables.yml
vagrant_variables.yml.sample

And disable the sync folder on all the functional testing (optionally set on vagrant_variables.yml)

Use new ceph vagrant boxes

---

tox.ini

ceph-ansible is now fully compliant with ansible 2.2 so bumping the
ansible version to make we test the right things.

ci: bump ansible version to 2.2

---

Vagrantfile
vagrant_variables.yml.sample

This makes our libvirt boxes come up with the OS on /dev/vda and
three devices added at /dev/sd{a/b/c} so that we can ensure that
the OSD devices we want to use can always be available for
both virtualbox and libvirt for both xenial and centos7.

tests: make libvirt use the same device names as virtualbox

---

infrastructure-playbooks/rolling_update.yml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1395073

rolling_update: bump retries for osd_check/retries to 20 minutes

---

roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/misc/system_tuning.yml

Replaced Ansible 2.2 specific `check_mode: no` with backwards compatible `always_run: yes`

Replaced Ansible 2.2 specific `check_mode: no`

---

Vagrantfile

This will keep us from having name conflicts between our different
testing scenarios.

tests: sets random_hostname to true for libvirt nodes

---

.gitignore
Makefile
ceph-ansible.spec.in

`make rpm` will build a ceph-ansible RPM and place it in the current
working directory.
This will allow us to run this command in Jenkins for every branch.

add RPM packaging for CI

---

roles/ceph-osd/tasks/docker/fetch_configs.yml
vagrant_variables.yml.atomic

Ansible task was not properly fetching OSD cluster keyring causing
the keyring to be missing when we needed to authenticate. Similarly, we
were not properly waiting on the OSD keyring to be available before
continuing.
Signed-off-by: Ivan Font <ifont@redhat.com>

Fix error caused by missing OSD cluster keyring

---

infrastructure-playbooks/rolling_update.yml

Prior to this commit the serial variable was poorly documented. Now we
are making clear that this value should be left untouched as the rolling
update mechanism should happen serially.
Solves: bz-1396742

rolling_update: clarify "serial" usage

---

group_vars/all.docker.sample
infrastructure-playbooks/rolling_update.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-nfs/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-rbd-mirror/tasks/docker/main.yml
roles/ceph-restapi/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/main.yml

- Update rolling update playbook to support containerized deployments
for mons, osds, mdss, and rgws
- Skip checking if existing cluster is running when performing a rolling
update
- Fixed bug where we were failing to start the mds container because it
was missing the admin keyring. The admin keyring was missing because
it was not being pushed from the mon host to the ansible host due to
the keyring not being available before running the copy_configs.yml
task include file. Now we forcefully wait for the admin keyring to be
generated before continuing with the copy_configs.yml task include file
- Skip pre_requisite.yml when running on atomic host. This technically
no longer requires specifying to skip tasks containing the with_pkg tag
- Add missing variables to all.docker.sample
- Misc. …

Support containerized rolling update

---

roles/ceph-common/tasks/checks/check_ntp_atomic.yml
roles/ceph-common/tasks/checks/check_ntp_debian.yml
roles/ceph-common/tasks/checks/check_ntp_redhat.yml

As those task are only reading the installed packages and their output
is required in later tasks it is safe to run them also in check mode.

Make NTP checks usable with '--check'

---

roles/ceph-common/tasks/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-rgw/tasks/start_radosgw.yml

Adding a few `always_run: true` lines on tasks that execute reading operations to fill variables. Making it possible to run a `ansible-playbook --check` without running into errors on undefined variables.

Improve --check compatibility for ceph-common, ceph-mon and ceph-rgw roles

---

infrastructure-playbooks/shrink-mon.yml

The playbook will fail if only 1 mon is in the cluster
and advise to use the `purge-cluster` playbook instead.
Fix #1083

[shrink-mon]: force playbook to fail if there is only one mon

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

a397922 introduced a syntax error by attempting to default an unquoted
string, which causes execution failures on some ansible versions with:
Failed to template {{ ceph_rhcs_mount_path }}: Failed to template {{ ceph_stable_rh_storage_mount_path | default(/tmp/rh-storage-mount) }}: template error while templating string: unexpected '/'

Fix jinja defaulting syntax

---

contrib/push-roles-to-ansible-galaxy.sh

On certain git versions running: git pull origin --tags ends up with the
following error: It doesn't make sense to pull all tags; you probably
meant: git fetch --tags
So removing the --tags since later in the execution we do a git fetch
--tags

contrib: It doesn't make sense to pull all tags

---

roles/ceph-common/tasks/installs/debian_ceph_repository.yml

According to the official documentation, adding PPA is not available for Debian.

Add gluster nfs ganesha repo only for Ubuntu

---

roles/ceph-common/templates/httpd.conf

we recently dropped the support for apache with rgw, so this commit
removes the last remaining file.

common: remove apache file

---

infrastructure-playbooks/shrink-osd.yml

when the pid of osd is bigger than 9999, just like the follow 12860. the old regex pattern ` ':[0-9][0-9][0-9][0-9]\/[0-9][0-9][0-9][0-9]'` of  regex_replace filter  process 12860 will still left 0,and the 0 will append to host ip
```
[root@onest-4 /etc/ceph]#  ceph osd find 0
{
"osd": 0,
"ip": "20.1.1.95:6800\/12860",
"crush_location": {
"host": "onest-4",
"root": "default"
}
}
[root@onest-4 /etc/ceph]#  ps -ef |grep ceph-osd
ceph       12860       1  0 Nov21 ?        01:09:52 /usr/bin/ceph-osd -f --cluster ceph --id 0 --setuser ceph --setgroup ceph
root      162374  159422  0 13:49 pts/0    00:00:00 grep --color=auto ceph-osd
```
the 0 append to host ip while the real host ip is `20.1.1.95`
```
failed: [172.20.255.157] (item=20.1.1.950) => {"item": "20.1.1.950", "msg": "Failed to …
```

the pattern in regex_replace is not right when the pid of osd is bigger  than 9999

---

infrastructure-playbooks/take-over-existing-cluster.yml

Prior to this patch we were just looking for any *.conf file which
sometimes could results in multiple matches. The new command looks for a
.conf file that must contain [global] and 'fsid' patterns. This will
definitely get us the ceph.conf file. We can not directly use ceph.conf
because of a different cluster name.

take-over: use more precise ceph.conf detection

---

roles/ceph-mon/tasks/start_monitor.yml

Once the monitor process starts it will also trigger `ceph-create-keys`
which will collect the admin key and bootstrap keys. We used to force
this command because we were having issues on some distros like centos
7.0 and 7.1 not triggering this. This is fixed on centos 7.2 and not an
issue on ubuntu 14.04 or 16.04 so we can remove this task. If the
monitor hangs or fails to start the playbook will fail right after at
the "wait for client.admin key exists" task after 300sec.
Closes: #1161

mon: remove collect keys

---

roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/main.yml

This commit solves the situation where you lost your fetch directory and
you are running ansible against an existing cluster. Since no fetch
directory is present the file containing the fsid doesn't exist so we
are creating a new one. Later the ceph.conf gets updated with a wrong
fsid which causes problems for clients and ceph processes.
Closes: #1148

common: do not regenerate a cluster fsid if cluster exits

---

roles/ceph-common/tasks/facts.yml

mon_group_name variable can be used to override mons group, but
this task assumes the group is always 'mons'. So we need to use
the var to find the group name instead.

Fix the mons running check to use group name var

---

ceph-aio-no-vagrant.sh
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

- Add mon_pg_warn_max_per_osd, osd_pool_default_size and osd_pool_default_min_size variables
- Add option to configure default pool size
- Add option not to install MDS and RGW
- Improve ssh_setup to check if file and key already exist
- Improve populate_vars for safety rerun for idempotent
- Change path of inventory file to where ansible run. So this won't pollute the system
- Remove check host key
- Remove sudo when install Ansible

Improve script to install Ceph AIO without Vagrant

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

Removes gitbuilder references, and uses the new shaman redirects.
Note: DEB repos will not work correctly until https://github.com/ceph/chacra/pull/217 is deployed

Shaman support for `ceph_dev`

---

Makefile

Prior to this change, all RPMs would have a Version field that started with `v`, for example `ceph-ansible-v2.0.0-163.g2c98b1d.el7`
Strip the `v` out in these cases, so that the version is simply a number.
Also, ignore any tags that do not start with `v`.

Makefile: strip "v" from RPM versions, and improve version detection

---

roles/ceph-mon/tasks/ceph_keys.yml

If previous check was not run, .stdout_lines is not a valid key on the dictionary.
To get around this, use .get("stdout_lines") instead.
Also add in a default empty list

Change attribute call to .get call in ceph keys

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Only when ceph_origin == "upstream", install_on_redhat.yml will include
redhat_ceph_repository.yml, same as debian.
In redhat_ceph_repository.yml, ceph_custom_repo will be added.
But in check_mandatory_vars.yml, ceph_origin=="upstream" can't be combined
with ceph_custom

fix ceph_custom not usable

---

roles/ceph-agent/tasks/pre_requisite.yml

Because we shouldn't enforce where the agent is coming from as repos may be set from an ISO or local repo.
Resolves: rhbz#1403576

ceph-agent: do not check for subscription manager for agent install

---

ceph-ansible.spec.in
site.yml.sample

A couple minor patches needed for https://github.com/ceph/ceph-installer
- include ``infrastructure-playbooks/`` in the rpms
- sets ``gather_facts: True`` in ``site.yml.sample`` as ``ceph-installer`` uses this playbook and requires the usage of ansible facts.

changes needed for ceph-installer support

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml

We can now see the name of the file we are waiting for, depending on the
cluster name this will change.

common: show which file we are waiting for

---

roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml
roles/ceph-common/templates/rhcs.pref.j2

When `ceph_stable_rh_storage` is True, every cluster node should have a
`/etc/apt/preferences.d/rhcs.pref` file with the following contents:
```
Explanation: Prefer Red Hat packages
Package: *
Pin: release o=/Red Hat/
Pin-Priority: 999
```
ceph-deploy already did this when used with ice-setup, and we need to do
the same thing with the ceph-ansible stack.
Closes: #1182

common: set apt pinning with Red Hat Ceph Storage

---

roles/ceph-restapi/tasks/start_restapi.yml

I find when ceph-rest-api started with `--cluster xxx`, it will not read /etc/ceph/xxx.conf
So I use `--conf` here.
The ceph-rest-api is lack of a systemd service.
Maybe droping a systemd service here or ceph/ceph is better....

fix ceph-rest-api not using correct configure file

---

roles/ceph-osd/tasks/check_mandatory_vars.yml

when running a containerized deployment, some variable are not
applicable thus should not be checked.

osd: docker change required variables for check

---

roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/generate_cluster_fsid.yml
roles/ceph-mon/tasks/deploy_monitors.yml

This commit solves the situation where you lost your fetch directory and
you are running ansible against an existing cluster. Since no fetch
directory is present the file containing the initial mon keyring
doesn't exist so we are generating a new one.

common: do not regenerate initial mon keyring if cluster exists

---

ceph-ansible.spec.in

This is the only version that our CI uses for testing, so it's the only version we can confidently say works.
Update the RPM packaging to specifically require this version of Ansible.

rpm: require Ansible >= 2.2.0.0

---

tox.ini

This will make the CI output in jenkins much easier to read.

tests: preserve newlines in ansible output when testing

---

roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/facts_mon_fsid.yml

The block syntax in ansible is broken on 2.1 so we work around the
issue introduced in 471be5e by using a task file include.
Fixes #1196

Workaround for broken 'block' syntax

---

roles/ceph-common/tasks/checks/check_firewall.yml

command is a shell-buitin, so `command -v nmap` must use shell module
Signed-off-by: Shengjing Zhu <zsj950618@gmail.com>

fix check nmapexist on debian

---

roles/ceph-mon/tasks/ceph_keys.yml

Task put initial mon keyring in mon kv store from
ceph-mon/tasks/ceph_keys.yml is failing when cephx is disabled. The root
cause is that variable monitor_keyring is not populated by any task from
deploy_monitors.yml.
Fixes: #1211

mon: only put mon initial key in mon kv when cephx is enabled

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-common/defaults/main.yml

I'm seeing some teuthology failures when trying to install ceph packages, such as this on centos (full [teuthology.log](http://qa-proxy.ceph.com/teuthology/cbodley-2016-12-08_13:02:07-rgw-wip-cbodley-testing---basic-smithi/617718/teuthology.log)):
```
Error: Package: 1:ceph-common-11.0.2-2242.gbfb49aa.el7.x86_64 (ceph)
Requires: libcephfs2 = 1:11.0.2-2242.gbfb49aa.el7
Installed: 1:libcephfs2-11.0.2-2336.g27f6b03.el7.x86_64 (@ceph)
libcephfs2 = 1:11.0.2-2336.g27f6b03.el7
Available: 1:libcephfs2-11.0.2-2242.gbfb49aa.el7.x86_64 (ceph)
libcephfs2 = 1:11.0.2-2242.gbfb49aa.el7
```
It appears that the existing package for `libcephfs2` was not cleaned up by the ceph-ansible's `Ensure ceph packages are not present` task, which is referring to this package as `libcephfs1`.

bump package version to libcephfs2

---

infrastructure-playbooks/purge-cluster.yml
tox.ini

This test verifies that you can purge a cluster using journal collocation and then redeploy the cluster again. There were some minor fixes to ``purge-cluster.yml`` needed for the playbook to work.

tests: adds a purge_cluster_collocated scenario

---

roles/ceph-common/tasks/main.yml

Prior to this change, a playbook run with `--tags` or `--skip-tags` would fail, because the ceph-common role would not include the release.yml task, and this file defines critical things like ceph_release.
Thanks @andrewschoen for help with the fix.

ceph-common: always include release.yml

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/multisite/secondary.yml

Allowing granular control of the pull host/port/protocol for installs where SSL/443 is used and direct civetweb access isn't necessarily available.
fixes: #1207

[rtr] Granular Multi-site PULL Variables

---

infrastructure-playbooks/purge-cluster.yml
tox.ini

I need to remove those include_vars lines because including those default vars overwrites what we have defined here: https://github.com/ceph/ceph-ansible/blob/master/tests/functional/centos/7/journal-collocation/group_vars/all
Because the defaults are being used ``devices`` is set to ``[]`` which causes this task to skip, https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml#L395, resulting in OSDs not being properly purged.

tests: fixes for purge_cluster_collocated

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/tasks/start_monitor.yml

ceph-common will overwrite ceph.conf on every run, so
when ceph-mon also edits the file it will cause an
unnecessary restart of ceph-mon

move monitor definition from ceph-mon back to ceph-common

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

As described in issue #1224 leaving this variable undefined may
cause a problem during execution of the ceph-osd role.

Set empty list as default for osd_directories

---

tox.ini

`2.2.1` is not released yet, but this will be what we should rely on once it gets out.

bump ansible testing version to 2.2.1 for the 2.2 environment

---

roles/ceph-mon/tasks/ceph_keys.yml

Followup to #1173 
As part of https://github.com/ceph/ceph/pull/9345 the ceph-mon service no longer implicitly calls `ceph-create-keys` to generate the admin client key.

mon: run ceph-create-keys after startup for kraken release

---

group_vars/all.docker.yml.sample
roles/ceph-common/tasks/docker/fetch_image.yml
roles/ceph-docker-common/defaults/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mon/meta/main.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/meta/main.yml
roles/ceph-nfs/tasks/docker/dirs_permissions.yml
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/meta/main.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/templates/ceph-osd.service.j2
roles/ceph-rbd-mirror/meta/main.yml
roles/ceph-rbd-mirror/tasks/docker/dirs_permissions.yml
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-restapi/meta/main.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/start_docker_restapi.yml
roles/ceph-rgw/meta/main.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/templates/ceph-rgw.service.j2
roles/ceph.ceph-docker-common

This adds the ability to deploy containers that are stored in a custom registry and not docker.io. Adding a ceph-docker-common role was the easiest way to share the new value of ``ceph_docker_registry`` across all the other roles. Eventually, I think we should move things like ``fetch_images.yml`` out of ``ceph-common`` and into ``ceph-docker-common``.
This is needed for ceph-docker testing as well: https://github.com/ceph/ceph-docker/pull/458

adds a ceph-docker-common role and enables custom registry usage

---

roles/ceph-docker-common/meta/main.yml

This role needs a meta/main.yml before we can upload it to ansible
galaxy.

ceph-docker-common: include a meta/main.yml so we can use galaxy

---

contrib/push-roles-to-ansible-galaxy.sh

Prior to this patch we were only pushing 'master' and 'ansible-1.9'
branches. Each new release also introduces a new branch so we want to
push it as well.
Yes the 'grep' is a bit ugly, feel free to come up with something nicer :)

contrib: push all new stable branches to the galaxy

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

The libcephfs1 package was removed from ceph-common in
cb1c06901e02a9f44c24a5d20737a9f33ac8ab2b, however it was not synced
to group_vars/all.yml.sample using the `generate_group_vars_sample.sh`
script. This fixes up the comment formatting in the ceph-common
defaults and brings the group_vars sample back into sync.

Remove libcephfs1 from group_vars sample

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

- Allow for enhanced configurability of the civetweb parameters
- Add switch to enable CNAME bucket resolution (ie. some.website.com.objects.example.com) where bucket name is "some.website.com"
- Ability to enable RGW usage logging and its associated configuration parameters which are detailed at http://docs.ceph.com/docs/jewel/man/8/radosgw/#usage-logging
- Add switch to enable S3-style static website hosting.

Enhance RGW config options

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/main.yml
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/cluster/hosts
tests/functional/centos/7/cluster/vagrant_variables.yml
tests/functional/ubuntu/16.04/cluster/hosts
tests/functional/ubuntu/16.04/cluster/vagrant_variables.yml

Since we introduced config_overrides we removed a lot of options from
the default template. In some cases, like mds pool, openstack pools etc
we need to know the amount of PGs required. The idea here is to skip the
task if ceph_conf_overrides.global.osd_pool_default_pg_num is not define
in your `group_vars/all.yml`.
Closes: #1145

mon: pool creation and pgs

---

roles/ceph-mon/tasks/openstack_config.yml

could have scenario where different openstack components would
use the same pool, but the logic would create the same pool
more than once
add unique filter to account for this

add unique filter to openstack pool names

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

This allows the user to set ip_version to either ipv4 or ipv6. This
resolves a bug where monitor_address is set to an ipv6 address, but the
template fails to render because it's hardcoded to look for an 'ipv4'
key in the ansible facts.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1416010
Resolves: bz#1416010

Adds ip_version configuration option

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

This allows the user to set ip_version to either ipv4 or ipv6. This
resolves a bug where monitor_address is set to an ipv6 address, but the
template fails to render because it's hardcoded to look for an 'ipv4'
key in the ansible facts.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1416010
Resolves: bz#1416010
(cherry picked from commit 03cb803bd1bd6da888e0483db40d444cd4ee86e3)
Original PR: https://github.com/ceph/ceph-ansible/pull/1247

Backport: Adds ip_version configuration option

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/rbd_pool.yml
roles/ceph-mon/tasks/rbd_pool_pgs.yml
roles/ceph-mon/tasks/rbd_pool_size.yml

This patch makes sure we set the proper pool size on the rbd pool.
Usually during bootstrap the rbd pool size is not honoured so we need to
add this workaround.

mon: make sure osd_pool_default_size is honoured

---

infrastructure-playbooks/purge-cluster.yml
tests/functional/centos/7/journal-collocation/group_vars/all
tox.ini

- Adds test coverage for https://github.com/ceph/ceph-ansible/pull/1214
- renames ``ansible2.2-purge_cluster_collocated`` to ``ansible2.2-purge-cluster`` and now purges dedicated journals instead of collocated journals
- adds a ``ansible2.2-purge-dmcrypt`` scenario that tests purging of dmcrypt dedicated journals
- reorganizes the tox.ini to put purge tests into their own tox environment. This allows for ease of adding new purge cluster tests.

CI testing updates

---

roles/ceph-rgw/tasks/multisite/main.yml

Using ini_file with ansible_hostname to ensure each INI block gets the rgw_zone setting in a multi-RGW setup. Also, ansible_hostname better matches what ceph-common does for the actual hostname (ansible_host != ansible_hostname under all conditions).
Using lineinfile caused only the last stanza for RGW to get the rgw_zone setting.

Using ini_file + ansible_hostname for rgw_zone setting

---

roles/ceph-rgw/handlers/main.yml

Use hostname instead of host (host can be an IP) and hostname matches the default nomenclature in ceph.conf

Use ansible_hostname instead of ansible_host in handler

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/handlers/restart-mds.yml
roles/ceph-common/handlers/restart-mon.yml
roles/ceph-common/handlers/restart-osd.yml
roles/ceph-common/handlers/restart-rgw.yml
roles/ceph-common/handlers/validate-mon.yml
roles/ceph-common/handlers/validate-osd.yml
roles/ceph-common/tasks/generate_ceph_conf.yml
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/dmcrypt-dedicated-journal/group_vars/all
tests/functional/centos/7/dmcrypt-journal-collocation/group_vars/all
tests/functional/ubuntu/16.04/cluster/group_vars/all

This commits allows us to restart Ceph daemon machine by machine instead
of restarting all the daemons in a single shot.
Signed-off-by: Sébastien Han seb@redhat.com

common: serialise host restart

---

roles/ceph-common/handlers/main.yml

This breaks if the roles don't live in the same place as the playbook.
See: https://github.com/ceph/ceph-ansible/issues/1265

ceph-common: remove absolute path to handler include files

---

README.md

Adding underscores in the ceph_conf_overrides variable can result in incorrect
config options appearing.  A note has been added to clarify that using
underscores here can cause this behavior and recommending not to do it.
See: https://github.com/ceph/ceph-ansible/issues/1262
Signed-off-by: Kyle Squizzato <ksquizz@gmail.com>

README: Do not recommend using underscores for opts in ceph_conf_overrides

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/validate-osd.yml

Fixes: https://github.com/ceph/ceph-ansible/issues/1272

common: ability to disable handler osd health check

---

roles/ceph-osd/tasks/scenarios/bluestore.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-dedicated-journal.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-journal-collocation.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml
roles/ceph-osd/tasks/scenarios/osd_directory.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

we now use the name of the scenario in the prepare task.

osd: clarify osd scenario prepare sequence

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/validate-osd.yml

backport 1274: common: ability to disable handler osd health check

---

roles/ceph-common/templates/ceph.conf.j2

This fixes an issue with parsing the ceph.conf file when ip_version is set to
ipv6.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1419814

ceph-common: set ms bind ipv6 = true in ceph.conf when using ipv6

---

roles/ceph-mon/tasks/ceph_keys.yml

We shouldn't test directly the value of
`ceph_conf_overrides.global.osd_pool_default_pg_num` because this can
cause the playbook to fail if the key `global` is not present in
`ceph_conf_overrides`. Therefore we have to use the facts that have been defined earlier.
Fix: #1242

ceph-mon: Fix bug #1242

---

roles/ceph-common/templates/ceph.conf.j2

backport of https://github.com/ceph/ceph-ansible/pull/1285

backport: "ceph-common: set ms bind ipv6 = true in ceph.conf when using ipv6 #1285"

---

infrastructure-playbooks/purge-cluster.yml

This copies the method from rolling_update.yml to detect the init system
of the host. We can not always ensure that ceph-detect-init will be
present on the system.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1418980

purge-cluster: do not use ceph-detect-init

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-rgw/tasks/main.yml

76ddcbc introduced an issue by removing some needed conditions on tasks
that need to be run only on release >= kraken.

bugfix: Add missing conditions for kraken release

---

roles/ceph-client/tasks/main.yml
roles/ceph-client/tasks/pre_requisite.yml
roles/ceph-mon/tasks/ceph_keys.yml

Expand the fix in #1291 to all the playbook in order to get a full coverage.
Fix: #1294

Check if ceph_conf_overrides.global is defined before calling it

---

roles/ceph-common/tasks/facts.yml

If cephx is disabled it is not necessary to include `facts_mon_fsid.yml`
in `roles/ceph-common/tasks/facts.yml`.
Fix: #1300

Skip facts_mon_fsid.yml if cephx is disabled

---

infrastructure-playbooks/rgw-standalone.yml

This playbook is used to add an rgw node to an existing cluster when you
don't want to rerun the site.yml against your entire cluster again.
This is also used by the api/rgw/configure endpoint of ceph-installer.

rgw-standalone.yml will also now collect keys

---

roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-nfs/tasks/docker/start_docker_nfs.yml
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

So unit files were stored in /var/lib/ceph some where in
/etc/systemd/system. Now they are all under /etc/systemd/system.
closes: #1296

docker: homogenise systemd file location

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-common/handlers/restart-osd.yml
roles/ceph-common/handlers/validate-osd.yml

Some playbooks use [0-9]*, others use \d+$
The latter is more correct since cluster name may contain numbers.
Signed-off-by: Shengjing Zhu <zsj950618@gmail.com>

fix grep match pattern for osd ids

---

roles/ceph-common/tasks/misc/system_tuning.yml

To configure kernel the task is using "command" module which is not
respect operator ">". So this task just print to "stdout": "never >
/sys/kernel/mm/transparent_hugepage/enabled"
fix: #1319

common: fix "disable transparent hugepage"

---

group_vars/all.yml.sample

As of Infernalis, the Ceph daemons run as an unprivileged "ceph" UID, and this is by design.
Commit f19b765f7995dab4aca46e1885320dc440485ead altered the default civetweb port from 80 to 8080 with a comment in the commit log about "until this gets solved"
Remove the comment about permissions on Infernalis, because this is always going to be the case on the Ceph versions we support, and it is just confusing.
If users want to expose civetweb to s3 clients using privileged TCP ports, they can redirect traffic with iptables, or use a reverse proxy application like HAproxy.

group_vars: rm Infernalis comment

---

group_vars/all.yml.sample
infrastructure-playbooks/rolling_update.yml
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
tox.ini

This currently tests a rolling update on a cluster using dmcrypt dedicated journals from jewel to kraken. I had to change to using ``yum_repository`` to manage the ``ceph_stable`` repo because the ceph-release package from jewel -> kraken has the same version number and yum does not know to update anything. Also, this ways gives us much more flexibility in using other mirrors.

adds a testing scenario for rolling updates

---

infrastructure-playbooks/take-over-existing-cluster.yml

The previous command was returning /etc/ceph/ceph.conf, we only need
'ceph' to be returned.

infra: fix cluster name detection

---

roles/ceph-mon/tasks/create_mds_filesystems.yml

Check if ceph filesystem already exists before creating it.
If the ceph filesystem doesn't exist, execute the task only on one node.
Fix: #1314

ceph-mon: Check if ceph filesystem exists

---

infrastructure-playbooks/rolling_update.yml

The task waiting for the monitor to join the quorum... , the result for ceph -s | grep monmap only contain monmap, not included quorum:
```
monmap e1: 3 mons at {sh-office-ceph-1=10.12.10.34:6789/0,sh-office-ceph-2=10.12.10.35:6789/0,sh-office-ceph-3=10.12.10.36:6789/0}
```
If want to get monitor, should use this:
```
election epoch 80, quorum 0,1 sh-office-ceph-1,sh-office-ceph-2
```
ceph verison: 10.2.5

rolling_update check monitor quorum error

---

roles/ceph-common/tasks/checks/check_system.yml

"red hat storage" -> "red hat ceph storage"
"RHEL 7.1" -> "RHEL 7"
and make the version number check verify the very latest version
https://bugzilla.redhat.com/show_bug.cgi?id=1354059

check_system: improve RHCS support message and version comparison

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/pre_requisite.yml
roles/ceph-rgw/templates/ceph.j2

This was needed for Hammer and older version, not needed anymore since
we have a 'ceph' user to run ceph processes.

rgw: remove sudoers file

---

Makefile

When `git describe` returns an `rc` tag (eg `2.2.0rc1`), insert the RC number into the RPM's `Release` field.
This change will allow us to generate RPMs from the master branch with an NVR that is higher than v2.1.9, once we tag v2.2.0rc1 on that branch.

Makefile: handle "rc" version tags

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

From Josh Durgin, "I'd recommend not setting vfs_cache_pressure in ceph-ansible. The syncfs issue is still there, and has caused real problems in the past, whereas there hasn't been good data showing lower vfs_cache_pressure is very helpful - the only cases I'm aware of have shown it makes little difference to performance."
https://bugzilla.redhat.com/show_bug.cgi?id=1395451

avoid setting vfs_cache_pressure

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

This has the behavior of overriding custom values set in group_vars.
I've added defaults to the rest of the group names so that if they are
not overridden in group_vars then defaults will be used.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1354700

purge-cluster: do not set group name vars at playbook level

---

tox.ini

This updates the centos 7 cluster scenario from jewel to kraken using
the rolling_update playbook.

tests: adds an update_cluster testing scenario

---

group_vars/mons.yml.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/calamari.yml

This patch introduces calamari_debug option which will turn on debugging
for calamari before initializing and running it.

calamari: Add debugging option

---

roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml

Prior to this change, ceph-ansible would install the main NFS Ganesha server daemon on Ubuntu, but it would skip the Ceph FSALs.
Running `apt-get install nfs-ganesha` will only install the main NFS Ganesha server. It does *not* pull in the RGW FSAL (`/usr/lib/x86_64-linux-gnu/ganesha/libfsalrgw.so`)
Running `apt-get install nfs-ganesha-fsal` will install the RGW FSAL as well as the main NFS Ganesha server package.

ceph-common: install nfs-ganesha FSALs on Debian

---

roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-rgw/templates/ceph-rgw.service.j2

This option was missing for rrgw, mds, rbd mirror and nfs making these
daemon impossible to run on a kv deployment with containers.

kv scenario: add KV_PORT option

---

infrastructure-playbooks/make-osd-partitions.yml

With the merge of PR #1336 the syntax check fails. This commit replaces
the tabs with proper indentation.

Fixing tabs that are breaking the syntax check

---

roles/ceph-mon/tasks/docker/main.yml

Sometimes the socket appears during the 5th attempt and sometimes not so
increasing the timeout a little bit.

mon: increase wait for monitor socket timeout

---

group_vars/docker-commons.yml.sample
group_vars/mons.yml.sample
roles/ceph-docker-common/tasks/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-mon/tasks/set_osd_pool_default_pg_num.yml

Add possibility to create openstack pools and keys even for containerized deployments
Fix: #1321 

ceph-mon: create openstack pools and keys even for containerized deployments

---

group_vars/docker-commons.yml.sample
roles/ceph-docker-common/defaults/main.yml
roles/ceph-docker-common/tasks/pre_requisites/prerequisites.yml

This is not only for monitors, but also mds, rgw and rbd mirror so
making the var name more generic:
ceph_docker_enable_centos_extra_repo

docker: change centos extra repo var name

---

roles/ceph-mon/tasks/ceph_keys.yml

After the jewel release the mon startup does not generate keys, but it's
still harmless to call ceph-create-keys with jewel because this task has
a 'creates' argument that will cause it not to run if the keys already
exist.
Removing this when condition also allows the downstream CI tests to
install kraken or luminous without resetting ceph_stable_release, which does not
pertain to rhcs.

ceph-mon: always call ceph-create-keys

---

roles/ceph-common/tasks/generate_ceph_conf.yml

This removes the implicit order requirement when using OSD fragments.
When you use OSD fragments and ceph-osd role is not the last one,
the fragments get removed from ceph.conf by ceph-common.
It is not nice to have this code at two locations, but this is
necessary to prevent problems, when ceph-osd is the last role as
ceph-common gets executed before ceph-osd.
This could be prevented when ceph-common would be explicitly called
at the end of the playbook.
Signed-off-by: Christian Zunker <christian.zunker@codecentric.de>

Make ceph-common aware of osd config fragments

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

With ' in osd_crush_location, systemd will show this error:
ceph-osd-prestart.sh[2931]: Invalid command:  invalid chars ' in 'root=
Signed-off-by: Christian Zunker <christian.zunker@codecentric.de>

Fix osd_crush_location to prevent systemd error message

---

roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

This fixes issue #1299. According to @ktdreyer s comment in the ticket,
he fixed the web server config so also older (non-SNI) python clients
can use the uri module here.

Use ansible uri module instead of shell module with curl

---

group_vars/docker-commons.yml.sample
roles/ceph-docker-common/defaults/main.yml
roles/ceph-docker-common/tasks/main.yml
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-nfs/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-rbd-mirror/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml

Make bootstrap directories permissions work for both RedHat and Debian
os families.
Fix: #1338

ceph-docker: fix bootstrap directories permissions

---

tests/functional/rhcs_setup.yml
tox.ini

This adds a new prefix, ``rhcs-``, that when added will instruct our testing scenarios to install Red Hat Ceph Storage instead of upstream ceph.

tests: enable testing of rhcs

---

roles/ceph-common/tasks/misc/system_tuning.yml

systctl tuning should be in the sysctl.d directory. This creates
a seperation from what values were set specific to ceph, and what
values were set by the operator.
Signed-off-by: Tyler Brekke <tbrekke@redhat.com>

ceph-common: update sysctl file location

---

roles/ceph-common/handlers/restart-mds.yml
roles/ceph-common/handlers/restart-mon.yml
roles/ceph-common/handlers/restart-osd.yml
roles/ceph-common/handlers/restart-rgw.yml

If a group of hosts is empty, (for instance 'mdss', in case of a
deployment without any mds node), the playbook will fails when trying
to restart service with `"'dict object' has no attribute u'XXX'"` error.
The idea here is to force the `with_items` statements in all included handler tasks
to get at least an empty array.

BugFix: Fix #1374

---

infrastructure-playbooks/cluster-os-migration.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-nfs/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml

Some tasks try to look to "default mon group in inventory", but if group have another name role is failed on `create openstack pool` : `The conditional check 'inventory_hostname == groups.mons|last' failed.`

Resolve issues when groups names not in default value.

---

Vagrantfile
vagrant_variables.yml.sample

If debug is set to true in vagrant_variables.yml then during the vagrant
provision phase Ansible will run with -vvvv option

vagrant: add debug option

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_ntp_debian.yml
roles/ceph-common/tasks/checks/check_ntp_redhat.yml

ntp is still installed even if ntp_service_enabled is set to false.
That could be a problem if the time synchronization is managed by
something else than ceph-ansible or if you want to use different NTP
implementation as suggested in #1354.
Fixes: #1354

Common: Do not install ntp when ntp_service_enabled is false

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-common/handlers/restart-osd.yml
roles/ceph-common/handlers/validate-osd.yml
roles/ceph-osd/tasks/activate_osds.yml
tests/conftest.py

Problem: too many different commands to do the same thing. The 'cut'
command on infrastructure-playbooks/purge-cluster.yml was also wrong.
This sed command from osixia in ceph-docker
https://github.com/ceph/ceph-docker/pull/580/ addresses all the
scenarios.

playbook: homogenize the way list osd ids

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/scenarios/bluestore.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-journal-collocation.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml

As reported in
https://github.com/ceph/ceph-ansible/issues/1403 when devices are held
by lvm and `osd_auto_discovery` is set to true, it's not enough to check
for a partition count = 0 since Ansible does not report.
This patch also looks for 'holders' which in a case of lvm corresponds
to the name of the pv. Now we also look for holders = 0.
Fixes: #1403

osd: autodiscovery mode, use holders to detect device

---

tox.ini

When testing this downstream it makes more sense for this scenario to be
named just 'cluster' because have 'centos7' in the name is misleading.

tests: add an alias of cluster for the centos7_cluster scenario

---

roles/ceph-osd/tasks/check_devices_auto.yml

Small fix for (probably copy&paste) issue from 42ffe6301.
Fixing following issue:
```
TASK [ceph-osd : fix partitions gpt header or labels of the osd disks (autodiscover disks)] ***
task path: /home/usmqe/ceph-ansible/roles/ceph-osd/tasks/check_devices_auto.yml:26
fatal: [n41.gusty]: FAILED! => {
"failed": true, 
"msg": "The conditional check 'item.value.holders|count == 0' failed. The error was: error while evaluating conditional (item.value.holders|count == 0): 'list object' has no attribute 'value'\n\nThe error appears to have been in '/home/usmqe/ceph-ansible/roles/ceph-osd/tasks/check_devices_auto.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: fix partitions gpt header or labels of …
```

osd autodiscovery mode: fix holders detection

---

tox.ini

This allows us to control the docker registry, image name and tag name
for the containers.

tests: add docker environment variables to tox.ini

---

roles/ceph-mon/tasks/start_monitor.yml

ceph-create-keys unit file was removed here:
* https://github.com/ceph/ceph/commit/8bcb4646b6b9846bb965cdec3ca2a21eb3b26bab
* https://github.com/ceph/ceph/commit/dc5fe8d415858358bd0baf5d8dce0a753f5e0cea
As a consequence the systemctl preset command now fails to run since the
unit does not exist anymore. Due to the redirection in /dev/null we
don't know what's happening.
Ultimately the mon unit doesn't get enabled and the mon service won't
start after reboot.
Removing the old/non-existent unit makes the command succeed now.
ceph fix: https://github.com/ceph/ceph/pull/14226
Signed-off-by: WingkaiHo <sanguosfiang@163.com>
Co-Authored-By: Sébastien Han <seb@redhat.com>

enable ceph-mon.target service after monitor start

---

roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-common/templates/tmpfiles_hugepage.j2

Resolve #1408 and #1013.
First check tmpfiles.d directory for local administrator is present (or create it).
After file is created - systemd-tmpfiles is executed and if exit zero exit status - all okay and hugepage is tuned (can be covered in tests).

ceph-common: persist "disable_transparent_hugepage"

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
tests/functional/ubuntu/16.04/cluster/group_vars/all

Kraken has been out for a couple of weeks now and the CI can test both
Kraken and Jewel.

common: bump ceph version to kraken

---

tests/functional/rhcs_setup.yml

- changes centos/atomic-host box to rhel7
- enables the rhel-7-extras-nightly repo on test nodes

tests: updates for rhcs testing

---

roles/ceph-mon/tasks/docker/fetch_configs.yml

Ansible evaluates the 'with_items' before the 'when' so if the inventory
does not have the group declared it'll fail. To fix this, we set an
empty array to make the with_items happy and then evaluate with the
'when'.

mon: fix with_items being evaluated before when

---

roles/ceph-common/tasks/generate_ceph_conf.yml
roles/ceph-osd/tasks/osd_fragment.yml

Ansible's assemble module by default will put all files in the src
directory together into dest. We only want to put {{ cluster }}.conf
and osd.conf together, not anything that might have found its way into
/etc/ceph/ceph.d (e.g. files left by the sysadmin taking backups
before an ansible run). So specify a regexp that matches only those
two files.

Only assemble {{ cluster }}.conf and osd.conf

---

infrastructure-playbooks/purge-cluster.yml

raw_device would return invalid block device names for NVMe and HPSA
devices which would cause sgdisk partition deletion to fail
$ echo /dev/nvme1n1p3 | egrep -o '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p){1,2}'
/dev/nvme1n1p
Needs to be /dev/nvme1n1.
$ echo /dev/cciss/c0d0p2 |  egrep -o '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p){1,2}'
/dev/cciss/c0d0p
Valid device name is /dev/cciss/c0d0.

purge-cluster: fix grep match for NVMe and HP Smart Array devices

---

roles/ceph-common/tasks/main.yml
tests/functional/rhcs_setup.yml
tox.ini

When setting ``CEPH_STABLE = false`` as an environment variable it gets passed to --extra-vars as a string, which will always evaluate to ``true`` in the tasks. This PR avoids that by modifying the ``group_vars/all`` for the scenario being tested when we've used the ``rhcs`` prefix.
This also fixes a bug where the ``installs/install_on_redhat.yml`` task was always being included unless you were trying to do an iso install for rhcs.

tests: fix ceph_rhcs setup

---

roles/ceph-mon/tasks/ceph_keys.yml

The previous command was hanging, see this issue:
https://github.com/ceph/ceph-ansible/issues/1440

ceph-mon: change command to see if rbd exists

---

docs/source/testing/scenarios.rst

It also fixes the following error:
Warning, treated as error:
/home/jenkins-build/build/workspace/ceph-ansible-docs/docs/source/testing/scenarios.rst:21:  WARNING: Explicit markup ends without a blank line; unexpected unindent.

docs: describe all required scenario files

---

docs/source/testing/layout.rst
docs/source/testing/tests.rst

describe layout of Python tests and fixtures, with links to external resources for `testinfra` and `pytest`

[docs] fixtures and Python tests

---

roles/ceph-osd/templates/ceph-osd-run.sh.j2

The same issue is discussed here: https://github.com/moby/moby/issues/9950
This patch resolves the issue by adding the "--security-opt apparmor:unconfined" option in ceph-osd-run.sh.j2, but only for Debian systems.

Apparmor on Ubuntu Xenial will not permit containers to mount devices.

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml

This is to allow ceph-mgr daemons to remote control
osd and mds daemons with MCommand messages.
Fixes: http://tracker.ceph.com/issues/19713
Signed-off-by: John Spray <john.spray@redhat.com>

mon: update mgr key capabilities

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/checks/check_socket.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/templates/restart_mon_daemon.sh.j2
roles/ceph-common/templates/restart_osd_daemon.sh.j2
tests/functional/centos/7/journal-collocation/group_vars/all

Since `5bec62b` force the user to have a configuration that makes the
PGs in 100% clean state. We need to have a better logging in the
`restart_*_daemon.sh` scripts. Indeed, if a daemon fails to start we
shouldn't not being deeply debugging why.

Common: Restore check_socket

---

roles/ceph-mon/tasks/calamari.yml

Prior to this change, ansible was only checking for the existence of the
package, now if upgrade_ceph_packages is true this means we are
performing an upgrade.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1442016

mon: upgrade calamari when running rolling_update playbook

---

roles/ceph-mon/tasks/calamari.yml

Prior to this change, ansible was only checking for the existence of the
package, now if upgrade_ceph_packages is true this means we are
performing an upgrade.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1442016
(cherry picked from commit 84d96be197617ff8cdf8141e4a52657f172b2809)

backport-1466: mon: upgrade calamari when running rolling_update playbook

---

infrastructure-playbooks/purge-cluster.yml

This removes tasks from the end of the purge-cluster playbook that are not needed anymore. This was noticed because in rhcs we install ``ceph-common`` on clients nodes and that package does not include ``ceph.target`` so the playbook would fail.  Removing the packages should stop that service anyway if it is running, eventually we'll want to not install ``ceph-base`` upstream on client nodes either as it's not meant to be installed standalone.
There is also some cleanup on sysv and upstart tasks.

purge-cluster: remove unneeded tasks

---

group_vars/all.yml.sample
group_vars/rgws.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/main.yml
roles/ceph-rgw/tasks/rgw_pool_pgs.yml

Add more rgw ceph config variables and create
pools for rgw.
Suggestions for parameters in comments

rgw: set tuning parameters

---

infrastructure-playbooks/shrink-osd.yml

When the osd's disk or partition damage,  we could not use the ceph-disk deactivate and ceph-disk destroy to shrink osd.  It must use the ceph command to shrink osd. 
You can use the sgdisk --zap-all -- /dev/device_name to simulate partition damage.
This osd could not be shrink by this playbook, it will throw error "Cannot find any match device!!" at task deactivating osd(s)

improve shrink-osd.yml can shrink osd when disk damage

---

tox.ini

backport of #1487 
I did not backport 8472472194521a468b58bac76954cb86cbcdaece as it looks like we are missing other documentation commits and it was conflicting.

Backport: "tests: actually test jewel when we say we are #1487"

---

tests/functional/rhcs_setup.yml
tox.ini

tests: allow for insecure docker registries when testing rhcs

---

tests/functional/rhcs_setup.yml
tox.ini

backport: "tests: allow for insecure docker registries when testing rhcs #1490"

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_debian.yml

We shouldn't need this anymore as the upgrade bug that
debian_ceph_packages was used to workaround should have
been fixed as of jewel.
See https://github.com/ceph/ceph-ansible/issues/1481 for more
detailed information.

ceph-common: remove debian_ceph_packages

---

ansible.cfg

Ability to log ansible plays in a log file. Default location is
/var/log/ansible.log
Be sure the user running Ansible has permissions on the logfile.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1445065

ansible: add logging path

---

roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml
site-docker.yml.sample
site.yml.sample
tests/conftest.py
tests/functional/tests/test_install.py

ceph-mgr tasks have to be skipped on jewel.
Fix: #1494

Common: Do not install ceph-mgr packages on jewel

---

tox.ini

Now that the default value in ``ceph-common/defaults/main.yml`` for ``ceph_stable_release`` is kraken the CI should match that.

tests: update default of CEPH_STABLE_RELEASE to kraken

---

roles/ceph-common/templates/ceph.conf.j2

"rgw override bucket index max shards" and
"rgw bucket default quota max objects" were in the
client section of the ceph.conf and not being
applied, this commit moves them to global
Resolves: bz#1391500

rgw: move default bucket quota conf vars to global

---

tox.ini

The Ansible team has released v2.2.3, which fixes two CVEs:
CVE-2017-7481
CVE-2017-7466
https://www.ansible.com/security

tox: bump ansible version to 2.2.3

---

ceph-ansible.spec.in

These are unnecessary on RPM-based platforms, and it makes it harder to audit the RPM-packaged files for security when we ship things that are unneeded.

rpm: do not package coreos-related files

---

roles/ceph-mon/tasks/docker/main.yml

The CI on Docker is reporting the following error:
STDERR:
Error EINVAL: bad entity name
This is due to the fact that this auth entity name does not exist on
Jewel so we should not create that key when running Jewel containers.
Fixes: https://github.com/ceph/ceph-ansible/issues/1514

mon: do not create mgr key on jewel

---

ansible.cfg

Default ansible control_path option is too long, so we shorten it by
changing the ansible.cfg file.
For more info see: https://github.com/ansible/ansible/issues/11536
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1447569

ansible: shorten default control_path

---

generate_group_vars_sample.sh
group_vars/all.yml.sample
group_vars/rgws.yml.sample

In some case, ceph_docker_registry does not match with a defined host
group in the playbook so we make this variable widely available.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1447179

generate_group_vars_sample: merge role variables

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

Already documented in the [Red Hat Ceph Storage 2 Installation Guide for Red Hat Enterprise Linux](https://access.redhat.com/webassets/avalon/d/Red_Hat_Ceph_Storage-2-Installation_Guide_for_Red_Hat_Enterprise_Linux-en-US/Red_Hat_Ceph_Storage-2-Installation_Guide_for_Red_Hat_Enterprise_Linux-en-US.pdf), but not here.

monitor_interface: document need to use monitor_address when using IPv6

---

ansible.cfg

Default ansible control_path option is too long, so we shorten it by
changing the ansible.cfg file.
For more info see: https://github.com/ansible/ansible/issues/11536
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1447569
(cherry picked from commit 0e931d2bce1030fcec9121a8dba70009cff83403)

backport: ansible: shorten default control_path

---

tests/requirements.txt

1.6.1 fails with 'testinfra is in an unsupported or invalid wheel'
See: https://github.com/philpep/testinfra/issues/201

tests: pin testinfra to 1.6.0

---

contrib/backport_to_stable_branch.sh

To ease the backport, I wrote a quick script.
Usage: ./backport.sh.sh stable-2.2
6892670d317698771be7e96ce9032bc27d3fd1e5 my-work
We can also pass multiple commits.
Follow up on @ktdreyer write up here:
https://github.com/ceph/ceph-ansible/pull/1529

contrib: add backport script

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

Already documented in the Red Hat Ceph Storage 2 Installation Guide
for Red Hat Enterprise Linux, but not here
Signed-off-by: Florian Klink <flokli@flokli.de>
(cherry picked from commit 10b91661ceef7992354032030c7c2673a90d40f4)

backport: monitor_interface: document need to use monitor_address when using IPv6

---

roles/ceph-mon/templates/ceph-mon.service.j2

Problem: fail to deploy a containerized Ceph cluster with ipv6
Solution: do not hardcode ipv4 when bootstrapping the container.
Now use ip_version: ipv6 to get a containerized cluster deployed with
ipv6.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1451786

mon: do not hardcode ipv4

---

roles/ceph-mon/templates/ceph-mon.service.j2

Problem: fail to deploy a containerized Ceph cluster with ipv6
Solution: do not hardcode ipv4 when bootstrapping the container.
Now use ip_version: ipv6 to get a containerized cluster deployed with
ipv6.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1451786
(cherry picked from commit c7aae7f965758eb08a806fc7be75d8075884b733)

backport: Container ipv6 bkp

---

roles/ceph-common/tasks/generate_ceph_conf.yml
roles/ceph-osd/tasks/osd_fragment.yml

This backports 3 fixes from master onto stable-2.1 They are 349b9ab3e72f188c50b5f84f3ce5ee2fddcfbf80 (which means that you don't lose the osd fragments from ceph.conf on nodes that are members of another group as well as osds) and the two commits from my PR https://github.com/ceph/ceph-ansible/pull/1431 which mean you don't pick up stray files from `/etc/ceph/ceph.d`

Backport osd fragments fix

---

README.md

Add instructions for how we maintain and release the stable release series.
We'd been following this for a while, so let's get it written down.

README: add backporting instructions

---

roles/ceph-common/tasks/checks/check_system.yml

Clarify in the error message that only RHEL version >= 7.3 are
supported.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1452431

common: explicitly set rhel os version support

---

roles/ceph-common/tasks/checks/check_system.yml

Clarify in the error message that only RHEL version >= 7.3 are
supported.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1452431
(cherry picked from commit 8ad503b2488c1b9544165fa53c01e27d85af17ab)

backport: common: explicitly set rhel os version support

---

Vagrantfile

Use host-passthrough for libvirt vCPUs

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

Problem: we could end up in situation where we would install a package
on a machine that does not have the right repo enabled. Because the
condition was set to OR we weren't pinning a particular host but just a
condition. Let's say someone sets 'ceph_origin == "distro"', this would
try to install OSD packages on Monitors.
Solution: use a AND condition to first pin to the group_name (which
identifies a set of hosts) AND then after this one of the installation
condition.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1453119

common: fix installation condition

---

infrastructure-playbooks/rolling_update.yml

Problem: we are delegating the set/unset flag to a monitor node but we
try to call an osd container
Solution: use the right container name.

rolling-update: set/unset flags on the right container

---

infrastructure-playbooks/rolling_update.yml

Problem: we are delegating the set/unset flag to a monitor node but we
try to call an osd container
Solution: use the right container name.
(cherry picked from commit 90389864d8d7cc8d426ef7c8687eeb43db92406e)

backport: rolling-update: set/unset flags on the right container

---

roles/ceph-mon/tasks/docker/fetch_configs.yml

Ansible evaluates the 'with_items' before the 'when' so if the inventory
does not have the group declared it'll fail. To fix this, we set an
empty array to make the with_items happy and then evaluate with the
'when'.
(cherry picked from commit 05331a26348e162e4083131d2a259f6c983f3ec9)

backport: mon: fix with_items being evaluated before when

---

infrastructure-playbooks/purge-docker-cluster.yml
tox.ini

- defaults ``raw_journal_devices`` to ``[]``. This allows the purge-docker-cluster.yml playbook to complete if the cluster was not deployed with dedicated journals
- creates a testing scenario for purging containerized clusters
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1455187

purge-docker-cluster fix and test

---

tox.ini

When we purge a containerized cluster we need to use the correct
playbook when redploying the cluster.

tests: use docker playbook when redeploying a purged cluster

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

since `-e CEPH_DAEMON=OSD_CEPH_DISK_ACTIVATE` is already hardcoded in
`eph-osd-run.sh.j2` there is no need to add `-e
CEPH_DAEMON=OSD_CEPH_DISK_ACTIVATE` as a default value in defaults vars.

Docker: Remove duplicate var passed to docker-run

---

roles/ceph-common/templates/restart_osd_daemon.sh.j2

For some reason we changed the check of pgs but it appears it could be
dangerous because the current check might satisfied as long as 1 PG is
active+clean.

Common: Improve check pgs

---

infrastructure-playbooks/purge-docker-cluster.yml

We need to include ceph_docker_registry when removing containers/images
because if we don't it will assume docker.io which is not always where
the image originated from, causing the playbook to fail.

purge-docker-cluster: include ceph_docker_registry

---

roles/ceph-mon/templates/ceph-mon.service.j2

The fact ['ansible_$interface']['ipv4'] is a dictionary where
['ansible_$interface']['ipv6'] is a list. If we use
ansible_default_ipv6|ipv4 is is always a dictionary which allows us to
get the ipv6 and ipv4 address without adding more complexity to the
template.

ceph-mon: fix support for ipv6 on containerized mons

---

ceph-ansible.spec.in

Currently we cannot install the ceph-iscsi-ansible RPM on a node where the ceph-ansible RPM is already installed.
ceph-iscsi-ansible should install on top of the ceph-ansible environment without issues.

rpm: do not package iscsi files

---

roles/ceph-mon/templates/ceph-mon.service.j2

backport: "ceph-mon: fix support for ipv6 on containerized mons #1587"

---

site.yml.sample

We ship ceph-iscsi-gw in a separate repo downstream and do not package
it with ceph-ansible. Including the play for ceph-iscsi-gw in
site.yml.sample makes the playbook fail when using the downstream
packages.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1454945

remove ceph-iscsi-gw play from site.yml.sample

---

group_vars/all.yml.sample
roles/ceph-docker-common/defaults/main.yml

Add a default value for `ceph_docker_on_openstack` to avoid a
conditional check error for the task `pause after docker install before starting` in
`roles/ceph-docker-common/tasks/pre_requisites/prerequisites.yml`

Common: Add a default for ceph_docker_on_openstack

---

roles/ceph-common/templates/restart_osd_daemon.sh.j2

Rewrite the check_pgs by using json parsing instead of complex regexp to
parse the `ceph -s` output.

Common: Rewrite check_pgs

---

ansible.cfg

On a Vagrant setup, every host is 127.0.0.1 and every user is vagrant.
To not have ansible do the same stuff on the same machine (the one
we connected first), we should keep the port as part of the
control path.
Also this helps in setups where different hosts might be hidden
behind the same IP, but on different ports (e.g. using DNAT).

keep port as part of the control path

---

infrastructure-playbooks/cluster-os-migration.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

Avoid screen scrapping by rewriting `waiting for clean pgs` tasks like it is
done in 304de48.
Use the json output returned by `ceph -s` instead

rewrite check pgs clean tasks

---

roles/ceph-mon/tasks/ceph_keys.yml

For newly created cluster the command: ceph --cluster {{ cluster }} osd
pool get rbd size does not respond properly.
We only want to check if the rbd pool exists, so we know use an ls |
grep approach.
Closes: https://github.com/ceph/ceph-ansible/issues/1547

ceph-mon: fix get rbd size hanging

---

infrastructure-playbooks/rolling_update.yml
tests/functional/centos/7/docker-cluster/group_vars/all
tox.ini

I have yet to get this test to pass so I'm not going to enable it in the CI quite yet.
The failure I see is that the first updated MON does not start and join the quorum after being updated.

tests: adds a test for rolling updates of containerized clusters

---

roles/ceph-common/templates/ceph.conf.j2

Remove "osd mkfs type" and the other pre-Bluestore parameters from the generated ceph.conf so that disk activation on OSDs will work. The current default xfs config results in a failed deployment and incorrect partition metadata.

Bluestore: Omit "osd mkfs type" etc from ceph.conf

---

roles/ceph-common/templates/restart_osd_daemon.sh.j2

The current handler only restarts one OSD on each OSD server. After
the first one it stops, not matter what results the checks had.

Restart all OSDs and do not stop after the first one.

---

group_vars/mons.yml.sample
roles/ceph-mon/defaults/main.yml

OpenStack's Gnocchi service expects to have a pool called "metrics". This change adds "metrics" to the list of `openstack_pools` and creates a corresponding key. It is only run if the user sets `openstack_config: false`.

Add OpenStack metrics pool

---

infrastructure-playbooks/cluster-os-migration.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-common/templates/restart_osd_daemon.sh.j2

The new test in the checks PGs are no longer working on distributions
where /bin/sh isn't linked to /bin/bash.
Fix: #1619

Make the new check PGs working with /bin/sh

---

roles/ceph-docker-common/tasks/main.yml
roles/ceph-nfs/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-rbd-mirror/tasks/docker/main.yml
roles/ceph-restapi/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/main.yml

In addition to 7bb04a5, these lines are no longer needed and can even
cause playbook failures.

Fix followup

---

roles/ceph-mon/tasks/openstack_config.yml

Somehow the shell module will return an error if the command line is not
next to it.
Plus fixed the import with the right path.

mon: fix openstack key creation

---

README.md
ceph-ansible.spec.in
group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/dmcrypt-dedicated-journal/group_vars/all
tests/functional/centos/7/dmcrypt-dedicated-journal/hosts
tests/functional/centos/7/dmcrypt-journal-collocation/group_vars/all
tests/functional/centos/7/dmcrypt-journal-collocation/hosts
tests/functional/centos/7/journal-collocation/group_vars/all
tests/functional/centos/7/journal-collocation/hosts
tests/functional/ubuntu/16.04/cluster/group_vars/all
tests/functional/ubuntu/16.04/cluster/hosts

e8187f6 does not fix the ipv6 as expected since `ansible_default_*` are
filled with the IP address carried by the network interface used by the
default gateway route. By the way, it assumes that the MON_IP address will
be this IP address which is not always the case.
We need to keep using the previous fact but add some intelligence in the
template to determine how to retrieve the ipv4|ipv6 address since the path
to the fact in `hostvars` is not the same according to ipv4 vs ipv6 case.
Fixes: https://github.com/ceph/ceph-ansible/issues/1352

Common: Add ipv6 support

---

Vagrantfile
group_vars/all.yml.sample
group_vars/mons.yml.sample
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-docker-common/defaults/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/check_mandatory_vars.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
tests/functional/centos/7/docker-cluster-dedicated-journal/Vagrantfile
tests/functional/centos/7/docker-cluster-dedicated-journal/group_vars/all
tests/functional/centos/7/docker-cluster-dmcrypt-journal-collocation/Vagrantfile
tests/functional/centos/7/docker-cluster-dmcrypt-journal-collocation/group_vars/all
tests/functional/centos/7/docker-cluster/group_vars/all

Some variables are missing from ceph-docker-common role since the
include of check_mandatory_vars.yml has been re-added in the ceph-mon
role.

Docker-common: Add missing variables declaration

---

group_vars/mons.yml.sample
group_vars/rgws.yml.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/crush_rules.yml
roles/ceph-mon/tasks/openstack_config.yml

Add an extra variable to the openstack pools, which creates them with
defined rules. This will allow to place different pools on e.g.
different type of disks.
This commit will also set a new default rule when defined and move
the rbd pool to the new rule.

Create OpenStack pools with crush rule

---

group_vars/mons.yml.sample
group_vars/rgws.yml.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml

Add a new parameter `admin_secret` that allow to deploy a ceph cluster
with a custom admin secret.
Fix: #1630

Mon: Allow to deploy with custom admin secret

---

tests/functional/centos/7/docker-cluster-dmcrypt-journal-collocation/group_vars/all

The scenario set in `group_vars/all` for
docker-cluster-dmcrypt-journal-collocation is not the correct one.

Tests: fix scenario for docker-cluster-dmcrypt-journal-collocation

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

rsync is required by the ansible synchronize package. Ensure
it is installed when local installation is selected.
Signed-off-by: Douglas Fuller <dfuller@redhat.com>

common: ensure rsync is installed for local install

---

roles/ceph-osd/tasks/check_mandatory_vars.yml

Fail with a sane message if the devices variable is not an array
during manual device assignment.
Signed-off-by: Douglas Fuller <dfuller@redhat.com>

osd: validate devices variable input

---

group_vars/mons.yml.sample
roles/ceph-mon/defaults/main.yml

In addition to ceph/ceph-docker@69d9aa6, this explains how to deploy a
containerized cluster with a custom admin secret.
Basically, just need to pass the `admin_secret` defined in your
`group_vars/all.yml` to the `ceph_mon_docker_extra_env` variable.
Eg:
`ceph_mon_docker_extra_env: -e CLUSTER={{ cluster }} -e FSID={{ fsid }}
-e MON_NAME={{ monitor_name }} -e ADMIN_SECRET={{ admin_secret }}`

Doc: containerized deploy with custom admin secret

---

vagrant_variables.yml.atomic
vagrant_variables.yml.openstack
vagrant_variables.yml.sample

in addition to e5d06a4 make sure devices variable will be a list even
with vagrant.

vagrantfile: Ensure `devices` variable is a list

---

roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

the newest ceph-disk use bluestore default, so if we want using filestore , we need to config filestore explicitly.

fix: osd use filestore

---

tests/functional/tests/osd/test_osds.py

the `test_osds_listen_on_*` consider OSDs will always listen on tcp port
with consecutive tcp port number starting from `6800`.
Eg.
If you have 2 OSDs, tests will assume it should listen on 2 ports for each
network (`public_network` and `cluster_network`), therefore:
`6800, 6801, 6802, 6803`
but sometime it doesn't happen this way and you can get OSDs listening
on tcp port like this :
`6800, 6801, 6802, 6805`
Then the test are failing while it shouldn't.

tests: fix test_osds_listen_on_* tests

---

docs/source/testing/tox.rst
tests/functional/dev_setup.yml
tox.ini

If you use the 'dev' factor, the testing scenario will
use repos from shaman.ceph.com. You can define CEPH_DEV_BRANCH
and CEPH_DEV_SHA1 to specify which repo you'd like to test.

tests: run all existing tests with shaman repos

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample
group_vars/rgws.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml

The openstack_keys structure now supports a key called acls whose value is a list of strings that one could 
pass to setfacl. The ansible ACL module applies the ACLs to all openstack keys with this property.
Fixes: #1688

Allow user to define ACLs for OpenStack keys

---

infrastructure-playbooks/purge-cluster.yml

when osd devices is a disk partition, ceph-disk zap "{{ item }}" will not work.
Check the osd device type first, is the osd device is a raw device, using ceph-disk, else using sgdisk

fix: when osd device is a disk partition

---

roles/ceph-osd/tasks/activate_osds.yml
tests/functional/tests/osd/test_osds.py

ceph-disk is responsable for enabling the unit file if needed. Actually
since https://github.com/ceph/ceph/pull/12241 it seems that it's not
even needed. On an event of a restart, udev rules will be trigger and
they will ceph-disk activate the device too so the 'enabled' is not
needed.
Closes: https://github.com/ceph/ceph-ansible/issues/1142

osd: do not enable osd@id unit file

---

roles/ceph-common/handlers/main.yml

OSDs get started by ceph-disk before the ceph.conf file is written
with a crush location. That results in a crush map without configured
crush location.
To prevent this, we have to restart the OSDs during the initial setup
after the crush location was added to the ceph.conf file.

Restart OSDs during initial setup when crush location is used

---

roles/ceph-osd/tasks/check_devices_auto.yml

We forgot to handle the case where "check if any of the raw partitions
are mounted" task gets skipped.

osd: fail check mount partition if not skipped

---

group_vars/all.yml.sample
profiles/rgw-keystone-v2
profiles/rgw-keystone-v3
profiles/rgw-radosgw-static-website
profiles/rgw-usage-log
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/generate_ceph_conf.yml
roles/ceph-common/templates/ceph.conf.j2

This commit introduces a new directory called "profiles" which
contains some set of variables for a particular use case. These profiles
provide guidance for certain scenarios such as:
- configuring rgw with keystone v3
Signed-off-by: Sébastien Han seb@redhat.com

profiles: introducing cluster profiles

---

infrastructure-playbooks/make-osd-partitions.yml

if osd using a partition, and the disk has partitioned manually,  the partition's ownership should be changed to ceph:ceph. 
Otherwise ceph-disk activate will be failed for something permission denied error

change the partition's ownership

---

infrastructure-playbooks/make-osd-partitions.yml

nvme disk's partition name has a 'p' between diskname and partition index

fix for nvme part path

---

contrib/push-roles-to-ansible-galaxy.sh

The `ceph/ansible-ceph-defaults` repo will need to be created.
This is needed because downstream projects that consume ceph-ansible, such as openstack-ansible, are unable to do so due to #1737 until there is a ceph-defaults breakout role created.

Add ceph-defaults to galaxy role breakout script

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/release-rhcs.yml

For ceph_dev and rhcs installation we need to detect the release since
we do not declare it explicitly. Keeping the default ceph_stable_release
could lead to several things going wrong and some have already been
reported.
Fixes: https://github.com/ceph/ceph-ansible/issues/1712 and https://bugzilla.redhat.com/show_bug.cgi?id=1476210

common: override and autodetect ceph_stable_release

---

roles/ceph-common/tasks/generate_ceph_conf.yml

Writing into /tmp is not always allowed, but we can assume the
fetch_directory is writable.

ceph-common: render ceph_conf_overrides into fetch_directory

---

tests/functional/centos/7/lvm-osds/group_vars/all
tests/functional/lvm_setup.yml

When you udpate to the latest version of the centos/7 box it always puts
the OS on /dev/sda, so do not use it as an OSD.

tests: do not use /dev/sda in the lvm scenario

---

group_vars/mons.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml

The openstack_keys structure now supports a key called mode
whose value is a string that one could pass to chmod to set
the mode of the key file. The ansible file module applies the
mode to all openstack keys with this property.
Fixes: #1755

Allow user to specify the mode of the openstack keys

---

roles/ceph-mon/tasks/openstack_config.yml

The original fix to issue #1755 only set the permissions on
the monitors to which the key was copied, but not the original
monitor where the key was created. Thus, we use a separate task
to set the permission of the key.

Set the permissions mode on all of the OpenStack keys

---

roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

This install the package `rbd-mirror` as it is not installed for rbdmirror nodes.

ceph-common: install base package to provide ceph CLI

---

roles/ceph-mds/tasks/docker/enable_multimds.yml
roles/ceph-mds/tasks/docker/main.yml

This is under the MDS role instead of the mon role because that role
does not create the filesystem under docker.
Signed-off-by: Douglas Fuller <dfuller@redhat.com>

ceph-mds: Enable multimds under docker

---

group_vars/mdss.yml.sample
group_vars/mgrs.yml.sample
group_vars/mons.yml.sample
group_vars/osds.yml.sample
group_vars/rbd-mirrors.yml.sample
group_vars/rgws.yml.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mds/templates/ceph-mds.service.d-overrides.j2
roles/ceph-mgr/defaults/main.yml
roles/ceph-mgr/tasks/pre_requisite.yml
roles/ceph-mgr/templates/ceph-mgr.service.d-overrides.j2
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-mon/templates/ceph-mon.service.d-overrides.j2
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/start_osds.yml
roles/ceph-osd/templates/ceph-osd.service.d-overrides.j2
roles/ceph-rbd-mirror/defaults/main.yml
roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.d-overrides.j2
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/start_radosgw.yml
roles/ceph-rgw/templates/ceph-rgw.service.d-overrides.j2

ceph-mon can fail to start under certain circumstances (for example,
when running in a container) because the default systemd service
configuration causes namespace issues.
To work around this we can override the system service settings by
placing an overrides file in the ceph-mon@.service.d directory. This can
be generic so as to allow any potential changes required to the ceph-mon
service file.
The overrides file is only setup when the "ceph_mon_systemd_overrides"
config_template override variable is specified.

Allow ceph-mon systemd overrides to be specified

---

tests/conftest.py
tests/functional/tests/mon/test_mons.py
tests/functional/tests/osd/test_journal_collocation.py
tests/functional/tests/osd/test_osds.py
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/tests/test_install.py

This adds the tests for ceph-volume's executables, to ensure they are installed when the `lvm` osd scenario is picked up.
It also updates the fixture usage to align with the latest from testinfra

ceph-volume executable tests and testinfra API update

---

roles/ceph-nfs/tasks/pre_requisite.yml

This commit fix the radosgw-admin call during [ceph-nfs : create rgw nfs user] TASK.
radosgw-admin should be use with the cluster name in option if cluster name is not "ceph"
Refer to this issue https://github.com/ceph/ceph-ansible/issues/1785

fix radosgw-admin call with another cluster name than "ceph"

---

roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml

To be properly evaluated the "skipped" conditions must always have the
first place on the list of condition, otherwise the other conditions are
evaluated before and make the task fail.

mon, osd: fix skipped condition

---

infrastructure-playbooks/purge-cluster.yml

We now purge block db and/or wal partitions if we find any.
Closes: https://github.com/ceph/ceph-ansible/issues/1770

purge: add ability to purge bluestore osd

---

roles/ceph-common/tasks/create_ceph_initial_dirs.yml
roles/ceph-docker-common/tasks/checks.yml
roles/ceph-docker-common/tasks/dirs_permissions.yml
roles/ceph-docker-common/tasks/fetch_configs.yml
roles/ceph-fetch-keys/tasks/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-rbd-mirror/defaults/main.yml
roles/ceph-rbd-mirror/tasks/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml

The rbd-mirror daemon will be HA under luminous and new daemon health
features require a way to uniquely identify rbd-mirror instances.
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

rbd-mirror should use per-host user id keyring

---

roles/ceph-defaults/handlers/main.yml

Problem: task "check for a ceph socket in containerized deployment" will
be skipped if we are not an OSD.
with_items are still evaluated before when conditions so if the task was
skipped the dict will be empty and then fail.
Adding a "not skipped" condition skips the execution of the task.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1482061

ceph-defaults: fix handler for osd container

---

Vagrantfile
group_vars/all.yml.sample
group_vars/mdss.yml.sample
group_vars/mgrs.yml.sample
group_vars/mons.yml.sample
group_vars/osds.yml.sample
group_vars/rgws.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-defaults/defaults/main.yml
tests/functional/centos/7/bluestore/group_vars/all
tests/functional/centos/7/bs-crypt-ded-jrn/group_vars/all
tests/functional/centos/7/bs-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-ded-jrn/group_vars/all
tests/functional/centos/7/bs-docker/group_vars/all
tests/functional/centos/7/bs-jrn-col/group_vars/all
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/crypt-ded-jrn/group_vars/all
tests/functional/centos/7/crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-ded-jrn/group_vars/all
tests/functional/centos/7/docker/group_vars/all
tests/functional/centos/7/jrn-col/group_vars/all
tests/functional/centos/7/lvm-osds/group_vars/all
tests/functional/ubuntu/16.04/cluster/group_vars/all

Resolves issue: Multiple RGW Ceph.conf Issue #1258
In multi-RGW setup, in ceph.conf the RGW sections
contain identical bind IP in civetweb line. So this
modification fixes that issue and puts the right IP
for each RGW.
Closes: https://github.com/ceph/ceph-ansible/issues/1767
Signed-off-by: SirishaGuduru SGuduru@walmartlabs.com

Common: changed civetweb line in rgw section(conf)

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-defaults/templates/restart_osd_daemon.sh.j2

This commit eases the use of the
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
playbook. We basically run it with a couple of pre-tasks and then we let
the playbook run the docker roles.
It obviously expect to have proper variables configured in order to
work.

switch-from-non-containerized-to-containerized: simplify

---

docs/source/osds/scenarios.rst
infrastructure-playbooks/purge-cluster.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/check_mandatory_vars.yml
roles/ceph-osd/tasks/scenarios/lvm.yml
tests/functional/centos/7/lvm-osds/group_vars/all
tox.ini

To add this support, restructuring of ``lvm_volumes`` was necessary. The new format provides more flexibility in regards to how you define your lvm-based OSDs.
This also adds a ``purge_lvm_osds`` testing scenario to ensure it works correctly.
Fixes: https://github.com/ceph/ceph-ansible/issues/1787

adds purge support for the lvm_osds osd scenario

---

infrastructure-playbooks/rolling_update.yml

In our test case we don't have any pgs, thus the check fails. The check
always returns an empty array, which makes the comparaison failing.

rolling update: skip pg check if num_pgs = 0

---

roles/ceph-mon/tasks/docker/main.yml

Before this commit we were forcing ipv4 which might not be available.
Now setting ip_version to ipv4 or ipv6 will give you the right support.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1484189

ceph-mon: remove hardcoded ipv4 in containers

---

site.yml.sample

Before this patch we couldn't use --limit properly to only interact with
a particular set of hosts. We basically always required to have ceph-mon
role being played to properly get facts and then build the ceph.conf.
Now, the current running host will get the facts from the machines that
are not part of the current play. This is achieved with the help of the
new option delegate_facts, for more info see:
http://docs.ansible.com/ansible/latest/playbooks_delegation.html#delegated-facts

site: delegate fact to all the hosts

---

ceph-ansible.spec.in

Fixes:
+ cp -pr README.md /builddir/build/BUILDROOT/ceph-ansible-3.0.0-0.rc3.62.gaadac71.el7.x86_64/usr/share/doc/ceph-ansible-3.0.0
cp: cannot stat 'README.md': No such file or directory

rpm update the DOC section to point to rst

---

roles/ceph-config/tasks/main.yml

There should be no need to use sudo when writing or using these files.
It creates and issue when the user running ansible-playbook does not
have sudo privs.

ceph-config: when using local_action set become: false

---

roles/ceph-mon/tasks/docker/main.yml
roles/ceph-nfs/tasks/pre_requisite.yml

Some deployments can't copy infrastructure playbooks outside of the
infrastructure-playbooks directory. Thus they use ANSIBLE_ROLES_PATH to
overcome this. However some roles have 'playbook_dir' hardcoded, which
results in wrong path since the execution comes from
infrastructure-playbooks. Basically the role triggered by a playbook
from infrastructure-playbooks believes that the roles are in
infrastructure-playbooks/roles. This commit fixes that.

ceph-mon: detect ANSIBLE_ROLES_PATH if present

---

infrastructure-playbooks/rolling_update.yml

Prior to this patch, we were applying the osd flags like this:
"
General pre tasks
Set flags
Upgrade OSDs on a host
Unset flags <-- this triggers pending scrub to start
Set flags
Upgrade OSDs on a hosts
Unset flags <-- this triggers pending scrub to start
.
.
.
General post tasks
"
Now instead, we apply the flag once before starting the OSD update and
unset them once the last OSD is finished.
"
General pre tasks
Set flags and wait for any scrubs to finish
Upgrade OSDs on a host
Upgrade OSDs on a host
.
.
.
Unset flags
General post tasks
"

rolling_update: nicer way to set osd flags

---

roles/ceph-docker-common/tasks/fetch_configs.yml

Keys should only be readable and writable by their respective owners and that's all.
Closes: https://github.com/ceph/ceph-ansible/issues/1760

ceph-docker-common: apply 0600 to key permissions

---

tox.ini

This is mostly important in rhcs testing so that our tests can use
packages installed on the distro.

tests: always use sitepackages=True

---

roles/ceph-defaults/handlers/main.yml

with_items is evaluated before the when condition so if the task that
registers the 'results' is skipped the task will fail with:
{"failed": true, "msg": "'dict object' has no attribute 'results'"}
Defaulting to an empty array fixes the issue.
Reverts: abdd66619e1d5c94f74e994bff667b5ccc6b529f
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1482061

handler: default to empty array if task skipped

---

roles/ceph-docker-common/tasks/fetch_configs.yml

The list can not be evaluated properly if it containers '[]', which is
the case when using the filter "default([])". To fix this, we have to
properly merge the lists.
This is fixing the issue: "list object has no element 1"

ceph-docker-common: fix empty array

---

roles/ceph-docker-common/tasks/main.yml
roles/ceph-docker-common/tasks/release.yml

By detecting the ceph version running in the container we can easily
apply conditions like:
ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous
We do that already, in ceph-docker-common/tasks/fetch_configs.yml.
This fixes the error:
```
TASK [ceph-docker-common : register rbd bootstrap key]
******************************************************
fatal: [magna005]: FAILED! => {"failed": true, "msg": "The conditional
check 'ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous'
failed. The error was: error while evaluating conditional
(ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous):
'dict object' has no attribute 'dummy'\n\nThe error appears to have been
in
'/home/ubuntu/ceph-ansible/roles/ceph-docker-common/tasks/fetch_configs.yml':
line 2, column …
```

ceph-docker-common: detect ceph version

---

infrastructure-playbooks/purge-cluster.yml

this enhancement allows purge-cluster.yml to handle sites with **osd_auto_discovery: true** .  Rather than use **devices** var to zap OSD data partitions, we find these partitions in the same way we find other types of partitions.  It was tested both with both **osd_scenario: non-collocated + osd_auto_discovery: false**  , and also with **osd_scenario: collocated + osd_auto_discovery: true** .
Since the **devices** var is not used, we don't need to clear it for **osd_scenario: lvm** either.

dont use devices var anymore, works for osd_auto_discover

---

site-docker.yml.sample

Now we can use --limit on the container deployment too. This is useful
while deploying client nodes.
e.g: ansible-playbook -i inventory -l clients site-docker.yml.sample

site-docker.yml.sample: delegate facts

---

roles/ceph-common/tasks/installs/configure_redhat_repository_installation.yml

There is no need to show a "changed" at the end of the play for a
"command" module task.

ceph-common: remove useless changed task

---

roles/ceph-osd/tasks/scenarios/lvm.yml
tests/conftest.py
tests/functional/centos/7/lvm-osds/group_vars/all
tests/functional/lvm_setup.yml
tests/functional/tests/osd/test_osds.py

This adds support to the lvm_journals scenario so that you can use an lv for a journal. It also modifies the test so that it uses a partition for the other journal instead of a raw device, as ceph-volume is changing to not allow raw devices for journals.

lvm-osds: test with a partition and an lv as journals

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/templates/ceph-radosgw.service.j2

This patch adds passing the RGW_CIVETWEB_IP to the docker
container. This IP defaults to the value of radosgw_civetweb_bind_ip.
radosgw_civetweb_bind_ip default to ipv4.default
Without this value, the RGW containter will bind to 0.0.0.0

Update ceph_rgw_docker_extra_env to add bind ip

---

roles/ceph-rgw/tasks/start_radosgw.yml

The ceph RGW systemd services are actually named "ceph-radosgw" and not
"ceph-rgw", this patch fixes that for the systemd overrides file.

Fix RGW systemd directory

---

tox.ini

Luminous is out so let's test it instead of Kraken.

ci: test luminous

---

tests/functional/centos/7/bluestore/group_vars/clients
tests/functional/centos/7/cluster/group_vars/clients

Needed when user_config is set to true

client: copy admin key so we can create pools and keys

---

infrastructure-playbooks/shrink-mon.yml

Monitor removal from the monmap is not immediate, so let's wait a little
bit and then fail if the monitor is still in the monmap.
We try twice in total with 10 sec intervals.

shrink-mon: wait a little bit for the mon to be out

---

roles/ceph-docker-common/defaults/main.yml

Logging inside the container is not useful since it writes to the
overlayfs partition, resulting in potential performance degradation on
the container.
If you need to check the logs, just look at journald.

ceph-docker-common: do not log inside the container
