ceph/ceph-ansible

Vagrantfile

See: https://github.com/mitchellh/vagrant/issues/5048.
Closes: #172

Fix vagrant deployment for vagrant version > 1.7

---

group_vars/all
group_vars/mons
group_vars/osds

Updating each group_vars file to reflect the content of each role
default variables.
Closes: #169

Update group_vars files to match roles defaults vars

---

roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/main.yml

Fix ICE installation

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/os_check.yml
roles/ceph-common/tasks/os_tuning.yml
roles/ceph-common/tasks/prerequisite_ice.yml

Depending on the OS you are runnning on you should be able to configure
these values.
Re-ordering file for clarity as well.

Make OS tuning var configurable and file re-ordering

---

group_vars/osds
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/templates/osd.conf.j2

Still WIP, @mwheckmann free to test
As requested by #162
Current known issue, since ceph.conf gets modified during every single
run (at the end during the merge) so this will restart ceph daemons.

WIP: Implement OSD sections

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Add debug options for Ceph daemons.

Enable Ceph daemons debug options

---

.travis.yml
tests/inventory
tests/test.yml

Add test to the playbooks

---

roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/openstack_config.yml

Creates pools, keys and users.

Ability to populate OpenStack installation

---

roles/ceph-radosgw/files/s3gw.fcgi
roles/ceph-radosgw/tasks/install_debian.yml
roles/ceph-radosgw/tasks/install_redhat.yml
roles/ceph-radosgw/templates/rgw.conf
roles/ceph-radosgw/templates/s3gw.fcgi.j2

Fix Rados Gateway socket path

---

Vagrantfile

Fix Vagrant vars for MDS and RGW

---

README.md
roles/ceph-common/defaults/main.yml
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/docker.yml
roles/ceph-mds/tasks/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/docker.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-radosgw/defaults/main.yml
roles/ceph-radosgw/tasks/docker.yml
roles/ceph-radosgw/tasks/main.yml
roles/ceph-radosgw/tasks/pre_requisite.yml
roles/ceph-radosgw/tasks/start_radosgw.yml
site.yml

WIP! Still figuring out how to implement this :)

Docker support

---

tests/README.md
tests/validate-ceph.yml
tests/validate-mds.yml
tests/validate-mon.yml
tests/validate-rados.yml
tests/validate-rbd.yml
tests/validate-rgw.yml

WIP: first implementation of functional tests

---

maintenance.yml
roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/prerequisite_ice.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-radosgw/tasks/install_debian.yml

Improve YAML syntax

---

cluster-os-migration.yml

Add support for RGW

---

roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/os_tuning.yml
roles/ceph-common/tasks/prerequisite_ice.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/osd_directory.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/raw_multi_journal.yml
roles/ceph-osd/tasks/zap_devices.yml
roles/ceph-radosgw/tasks/install_debian.yml
roles/ceph-radosgw/tasks/install_redhat.yml
roles/ceph-restapi/tasks/main.yml
roles/ceph-restapi/tasks/pre_requisite.yml

We only want to see things that really changed after a play completes.

Only change when the task returns false

---

roles/ceph-common/defaults/main.yml

Use last Ceph release Hammer

---

Vagrantfile
roles/ceph-common/defaults/main.yml
site.yml

Add another warning for cephx signatures

Add ceph-common role to client machines

---

Vagrantfile
vagrant_variables.yml.sample

Ability to configure the memory

---

library/ceph_facts

Example usage
ansible all -i hosts.foo -m ceph_facts
See source for additional examples

Import of ceph_facts module

---

Vagrantfile
group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/check-mandatory-vars.yml
roles/ceph-common/tasks/main.yml

* fix the Vagrantfile ruby check
* fix the variable positions
Bring more mandatory variables and try to separate Vagrant vars from the
playbook vars.

Fix multiple things

---

group_vars/all
roles/ceph-radosgw/tasks/start_radosgw.yml

Fix startup and move vars to group_vars

Fix radosgw startup on RedHat systems

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-radosgw/tasks/main.yml
roles/ceph-radosgw/tasks/openstack-keystone.yml

Add support for Rados Gateway configuration with Keystone

---

roles/ceph-restapi/tasks/main.yml

simplify running process check

---

roles/ceph-mon/tasks/deploy_monitors.yml

This looks like a bug, if not, it should have a comment that tells why

Directory should be executable

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Here is everything in one pull request

Add rbd_concurrent_management_ops

---

install-ansible.sh

Rename bootstrap ansible to install

---

install-ansible.sh

Minor change: Install latest Ansible from official PPA

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Add more param to reduce the scrub overhead.

Reduce scrubbing impact

---

vagrant_variables.yml.sample

Change fedora box example

---

vagrant_variables.yml.sample

Fix ubuntu box images name

---

roles/ceph-osd/tasks/journal_collocation.yml

Followup on #287

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/install_on_debian.yml
roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/os_tuning.yml
roles/ceph-common/tasks/prerequisite_ice.yml
roles/ceph-mds/tasks/docker.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/docker.yml
roles/ceph-osd/tasks/journal_collocation.yml
roles/ceph-osd/tasks/osd_directory.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/raw_multi_journal.yml
roles/ceph-osd/tasks/zap_devices.yml
roles/ceph-radosgw/tasks/docker.yml
roles/ceph-radosgw/tasks/install_debian.yml
roles/ceph-radosgw/tasks/install_redhat.yml
roles/ceph-radosgw/tasks/main.yml
roles/ceph-radosgw/tasks/pre_requisite.yml
roles/ceph-radosgw/tasks/start_radosgw.yml
roles/ceph-restapi/tasks/main.yml
roles/ceph-restapi/tasks/pre_requisite.yml

Add more visibility for the 'when' statement.

WIP: Cosmetic

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/haproxy/defaults/main.yml
roles/haproxy/templates/precise/haproxy.cfg

Nice to be able to use different group-names than the defaults.

make group names definable

---

roles/ceph-restapi/defaults/main.yml
roles/ceph-restapi/tasks/docker.yml
roles/ceph-restapi/tasks/main.yml
roles/ceph-restapi/tasks/start_restapi.yml

Add restapi container deployment

---

group_vars/restapis

Add group_vars for restapi

---

README.md

Add vagrant demo video

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml

Improve handlers

---

roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-radosgw/tasks/start_radosgw.yml

closes: #297, #264, #265 and #301 

Fixes rgw and mon startup on red hat

---

roles/ceph-common/defaults/main.yml

Tiny fix for a variable undeclared

---

Vagrantfile
group_vars/all
group_vars/mons
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/install_on_redhat.yml
roles/ceph-common/tasks/prerequisite_rh_storage.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/main.yml
site.yml

Now we don't need to activate the services through a variable. If the
role is activated in the inventory, actions will occur automatically.

Cleanup daemon declaration

---

site.yml

Only activate restpi when needed

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/install_on_debian.yml

Add more repo source for stable

---

group_vars/all
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Add `rbd_default_features` and `rbd_default_map_options`.

Add more client options

---

roles/ceph-common/tasks/prerequisite_rh_storage_cdn_install.yml

If we don't ignore errors here, the node will get skipped for the rest
of the playbook...

Ignore errors

---

README.md

Add bare metal video

---

roles/ceph-mon/tasks/deploy_monitors.yml

Fix monitor key generation

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

Add primary affinity option

---

roles/ceph-common/meta/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mon/meta/main.yml
roles/ceph-radosgw/meta/main.yml
roles/ceph-restapi/meta/main.yml

First steps to Ansible Galaxy

---

roles/ceph-mon/tasks/start_monitor.yml

Fix ceph version return code issue

---

contrib/splitup.yml

Fix the branch update

---

roles/ceph-common/tasks/main.yml

Create fetch directory if it doesn't exist.

---

roles/ceph-common/LICENSE
roles/ceph-common/README.md
roles/ceph-mds/LICENSE
roles/ceph-mds/README.md
roles/ceph-mon/LICENSE
roles/ceph-mon/README.md
roles/ceph-osd/LICENSE
roles/ceph-osd/README.md
roles/ceph-restapi/LICENSE
roles/ceph-restapi/README.md
roles/ceph-rgw/LICENSE
roles/ceph-rgw/README.md

Add READMEs for each roles

---

roles/ceph-common/README.md
roles/ceph-mds/README.md
roles/ceph-mon/README.md
roles/ceph-osd/README.md
roles/ceph-restapi/README.md
roles/ceph-rgw/README.md

Add contribution note

---

roles/ceph-mds/tasks/docker.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-osd/tasks/scenarios/docker.yml
roles/ceph-restapi/tasks/docker.yml
roles/ceph-rgw/tasks/docker.yml

Fix pip module invocation

---

roles/ceph-rgw/tasks/installs/install_debian.yml
roles/ceph-rgw/tasks/installs/install_redhat.yml

Fix templates file path

---

group_vars/mons.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/tasks/main.yml

We can now deploy 3 mons on 3 different hosts.

Fix multi-mon docker deployment

---

group_vars/osds.sample
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/tasks/main.yml

Re-arrange docker invocation and fix bootstrap

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

Fixes: https://github.com/ceph/ceph-docker/issues/19

Fix the conntrack_max

---

group_vars/mdss.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-mds/tasks/main.yml

Re-arrange docker invocation and fix bootstrap mds

---

group_vars/mdss.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml

Fix dummy mistakes with variables

---

cluster-os-migration.yml
contrib/splitup.yml
purge-cluster.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/scenarios/docker.yml
roles/ceph-restapi/tasks/start_restapi.yml
roles/ceph-rgw/tasks/installs/install_debian.yml
roles/ceph-rgw/tasks/start_radosgw.yml
rolling_update.yml

Changed ignore_errors to failed_when so the output doesn't show in
red. Also changed a few instances of the shell module to stat.

Failed_when and stat module

---

cluster-os-migration.yml
contrib/splitup.yml
purge-cluster.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/scenarios/docker.yml
roles/ceph-restapi/tasks/start_restapi.yml
roles/ceph-rgw/tasks/installs/install_debian.yml
roles/ceph-rgw/tasks/start_radosgw.yml
rolling_update.yml

Revert "Failed_when and stat module"

---

cluster-os-migration.yml
contrib/splitup.yml
purge-cluster.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml
roles/ceph-mds/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/docker.yml
roles/ceph-mon/tasks/docker/fetch_configs.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/osd_fragment.yml
roles/ceph-osd/tasks/scenarios/docker.yml
roles/ceph-restapi/tasks/start_restapi.yml
roles/ceph-rgw/tasks/installs/install_debian.yml
roles/ceph-rgw/tasks/start_radosgw.yml
rolling_update.yml

Changed ignore_errors to failed_when so the output doesn't show in
red.

Failed_when instead of ignore_errors

---

group_vars/osds.sample
roles/ceph-osd/defaults/main.yml

Remove zap variables

---

roles/ceph-common/README.md

Update ceph-common readme

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Add bool for osd_group_name in group_names for device checks.

Check to ensure device checks only happen on osds

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

Make package dependencies configurable

---

README.md
group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

Get Ceph from distro repository (redhat-based)

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

Do not check for devices when device autodetect

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rgw_on_debian.yml
roles/ceph-common/tasks/installs/install_rgw_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_ice.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_iso_install.yml

I validated this on Debian and Ubuntu, but I wouldn't mind a 
second eye since this is a large refactor. The only module that 
didn't play nice with the new styling was `local_action` in `main.yml`.
Partially solves #355

Update ceph-common styling

---

vagrant_variables.yml.sample

Signed-off-by: Sébastien Han <sebhan@cisco.com>

Add a debian img example

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/fetch_configs.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

Create missing directories when deploying with docker

---

roles/ceph-mds/tasks/docker/checks.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/checks.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/checks.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/checks.yml
roles/ceph-rgw/tasks/docker/main.yml

Add safety checks prior to deploy a cluster in containers

---

roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mds/tasks/docker/selinux.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/selinux.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/selinux.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/selinux.yml

Add proper permission for selinux

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

Install pip before using it

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-restapi/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/pre_requisite.yml

Add support for infernalis, rework dirs and files permissions.
Fix mds pools creation.

Use new Infernalis release

---

roles/ceph-common/tasks/checks/check_system.yml

Fail for unsupported ansible version

---

roles/ceph-common/defaults/main.yml

Reserve some memory

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/start_radosgw.yml

Support infernalis for rh storage

---

group_vars/all.sample

Change update group_vars ivetweb port

---

roles/ceph-restapi/tasks/pre_requisite.yml

Fix condition logic for infernalis in restapi

---

install-ansible.sh

Fix install for rhel

---

install-ansible.sh

Fix test for Red Hat Enterprise Server and add a default case.

Fix failing install-ansible test

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml

Clarify ceph_origin usage

---

roles/ceph-common/defaults/main.yml

vm.min_free_kbytes was in bytes not in kbytes.

Changed vm.min_free_kbytes to 4 GB

---

contrib/splitup.yml
plugins/actions/config_template.py
roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/main.yml

Necessary change to work on ansible v2

---

Vagrantfile
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml
vagrant_variables.yml.atomic

- Add centos/atomic-host
- Tagging yum tasks and skip when provisioning CentOS Atomic host.

WIP: initial steps to provision CentOS Atomic host

---

group_vars/all.sample

update group_vars/all.sample with min_free_kbytes

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

use python-pip and not pip
closes #499 

Fix pip package name on debian

---

roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rgw_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

fixes the `importError: No module named yum` see here:
https://jenkins.ceph.com/job/ceph-ansible-pull-requests/45/console

use dnf when yum is not available

---

test.yml
tests/inventories/single-machine.yml

CI does not use root, but sudo will do fine

---

roles/ceph-restapi/meta/main.yml

ceph-restapi: fix meta file

---

example-ansible-role-requirements.yml

add a galaxy dependency file example

---

contrib/splitup.yml

contrib: add the ceph-agent

---

purge-cluster.yml

Rewritten purge-cluster playbook. 
Tested with Ceph Hammer and Infernalis on CentOs 7 and Ubuntu 14.04 with Ansible 2.0.1.0

Rewrite purge-cluster playbook

---

README.md
Vagrantfile
vagrant_variables.yml.sample

```bash
$ vagrant up --no-provision --provider=parallels
$ vagrant provision
.......
PLAY RECAP ********************************************************************
mds0                       : ok=53   changed=9    unreachable=0    failed=0
mon0                       : ok=114  changed=17   unreachable=0    failed=0
mon1                       : ok=114  changed=17   unreachable=0    failed=0
mon2                       : ok=114  changed=17   unreachable=0    failed=0
osd0                       : ok=99   changed=10   unreachable=0    failed=0
osd1                       : ok=99   changed=10   unreachable=0    failed=0
osd2                       : ok=99   changed=10   unreachable=0    failed=0
rgw0                       : ok=57   changed=10   unreachable=0    failed=0
```

Added support parallels provider

---

contrib/splitup.yml

contrib: add ceph-fetch-keys

---

roles/ceph-mds/tasks/pre_requisite.yml

ceph-mds: enable systemd unit file

---

purge-cluster.yml

Signed-off-by: KGoreczny <krzysztof.goreczny@intel.com>

Add zap journal devices for raw multi journal scenario in purge-cluster

---

roles/ceph-common/tasks/misc/system_tuning.yml

ceph-common: only change task when false

---

site.yml.sample

default serial deploying mons

---

roles/ceph-agent/meta/main.yml

ceph-agent: add dependency section for the galaxy

---

roles/ceph-agent/meta/main.yml
roles/ceph-fetch-keys/meta/main.yml

ceph-agent and key fix platform RHEL key

---

README.md

README: how to submit patches

---

generate_group_vars_sample.sh

generate sample: fix sed on OSX

---

contrib/splitup.yml

contrib: fix ceph-common role name

---

group_vars/all.sample

ceph-common: update group_vars

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml

ceph-mon/mds: fix fqdn

---

Vagrantfile
roles/ceph-common/tasks/main.yml
vagrant_variables.yml.sample

ceph-common: fix mon startup for dev installation

---

vagrant_variables.yml.sample

vagrant: add other boxes for centos and ubuntu

---

README.md

documention on how to configure ceph.conf using ceph_conf_overrides

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

ceph-common: fix ceph install for centos distros

---

roles/ceph-osd/tasks/check_devices.yml

ceph-osd: fix regex to check partitions

---

roles/ceph-osd/tasks/osd_fragment.yml

fix fragment for osd directory scenario

---

purge-cluster.yml

purge: clean install cache and purge rgw

---

group_vars/mons.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/templates/ceph-mon.service.j2

ceph-mon: docker fix run on atomic host

---

roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

fixing the can't open /var/lib/ceph/bootstrap-osd/ceph.keyring: can't
open /var/lib/ceph/bootstrap-osd/ceph.keyring: (13) Permission denied

ceph-docker: fix permissions on directories

---

roles/ceph-rbd-mirror/LICENSE

ceph-rbd-mirorr: add license file

---

contrib/splitup.yml

contrib: update with ceph-rbd-mirror

---

roles/ceph-rbd-mirror/README.md

rbd-mirror: fix readme title

---

roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml

docker: do not hardcode image and user name

---

test.yml

This should fix all the failures from this commit 2d21f741f53a2c05b5d1f410725cfdd8ddcaf518

remove agent role, no packages for it upstream yet

---

roles/ceph-common/tasks/main.yml

Need to use a template, not a bare variable name.

Fix creation of RBD client directories

---

roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
vagrant_variables.yml.atomic

some fixes to run containers on Atomic

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/facts.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/start_monitor.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
roles/ceph-rgw/tasks/start_radosgw.yml

Fixes issue #736 
Adds vars all the way up to kraken

Define readable vars for Ceph version comparisons

---

roles/ceph-mds/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-osd/tasks/docker/main.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/main.yml

Docker fixes and cleanups

---

take-over-existing-cluster.yml

take-over: remove the connection local

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

Mounts /run when executing osd container

---

roles/ceph-mds/tasks/docker/pre_requisite.yml

Fixes to make the ceph-mds role work with Docker

Docker fixes for MDS

---

group_vars/all.sample
group_vars/common-coreoss.sample
roles/ceph-common/tasks/facts.yml
roles/ceph-mds/tasks/pre_requisite.yml
roles/ceph-mon/tasks/start_monitor.yml

Several fixes

---

group_vars/all.sample
group_vars/common-coreoss.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

ceph: use jewel release

---

README.md
contrib/splitup.yml
localrepo-site.yml.sample
roles/ceph-common-coreos/README.md
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml

Signed-off-by: Li Peng <lip@dtdream.com>

cleanup: fix typos and inappropriate variable names

---

roles/ceph-osd/tasks/check_devices.yml

try to zap a device again if sgdisk fails on the first try

---

roles/ceph-mon/tasks/docker/create_configs.yml

this fixes the wrong permission on /etc/ceph
@leseb

don't recreate /etc/ceph with wrong mode

---

README.md

README: add some doc for use_server_package_split

---

group_vars/all.sample
group_vars/clients.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/ceph.conf.j2

ceph-rgw: implement num_threads for civetweb

---

Vagrantfile

When testing ceph-ansible using Vagrant on an OpenStack infrastructure such as OS1, it is recommended that the VMs created have unique names with the OpenStack username in the VM name.  This allows the infrastructure admins to easily track down the owners of VM instances.
This change will prefix the VM names that Vagrant creates with the OpenStack username.
Additionally, a small change was made to set the cluster_network and public_network variables in the docker case as it is in the non-docker case.

docker: Prefix OpenStack VM names to prevent collision

---

roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml

ceph-common: specify file path for repo key

---

group_vars/all.sample

Specify unit to use for the journal_size parameter.

Specify OSD journal size unit

---

roles/ceph-common/templates/redhat_storage_repo.j2

See: https://bugzilla.redhat.com/show_bug.cgi?id=1339439
Resolves: rhbz#1339439

remove the gpgkey line from the red hat storage repo template

---

roles/ceph-osd/tasks/scenarios/bluestore.yml
roles/ceph-osd/tasks/scenarios/journal_collocation.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

Fixes: issue #835
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1342117

Do not ignore ceph-disk issues

---

group_vars/all.docker.sample
group_vars/osds.sample
roles/ceph-common/templates/ceph.conf.j2
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

in containerized deployment, use the right interface name variable in mon; remove one line inline files
cleanup on docker osd tasks
@alfredodeza @leseb

some fixes for container deployment

---

README.md
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

- be explicit on Atomic VirtualBox instruction
- fix mds/rgw containerized deployment

be explicit on Atomic VirtualBox instruction

---

purge-docker-cluster.yml

Minor fix for missing quotes that I encountered while trying to run this playbook.

docker: fix missing quotes

---

roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/templates/ceph-mon.service.j2

And removing symbolic links and fixing systemctl enable on CoreOS.

Adding option to change kv_port and docker tag

---

roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-osd/tasks/pre_requisite.yml

Add DNF for RedHat

---

install-ansible.sh

install-ansible: exit if ansible is installed

---

README.md

README: add a FAQ

---

rolling_update.yml

refactoring the current code to apply the default syntax style that is
used in the entire playbook.

rolling-upgrade: cleanup and cosmetic

---

roles/ceph-common/templates/redhat_storage_repo.j2

Use more descriptive names for the local RHCS Yum repositories.

ceph-common: update names for local RHCS repos

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

These are some of the errors I found running against my own setup with the roles/plugins, which I ported back into the repository. I hope you find them satisfactory.
Thanks again for the awesome work, we're still using the majority of this in volplugin and it's very useful.

Container fixups

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-nfs/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

Install docker-py in version matched to ansible docker module
Signed-off-by: KGoreczny <krzysztof.goreczny@intel.com>

Fix docker deployment for Ansible 2.1

---

roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/templates/ceph-osd.service.j2

Adding option to change etcd port and docker image tag. Removing symbolic links, fixing enabling of systemd unit files. Migrating from docker module to shell module to ensure osd disk prepare finishes before launching next task.

Fixing containerized deployment with kv

---

roles/ceph-common/tasks/checks/check_firewall.yml

Only check ports if NMAP exists

---

roles/ceph-common/tasks/checks/check_system.yml

common: prepare arm support

---

ceph-aio-no-vagrant.sh
install-ansible.sh

we can now chose the install source

aio: more flexible script

---

purge-docker-cluster.yml

- Reorder package removal steps
- Remove package dependencies after package is removed

Updates to containerized purge cluster playbook

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/misc/system_tuning.yml

remove ability to disable swap

---

group_vars/osds.sample
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-dedicated-journal.yml
roles/ceph-osd/tasks/scenarios/dmcrypt-journal-colocation.yml
roles/ceph-osd/tasks/scenarios/dmcrypt.yml

add the ability to encrypt osd data store using dm-crypt

ceph-osd: add dmcrypt scenario

---

roles/ceph-rbd-mirror/tasks/docker/selinux.yml
roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2

- Remove /var/lib/ceph dependencies
- Add support for rbd-mirror image tag

Updates for containerized rbd-mirror role

---

roles/ceph-common/templates/ceph.conf.j2
roles/ceph-common/templates/mon_addr_address.j2
roles/ceph-common/templates/mon_addr_interface.j2

Use a more common description for monitors and remove the sub monitor sections.
Closes: #803 

WIP ceph-common: test mon initial members

---

group_vars/all.sample
roles/ceph-common/README.md
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_cdn_install.yml
roles/ceph-common/tasks/pre_requisites/prerequisite_rh_storage_iso_install.yml
roles/ceph-common/templates/redhat_storage_repo.j2

rename ceph_stable_rh_storage to ceph_stable_rhcs

---

group_vars/nfss.sample
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/templates/ganesha.conf.j2
roles/ceph-nfs/defaults/main.yml
roles/ceph-nfs/tasks/docker/copy_configs.yml
roles/ceph-nfs/tasks/docker/create_configs.yml
roles/ceph-nfs/tasks/docker/dirs_permissions.yml
roles/ceph-nfs/tasks/docker/fetch_configs.yml
roles/ceph-nfs/tasks/docker/main.yml
roles/ceph-nfs/tasks/pre_requisite.yml
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml
roles/ceph-rgw/tasks/docker/main.yml

Add support for FSAL_RGW to the NFS gateway.  Both standard and
containerized versions are supported.

NFS for FSAL_RGW

---

group_vars/all.docker.sample
group_vars/all.sample
group_vars/nfss.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/templates/ganesha.conf.j2
roles/ceph-nfs/defaults/main.yml
roles/ceph-nfs/tasks/docker/create_configs.yml
roles/ceph-nfs/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml

- Move fsal_rgw config to ceph-common, as it's shaered with ceph-rgw
- Update all.docker.sample with NFS config

NFS fixups

---

infrastructure-playbooks/purge-docker-cluster.yml

- Added support for purging containerized rbd-mirror node

Update for containerized purge cluster playbook

---

site-docker.yml.sample

Add ceph-rbd-mirror role to containerized sample playbook

---

infrastructure-playbooks/purge-docker-cluster.yml

Update relative path to include vars

---

roles/ceph-rgw/tasks/docker/copy_configs.yml

- Short-circuit conditional to prevent dereferencing an undefined
dictionary variable

Fix for ceph-rgw role

---

Vagrantfile
vagrant_variables.yml.openstack
vagrant_variables.yml.sample

Solve this error: "Multiple possible networks found, use a Network ID to be more specific."
Signed-off-by: FranBarrera <franbarrera6@gmail.com>

Add network Openstack

---

Vagrantfile
vagrant_variables.yml.openstack

Signed-off-by: FranBarrera <FranBarrera6@gmail.com>

Add floating_ip_pool openstack

---

roles/ceph-mon/tasks/deploy_monitors.yml

deploy_monitors: use python2 for v2 code

---

Vagrantfile
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/templates/ceph.conf.j2
vagrant_variables.yml.linode

This will be used in upcoming performance testing.

vagrant: add support for Linode VMs

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

ability to switch from bare metal to containerized daemons

---

vagrant_variables.yml.atomic

Adding iscsi_gw_vms variable

---

roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_debian.yml

ceph-common: install ceph-fuse on clients

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml

please refer to https://bugzilla.redhat.com/show_bug.cgi?id=1376283

fix non skipped task for ansible v1.9.x

---

install-ansible.sh
roles/ceph-common/tasks/installs/install_on_debian.yml

Fixes an issue with Ansible compilation where no submodules are available, and corrects syntax for Ansible v2.

Debian installation: fix Ansible compilation and correct syntax for Ansible v2

---

group_vars/all.sample
roles/ceph-common/defaults/main.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/secure_cluster.yml

multimds: add commands to enable and set max_mds

---

roles/ceph-common/tasks/installs/debian_ceph_repository.yml

common: add gluster ganesha repo on Debian

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices_auto.yml

osd: fix autodiscovery disk

---

Vagrantfile
vagrant_variables.yml.openstack

Updates to fix running with openstack

---

roles/ceph-common/tasks/installs/install_on_redhat.yml

see: https://bugzilla.redhat.com/show_bug.cgi?id=1382878

common: fix rundep installation

---

infrastructure-playbooks/cluster-os-migration.yml
infrastructure-playbooks/purge-multisite.yml
infrastructure-playbooks/rolling_update.yml

infrastructure-playbooks: fix syntax errors in all playbooks

---

.gitignore
infrastructure-playbooks/README.md
infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

This is a rebase of https://github.com/ceph/ceph-ansible/pull/1047
Fixing: https://bugzilla.redhat.com/show_bug.cgi?id=1388295
Also add some notes in the README on how to run infrastructure
playbooks.

rebased rolling_update: fix wrong indent

---

plugins/actions/_v2_config_template.py

This  PR will resolve issues with ansible >=v2.2 while maintaining compatibility with <2.2.
Signed-off-by: Kevin Carter kevin.carter@rackspace.com

Updated config_template for 2.2 compat

---

roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-nfs/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/docker/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml

Reverts ceph/ceph-ansible#1042

Revert "Change enabling of extras repo for CentOS to use ini_file"

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

Please see the issue (https://github.com/ceph/ceph-ansible/issues/1026) for details

Fix hard-coded group names in include tasks for group variable file names

---

group_vars/all.sample
group_vars/osds.sample
infrastructure-playbooks/purge-cluster.yml
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml

Define it as empty list by default, remove unneccessary 'default([])' checks
Signed-off-by: Eduard Egorov eduard.egorov@icl-services.com

Make {{ devices }} list optional

---

infrastructure-playbooks/rolling_update.yml

rolling update: fix restarts of radosgw

---

roles/ceph-common/templates/ceph.conf.j2

fix python3 compatibility in jinja2 template.

---

roles/ceph-agent/tasks/pre_requisite.yml
roles/ceph-common/tasks/installs/debian_ceph_repository.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/install_rh_storage_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml
roles/ceph-mds/tasks/docker/pre_requisite.yml
roles/ceph-mon/tasks/calamari.yml
roles/ceph-mon/tasks/docker/pre_requisite.yml
roles/ceph-nfs/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/docker/pre_requisite.yml
roles/ceph-osd/tasks/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/docker/pre_requisite.yml
roles/ceph-rbd-mirror/tasks/pre_requisite.yml
roles/ceph-restapi/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/docker/pre_requisite.yml
roles/ceph-rgw/tasks/openstack-keystone.yml

Refactor the code using 'package' module
Fix Issue #520 
(However it doesn't cover all cases because some of them are not refactorable.
Ex: because of diverging packages name between distribution)

Use 'package' module instead of yum, apt and dnf

---

.gitignore

ignore `*.retry` files in general

git: update gitignore

---

README.md

For new comers, it's easier to find irc & the mailing list if we
mention them here.

README: Adding mailing list / irc / github entry points

---

action_plugins

Adding symlink to action_plugins so this works in ansible tower

---

roles/ceph-common-coreos/tasks/install_pip.yml
roles/ceph-common-coreos/tasks/install_pypy.yml

Add support to download pypy and pip via proxy if required

Adding Proxy support

---

infrastructure-playbooks/make-osd-partitions.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_static.yml
roles/ceph-osd/tasks/scenarios/raw_multi_journal.yml

Just simply add a task in scenarios/raw_multi_journal.yml
I tested it locally without problem. But further discussion is welcome to see any better solution.
This addresses #895

Add prepare osd with partition devices in raw_multi_journal

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1408848

common: document "cluster" variable usage

---

tox.ini

tests: test with the latest ansible stable-2.2 branch from github

---

infrastructure-playbooks/purge-cluster.yml
tox.ini

These fixes are in master but were never ported back to the stable-2.1 branch.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1413985

Purge cluster fixes

---

tox.ini

(cherry picked from commit 1a4886a561cb3288f015e97d8adef5309ef55947)

Bump ansible to 2.2.1

---

group_vars/all.docker.yml.sample
roles/ceph-common/tasks/docker/fetch_image.yml
roles/ceph-docker-common/defaults/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mds/tasks/docker/dirs_permissions.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mon/meta/main.yml
roles/ceph-mon/tasks/docker/dirs_permissions.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/meta/main.yml
roles/ceph-nfs/tasks/docker/dirs_permissions.yml
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/meta/main.yml
roles/ceph-osd/tasks/docker/dirs_permissions.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/templates/ceph-osd.service.j2
roles/ceph-rbd-mirror/meta/main.yml
roles/ceph-rbd-mirror/tasks/docker/dirs_permissions.yml
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-restapi/meta/main.yml
roles/ceph-restapi/tasks/docker/dirs_permissions.yml
roles/ceph-restapi/tasks/docker/start_docker_restapi.yml
roles/ceph-rgw/meta/main.yml
roles/ceph-rgw/tasks/docker/dirs_permissions.yml
roles/ceph-rgw/templates/ceph-rgw.service.j2
roles/ceph.ceph-docker-common

Backport of https://github.com/ceph/ceph-ansible/pull/1229

ceph-docker-common backport

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/main.yml
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/cluster/hosts
tests/functional/centos/7/cluster/vagrant_variables.yml
tests/functional/ubuntu/16.04/cluster/hosts
tests/functional/ubuntu/16.04/cluster/vagrant_variables.yml

backport of PR #1146

---

infrastructure-playbooks/purge-cluster.yml

Backport of purge cluster updates

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/rbd_pool.yml
roles/ceph-mon/tasks/rbd_pool_pgs.yml
roles/ceph-mon/tasks/rbd_pool_size.yml

backport of https://github.com/ceph/ceph-ansible/pull/1214

Backport: 'mon: make sure osd_pool_default_size is honoured'

---

Vagrantfile
group_vars/all.docker.yml.sample
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

See commit messages for details.

Docker extra env vars

---

infrastructure-playbooks/purge-cluster.yml
tests/functional/centos/7/journal-collocation/group_vars/all
tox.ini

backport of https://github.com/ceph/ceph-ansible/pull/1250

Backport: 'CI testing updates'

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-common/tasks/create_ceph_initial_dirs.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/main.yml
roles/ceph-osd/tasks/pre_requisite.yml

backport of #1254 
Let's wait until all test pass to merge this one.

Backport: "Osd dir exist and purge fixes #1254"

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/handlers/restart-mds.yml
roles/ceph-common/handlers/restart-mon.yml
roles/ceph-common/handlers/restart-osd.yml
roles/ceph-common/handlers/restart-rgw.yml
roles/ceph-common/handlers/validate-mon.yml
roles/ceph-common/handlers/validate-osd.yml
roles/ceph-common/tasks/generate_ceph_conf.yml
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/dmcrypt-dedicated-journal/group_vars/all
tests/functional/centos/7/dmcrypt-journal-collocation/group_vars/all
tests/functional/ubuntu/16.04/cluster/group_vars/all

Backport: "common: serialise host restart #995"

---

roles/ceph-common/handlers/main.yml

backport: "ceph-common: remove absolute path to handler include files #1266"

---

tests/conftest.py

If no OSDs were created the command would fail and because we were using
check_output it would throw an exception and mark all OSD tests as ERROR.
This keeps tests from running that might tell us why the OSDS were not created.

tests: if no osds are created do not error in conftest.py

---

README.md
group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/validate-osd.yml
roles/ceph-docker-common/tasks/main.yml
roles/ceph-docker-common/tasks/system_checks.yml
roles/ceph-mds/tasks/docker/start_docker_mds.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/tasks/docker/start_docker_nfs.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
roles/ceph-rgw/tasks/multisite/main.yml

We decided these changes were not essential for the 2.1.z release series.

Revert to v2.1.6 (631e6d0fbbb2ddc640a1c57dccb4d998099b5d7b)

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/installs/redhat_ceph_repository.yml

Closes: #1282
Signed-off-by: Shengjing Zhu <zsj950618@gmail.com>

add ceph_mirror variable

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml

purge: ability to purge client role

---

infrastructure-playbooks/rolling_update.yml

Previous use of the stat module didn't work as expected so using the
linux stat command now.
Closes: #1286

rolling-update: detect init system properly

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml

Backport: 'purge: ability to purge client role #1281'

---

infrastructure-playbooks/purge-cluster.yml

Backport: "purge-cluster: do not use ceph-detect-init #1284"

---

infrastructure-playbooks/purge-cluster.yml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1422134
Resolves rhbz#1422134

purge-cluster: remove calamari-server package

---

infrastructure-playbooks/purge-cluster.yml

backport: "purge-cluster: remove calamari-server package #1306"

---

infrastructure-playbooks/purge-cluster.yml

See: https://bugzilla.redhat.com/show_bug.cgi?id=1414647

purge-cluster: also purge dmcrypt dedicated journals

---

infrastructure-playbooks/purge-cluster.yml

backport: "purge-cluster: also purge dmcrypt dedicated journals #1311"

---

roles/ceph-mon/tasks/create_mds_filesystems.yml
roles/ceph-mon/tasks/main.yml

send fs commands to one mon

---

infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/tasks/docker/create_configs.yml
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2
roles/ceph-osd/templates/ceph-osd.service.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-restapi/tasks/docker/start_docker_restapi.yml
roles/ceph-rgw/templates/ceph-rgw.service.j2

harmonize docker names

---

infrastructure-playbooks/make-osd-partitions.yml
roles/ceph-mon/tasks/ceph_keys.yml

load device partition file in directory host_vars
1) if the user define host_vars/hostname.yml load the devices  partition on this file.
2) otherwise load host_vars/default.yml for default

Load a variable file for devices partition

---

roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2

rbd-mirror: fix spelling

---

roles/ceph-restapi/tasks/start_restapi.yml

```
[root@ceph24 ~]# ps aux|grep ceph-rest-api | grep  -v 'grep'
root     2939120  0.0  0.0 1075240 28476 ?       Sl   17:25   0:00 python /bin/ceph-rest-api --conf /etc/ceph/ceph.conf
[root@ceph24 ~]# echo $?
0
[root@ceph24 ~]# pgrep ceph-rest-api
[root@ceph24 ~]# echo $?
1
```
```
---
- name: check if ceph rest api is already started
shell: "pgrep ceph-rest-api"
changed_when: false
failed_when: false
always_run: true
register: restapi_status
- debug:
msg: "{{ restapi_status }}"
- name: start ceph rest api
shell: "nohup ceph-rest-api --conf /etc/ceph/ceph.conf &"
changed_when: false
when: restapi_status.rc != 0
```
```
#run first time
[root@devstack ansible]# ansible-playbook -i inventory  site.yml 
_________________
< PLAY [cinder24] >
-----------------
\   ^__^
\  (oo)\_______
(__)\ …
```

the $? of pgrep ceph-rest-api command return is 1 when ceph-rest-api is already run

---

tox.ini

tests: allow setting fetch_directory with an environment variable

---

tox.ini

tests: run all tests for jewel and kraken

---

tox.ini

tests: bump the version of ansible to 2.2.2

---

docs/source/testing/scenarios.rst

docs: scenario files and section descriptions

---

infrastructure-playbooks/migrate-journal-to-ssd.yml

This playbook use to migrate activity osd(s) journal to SSD.

Migrate osd(s) journal to ssd

---

infrastructure-playbooks/rolling_update.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/main.yml
site-docker.yml.sample
tests/functional/centos/7/cluster/hosts
tests/functional/centos/7/docker-cluster/group_vars/all
tests/functional/centos/7/docker-cluster/hosts
tests/functional/ubuntu/16.04/cluster/hosts

Without this, we don't test the mgr role so we need to add it.

test: add mgr section to the host inventory file

---

roles/ceph-common/tasks/main.yml
tests/functional/rhcs_setup.yml
tox.ini

Backport: 'tests: fix ceph_rhcs setup #1439'

---

docs/source/testing/scenarios.rst
docs/source/testing/tox.rst

docs: write docs for tox.ini file

---

tests/functional/rhcs_setup.yml

tests: mgr nodes should have the ceph-mon repo install

---

infrastructure-playbooks/purge-cluster.yml

backport: "purge-cluster: remove unneeded tasks #1464"

---

roles/ceph-common/handlers/main.yml

Fix the condition on the osd restart handler.

Common: Fix condition on osd restart handler

---

roles/ceph-common/handlers/main.yml

Fix the condition on the osd restart handler.

Backport: Common: Fix condition on osd restart handler

---

tests/conftest.py
tests/functional/tests/mon/test_mons.py

This adds a test to ensure that all containerized OSDs are up and in.

tests: test all docker osds are up and in

---

tests/conftest.py
tests/functional/tests/mon/test_mons.py

Backport: "tests: test all docker osds are up and in #1485"

---

tests/functional/rhcs_setup.yml

(cherry picked from commit 35aab1274a5ec6ad696040965c87a87310bb019e)

tests: enable the rhcs-7-extras-nightly repo on test nodes

---

docs/source/testing/tox.rst
tox.ini

tests: actually test jewel when we say we are

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

ceph-common: add luminous to ceph_release_num

---

tests/functional/centos/7/cluster/group_vars/rgws
tests/functional/centos/7/docker-cluster/group_vars/all
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/ubuntu/16.04/cluster/group_vars/rgws

rgw: test functionality of conf vars and pool creation for tuning

---

roles/ceph-osd/templates/ceph-osd.service.j2

ceph-osd: fix typo in containerized OSD systemd unit

---

roles/ceph-common/tasks/checks/check_system.yml
roles/ceph-common/tasks/installs/install_on_clear.yml
roles/ceph-common/tasks/main.yml
roles/ceph-osd/tasks/pre_requisite.yml

Signed-off-by: Alberto Murillo Silva <alberto.murillo.silva@intel.com>

Add clearlinux to supported platforms

---

ceph-aio-no-vagrant.sh

Since we don't provide install-ansible.sh anymore we just check if it
exists. If not we fail and ask for installation.

ceph-aio-no-vagrant.sh: check if ansible is installed

---

roles/ceph-common/templates/restart_osd_daemon.sh.j2

ceph-common: improve error message on restart osd daemon script

---

tests/functional/tests/rgw/test_rgw_tuning.py

test: check if default bucket object quota is applied

---

tests/functional/centos/7/cluster/group_vars/rgws
tests/functional/centos/7/docker-cluster/group_vars/all
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/ubuntu/16.04/cluster/group_vars/rgws

This branch would add the testing for the rgw tuning, as of now, one of the RGW tests isn't passing

rgw testing stable 2.2

---

roles/ceph-mon/tasks/ceph_keys.yml

ignore error when key is not exist

ignore error when key is not exist

---

roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml

Signed-off-by: Pascal Watteel <pascal.watteel@emc.com>

added support for Sandisk FusionIO devices

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

docker: Retry OSD disk prepare to workaround race condition

---

generate_group_vars_sample.sh
group_vars/all.yml.sample
group_vars/rgws.yml.sample

backport: Docker registry bkp

---

roles/ceph-mon/tasks/ceph_keys.yml

(cherry picked from commit 027f9aaf09fd63a887a8d725b542930219f43707)

backport: ignore error when doesn't exist

---

roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml

Signed-off-by: Pascal Watteel <pascal.watteel@emc.com>
(cherry picked from commit e4ef8bb87f9df22459908f71d8cc816b081d829a)

backport: added support for Sandisk FusionIO devices

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml

(cherry picked from commit 471cdb0c3999b375f2891472d4645eea5f4d7051)

backport: ceph-common: add luminous to ceph_release_num

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml

Reverts ceph/ceph-ansible#1531

Revert "docker: Retry OSD disk prepare to workaround race condition"

---

roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml

This resolves a bug identifying partitions for FusionIO devices.

Fixing partition detection regex for FusionIO devices.

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml

backport of: #1557
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1453119

backport: Install condition bkp

---

infrastructure-playbooks/purge-docker-cluster.yml
tox.ini

Backport: "purge-docker-cluster fix and test #1568"

---

infrastructure-playbooks/purge-docker-cluster.yml
tox.ini

backport of #1582 and #1577
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1455187

purge-docker-cluster.yml backports

---

site.yml.sample

Backport: "remove ceph-iscsi-gw play from site.yml.sample #1589"

---

ansible.cfg

Closes: https://github.com/ceph/ceph-ansible/issues/1611

ansible: disable retry files

---

group_vars/mons.yml.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml

We now allow a user to pass a key secret.
Fixes: https://github.com/ceph/ceph-ansible/issues/1617

mon: rework openstack keys creation

---

roles/ceph-mon/tasks/deploy_monitors.yml

Ensure that ceph-mon applies mon directory ownership recursively

---

roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2
tests/functional/centos/7/docker-cluster-dmcrypt-journal-collocation/group_vars/all

osd: docker, refactor ceph-osd-run.sh.j2

---

site-docker.yml.sample

site: docker add client role

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/templates/ceph.conf.j2
tests/functional/centos/7/cluster/group_vars/all

use host specific value for monitor_interface in ceph.conf creation

---

Vagrantfile
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-docker-common/tasks/create_configs.yml
roles/ceph-docker-common/tasks/fetch_configs.yml
roles/ceph-docker-common/tasks/main.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/openstack_config.yml
roles/ceph-nfs/tasks/docker/copy_configs.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml
tests/functional/centos/7/docker/hosts
tests/functional/centos/7/docker/vagrant_variables.yml
tests/functional/centos/7/jrn-col/group_vars/all

Add the possibility to deploy a client-node in a containerized deployment

Add the possibility to deploy a client-node in a containerized deployment

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample

Sync group_vars/*.sample files

---

roles/ceph-mon/tasks/openstack_config.yml

Copies all created openstack keys on all mons.

Mon: Copy openstack keyring files on all mons

---

group_vars/all.yml.sample
group_vars/rgws.yml.sample
roles/ceph-docker-common/defaults/main.yml

ceph-docker-common: update etcd kv port

---

roles/ceph-mon/tasks/deploy_monitors.yml

mon: add mgr cap to admin key

---

infrastructure-playbooks/purge-cluster.yml

Closes https://github.com/ceph/ceph-ansible/issues/1672

purge: remove leftover unit files

---

group_vars/all.yml.sample
roles/ceph-common/defaults/main.yml
roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/release.yml

Fix https://github.com/ceph/ceph-ansible/issues/1712

common: make ceph_stable_release mandatory

---

tox.ini

Signed-off-by: Gregory Meno <gmeno@redhat.com>

change ansible environment to 2.3 release

---

group_vars/all.yml.sample
group_vars/clients.yml.sample
group_vars/osds.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

resync group_vars files

---

group_vars/rbd-mirrors.yml.sample
group_vars/rhcs.yml.sample

resync group_vars

---

roles/ceph-osd/tasks/scenarios/lvm.yml

ceph-osd: ceph-volume requires --data to be in vg/lv format

---

group_vars/osds.yml.sample

resync groups_vars

---

roles/ceph-agent/meta/main.yml
roles/ceph-client/meta/main.yml
roles/ceph-common/meta/main.yml
roles/ceph-config/meta/main.yml
roles/ceph-defaults/meta/main.yml
roles/ceph-docker-common/meta/main.yml
roles/ceph-fetch-keys/meta/main.yml
roles/ceph-mds/meta/main.yml
roles/ceph-mgr/meta/main.yml
roles/ceph-mon/meta/main.yml
roles/ceph-nfs/meta/main.yml
roles/ceph-osd/meta/main.yml
roles/ceph-rbd-mirror/meta/main.yml
roles/ceph-restapi/meta/main.yml
roles/ceph-rgw/meta/main.yml

Closes: https://github.com/ceph/ceph-ansible/issues/1637

update meta for ansible galaxy

---

contrib/push-roles-to-ansible-galaxy.sh

We now compare local tags versus remote tags and do nothing if they both
exist.

contrib: do not rework if tag exist

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/release-rhcs.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-docker-common/tasks/release.yml

common: add mimic release facts

---

tests/functional/tests/osd/test_osds.py

tests: fix duplicate osd service test

---

Vagrantfile
group_vars/osds.yml.sample
infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-docker-common/tasks/fetch_configs.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/ceph_disk_cli_options_facts.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_auto.yml
roles/ceph-osd/tasks/check_devices_static.yml
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/scenarios/collocated.yml
roles/ceph-osd/tasks/scenarios/non-collocated.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2
tests/functional/centos/7/bs-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-ded-jrn/group_vars/all
tests/functional/centos/7/bs-docker/group_vars/all
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/crypt-ded-jrn/group_vars/all
tests/functional/centos/7/crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-ded-jrn/group_vars/all
tests/functional/centos/7/docker/group_vars/all
tests/functional/centos/7/jrn-col/group_vars/all

Fixes: https://github.com/ceph/ceph-ansible/issues/1729 and https://bugzilla.redhat.com/show_bug.cgi?id=1484466

osd: allow multi dedicated journals for containers

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml

I had to change these to make Ceph dev deployments work

Dev repository fixes

---

roles/ceph-common/tasks/main.yml

common do not filter by distro when dev is set for figuring out ceph_release

---

Vagrantfile
infrastructure-playbooks/shrink-mon.yml
infrastructure-playbooks/shrink-osd.yml
tests/functional/centos/7/cluster/group_vars/osds
tests/functional/centos/7/cluster/hosts
tests/functional/centos/7/cluster/vagrant_variables.yml
tests/functional/tests/mon/test_mons.py
tox.ini

Rework shrinking a monitor and an OSD playbook. Also adding test
scenario.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1366807

shrink mon and osd

---

roles/ceph-rgw/templates/ceph-radosgw.service.j2

ceph-rgw: fix systemd unit layout

---

group_vars/clients.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/pre_requisite.yml

client: do not copy admin key by default

---

tox.ini

tests: set ceph_stable_release to luminous for rhcs

---

group_vars/nfss.yml.sample
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-nfs/defaults/main.yml
roles/ceph-nfs/tasks/docker/start_docker_nfs.yml

The service is nfs-ganesha where ceph-nfs@{{ ansible_hostname }} will be
the name of the container.

switch to container: fix ceph nfs

---

roles/ceph-mon/templates/ceph-mon.service.j2

mon: add support for monitor_address block for containers

---

roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/scenarios/collocated.yml
roles/ceph-osd/tasks/scenarios/non-collocated.yml

osd: refact include of `activate_osds.yml`

---

roles/ceph-osd/tasks/activate_osds.yml
roles/ceph-osd/tasks/check_devices.yml
roles/ceph-osd/tasks/check_devices_static.yml
roles/ceph-osd/tasks/scenarios/collocated.yml
roles/ceph-osd/tasks/scenarios/non-collocated.yml
tests/functional/centos/7/bluestore/group_vars/all
tests/functional/centos/7/bs-crypt-ded-jrn/group_vars/all
tests/functional/centos/7/bs-dock-ded-jrn/group_vars/all
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/crypt-ded-jrn/group_vars/all
tests/functional/centos/7/docker-ded-jrn/group_vars/all
tests/functional/ubuntu/16.04/cluster/group_vars/all

We have been struggling with this, it's still broken and breaking other
things too now

osd: drop support for device partition

---

group_vars/nfss.yml.sample
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-nfs/defaults/main.yml
roles/ceph-nfs/tasks/pre_requisite.yml
roles/ceph-nfs/templates/ganesha.conf.j2
tests/functional/tests/nfs/test_nfs_ganesha.py

- Add RGW keyring to nfs node
- Add RGW section to ganesha.conf
- Add RGW section to ceph.conf onf nfs node

nfs: configure RGW FSAL to start up correctly

---

infrastructure-playbooks/shrink-osd.yml

shrink-osd: fix when multiple osds

---

infrastructure-playbooks/rolling_update.yml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1490188

rolling_update: clarify update doc

---

infrastructure-playbooks/shrink-mon.yml
infrastructure-playbooks/shrink-osd.yml
tox.ini

shrink: support for container

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-docker-cluster.yml

mgr nodes are not managed by purge-cluster.yml

purge: implement mgr purge

---

tests/functional/tests/rgw/test_rgw.py

test: add basic testing coverage for the rgw

---

infrastructure-playbooks/rolling_update.yml

rolling_update: clarify mon quorum command

---

docs/source/index.rst

Add RPM and DEB instructions for installing Ansible.

[skip ci] docs: add instructions for installing Ansible

---

roles/ceph-defaults/tasks/check_socket.yml

[skip ci] defaults: fix check socket non-container handler

---

roles/ceph-osd/tasks/docker/main.yml

Fixing path to osd_fragment.yml

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
roles/ceph-defaults/defaults/main.yml

[skip ci] common: fix rhcs installation on debian

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

common: fix ga verison for debian rhcs

---

roles/ceph-common/tasks/checks/check_mandatory_vars.yml
roles/ceph-common/tasks/installs/debian_dev_repository.yml
roles/ceph-common/tasks/installs/debian_rhcs_repository.yml
roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml

[skip ci] common: iso install on Debian is supported by rhcs

---

roles/ceph-osd/tasks/check_devices.yml
roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
tests/conftest.py

fix some bugs regarding `jewel` release and fix testinfra for nfss node as well.

Fix jewel nightly

---

group_vars/nfss.yml.sample
roles/ceph-nfs/defaults/main.yml

- remove unused ganesha config vars,
- set different default Export_ids for each FSAL

nfs: config var changes

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

nfs: missing conditional for setting rgw key permissions

---

infrastructure-playbooks/purge-docker-cluster.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/shrink-osd.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
roles/ceph-defaults/handlers/main.yml
roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
roles/ceph-osd/tasks/scenarios/collocated.yml
roles/ceph-osd/tasks/scenarios/non-collocated.yml
tests/functional/centos/7/bluestore/group_vars/all
tests/functional/centos/7/bs-crypt-ded-jrn/group_vars/all
tests/functional/centos/7/bs-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-crypt-jrn-col/group_vars/all
tests/functional/centos/7/bs-dock-ded-jrn/group_vars/all
tests/functional/centos/7/bs-jrn-col/group_vars/all
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/crypt-ded-jrn/group_vars/all
tests/functional/centos/7/crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-crypt-jrn-col/group_vars/all
tests/functional/centos/7/docker-ded-jrn/group_vars/all
tests/functional/centos/7/docker/group_vars/all
tests/functional/centos/7/jrn-col/group_vars/all
tests/functional/ubuntu/16.04/cluster/group_vars/all

We don't need to wait if they are no PGS.

[skip ci] handler: do not test if pgs_num = 0

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

[skip ci] switch: check pgs only when num_pgs > 0

---

infrastructure-playbooks/purge-cluster.yml

I have encourted a couple of bugs when testing ceph-ansible on my machine. These commits helped me fix them.

A couple of purge cluster fixes

---

Vagrantfile
infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-iscsi-gateways.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-common/tasks/installs/install_debian_packages.yml
roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
roles/ceph-common/tasks/installs/install_redhat_packages.yml
roles/ceph-common/tasks/installs/redhat_community_repository.yml
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-iscsi-gw/tasks/prerequisites.yml
roles/ceph-mds/tasks/non_containerized.yml
roles/ceph-mgr/tasks/pre_requisite.yml
roles/ceph-nfs/tasks/pre_requisite_non_container.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2
tests/functional/centos/7/cluster/ceph-override.json
tests/functional/tests/mds/test_mds.py
tests/functional/tests/mgr/test_mgr.py
tox.ini

Use the pg check before doing the pg check, not on the quorum check.
Also never quote int when doing comparaison.

infra: use the pg check in the right place

---

docs/source/index.rst
roles/ceph-common/tasks/installs/debian_community_repository.yml
roles/ceph-common/tasks/installs/debian_dev_repository.yml
roles/ceph-common/tasks/installs/redhat_community_repository.yml
roles/ceph-common/tasks/installs/redhat_dev_repository.yml
roles/ceph-iscsi-gw/tasks/prerequisites.yml
roles/ceph-nfs/tasks/pre_requisite_non_container.yml

This is something that has nothing to do in `ceph-common`, this
is too specific to `ceph-nfs` role.

nfs: move repository configuration in ceph-nfs role

---

infrastructure-playbooks/purge-iscsi-gateways.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1500281

[skip ci] purge-iscsi: fix group name

---

infrastructure-playbooks/take-over-existing-cluster.yml

Clean cherry-pick of @djgalloway's fix for 4639d89231dc35c743ded29ed0f962f36a4b0574.
Fixes #2033.

stable-2.2: fix missing backport

---

roles/ceph-common/tasks/configure_cluster_name.yml

Minor fix to ensure that existing CLUSTER_NAME is changed, and avoid duplicates.

Add regexp check for setting CLUSTER_NAME

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

add the miss word

---

roles/ceph-config/templates/ceph.conf.j2

Once and for all, hopefully...

rgw/nfs: fix section duplication

---

tests/requirements.txt
tox.ini

Closes: https://github.com/ceph/ceph-ansible/issues/2087

[skip ci] Test ansible 2.4.1

---

roles/ceph-nfs/files/org.ganesha.nfsd.conf
roles/ceph-nfs/tasks/pre_requisite_container.yml

This file was (accidentally) not included in a previous
commit 87b1da09e7131ec2741f332fd72aaec8de65e526.

Include ganesha dbus config file

---

tox.ini

[skip ci] tests: sync with ceph/ceph-build for ceph-ansible-nightlies

---

roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-docker-common/tasks/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-osd/tasks/docker/start_docker_osd.yml
roles/ceph-osd/tasks/scenarios/collocated.yml
roles/ceph-osd/tasks/scenarios/non-collocated.yml
roles/ceph-osd/templates/ceph-osd-run.sh.j2

[skip ci] 2128-bkp

---

ceph-ansible.spec.in

[skip ci] backport of ansible-2.4.1.0

---

roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2

[skip ci] backport of 2167

---

tox.ini

[skip ci] backport of 2165

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

[skip ci] fix: remove the duplicated code

---

roles/ceph-osd/tasks/activate_osds.yml

[backport][stable-3.0] Fix dmcrypt bkp

---

roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml

[skip ci] 2182-bkp

---

roles/ceph-osd/tasks/check_gpt.yml
roles/ceph-osd/tasks/main.yml

backport of 2197

---

roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml

[skip ci] backport of 2207

---

infrastructure-playbooks/purge-cluster.yml

[skip ci] backport of 2221-bis

---

Vagrantfile

Vagrantfile: Fixed repeated OSD controller creation

---

roles/ceph-defaults/handlers/main.yml

[skip ci] backport of 2214

---

roles/ceph-osd/tasks/pre_requisite.yml

[skip ci] backport of 2202

---

infrastructure-playbooks/purge-cluster.yml

[skip ci] backport of 2221

---

docs/source/index.rst

(cherry picked from commit 7d239b69082146305349666d6fd8125549b64feb)

fix the ansible version for the stable-3.0 branch

---

roles/ceph-osd/tasks/check_gpt.yml

[skip ci] backport of 2226

---

tox.ini

This reverts commit 7a1d7d92ff4d6f38be9f11f4c26909b361b58f99.

Revert "tests: set CEPH_STABLE_RELEASE in ceph-build"

---

roles/ceph-defaults/tasks/check_socket_non_container.yml

backport of 2257

---

roles/ceph-client/tasks/pre_requisite.yml
roles/ceph-mds/tasks/containerized.yml

backport of 2253

---

group_vars/clients.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-client/tasks/main.yml
roles/ceph-client/tasks/pre_requisite.yml
tests/functional/centos/7/cluster/group_vars/clients

Backport of 2249

---

roles/ceph-mgr/tasks/pre_requisite.yml

Backport of 2267

---

roles/ceph-defaults/tasks/facts.yml

Backport of 2245

---

roles/ceph-docker-common/tasks/main.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mgr/templates/ceph-mgr.service.j2
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-osd/templates/ceph-osd-run.sh.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-rgw/templates/ceph-radosgw.service.j2

backport of 2248

---

roles/ceph-osd/templates/ceph-osd-run.sh.j2

We have a scenario when we switch from non-container to containers.

osd: best effort if no device is found

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

backport of 2279

---

roles/ceph-osd/templates/ceph-osd-run.sh.j2

Backport of 2278

---

infrastructure-playbooks/rolling_update.yml

Backport of 2272

---

site-docker.yml.sample

backport of 2283

---

tests/functional/centos/7/bs-osds-container/group_vars/all.yml
tests/functional/centos/7/docker-collocation/group_vars/all
tests/functional/centos/7/docker/group_vars/all
tests/functional/centos/7/fs-osds-container/group_vars/all.yml

Backport of 2288

---

roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

Backport of 2291

---

roles/ceph-mon/tasks/ceph_keys.yml

Backport of 2289

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-osd/tasks/check_gpt.yml

Backport of 2256

---

infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
tox.ini

backport of 2301

---

roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/main.yml

Backport of 2306

---

roles/ceph-config/templates/ceph.conf.j2
roles/ceph-docker-common/defaults/main.yml

Backport of 2307

---

roles/ceph-defaults/tasks/facts.yml

Backport of 2309

---

ceph-ansible.spec.in
docs/source/index.rst
docs/source/testing/running.rst
tox.ini

ci: test on ansible 2.4.2

---

ceph-ansible.spec.in
docs/source/index.rst
docs/source/testing/running.rst
tox.ini

backport of 2295

---

roles/ceph-rgw/tasks/docker/start_docker_rgw.yml

Backport of 2329

---

infrastructure-playbooks/rolling_update.yml

Backport of 2324

---

roles/ceph-osd/tasks/activate_osds.yml

backport of 2285

---

infrastructure-playbooks/purge-docker-cluster.yml

Backport of 2323

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

Backport of 2347

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

Backport of 2355

---

roles/ceph-osd/tasks/start_osds.yml

Backport of 2356

---

infrastructure-playbooks/purge-docker-cluster.yml

Backport of 2362

---

group_vars/all.yml.sample
group_vars/osds.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/defaults/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2

osd: resync group_vars file

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/defaults/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2

Backport of 2360

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/untested-by-ci/cluster-maintenance.yml
infrastructure-playbooks/untested-by-ci/cluster-os-migration.yml
roles/ceph-common-coreos/tasks/install_pip.yml
roles/ceph-common-coreos/tasks/install_pypy.yml
roles/ceph-common/tasks/checks/check_firewall.yml
roles/ceph-common/tasks/facts_mon_fsid.yml
roles/ceph-config/tasks/main.yml
roles/ceph-defaults/tasks/facts.yml
roles/ceph-docker-common/tasks/fetch_image.yml
roles/ceph-docker-common/tasks/stat_ceph_files.yml
roles/ceph-iscsi-gw/tasks/deploy_ssl_keys.yml
roles/ceph-mds/tasks/containerized.yml
roles/ceph-mgr/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-nfs/tasks/pre_requisite_container.yml
roles/ceph-osd/tasks/copy_configs.yml
roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
roles/ceph-restapi/tasks/docker/copy_configs.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml
tests/functional/reboot.yml

rewrite `local_action` tasks to adopt a nicer syntax.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1510555

Fix 1510555

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/untested-by-ci/cluster-maintenance.yml
infrastructure-playbooks/untested-by-ci/cluster-os-migration.yml
roles/ceph-common-coreos/tasks/install_pip.yml
roles/ceph-common-coreos/tasks/install_pypy.yml
roles/ceph-common/tasks/checks/check_firewall.yml
roles/ceph-common/tasks/facts_mon_fsid.yml
roles/ceph-config/tasks/main.yml
roles/ceph-defaults/tasks/facts.yml
roles/ceph-docker-common/tasks/fetch_image.yml
roles/ceph-docker-common/tasks/stat_ceph_files.yml
roles/ceph-iscsi-gw/tasks/deploy_ssl_keys.yml
roles/ceph-mds/tasks/containerized.yml
roles/ceph-mgr/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-nfs/tasks/pre_requisite_container.yml
roles/ceph-osd/tasks/copy_configs.yml
roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
roles/ceph-restapi/tasks/docker/copy_configs.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml
tests/functional/reboot.yml

backport of 2365

---

roles/ceph-osd/tasks/activate_osds.yml

Backport of 2219

---

roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-rgw/templates/ceph-radosgw.service.j2

Backport of 2078

---

roles/ceph-mds/tasks/containerized.yml
roles/ceph-mon/tasks/docker/main.yml

Backport of 2371

---

README.rst

Update the Documentation link from 2.2 -> 3.0
Helpful for newbies.

Update Documentation example link to 3.0

---

roles/ceph-defaults/tasks/facts.yml

Backport of 2381

---

roles/ceph-osd/templates/ceph-osd-run.sh.j2

Backport of 2380

---

group_vars/mdss.yml.sample
group_vars/osds.yml.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-osd/defaults/main.yml

Backport of 2304

---

infrastructure-playbooks/rolling_update.yml

Backport of 2392

---

infrastructure-playbooks/take-over-existing-cluster.yml

Backport of 2389

---

infrastructure-playbooks/rolling_update.yml

Backport of 2398

---

roles/ceph-mon/tasks/openstack_config.yml

Backport of 2413

---

roles/ceph-nfs/tasks/start_nfs.yml

The nfs-ganesha package has been fixed.
This reverts commit e88af3c4cb314f1f640447ebdce343f0aca85fb4.

Revert "[TEST] Test setting up correct systemd file for nfs-ganesha"

---

roles/ceph-client/tasks/pre_requisite.yml

Backport of 2397

---

tox.ini

Backport of 2419

---

roles/ceph-common/tasks/misc/system_tuning.yml
roles/ceph-rgw/handlers/main.yml
roles/ceph-rgw/tasks/docker/copy_configs.yml
tests/functional/centos/7/docker/group_vars/rgws

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1544720
Backport of #2428

[Backport] Bkp 2428

---

ansible.cfg

Based on the OpenShift one:
https://docs.openshift.com/container-platform/3.7/scaling_performance/install_practices.html#scaling-performance-install-optimization
* Increases number of forks.
* Disables host_key_checking
* Smart gathering facts
* Fact caching jsonfile
* Enables profile_tasks callback
* Mutliplexes ssh connections (ControlMaster)
* Enables pipelining

Tune ansible.cfg

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

ceph-osd note that some scenarios use ceph-disk vs. ceph-volume

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

Backport of 2477

---

roles/ceph-osd/templates/osd.conf.j2

Backport of 2469

---

roles/ceph-mds/tasks/containerized.yml

Backport of 2479

---

site-docker.yml.sample

Backport of 2459

---

roles/ceph-defaults/tasks/facts.yml

Backport of 2495

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

Backport of 2502

---

infrastructure-playbooks/purge-cluster.yml
library/ceph_volume.py
tests/functional/lvm_setup.yml

Adds zap support to the existing ``ceph_volume`` module, an alternative approach to #2442
Fixes: #2337

ceph_volume: adds zap support

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample
infrastructure-playbooks/ceph-keys.yml
library/ceph_key.py
library/test_ceph_key.py
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-client/tasks/pre_requisite.yml
roles/ceph-defaults/tasks/facts.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/tasks/openstack_config.yml
tests/functional/centos/7/cluster/group_vars/clients
tests/functional/centos/7/docker-collocation/group_vars/clients
tests/functional/centos/7/docker/group_vars/clients
tests/functional/centos/7/ooo-collocation/hosts

add ceph_key module

---

roles/ceph-mds/tasks/containerized.yml
roles/ceph-nfs/tasks/pre_requisite_container.yml
roles/ceph-osd/tasks/copy_configs.yml

Backport of 2511

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

Backport of 2488

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml

To install iscsi gw packages we need to enable the tools repo.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1547849

[skip ci] common: add tools repo for iscsi gw

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml

[skip ci] 2518 bkp

---

site-docker.yml.sample
site.yml.sample

These conditions introduced by d981c6bd2 were insane.
This should be a bit easier to read.

site-docker: make it more readable

---

roles/ceph-defaults/tasks/facts.yml

Backport of 2505

---

roles/ceph-defaults/tasks/facts.yml

bpk 2481 - ceph-defaults: fix ceph_uid fact on container deployments

---

tox.ini

Backport of 2497

---

infrastructure-playbooks/shrink-osd.yml

[skip ci] backport of 2537 bkp

---

plugins/actions/_v2_config_template.py
roles/ceph-mon/tasks/docker/copy_configs.yml
roles/ceph-mon/tasks/docker/main.yml
tests/requirements2.5.txt
tox.ini

ci: test ansible 2.5

---

group_vars/clients.yml.sample
group_vars/mons.yml.sample
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/tasks/openstack_config.yml
tests/functional/centos/7/cluster/group_vars/clients
tests/functional/centos/7/cluster/group_vars/mons
tests/functional/centos/7/docker-collocation/group_vars/clients
tests/functional/centos/7/docker/group_vars/clients
tests/functional/centos/7/docker/group_vars/mons

Latest is now centos not ubuntu anymore so the condition was wrong.

switch: fix ceph_uid fact

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml

Backport of 2558

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1574458

[skip ci] common: enable Tools repo for rhcs clients

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

in tasks for os_family Red Hat we were missing this
fixes: bz1575859
Signed-off-by: Gregory Meno <gmeno@redhat.com>

adds missing state needed to upgrade nfs-ganesha

---

roles/ceph-defaults/templates/restart_mds_daemon.sh.j2

Backport of 2498

---

site-docker.yml.sample
site.yml.sample
tox.ini

backport of 2560

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

Backport of #2570 - stable-3.1

Backport of 2570 - stable-3.1

---

roles/ceph-nfs/tasks/pre_requisite_non_container.yml

Backport of 2570

---

roles/ceph-osd/templates/ceph-osd-run.sh.j2

Backport of 2567

---

roles/ceph-mon/tasks/docker/main.yml

Backport of #2575 in stable 3.1

[skip ci] 2575 bkp stable 3.1

---

roles/ceph-client/tasks/create_users_keys.yml

Backport of #2561 in stable-3.1

Backport of 2561 in stable-3.1

---

roles/ceph-defaults/handlers/main.yml

Backport of #2141 in stable-3.0

Backport of 2141 in stable-3.0

---

roles/ceph-iscsi-gw/tasks/prerequisites.yml

Backport of #2586 in stable-3.0

[skip ci] Backport of 2586 in stable-3.0

---

infrastructure-playbooks/purge-cluster.yml

Fixes for purge_cluster playbook.
The devices list wasn't built properly.
The partitions weren't wiped.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1492242

fix purge, wipe partitions properly

---

roles/ceph-mgr/tasks/main.yml

Backport of #2610 in stable-3.1

[skip ci] Backport of 2610 in stable-3.1

---

roles/ceph-defaults/templates/restart_osd_daemon.sh.j2

Backport of #2613 in stable-3.1

Backport of 2613 in stable-3.1

---

infrastructure-playbooks/purge-cluster.yml

[skip ci] backport of 2596 in stable-3.0

---

plugins/actions/validate.py

[skip ci] validate: fix validation of bluestore lvm scenario

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

Backport of #2595 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1577846

Backport of 2595 in stable-3.1

---

roles/ceph-defaults/templates/restart_osd_daemon.sh.j2

Backport of #2613 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1573317

Backport of 2613 in stable-3.0

---

roles/ceph-defaults/handlers/main.yml

Backport of #2451 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581403

Backport of 2451 in stable-3.0

---

roles/ceph-osd/tasks/main.yml

commit 5429ada53399ef72bd3ba450a9bab55069b5aab2 (HEAD -> wip_lvm_bluestore, origin/wip_lvm_bluestore)
Author: Vishal Kanaujia <vishal.kanaujia@flipkart.com>
Date:   Wed May 16 15:28:31 2018 +0530
Skip GPT header creation for lvm osd scenario
https://github.com/ceph/ceph-ansible/issues/2592
Signed-off-by: Vishal Kanaujia <vishal.kanaujia@flipkart.com>

Skip GPT header creation for lvm osd scenario

---

roles/ceph-osd/tasks/main.yml

Backport of #2593 in stable-3.1

Backport of 2593 in stable-3.1

---

rhcs_edits.txt

Backport of #2563 in stable-3.1

[skip ci] Backport of 2563 in stable-3.1

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml
roles/ceph-rgw/tasks/main.yml
tests/functional/centos/7/ooo-collocation/hosts

Backport of #2620 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581573

Backport of 2620 in stable-3.1

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml
roles/ceph-rgw/tasks/main.yml
tests/functional/centos/7/ooo-collocation/hosts

Backport of #2620 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581573

 Backport of 2620 in stable-3.0

---

infrastructure-playbooks/purge-iscsi-gateways.yml

Backport of #2644 in stable-3.0

[skip ci] Backport of 2644 in stable-3.0

---

infrastructure-playbooks/purge-iscsi-gateways.yml

Backport of #2644 in stable-3.1

[skip ci] Backport of 2644 in stable-3.1

---

roles/ceph-mds/tasks/main.yml

Backport of #2645 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1578086

Backport of 2645 in stable-3.1

---

CONTRIBUTING.md

As per issue #2623, it is important to define the commit guidelines.
This commit is about adding a first version of it.

CONTRIBUTING.md: Initial release

---

tests/functional/setup.yml
tox.ini

Backport of #2652 in stable-3.0

Backport of 2652 in stable-3.0

---

tests/functional/setup.yml
tox.ini

Backport of #2652 in stable-3.1

Backport of 2652 in stable-3.1

---

tests/requirements2.5.txt

Backport of #2651 in stable-3.1

Backport of 2651 in stable-3.1

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/container_env_facts.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/main.yml

Backport of #2525 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1551637

Backport of 2525 in stable-3.0

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/container_env_facts.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/main.yml

Backport of #2525 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1551637

Backport of 2525 in stable-3.1

---

Makefile

Backport of #2585 in stable-3.0

[skip ci] Backport of 2585 in stable-3.0

---

Makefile

Backport of #2669 in stable-3.1

[skip ci] Backport of 2669 in stable-3.1

---

Makefile

Backport of #2669 in stable-3.0

Backport of 2669 in stable-3.0

---

roles/ceph-osd/tasks/openstack_config.yml

Backport of #2675 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1578086

Backport of 2675 in stable-3.1

---

roles/ceph-mon/tasks/main.yml
roles/ceph-osd/tasks/main.yml

Backport of #2679 in stable-3.1

Backport of 2679 in stable-3.1

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/release-rhcs.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-docker-common/tasks/release.yml

Backport of #2673 in stable-3.1

Backport of 2673 in stable-3.1

---

roles/ceph-rgw/tasks/multisite/master.yml

This checkin fixes a syntax error in RGW multisite role under when
clause.
Fixes: #2704
Signed-off-by: Vishal Kanaujia <vishal.kanaujia@flipkart.com>

Syntax error fix in rgw multisite role

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
roles/ceph-rgw/tasks/main.yml
roles/ceph-rgw/tasks/rgw_pool_pgs.yml
tests/functional/centos/7/bs-osds-container/group_vars/rgws.yml
tests/functional/centos/7/bs-osds-non-container/group_vars/rgws.yml
tests/functional/centos/7/cluster/group_vars/rgws
tests/functional/centos/7/docker-collocation/group_vars/rgws
tests/functional/centos/7/docker/group_vars/rgws
tests/functional/centos/7/fs-osds-container/group_vars/rgws.yml
tests/functional/centos/7/fs-osds-non-container/group_vars/rgws.yml
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/ubuntu/16.04/cluster/group_vars/rgws

Backport of #2424 in stable-3.1

Backport of 2424 in stable-3.1

---

group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/docker/main.yml
roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
roles/ceph-rgw/tasks/main.yml
roles/ceph-rgw/tasks/rgw_pool_pgs.yml
tests/functional/centos/7/bs-osds-container/group_vars/rgws.yml
tests/functional/centos/7/bs-osds-non-container/group_vars/rgws.yml
tests/functional/centos/7/cluster/group_vars/rgws
tests/functional/centos/7/docker-collocation/group_vars/rgws
tests/functional/centos/7/docker/group_vars/rgws
tests/functional/centos/7/fs-osds-container/group_vars/rgws.yml
tests/functional/centos/7/fs-osds-non-container/group_vars/rgws.yml
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/ubuntu/16.04/cluster/group_vars/rgws

Backport of #2424 in stable-3.0

Backport of 2424 in stable-3.0

---

tests/functional/tests/rgw/test_rgw_tuning.py

Backport of #2706 in stable-3.1

Backport of 2706 in stable-3.1

---

infrastructure-playbooks/rolling_update.yml

this is kind of follow up on what has been made in #2560.
See #2560 and #2553 for details.
Closes: #2708

rolling_update: fix facts gathering delegation

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

Backport of #2695 in stable-3.1

Backport of 2695 in stable-3.1

---

tests/functional/centos/7/cluster/group_vars/osds
tox.ini

Backport of #2696 in stable-3.1

Backport of 2696 in stable-3.1

---

tests/functional/tests/mds/test_mds.py

Backport of #2725 in stable-3.1

Backport of 2725 in stable-3.1

---

roles/ceph-client/tasks/create_users_keys.yml

Backport of #2723 in stable-3.1

Backport of 2723 in stable-3.1

---

roles/ceph-client/tasks/create_users_keys.yml
tests/functional/centos/7/ooo-collocation/hosts

Backport of #2732 in stable-3.1

Backport of 2732 in stable-3.1

---

roles/ceph-client/tasks/create_users_keys.yml

Backport of #2739 in stable-3.1

Backport of 2739 in stable-3.1

---

tests/functional/centos/7/cluster/vagrant_variables.yml

Backport of #2748 in stable-3.0

[skip ci] Backport of 2748 in stable-3.0

---

roles/ceph-client/tasks/create_users_keys.yml

Backport of #2760 in stable-3.1

Backport of 2760 in stable-3.1

---

roles/ceph-mds/tasks/create_mds_filesystems.yml

Backport of #2694 in stable-3.1
https://bugzilla.redhat.com/show_bug.cgi?id=1590831

Backport of 2694 in stable-3.1

---

group_vars/mons.yml.sample
group_vars/osds.yml.sample
roles/ceph-mon/defaults/main.yml
roles/ceph-osd/defaults/main.yml

Backport of #2775 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1591876

Backport of 2775 in stable-3.1

---

roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/misc/configure_firewall_rpm.yml

Backport of #2776 in stable-3.1

Backport of 2776 in stable-3.1

---

tests/functional/centos/7/ooo-collocation/hosts
tests/functional/centos/7/ooo-collocation/vagrant_variables.yml

Backport of #2765 in stable-3.1

Backport: tests: add more nodes in ooo testing scenario in stable-3.1

---

docs/source/index.rst

It is now on its own channel, not extras.

Fix RHEL based Ansible installation

---

CONTRIBUTING.md

Let's add more information which could avoid contributors to waste their time
and CI resources.

[skip ci] doc: Update CONTRIBUTING.md

---

group_vars/nfss.yml.sample
roles/ceph-nfs/defaults/main.yml
roles/ceph-nfs/templates/ganesha.conf.j2

Set the default to 'root_squash' - which is the default of nfs-ganesha.
Signed-off-by: Michel Rode <rmichel@devnu11.net>

Added 'squash' as a parameter to nfs-ganesha.

---

tests/functional/centos/7/ooo-collocation/hosts
tests/functional/centos/7/ooo-collocation/vagrant_variables.yml

Backport of #2765 in stable-3.0

Backport: tests: add more nodes in ooo testing scenario in stable-3.0

---

.mergify.yml

Mergify automatically merges pull requests when they're ready so you
don't have to. You set the rules, it does the rest.

[skip ci] add mergify

---

tox.ini

This sleep 120 looks a bit long, let's reduce this to 30sec and see if
things go faster.

tests: reduce the amount of time we wait

---

infrastructure-playbooks/purge-docker-cluster.yml

Backport of #2478 in stable-3.0

Backport of 2478 in stable-3.0

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594974
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

setup mon repo on mgr nodes when rhcs cdn debian config is set

---

roles/ceph-osd/tasks/main.yml
tests/functional/lvm_setup.yml

Backport of #2593 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1582181

Backport of 2593 in stable-3.0

---

docs/source/index.rst

"OSD Configuration" should be part of the "Configuration and Usage" section.

docs: make "OSD Configuration" a subsection

---

group_vars/mgrs.yml.sample
roles/ceph-mgr/defaults/main.yml
roles/ceph-mgr/tasks/main.yml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1600155

Automatic backport of pull request #2784

---

tox.ini

In addition to ceph/ceph-build#1082
Let's set the ansible version in each ceph-ansible branch's respective
requirements.txt.

tests: stop hardcoding ansible version (master)

---

tests/functional/centos/7/shrink_osd/group_vars/all
tests/functional/centos/7/shrink_osd_container/group_vars/all

Update network subnets in group_vars/all

tests: followup on b89cc1746f

---

roles/ceph-validate/tasks/check_eth_mon.yml
roles/ceph-validate/tasks/check_eth_rgw.yml
roles/ceph-validate/tasks/main.yml

Check if the interface provided:
* exists in the gathered facts (thus on the system)
* is active
* has an IP address (depending on ip_version )
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1600227

validate: add checks for interfaces

---

requirements.txt

update requirements.txt accordingly to the last ansible version tested
on master.

main: update requirements.txt

---

roles/ceph-osd/tasks/openstack_config.yml
roles/ceph-rbd-mirror/tasks/pre_requisite.yml
site-docker.yml.sample
site.yml.sample
tests/functional/centos/7/cluster/hosts
tests/functional/centos/7/cluster/vagrant_variables.yml

bring back possibility to deploy jewel

backward compatibility for jewel deployment

---

docs/source/index.rst
group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/defaults/main.yml
roles/ceph-defaults/tasks/facts.yml
roles/ceph-validate/tasks/main.yml

- update doc
- clean ceph.conf.j2 template
- fix bz https://bugzilla.redhat.com/show_bug.cgi?id=1580408
- deprecate fqdn deployment

various fixes

---

roles/ceph-osd/tasks/openstack_config.yml

We need ceph_release in the condition, not ceph_stable_release
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1619255

osd: fix ceph_release

---

infrastructure-playbooks/lv-create.yml
infrastructure-playbooks/vars/lv_vars.yaml

remove error message when PV creation fails

infrastructure playbooks: remove lv-create error msg

---

roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/tasks/facts.yml

let's add ansible_hostname as a default value for rgw_hostname if no
hostname in servicemap matches ansible_fqdn.

defaults: add a default value to rgw_hostname

---

roles/ceph-config/templates/ceph.conf.j2

the default value for _rgw_hostname was took from the current node being
played while it should be took from the respective node in the loop.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1622505

config: set default _rgw_hostname value to respective host

---

roles/ceph-config/tasks/main.yml

Fixes: https://github.com/ceph/ceph-ansible/issues/3135

ceph-config: do not use osds_per_device literally

---

infrastructure-playbooks/purge-cluster.yml

Fixes: https://github.com/ceph/ceph-ansible/issues/3156

purge-cluster: zap devices used with the lvm scenario

---

infrastructure-playbooks/untested-by-ci/purge-multisite.yml
roles/ceph-common/tasks/main.yml
roles/ceph-mon/tasks/main.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-rgw/tasks/main.yml
roles/ceph-rgw/tasks/multisite/main.yml

See - https://github.com/ceph/ceph-ansible/issues/2998

don't use "static" field while including roles

---

roles/ceph-handler/templates/restart_mds_daemon.sh.j2
roles/ceph-handler/templates/restart_mgr_daemon.sh.j2
roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
roles/ceph-handler/templates/restart_rbd_mirror_daemon.sh.j2

Remove some legacy in those restart script.

handler: remove some leftover in restart_*_daemon.sh.j2

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml
tests/functional/centos/7/cluster/group_vars/all
tests/functional/centos/7/docker/group_vars/all

Let's configure firewalld by default.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1526400

defaults: set default `configure_firewall` to `True`

---

infrastructure-playbooks/lv-create.yml
infrastructure-playbooks/vars/lv_vars.yaml.sample

infrastructure playbooks: ensure nvme_device is defined in lv-create.yml

---

library/igw_purge.py
roles/ceph-iscsi-gw/library/igw_purge.py

[skip ci] iscsi more linting

---

infrastructure-playbooks/purge-docker-cluster.yml
roles/ceph-common/tasks/configure_cluster_name.yml
roles/ceph-common/tasks/main.yml
roles/ceph-docker-common/tasks/pre_requisites/prerequisites.yml
roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
roles/ceph-nfs/tasks/pre_requisite_non_container.yml
roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
roles/ceph-osd/tasks/system_tuning.yml
roles/ceph-validate/tasks/check_system.yml
roles/ceph-validate/tasks/main.yml
tests/functional/setup.yml

Fixes: https://github.com/ceph/ceph-ansible/issues/2835

use block directives to group tasks

---

infrastructure-playbooks/add-osd.yml
infrastructure-playbooks/rgw-standalone.yml
infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/shrink-mon.yml
infrastructure-playbooks/shrink-osd.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
infrastructure-playbooks/take-over-existing-cluster.yml
infrastructure-playbooks/untested-by-ci/replace-osd.yml
plugins/actions/validate.py
roles/ceph-validate/tasks/main.yml
site-docker.yml.sample
site.yml.sample
test.yml

Use `import_task` and `include_task` instead.

don't use "role" or "roles" to include roles

---

plugins/actions/validate.py
roles/ceph-validate/tasks/main.yml

remove DNM commits that got merged with PR #3058

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-mon/tasks/docker/main.yml
roles/ceph-mon/tasks/docker/start_docker_monitor.yml
roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml

this syntax in deprecated
Closes: #3281

playbook: remove jinja syntax in when statement

---

roles/ceph-common/tasks/installs/debian_custom_repository.yml
roles/ceph-common/tasks/installs/debian_uca_repository.yml
roles/ceph-iscsi-gw/README

The file does not bring much to the repo.

[skip ci] iscsi: rm README entry

---

plugins/actions/validate.py

This resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1638325

validate: accept lowercase true and false as boolean values

---

library/igw_purge.py
roles/ceph-iscsi-gw/library/igw_purge.py

Signed-off-by: Jason Dillaman <dillaman@redhat.com>

igw: add support for IPv6

---

tox.ini

Adding this rule on the hypervisor will allow cluster to talk to each
other.

tests: rgw_multisite allow clusters to talk to each other

---

roles/ceph-config/templates/ceph.conf.j2

jinja comment should be written using the jinja syntax `{# ... #}`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1654441

config: write jinja comment with appropriate syntax

---

infrastructure-playbooks/add-osd.yml
infrastructure-playbooks/shrink-osd-ceph-disk.yml
infrastructure-playbooks/shrink-osd.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
infrastructure-playbooks/take-over-existing-cluster.yml
infrastructure-playbooks/untested-by-ci/replace-osd.yml
site.yml.sample

use "pre_tasks" and "post_tasks" whenever required

---

RELEASE-NOTE.md

Somehowe Github now recognizes the #<digit> format of PRs on other
markdown.

[skip ci] RELASE-NOTE: fix PR links

---

library/ceph_key.py
library/test_ceph_key.py

fixes: #3421
it looks like this will need to be backported too, but I'm not sure how that process works. Are there docs for that?

ceph_keys: pass in module for error messages

---

infrastructure-playbooks/lv-create.yml
infrastructure-playbooks/lv-teardown.yml
infrastructure-playbooks/untested-by-ci/make-osd-partitions.yml
infrastructure-playbooks/untested-by-ci/migrate-journal-to-ssd.yml
infrastructure-playbooks/untested-by-ci/recover-osds-after-ssd-journal-failure.yml
roles/ceph-agent/tasks/pre_requisite.yml
roles/ceph-common/tasks/installs/configure_redhat_local_installation.yml
roles/ceph-common/tasks/installs/debian_uca_repository.yml
roles/ceph-common/tasks/installs/install_debian_packages.yml
roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
roles/ceph-common/tasks/installs/install_on_debian.yml
roles/ceph-common/tasks/installs/install_redhat_packages.yml
roles/ceph-common/tasks/installs/install_suse_packages.yml
roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
roles/ceph-infra/tasks/ntp_debian.yml
roles/ceph-infra/tasks/ntp_rpm.yml
roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
roles/ceph-mds/tasks/non_containerized.yml
roles/ceph-mgr/tasks/pre_requisite.yml
roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-rbd-mirror/tasks/pre_requisite.yml
roles/ceph-rgw/tasks/openstack-keystone.yml
tests/functional/lvm_setup.yml
tests/functional/rgw_multisite.yml
tests/functional/rhcs_setup.yml
tests/functional/setup.yml

add register/until on all packaging related tasks to avoid non valid CI
failure.

retry on packages and repositories failures

---

CONTRIBUTING.md

[skip ci] CONTRIBUTING: add more guideline for backport

---

library/ceph_key.py

Fixes: #3461
Signed-off-by: Dan Mick <dan.mick@redhat.com>

ceph_key: if initial keys are missing, report which ones

---

roles/ceph-iscsi-gw/tasks/deploy_ssl_keys.yml

copy certificates as root user

---

tests/functional/tests/rgw/test_rgw.py

The error was introduced by the commit
1ac94c048ff1d1385de2892d0ecef7879ec563e9.
Fixes: https://github.com/ceph/ceph-ansible/issues/3528

tests: fix identation issue in test_rgw.py

---

roles/ceph-common/tasks/main.yml

When we're deploying a dev branch.

do not set ceph_release to dummy

---

tests/functional/all_daemons/container/hosts-ubuntu
tests/functional/all_daemons/hosts-ubuntu
tests/functional/lvm_setup.yml

especially for ooo_collocation scenario which is still using ceph-disk
testing.

tests/master: run lvm_setup.yml only when osd_scenario is lvm

---

tests/functional/all_daemons/container/hosts-ubuntu
tests/functional/all_daemons/hosts-ubuntu

add a missing inventory file,
remove an iscsigw node from all_daemons deployment

fix ubuntu testing on stable-3.2

---

roles/ceph-iscsi-gw/tasks/deploy_ssl_keys.yml

remove leftover introduced by 9d590f4

iscsi-gws: remove a leftover

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample

resync group_vars sample files with their corresponding original files.

doc: resync group_vars sample files

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mgr/templates/ceph-mgr.service.j2
roles/ceph-mon/tasks/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/templates/ceph-osd.service.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-rgw/templates/ceph-radosgw.service.j2
tox.ini

rename switch_to_containers scenario

switch_to_containers: a couple of fixes

---

raw_install_python.yml
roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
roles/ceph-facts/tasks/facts.yml
site.yml.sample
tests/conftest.py
tests/functional/tests/mds/test_mds.py
tests/functional/tests/mgr/test_mgr.py
tests/functional/tests/mon/test_mons.py
tests/functional/tests/nfs/test_nfs_ganesha.py
tests/functional/tests/osd/test_osds.py
tests/functional/tests/rbd-mirror/test_rbd_mirror.py
tests/functional/tests/rgw/test_rgw.py
tests/functional/tests/rgw/test_rgw_tuning.py
tests/functional/tests/test_install.py
tox.ini

- fix uid/gid in ceph tmpfiles
- move file to `/etc/tmpfiles.d`

container: fix tmpfiles.d ceph files

---

roles/ceph-validate/tasks/check_eth_mon.yml
roles/ceph-validate/tasks/check_eth_rgw.yml

Convert interface names to underscores
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1540881
Signed-off-by: Tomas Petr <tpetr@redhat.com>

Convert interface names to underscores

---

tox.ini

this scenario doesn't exist in stable-3.1

tests: remove lvm_batch scenario

---

roles/ceph-mgr/tasks/main.yml

Signed-off-by: wumingqiao <wumingqiao@beyondcent.com>

ceph-mgr: run mgr_modules.yml only on the first mgr host

---

site-container.yml.sample
site.yml.sample

This reverts commit 9c10affb69a89a018ea16f191dd7008e89d6c911.

Revert "site.yml: run ceph-validate before facts/defaults roles"

---

infrastructure-playbooks/purge-cluster.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-facts/tasks/set_monitor_address.yml

Similar to #3658
Since there's too many changes between master and stable branches let's
commit directly in each branches instead of trying to backport this
commit.

remove all NBSPs on master branch

---

tox.ini

update scenario has been moved to a dedicated tox ini file.
We shouldn't have any references to this scenario in the main tox ini
file.

tests: clean tox.ini

---

.mergify.yml

Add action to backport commits to stable-4.0.

mergify: Update with stable-4.0 branch

---

tests/conftest.py
tests/functional/tests/osd/test_osds.py
tox-update.ini
tox.ini

refact the update scenario like it has been made in master.
(see f0e616962)

tests: refact update scenario (stable-3.2)

---

README-MULTISITE.md
group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml
roles/ceph-rgw/tasks/multisite/master.yml
roles/ceph-rgw/tasks/multisite/secondary.yml
tests/functional/rgw-multisite/container/group_vars/rgws
tests/functional/rgw-multisite/container/hosts
tests/functional/rgw-multisite/container/secondary/hosts
tests/functional/rgw-multisite/group_vars/rgws
tests/functional/rgw-multisite/hosts
tests/functional/rgw-multisite/secondary/hosts

rgw multisite: add more than 1 rgw to the master or secondary zone

---

tests/conftest.py

add nautilus and octopus releases.

tests: update ceph_release_num in conftest.py

---

tox.ini

Run tests with 8 processes/cores since other scenarios do the same.

add_mdss: change number of processes for testing to 8

---

RELEASE-NOTE.md
infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/rolling_update.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-common/tasks/facts_mon_fsid.yml
roles/ceph-nfs/tasks/create_rgw_nfs_user.yml
roles/ceph-osd/tasks/openstack_config.yml
roles/ceph-rgw/handlers/main.yml
roles/ceph-validate/tasks/check_ipaddr_mon.yml

this can cause issues, let's replace all of these chars with real
spaces.

remove all NBSPs char in stable-3.2 branch

---

infrastructure-playbooks/shrink-osd.yml

Signed-off-by: lishuhao letterwuyu@gmail.com

Fix comment content

---

ceph-ansible.spec.in
docs/source/index.rst
infrastructure-playbooks/purge-docker-cluster.yml
library/test_ceph_volume.py
requirements.txt
roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
roles/ceph-nfs/tasks/main.yml
roles/ceph-validate/tasks/check_system.yml
tests/functional/tests/mon/test_mons.py
tests/requirements.txt
tox-dashboard.ini
tox-update.ini
tox.ini

- remove private attribute with import_role.
- update documentation.
- update rpm spec requirement.
- fix MagicMock python import in unit tests.
Closes: #3765 

switch to ansible 2.8

---

tox-update.ini
tox.ini

This commit splits the update scenario into a dedicated tox.ini file.

tests: split update in a dedicated tox.ini file

---

plugins/actions/config_template.py

This change pulls in the most recent release of the config_template module
into the ceph_ansible action plugins.
Signed-off-by: Kevin Carter <kecarter@redhat.com>

Sync config_template from upstream

---

roles/ceph-validate/tasks/check_devices.yml

see https://bugzilla.redhat.com/show_bug.cgi?id=1648168#c17 for details.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1648168#c17

validate: fail in check_devices at the right task

---

infrastructure-playbooks/shrink-mon.yml

This commit should've been part of commit
2fb12ae55462f5601a439a104a5b0c01929accd9.

use pre_tasks and post_tasks in shrink-mon.yml too

---

infrastructure-playbooks/rolling_update.yml
roles/ceph-osd/tasks/main.yml

- remove a legacy task
- add a health check early
- only mask and stop unit in mgr sequence

update: various fixes

---

roles/ceph-config/templates/ceph.conf.j2
roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mgr/templates/ceph-mgr.service.j2
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-nfs/templates/ceph-nfs.service.j2
roles/ceph-osd/templates/ceph-osd-run.sh.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
roles/ceph-rgw/templates/ceph-radosgw.service.j2

related ceph-container PR: ceph/ceph-container#1408
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710548

containers: improve logging

---

roles/ceph-nfs/templates/ganesha.conf.j2

remove legacy options
```
21/06/2019 15:36:11 : epoch 5d0cf96b : nfs0 : ganesha.nfsd-115[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:13): Unknown parameter (Dir_Max)
21/06/2019 15:36:11 : epoch 5d0cf96b : nfs0 : ganesha.nfsd-115[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:14): Unknown parameter (Cache_FDs)
```

nfs: clean template

---

docs/source/index.rst

for the Ceph master branch.
Signed-off-by: Theo Ouzhinski touzhinski@gmail.com

docs: Correct weird wording

---

roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-mgr/tasks/mgr_modules.yml
roles/ceph-osd/tasks/start_osds.yml

This commit fixes the lint errors [301,306]:

lint: fix some lint errors

---

roles/ceph-container-engine/tasks/pre_requisites/debian_prerequisites.yml
roles/ceph-rgw/tasks/multisite/master.yml

[201] Trailing whitespace
[206] Variables should have spaces before and after: {{ var_name }}

lint: fix error [201,206]

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml
roles/ceph-grafana/tasks/configure_grafana.yml
site.yml.sample

download grafana dashboard files from github when running on Debian based OS
Signed-off-by: liuxu <liuxu623@gmail.com>

dashboard: add grafana dashboard support on Debian based OS

---

.github/stale.yml

30d + 7d for closing an issue that is inactive sounds enough.

stalebot: decrease daysUntilStale parameter

---

Vagrantfile

because of the current ip address assignation, it's not possible to
deploy more than 9 nodes per daemon type.
This commit refact a bit and allows us to get around this limitation.
(cherry picked from commit 778c51a0ff7a8c66c464f4828a0f87dd290e1c3e)

Vagrantfile: support more than 9 nodes per daemon type

---

tests/functional/all_daemons/container/group_vars/iscsigws
tests/functional/all_daemons/group_vars/iscsigws

so we dont' have to hardcode this in the tests

tests: set gateway_ip_list dynamically

---

roles/ceph-handler/handlers/main.yml
roles/ceph-handler/tasks/main.yml

This commit merges the two restart tasks into a single one, this way
it's one task less to notify.

handlers: refact osd handler

---

infrastructure-playbooks/rolling_update.yml
roles/ceph-mds/tasks/create_mds_filesystems.yml

Refact the mds cluster upgrade code in order to follow the documented
recommandation.
See: https://github.com/ceph/ceph/blob/master/doc/cephfs/upgrading.rst
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1569689

update: follow new recommandation to upgrade mds cluster

---

infrastructure-playbooks/rolling_update.yml

Add missing quote in order to keep consistency.

update: add missing quotes

---

group_vars/rhcs.yml.sample
rhcs_edits.txt
roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-iscsi-gw/tasks/common.yml
roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml

This PR adds:
- ceph-iscsi stable repository support (from download.ceph.com)
- ceph-iscsi integration in the ceph dashboard.
Closes: #4638
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1764173

ceph-iscsi: dashboard and repository improvements

---

infrastructure-playbooks/rolling_update.yml

otherwise a single MDS would never be updated.

update: avoid skipping single mds deployment upgrade

---

roles/ceph-nfs/tasks/create_rgw_nfs_user.yml

RGW NFS user should update with the keys from group vars when those are specified

Ceph RGW nfs user modify to specific defined access key and secret key

---

tox-update.ini

test upgrades from nautilus to octopus instead of mimic to octopus.

tests: upgrade from nautilus to octopus in master

---

tests/scripts/vagrant_up.sh

monitor how long it takes to get all VMs up and running

tests: add time command in vagrant_up.sh

---

group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

Removes an outdated information from osds.yml.sample
Closes https://bugzilla.redhat.com/show_bug.cgi?id=1640525
Signed-off-by: Noah Watkins <nwatkins@redhat.com>

Remove outdated documentation

---

roles/ceph-container-engine/tasks/main.yml
roles/ceph-container-engine/vars/CentOS-8.yml
tox-podman.ini

This reverts commit 19e9a06ab1429769a0513c54c12bf07698d2178f.

Revert "tox-podman: use centos 8 vagrant image"

---

tox-update.ini

The path to the inventory isn't correct because we are missing the variable
`CONTAINER_DIR` here.

tests: fix update scenario (container)

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

defaults: fix a typo

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

Add SSL cert comment 

---

infrastructure-playbooks/shrink-mds.yml
roles/ceph-facts/tasks/facts.yml

This commit deletes the filesystem when no more MDS is present after shrinking operation.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1787543

shrink-mds: fix filesystem removal task

---

infrastructure-playbooks/docker-to-podman.yml
tests/functional/docker2podman/Vagrantfile
tests/functional/docker2podman/ceph-override.json
tests/functional/docker2podman/group_vars/all
tests/functional/docker2podman/group_vars/clients
tests/functional/docker2podman/group_vars/iscsigws
tests/functional/docker2podman/group_vars/mons
tests/functional/docker2podman/group_vars/osds
tests/functional/docker2podman/group_vars/rgws
tests/functional/docker2podman/hosts
tests/functional/docker2podman/vagrant_variables.yml
tox-docker2podman.ini

This commit adds a package installation task in order to install podman
during the docker-to-podman.yml migration playbook.

docker2podman: install podman package

---

infrastructure-playbooks/rolling_update.yml

This task is a code duplicate, probably a legacy, let's remove it.

update: remove legacy

---

README-MULTISITE.md
group_vars/rgws.yml.sample
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/tasks/main.yml
roles/ceph-rgw/tasks/rgw_create_pools.yml
roles/ceph-validate/tasks/check_rgw_pools.yml
roles/ceph-validate/tasks/main.yml
tests/functional/add-rgws/group_vars/rgws
tests/functional/all-in-one/container/group_vars/all
tests/functional/all-in-one/group_vars/all
tests/functional/all_daemons/container/group_vars/rgws
tests/functional/all_daemons/group_vars/rgws
tests/functional/collocation/container/group_vars/rgws
tests/functional/collocation/group_vars/rgws
tests/functional/podman/group_vars/rgws
tests/functional/rgw-multisite/container/group_vars/rgws
tests/functional/rgw-multisite/container/secondary/group_vars/rgws
tests/functional/rgw-multisite/group_vars/rgws
tests/functional/rgw-multisite/secondary/group_vars/rgws
tests/functional/shrink_rgw/container/group_vars/rgws
tests/functional/shrink_rgw/group_vars/rgws

Add support for erasure code pools.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1731148
Co-authored-by: Dimitri Savineau <dsavinea@redhat.com>

rgw: extend automatic rgw pool creation capability

---

roles/ceph-rgw/tasks/rgw_create_pools.yml

5s as a connection timeout could be low in some setup. Let's increase
it to 10s.

ceph-rgw: increase connection timeout to 10

---

requirements.txt
tests/requirements.txt

See https://github.com/advisories/GHSA-3m93-m4q6-mc6v

requirements: enforce ansible version requirement

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-container-cluster.yml
roles/ceph-facts/tasks/facts.yml
roles/ceph-facts/tasks/set_radosgw_address.yml
roles/ceph-infra/tasks/configure_firewall.yml
roles/ceph-rgw/handlers/main.yml
roles/ceph-validate/tasks/check_system.yml

This commits add ansible 2.9 support in addition of 2.8.

Add ansible 2.9 support

---

library/ceph_volume.py
tests/functional/filestore-to-bluestore/container/group_vars/all
tests/functional/filestore-to-bluestore/container/hosts
tests/functional/filestore-to-bluestore/group_vars/all
tests/functional/filestore-to-bluestore/hosts

This commit fixes a regression introduced by
0326d992c2b6b92a6d4b8ccf2a51d9343652da48.

library: fix bug in ceph_volume

---

roles/ceph-config/templates/ceph.conf.j2
roles/ceph-facts/tasks/set_radosgw_address.yml
roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
roles/ceph-infra/tasks/configure_firewall.yml
roles/ceph-rgw/tasks/multisite/checks.yml
roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
roles/ceph-rgw/tasks/multisite/create_zone_user.yml
roles/ceph-rgw/tasks/multisite/main.yml
roles/ceph-rgw/tasks/multisite/master.yml
roles/ceph-rgw/tasks/multisite/secondary.yml
roles/ceph-validate/tasks/check_rgw_multisite.yml
tests/functional/rgw-multisite/container/group_vars/rgws
tests/functional/rgw-multisite/container/host_vars/osd0
tests/functional/rgw-multisite/container/hosts
tests/functional/rgw-multisite/container/secondary/group_vars/rgws
tests/functional/rgw-multisite/container/secondary/host_vars/osd0
tests/functional/rgw-multisite/container/secondary/hosts
tests/functional/rgw-multisite/group_vars/rgws
tests/functional/rgw-multisite/host_vars/osd0
tests/functional/rgw-multisite/hosts
tests/functional/rgw-multisite/secondary/group_vars/rgws
tests/functional/rgw-multisite/secondary/host_vars/osd0
tests/functional/rgw-multisite/secondary/hosts
tests/functional/rgw_multisite.yml

This commit adds the multi-instances when deploying rgw multisite
Co-authored-by: Dimitri Savineau <dsavinea@redhat.com>

rgw: add multi-instances support when deploying multisite

---

group_vars/clients.yml.sample
roles/ceph-client/defaults/main.yml
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-nfs/tasks/main.yml
site-container.yml.sample
site.yml.sample

This commit refact and fix the nfs deployment with external ceph cluster
support.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1814942
(cherry picked from commit cc28d9ec2669f14fa2e75627093aa65905af969f)

nfs: fix nfs with external ceph cluster support (bp #5169)

---

roles/ceph-facts/tasks/set_monitor_address.yml

This commit fixes a typo in some task titles

facts: fix typo

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/release-rhcs.yml
roles/ceph-container-common/tasks/release.yml
roles/ceph-defaults/defaults/main.yml
tests/conftest.py

Add the 16th ceph release: pacific.

Add pacific release

---

tox.ini

This commit removes some leftover in tox.ini

tests: remove some legacy in tox.ini

---

.mergify.yml

Add action to backport commits to stable-5.0.

mergify: Update with stable-5.0 branch

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

In master, even though we are using dev repo, the value here should be closer
from the last stable released.

[skip ci] defaults: change nfs_ganesha_stable_branch

---

library/ceph_volume.py
tests/library/test_ceph_volume.py

This is an manual backport of pull request #5209 done by Mergify

ceph_volume: fix multiple db/wal devices (bp #5209)

---

infrastructure-playbooks/rolling_update.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
roles/ceph-client/tasks/create_users_keys.yml
site-docker.yml.sample
site.yml.sample

This PR is intended to backport playbook execution time improvements on client nodes in stable-3.2 branch
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1818708

backport playbook execution time improvements on client nodes in stable-3.2

---

README.rst
ceph-ansible.spec.in
group_vars/all.yml.sample
group_vars/rhcs.yml.sample
requirements.txt
roles/ceph-common/tasks/installs/configure_el8_dep.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_dev_repository.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
roles/ceph-validate/tasks/check_system.yml
tests/functional/all_daemons/group_vars/nfss
tests/requirements.txt
tox-docker2podman.ini
tox-external_clients.ini
tox-filestore_to_bluestore.ini
tox-podman.ini
tox-update.ini
tox.ini

This commit updates the testing so we test stable-5.0 against
ceph@octopus.

tests: update testing

---

site-container.yml.sample

This adds a symlink to the site-docker.yml.sample playbook.

Add site-container.yml symlink

---

library/ceph_key.py

553584cbd0d014429e665f998776e8d198f72d2b introduced a regression when no
secret is passed, it overwrites the secret each time the task is run.

ceph_key: fix idempotency when no secret is passed

---

library/ceph_key.py

Fetch the key when it is present in the cluster but not on the node.

ceph_key: fetch key when needed

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
roles/ceph-mgr/tasks/pre_requisite.yml

This is a manual backport of pull request #5249 done by Mergify
---

ceph-mgr: add saml python lib for dashboard SSO (bp #5249)

---

roles/ceph-facts/tasks/facts.yml
roles/ceph-mds/tasks/create_mds_filesystems.yml

This commit fixes --limit runs against mds nodes.

mds: fix --limit runs against mds nodes

---

roles/ceph-validate/tasks/check_system.yml

This is a manual backport of pull request #5264 done by Mergify
---
<details>
<br />
- `@Mergifyio rebase` will rebase this PR
</details>

ceph-validate: update RHEL requirement for RHCS (bp #5264)

---

roles/ceph-facts/tasks/facts.yml
roles/ceph-mds/tasks/create_mds_filesystems.yml

This is a manual backport of pull request #5270 done by Mergify
---
<details>
<br />
- `@Mergifyio rebase` will rebase this PR
</details>

mds: fix --limit run against mds nodes ((bp #5270)

---

library/ceph_volume.py

This is a manual backport of pull request #5262 done by Mergify
---
<details>
<br />
</details>

library/ceph_volume: look for error messages in stderr (bp #5262)

---

roles/ceph-validate/tasks/check_system.yml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1826884
rc is a number not a string. removing '' from the 0.

Correcting validation type check on rc

---

tests/functional/all_daemons/container/hosts
tests/functional/all_daemons/container/vagrant_variables.yml

This commit adds back nfs testing on master branch

tests: add back nfs testing on master

---

README-MULTISITE.md

+ Mention of this variable was missing in the original version.
+ Minor revisions around the concept of secondary zone.

[skip ci] docs: fix multisite docs add endpoints var in rgw_instances section

---

roles/ceph-validate/tasks/check_system.yml

This is a manual backport of pull request #5296 done by Mergify
---
<details>
<br />
</details>

typo: updating type check on rc

---

group_vars/all.yml.sample
group_vars/mgrs.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/installs/configure_el8_dep.yml
roles/ceph-common/tasks/installs/install_on_redhat.yml
roles/ceph-common/tasks/installs/redhat_community_repository.yml
roles/ceph-common/tasks/installs/redhat_dev_repository.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-mgr/defaults/main.yml
roles/ceph-mgr/tasks/mgr_modules.yml
roles/ceph-mgr/tasks/pre_requisite.yml
roles/ceph-validate/tasks/check_system.yml
tests/conftest.py
tests/functional/docker2podman/group_vars/all
tests/functional/docker2podman/hosts

This is a manual backport of pull request #5237 done by Mergify
---
<details>
<br />
</details>

Readd CentOS 7 with conditions (bp #5237)

---

README-MULTISITE.md

Make all of the hosts start at 1 and not 0,
also make some minor changes in scenario 3 to
remova an inconsistency.

[skip-ci] docs: minor fixes to README-MULTISITE.md

---

.travis.yml
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
library/ceph_pool.py
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-iscsi-gw/tasks/common.yml
roles/ceph-mds/tasks/create_mds_filesystems.yml
roles/ceph-osd/tasks/openstack_config.yml
tests/functional/all_daemons/container/group_vars/all
tests/functional/all_daemons/container/group_vars/clients
tests/functional/all_daemons/group_vars/all
tests/functional/all_daemons/group_vars/clients
tests/library/test_ceph_pool.py

This commit adds a new module `ceph_pool`

library: add ceph_pool module

---

docs/source/day-2/upgrade.rst
docs/source/index.rst

This commit adds a chapter about the ceph upgrade process.
Closes: #5393

docs: Add upgrade operation.

---

roles/ceph-container-engine/vars/Ubuntu-20.yml

Signed-off-by: George Shuklin <george.shuklin@gmail.com>

[skip ci] Add container settings for Ubuntu 20 (the same as Ubuntu 18)

---

library/ceph_volume.py
tox-docker2podman.ini
tox-external_clients.ini
tox-filestore_to_bluestore.ini
tox-podman.ini
tox-update.ini
tox.ini

This commit makes all jobs authenticating to docker hub in order to
avoid the rate limit.

tests: add docker hub authentication in jobs

---

library/ceph_volume.py

do not skip zapping if osd_fsid is passed
(cherry picked from commit f402ab2b87813f0f9c3fba661a52f5afebc19723)

[backport stable-5.0] ceph_volume: fix regression

---

site-container.yml.sample
site.yml.sample

Remove two other pattern 'iscsigws' in main playbook that have been
missed in cc0d9697c554e459af11965fc2710e42abef4e13

play: followup on cc0d969

---

infrastructure-playbooks/cephadm-adopt.yml
tox.ini

This adds an optional cephadm_adopt scenario which is based on
all_daemons.

[skip ci] tox: add cephadm_adopt scenario

---

infrastructure-playbooks/cephadm-adopt.yml

- wait for monitor in quorum
- add osd flags during adoption
- add iscsi support
- remove the cephadm script
- show orchestrator status

[skip ci] batch fixes/features cephadm adopt

---

library/ceph_key.py

ceph_key: fix bug in 'info' feature
Fix 'info' feature from ceph_key.py module

ceph_key: fix bug in 'info' feature

---

infrastructure-playbooks/cephadm-adopt.yml

- inform users about cephadm
- refresh the service/daemon list
- Revert "remove the cephadm script"

[skip ci] enchancement on displayed information

---

infrastructure-playbooks/shrink-osd.yml
tests/functional/shrink_osd/container/group_vars/osds
tests/functional/shrink_osd/container/hosts
tests/functional/shrink_osd/container/vagrant_variables.yml
tests/functional/shrink_osd/group_vars/osds
tests/functional/shrink_osd/hosts
tests/functional/shrink_osd/vagrant_variables.yml
tox-shrink_osd.ini

This adds more coverage on the shrink_osd scenario.

tests: refact shrink_osd scenario

---

library/ceph_key.py
tests/library/test_ceph_key.py

This commit adds more coverage regarding the testing of ceph_key module

tests: add more coverage for test_ceph_key

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-dashboard/tasks/configure_grafana_layouts.yml
roles/ceph-defaults/defaults/main.yml

This is a manual backport of pull request #5155
---
<details>
<br />
- `@Mergifyio rebase` will rebase this PR
</details>

Fix for TLS dashboard (bp #5155)

---

roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml

In order to avoid failures that could be fixed by simply
retrying.

iscsigw: add retry/until

---

library/ceph_key.py
tests/library/test_ceph_key.py

This commit refactors the code to remove a duplicate condition and it
makes the `state: absent` code idempotent

ceph_key: refact the code and minor fixes

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/installs/debian_custom_repository.yml
roles/ceph-common/tasks/installs/redhat_custom_repository.yml
roles/ceph-defaults/defaults/main.yml

This is backport of commit 4c592066b7c1caaec700af347fc9edf2109c1659
Signed-off-by: Rafal Wadolowki <rwadolowski@cloudferro.com>

[skip ci] ceph_custom_repo: define apt and rpm key for custom repo

---

roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-facts/tasks/facts.yml

there's no need to run this task on all nodes.
This uses too much memory for nothing.
Backport: #5663
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1856981
(cherry picked from commit f0fe193d8ec48414447aa4a7d50b1a9859c71295)

facts: refact and optimize memory consumption (bp #5663)

---

roles/ceph-infra/tasks/main.yml
roles/ceph-infra/templates/logrotate.conf.j2

The iscsi nodes aren't included in the logrotate condition.

[skip ci] ceph-infra: include iscsi nodes for logrotate

---

README.rst

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

docs: update URLs to point to the RTD links

---

docs/source/installation/methods.rst

Based on the discussion in issue https://github.com/ceph/ceph-ansible/issues/5392 I added now this paragraph to this page.
Signed-off-by: Raffael Luthiger <r.luthiger@huanga.com>

[skip ci] Update methods.rst

---

roles/ceph-rgw/tasks/rgw_create_pools.yml

This reverts commit ba3512a8fcffdbbd40fbd41f4e16b0d3ca1ca328.

Revert "ceph-rgw: remove ceph_pool state and default value"

---

.github/workflows/flake8.yml
library/ceph_add_users_buckets.py
library/ceph_crush.py
library/ceph_dashboard_user.py
library/ceph_key.py
library/ceph_pool.py
library/ceph_volume.py
library/igw_lun.py
library/igw_purge.py

This commit ensure all ceph-ansible modules pass flake8 properly.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

library: flake8 ceph-ansible modules

---

roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-osd/tasks/openstack_config.yml

In addition to f7e2b2c608eef4bbba47586f1e24d6ade1572758

common: follow up on #5948

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

see linked bz for details
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1889426

dashboard: enable https by default

---

site-container.yml.sample
site.yml.sample

This tag can be set at the play level.

[skip ci] main: followup on pr 6012

---

.github/workflows/pytest.yml
.travis.yml
tests/requirements.txt

Move the pytest testing from TravisCI to Github workflow.

[skip ci] tests: use github workflow for pytest

---

.github/workflows/pytest.yml
ansible.cfg
library/ceph_dashboard_user.py
library/ceph_ec_profile.py
library/ceph_fs.py
library/ceph_key.py
library/ceph_pool.py
library/ceph_volume.py
module_utils/ca_common.py
roles/ceph-rgw/tasks/rgw_create_pools.yml
tests/library/ca_test_common.py
tests/library/test_ca_common.py
tests/library/test_ceph_dashboard_user.py
tests/library/test_ceph_ec_profile.py
tests/library/test_ceph_fs.py
tests/library/test_ceph_key.py

This PR adds a new module `ceph_ec_profile` and introduce `module_utils` to avoid duplicating things in each module

library: add new module ceph_ec_profile

---

tests/library/test_ceph_volume_simple_activate.py
tests/library/test_ceph_volume_simple_scan.py

[skip ci] tests: use ca_test_common with ceph_volume_simple

---

.mergify.yml

This reverts commit fb7dced59869cc8cd5d0f7920f86ea5d836b5ec7.

[skip ci] Revert "mergify: add configuration for 4.2z1 branch"

---

infrastructure-playbooks/filestore-to-bluestore.yml

since cf7345f143148a6be2d71954f829a8f7fe11ab22, we don't need to set
this fact anymore.

fs2bs: remove a legacy fact

---

tests/functional/all_daemons/container/hosts
tests/functional/all_daemons/hosts
tox.ini

in order to test lvm batch in purge scenario.

tests: use lvm batch on osd2 (all_daemons)

---

library/cephadm_bootstrap.py
tests/library/test_cephadm_bootstrap.py

This adds the custom registry auth support when using a registry with
authentication.

library/cephadm_bootstrap: add registry support

---

infrastructure-playbooks/rolling_update.yml
roles/ceph-common/tasks/installs/redhat_dev_repository.yml
roles/ceph-validate/tasks/check_system.yml
tox-update.ini
tox.ini

There's no need to achieve this in two tasks.

rolling_update: pg check refactor

---

docs/source/dev/index.rst
docs/source/index.rst

- mention `stable-6.0` requirements.
- update some patterns.

doc: update the documentation

---

docs/source/installation/containerized.rst

This adds more documentation to the configuration and usage of
containerizerd deployment.
Closes: #6198

doc: update containerized deployment

---

docs/source/installation/containerized.rst

[skip ci] doc: add a note about "latest" tags

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-common/tasks/release-rhcs.yml
roles/ceph-container-common/tasks/release.yml
roles/ceph-defaults/defaults/main.yml
tests/conftest.py

Add the 17th ceph release: quincy.

Add quincy release

---

tox.ini

In order to avoid false positive in the CI that I've been unable to
reproduce.

tests: increase nb of rerun in pytest

---

docs/source/day-2/upgrade.rst
docs/source/dev/index.rst
docs/source/index.rst
docs/source/installation/methods.rst
docs/source/installation/non-containerized.rst
docs/source/osds/scenarios.rst

While working on the previous PR, I found a couple of typos in the
docs. This fixes those.

[skip ci] Docs: fix some typos

---

docs/source/osds/scenarios.rst

Ceph documentation has changed the paths.

docs: Update URL to LVM batch

---

roles/ceph-validate/tasks/main.yml

update the message accordingly to the check updated in
commit 98e32b92f30c4e234f51f8f3d29e932764405e25

validate: followup on 98e32b9

---

tests/functional/all_daemons/hosts
tests/functional/all_daemons/vagrant_variables.yml

This reverts commit 8372b6792fb94bd7e333ac8017ffca0f139702c7.

Revert "tests: disable nfs testing on master"

---

.deepsource.toml
plugins/actions/config_template.py
plugins/filter/ipaddrs_in_ranges.py
tests/functional/tests/nfs/test_nfs_ganesha.py
tests/functional/tests/rgw/test_rgw.py

Hey, I'm a Developer Outreach at [DeepSource](https://deepsource.io/) and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality and performance improvements](https://deepsource.io/gh/akshgpt7/ceph-ansible/) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Use literals instead of function calls to create data structure.
- Refactor unnecessary list comprehension.
- Simplify `if` statement.
- Refactor useless `else` block in the loop.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

core: Refactor code quality issues

---

infrastructure-playbooks/cephadm-adopt.yml
roles/ceph-nfs/tasks/create_rgw_nfs_user.yml
roles/ceph-nfs/tasks/start_nfs.yml

This PR fixes 2 BZs :
- https://bugzilla.redhat.com/show_bug.cgi?id=1943170
- https://bugzilla.redhat.com/show_bug.cgi?id=1944504

[skip ci] cephadm_adopt: various fixes

---

ceph-ansible.spec.in
requirements.txt
roles/ceph-validate/tasks/check_system.yml
tests/requirements.txt
tox.ini

Let's start testing against ansible 2.10

core: bump ansible version

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-defaults/defaults/main.yml

The multisite README file has been merged into a single file.
Closes: #6411

[skip ci] ceph-defaults: update multisite readme reference

---

roles/ceph-rgw-loadbalancer/templates/keepalived.conf.j2
roles/ceph-validate/tasks/main.yml

ceph-rgw-loadbalancer: Fix keepalived master selection (backport #5401)

---

tests/scripts/generate_ssh_config.sh

Signed-off-by: David Galloway <dgallowa@redhat.com>

tests: Retry generating SSH vagrant config.  Also add some debug.

---

roles/ceph-container-common/tasks/prerequisites.yml

Playbook failing saying:
msg: 'Could not find the requested service lvmetad: host'
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1955040

Container: Fixing service name lvm2-lvmetad

---

library/ceph_key.py
tests/library/test_ceph_key.py

Also code lint with flake8
Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

library/ceph_key.py: rewrite for generate_ceph_cmd()

---

.github/workflows/ansible-lint.yml
.github/workflows/defaults.yml
.github/workflows/signed-off.yml
tests/scripts/workflows/defaults.sh
tests/scripts/workflows/signed-off.sh

This adds some GitHub workflows and drops ansible-lint testing against py3.6 and py3.7

[skip ci] update GitHub workflows

---

infrastructure-playbooks/cephadm-adopt.yml

Set the nfs application to the ganesha pool.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1956840

[skip ci] cephadm-adopt: set application on ganesha pool

---

infrastructure-playbooks/rolling_update.yml

[skip ci] update: followup on pr #6689

---

infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/purge-container-cluster.yml

This commit reindents the playbook.
Also improve readability by adding an extra line between plays.

|skip ci] purge: reindent playbook

---

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

This was reverted by 7ddbe74
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1990733

switch2container: fix mon quorum check

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-client/tasks/create_users_keys.yml
roles/ceph-client/tasks/pre_requisite.yml
roles/ceph-crash/tasks/main.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-iscsi-gw/tasks/common.yml
roles/ceph-mds/tasks/common.yml
roles/ceph-mds/tasks/non_containerized.yml
roles/ceph-mgr/tasks/common.yml
roles/ceph-mon/tasks/ceph_keys.yml
roles/ceph-mon/tasks/deploy_monitors.yml
roles/ceph-nfs/tasks/main.yml
roles/ceph-nfs/tasks/pre_requisite_container.yml
roles/ceph-nfs/tasks/pre_requisite_non_container.yml
roles/ceph-osd/tasks/common.yml
roles/ceph-osd/tasks/openstack_config.yml
roles/ceph-rbd-mirror/tasks/common.yml
roles/ceph-rgw/tasks/common.yml
roles/ceph-rgw/tasks/pre_requisite.yml

let's not display any keyring secret by default in ansible log.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1980744

common: do not log keyring secret

---

infrastructure-playbooks/rolling_update.yml

this play doesn't need to gather facts from localhost

[skip ci] update: gather facts only one time

---

roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
roles/ceph-validate/tasks/main.yml

Only include specific variables when they are undefined

[skip ci] ceph-container-engine: allow override container_package_name and container_service_name

---

infrastructure-playbooks/purge-cluster.yml

This can help to skip docker removal tasks

purge: add remove_docker tag

---

roles/ceph-dashboard/tasks/configure_dashboard.yml
tests/functional/collocation/container/hosts
tests/functional/collocation/container/vagrant_variables.yml
tests/functional/collocation/hosts
tests/functional/collocation/vagrant_variables.yml

we update the pool size from 1 to 2 but only 1 node is available.

[skip ci] tests: add osd node in collocation

---

tests/functional/collect-logs.yml

related ceph-build PR: ceph/ceph-build#1914

[skip ci] tests: move collect-logs.yml to ceph-ansible repo

---

tests/functional/collect-logs.yml

- change `ceph -s` output to json-pretty.
- gather rgw logs

[skip ci] tests: update collect-logs.yml playbook

---

roles/ceph-validate/tasks/check_repository.yml

Otherwise, installation on SuSe fails.
Fixes: #6996

validate: support obs repository

---

infrastructure-playbooks/purge-cluster.yml

After run purge-cluster.yml playbook some packages are still installed on the OS. They should also be removed.
Signed-off-by: jowsiewski <owsiewski@gmail.com>

[skip ci] Remove the remaining packages

---

infrastructure-playbooks/cephadm-adopt.yml

Fixes commit da42f3d139e595d09edfb30334fbc7ce17ffa3fe

[skip ci] Using another user than root for cephadm ssh connections fails

---

infrastructure-playbooks/backup-and-restore-ceph-files.yml

this playbook can backup or restore some ceph files.
(/etc/ceph, /var/lib/ceph, ...)

[skip ci] contrib: add a playbook

---

.mergify.yml

[skip ci] mergify: add restriction on backport command

---

docs/source/index.rst
infrastructure-playbooks/filestore-to-bluestore.yml
infrastructure-playbooks/lv-teardown.yml
infrastructure-playbooks/purge-cluster.yml
infrastructure-playbooks/shrink-osd.yml
requirements.txt
requirements.yml
roles/ceph-validate/tasks/check_system.yml
tests/functional/setup.yml
tests/requirements.txt
tox-external_clients.ini
tox-filestore_to_bluestore.ini
tox-shrink_osd.ini
tox-subset_update.ini
tox-update.ini
tox.ini

Add required changes to support ansible 2.12

ansible: bump to ansible 2.12

---

.mergify.yml

add stable-7.0 configuration and reindent the file properly.

[skip ci] Update mergify

---

README.rst
site-container.yml.sample
site.yml.sample
tox-external_clients.ini
tox-subset_update.ini
tox-update.ini
tox.ini

Given that the project is still maintained for the time being, let's add a better
comment about that.

add better clarification on ceph-ansible current status

---

tox-external_clients.ini
tox-filestore_to_bluestore.ini
tox-shrink_osd.ini
tox-subset_update.ini
tox-update.ini
tox.ini

This reverts commit a568314eda48f2e1864ddc1e7648542db3034e7f.

Revert "tests: use build main/6f765e2"

---

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml

s/of/or ..
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2099828#c25

[skip ci] common: fix a typo

---

infrastructure-playbooks/backup-and-restore-ceph-files.yml

current approach is too complex and causes too many issues permission
issues.

[skip ci] backup-and-restore: use archive/unarchive approach

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
roles/ceph-config/tasks/main.yml
roles/ceph-config/templates/ceph.conf.j2
roles/ceph-defaults/defaults/main.yml

- sets `autotune_memory_target_ratio` per osd host.
- ceph.conf refactor (osd)
- reindent main.yml in ceph-config
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2056675

[skip ci] config/osd: various fixes

---

group_vars/all.yml.sample
group_vars/rhcs.yml.sample
infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
module_utils/ca_common.py
roles/ceph-common/vars/main.yml
roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-defaults/defaults/main.yml
roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
tests/conftest.py
tests/functional/tests/rbd-mirror/test_rbd_mirror.py
tox.ini

"set_fact container_run_cmd" is not set when using --limit on MDS as facts
were not run on first MON.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2111017

Playbook fails when using --limit to install new MDS

---

infrastructure-playbooks/cephadm-adopt.yml

The commands called here are not built correctly.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2058038#c27

[skip ci] adopt: fix placement update calls for rgw

---

roles/ceph-crash/templates/ceph-crash.service.j2

regression by: d374e634edbb55cc1012308dff848a42a01fb012

ceph-crash: add missing \ in service file

---

roles/ceph-dashboard/tasks/configure_dashboard.yml
roles/ceph-facts/tasks/set_radosgw_address.yml

Restore missing changes from previous stable versions (4, 5, 6)

Some rgw fixes

---

infrastructure-playbooks/rolling_update.yml

Updates docker systemd files and reload docker daemon before starting upgrades
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2147570

[skip ci] Updates docker systemd files and reload docker daemon

---

tests/scripts/vagrant_up.sh

Uses the latest centos/streamX image available.
Signed-off-by: Teoman ONAY <tonay@ibm.com>

Uses a more recent version of the CentOS stream 8 box

---

roles/ceph-crash/templates/ceph-crash.service.j2
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mgr/templates/ceph-mgr.service.j2
roles/ceph-osd/templates/ceph-osd.service.j2
roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2

Add --security-opt label=disable to all containers accessing /var/lib/ceph

[skip ci] Fix selinux label issues

---

group_vars/all.yml.sample
infrastructure-playbooks/rolling_update.yml
roles/ceph-container-common/tasks/release.yml
roles/ceph-defaults/defaults/main.yml
tests/conftest.py
tox-subset_update.ini
tox-update.ini

This adds the few required changes in order to fully support Ceph Squid.

kickoff squid

---

group_vars/all.yml.sample
group_vars/osds.yml.sample
roles/ceph-osd/defaults/main.yml

regression by dcdb1710cbaf7946cf8161b4395697d4898680d3

ceph-volume: disable dmcrypt by default

---

group_vars/all.yml.sample
group_vars/mdss.yml.sample
group_vars/mgrs.yml.sample
group_vars/mons.yml.sample
group_vars/osds.yml.sample
group_vars/rgws.yml.sample
roles/ceph-mds/defaults/main.yml
roles/ceph-mds/templates/ceph-mds.service.j2
roles/ceph-mgr/defaults/main.yml
roles/ceph-mgr/templates/ceph-mgr.service.j2
roles/ceph-mon/defaults/main.yml
roles/ceph-mon/templates/ceph-mon.service.j2
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/templates/systemd-run.j2
roles/ceph-rgw/defaults/main.yml
roles/ceph-rgw/templates/ceph-radosgw.service.j2

This can help to have extra params or modify the existing ones via group vars.

systemd: export params as a varaible

---

library/radosgw_zone.py
tests/library/test_radosgw_zone.py

Support zone set from a json doc

radosgw_zone: add support zone set

---

library/ceph_volume.py

Run read-only actions on check mode

ceph-volume: add support check mode

---

.mergify.yml

This adds the mergify support for stable-8.0

mergify: add stable-8.0

---

library/ceph_config.py

ceph_config: add support config remove

---

roles/ceph-common/tasks/installs/configure_redhat_repository_installation.yml
tests/functional/setup.yml
tox.ini

- configure epel repo when running on rockylinux
- add required changes to tox so we can run tox testing against ubuntu and rocky linux
- clean up setup.yml

[skip ci] various changes

---

profiles/rgw-keystone-v2
profiles/rgw-keystone-v3

[skip ci] rgw_profiles: update rgw-keystone profiles

---

library/ceph_key.py

Check if the key exists before removal.

ceph-key: check for key existance on absent state

---

infrastructure-playbooks/cephadm-adopt.yml

spec file template conditions were incorrect

cephadm-adopt: fix "Update the placement of radosgw hosts" task

---

.github/workflows/pytest.yml

pytest: python-version typo

---

.mergify.yml

This adds the mergify support for stable-9.0

mergify: add stable-9.0
