- roles/ceph-osd/tasks/scenarios/collocated.yml
I forgot to re-add the partition check while refactoring the osd
> ceph-osd: do not re-prepare if already prepared

- tests/functional/centos/7/bluestore/hosts
- tests/functional/centos/7/bluestore/vagrant_variables.yml
- tests/functional/centos/7/bs-crypt-ded-jrn/hosts
- tests/functional/centos/7/bs-crypt-jrn-col/hosts
- tests/functional/centos/7/bs-dock-crypt-jrn-col/hosts
- tests/functional/centos/7/bs-dock-ded-jrn/hosts
- tests/functional/centos/7/bs-docker/hosts
- tests/functional/centos/7/bs-docker/vagrant_variables.yml
- tests/functional/centos/7/bs-jrn-col/hosts
- tests/functional/centos/7/crypt-ded-jrn/hosts
- tests/functional/centos/7/crypt-ded-jrn/vagrant_variables.yml
- tests/functional/centos/7/crypt-jrn-col/hosts
- tests/functional/centos/7/docker-crypt-jrn-col/hosts
- tests/functional/centos/7/docker-ded-jrn/hosts
- tests/functional/centos/7/jrn-col/hosts
- tests/functional/centos/7/lvm-osds/hosts
With Luminous we need to have a mgr daemon.
This commit adds an mgr node for all scenarios.
> tests: Add mgr node for all scenarios

- ansible.cfg
CI slaves are slow so by setting a higher value we can avoid the following error:
Timeout (12s) waiting for privilege escalation prompt:
Now we wait for 32 sec...
More info here: https://github.com/ansible/ansible/issues/14426
> ansible.cfg: increase ssh timeout

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-docker-common/tasks/pre_requisites/debian_prerequisites.yml
- roles/ceph-docker-common/tasks/pre_requisites/prerequisites.yml
- roles/ceph-docker-common/tasks/pre_requisites/remove_ceph_udev_rules.yml
- roles/ceph-docker-common/tasks/stat_ceph_files.yml
- roles/ceph-mon/tasks/docker/main.yml
- site-docker.yml.sample
- tests/functional/centos/7/cluster/hosts-switch-to-containers
- tox.ini
We must mask the image so we are sure that even if the system reboots
then the OSDs won't start.
> switch-from-non-containerized-to-containerized: mask unit files

- roles/ceph-common/tasks/checks/check_system.yml
We only test and support 2.3.x at the moment.
Closes: https://github.com/ceph/ceph-ansible/issues/1858
> fail if ansible version < 2.3

- group_vars/mdss.yml.sample
- group_vars/mgrs.yml.sample
- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- group_vars/rbd-mirrors.yml.sample
- group_vars/rgws.yml.sample
- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-mds/defaults/main.yml
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-rbd-mirror/defaults/main.yml
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/defaults/main.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
This can be controlled via 2 options:
* ceph_$DAEMON_docker_memory_limit
* ceph_$DAEMON_docker_cpu_limit
OSD and MDS have 5GB for memory and 1 CPU by default.
MON, RGW, RBD MIRROR, MGR have 2GB for memory and 1 CPU by default.
> container: introduce resource limitation for containers

- roles/ceph-client/tasks/create_users_keys.yml
Add new boolean parameter for client config create_key_file_only
with a default of false. When create_key_file_only is true, the
client tasks to connect to the external ceph cluster to verify
the key `ceph auth import` the key are skipped.
Fixes: #1848
> Add option to create client keyring file but not import it

- infrastructure-playbooks/purge-cluster.yml
Prior command was avoiding the lockbox mountpoint and the playbook was
failing with:
rmtree failed: [Errno 30] Read-only file system:
'/var/lib/ceph/osd-lockbox/4e9d8052-87c2-4fde-a56c-b8c108a3eefc/key-management-mode'
> purge: get lockbox mountpoint and unmount it

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
If devices is passed through an extra var this register won't work so
let's only register the var is devices is not defined. If devices is not
defined and lenght is > 0 then we trust its content.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1489099
> switch-from-non-containerized-to-containerized: fix devices

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
This commits allows us to run
switch-from-non-containerized-to-containerized-ceph-daemons.yml multiple
times.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1489353
> switch: make osd collection idempotent

- roles/ceph-common/tasks/installs/install_debian_packages.yml
The apt module will fail to downgrade packages properly when defualt
release is unnecessarily defined.
Closes #1869
> Omit the apt default_release if it is not needed

- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
> ceph-rbd-mirror; docker fix typo

- Vagrantfile
- group_vars/all.yml.sample
- group_vars/nfss.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-common/tasks/installs/debian_dev_repository.yml
- roles/ceph-common/tasks/installs/install_debian_enterprise_packages.yml
- roles/ceph-common/tasks/installs/install_debian_packages.yml
- roles/ceph-common/tasks/installs/install_redhat_packages.yml
- roles/ceph-common/tasks/installs/redhat_community_repository.yml
- roles/ceph-common/tasks/installs/redhat_dev_repository.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/tasks/pre_requisite.yml
- roles/ceph-nfs/templates/ganesha.conf.j2
- tests/conftest.py
- tests/functional/centos/7/cluster/group_vars/all
- tests/functional/centos/7/cluster/group_vars/nfss
- tests/functional/centos/7/cluster/hosts
- tests/functional/centos/7/cluster/vagrant_variables.yml
- tests/functional/dev_setup.yml
- tests/functional/tests/nfs/test_nfs_ganesha.py
- tests/functional/ubuntu/16.04/cluster/group_vars/all
- tests/functional/ubuntu/16.04/cluster/group_vars/nfss
- tests/functional/ubuntu/16.04/cluster/hosts
- tests/functional/ubuntu/16.04/cluster/vagrant_variables.yml
This PR is ready to be merged.
> Wip RGW NFS

- group_vars/mdss.yml.sample
- group_vars/mgrs.yml.sample
- group_vars/mons.yml.sample
- group_vars/nfss.yml.sample
- group_vars/restapis.yml.sample
- group_vars/rgws.yml.sample
- roles/ceph-mds/defaults/main.yml
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-restapi/defaults/main.yml
- roles/ceph-rgw/defaults/main.yml
Less configuration for the user, the container inherit from the global
variables. No more container specific variables.
> docker: simplify variable declaration

- ceph-ansible.spec.in
As of 54d7a81241eac26d87e2bee513df5efd8866a586, we're doing more than stripping CoreOS files in the RPM now. Move the comments around to better match the code that does what the comments describe.
The purpose of this change is to make it easier to read this part of the RPM spec file.
> rpm: better comments for file removals

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
Since #1724 has been merged, this comment is deprecated
> ceph-osd: remove deprecated comment in sample file

- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-docker-common/tasks/selinux.yml
- roles/ceph-mds/tasks/docker/copy_configs.yml
- roles/ceph-mds/tasks/docker/main.yml
- roles/ceph-mgr/tasks/docker/copy_configs.yml
- roles/ceph-mgr/tasks/docker/main.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/fetch_configs.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-nfs/tasks/docker/copy_ganesha_configs.yml
- roles/ceph-nfs/tasks/docker/main.yml
- roles/ceph-osd/tasks/copy_configs.yml
- roles/ceph-osd/tasks/main.yml
- roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
- roles/ceph-rbd-mirror/tasks/docker/main.yml
- roles/ceph-restapi/tasks/docker/copy_configs.yml
- roles/ceph-restapi/tasks/docker/main.yml
- roles/ceph-rgw/tasks/docker/copy_configs.yml
- roles/ceph-rgw/tasks/docker/copy_rgw_configs.yml
- roles/ceph-rgw/tasks/docker/main.yml
All keys are copied to all nodes.
This commit split that task in each roles so keys are copied to their
respective nodes.
> docker: split the task 'copy ceph configs&keys'

- Makefile
It's not currently possible to install EPEL 7's fedpkg alongside the centos-packager package in CentOS 7 Extras (for `/usr/bin/cbs`), because they each depend on slightly different Koji package versions.
This means that we cannot run `make srpm` on a system where centos-packager is installed, because that depends on fedpkg.
Remove the dependency on fedpkg for the "srpm" target, and run `rpmbuild -bs` directly.
The purpose of this change is to make it easier to automatically build ceph-ansible SRPMs in Jenkins/cbs.centos.org.
> Makefile: remove fedpkg dependency for "srpm"

- roles/ceph-osd/tasks/start_osds.yml
The script can fail to get the osd id because the osds are activated by
udev and it can take a while for them to activate. This commit fixes
that by trying to get all the osds per node in a loop.
This commit also makes the osd services enabled so that they are
available after reboot.
> ceph-osd: Fix osd start sequence

- infrastructure-playbooks/purge-cluster.yml
Handles the case when a mon is collocated with an OSD.
Closes: https://github.com/ceph/ceph-ansible/issues/1877
> purge: only purge specific directories for mon

- tests/functional/lvm_setup.yml
The ``dev-ansible2.3-purge_lvm_osds`` task has been failing because the ``purge-cluster.yml`` playbook does not destroy partitions used for lvm osd journals which causes the second run of ``lvm_setup.yml`` to fail during the purge scenario.
Proper support for purging partitions used for lvm osds will be added when ``ceph-volume lvm zap`` is available.
> tests: fix lvm_setup.yml for purge_cluster.yml

- roles/ceph-config/templates/ceph.conf.j2
Since the only support civetweb these variables are obsolete.
> rgw: remove old variables

- roles/ceph-mon/tasks/docker/main.yml
This fixes RHCS builds. We know which Ceph version we are running on.
> mon: create the mgr key for release >= luminous

- ceph-ansible.spec.in
When building the RPM on CentOS, we will ship the `all.yml.sample` file and delete `rhcs.yml.sample`.
When building the RPM on RHEL, we will ship the `rhcs.yml.sample` file and delete `all.yml.sample`.
> rpm: ship different yml samples on RHEL vs CentOS

- ceph-ansible.spec.in
The ceph-iscsi-ansible project has moved into ceph-ansible now. Make the ceph-ansible package obsolete the ceph-iscsi-ansible package. With this change, Yum updates will seamlessly uninstall the ceph-iscsi-ansible package.
> rpm: Obsoletes ceph-iscsi-ansible

- ceph-ansible.spec.in
We require a newer verison of Ansible now.
> rpm: require Ansible 2.3.1.0

- roles/ceph-defaults/templates/restart_mon_daemon.sh.j2
- roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
- roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
Use default delay since the mon (in particular) can take more time to
restart.
Solves error with:
STDERR:
Error response from daemon: No such container: ceph-mon-mon0
> defaults: restart docker daemon higher delay

- ceph-ansible.spec.in
When building the RPM on RHEL, we will ship the conents of the `rhcs.yml.sample` file into `all.yml.sample`.
The purpose of this change is to expose "all.yml.sample" to both upstream and downstream users, so they use the same file name (but with different contents.)
> rpm: ship rhcs.yaml.sample as all.yml.sample on RHEL

- roles/ceph-docker-common/tasks/checks.yml
The variable "statleftover" was removed by commit
a60c74f61eb4b7523ef6d4065624312bfd0aa03a
and never added back to the new playbook,
yet it is still being referenced.
Adding it back
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1492224
> docker-common: re-introduce state for leftover files

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-client/tasks/pre_requisite.yml
- roles/ceph-osd/tasks/check_mandatory_vars.yml
- site-docker.yml.sample
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/centos/7/docker/hosts
On a container env, machines don't have any ceph binaries so we need to
use a container to run the commands.
> client: ability to create keys and pool with no ceph binaries

- group_vars/nfss.yml.sample
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/templates/ganesha.conf.j2
In analogy to ceph_nfs_rgw_user, we should be able to define a user
with which the nfs-ganesha Ceph FSAL connects to the cluster.
Introduce a ceph_nfs_ceph_user, setting its default to "admin" (which
preserves the prior behavior of always connecting as client.admin).
Fixes #1910.
> Introduce ceph_nfs_ceph_user

- roles/ceph-common/tasks/checks/check_system.yml
Looks like Ansible is now using "RedHat" instead of "Red Hat Enterprise
Linux"
> common: fix rhel check

- roles/ceph-common/tasks/installs/debian_ceph_repository.yml
- roles/ceph-common/tasks/installs/install_on_debian.yml
- roles/ceph-common/templates/ganesha.conf.j2
- roles/ceph-nfs/defaults/main.yml
- Install `nfs-ganesha` packages on Ubuntu from the correct PPA (one with a build that actually contains a Ceph FSAL).
- Correct the `ganesha.conf` template to generate correct nfs-ganesha parameters.
- Enable nfs-ganesha to connect to Ceph using a CephX identity other than `client.admin` (but retain the default to connect as `client.admin`, to preserve compatibility).
> stable-2.2: Enable working nfs-ganesha deployment on Ubuntu

- roles/ceph-nfs/templates/ganesha.conf.j2
- Change capitalization of config options to be
in line with what config.txt in the nfs-ganesha
tree says
changes are referenced from here: https://github.com/ceph/ceph-ansible/pull/1912
> nfs: ganesha.conf template fixes

- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/tasks/docker/start_docker_nfs.yml
- roles/ceph-nfs/tasks/pre_requisite.yml
When ceph-nfs service is managed by pacemaker, it's useful to
not enable and start ceph-nfs service through systemd but let
pacemaker to start the service in a next step.
> Make ceph-nfs service enablement/start optional

- roles/ceph-mds/tasks/docker/copy_configs.yml
- roles/ceph-mgr/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
- roles/ceph-nfs/tasks/docker/copy_configs.yml
- roles/ceph-osd/tasks/copy_configs.yml
- roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
- roles/ceph-restapi/tasks/docker/copy_configs.yml
- roles/ceph-rgw/tasks/docker/copy_configs.yml
We generate the ceph.conf on all the nodes through the
ceph-docker-common so there is no need to push it to the Ansible file.
Also this is breaking the ceph.conf template generation since we only
generate sections based on the host the ansible task is running on.
For example, what's typically happening, we bootstrap the monitor, we
get a ceph.conf generated for a mon only, we go on an osd, we generate
the ceph.conf with osd section (done by ceph-docker-common) but this
gets overwritten by the copy_config task of the ceph-osd role.
> docker: we don't need to copy the ceph.conf on all the nodes

- group_vars/all.yml.sample
- group_vars/nfss.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
This section is not needed when running a bluestore osd.
> config: no not generate osd section if bluestore

- group_vars/nfss.yml.sample
Add the ceph_nfs_ceph_user variable to nfss.yml.sample too (not just
all.yml.sample).
This was properly included in ada2f147f5c6537cf51171c995009b0b3288c027
in master, but was missing from
72e32ae0bf1f060aaabd88ddb9c8dd000c0c5d97 in stable-2.2.
> stable-2.2: add ceph_nfs_ceph_user to nfss.yml.sample

- roles/ceph-nfs/tasks/create_rgw_nfs_user.yml
This is what happens when you don't run all the jobs from the CI...
> [skip ci] nfs: fix undefined variable

- roles/ceph-nfs/tasks/create_rgw_nfs_user.yml
the default is not an array, default is empty.
> [skip ci] nfs: fix docker_exec_cmd_nfs default value

- roles/ceph-config/templates/ceph.conf.j2
Conf file generation failing on rgw nodes when nodes have different
interface names.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1493552
> config: fix rgw interface when using different interfaces

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
need to use `hostvars[host]['XXX']` to retrieve the monitor
interface and/or radosgw interface.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1493920
> config: fix path to set `interface` in ceph.conf

- infrastructure-playbooks/purge-docker-cluster.yml
- infrastructure-playbooks/rolling_update.yml
The old name is used to restart the service in `rolling_update.yml`, it breaks the
`test_rgw_service_is_running()` test.
> update: update rgw systemd unit name

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
It's sad but we can not rely on the prepare container anymore since the
log are flushed after reboot. So inpecting the container does not return
anything.
Now, instead we use a ephemeral container to look up for the
journal/block.db/block.wal (depending if filestore or bluestore) and
build the activate command accordingly.
> [skip ci] osd: fix container reboot

- roles/ceph-defaults/handlers/main.yml
- roles/ceph-defaults/tasks/check_socket.yml
If we don't bootstrap the mgr after the mon and the osds handler are
called, we will never be able to reach a clean state since the pgs
stats are handled by the mgr. This also happens when doing daemon
collocation.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1493920
> handler: enhance socket detection

- roles/ceph-common/tasks/checks/check_mandatory_vars.yml
It's failing if a *valid* choice is specified.
> ceph-common: Fix logic for ceph_repository_type

- infrastructure-playbooks/purge-cluster.yml
Most osd scenarios do not use lvm_volumes, so default it in
purge-cluster.yml if it's not defined.
> purge-cluster: default lvm_volumes if not defined

- roles/ceph-docker-common/tasks/main.yml
there is no need to backslash the quotes here.
> docker-common: fix wrong syntax

- roles/ceph-mon/tasks/ceph_keys.yml
Specify the timeout flag to ceph-create-keys, which causes it to time out
if a monitor quorum isn't achieved. This overrides the default timeout
of 10 minutes, causing ceph-ansible to fail faster in the event of cluster
network issues.
Signed-off-by: Douglas Fuller <dfuller@redhat.com>
> mon/ceph_keys: Add timeout flag to ceph-create-keys

- site-docker.yml.sample
- site.yml.sample
we don't know ceph_stable_release before executing the role so at least
we need to run ceph-defaults and ceph-docker-common or
ceph-common.
> site: fix condition

- site-docker.yml.sample
- site.yml.sample
Fix typo, ceph_release is used, not ceph_stable_release
> [skip ci]  site: s/ceph_stable_release/ceph_release

- roles/ceph-mds/tasks/docker/copy_configs.yml
- roles/ceph-mgr/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
- roles/ceph-nfs/tasks/docker/copy_configs.yml
- roles/ceph-osd/tasks/copy_configs.yml
- roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
- roles/ceph-restapi/tasks/docker/copy_configs.yml
- roles/ceph-rgw/tasks/docker/copy_configs.yml
This fixes the error :
```
The conditional check 'sestatus.stdout != 'Disabled'' failed.
```
that occurs when running on non rhel based system since the
`sestatus` fact is registered only on rhel based distribution.
> [skip ci] mgr: add condition to run selinux tasks only on rhel os family

- roles/ceph-mds/tasks/docker/start_docker_mds.yml
- roles/ceph-mgr/tasks/docker/start_docker_mgr.yml
- roles/ceph-mon/tasks/docker/start_docker_monitor.yml
- roles/ceph-osd/tasks/docker/start_docker_osd.yml
- roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
Using systemd module allows us to do in one task what we did in three
tasks:
- enable unit file,
- issue a `daemon-reload`,
- start the service
> Use systemd module instead of service.

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
I forgot to add cluster name support so some partition were never
mounted correctly.
> osd: add cluster name support

- infrastructure-playbooks/purge-cluster.yml
After purging cluster,  block partitions also exist which will block the next cluster deployment. So remove them together with journal/db/wal partitions.
> purge-cluster: delete block partitions if using bluestore

- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-defaults/tasks/main.yml
The task which sets `ceph_current_fsid` in `facts.yml` in case of containerized
deployment, will definitely fail because `docker_exec_cmd` is not set
yet.
This commits simply makes `facts.yml` played after `check_socket.yml` so
`docker_exec_cmd` is set properly.
> defaults: change running order in main.yml

- site-docker.yml.sample
- site.yml.sample
So we can later evaluate the conditions.
Also fix the variable, we are comparing ceph_release not
ceph_stable_release
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1486062
> site: always play ceph-defaults and ceph-docker-common

- infrastructure-playbooks/rolling_update.yml
- roles/ceph-client/tasks/pre_requisite.yml
Also we now play ceph-config to have everything being generated for new
daemons bootstrap during upgrade.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1497959
> upgrade: a support for mgrs

- docs/source/index.rst
We require Ansible 2.3.1 or greater to run ceph-ansible's master branch.
> docs: master requires ansible 2.3.1

- roles/ceph-client/tasks/main.yml
- roles/ceph-client/tasks/pre_requisite.yml
- roles/ceph-iscsi-gw/tasks/configure_iscsi.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-mon/tasks/main.yml
- roles/ceph-mon/tasks/rbd_pool.yml
- roles/ceph-mon/tasks/rbd_pool_df.yml
- roles/ceph-mon/tasks/rbd_pool_pgs.yml
- roles/ceph-mon/tasks/rbd_pool_size.yml
- roles/ceph-mon/tasks/set_osd_pool_default_pg_num.yml
- tests/functional/centos/7/bluestore/group_vars/all
- tests/functional/centos/7/bs-crypt-ded-jrn/group_vars/all
- tests/functional/centos/7/bs-crypt-jrn-col/group_vars/all
- tests/functional/centos/7/bs-dock-crypt-jrn-col/group_vars/all
- tests/functional/centos/7/bs-jrn-col/group_vars/all
- tests/functional/centos/7/cluster/group_vars/all
- tests/functional/centos/7/crypt-ded-jrn/group_vars/all
- tests/functional/centos/7/crypt-jrn-col/group_vars/all
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/centos/7/jrn-col-auto-dm/group_vars/all
- tests/functional/centos/7/jrn-col-auto/group_vars/all
- tests/functional/centos/7/jrn-col/group_vars/all
- tests/functional/centos/7/lvm-osds/group_vars/all
- tests/functional/tests/mds/test_mds.py
- tests/functional/ubuntu/16.04/cluster/group_vars/all
- tox.ini
The rbd pool is the default pool that gets created during ceph cluster
initializaiton.  If we act on the rbd related operations too early, the
rbd pool does not exist yet.  Move the call to perform rbd operations
to a later stage after other pools have been created.
The rbd_pool.yml playbook has all the operations related to the rbd pool.
Replace the always_run (deprecated) directive with check_mode.
Most of the ceph related tasks only need to run once.  The run_once directive
executes the task on the first host.
The ceph sub-command to delete a pool is delete (not rm).
The changes submitted here were tested with this ceph version.
ceph version 0.94.9-9.el7cp (b83334e01379f267fb2f9ce729d74a0a8fa1e92c)
This upload includes these changes:
- Use the fail module (instead of assert).
- From …
> Only perform actions on the rbd pool after it has been created

- roles/ceph-mon/tasks/create_mds_filesystems.yml
Otherwise pools with names 'cephfs_data' and 'cephfs_metadata'
are created.
> Evaluate cephfs pool variables

- roles/ceph-nfs/templates/ceph-nfs.service.j2
It's useful to keep logs permanently, also this fixes bind mount
for /var/lib/nfs/ganesha directory.
> Fix bind mount for /var/lib/nfs/ganesha directory

- roles/ceph-common/tasks/installs/install_debian_packages.yml
- roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
- roles/ceph-common/tasks/installs/install_redhat_packages.yml
`ceph_release` isn't available at this step of the playbook because it
is set later based on the installed binaries.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1486062
> common: remove unusuable conditions

- Vagrantfile
- tests/functional/centos/7/bluestore/group_vars/all
- tests/functional/centos/7/bluestore/hosts
- tests/functional/centos/7/bluestore/vagrant_variables.yml
- tests/functional/centos/7/bs-crypt-ded-jrn/vagrant_variables.yml
- tests/functional/centos/7/bs-crypt-jrn-col/vagrant_variables.yml
- tests/functional/centos/7/bs-dock-crypt-jrn-col/vagrant_variables.yml
- tests/functional/centos/7/bs-dock-ded-jrn/vagrant_variables.yml
- tests/functional/centos/7/bs-jrn-col/vagrant_variables.yml
- tests/functional/centos/7/cluster/vagrant_variables.yml
- tests/functional/centos/7/crypt-ded-jrn/group_vars/all
- tests/functional/centos/7/crypt-ded-jrn/vagrant_variables.yml
- tests/functional/centos/7/crypt-jrn-col/group_vars/all
- tests/functional/centos/7/crypt-jrn-col/vagrant_variables.yml
- tests/functional/centos/7/docker-crypt-jrn-col/group_vars/all
- tests/functional/centos/7/docker-crypt-jrn-col/vagrant_variables.yml
- tests/functional/centos/7/docker-ded-jrn/group_vars/all
- tests/functional/centos/7/docker-ded-jrn/vagrant_variables.yml
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/centos/7/docker/vagrant_variables.yml
- tests/functional/centos/7/jrn-col-auto-dm/group_vars/all
- tests/functional/centos/7/jrn-col-auto-dm/vagrant_variables.yml
- tests/functional/centos/7/jrn-col-auto/group_vars/all
- tests/functional/centos/7/jrn-col-auto/vagrant_variables.yml
- tests/functional/centos/7/jrn-col/group_vars/all
- tests/functional/centos/7/jrn-col/vagrant_variables.yml
- tests/functional/centos/7/lvm-osds/group_vars/all
- tests/functional/centos/7/lvm-osds/vagrant_variables.yml
- tests/functional/ubuntu/16.04/cluster/vagrant_variables.yml
If two environments are using the same subnet, we will get trouble
because of ips addresses conflicts.
This commit ensures each scenario has a uniq subnet for both public and cluster
network so we can setup several test environment at a time on a same hypervisor.
> tests: make all subnet uniq per scenario

- roles/ceph-osd/tasks/check_devices.yml
This is needed later, if we do unique, only the first OSD will get a
journal.
> [skip ci] osd: do not do unique on dedicated_devices

- group_vars/nfss.yml.sample
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-nfs/templates/ganesha.conf.j2
Exports dir is used when dynamic exports creation is enabled.
> Include exports dir in ceph-nfs config file

- group_vars/nfss.yml.sample
- roles/ceph-defaults/templates/restart_nfs_daemon.sh.j2
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-nfs/templates/ceph-nfs.service.j2
It's useful to have constant service instance id when ceph-nfs
is managed by pacemaker.
> Allow to override systemd service instance id

- infrastructure-playbooks/purge-cluster.yml
Using a condition when osd_scenario == 'non-collocated' was wrong since
these partitions can be collocated on a single device also. Removing the
check makes the purge of these partitions.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1499871
> [skip ci] purge: fix journal purge

- group_vars/nfss.yml.sample
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/tasks/pre_requisite_container.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-nfs/templates/ganesha.conf.j2
* DBus on host should include ganesha service file
* to allow ganesha container to respond on DBus it needs to run
in --privileged mode (ganesha folks contacted to look at this)
* ceph_nfs_include_exports_dir variable replaced with more general
ceph_nfs_dynamic_exports
> Ceph-nfs dynamic exports fixes

- roles/ceph-common/tasks/installs/install_redhat_packages.yml
This patch fixes a typo where `package:` was used twice in the same
task.
> Remove duplicate 'package' key

- roles/ceph-common/tasks/installs/install_redhat_packages.yml
This patch fixes a typo where "package:" was used twice in the same
task.
(cherry picked from commit 10e1d464e5664e4f440378289b96c70f1aa1e1b3)
> [skip ci] bpk-2021 - Remove duplicate 'package' key

- roles/ceph-common/tasks/installs/install_redhat_packages.yml
Modern versions of Ansible can handle a list of packages passed
directly to the package modules. This patch optimizes the package
install process by passing the list of packages directly to the
module.
> Pass list of packages instead of with_items

- docs/source/dev/index.rst
- docs/source/index.rst
Cherry-pick some of @andrewschoen's documentation fixes to `stable-2.2`. Add a couple more patches on top that avoid talking about `osd_scenario` (irrelevant in `stable-2.2`) and mention the 6 different OSD scenario booleans instead.
> Backport documentation to stable-2.2

- tests/conftest.py
- tests/functional/centos/7/docker-collocation/ceph-override.json
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
- tests/functional/tests/rgw/test_rgw.py
- the rbd-mirror unit systemd name is not the same when running jewel vs
luminous.
- servicemap is not available on jewel.
> tests: rbd/rgw adapt testinfra for jewel

- group_vars/mons.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/tasks/check_mandatory_vars.yml
- roles/ceph-mon/tasks/create_mds_filesystems.yml
- tests/functional/centos/7/cluster/group_vars/mons
- tests/functional/centos/7/docker/group_vars/mons
- tests/functional/ubuntu/16.04/cluster/group_vars/mons
We now have a variable called ceph_pools that is mandatory when
deploying a MDS.
It's a dictionnary that contains a pool name and a PG count. PG count is
mandatory and must be set, the playbook will fail otherwise.
Closes: https://github.com/ceph/ceph-ansible/issues/2017
> mds: precisely define cephfs pool

- infrastructure-playbooks/purge-docker-cluster.yml
- roles/ceph-common/tasks/checks/check_ntp_atomic.yml
- roles/ceph-common/tasks/checks/check_ntp_redhat.yml
- roles/ceph-common/tasks/installs/configure_redhat_repository_installation.yml
- roles/ceph-docker-common/tasks/checks/check_ntp_atomic.yml
- roles/ceph-docker-common/tasks/checks/check_ntp_redhat.yml
Ansible throws warnings when using yum/dnf/rpm with the command
module:
[WARNING]: Consider using yum module rather than running yum
This patch adds the `warn: no` argument to suppress the warnings
in the Ansible output.
> Suppress yum/dnf/rpm command warnings

- infrastructure-playbooks/rolling_update.yml
- roles/ceph-fetch-keys/tasks/main.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/create_mds_filesystems.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-osd/tasks/ceph_disk_cli_options_facts.yml
- roles/ceph-osd/tasks/check_mandatory_vars.yml
- roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
- roles/ceph-rbd-mirror/tasks/pre_requisite.yml
- roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
- roles/ceph-rgw/tasks/main.yml
- site-docker.yml.sample
- site.yml.sample
This patch changes the `when:` keys so that they have no jinja2
delimiters. This avoids Ansible warnings which could turn into
errors in a future Ansible release.
> Remove jinja2 delimiters from `when` keys

- tox.ini
This patch adds the `profile_tasks` callback plugin to the whitelist
so that we can identify the tasks which are taking the longest amount
of time to run.
> Enable profile_tasks callback plugin

- roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
on jewel `ceph-rbd-mirror.target` isn't enabled, therefore, if the node
is rebooted, the service doesn't get started.
from ceph-rbd-mirror unit file:
```
[Install]
WantedBy=ceph-rbd-mirror.target
```
> rbd-mirror: enable ceph-rbd-mirror.target

- tests/functional/reboot.yml
- tox.ini
vagrant is serialized and takes a lot of time compare to simple reboot.
See the benchmarks below for 3 VMs:
```
[leseb@rick docker]$ time ANSIBLE_SSH_ARGS="-F
/home/leseb/reproduce-ci/tmp.zgGC7d5mIC/build/workspace/ceph-ansible/tests/functional/centos/7/docker/vagrant_ssh_config"  ansible-playbook -i /home/leseb/reproduce-ci/tmp.zgGC7d5mIC/build/workspace/ceph-ansible/tests/functional/centos/7/docker/hosts reboot.yml
PLAY [mons]
****************************************************************************************************************************************************************************************************
TASK [Gathering Facts]
*************************************************************************************************************************************************** …
```
> ci: reboot with ansible instead of vagrant reload

- roles/ceph-mon/tasks/check_mandatory_vars.yml
- tests/functional/centos/7/docker-collocation/group_vars/mons
1. add the variables to docker_collocation
2. trigger the check when a MDS is part of the inventory file, not when
we run on an MDS...
> mds: fix fs pool creation

- roles/ceph-docker-common/tasks/main.yml
- site-docker.yml.sample
- tests/functional/centos/7/docker/hosts
- tests/functional/centos/7/docker/vagrant_variables.yml
The container deployment is serialized, adding this task as a best
effort. If docker is already present we pull the image otherwise we wait
for the role to play.
> site-docker.yml try to fetch images in //

- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
This will solve the following issue when starting docker containers on ubuntu:
invalid argument "1\u00a0" for --cpus=1 : failed to parse 1  as a rational number
Closes-bug: #2056
> In docker start scripts replace \u00a0 with \u0020

- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- Add upgrade support for rbd mirror and nfs daemons.
- Only works with systemd (remove sysvinit and upstart occurence)
- A bit of cleanup
> upgrade: support for rbd mirror and nfs

- plugins/actions/_v1_config_template.py
- plugins/actions/_v2_config_template.py
Handlers are always triggered in ceph-ansible because ceph.conf file is
generated with a random order for the different keys/values pairs
in sections.
In python, a dict is not sorted. It means in our case each time we try
to generate the ceph.conf file it will be rendered with a random order
since the mechanism behind consist of rendering a file from a python dict
with keys/values. Therefore, as a quick workaround, forcing this dict to be
sorted before rendering the configuration file will ensure that it will be
rendered always the same way.
I don't know whether it should be fixed upstream, fixing this at ceph-ansible level means forking this plugin. However, it's not a huge modification and should be pretty easy to maintain or revert if ever we could find a better fix.
@leseb …
> ceph-defaults: fix handlers that are always triggered

- ceph-ansible.spec.in
Downstream version of ceph-ansible could still trigger install from
upstream repo and import keys.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1503019
> [skip ci] rpm: remove ability to install ceph community version

- tests/requirements.txt
This allows us to deal with API change of "host" fixture
see https://github.com/philpep/testinfra/blob/master/CHANGELOG.rst#160
Now we can run tox against stable-2.2 release of ceph-ansible
Signed-off-by: Gregory Meno <gmeno@redhat.com>
> pin test-infra requirement at 1.5.5

- roles/ceph-defaults/handlers/main.yml
When doing collocation the condition "inventory_hostname in play_hosts"
is breaking the restart workflow.
> defaults: fix handlers for collocation

- group_vars/mgrs.yml.sample
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/tasks/main.yml
The ceph mgr daemon has modules that can be enabled, for example the dashboard: http://docs.ceph.com/docs/master/mgr/dashboard/
This PR adds the capability to enable the modules.
> Add ability to enable ceph mgr modules.

- roles/ceph-config/tasks/main.yml
- roles/ceph-defaults/templates/restart_rbd_mirror_daemon.sh.j2
In Jewel, we don't use bootstrap-rbd keyring for rbd-mirror nodes, it
results with a socket path/name different according to which ceph
release you are deploying.
> [skip ci] rbd: fix restart script for jewel

- roles/ceph-mgr/tasks/main.yml
3a58757 introduced an issue for Jewel deployments, since this role is
skipped, `enabled_ceph_mgr_modules.stdout` doesn't exist, therefore, it
ends up with an attribute error.
Uses `.get()` to retrieve `stdout` with a default value so it won't fail
if this attribute doesn't exist (jewel).
> [skip ci] mgr: fix broken task on jewel

- group_vars/all.yml.sample
- group_vars/osds.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/rolling_update.yml
- roles/ceph-common/tasks/checks/check_mandatory_vars.yml
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
- roles/ceph-docker-common/tasks/check_mandatory_vars.yml
- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-mgr/tasks/main.yml
- roles/ceph-mon/tasks/check_mandatory_vars.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/defaults/main.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
stable-3.0 brought numerous changes in ceph-ansible variables, this PR
aims to maintain backward compatibility for someone running stable-2.2
upgrading to stable-3.0 but keeps its groups_vars untouched.
We will then determine the right options to make sure the upgrade works
but we are expecting that new variables should be used.
We will drop this in a near future, maybe 3.1 or 3.2.
Closes: https://github.com/ceph/ceph-ansible/issues/1834
> [skip ci] all: backward compatibility between stable-2.2 and 3.0

- roles/ceph-rgw/tasks/start_radosgw.yml
systemd script for radosgw is radosgw@ not rgw@, the directory needs to
match the path.
> Typo fix for radosgw@ systemd file

- infrastructure-playbooks/purge-docker-cluster.yml
- tox.ini
- split purge_cluster because we need to test filestore and bluestore
scenarios.
- clean some leftover.
> tests: split purge_cluster, followup on a53aa9e

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/configure_memory_allocator.yml
- roles/ceph-common/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Use "ceph_tcmalloc_max_total_thread_cache" to set the
TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES value inside /etc/default/ceph for
Debian installs, or /etc/sysconfig/ceph for Red Hat/CentOS installs.
By default this is not set, so the default package value will be used,
if specified this value will be changed to match the variable, and ceph
services will be restarted.
> Option to set TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-mon/tasks/openstack_config.yml
Only chmod or setfacl the requested keyring(s) in the
opentack_keys data structure when the mode or acls keys
of that data structure exist.
User may specify four permission combinations for the
keyring file(s): 1. only set ACL, 2. only set mode,
3. set neither mode nor ACL, 4. set mode and then ACL.
Fixes: #2092
> Make acls and mode parameters of opentack_keys optional

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-docker-common/tasks/fetch_image.yml
This change sets a default timeout of 300s for the image pull. If the
image pull times out (300s), we will retry 3 times by default.
fixes #1954
> Docker image pull retry

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
ceph_repository_type was declared multiple times. This commit fixes
this.
> default: remove dup variable

- tests/functional/lvm_setup.yml
ansible==2.4 requires that label be set to gpt, or it will be defaulted
to msdos.
> test: when creating the /dev/sdc2 partition specify label as gpt

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/tasks/docker/start_docker_osd.yml
- roles/ceph-osd/tasks/scenarios/collocated.yml
- roles/ceph-osd/tasks/scenarios/non-collocated.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Setting monitor_interface in group_vars/all.yml makes the
hostvars[host]['monitor_interface'] non-existing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1507922
> config: fix monitor_interface when not passed in the inventory file | osd:  fix old jewel container activation

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
> osd: fix a typo in roles/ceph-osd/defaults/main.yml

- roles/ceph-osd/tasks/main.yml
- roles/ceph-osd/tasks/scenarios/collocated.yml
The current code will also return lvm devices such as /dev/dm-2, this
kind of device type is not supported by ceph-disk at the moment. Now we
just ignore them.
> osd: do not use dm when osd_auto_discovery

- tests/functional/centos/7/docker-collocation/ceph-override.json
- tox.ini
this line has been removed by mistake in a53aa9e.
(cherry picked from commit 93f0856770ca1cee7628f906c06f94ee77c8be7e)
> tests: re-add missing param in tox

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
The path to the fact is not correct.
In any case, we will retrieve the IP address in hostvars, the variable
is the way we get the interface name according where it has been set
(eg.: inventory host file vs. group_vars/)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1510906
> config: fix config generation

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
The path to the fact is not correct.
In any case, we will retrieve the IP address in hostvars, the variable
is the way we get the interface name according where it has been set
(eg.: inventory host file vs. group_vars/)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1510906
(cherry picked from commit 80d32decd3e5c58c732eb06017be886b0f5d75e4)
> [backport][stable-3.0] config: fix config generation

- roles/ceph-osd/tasks/docker/start_docker_osd.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
there is no need to have a condition on this task, this test should be
always run since the result will be interpreted later.
> osd: always run disk_list test

- roles/ceph-osd/tasks/docker/start_docker_osd.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
there is no need to have a condition on this task, this test should be
always run since the result will be interpreted later.
(cherry picked from commit 591d77220e4e8fef12faf4312ec977c3e175ed09)
> [skip ci] osd: always run disk_list test

- roles/ceph-osd/tasks/main.yml
This will prevent ceph-ansible from using a loop device while it
shouldn't in auto_discovery mode.
> osd: avoid using non desired loop device in autodiscovery

- infrastructure-playbooks/purge-docker-cluster.yml
purge-docker-cluster must remove all osd_disk_prepare logs in
`{{ ceph_osd_docker_run_script_path }}`, otherwise if you purge your
cluster and try to redeploy it, osds will fail to start since because it
will try to retrieve find a partition uuid which doesn't exist.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1510470
> purge-docker-cluster: ensure old logs are removed

- ceph-ansible.spec.in
2.4.0.0 has some bugs, and we're going to ship with v2.4.1.0.
> rpm: require ansible 2.4.1.0

- roles/ceph-defaults/handlers/main.yml
- One can not run scripts directly in place, that mounted with `noexec`
option. But one can run scripts as arguments for `bash/sh`.
Signed-off-by: Arano-kai <captcha.is.evil@gmail.com>
> FIX: run restart scripts in `noexec` /tmp

- roles/ceph-defaults/tasks/facts.yml
these tasks are not needed when using `osd_scenario: lvm`
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1509230
> osd: skip some set_fact when osd_scenario=lvm

- infrastructure-playbooks/take-over-existing-cluster.yml
The ansible inventory could have more than just ceph-ansible hosts, so
we shouldnt use "hosts: all", also only grab one file when getting
the ceph cluster name instead of failing when there is more than one
file in /etc/ceph. Also fix location of the ceph.conf template
> infra: fix take-over-existing-cluster.yml playbook

- docs/source/index.rst
In my env, only ansible version 2.3.1 and 2.3.2 can run the stable-3.0 branch ,but ansible 2.2
> Fix: the ansible version for the stable-3.0 branch

- roles/ceph-osd/tasks/start_osds.yml
crush location only set for containerized deployment
Signed-off-by: yaoning <yaoning@unitedstack.com>
> osd: fix crush location for non-containerized deployment

- roles/ceph-defaults/tasks/facts.yml
these tasks are not needed when using `osd_scenario: lvm`
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1509230
(cherry picked from commit 238754a8446f5ae3d2eefea9420e6d61f4426481)
> [skip ci] osd: skip some set_fact when osd_scenario=lvm

- roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
Like 80d32dec, the path to the fact is not correct.
In any case, we will retrieve the IP address in hostvars, the variable
is the way we get the interface name according where it has been set
(eg.: inventory host file vs. group_vars/)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1510906
> defaults: fix rgw restart script in handlers

- tox.ini
`CEPH_STABLE_RELEASE` needs to bet set in ceph-build according
to ceph/ceph-ansible#2165
> tests: set CEPH_STABLE_RELEASE in ceph-build

- roles/ceph-osd/tasks/build_devices.yml
- roles/ceph-osd/tasks/main.yml
- tests/functional/centos/7/bs-osds-container/group_vars/all.yml
- tests/functional/centos/7/docker-collocation/group_vars/all
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/centos/7/fs-osds-container/group_vars/all.yml
according to ceph/ceph-container#840, this variable is no longer needed.
backport of #2170 
(cherry picked from commit aa0b1ed11872ea6f69f69b4a376b13ae5d6e12e0)
> [backport][stable-3.0] tests: remove OSD_FORCE_ZAP variable from tests

- roles/ceph-mon/tasks/openstack_config.yml
If ceph-ansible deploys a Ceph cluster with "openstack_config: true"
and sets the openstack_keys map to have certain ACLs or permissions,
the requested ACLs or permissions are only set on one of the monitor
nodes [2] when they should be set on all of them.
This patch solves [3] the above issue by having the chmod and setfacl
tasks iterate the list of mon nodes (including the mon node that the
task was delegated to) to apply the chmod of setfacl to the keys in
openstack_keys.
[1]
```
openstack_keys:
- { name: client.openstack, key: "$(ceph-authtool --gen-print-key)", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool=images, allow rwx pool=vms, allow rwx pool=volumes, allow rwx pool=backups", mode: "0600", acls: ["u:nova:r--", "u:cinder:r--", …
```
> Set permissions and ACLs of OpenStack keys on all ceph-mons

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
the osd disk activate can't find device in /dev/mapper/* because of a
refactor that is missing in stable-2.2 branch
> [skip ci] osd: fix dmcrypt on stable-2.2

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
backport of #2181 
(cherry picked from commit 097249371f0baae2b97367c219ac5973c57d60d3)
> fix: remove the duplicated code

- roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
when `ceph-rbd-mirror.target` is not enabled, the service won't start
after a reboot because there is a dependency between these two units.
> rbd: enable ceph-rbd-mirror.target on releases prior to luminous

- infrastructure-playbooks/purge-docker-cluster.yml
`with_fileglob` loops over files on the machine that runs the playbook.
> purge-docker: remove osd disk prepare logs

- roles/ceph-mon/tasks/openstack_config.yml
A recent change [1] required that the openstack_keys
param always containe an acls list. However, it's
possible it might not contain that list. Thus, this
param sets a default for that list to be empty if it
is not in the structure as defined by the user.
[1] d65cbaa53952269ec9a2e76fca8203ce7ad22c2b
> Make openstack_keys param support no acls list

- roles/ceph-osd/tasks/check_gpt.yml
- roles/ceph-osd/tasks/main.yml
ceph-disk prepare will fail on jewel if a GPT label is not present on
device.
> osd: ensure a gpt label is set on device

- infrastructure-playbooks/purge-cluster.yml
`with_fileglob` loops over files on the machine where ansible-playbook
is being run. Here, we want to iterate over files on the remote machine
> purge-cluster: remove usage of `with_fileglob`

- roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
Since some daemons now install their own packages the task checking the
ceph version fails on Debian systems. So the 'ceph-common' package must
be installed on all the machines.
> common: install ceph-common on all the machines

- group_vars/mons.yml.sample
- roles/ceph-mon/defaults/main.yml
The Openstack section in the group_vars sample for mons defines some variables for pool settings which are used to generate user keys later on. However, one line didn't use those variables but hardcoded pool names instead.
> Group_vars mon sample - replaced hardcoded pool names for Openstack

- roles/ceph-osd/tasks/pre_requisite.yml
This task was originally needed to fix a docker installation issue
(see: #1030). This has been fixed, therefore it can be removed.
Fixes: #2199
> osd: remove leftover and fix a typo

- roles/ceph-defaults/handlers/main.yml
In case where docker CLI is available but docker is not running, we
don't want to trigger the restart of the daemons.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1510555
> handlers: restart daemons only if docker is running

- roles/ceph-osd/tasks/activate_osds.yml
This is particularly useful in CI environments where you dont have
the option of adding extra devices or volumes to the host. It is also
a simple change to support loopback devices.
> Add support for using loopback devices as OSDs

- infrastructure-playbooks/purge-cluster.yml
this task hangs because `{{ inventory_hostname }}` doesn't resolv to an
actual ip address.
Using `hostvars[inventory_hostname]['ansible_default_ipv4']['address']`
should fix this because it will reach the node with its actual IP
address.
> purge: fix bug on 'wait_for' task

- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-mgr/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
During a containerized deployment, set the permissions of ceph.client.admin.keyring and other keyrings to chmod 600 and chown it to ceph.
> Set tighter permissions on keyrings when containerized

- roles/ceph-defaults/tasks/facts.yml
The CI complains because of `ceph_uid` fact which doesn't exist since
the docker image tag used in the CI doesn't match with this condition.
> defaults: fix CI issue with ceph_uid fact

- roles/ceph-osd/tasks/activate_osds.yml
Bugfix fo #2206.
I was found that partition number is hardcoded to task, but for ata devices partition number is only number. For nvme device needed prefix 'p' before partition number.
Test:
```yaml
---
- hosts: localhost
gather_facts: false
vars:
devices:
- '/dev/sda'
- '/dev/sdb'
- '/dev/nvme0n1'
- '/dev/nvme0n2'
tasks:
- name: Test nvme for 2206
command: echo "{{ item | regex_replace('^(\/dev\/cciss\/c[0-9]{1}d[0-9]{1})$', '\1p') | regex_replace('^(\/dev\/loop[0-9]{1})$', '\1p') }}
{%- if 'nvme' in item %}{{ 'p1' }}{% else %}{{ '1' }}{% endif %}"
with_items:
- "{{ vars['devices'] | unique }}"
register: result
loop_control:
label: "{{ 'Device is: ' ~ item ~ ', device with partition is: ' ~ result.stdout_lines[0] }}"
```
Result:
```python
PLAY [localhost] …
```
> ceph-osd: respect nvme partitions when device is a disk.

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
If a deployer uses an interface name with a dash/hyphen in it, such
as `br-storage` for the monitor_interface group_var, the `ceph.conf.j2`
template fails to find the right facts. It looks for
`ansible_br-storage` but only `ansible_br_storage` exists.
This patch converts the interface name to underscores when the
template does the fact lookup.
> Convert interface names to underscores for facts

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Add the variables ceph_osd_docker_cpuset_cpus and
ceph_osd_docker_cpuset_mems, so that a user may specify
the CPUs and memory nodes of NUMA systems on which OSD
containers are run.
Provides an example for osds.yaml.sample to guide user
based on sample `lscpu` output since cpuset-mems refers
to the memory by NUMA node only while cpuset-cpus can
refer to individual vCPUs within a NUMA node.
> Add flags for OSD 'docker run --cpuset-{cpus,mems}'

- roles/ceph-defaults/tasks/check_socket_non_container.yml
As reported in https://github.com/ceph/ceph-ansible/issues/2254, the
check with fuser is not ideal. If fuser is not available the return code
is 127. Here we want to make sure that we looking for the correct return
code, so 1.
Closes: https://github.com/ceph/ceph-ansible/issues/2254
> default: look for the right return code on socket stat in-use

- roles/ceph-mgr/tasks/pre_requisite.yml
The ceph-mgr package name is identical to RedHat so add the SUSE family
to the existing task.
> roles: ceph-mgr: Install the ceph-mgr package on SUSE

- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
The name docker_version is very generic and is also used by other
roles. As a result, there may be name conflicts. To avoid this a
ceph_ prefix should be used for this fact. Since it is an internal
fact renaming is not a problem.
> Rename fact docker_version to ceph_docker_version

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
This resolves the following error:
E: There were unauthenticated packages and -y was used without
--allow-unauthenticated
> nfs: fix package install for debian/suss systems

- infrastructure-playbooks/rolling_update.yml
There is no need to ask for root on the local action. This will prompt
for a password the current user is not part of sudoers. That's
unnecessary anyways.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1516947
> rolling_update: do not require root to answer question

- site-docker.yml.sample
When deploying with Ansible at large scale, the delegate_facts method
consumes a lot of memory on the host that is running Ansible. This can
cause various issues like memory exhaustion on that machine.
You can now run Ansible with "-e delegate_facts_host=False" to disable
the fact sharing.
> site-docker: ability to disable fact sharing

- tests/functional/centos/7/bs-osds-container/group_vars/all.yml
- tests/functional/centos/7/docker-collocation/group_vars/all
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/centos/7/fs-osds-container/group_vars/all.yml
When deploying Jewel from master we still need to enable this code since
the container image has such check. This check still exists because
ceph-disk is not able to create a GPT label on a drive that does not
have one.
> fix jewel scenarios on container

- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
When upgrading from OSP11 to OSP12 container, ceph-ansible attempts to
disable the RGW service provided by the overcloud image. The task
attempts to stop/disable ceph-rgw@{{ ansible-hostname }} and
ceph-radosgw@{{ ansible-hostname }}.service. The actual service name is
ceph-radosgw@radosgw.$name
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1525209
> rgw: disable legacy rgw service unit

- roles/ceph-mon/tasks/ceph_keys.yml
ceph-create-keys is idempotent so it's not an issue to run it each time
we play ansible. This also fix issues where the 'creates' arg skips the
task and no keys get generated on newer version, e.g during an upgrade.
Closes: https://github.com/ceph/ceph-ansible/issues/2228
> mon: always run ceph-create-keys

- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- tox.ini
This fixes a few things related to our nightly tests with ``stable-3.0`` that deploy jewel clusters.
- when updating a jewel cluster ignore failures related to stopping ``nfs-ganesha`` 
- when switching a jewel cluster to containers ignore ``nfs`` and ``mgr``  service failures
- explicitly set ``UPDATE_CEPH_DOCKER_IMAGE_TAG`` for jewel tests so they upgrade to luminous and not latest.
These are really only an issue because we've setup our tests to work with both jewel and luminous.
> tests: fixes to allow for stable-3.0 nightly testing of jewel

- group_vars/mdss.yml.sample
- group_vars/osds.yml.sample
- roles/ceph-mds/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
A default value of 4GB for MDS is more appropriate and 3GB for OSD also.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1531607
> containers: bump memory limit

- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/main.yml
There is no reasons why we can't use crush rules when deploying
containers. So moving the inlcude in the main.yml so it can be called.
> mon: use crush rules for non-container too

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-docker-common/defaults/main.yml
Previously we were using ceph_conf_overrides however this doesn't play
nice for softwares like TripleO that uses ceph_conf_overrides inside its
own code. For now, and since this is the only occurence of this, we can
ensure no logs through the ceph conf template.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1532619
> container: change the way we force no logs inside the container

- roles/ceph-defaults/tasks/facts.yml
When containerized deployment, `docker_exec_cmd` is not set before the
task which try to retrieve the current fsid is played, it means it
considers there is no existing fsid and try to generate a new one.
Typical error:
```
ok: [mon0 -> mon0] => {
"changed": false,
"cmd": [
"ceph",
"--connect-timeout",
"3",
"--cluster",
"test",
"fsid"
],
"delta": "0:00:00.179909",
"end": "2018-01-09 10:36:58.759846",
"failed": false,
"failed_when_result": false,
"rc": 1,
"start": "2018-01-09 10:36:58.579937"
}
STDERR:
Error initializing cluster client: Error('error calling conf_read_file: errno EINVAL',)
```
> containers: fix bug when looking for existing cluster

- roles/ceph-osd/tasks/activate_osds.yml
On a non-collocated scenario, if a drive is faulty we can't really
remove it from the list of 'devices' without messing up or having to
re-arrange the order of the 'dedicated_devices'. We want to keep this
device list ordered. This will prevent the activation failing on a
device that we know is failing but we can't remove it yet to not mess up
the dedicated_devices mapping with devices.
> osd: skip devices marked as '/dev/dead'

- Makefile
With this change, `make srpm` will generate an RPM with "beta" in the Release value.
For example, a Git tag named `v3.2.0beta1` will create `ceph-ansible-3.2.0-0.beta1.1.el7.src.rpm`
> Makefile: handle "beta" Git tags

- tox.ini
This reverts commit 7a1d7d92ff4d6f38be9f11f4c26909b361b58f99.
(cherry picked from commit 73a20e9b50f9212f4e610ae021b23c8e010e9991)
backport of #2236
> Revert "tests: set CEPH_STABLE_RELEASE in ceph-build"

- docs/source/osds/scenarios.rst
- library/ceph_volume.py
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/scenarios/lvm.yml
- tests/functional/centos/7/bs-lvm-osds/group_vars/all
- tests/functional/centos/7/lvm-osds/group_vars/all
A ``--crush-device-class`` feature is currently in development for ``ceph-volume``, but we need this in place first so that we can test the PR that introduces ``--crush-device-class``.
> ceph-volume: adds a crush_device_class option for lvm_volumes

- roles/ceph-common/tasks/checks/check_ntp_atomic.yml
- roles/ceph-common/tasks/checks/check_ntp_debian.yml
- roles/ceph-common/tasks/checks/check_ntp_redhat.yml
- roles/ceph-docker-common/tasks/checks/check_ntp_atomic.yml
- roles/ceph-docker-common/tasks/checks/check_ntp_debian.yml
- roles/ceph-docker-common/tasks/checks/check_ntp_redhat.yml
- roles/ceph-docker-common/tasks/misc/ntp_atomic.yml
Checking if ntp is present is not needed anymore, these tasks are not
used anymore. So let's remove them
> ntp: followup cleanup

- infrastructure-playbooks/rolling_update.yml
When update from a minor Jewel version to another, the playbook will
fail on the task "fail if no mgr host is present in the inventory".
This now can be worked around by running Ansible with_items
-e jewel_minor_update=true
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1535382
> rolling update: add mgr exception for jewel minor updates

- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
Some systems that were deployed with old tools can leave units named
"ceph-radosgw@radosgw.gateway.service". As a consequence, they will
prevent the new unit to start.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1509584
> rgw: disable legacy unit

- tests/functional/centos/7/bs-lvm-osds/group_vars/all
- tests/functional/centos/7/lvm-osds/group_vars/all
The --crush-device-class flag for ceph-volume is not available in luminous so lets
remove this testing option for now until it's more widely available.
> tests: remove crush_device_class from lvm tests

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
This is to keep backward compatibility with stable-2.2 and satisfy the
check "verify dedicated devices have been provided" in
`check_mandatory_vars.yml`. This check is looking for
`dedicated_devices` so we need to default it's value to
`raw_journal_devices` when `raw_multi_journal` is set to `True`.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1536098
Backport of #2338 
(cherry picked from commit 9306a1789c95e5abb77260dde4d9cc3df900959f)
> osds: change default value for `dedicated_devices`

- ansible.cfg
We noticed that sometime, ceph-ansible can fail with error :
`Failed to connect to the host via ssh:`
It can occurs after the task `restart firewalld` has been played.
Setting `retries` to 5 should prevent from unexcepted ssh failure.
> ansible: set ssh retry option to 5

- docs/source/osds/scenarios.rst
- library/ceph_volume.py
- roles/ceph-osd/tasks/scenarios/lvm.yml
dmcrypt support in ``ceph-volume`` is coming shortly, this PR adds that to our ``ceph_volume`` module. I didn't enable this in any of of the CI scenarios yet though so all of our existing lvm tests should still pass. We need this feature in now though so that we can test with ``ceph-ansible`` as this feature is developed.
> ceph-volume: adds dmcrypt support

- roles/ceph-defaults/tasks/facts.yml
Sometime the playbook gets stuck because even with `--connect-timeout=`
option, the connexion to the existing ceph cluster never timeout.
As a workaround, using `timeout` command provided by coreutils will
actually timeout if we can't connect to the cluster.
> defaults: avoid getting stuck (ceph --connect-timeout)

- infrastructure-playbooks/rolling_update.yml
These tasks are needed only when upgrading to luminous.
They are not needed in Jewel minor upgrade and by the way, they fail because
`ceph versions` command doesn't exist.
> upgrade: skip luminous tasks for jewel minor update

- roles/ceph-config/tasks/main.yml
This allows us to use host-specific variables in ceph_conf_overrides variable (e.g. for rados gateway configuration variables, see profiles/rgw-keystone-v3).
Signed-off-by: Eduard Egorov <eduard.egorov@icl-services.com>
> config: add work-around for host-specific ceph_conf_overrides evaluation

- roles/ceph-config/tasks/main.yml
This allows us to use host-specific variables in ceph_conf_overrides variable. For example, this fixes usage of such variables (e.g. 'nss db path' having {{ ansible_hostname }} inside) in ceph_conf_overrides for rados gateway configuration (see profiles/rgw-keystone-v3) - issue #2157.
Signed-off-by: Eduard Egorov <eduard.egorov@icl-services.com>
(cherry picked from commit 93e9f3723bb4bcf8004bbcea3213d72d11588899)
> config: add host-specific ceph_conf_overrides evaluation and generation.

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
This should default to False. The default for Keystone is not to use PKI
keys, additionally, anybody using this setting had to have been manually
setting it before.
Fixes: #2111
> Add default for radosgw_keystone_ssl

- roles/ceph-osd/tasks/start_osds.yml
The 'get osd id' task goes through all the 10 times (and its respective
timeouts) to make sure that the number of OSDs in the osd directory
match the number of devices.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1537103
> Do not search osd ids if ceph-volume

- infrastructure-playbooks/purge-docker-cluster.yml
This is a typo caused by leftover.
It was previously written like this :
`shell: echo /dev/$(lsblk -no pkname "{{ item }}") }}")`
and has been rewritten to :
`shell: $(lsblk --nodeps -no pkname "{{ item }}") }}")`
because we are appending later the '/dev/' in the next task.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540137
> purge: fix resolve parent device task

- infrastructure-playbooks/purge-docker-cluster.yml
purge-docker: fix ceph-osd-zap name container
the `zap ceph osd disks` task should iter on `resolved_parent_device`
instead of `combined_devices_list` which contain only the base device
name (vs. full path name in `combined_devices_list`).
this fixes the issue where docker complain about container name because
of illegal characters such as `/` :
```
"/usr/bin/docker-current: Error response from daemon: Invalid container
name (ceph-osd-zap-magna074-/dev/sdb1), only [a-zA-Z0-9][a-zA-Z0-9_.-]
are allowed.","See '/usr/bin/docker-current run --help'."
""
```
having the the basename of the device path is enough for the container
name.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540137
> purge-docker: fix ceph-osd-zap name container

- roles/ceph-mon/tasks/main.yml
Was called too early, container was not yet started so the commands failed.
Moved the section after include docker/main.yml
Signed-off-by: Greg Charot <gcharot@redhat.com>
> mon: Fixed crush_rule_config for containerised deployment.

- roles/ceph-mds/tasks/containerized.yml
- roles/ceph-mon/tasks/docker/main.yml
While hostname -f will always return an hostname including its
domain part and -s without the domain part, the behavior when
no arguments are given can include or not include the domain part
depending on how the system is configured; the socket name might
not match the instance name then.
> Check for docker sockets named after both _hostname or _fqdn

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
This commit fixes a bug that occurs especially for dmcrypt scenarios.
There is an issue where the 'disk_list' container can't reach the ceph
cluster because it's not launched with `--net=host`.
If this container can't reach the cluster, it will hang on this step
(when trying to retrieve the dm-crypt key) :
```
+common_functions.sh:448: open_encrypted_part(): ceph --cluster abc12 --name \
client.osd-lockbox.9138767f-7445-49e0-baad-35e19adca8bb --keyring \
/var/lib/ceph/osd-lockbox/9138767f-7445-49e0-baad-35e19adca8bb/keyring \
config-key get dm-crypt/osd/9138767f-7445-49e0-baad-35e19adca8bb/luks
+common_functions.sh:452: open_encrypted_part(): base64 -d
+common_functions.sh:452: open_encrypted_part(): cryptsetup --key-file \
-luksOpen /dev/sdb1 9138767f-7445-49e0-baad-35e19adca8bb
```
It …
> osd: fix osd restart when dmcrypt

- roles/ceph-defaults/tasks/facts.yml
osd_scenario does not exist in the ceph-default role so if we try to
play ceph-default on an OSD node, the playbook will fail with undefined
variable.
> default: define 'osd_scenario' variable

- site-docker.yml.sample
- site.yml.sample
Now by running the playbook like this:
ansible-playbook site.yml --tags='ceph_update_config'
You can only generate a ceph configuration file on the nodes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1543434
> site: ability to only generate a ceph.conf on the machines

- roles/ceph-mon/tasks/openstack_config.yml
Since Luminous we need to set the application tag for each pool,
otherwise a CEPH_WARNING is generated when the pools are in use.
We should assign the OpenStack pools to their default which would be
"rbd". When updating to Luminous this would happen automatically to the
vms, images, backups and volumes pools, but for new deploys this is not
the case.
> Set application for OpenStack pools

- roles/ceph-osd/tasks/activate_osds.yml
Add support for using multipath disks as OSDs. This requires ceph-ansible knowing how the multipath disk partition names are formatted.
> Add support for multipath disks

- infrastructure-playbooks/take-over-existing-cluster.yml
This should partially fix https://bugzilla.redhat.com/show_bug.cgi?id=1501117
The addition of including the ``host_vars`` is troublesome though and will fail downstream if that file does not exist. Using ``include_vars`` in a playbook also has higher var precedence than those collected relative to your inventory or playbook which can cause unexpected failures. I'll submit another PR to master to remove at least the lines that include ``host_vars``.
> backport: infra: fix take-over-existing-cluster.yml playbook

- infrastructure-playbooks/take-over-existing-cluster.yml
These are better collected by ansible automatically. This would also
fail if the host_var file didn't exist.
> infra: do not include host_vars/* in take-over-existing-cluster.yml

- infrastructure-playbooks/rolling_update.yml
Variables set at the play level with ``vars`` do
not carry over into the next play in the playbook.
The var jewel_minor_update was set in a previous play but
used in this one and was failing because it was not defined.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1544029
> rolling update: fix undefined jewel_minor_update failure

- roles/ceph-mon/tasks/openstack_config.yml
Since Luminous we need to set the application tag for each pool,
otherwise a CEPH_WARNING is generated when the pools are in use.
We should assign the OpenStack pools to their default which would be
"rbd". When updating to Luminous this would happen automatically to the
vms, images, backups and volumes pools, but for new deploys this is not
the case.
> Backport of 2386

- roles/ceph-defaults/handlers/main.yml
This patch fixes an issue where if hosts have different service lists,
it will prevent restarting changes on services that run later on.
For example, hostA in the mons and rgws group would initiate a config
change and restart of services on all mons and rgws hosts, even though
a separate hostB (which is only in the rgws group) has not had its
configuration changed yet. Additionally, when the second host has its
coniguration changed as part of the ceph-rgw role, it will not initiate
a restart since its inventory name != the first hosts.
To fix this we should run the restart once (which is already the case)
as long as the host is in the appropriate group, and filter to the other
hosts in that group.
> Restart services if handler called

- roles/ceph-docker-common/tasks/main.yml
- site-docker.yml.sample
This fact is already set in site-docker.yml so there's no need to check
it again in ceph-docker-common
Signed-off-by: Paul Bourke <paul.bourke@oracle.com>
> Remove redundant task to check if atomic

- infrastructure-playbooks/rolling_update.yml
According to hostname configuration, the task waiting for mons to be in
quorum might fail.
The idea here is to look for both shortname and fqdn in
`ceph_health_raw` instead of just `ansible_hostname`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1546127
> update: look for short and fqdn in ceph_health_raw

- roles/ceph-nfs/tasks/start_nfs.yml
Don't merge this.
Test to see if we copy over the nfs-ganesha-lock.service.debian8 file
properly, whether the Xenial CI job will work.
The upstream download.ceph.com nfs-ganesha package should be fixed for
xenial (which is in progress).
> [TEST] Test setting up correct systemd file for nfs-ganesha

- roles/ceph-common/tasks/misc/system_tuning.yml
Using updatedb -e doesnt make a permanent change, but will updatedb
without the passed path.
To make this change more permanent we should update the
/etc/updatedb.conf file to include /var/lib/ceph.
> Adjust /etc/updatedb.conf to not parse /var/lib/ceph

- roles/ceph-common/tasks/misc/system_tuning.yml
Using updatedb -e doesnt make a permanent change, but will updatedb
without the passed path.
To make this change more permanent we should update the
/etc/updatedb.conf file to include /var/lib/ceph.
Backport of: #2405 
(cherry picked from commit 2779d2a850265d01b62b9d8b4db7c2b4ce8b8fec)
> Backport of 2405

- roles/ceph-defaults/handlers/main.yml
This patch fixes an issue where if hosts have different service lists,
it will prevent restarting changes on services that run later on.
For example, hostA in the mons and rgws group would initiate a config
change and restart of services on all mons and rgws hosts, even though
a separate hostB (which is only in the rgws group) has not had its
configuration changed yet. Additionally, when the second host has its
coniguration changed as part of the ceph-rgw role, it will not initiate
a restart since its inventory name != the first hosts.
To fix this we should run the restart once (using run_once: True)
as long as the host has called the handler. This will ensure that even
if only 1 host has called the handler it will initiate a restart on all
hosts that have called the handler. …
> backport of 2287

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- tests/functional/centos/7/bs-lvm-osds/group_vars/all
- tests/functional/centos/7/bs-lvm-osds/vagrant_variables.yml
- tests/functional/centos/7/bs-osds-container/group_vars/osds.yml
- tests/functional/centos/7/bs-osds-container/vagrant_variables.yml
- tests/functional/centos/7/bs-osds-non-container/group_vars/osds.yml
- tests/functional/centos/7/bs-osds-non-container/vagrant_variables.yml
- tests/functional/centos/7/cluster/group_vars/all
- tests/functional/centos/7/cluster/group_vars/osds
- tests/functional/centos/7/cluster/vagrant_variables.yml
- tests/functional/centos/7/fs-osds-container/group_vars/osds.yml
- tests/functional/centos/7/fs-osds-container/vagrant_variables.yml
- tests/functional/centos/7/fs-osds-non-container/group_vars/osds.yml
- tests/functional/centos/7/fs-osds-non-container/vagrant_variables.yml
- tests/functional/centos/7/lvm-osds/group_vars/all
- tests/functional/centos/7/lvm-osds/vagrant_variables.yml
- tests/functional/ubuntu/16.04/cluster/group_vars/all
- tests/functional/ubuntu/16.04/cluster/group_vars/osds
- tests/functional/ubuntu/16.04/cluster/vagrant_variables.yml
- vagrant_variables.yml.linode
- vagrant_variables.yml.sample
This is now managed by Ceph packages.
See: https://github.com/ceph/ceph/pull/18544/files
http://tracker.ceph.com/issues/21929
Closes: https://github.com/ceph/ceph-ansible/issues/2410
> remove kernel.pid_max

- roles/ceph-mon/tasks/openstack_config.yml
Previously it was necessary to provide a value (eventually an
empty string) for the "rule_name" key for each item in
openstack_pools. This change makes that optional and defaults to
empty string when not given.
> Make rule_name optional when defining items in openstack_pools

- roles/ceph-mds/tasks/non_containerized.yml
Fix typo on when test for ansible_service_mgr == systemd
> mds: fix ansible_service_mgr typo

- roles/ceph-client/tasks/pre_requisite.yml
That task is failing on containerized deployment because `ceph:ceph`
doesn't exist.
The idea here is to use the `{{ ceph_uid }}` to set the ownerships for
the admin keyring when containerized_deployment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1540578
> client: use `ceph_uid` fact to set uid/gid on admin key

- roles/ceph-mds/tasks/non_containerized.yml
This commit fixes a typo introduced by 4671b9e74e657988137f6723ef12e38c66d9cd40
(cherry picked from commit 1e1b26ca4d6f4ede84756003b9ffad851530e956)
Backport of #2416
> [backport] mds: fix ansible_service_mgr typo

- tox.ini
The jobs launches by the CI are not using 'ansible.cfg'.
There are some parameters that should avoid SSH failure that we are used
to see in the CI so far.
> tests: make CI jobs using 'ansible.cfg'

- roles/ceph-mon/tasks/docker/main.yml
Keeps consistency inside the role and among roles.
Makes the code more readable.
> Makes use of docker_exec_cmd in ceph-mon role.

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
As part of fcba2c801a122b7ce8ec6a5c27a70bc19589d177 these vars were
removed and no longer do anything:
radosgw_dns_name
radosgw_resolve_cname
This patch removes them from the group_vars files and defaults/main.yml
> Remove vars that are no longer used

- callback_plugins/installer_checkpoint.py
- site-docker.yml.sample
- site.yml.sample
This was taken from the openshift ansible repository here:
https://github.com/leseb/openshift-ansible/tree/master/roles/installer_checkpoint
Rationale:
A complete OpenShift cluster installation is comprised of many different
components which can take 30 minutes to several hours to complete. If
the installation should fail, it could be confusing to understand at
which component the failure occurred. Additionally, it may be desired to
re-run only the component which failed instead of starting over from the
beginning. Components which came after the failed component would also
need to be run individually.
Ceph has a similar situation so we can benefit from that
callback_plugin.
> add support for installation checkpoint

- group_vars/clients.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/create_users_keys.yml
`ceph_conf_overrides.global.osd_pool_default_pg_num` shouldn't be a
mandatory variable since we can set it in `keys` dict.
It's too much to have to define both.
> client: fix pgs num for client pool creation

- infrastructure-playbooks/purge-docker-cluster.yml
- roles/ceph-mon/tasks/docker/configure_ceph_command_aliases.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-mon/templates/ceph-aliases.sh.j2
Same approach as openshift-ansible with etcdctl:
* https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/etcd/tasks/auxiliary/drop_etcdctl.yml
* https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/etcd/etcdctl.sh
Adds some ceph aliases to /etc/profile.d/ceph-aliases.sh so we can run ceph cli commands: ceph, radosgw-admin, rados and rbd directly from the host, without having to do "sudo docker exec ...".
> Adds handy ceph aliases whe containerized installations.

- roles/ceph-config/tasks/main.yml
Since the approach to creating a ceph.conf file has changed, and now
no-longer relies on assembling config file fragments in /etc/ceph/ceph.d
we can avoid the conf_overrides rendering on the local host and skip out
the tasks related to that, instead using just the config_template task
to configure the file directly.
> Simplify ceph.conf generation

- plugins/actions/_v1_config_template.py
- plugins/actions/_v2_config_template.py
In ec042219e64a321fa67fce0384af76eeb238c645 we added OrderedDict and
sorted to be able to preserve order for config_template k,v pairs inside
a section.
This patch adds a similar ordering for the sections themselves, which
could still change order and intiiate handler restarts.
OrderedDict isn't needed because we use .items() to return a list that
can then be sorted().
> Fix config_template to consistently order sections

- roles/ceph-defaults/tasks/facts.yml
This variable is needed for containerized clusters and is required for
the ceph-docker-common role. Typically the is_atomic variable is set in
site-docker.yml.sample though so if ceph-docker-common is used outside
of that playbook it needs set in another way. Moving the creation of
this variable inside the role means playbooks don't need to worry
about setting it.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1558252
> ceph-defaults: set is_atomic variable

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
setup cephx keys when not nfs_obj_gw
Copy the admin key when configured nfs_file_gw (but not nfs_obj_gw). Also,
copy/setup RGW related directories only when configured as nfs_obj_gw.
> setup keys properly when not nfs_obj_gw

- roles/ceph-osd/templates/osd.conf.j2
osd crush location is set by ceph_crush in the library,
osd.conf.j2 is not used any more.
Signed-off-by: Ning Yao <yaoning@unitedstack.com>
> cleanup osd.conf.j2

- group_vars/clients.yml.sample
- group_vars/mons.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/tasks/openstack_config.yml
- tests/functional/centos/7/cluster/group_vars/clients
- tests/functional/centos/7/cluster/group_vars/mons
- tests/functional/centos/7/docker-collocation/group_vars/clients
- tests/functional/centos/7/docker/group_vars/clients
- tests/functional/centos/7/docker/group_vars/mons
Follow up patch to PR 2432 [1] which replaces "size" (sorry if
the original bug used that term, which can be confusing) with
expected_num_objects as is used in the Ceph documentation [2].
[1] https://github.com/ceph/ceph-ansible/pull/2432/files
[2] http://docs.ceph.com/docs/jewel/rados/operations/pools
> Refer to expected-num-ojects as expected_num_objects, not size

- roles/ceph-mds/tasks/containerized.yml
This update will resolve `ceph-mds: deployment failure error['cephfs' is undefined.].`
See: `roles/ceph-mon/tasks/create_mds_filesystems.yml`. The same last two tasks are present there, and actually belong in that role since `"{{ cephfs }}"` gets defined in:
`roles/ceph-mon/defaults/main.yml`, and not `roles/ceph-mds/defaults/main.yml`
Signed-off-by: Randy J. Martinez <ramartin@redhat.com>
> ceph-mds: delete duplicate multimds container tasks

- infrastructure-playbooks/purge-docker-cluster.yml
The `remove_packages` prompt is redundant to the `ireallymeanit` prompt
since it does exactly the same thing. I guess the only goal of this task
was to make a break to warn user about `--skip-tags=with_pkg` feature.
This warning should be part of the first prompt.
> purge-docker: remove redundant task

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-client/tasks/pre_requisite.yml
- roles/ceph-config/tasks/main.yml
- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-docker-common/tasks/main.yml
- roles/ceph-docker-common/tasks/selinux.yml
- site-docker.yml.sample
This PR aims to move the client pools and keys creation for from ceph-client to ceph-mon so we do not have to pull container image for client nodes.
> create keys and pools for client nodes only on first node

- roles/ceph-defaults/tasks/facts.yml
Tripleo deployment failed when the monitors not manged
by tripleo itself with:
FAILED! => {"msg": "list object has no element 0"}
The failing play item was introduced by
f46217b69ae18317cb0c1cc3e391a0bca5767eb6 .
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1552327
Signed-off-by: Attila Fazekas <afazekas@redhat.com>
> Deploying without managed monitors failed

- site-docker.yml.sample
get a non empty array as default value for `groups.get('clients')`,
otherwise `| first` filter will complain because it can't work with
empty array.
> site-docker: followup on #2487

- roles/ceph-common/tasks/installs/redhat_dev_repository.yml
No use even trying to use something that doesn't exist.
> Use the CentOS repo for Red Hat dev packages

- roles/ceph-defaults/tasks/facts.yml
- tox.ini
Currently tag-build-master-luminous-ubuntu-16.04 is not used anymore.
Also now, 'latest' points to CentOS so we need to make that switch here
too.
We know have latest tags for each stable release so let's use them and
point tox at them to deploy the right version.
> tox: use container latest tag for upgrades

- roles/ceph-common/tasks/installs/install_redhat_packages.yml
Prior to this change, if a user had ceph-test-12.2.1 installed, and upgraded to ceph v12.2.3 or newer, the RPM upgrade process would fail.
The problem is that the ceph-test RPM did not depend on an exact version of ceph-common until v12.2.3.
In Ceph v12.2.3, ceph-{osdomap,kvstore,monstore}-tool binaries moved from ceph-test into ceph-base. When ceph-test is not yet up-to-date, Yum encounters package conflicts between the older ceph-test and newer ceph-base.
When all users have upgraded beyond Ceph < 12.2.3, this is no longer relevant.
> common: upgrade/install ceph-test RPM first

- docs/source/index.rst
The path of ceph.conf sample template moved to ceph-config.
Therefore docs needs to be changed to the right directory.
Signed-off-by: JohnHaan <yongiman@gmail.com>
> Fixed wrong path of ceph.conf in docs.

- infrastructure-playbooks/purge-docker-cluster.yml
Added 'ignore_errors: true' to multiple tasks which run docker commands; even in cases where docker is no longer installed. Because of this, certain tasks in the purge-docker-cluster.yml will cause the playbook to fail if re-run and stop the purge. This leaves behind a dirty environment, and a playbook which can no longer be run.
Fix Regex line 275: Sometimes 'list-units' will output 4 spaces between loaded+active. The update will account for both scenarios.
purge fetch_directory: in other roles fetch_directory is hard linked ex.: "{{ fetch_directory }}"/"{{ somedir }}". That being said, fetch_directory will never have a trailing slash in the all.yml so this task was never being run(causing failures when trying to re-deploy).
Signed-off-by: Randy J. Martinez <ramartin@redhat.com>
> purge-docker: added conditionals needed to successfully re-run purge-docker-cluster.yml.

- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/templates/ganesha.conf.j2
Add a variable, ceph_nfs_disable_caching, that if set to true
disables ganesha's directory and attribute caching as much as
possible.
Also, disable caching done by ganesha, when 'nfs_file_gw'
variable is true, i.e., when Ganesha is used as CephFS's gateway.
This is the recommended Ganesha setting as libcephfs already caches
information. And doing so helps avoid cache incoherency issues
especially with clustered ganesha over CephFS.
Fixes: https://tracker.ceph.com/issues/23393
Signed-off-by: Ramana Raja <rraja@redhat.com>
> ceph-nfs: allow disabling ganesha caching

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
NFS-ganesha cannot start is the nfs-server service
is running. This commit stops nfs-server in case it
is running on a node before the nfs-ganesha service
starts up
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1508506
> nfs: ensure nfs-server server is stopped

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mon/tasks/create_mds_filesystems.yml
allow_multimds will be officially deprecated in Mimic, specify it
only for all versions of Ceph where it was declared stable. Going
forward, specify only max_mds.
Version checks should make this safe to merge.
> Remove deprecated allow_multimds

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Copy the admin key when configured nfs_file_gw (but not nfs_obj_gw). Also,
copy/setup RGW related directories only when configured as nfs_obj_gw.
[skip ci]
backport of : #2438 
(cherry picked from commit 7f91547304349199bf10a636b4e10ccaf20a4212)
> setup cephx keys when not nfs_obj_gw

- roles/ceph-osd/tasks/main.yml
- roles/ceph-osd/tasks/scenarios/collocated.yml
- roles/ceph-osd/tasks/scenarios/non-collocated.yml
Regardless if the partition is 'ceph' or something else, we don't want
to be as strick as checking for a particular partition.
If the drive has a partition, we just don't do anything.
This solves the case where the server reboots, disks get a different
/dev/sda (node) allocation. In this case, prior to restarting the server
/dev/sda was an OSD, but now it's /dev/sdb and the other way around.
In such scenario, we will try to prepare the OSD and create a new
partition, so let's not mess around with devices that have partitions.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1498303
> osd: do not do anything if the dev has a partition

- roles/ceph-common/tasks/installs/debian_rhcs_repository.yml
When installing rhcs on Debian systems the red hat repos must have the
highest priority so we avoid packages conflicts and install the rhcs
version.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1565850
> [skip ci] rhcs: re-add apt-pining

- roles/ceph-defaults/tasks/facts.yml
Red Hat is now using tags[3,latest] for image rhceph/rhceph-3-rhel7. Because of this, the ceph_uid conditional passes for Debian when 'ceph_docker_image_tag: latest' on RH family deployments. Updating the conditional to ansible_os_family solves the problem.
Signed-off-by: Randy J. Martinez <ramartin@redhat.com>
> ceph-defaults: fix ceph_uid fact on container deployments

- roles/ceph-client/tasks/create_users_keys.yml
ceph-authtool does not support raw arguements so we have to quote caps
declaration like this allow 'bla bla' instead of allow bla bla
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1568157
> client: add quotes to the dict values

- infrastructure-playbooks/shrink-osd.yml
Now if the service name contains nvme we know we need to remove the last
2 character instead of 1.
If nvme then osd_to_kill_disks is nvme0n1, we need nvme0
If ssd or hdd then osd_to_kill_disks is sda1, we need sda
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1561456
> [skip ci] shrink-osd: ability to shrink NVMe drives

- .gitignore
I personally dev on vscode and I have some preferences to save when it
comes to running the python unit tests. So escaping this directory is
actually useful.
(cherry picked from commit 3c4319ca4b5355d69b2925e916420f86d29ee524)
> [skip ci] add .vscode/ to gitignore

- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-common/tasks/installs/debian_custom_repository.yml
- roles/ceph-common/tasks/installs/debian_dev_repository.yml
- roles/ceph-common/tasks/installs/debian_uca_repository.yml
- roles/ceph-common/tasks/installs/install_on_debian.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
- roles/ceph-docker-common/tasks/pre_requisites/debian_prerequisites.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
The apt-cache update can fail due to transient issues related to the
action being a network operation. To reduce the impact of these
transient failures this patch adds a retry to the update_cache task.
However, the apt_repository tasks which would perform an apt_update
won't retry the apt_update on a failure in the same way, as such this PR
moves the apt_update into an individual task, once per role.
Finally, the apt_repository tasks no longer have a changed_when: false,
and the apt_cache update is only performed once per role, if the
repositories change. Otherwise the cache is updated on the "apt" install
tasks if the cache_timeout has been reached.
> Move apt cache update to individual task per role

- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
If we are in a middle of an update we want to get the new package
version being installed so the task that copies the repo files should
not be skipped.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572032
> common: copy iso files if rolling_update

- roles/ceph-nfs/templates/ganesha.conf.j2
When 'ceph_nfs_disable_caching' is set to True, disable attribute
caching done by Ganesha for all Ganesha exports.
Signed-off-by: Ramana Raja <rraja@redhat.com>
> ceph-nfs: disable attribute caching

- site-docker.yml.sample
- site.yml.sample
there is no need to gather facts with O(N^2) way.
Only one node should gather facts from other node.
Fixes: #2553
> playbook: improve facts gathering

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
The Debian and SuSE installs for nfs-ganesha on the non-rhcs repository
requires you to allow_unauthenticated for Debian, and disable_gpg_check
for SuSE. The nfs-ganesha-rgw package already does this, but the
nfs-ganesha-ceph package will fail to install because of this same
issue.
This PR moves the installations to happen when the appropriate flags are
set to True (nfs_obj_gw & nfs_file_gw), but does it per distro (one for
SuSE and one for Debian) so that the appropriate flag can be passed to
ignore the GPG check.
> Fix install of nfs-ganesha-ceph for Debian/SuSE

- roles/ceph-defaults/templates/restart_mds_daemon.sh.j2
Make sure the `restart_mds_daemon` script is created with the correct MDS name.
Like for the monitors, the script should contain a short name or fully qualified domain name depending on variable settings.
For monitors, this is already ok:
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/tasks/facts.yml#L11-L21
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/templates/restart_mon_daemon.sh.j2#L5
For metadata servers this is not:
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/tasks/facts.yml#L122-L132
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/templates/restart_mds_daemon.sh.j2#L5
> Fix MDS name in restart_mds_daemon script

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Quick clean on a legacy syntax due to e0a264c7e
> osd: clean legacy syntax in ceph-osd-run.sh.j2

- roles/ceph-mon/tasks/docker/main.yml
On containerized deployment,
when upgrading from jewel to luminous, mgr keyring creation fails because the
command to create mgr keyring is executed on a container that is still
running jewel since the container is restarted later to run the new
image, therefore, it fails with bad entity error.
To get around this situation, we can delegate the command to create
these keyrings on the first monitor when we are running the playbook on the last monitor.
That way we ensure we will issue the command on a container that has
been well restarted with the new image.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1574995
> mon: fix mgr keyring creation when upgrading from jewel

- roles/ceph-client/tasks/create_users_keys.yml
trying to set the default value for pg_num to
`hostvars[groups[mon_group_name][0]]['osd_pool_default_pg_num'])` will
break in case of external client nodes deployment.
> client: remove default value for pg_num in pools creation

- Makefile
Prior to this change, if we created entirely new Git tags patterns like "3.2.0alpha" or "3.2.0foobar", the Makefile would incorrectly translate the Git tag name into a Name-Version-Release that would prevent upgrades to "newer" versions.
This happened for example in https://bugs.centos.org/view.php?id=14593, "Incorrect naming scheme for a build of ceph-ansible prevents subsequent updates to be installed"
If we encounter a new Git tag format that we cannot parse, pessimistically bail out early instead of trying to build an RPM.
The purpose of this safeguard is to prevent Jenkins from building RPMs that cannot be easily upgraded.
> Makefile: bail out on unknown Git tag formats

- roles/ceph-osd/tasks/system_tuning.yml
The order of fs.aio-max-nr (which is hard-coded to 1048576) means that
if you set fs.aio-max-nr in os_tuning_params it will effectively be
ignored for bluestore scenarios.
To resolve this we should move the setting of fs.aio-max-nr above the
setting of os_tuning_params, in this way the operator can define the
value of fs.aio-max-nr to be something other than 1048576 if they want
to.
Additionally, we can make the sysctl settings happen in 1 task rather
than multiple.
> Allow os_tuning_params to overwrite fs.aio-max-nr

- roles/ceph-osd/tasks/system_tuning.yml
The order of fs.aio-max-nr (which is hard-coded to 1048576) means that
if you set fs.aio-max-nr in os_tuning_params it will effectively be
ignored for bluestore scenarios.
To resolve this we should move the setting of fs.aio-max-nr above the
setting of os_tuning_params, in this way the operator can define the
value of fs.aio-max-nr to be something other than 1048576 if they want
to.
Additionally, we can make the sysctl settings happen in 1 task rather
than multiple.
(cherry picked from commit 08a2b58d39a687e25436afdf3fda1591d3be8ca1)
> Backport #2574 to stable-3.1

- infrastructure-playbooks/rolling_update.yml
the role `ceph-mgr` that is played later in the playbook fails because
the destination path for the fetched keys is wrong.
This patch fix the destination path used in the task `fetch ceph mgr
key(s)` so there is no mismatch.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1574995
(cherry picked from commit 1b4c3f292d8779158ea445a8c9a11c8ed26abe11)
> bkp of 2588: rolling_update: fix dest path for mgr keys fetching

- roles/ceph-mon/tasks/docker/main.yml
There is no need to stat for created mgr keyrings since they are created
anyway when deploying a ceph cluster > jewel.
We won't enter the block if ceph release is prior to luminous.
> mon: refactor of mgr key fetching

- roles/ceph-common/tasks/installs/install_debian_packages.yml
- roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
- roles/ceph-common/tasks/installs/install_redhat_packages.yml
- roles/ceph-common/tasks/installs/install_suse_packages.yml
- roles/ceph-common/vars/main.yml
To make the package installation more efficient we should install
packages as a list rather than as individual tasks or using a
"with_items" loop. The package managers can handle a list passed to them
to install in one go.
We can use a specified list with the "omit" filter to indicate when
packages should be installed or not.
> Install packages as a list

- Makefile
Add a new "make tag" command. This automates some common operations:
1) Automatically determine the next Git tag version number to create.
For example:
"3.2.0beta1 -> "3.2.0beta2"
"3.2.0rc1 -> "3.2.0rc2"
"3.2.0" -> "3.2.1"
2) Create the Git tag, and print instructions for the user to push it to
GitHub.
3) Sanity check that HEAD is a stable-* branch or master (bail on
everything else).
4) Sanity check that HEAD is not already tagged.
Note, we will still need to tag manually once each time we change the format, for example when moving from tagging "betas" to tagging "rcs", or "rcs" to "stable point releases".
> [skip ci] Makefile: add "make tag" command

- infrastructure-playbooks/rolling_update.yml
During a minor update from a jewel to a higher jewel version (10.2.9 to
10.2.10 for example) osd flags don't get applied because they were done
in the mgr section which is skipped in jewel since this daemons does not
exist.
Moving the set flag section after all the mons have been updated solves
that problem.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1548071
> rolling_update: move osd flag section

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
During the transition from jewel non-container to container old ceph
units are disabled. ceph-disk can still remain in some cases and will
appear as 'loaded failed', this is not a problem although operators
might not like to see these units failing. That's why we remove them if
we find them.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1577846
> [skip ci] switch: disable ceph-disk units

- infrastructure-playbooks/rolling_update.yml
During a minor update from a jewel to a higher jewel version (10.2.9 to
10.2.10 for example) osd flags don't get applied because they were done
in the mgr section which is skipped in jewel since this daemons does not
exist.
Moving the set flag section after all the mons have been updated solves
that problem.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1548071
Co-authored-by: Tomas Petr <tpetr@redhat.com>
(cherry picked from commit d80a871a078a175d0775e91df00baf625dc39725)
backport of : #2594
> Backport 3.0 : rolling_update: move osd flag section

- vagrant_variables.yml.atomic
Missing this variable causes Vagrant fail to provision cluster.
@font @leseb
> [skip ci] Adding mgr_vms variable

- infrastructure-playbooks/take-over-existing-cluster.yml
A customer has been facing an issue when trying to override
`monitor_interface` in inventory host file.
In his use case, all nodes had the same interface for
`monitor_interface` name except one. Therefore, they tried to override
this variable for that node in the inventory host file but the
take-over-existing-cluster playbook was failing when trying to generate
the new ceph.conf file because of undefined variable.
Typical error:
```
fatal: [srvcto103cnodep01]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'ansible_bond0.15'"}
```
Including variables like this `include_vars: group_vars/all.yml` prevent
us from overriding anything in inventory host file because it
overwrites everything you would have defined in inventory.
Closes: …
> [skip ci] take-over: fix bug when trying to override variable

- roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
Extra space in systemctl list-units can cause restart_osd_daemon.sh to
fail
It looks like if you have more services enabled in the node space
between "loaded" and "active" get more space as compared to one space
given in command the command[1].
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1573317
> [skip ci] defaults: restart_osd_daemon unit spaces

- roles/ceph-validate/tasks/main.yml
A dev or rhcs install does not require ceph_stable_release to be set and
instead generates that by looking at the installed ceph-version.
However, at this point in the playbook ceph may not have been installed
yet and ceph-common has not be run.
Fixes: https://github.com/ceph/ceph-ansible/issues/2618
> ceph-validate: do not check ceph version on dev or rhcs installs

- infrastructure-playbooks/rolling_update.yml
When running ansible2.4-update_docker_cluster there is an issue on the
"get current fsid" task. The current task only works for
non-containerized deployment but will run all the time (even for
containerized). This currently results in the following error:
TASK [get current fsid] ********************************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-luminous-ansible2.4-update_docker_cluster/rolling_update.yml:214
Tuesday 22 May 2018  22:48:32 +0000 (0:00:02.615)       0:11:01.035 ***********
fatal: [mgr0 -> mon0]: FAILED! => {
"changed": true,
"cmd": [
"ceph",
"--cluster",
"test",
"fsid"
],
"delta": "0:05:00.260674",
"end": "2018-05-22 22:53:34.555743",
"rc": 1,
"start": "2018-05-22 22:48:34.295069"
}
STDERR:
2018-05-22 22:48:34.495651 …
> rolling_update: fix get fsid for containers

- rhcs_edits.txt
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1519835
> [skip ci] rhcs: bump version to 3.0 for stable 3.1

- site-docker.yml.sample
Since we fixed the `gather and delegate facts` task, this exception is
not needed anymore. It's a leftover that should be removed to save some
time when deploying a cluster with a large client number.
> playbook: follow up on #2553

- group_vars/rgws.yml.sample
- roles/ceph-rgw/defaults/main.yml
- roles/ceph-rgw/tasks/docker/container_env_facts.yml
- roles/ceph-rgw/tasks/docker/main.yml
- roles/ceph-rgw/tasks/main.yml
You can now use RGW_ZONE and RGW_ZONEGROUP on each rgw host from your
inventory and assign them a value. Once the rgw container starts it'll
pick the info and add itself to the right zone.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1551637
> rgw: container add option to configure multi-site zone

- site-docker.yml.sample
Backport of #2638 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1582281
> Backport of 2638 in stable-3.1

- roles/ceph-mds/tasks/main.yml
When collocating mds on monitor node, the cephpfs will fail
because `docker_exec_cmd` is reset to `ceph-mds-monXX` which is
incorrect because we need to delegate the task on `ceph-mon-monXX`.
In addition, it wouldn't have worked since `ceph-mds-monXX` container
isn't started yet.
Moving the task earlier in the `ceph-mds` role will fix this issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1578086
> mds: move mds fs pools creation

- infrastructure-playbooks/purge-iscsi-gateways.yml
Without the become:yes, the purge tasks fail with either access issues to the rados config object
or the log file in /var/log.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1549004
> [skip ci] iscsi purge process needed sudo privileges

- infrastructure-playbooks/rolling_update.yml
ceph-iscsi packages are currently broken so let's not run the CI yet.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1575829
> rolling_update: add role ceph-iscsi-gw

- requirements.txt
ceph-config: add netaddr to python requirements
netaddr is required to generate ceph.conf, let's add this requirement in `requirements.txt`
> python-netaddr is required to generate ceph.conf

- tests/functional/setup.yml
- tox.ini
In the CI we can see at many times failures like following:
`Failure talking to yum: Cannot find a valid baseurl for repo:
base/7/x86_64`
It seems the fastest mirror detection is sometimes counterproductive and
leads yum to fail.
This has been added in the `setup.yml`.
This playbook was used until now only just before playing `testinfra`
and could be used before running ceph-ansible so we can add some
provisionning tasks.
> tests: avoid yum failures

- tests/requirements2.5.txt
`requirements2.5.txt` is pointing to `tests/requirements2.4.txt` while
it should point to `requirements2.4.txt` since they are in the same
directory.
> tests: fix broken symlink

- roles/ceph-osd/tasks/main.yml
in `ceph-osd` there is no need to set `docker_exec_cmd` since the only
place where this fact is used is in `openstack_config.yml` which
delegate all docker command to a monitor node. It means we need the
`docker_exec_cmd` fact that has been set referring to `ceph-mon-*`
containers, this fact is already set earlier in `ceph-defaults`.
By the way, when collocating an OSD with a MON it fails because the container
`ceph-osd-{{ ansible_hostname }}` doesn't exist.
Removing this task will allow to collocate an OSD with a MON.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1584179
> osds: do not set docker_exec_cmd fact

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
- tests/functional/centos/7/cluster/group_vars/all
- tests/functional/centos/7/docker-collocation/group_vars/all
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/ubuntu/16.04/cluster/group_vars/all
When playing ceph-mds role, mon nodes have set a fact with the default
pg num for osd pools, we can simply default to this value for cephfs
pools (`cephfs_pools` variable).
At the moment the variable definition for `cephfs_pools` looks like:
```
cephfs_pools:
- { name: "{{ cephfs_data }}", pgs: "" }
- { name: "{{ cephfs_metadata }}", pgs: "" }
```
and we have a task in `ceph-validate` to ensure `pgs` has been set to a
valid value.
We could simply avoid this check by setting the default value of `pgs`
to `hostvars[groups[mon_group_name][0]]['osd_pool_default_pg_num']` and
let to users the possibility to override this value.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581164
> mdss: do not make pg_num a mandatory params

- Makefile
Fix a typo in `tag` target, double quote are missing here.
Without them, the `make tag` command fails like this:
```
if [[ "v3.0.35" ==  ]]; then \
echo "e5f2df8 on stable-3.0 is already tagged as v3.0.35"; \
exit 1; \
fi
/bin/sh: -c: line 0: unexpected argument `]]' to conditional binary operator
/bin/sh: -c: line 0: syntax error near `;'
/bin/sh: -c: line 0: `if [[ "v3.0.35" ==  ]]; then     echo "e5f2df8 on stable-3.0 is already tagged as v3.0.35";     exit 1; fi'
make: *** [tag] Error 2
```
> Makefile: followup on #2585

- roles/ceph-osd/tasks/openstack_config.yml
This is a follow up on #2628.
Even with the openstack pools creation moved later in the playbook,
there is still an issue because OSDs are not all UP when trying to
create pools.
Adding a task which checks for all OSDs to be UP with a `retries/until`
condition should definitively fix this issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1578086
> osds: wait for osds to be up before creating pools

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/release-rhcs.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-docker-common/tasks/release.yml
The first 14.x tag has been cut so this needs to be added so that
version detection will still work on the master branch of ceph. I've
used the 'next' name here because at this time 14.x has not be named.
Fixes: https://github.com/ceph/ceph-ansible/issues/2671
> ceph-defaults: add the 14.x entry to ceph_release_num

- roles/ceph-mon/tasks/main.yml
- roles/ceph-osd/tasks/main.yml
Since the openstack_config.yml has been moved to `ceph-osd` we must move
this `set_fact` in ceph-osd otherwise the tasks in
`openstack_config.yml` using `openstack_keys` will actually use the
defaults value from `ceph-defaults`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1585139
> mons: move set_fact of openstack_keys in ceph-osd

- tests/functional/setup.yml
During the tests, the remote epel repository is generating a lots of
errors leading to broken jobs (issue #2666)
This patch is about using a local repository instead of a random one.
To achieve that, we make a preliminary install of epel-release, remove
the metalink and enforce a baseurl to our local http mirror.
That should speed up the build process but also avoid the random errors
we face.
This patch is part of a patch series that tries to remove all possible yum failures.
> ceph-defaults: Enable local epel repository

- roles/ceph-nfs/tasks/start_nfs.yml
This is a backport of f45662e27023e034adac646ad814d19574fd2153 :
"We can simply reference the template name since it exists within the
role that we are calling. We don't need to check the ANSIBLE_ROLE_PATH
or playbooks directory for the file."
This is worth backporting because it breaks when the roles are placed in a subdirectory,
for example if ceph-ansible is checked out as a submodule of another projet.
> Backport "Fix template reference for ganesha.conf"

- infrastructure-playbooks/rolling_update.yml
Rolling upgrades should use norebalance flag for OSDs
The rolling upgrades playbook should have norebalance flag set for
OSDs upgrades to wait only for recovery.
Fixes: #2657 
Signed-off-by: vishal.kanaujia@flipkart.com
> Rolling upgrades should use norebalance flag for OSDs

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/misc/configure_firewall_rpm.yml
- roles/ceph-defaults/defaults/main.yml
Prior to this commit the firewall tasks were not opening the ceph-mgr
ports. This would lead to unclean configuration since the ceph-mgr
daemons can not connect to the OSDs.
Thi commit opens the right ports on the ceph-mgr nodes to talk with the
OSDs.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1526400
> ceph-common: add firewall rules for ceph-mgr

- tests/functional/centos/7/cluster/group_vars/osds
- tox.ini
The admin key must be copied on the osd nodes only when we test the
shrink scenario. Shrink relies on ceph-disk commands that require the
admin key on the node where it's being executed.
Now we only copy the key when running on the shrink-osd scenario.
> test: do not always copy admin key

- tests/functional/tests/rgw/test_rgw_tuning.py
41b4632 has introduced a change in functionnals tests.
Since the admin keyring isn't copied on rgw nodes anymore in tests, let's use
the rgw keyring to achieve them.
> tests: fix rgw tests

- tests/functional/setup.yml
There is no need to execute this task on atomic hosts.
> tests: skip disabling fastest mirror detection on atomic host

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Otherwise, with the removal of mds_allow_multimds, the default of 3 will be set
on every new FS.
Introduced by: c8573fe0d745e4667b5d757433efec9dac0150bc
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1583020
> change max_mds default to 1

- site-docker.yml.sample
Since we fixed the `gather and delegate facts` task, this exception is
not needed anymore. It's a leftover that should be removed to save some
time when deploying a cluster with a large client number.
(cherry picked from commit 828848017cefd981e14ca9e4690dd7d1320f0eef)
> Backport: playbook: follow up on #2553 in stable-3.0

- roles/ceph-osd/tasks/openstack_config.yml
When configuring openstack, the created keyrings aren't copied over to
all monitors nodes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1588093
> osd: copy openstack keys over to all mon

- tests/functional/tests/mds/test_mds.py
the expected number of mds daemon consist of number of daemons that are
'up' + number of daemons 'up:standby'.
> tests: improve mds tests

- infrastructure-playbooks/rolling_update.yml
Backport of #2712 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1550977
> Backport of 2712 in stable-3.0

- infrastructure-playbooks/rolling_update.yml
Backport of #2712 in stable-3.1
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1550977
> Backport of 2712 in stable-3.1

- roles/ceph-client/tasks/create_users_keys.yml
the `docker_exec_cmd` fact set in client role when there is no monitor
in inventory is wrong, `ceph-client-{{ hostname }}` is never created so
it will fail anyway.
> client: use dummy created container when there is no mon in inventory

- roles/ceph-mon/tasks/openstack_config.yml
When configuring openstack, the created keyrings aren't copied over to
all monitors nodes.
This should have been backported from
433ecc7cbcc1ac91cab509dabe5c647d58c18c7f but this would implie too much
changes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1588093
> Backport: mon: copy openstack keys over to all mon in stable-3.0

- roles/ceph-osd/tasks/openstack_config.yml
Backport of #2724 in stable-3.1
> Backport of 2724 in stable-3.1

- tests/functional/tests/mds/test_mds.py
the expected number of mds daemon consist of number of daemons that are
'up' + number of daemons 'up:standby'.
(cherry picked from commit c94ada69e80d7a1ddfbd2de2b13086d57a6fdfcd)
> Backport of 2725 in stable-3.0

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
- tests/conftest.py
We need to do this because on dev or rhcs installs ceph_stable_release
is not mandatory and the firewall check tasks have a task that is
conditional based off the installed version of ceph. If we perform those
checks after package install then they will not fail on dev or rhcs
installs.
> ceph-common: move firewall checks after package installation

- ansible.cfg
We see quite a few failures in the CI related to testing nodes losing
ssh connection. This modification allows ansible to retry more times and
wait longer before timing out. This seems to really affect testing
scenarios that use a large amount of testing nodes. The centos7_cluster
scenario specifically has 12 nodes and suffered from these failures
often.
> tests: increase ssh timeout and retries in ansible.cfg

- requirements.txt
This is the latest version that we support. If we don't pin this we
get a 2.5.x version installed that causes the playbook to fail in
various ways.
Fixes: https://github.com/ceph/ceph-ansible/issues/2631
> pin version of ansible to 2.4.2 in requirements.txt

- roles/ceph-client/tasks/create_users_keys.yml
combining `run_once: true` with `inventory_hostname ==
groups.get(client_group_name) | first` might cause bug when the only
node being run is not the first in the group.
In a deployment with a single client node it might cause issue because
sometimes keyring won't be created since the task could be definitively
skipped.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1588093
> client: keyrings aren't created when single client node

- tests/functional/tests/iscsi/test_iscsi.py
We don't have the same service running on non-container for now, this
will change soon but for let's only run the test on container.
> test: only on containerized iscsi

- roles/ceph-mon/tasks/main.yml
The current secure cluster play runs with all the monitors. The rerun
of this task is unnecessary and can be skipped.
Fixes: #2737
Signed-off-by: Vishal Kanaujia <vishal.kanaujia@flipkart.com>
> ceph-mon: Fix to run secure cluster only once in a run

- roles/ceph-osd/tasks/main.yml
If 'openstack_config' is false this task shouldn't be executed.
> ceph-osd: set 'openstack_keys_tmp' only when 'openstack_config' is defined.

- plugins/actions/validate.py
This error message may be confusing and need to be more explicit on
where you have to install notario, indeed, people may think this library
must be installed on configured nodes while it must be installed on the
node you are running the playbook.
Fixes: #2649
> validate: be more explicit with error msg when notario isn't installed

- tests/functional/centos/7/cluster/vagrant_variables.yml
we see more and more failure like `fatal: [mon0]: UNREACHABLE! => {}` in
`centos7_cluster` scenario, Since we have 30Gb RAM on hypervisors, we
can give monitors a bit more RAM. By the way, nodes on containerized cluster
testing scenario have already 1024Mb memory allocated.
> tests: increase memory to 1024Mb for centos7_cluster scenario

- tests/functional/centos/7/cluster/vagrant_variables.yml
Backport of #2748 in stable-3.1
> [skip ci] Backport of 2748 in stable-3.1

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
Prior to this patch if you were running on a Red Hat system,
ceph-ansible would try to configure firewalld for you without the
operators's consent.
Now you can enable or disable the fw configuration by setting
configure_firewall to either true or false.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1589146
> common: ability to enable/disable fw configuration

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
Prior to this patch if you were running on a Red Hat system,
ceph-ansible would try to configure firewalld for you without the
operators's consent.
Now you can enable or disable the fw configuration by setting
configure_firewall to either true or false.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1589146
(cherry picked from commit 2e8412734a81077c2b11de316e08bbecbed2de96)
> Backport: common: ability to enable/disable fw configuration in stable-3.1

- roles/ceph-mds/tasks/create_mds_filesystems.yml
Multiple active MDS became stable in Luminous.
> ceph-mds: do not enable multimds on jewel

- roles/ceph-client/tasks/create_users_keys.yml
The 'dummy' container is created only on first client node, it means we
must seek to destroy this container only on this node, otherwise this
can cause failure like following :
```
fatal: [192.168.24.8]: FAILED! => {"changed": false, "cmd": ["docker", "rm",
"-f", "ceph-create-keys"], "delta": "0:00:00.023692", "end": "2018-06-12
20:56:07.261278", "msg": "non-zero return code", "rc": 1, "start":
"2018-06-12 20:56:07.237586", "stderr": "Error response from daemon: No such
container: ceph-create-keys", "stderr_lines": ["Error response from daemon: No
such container: ceph-create-keys"], "stdout": "", "stdout_lines": []}
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1590746
> client: try to kill dummy container only on first client node

- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
As discussed with the cores, the current limits are too low and should
be bumped to higher value.
So now by default monitors get 3GB and OSDs get 5GB.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1591876
> mon/osd: bump container memory limit

- roles/ceph-common/tasks/misc/configure_firewall_rpm.yml
Currently we expect that if configure_firewall is set to True to have
firewalld enabled and running. Let's enforce that.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1589146
> common: start firewalld if configure_firewall

- tests/functional/centos/7/ooo-collocation/hosts
- tests/functional/centos/7/ooo-collocation/vagrant_variables.yml
adding more node in this scenario could help to have a better coverage
so we can catch more potential bugs.
> tests: add more nodes in ooo testing scenario

- tests/functional/tests/mon/test_mons.py
- tests/functional/tests/test_install.py
It might happen that the list of ips/hosts in following line (ceph.conf)
- `mon initial memebers = <hosts>`
- `mon host = <ips>`
are not ordered the same way depending on deployment.
This patch makes the tests looking for each ip or hostname in respective
lines.
> tests: fix *_has_correct_value tests

- tests/functional/tests/mon/test_mons.py
- tests/functional/tests/test_install.py
Backport of #2789 in stable-3.1
> Backport: tests: fix *_has_correct_value tests in stable-3.1

- tox.ini
that may be helpful to know why a test has been skipped.
from pytest doc:
```
-r chars              show extra test summary info as specified by chars
(f)ailed, (E)error, (s)skipped, (x)failed, (X)passed,
(p)passed, (P)passed with output, (a)all except pP.
Warnings are displayed at all times except when
--disable-warnings is set
```
> tests: add more verbosity in testinfra

- roles/ceph-defaults/templates/restart_mgr_daemon.sh.j2
Depending on your setup, ceph-mgr might get restarted multiple times.
When this is done to fast, systemd will prevent further restarts because of
configured limits in the ceph-mgr systemd unit file.
Resetting the failure count will prevent this problem. The reset is done before
the restart so in case of a real problem during the restart it still fails.
Fixes: #2768
> reset failed count of ceph-mgr

- tox.ini
This reverts commit 68eb850b27cd65571b9654fe7c1fd9c1f8435fdd.
That's too verbose and can be enabled manually when debugging.
> Revert "tests: add more verbosity in testinfra"

- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
Backport of #2775 in stable-3.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1591876
> Backport: mon/osd: bump container memory limit in stable-3.0

- tests/conftest.py
- tests/functional/tests/mon/test_mons.py
- tests/functional/tests/osd/test_osds.py
- tests/functional/tests/rgw/test_rgw_tuning.py
- tests/requirements2.4.txt
At the moment, a lot of tests are skipped when daemons are collocated.
Our tests consider a node belong to only 1 group while it's possible for
certain scenario it can belong to multiple groups.
> tests: fix broken test when collocated daemons scenarios

- tests/functional/tests/mds/test_mds.py
- tests/functional/tests/mgr/test_mgr.py
- tests/functional/tests/nfs/test_nfs_ganesha.py
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
- tests/functional/tests/rgw/test_rgw.py
avoid duplicating test unnecessarily just because of docker exec syntax.
Using the same logic than in the playbook with `docker_exec_cmd` allow us
to execute the same test on both containerized and non containerized environment.
The idea is to set a variable `docker_exec_cmd` with the
'docker exec <container-name>' string when containerized and
set it to '' when non containerized.
> tests: factorize docker tests using docker_exec_cmd logic

- roles/ceph-mon/templates/ceph-mon.service.j2
--net=host was hardcoded in the startup line so even though
mon_docker_net_host was set to False the net option would always be
activated.
mon_docker_net_host is set to True by default so this commit does not
change the behaviour.
> mon: honour mon_docker_net_host option

- roles/ceph-common/tasks/installs/install_redhat_packages.yml
- roles/ceph-common/tasks/installs/install_suse_packages.yml
During 226f80c22bf61a7e8f00f4cca5f35eda67280250 only Debian package
installs had the correct state set to ensure packages were upgraded when
the "upgrade_ceph_packages" var was set to true.
Signed-off-by: Andy McCrae <andy.mccrae@gmail.com>
> Fix package state for upgrades on SuSE/RHEL

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
Refers to #2697 
This change creates a copy of `ceph.conf` in ansible server.
Room for improvement:  a toggle flag to control this behavior.
@leseb What do you think?
Signed-off-by: Ha Phan <thanhha.work@gmail.com>
> Generate a copy of ceph.conf locally

- roles/ceph-mon/tasks/deploy_monitors.yml
Minor fix so that initial keyring can be generated using python3.
Signed-off-by: Ha Phan <thanhha.work@gmail.com>
> ceph-mon: Generate initial keyring

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/pre_requisite.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-fetch-keys/tasks/main.yml
- roles/ceph-iscsi-gw/tasks/common.yml
- roles/ceph-mds/tasks/common.yml
- roles/ceph-mgr/tasks/common.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-nfs/tasks/common.yml
- roles/ceph-osd/tasks/common.yml
- roles/ceph-rbd-mirror/tasks/common.yml
- roles/ceph-rbd-mirror/tasks/pre_requisite.yml
- roles/ceph-rgw/tasks/common.yml
Add `keyring_permissions` variable to control permissions for keyring
files in `/etc/ceph`. Default value is the same as it was (0600),
but this variable allows user to override it (f.e. set it to 0640).
Rationale: We are configuring a monitoring for Ceph. It runs under
a separate user (telegraf), but this user is included into the ceph
group. To have access to the admin keyring it need to have
/etc/ceph/client.admin.keyring to be at least rw-r----- (0640).
I added a variable into ceph-defaults with the same value as current
value in all related tasks.  This will allow to override it through variable
in the inventory/group_vars/host_vars.
> Add ceph_keyring_permissions var to set permissions for keyring files

- plugins/actions/_v2_config_template.py
Some fixes have gone into
git.openstack.org/openstack/ansible-config_template to deal with a few
bugs we have run into.
This PR brings the ceph-ansible config_template version up to the same
as the ansible-config_template openstack repo.
Closes: #2742
Signed-off-by: Andy McCrae <andy.mccrae@gmail.com>
> Sync config_template with upstream

- .mergify.yml
We know a Signed-off-by check inside our pipeline so this bot is not
needed anymore.
> [skip ci] ci: remove DCO

- tests/conftest.py
On stable-3.0 we can't test iscsi-gw nodes on jewel because it's not
implemented yet.
> tests: skip iscsi-gw nodes on jewel

- roles/ceph-client/tasks/create_users_keys.yml
The container runs for 300 sec, then dies and removes itself thanks to
the '--rm' option, so there is no point of removing it. Also this is
causing failure under some circonstances.
Closing: https://bugzilla.redhat.com/show_bug.cgi?id=1568157
> ceph-client: do not kill the dummy container

- infrastructure-playbooks/rolling_update.yml
This change moves ceph-mgr upgrades to using ceph-key library.
Fixes: #2758
Signed-off-by: Vishal Kanaujia <vishal.kanaujia@flipkart.com>
> Rolling upgrades: Migrate to ceph-key module

- roles/ceph-mgr/tasks/main.yml
The data structure has slightly changed on mimic.
Prior to mimic, it used to be:
```
{
"enabled_modules": [
"status"
],
"disabled_modules": [
"balancer",
"dashboard",
"influx",
"localpool",
"prometheus",
"restful",
"selftest",
"zabbix"
]
}
```
From mimic it looks like this:
```
{
"enabled_modules": [
"status"
],
"disabled_modules": [
{
"name": "balancer",
"can_run": true,
"error_string": ""
},
{
"name": "dashboard",
"can_run": true,
"error_string": ""
}
]
}
```
This means we can't simply check if `item` is in `item in
_ceph_mgr_modules.disabled_modules`
the idea here is to use filter `map(attribute='name')` to build a list
when deploying mimic.
Fixes: #2766
> mgr: fix enabling of mgr module on mimic

- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
We forgot to add mgr_group_name when checking for the mon repo, thus the
conditional on the next task was failing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1598185
> ceph-common: fix rhcs condition

- roles/ceph-config/templates/ceph.conf.j2
The container image recently merged both cluster and mon log into a
single stream. Following this, we now see this warning coming from the
container image:
2018-06-19 13:44:01.542990 7ff75b024700  1 mon.vm02@1(peon).log
v57928205 unable to write to '/var/log/ceph/ceph.log' for channel
'cluster': (2) No such file or directory
So we now tell the mon to not log cluster log on the filesystem.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1591771
> ceph-config: do not log cluster log on container

- tests/conftest.py
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
prior mimic, the data structure returned by `ceph -s -f json` used to
gather information about rbd-mirror daemons looked like below:
```
"servicemap": {
"epoch": 8,
"modified": "2018-07-05 13:21:06.207483",
"services": {
"rbd-mirror": {
"daemons": {
"summary": "",
"ceph-nano-luminous-faa32aebf00b": {
"start_epoch": 8,
"start_stamp": "2018-07-05 13:21:04.668450",
"gid": 14107,
"addr": "172.17.0.2:0/2229952892",
"metadata": {
"arch": "x86_64",
"ceph_version": "ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)",
"cpu": "Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz",
"distro": "centos",
"distro_description": "CentOS Linux 7 (Core)",
"distro_version": "7",
"hostname": "ceph-nano-luminous-faa32aebf00b",
"instance_id": "14107",
"kernel_description": "#1 SMP Wed Mar 14 …
```
> tests: add mimic support for test_rbd_mirror_is_up()

- tests/requirements.txt
- tests/requirements2.4.txt
- tests/requirements2.5.txt
- tox.ini
We should test ceph-ansible against the latest ansible stable version on
master.
This commit also remove the pinning to 1.7.1 version of testinfra
because ansible 2.5 requires a newer version.
> tests: refact ci testing master

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- rundep.sample
As of Kraken, the journal code does not use the hdparm command anymore
so we can remove it from our package dependency list.
Fixes: https://github.com/ceph/ceph-ansible/issues/1402
(cherry picked from commit f6910efa24389c264062963b2054c7cd29ffebb3)
> common: remove hdparm

- tests/functional/tests/osd/test_osds.py
We must initialize `children` variable in `_get_osd_id_from_host()`,
otherwise, if for any reason the deployment has failed and result with
an osd host with no OSD registered, we won't enter in the condition,
therefore, `children` is never set and the function tries to return
something undefined.
Typical error:
```
E       UnboundLocalError: local variable 'children' referenced before assignment
```
Fixes: #2860
> tests: fix `_get_osd_id_from_host()` in TestOSDs()

- infrastructure-playbooks/purge-docker-cluster.yml
- roles/ceph-mon/tasks/docker/start_docker_monitor.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-restapi/tasks/docker/start_docker_restapi.yml
As of ansible 2.4, `docker` module has been removed (was deprecated
since ansible 2.1).
We must switch to `docker_container` instead.
See: https://docs.ansible.com/ansible/latest/modules/docker_module.html#docker-module
> common: switch from docker module to docker_container

- roles/ceph-mgr/tasks/main.yml
Follow up on #2784
We must check in the generated fact `_disabled_ceph_mgr_modules` to
enable disabled mgr module.
Otherwise, this task will be skipped because it's not comparing the
right list.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1600155
> mgr: fix condition to add modules to ceph-mgr

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Since `V2.6-stable` is available and has packages for `mimic`, let's
update this default value accordingly so nfs nodes can be deployed with
mimic.
> nfs: change default stable branch for nfs-ganesha repo

- tox.ini
since no latest-bis-jewel exists, it's using latest-bis which points to
ceph mimic. In our testing, using it for idempotency/handlers tests
means upgrading from jewel to mimic which is not what we want do.
> tests: add latest-bis-jewel for jewel tests

- docs/source/index.rst
- stable-2.1 and stable-2.2 shouldn't be referenced anymore.
- add stable-3.1 branch reference
- update the differents ansible version supported
> [skip ci] docs: update doc

- roles/ceph-validate/tasks/check_devices.yml
- roles/ceph-validate/tasks/main.yml
Do not run device validation on every hosts, only on OSD nodes.
> validate: only run osd test on osd node

- tests/requirements.txt
- tests/requirements2.2.txt
- tests/requirements2.5.txt
- tox.ini
In addition to ceph/ceph-build#1082
Let's set the ansible version in each ceph-ansible branch's respective
requirements.txt.
> tests: stop hardcoding ansible version (stable-3.1)

- tests/requirements.txt
- tests/requirements2.2.txt
- tox.ini
In addition to ceph/ceph-build#1082
Let's set the ansible version in each ceph-ansible branch's respective
requirements.txt.
> tests: stop hardcoding ansible version (stable-3.0)

- tests/conftest.py
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
- tox.ini
`test_rbd_mirror_is_up()` is failing on update scenarios because it
assumes the `ceph_stable_release` is still set to the value of the
original ceph release, it means it won't enter in the right part of the
condition and fails.
> tests: support update scenarios in test_rbd_mirror_is_up()

- roles/ceph-validate/tasks/check_system.yml
- tests/requirements.txt
Ansible 2.4 is currently end-of-life.
Ansible 2.5 will go end-of-life after Ansible 2.7 is released.
Fixes: #2901
> tests: test master against ansible 2.6

- roles/ceph-common/tasks/checks/check_system.yml
Make sure we fail if the Ansible version is >= 2.5, stable-3.0 only
support Ansible between 2.3.x and 2.4.x.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1598314
> common: enforce ansible version check

- roles/ceph-nfs/tasks/start_nfs.yml
When distributing ceph-nfs role, creation of rados index object
fails as it assumes availability of client.admin locally.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1607970
> Run creation of empty rados index object to first monitor

- roles/ceph-rgw/tasks/docker/container_env_facts.yml
In containerized deployments we now inherite from the
radosgw_civetweb_options options when bootstrapping the container.
Depends on https://github.com/ceph/ceph-container/pull/1126
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1582411
> rgw: add more config option for civetweb frontend

- site.yml.sample
Check `systempython2.stat` before `systempython2.stat.exists`.
Without this change, in the case that python2 is not installed, the `stat`
task fails without defining `systempython2.stat`. It leads that the next
installation tasks fail because of undefined `systempython2.stat`.
An example error output (edited for readability):
```
TASK [check for python2] ***********************************************
Wednesday 25 July 2018  14:52:47 +0900 (0:00:00.182)       0:00:00.182 *
fatal: [ceph-osd1.vlan221.vtj]: FAILED! => {
"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/python: not
found\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 127}
...ignoring
TASK [install python2 for debian based systems] ************************
Wednesday 25 July 2018  14:51:00 +0900 (0:00:01.742) …
```
> site.yml.sample: fix install python2

- roles/ceph-client/tasks/pre_requisite.yml
This task would be run on both containerized *and* non containerized
deployment.
Let's have a proper title to avoid confusion.
> client: fix an incorrect title in a task

- site-docker.yml.sample
- site.yml.sample
We now show the output of 'ceph -s'. Example output below:
```
TASK [display post install message] **********************************************************************************************************************************************************************************************************
ok: [localhost] => {
"msg": [
"  cluster:",
"    id:     753212df-f32a-4cc9-a097-2db6fe89a251",
"    health: HEALTH_OK",
" ",
"  services:",
"    mon: 1 daemons, quorum ceph-nano-lul-faa32aebf00b",
"    mgr: ceph-nano-lul-faa32aebf00b(active)",
"    osd: 1 osds: 1 up, 1 in",
" ",
"  data:",
"    pools:   4 pools, 32 pgs",
"    objects: 224 objects, 2546 bytes",
"    usage:   1027 MB used, 9212 MB / 10240 MB avail",
"    pgs:     32 active+clean",
" "
]
}
```
Closes: …
> site: report ceph -s status at the end of the deployment

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
The container runs with --rm which means it will be deleted by Docker
when exiting. Also 'docker rm -f' is not idempotent and returns 1 if the
container does not exist.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1609007
> osd: do not remove expose_partition container

- site-docker.yml.sample
- site.yml.sample
ceph-rest-api binary has been removed in mimic so we cannot deploy it
anymore. We just keep the role and the compability for existing users.
> restapi: disable it when ceph version > luminous

- library/igw_purge.py
- roles/ceph-iscsi-gw/library/igw_purge.py
We were not passing in the ceph conf info into the rbd image removal
command, so if the clustername was not the default igw purge would fail
due to the rbd rm command failing.
This just fixes the bug by passing in the ceph conf info which has the
clustername to use.
This fixes Red Hat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1601949
Signed-off-by: Mike Christie <mchristi@redhat.com>
> igw: fix image removal during purge

- roles/ceph-config/templates/ceph.conf.j2
This was introduced by
https://github.com/ceph/ceph/commit/59ee2e8d3b14511e8d07ef8325ac8ca96e051784
and made our socket checks impossible to run. The PID could be found,
but the cctid cannot.
This happens during upgrade to mimic and on cluster running on mimic.
So let's force the admin socket the way it was so we can properly check
for existing instances also the line $cluster-$name.$pid.$cctid.asok
is only needed when running multiple instances of the same daemon,
thing ceph-ansible cannot do at the time of writing
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1610220
> [skip ci] config: enforce socket name

- roles/ceph-defaults/templates/restart_mds_daemon.sh.j2
- roles/ceph-defaults/templates/restart_mgr_daemon.sh.j2
- roles/ceph-defaults/templates/restart_mon_daemon.sh.j2
- roles/ceph-defaults/templates/restart_rbd_mirror_daemon.sh.j2
- roles/ceph-defaults/templates/restart_rgw_daemon.sh.j2
This commit ensures we are backward compatible with fqdn deployments.
Since ceph-container enforces deployment to be done with shortname, we
must keep backward compatibility with clusters already deployed with
fqdn configuration
> defaults: backward compatibility with fqdn deployments

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Install ceph-iscsi-cli in order to provide the `gwcli` command tool.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1602785
> iscsigw: install ceph-iscsi-cli package

- roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
OSDs can have numbers >99 which means regular expression in `restart_osd_daemon.sh` should catch OSD number of any non-zero length.
This solves https://github.com/ceph/ceph-ansible/issues/2964
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1612853
> osd: Fixed bug in regular expression in restart_osd_daemon.sh

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
We were missing an option so let's add it back.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1519835
> [skip ci] Resync rhcs_edits.txt

- roles/ceph-common/tasks/installs/install_debian_packages.yml
- roles/ceph-common/tasks/installs/install_debian_rhcs_packages.yml
When we deploy a Jewel cluster on Ubuntu with `ceph_test: True`, we're unable to upgrade that cluster to Luminous.
`apt-get install ceph-common` fails to upgrade to luminous if a jewel `ceph-test` package is installed:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
ceph-base : Breaks: ceph-test (< 12.2.2-14) but 10.2.11-1xenial is to be installed
ceph-mon : Breaks: ceph-test (< 12.2.2-14) but 10.2.11-1xenial is to be installed
```
In ceph-ansible master, we resolve this whole class of problem by …
> [skip ci] common: upgrade/install ceph-test deb first

- roles/ceph-osd/tasks/build_devices.yml
rolling_update relies on the list of devices when performing the restart
of the OSDs. The task that is builind the devices list out of the
ansible_devices dict only runs when there are no partitions on the
drives. However during an upgrade the OSD are already configured, they
have been prepared and have partitions so this task won't run and thus
the devices list will be empty, skipping the restart during
rolling_update. We now run the same task under different requirements
when rolling_update is true and build a list when:
* osd_auto_discovery is true
* rolling_update is true
* ansible_devices exists
* no dm/lv are part of the discovery
* the device is not removable
* the device has more than 1 sector
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1613626
Signed-off-by: Sébastien Han …
> osd: generate device list for osd_auto_discovery on rolling_update

- roles/ceph-mon/tasks/calamari.yml
If calamari is already installed and ceph has been upgraded to a higher
version the initialisation will fail later. So if we detect the
calamari-server is too old compare to ceph_rhcs_version we try to update
it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1601755
> mon: fix calamari initialisation

- roles/ceph-defaults/tasks/facts.yml
The ceph_uid is also '167' on SUSE systems so extend the existing task.
Signed-off-by: Markos Chandras <mchandras@suse.de>
> roles: ceph-defaults: Set ceph_uid on SUSE distributions

- infrastructure-playbooks/purge-cluster.yml
In some case, use may mount a partition to /var/lib/ceph, and umount
it will be failure and no need to do so too.
> Use /var/lib/ceph/osd folder to filter osd mount point

- roles/ceph-defaults/tasks/facts.yml
Since commit f422efb1d6b56ce56a7d39a21736a471e4ed357 ("config: ensure
rgw section has the correct name") we observe the following failures in
new Ceph deployment with OpenStack-Ansible
fatal: [aio1_ceph-rgw_container-fc588f0a]: FAILED! => {"changed": false,
"cmd": "ceph --cluster ceph -s -f json", "msg": "[Errno 2] No such file
or directory"
The problem is because of the following two problems:
- The commit added the following conditional: 'ansible_hostname !=
ansible_fqdn' which for a properly configured system it evaluates to
'True' since ansible_hostname is not supposed to return an FQDN.
- The task executes 'ceph' but at this point no package installation has
happened. Packages are normally installed in the 'ceph-common' role
which runs after the 'ceph-defaults' one.
As such, we can …
> roles: ceph-defaults: Handle missing 'ceph' binary failures

- infrastructure-playbooks/take-over-existing-cluster.yml
We were using var_files long ago when default variables were not in
ceph-defaults, now the role exists this is not need. Moreover having
these two var files added:
- roles/ceph-defaults/defaults/main.yml
- group_vars/all.yml
Will create collision and override necessary variables.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1555305
> [skip ci] take-over-existing-cluster: do not call var_files

- infrastructure-playbooks/purge-iscsi-gateways.yml
- infrastructure-playbooks/rolling_update.yml
- site-docker.yml.sample
- site.yml.sample
Recently we renamed the group_name for iscsi iscsigws where previously
it was named iscsi-gws. Existing deployments with a host file section
with iscsi-gws must continue to work.
This commit adds the old group name as a backoward compatility, no error
from Ansible should be expected, if the hostgroup is not found nothing
is played.
Close: https://bugzilla.redhat.com/show_bug.cgi?id=1619167
> iscsi group name preserve backward compatibility

- roles/ceph-common/tasks/facts_mon_fsid.yml
- roles/ceph-common/tasks/main.yml
- roles/ceph-defaults/handlers/main.yml
- roles/ceph-defaults/tasks/facts.yml
A couple if things were wrong in the initial commit:
* ceph_release_num[ceph_release] >= ceph_release_num['luminous'] will
never work since the ceph_release fact is set in the roles after. So
either ceph-common or ceph-docker-common set it
* we can easily re-use the initial command to check if a cluster is
running, it's more elegant than running it twice.
* set the fact rgw_hostname on rgw nodes only
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1618678
> defaults: fix rgw_hostname

- site-docker.yml.sample
- tests/functional/centos/7/docker-collocation/vagrant_variables.yml
- tests/functional/centos/7/ooo-collocation/vagrant_variables.yml
There is no point of using hosts running on atomic AND centos hosts. So
let's run containerized scenarios on Atomic only.
> ci: stop using different images on the same run

- site-docker.yml.sample
- site.yml.sample
Same problem again... ceph_release_num[ceph_release] is only set in
ceph-docker-common/common roles so putting the condition on that role
will never work. Removing the condition.
The downside of this is we will be installing packages and then skip the
role on the node.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1622210
> sites: fix conditonnal

- roles/ceph-client/tasks/create_users_keys.yml
The dummy client container currently wont work on ppc64le hosts.
This PR creates a filtered client group that contains only hosts
that are not ppc64le - which can then be the group to run the
dummy container against.
This is for the specific case of a containerized_deployment where
there is a mixture of non-ppc64le hosts and ppc64le hosts.
Currently ppc64le is not supported with Ceph server components.
Signed-off-by: Andy McCrae <andy.mccrae@gmail.com>
> Dont run client dummy container on ppc64le hosts

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
Sometime /var/lib/ceph is mounted on a device so we won't be able to
remove it (device busy) so let's remove its content only.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1615872
> purge: only purge /var/lib/ceph content

- roles/ceph-rgw/tasks/start_radosgw.yml
If the ceph-radosgw target is not enabled, then enabling the
ceph-radosgw@ service has no effect since nothing will pull
it on the next reboot. As such, we need to ensure that the
target is enabled.
Signed-off-by: Markos Chandras <mchandras@suse.de>
> roles: ceph-rgw: Enable the ceph-radosgw target

- roles/ceph-nfs/tasks/start_nfs.yml
When ceph-nfs is deployed containerized and ceph-common is not
installed on the host the start_nfs task fails because the rados
command is missing on the host.
Run rados commands from a ceph container instead so that
they will succeed.
Signed-off-by: Tom Barron <tpb@dyncloud.net>
> ceph-nfs: run rados cmds in container

- roles/ceph-mon/templates/ceph-mon.service.j2
This command line is not supported.
According to official documentation:
```
Note that shell command lines are not directly supported.
If shell command lines are to be used,
they need to be passed explicitly to a shell implementation of some kind.
```
We must run this using /bin/sh instead.
> mon: fix `ExecStartPre` option in systemd unit file

- docs/source/osds/scenarios.rst
- group_vars/osds.yml.sample
- library/ceph_volume.py
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/scenarios/lvm-batch.yml
- tests/conftest.py
If this is set to anything other than the default value of -1 then the
--osds-per-device flag will be used by the batch command to define how
many osds will be created per device.
> ceph_volume: adds the osds_per_device parameter

- docs/tox.ini
using sphinx 1.8.0 breaks our doc test CI job.
Typical error:
```
Exception occurred:
File
"/home/jenkins-build/build/workspace/ceph-ansible-docs-pull-requests/docs/.tox/docs/lib/python2.7/site-packages/sphinx/highlighting.py",  line 26, in <module>
from sphinx.ext import doctest
SyntaxError: unqualified exec is not allowed in function 'run' it contains a nested function with free variables (doctest.py, line 97)
```
See: https://github.com/sphinx-doc/sphinx/issues/5417
Pinning to 1.7.9 to fix our CI.
> tests: pin sphinx version to 1.7.9

- roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
As of rhel 7.6, it has been decided it doesn't make sense to confine
`ganesha_t` anymore. It means this domain won't exist anymore.
Let's add a `failed_when: false` in order to make the deployment not
failing when trying to run this command.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1626070
> nfs: ignore error on semanage command for ganesha_t

- docs/source/osds/scenarios.rst
As of e3820a2 the creation of logical volumes is now supported by ceph-ansible.
> doc: update lvm doc

- infrastructure-playbooks/shrink-osd.yml
- tests/functional/centos/7/shrink_osd/hosts
ce1dd8d introduced the purge osd on containers but it was incorrect.
`resolve parent device` and `zap ceph osd disks` tasks must be delegated to
their respective OSD nodes.
Indeed, they were run on the ansible node, it means it was trying to
resolve parent devices from this node where it should be done on OSD
nodes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1612095
> shrink-osd: fix purge osd on containerized deployment

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
The commit:
commit 1164cdc002cccb9dc1c6f10fb6b4370eafda3c4b
Author: Guillaume Abrioux <gabrioux@redhat.com>
Date:   Thu Aug 2 11:58:47 2018 +0200
iscsigw: install ceph-iscsi-cli package
installs the cli package but does not start and enable the
rbd-target-api daemon needed for gwcli to communicate with the igw
nodes. This patch just enables and starts it for the non-container
setup. The container setup is already doing this.
This fixes bz https://bugzilla.redhat.com/show_bug.cgi?id=1613963.
> igw: enable and start rbd-target-api

- tests/functional/centos/7/shrink_osd/hosts
b89cc1746 introduced a typo. This commit fixes it
(cherry picked from commit 3382c5226c8e6e974dee7be39392652a203bb280)
> tests: fix monitor_address for shrink_osd scenario

- infrastructure-playbooks/shrink-osd.yml
- site-docker.yml.sample
Once the OSD is destroyed we also have to purge the associated devices,
this means purging journal, db , wal partitions too.
This now works for container and non-container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572933
> shrink-osd: purge dedicated devices

- roles/ceph-config/tasks/main.yml
This avoids errors when the osd scenario choosen does not require
setting devices or lvm_volumes. The default values for these are not
set because they exist in the ceph-osd role, not ceph-defaults.
> ceph-config: default devices and lvm_volumes when setting num_osds

- Vagrantfile
In case of an OpenStack "box", the Vagrantfile intend to check the
existence of os_networks and os_floating_ip_pool settings in
vagrant_variables.yml and pass them to the provider if they are set.
Due to two typos in the Vagrantfile this is not working as it checks the
wrong variable names.
This commit fixes the typos so these settings can be used.
Signed-off-by: Norbert Illés <illesnorbi@gmail.com>
> vagrantfile: fix references to OpenStack settings

- roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
After restarting each OSD, restart_osd_daemon.sh checks that the
cluster is in a good state before moving on to the next one. One of
the checks it does is that the number of pgs in the state
"active+clean" is equal to the total number of pgs in the cluster.
On large clusters (e.g. we have 173,696 pgs), it is likely that at
least one pg will be scrubbing and/or deep-scrubbing at any one
time. These pgs are in state "active+clean+scrubbing" or
"active+clean+scrubbing+deep", so the script was erroneously not
including them in the "good" count.
Fix this by summing the total of pgs in these 3 good states, and
comparing that to the num_pgs in pgmap; do this as an integer
comparison.
(could this be backported to at least stable-3.0 please?)
Closes: #2008
Signed-off-by: Matthew Vernon …
> restart_osd_daemon.sh.j2 - consider scrubbing pgs as OK

- roles/ceph-config/templates/ceph.conf.j2
We need to look for ceph_release when comparing with release names,
not ceph_version.
> Fix version check in ceph.conf template

- tests/functional/centos/7/ooo-collocation/hosts
get more coverage by adding an RGW daemon collocated on osd0.
We've missed a bug in the past which could have been caught earlier in
the CI.
Let's add this additional daemon in order to have a better coverage.
> tests: add an RGW node on osd0 for ooo-collocation

- docs/source/index.rst
List the osd_scenarios and install options that are validated by the
ceph-validate role in the documentation.
> docs: supported validation by the ceph-validate role

- infrastructure-playbooks/rolling_update.yml
In cluster with a large number of PGs, it can be expected some of them
scrubbing, it's a normal operation.
Preventing from scrubbing operation force to set noscrub flag before a
rolling update which is a problem because it pauses an important data
integrity operation until the end of the rolling upgrade.
This commit allows an upgrade even while PGs are scrubbing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1616066
> upgrade: consider all 'active+clean' states as valid pgs

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
38dc20e74b89c1833d45f677f405fe758fd10c04 introduced a bug in the purge
playbooks because using `*` in `command` module doesn't work.
`/var/lib/ceph/*` files are not purged, it means there is a leftover.
When trying to redeploy a cluster, it failed because monitor daemon was
detecting existing keyring, therefore, it assumed a cluster already
existed.
Typical error (from container output):
```
Sep 26 13:18:16 mon0 docker[31316]: 2018-09-26 13:18:16  /entrypoint.sh: Existing mon, trying to rejoin cluster...
Sep 26 13:18:16 mon0 docker[31316]: 2018-09-26 13:18:16.9323937f15b0d74700 -1 auth: unable to find a keyring on /etc/ceph/test.client.admin.keyring,/etc/ceph/test.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,:(2) No such file or directory
Sep 26 13:18:23 mon0 docker[31316]: 2018-09-26 …
```
> purge: actually remove of /var/lib/ceph/*

- infrastructure-playbooks/purge-cluster.yml
fix: https://github.com/ceph/ceph-ansible/issues/3166
Signed-off-by: wumingqiao <wumingqiao@beyondcent.com>
> purge-cluster: recursively remove ceph-related files, symlinks and directories under /etc/systemd/system.

- docs/source/osds/scenarios.rst
Updates the format of the examples, and extracts the values needed into different sections vs. trying to provide examples for all the different permutations.
@dmick @zmc would appreciate any feedback on these changes, happy to accommodate further.
> doc: redo lvm scenario documentation, improved wording and config descriptions

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/misc/ntp_debian.yml
- roles/ceph-common/tasks/misc/ntp_rpm.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
Allow user to choose between timesyncd, chronyd and ntpd
Installation will default to timesyncd since it is distributed as
part of the systemd installation for most distros.
Fixes issue #3086 on Github
Signed off by: Benjamin Cherian <benjamin_cherian@amat.com>
> Add support for different NTP daemons

- roles/ceph-config/templates/ceph.conf.j2
`monitor_address_block` should be read from hostvars[host] instead of
current node being played.
eg:
Let's assume we have:
```
[mons]
ceph-mon0 monitor_address=192.168.1.10
ceph-mon1 monitor_interface=eth1
ceph-mon2 monitor_address_block=192.168.1.0/24
```
the ceph.conf generation task will end up with:
```
fatal: [ceph-mon0]: FAILED! => {}
MSG:
'ansible.vars.hostvars.HostVarsVars object' has no attribute u'ansible_interface'
```
the reason is that it will assume `monitor_address_block` isn't defined even on
ceph-mon2 because looking for `monitor_address_block` instead of
`hostvars[host]['monitor_address_block']`, therefore it enters in the condition as default value:
```
{%- else -%}
{% set interface = 'ansible_' + (monitor_interface | replace('-', '_')) %}
{% if ip_version == 'ipv4' -%} …
```
> config: look up for monitor_address_block in hostvars

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Similar to c13a3c3 we must allow scrubbing when running this playbook.
In cluster with a large number of PGs, it can be expected some of them
scrubbing, it's a normal operation.
Preventing from scrubbing operation force to set noscrub flag.
This commit allows to switch from non containerized to containerized
environment even while PGs are scrubbing.
Closes: #3182
> switch: support migration when cluster is scrubbing

- infrastructure-playbooks/rolling_update.yml
since the introduction of ceph-handler, it has to be added in
rolling_update playbook as well
> rolling_update: add ceph-handler role

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
We give more assistance to consultants deplying by setting the registry
and the image name.
> [skip ci] rhcs: add helpers for the containerized deployment

- site-docker.yml.sample
- site.yml.sample
We need to play cpeh-defaults before showing that task so if the clsuter
name is 'ceph' then we get the default value from 'cluster' based on the
content of cpeh-defaults.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1636962
> site: use ceph-default to show cluster state

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- library/ceph_volume.py
- roles/ceph-config/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-osd/tasks/scenarios/lvm-batch.yml
- tests/functional/centos/7/lvm-batch/group_vars/all
This depends on https://github.com/ceph/ceph/pull/24404
As well as making the ``ceph_volume`` module idempotent when the ``action`` is ``batch``, this adds support for ``journal_size`` and ``block_db_size`` which allows us to get an accurate number of OSDs that will be created in ``ceph-config`` before a config file is written. The new ``ceph-volume`` flags ``--journal-size`` and ``--block-db-size`` was added in https://github.com/ceph/ceph/pull/24201 and is still unreleased.
> ceph-volume: makes the lvm scenario idempotent when using the simple configuration

- roles/ceph-validate/tasks/main.yml
These checks will never pass unless ceph_stable_release is passed and
ceph-defaults is run before ceph-validate. Additionally, we don't want
to support deploying jewel upstream at ceph-ansible master.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1637537
> ceph-validate: remove versions checks for bluestore and lvm scenario

- tests/functional/lvm_setup.yml
This fixes broken ceph-volume tests caused because lvm2 is no longer pre-installed in its images.
[vagrant@osd0 ~]$ which lvs
/usr/bin/which: no lvs in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin)
[vagrant@osd0 ~]$ sudo su
[root@osd0 vagrant]# which lvs
/usr/bin/which: no lvs in (/sbin:/bin:/usr/sbin:/usr/bin)
[root@osd0 vagrant]# lvm
bash: lvm: command not found
[root@osd0 vagrant]# yum provides lvs
Loaded plugins: fastestmirror
Determining fastest mirrors
* base: mirror.vcu.edu
* extras: www.gtlib.gatech.edu
* updates: mirror.siena.edu
base                                                                                                                                                       | 3.6 kB  00:00:00
extras …
> tests: install lvm2 before setting up ceph-volume/LVM tests

- docs/source/index.rst
'radosgw_interface' or 'radosgw_address' config option does
not need to be set for all ceph-ansible deployments.
Closes: https://github.com/ceph/ceph-ansible/issues/3143
Signed-off-by: Ramana Raja <rraja@redhat.com>
> docs: correct mandatory config options

- tests/functional/lvm_setup.yml
not gathering fact causes `package` module to fail because it needs to
detect which OS we are running on to select the right package manager.
> tests: fix lvm2 setup issue

- infrastructure-playbooks/rolling_update.yml
Cherry picking two commits from master to allow rolling updates during PG scrubbing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1616066
> backport: allow rolling updates during PG scrubbing

- tests/functional/tests/osd/test_osds.py
The CI is still running ceph-disk tests upstream. So until
https://github.com/ceph/ceph-ansible/pull/3187 is merged nothing will
pass anymore.
> test: fix docker test for lvm

- infrastructure-playbooks/rolling_update.yml
- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-fetch-keys/tasks/main.yml
- roles/ceph-handler/templates/restart_rbd_mirror_daemon.sh.j2
- roles/ceph-infra/tasks/configure_firewall.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-mgr/tasks/main.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/crush_rules.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-mon/tasks/docker/copy_configs.yml
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-osd/tasks/ceph_disk_cli_options_facts.yml
- roles/ceph-osd/tasks/openstack_config.yml
- roles/ceph-rbd-mirror/tasks/common.yml
- roles/ceph-rbd-mirror/tasks/docker/copy_configs.yml
- roles/ceph-rbd-mirror/tasks/pre_requisite.yml
- roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
- roles/ceph-rgw/tasks/main.yml
- site-docker.yml.sample
- site.yml.sample
- tests/conftest.py
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
- tests/functional/tests/rgw/test_rgw.py
- tox.ini
As of now, we should no longer support Jewel in ceph-ansible.
The latest ceph-ansible release supporting Jewel is `stable-3.1`.
> remove jewel support

- roles/ceph-handler/handlers/main.yml
`ceph_osd_container_stat` might not be set on other osd node.
We must ensure we are on the last node before trying to evaluate
`ceph_osd_container_stat`.
> handler: fix osd containers handler

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-defaults/handlers/main.yml
The current regex had a limitation of 99 OSDs, now this limit has been
removed and regardless the number of OSDs they will all be collected.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1630430
> Manual backport of #3171 in stable-3.1

- roles/ceph-docker-common/tasks/pre_requisites/debian_prerequisites.yml
Signed-off-by: Nan Li <herbert.nan@linaro.org>
> docker-ce is used in aarch64 instead of docker engine

- docs/source/osds/scenarios.rst
since dc3319c3c4e2fb58cb1b5e6c60f165ed28260dc8 this should be reflected
in the doc.
> doc: update default osd_objectstore value

- contrib/snapshot_vms.sh
This script is still 'work in progress' but could be used to make
snapshot of Libvirt VMs.
This can save some times when deploying again and again.
> [skip ci] contrib: add a bash script to snapshort libvirt vms

- docs/source/installation/methods.rst
- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Liberty is no longer available in the UCA. The last available release there
is currently Queens.
Signed-off-by: Christian Berendt <berendt@betacloud-solutions.de>
> [skip ci] ceph-defaults: set ceph_stable_openstack_release_uca to queens

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-docker-common/tasks/main.yml
Currently a throw-away container is built to run ceph client
commands to setup users, pools & auth keys. This utilises
the same base ceph container which has all the ceph services
inside it.
This PR allows the use of a separate container if the deployer
wishes - but defaults to use the same full ceph container.
This can be used for different architectures or distributions,
which may support the the Ceph client, but not Ceph server,
and allows the deployer to build and specify a separate client
container if need be.
Signed-off-by: Andy McCrae <andy.mccrae@gmail.com>
> Add ability to use a different client container

- infrastructure-playbooks/gather-ceph-logs.yml
Add a gather-ceph-logs.yml which will log onto all the machines from
your inventory and will gather ceph logs. This is not intended to work
on containerized environments since the logs are stored in journald.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1582280
> [skip ci] infra: add a gather-ceph-logs.yml playbook

- plugins/actions/validate.py
If the version of python-notario is < 0.0.13 an error message is given
like "TypeError: validate() got an unexpected keyword argument
'defined_keys'", which is not helpful in figuring
out you've got an incorrect version of python-notario.
This check will avoid that situation by telling the user that they need
to upgrade python-notario before they hit that error.
> validate: check the version of python-notario

- infrastructure-playbooks/rolling_update.yml
CLusters that were deployed using 'mon_use_fqdn' have a different unit
name, so during the upgrade this must be used otherwise the upgrade will
fail, looking for a unit that does not exist.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1597516
> rolling_update: fix upgrade when using fqdn

- roles/ceph-infra/tasks/configure_firewall.yml
we ensure that firewalld is installed and running before adding any
rule. This has no sense anymore not to reload firewalld once the rule
are added.
> ceph-infra: reload firewall after rules are added

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/iscsigws.yml.sample
- group_vars/rgws.yml.sample
- group_vars/rhcs.yml.sample
ee2d52d33df2a311cdf0ff62abd353fccb3affbc missed this sync between
ceph-defaults/defaults/main.yml and group_vars/all.yml.sampl
> resync group_vars/*.sample files

- group_vars/iscsigws.yml.sample
- group_vars/mdss.yml.sample
- group_vars/mgrs.yml.sample
- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- group_vars/rbdmirrors.yml.sample
- group_vars/rgws.yml.sample
- roles/ceph-iscsi-gw/defaults/main.yml
- roles/ceph-mds/defaults/main.yml
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mon/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
- roles/ceph-rbd-mirror/defaults/main.yml
- roles/ceph-rgw/defaults/main.yml
Since we do not have enough data to put valid upper bounds for the memory
usage of these daemons, do not put artificial limits by default. This will
help us avoid failures like OOM kills due to low default values.
Whenever required, these limits can be manually enforced by the user.
More details in
https://bugzilla.redhat.com/show_bug.cgi?id=1638148
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1638148
Signed-off-by: Neha Ojha <nojha@redhat.com>
> roles: do not limit docker_memory_limit for various daemons

- library/ceph_volume.py
- library/test_ceph_volume.py
- tests/conftest.py
https://tracker.ceph.com/issues/36363 has been resolved and the patch
has been backported to luminous and mimic so let's enable the container
support.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1541415
> ceph_volume: add container support for batch

- library/ceph_volume.py
osds-per-device needs to be passed to run_command as a string.
Otherwise, expandvars method will try to iterate over an integer.
Signed-off-by: Maciej Naruszewicz <maciej.naruszewicz@intel.com>
> ceph-volume: fix TypeError exception when setting osds-per-device > 1

- ceph-ansible.spec.in
- docs/source/index.rst
- requirements.txt
- roles/ceph-validate/tasks/check_system.yml
- tests/requirements.txt
Let's test ceph-ansible master against ansible 2.7 to catch early any
potential issue with this ansible version.
Closes: #3148
> tests: test master against ansible 2.7

- group_vars/all.yml.sample
- group_vars/rgws.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-rgw/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
Move all rgw multisite variables in ceph-defaults so ceph-validate can
go through them.
> rgw: move multisite default variables in ceph-defaults

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-defaults/tasks/set_monitor_address.yml
- roles/ceph-defaults/tasks/set_radosgw_address.yml
- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
- roles/ceph-mon/tasks/docker/main.yml
- roles/ceph-mon/templates/ceph-mon.service.j2
using consecutive set_fact in the playbook instead of complex jinja syntax
makes ceph.conf.j2 more readable.
By the way, jinja can be painful to debug at some point.
> config: remove complex jinja logic in ceph.conf.j2

- roles/ceph-common/tasks/main.yml
The task was included by mistake while resolving a merge confict for
commit 8edbda96df6896d51703fcc250f562abb4011a2d. The task removed in
commit b3a71eeb08e9cdb2607ed60d724f387a0a24d3de.
Fixes: https://github.com/ceph/ceph-ansible/issues/3292
> remove task named "include ntp debian setup tasks"

- roles/ceph-common/handlers/main.yml
- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-common/tasks/installs/debian_dev_repository.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
The use of a handler meant that the cache would be updated at the very
end of the play, which doesn't work when adding a development repo and
trying to install right after it. This mostly reverts
53cdddf88699263763b36643565e5f846d9d13a8 without an actual `git revert`
because that caused other conflicts.
PR that caused the breakage: https://github.com/ceph/ceph-ansible/pull/3277
> ceph-common: update_cache whenever a new deb repo is added

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
For tasks using (Ansible) modules for package management utilities,
pass the list of packages to be installed instead of repeating the task
for each package. Using the latter manner of installing a list of
packages leads to a deprecation warning by ansible-playbook command.
Fixes: https://github.com/ceph/ceph-ansible/issues/3293
> don't loop over a task using package management modules

- plugins/actions/validate.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1630975
> validate: ceph_origin and containerized_deployment can not both be set

- infrastructure-playbooks/purge-iscsi-gateways.yml
When the iscsi purge playbook is run we stop the gw and api daemons but
not tcmu-runner which I forgot on the previous PR.
Fixes Red Hat BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1621255
Signed-off-by: Mike Christie <mchristi@redhat.com>
> igw: stop tcmu-runner on iscsi purge

- roles/ceph-validate/tasks/check_system.yml
Although this is not officially supported, this commit allows
`stable-3.2` to run against ansible 2.4.
This should ease the transition in RHOSP.
> validate: allow stable-3.2 to run with ansible 2.4

- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-infra/handlers/main.yml
if firewalld.service systemd unit is masked, the handler will fail when
trying to restart it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1650281
> infra: don't restart firewalld if unit is masked

- roles/ceph-client/tasks/create_users_keys.yml
cd1e4ee024ef400ded25e8c99948648ead3a0892 introduced a typo.
> client: fix a typo in create_users_keys.yml

- roles/ceph.ceph-container-common
This error was introduced in the recent refactor of ceph-docker-common
in https://github.com/ceph/ceph-ansible/pull/3251. However, the Ansible
galaxy linter is not happy about it and fails importing the role.
Removing this since it's not used anymore.
> [skip ci] ceph.ceph-container-common remove symlink

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
* The default value of osd_memory_target used by ceph is 4294967296 bytes,
so use the same as ceph-ansible default.
* Convert ansible_memtotal_mb to bytes to calculate osd_memory_target
Fixes bug in https://github.com/ceph/ceph-ansible/pull/3113
Signed-off-by: Neha Ojha <nojha@redhat.com>
> osd_memory_target: standardize unit and fix calculation

- plugins/actions/validate.py
"missing variable" errors introduced by #3058 would attempt to
be reported, but since the exception contained no "path" definition,
would cause a second exception in the Invalid exception handler.
Make the exception handler verify that any field it tries to use
exists, clean up its message formatting, and reduce the verbose
level to see the literal error from notario in case more goes
wrong in future.
Signed-off-by: Dan Mick <dan.mick@redhat.com>
> validate plugin: handle missing exception fields without traceback

- library/ceph_facts
Example "output":
```json
"rbd_images": {
"rbd-root-images": {
"base-debian-stretch": {
"info": {
"block_name_prefix": "rbd_data.1b14046b8b4567", 
"create_timestamp": "Mon Nov 19 20:38:01 2018", 
"features": [
"layering", 
"exclusive-lock", 
"object-map", 
"fast-diff", 
"deep-flatten"
], 
"flags": [], 
"format": 2, 
"name": "base-debian-stretch", 
"object_size": 4194304, 
"objects": 25600, 
"order": 22, 
"size": 107374182400
}, 
"status": {
"watchers": []
}
}
}
}
```
I only tested this on Ansible 2.2 and with my own config; it may not be very robust.
> [skip ci] Discover rbd facts.

- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-osd/tasks/start_osds.yml
If you use python3 based ansible then keys() returns a dict_keys object,
not a list of keys. This breaks the installation on such a system. Using
the list filter provides a more robust solution that should work on both
python2 and python3 based ansible. You can find some more information
about the issue, here:
https://github.com/ansible/ansible/issues/19514
> start_osds: Use list instead of keys

- roles/ceph-config/templates/ceph.conf.j2
ceph.conf doesn't accept float value.
Typical error seen:
```
$ sudo ceph daemon osd.2 config get osd_memory_target
Can't get admin socket path: unable to get conf option admin_socket for osd.2:
parse error setting 'osd_memory_target' to '7823740108,8' (strict_si_cast:
unit prefix not recognized)
```
This commit ensures the value inserted in ceph.conf will be an integer.
> config: convert _osd_memory_target to int

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
If we mask it we won't be able to start the OSD container since now the
osd container use the osd ID as a name such as: ceph-osd@0
Fixes the error:  Failed to execute operation: Cannot send after transport endpoint shutdown
> [skip ci] switch: do not mask systemd unit

- library/ceph_volume.py
- library/test_ceph_volume.py
- roles/ceph-osd/tasks/start_osds.yml
In order to be able to retrieve udev information, we must expose its
socket. As per, https://github.com/ceph/ceph/pull/25201 ceph-volume will
start consuming udev output.
> osd: expose udev into the container

- roles/ceph-handler/templates/restart_mds_daemon.sh.j2
- roles/ceph-handler/templates/restart_mgr_daemon.sh.j2
- roles/ceph-handler/templates/restart_mon_daemon.sh.j2
- roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
- roles/ceph-handler/templates/restart_rbd_mirror_daemon.sh.j2
- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
This will tremendously help debugging daemons that fail on restart by
showing the systemd unit logs.
> handler: show unit logs on error

- infrastructure-playbooks/rolling_update.yml
when upgrading from RHCS 2.5 to 3.2, it fails because the task `create
ceph mgr keyring(s) when mon is containerized` has a when condition
`inventory_hostname == groups[mon_group_name]|last`.
First, this is incorrect because `inventory_hostname` is referring to a
mgr node, it means this condition would have never been satisfied.
Then, this condition + `serial: 1` makes the mgr keyring creating skipped on
the first node. Further, the `ceph-mgr` role tries to copy the mgr
keyring (it's not aware we are running `serial: 1`) this leads to a
failure like the following:
```
TASK [ceph-mgr : copy ceph keyring(s) if needed] ******************************************************************************************************************************************************************************** …
```
> mgr: fix mgr keyring error on rolling_update

- tests/functional/fedora/29/container-podman/group_vars/all
- tests/functional/fedora/29/container-podman/group_vars/clients
- tox.ini
we must apply this playbook before deploying the secondary cluster.
Otherwise, there will be a mismatch between the two deployed cluster.
> tests: apply dev_setup on the secondary cluster for rgw_multisite

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- plugins/actions/validate.py
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-defaults/tasks/set_radosgw_address.yml
change default value of `radosgw_address` to keep consistency with
`monitor_address`.
Moreover, `ceph-validate` checks if the value is '0.0.0.0' to determine
if it has to run `check_eth_rgw.yml`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1600227
> validate: change default value for `radosgw_address`

- roles/ceph-osd/tasks/start_osds.yml
This commit
https://github.com/ceph/ceph-ansible/commit/4cc1506303739f13bb7a6e1022646ef90e004c90#diff-51bbe3572e46e3b219ad726da44b64ebL13
accidentally removed this check.
This is a must have for ceph-disk based containerized OSDs.
> osd: re-introduce disk_list check

- infrastructure-playbooks/rolling_update.yml
So we can avoid the following failure:
The conditional check 'hostvars[mon_host]['ansible_hostname'] in (ceph_health_raw.stdout | from_json)["quorum_names"] or hostvars[mon_host]['ansible_fqdn'] in (ceph_health_raw.stdout | from_json)["quorum_names"]
' failed. The error was: No JSON object could be decoded
We just need to set a default, the next iteration will have a more
complete json since the command won't fail.
> rolling_update: default ceph json output to empty dict

- roles/ceph-mon/tasks/docker/fetch_configs.yml
We don't want to fail on key that are not present since they will get
created after the mons are updated. They will be created by the task
"create potentially missing keys (rbd and rbd-mirror)".
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1650572
> rolling_update: do not fail on missing keys

- infrastructure-playbooks/rolling_update.yml
try to create the potentially missing keys only on monitors that are
actually running.
The current node being played is stopped before this task.
By the way, delegating the command on all nodes but the current node
being played ensures that the generated keys will be present on all
monitors.
> rolling_update: create missing keyring only on running mon

- roles/ceph-config/templates/ceph.conf.j2
jinja comment should be written using the jinja syntax `{# ... #}`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1654441
(cherry picked from commit a86c2b85263f84891e2cbf7e782f7ac8891257b3)
> config: write jinja comment with appropriate syntax

- roles/ceph-osd/tasks/start_osds.yml
The code is now able (again) to start osds that where configured with
ceph-disk on a non-container scenario.
Closes: https://github.com/ceph/ceph-ansible/issues/3388
> osd: manage legacy ceph-disk non-container startup

- roles/ceph-config/templates/ceph.conf.j2
since 0.0.0.0 is the default radosgw address (not 'address'), not
configuring an address explicitly, and instead configuring the radosgw
interface, would result in 0.0.0.0 being used, instead of falling
through to section that inspects the interface config option.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1655131
Signed-off-by: Noah Watkins <nwatkins@redhat.com>
> rgw: use correct default rgw frontend address

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
This is false, `./defaults/main.yml` is not supposed to be modified
directly. groups_vars a/o host_vars should always be preferred.
> [skip ci] osd: remove an incorrect information

- roles/ceph-defaults/tasks/facts.yml
- roles/ceph-infra/handlers/main.yml
- roles/ceph-infra/tasks/configure_firewall.yml
If firewalld unit is masked, setting `configure_firewall: false` is
enough
> revert: infra: do not start firewalld if unit is masked

- .travis.yml
The sudo keyword will be fully deprecated.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Signed-off-by: Christian Berendt <berendt@betacloud-solutions.de>
> travis: remove sudo: required

- tox.ini
When calling shrink on containerized deployment, we were first doing the
setup with `latest-master` and then when calling the playbook we were
using the default value for `ceph_docker_image_tag` that comes from
ceph-defaults. Now we pass
`ceph_docker_image_tag={env:CEPH_DOCKER_IMAGE_TAG:latest-master}` so the
play will run the right container image.
> tox: add missing ceph_docker_image_tag in shrink

- infrastructure-playbooks/add-osd.yml
- infrastructure-playbooks/rgw-standalone.yml
- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/shrink-mon.yml
- infrastructure-playbooks/shrink-osd-ceph-disk.yml
- infrastructure-playbooks/shrink-osd.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- infrastructure-playbooks/take-over-existing-cluster.yml
- infrastructure-playbooks/untested-by-ci/replace-osd.yml
- site-container.yml.sample
- site.yml.sample
- test.yml
Since variable sharing has been made default for roles, private option
has been deprecated; so stop using it.
> don't use private option for import_role

- group_vars/mgrs.yml.sample
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/tasks/main.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
This commit removes the default module, so ceph-ansible does not enable
any manager module.
To enable a module you need to set a value to 'ceph_mgr_modules', you
can pass a list of modules like this:
ceph_mgr_modules:
- status
- dashboard
> mgr: little refact

- roles/ceph-defaults/tasks/facts.yml
We want to test podman on f29 non-atomic, atomic is not a hard
requirement. However, if you want to get podman then you will have to
install it first before running the playbook.
> ceph-defaults: do not use podman only on atomic

- infrastructure-playbooks/purge-docker-cluster.yml
This task has to be called after the role `ceph-defaults` has been
played, otherwise, `mon_group_name` will never be known.
> purge-container: move facts gathering after ceph-defaults role import

- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-common/tasks/installs/install_on_clear.yml
- roles/ceph-common/tasks/installs/install_on_debian.yml
- roles/ceph-common/tasks/installs/install_on_suse.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
- roles/ceph-common/tasks/installs/redhat_community_repository.yml
- roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
- roles/ceph-handler/handlers/main.yml
- roles/ceph-mds/tasks/non_containerized.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Make linter happy and add more robustness to remote tasks by retrying 3
times (the default) before failing.
> lint: Remote package tasks should have a retry

- site-container.yml.sample
- site.yml.sample
Add `any_errors_fatal: true` to all host sections in site.yml.sample and site-container.yml.sample` so that the playbook execution ceases spontaneously and instantaneously when errors occurs.
> set any_errors_fatal to true for all host section

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/scenarios/non-collocated.yml
In non-collocated scenario two separate partitions are created for RocksDB and WAL when using the same device for both. If I understand the documentation at [BlueStore documentation](http://docs.ceph.com/docs/mimic/rados/configuration/bluestore-config-ref/) correctly, it isn't required to explicitly create a partition for WAL, since it will be located along the RocksDB anyway.
This pull request adds support for setting `bluestore_wal_devices: []`. In this case no WAL device is passed to `ceph-disk` creating a single partition for RocksDB only.
> add support for rocksdb and wal on the same partition in non-collocated

- plugins/actions/validate.py
Validation currently fails when `ceph_repository: custom` even though this is a valid choice according to:
https://github.com/ceph/ceph-ansible/blob/561746f75e3913b30e6ae3f14768ebc8a516bf66/group_vars/all.yml.sample#L245
Setting the following works as documented/advertised with this patch:
```
---
ceph_repository: custom
ceph_custom_repo: http://somehost.com/path/to/custom.repo
```
> add 'custom' as valid ceph_repository value

- Vagrantfile
Those default values are useless and might cause issues.
- `osd_scenario` should be mandatory anyway.
- `pool_default_size` is not used anymore (this has been refactored
recently.
Closes: #3468
> Vagrantfile: remove useless default values

- infrastructure-playbooks/rolling_update.yml
There is no need to enforce `serial: 1` on client nodes.
Let's make it parameterizable by introducing a new *extra* variable
`client_update_batch`, if not filled this will default to `{{
ansible_forks }}`.
NOTE: this is only usable as an extra variable passed with
`-e client_update_batch=<num>`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1650184
> update: do not enforce `serial: 1` on client nodes

- infrastructure-playbooks/rolling_update.yml
Json is a type structure which is always typed as a string, where before
this we were declaring a dict, which is not a json valid structure.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1663026
(cherry picked from commit 896676ee80226121785f44f50d1f01fff5aa2fd7)
> [backport][stable-3.2] fix json data type

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
In Task "fetch nfs-ganesha development repository"
This has to be pushed directly to stable-3.2 since master has diverged
Signed-off-by: Bruceforce <Bruceforce@users.noreply.github.com>
> The nfs_ganesha_dev_apt_repo variable was set incorrect

- tests/functional/tests/osd/test_osds.py
Since msgr2 changes got merged, the OSDs in master (to be nautilus) will
double the amount of ports they listen to.
Failures look like:
[gw3] darwin -- Python 2.7.14 /Users/alfredo/python/ceph/src/ceph-volume/ceph_volume/tests/functional/batch/.tox/centos7-bluestore-mixed_type/bin/python2.7
self = <tests.osd.test_osds.TestOSDs object at 0x10e6fe810>
node = {'address': '192.168.3.100', 'ceph_release_num': {'dev': 99, 'jewel': 10, 'kraken': 11, 'luminous': 12, ...}, 'ceph_stable_release': 'luminous', 'cluster_address': '192.168.4.200', ...}
host = <testinfra.host.Host object at 0x10de20a10>
def test_osds_listen_on_cluster_network(self, node, host):
nb_port = (node["num_osds"] * 2)
>       assert host.check_output("netstat -lntp | grep ceph-osd | grep %s | wc -l" %  # noqa E501 …
> testinfra/osds double the amount of ports OSDs listen to

- roles/ceph-mon/tasks/ceph_keys.yml
Somewhat something changed with the introduction of msg2 and we have to
add each node as a peer so the monitors can form a quorum. This might be
due to our CI environment, although adding this is completly harmless
and solves monitors not being able to form quorum.
It seems that the initial monitor map wasn't containing the right
information about the peers (addresses like 0.0.0.0/0r1, for each rank.
> mon: force peer addition

- .gitignore
- raw_install_python.yml
- site-container.yml.sample
- site.yml.sample
- tests/functional/lvm_setup.yml
- tests/functional/setup.yml
to avoid duplicating code in `site.yml.sample`, `site-docker.yml.sample`
and `setup.yml`, let's isolate this part of the code and simply include
it each time we need it.
> refact the 'raw' installation of python

- group_vars/all.yml.sample
- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
- roles/ceph-rgw/handlers/main.yml
- roles/ceph-rgw/tasks/common.yml
- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
- roles/ceph-rgw/tasks/pre_requisite.yml
- roles/ceph-rgw/tasks/start_radosgw.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
- tests/functional/centos/7/cluster/group_vars/all
- tests/functional/centos/7/docker-collocation/group_vars/all
- tests/functional/centos/7/docker/group_vars/all
- tests/functional/tests/rgw/test_rgw.py
- tests/functional/tests/rgw/test_rgw_tuning.py
With this, we could have multiple rgw instances on a single host
with a single run, don't have to use rgw-standalone.yml which does not
seems able to bind ports separately.
And if you don't want to have multiple rgw instances, just do not
define 'rgw_instances'.
Not compatible with Multi-Site yet.
Signed-off-by: guihecheng <guihecheng@cmiot.chinamobile.com>
> rgw: add support for multiple rgw instances on a single host

- infrastructure-playbooks/rolling_update.yml
Signed-off-by: Giulio Fidente <gfidente@redhat.com>
> Preserve rolling_update backward compatibility with ansible < 2.5

- roles/ceph-common/tasks/main.yml
when `ceph_origin` is set to `'repository'` and `ceph_repository` to
`'community'` we need to ensure `ceph_release` reflect `ceph_stable_release`.
> override ceph_release with ceph_stable_release

- roles/ceph-config/templates/ceph.conf.j2
877979c78 in #3486 broke ceph.conf generation entirely. Remove the stray
curly brace.
> Fix ceph.conf generation

- tests/conftest.py
- tests/functional/tests/rgw/test_rgw.py
fix the wrong path used in various rgw testinfra tests.
set `1` as default value for `radosgw_num_instances`: if
`ansible_vars.get(radosgw_num_instances)` returns `None`, we can assume
there's only 1 instance since it's the default value in ceph-defaults.
> tests: fix rgw testinfra failure

- library/ceph_key.py
socket.gethostname may return a FQDN. Problem found in Linode.
> use shortname in keyring path

- tox.ini
switch_to_containers, ooo_collocation, podman should be able to specify
which os they are running on.
> tests: update envlist

- tests/functional/dev_setup.yml
- tox.ini
using `!` mark in tox.ini doesn't work on comma separated list.
The idea here is to skip all containerized scenario in dev_setup.yml and
use the `!` for the update scenario.
> tests: do not play dev_setup on containerized deployment

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/hosts-ubuntu
- tests/functional/shrink_mon/hosts-ubuntu
nfs-ganesha v2.5 and 2.6 have hit EOL. Install nfs-ganesha v2.7
stable that is currently being maintained.
Signed-off-by: Ramana Raja <rraja@redhat.com>
> Install nfs-ganesha stable v2.7

- tests/functional/lvm_setup.yml
especially for ooo_collocation scenario which is still using ceph-disk
testing.
> [skip ci] tests/stable-3.2: run lvm_setup.yml only when osd_scenario is lvm

- site.yml.sample
Many hosts sections in site.yml.sample were left out during the
backport commit 6e2cd0930fa17f5d50c73496eff71074301f55bd.
> set `any_errors_fatal` true for left out host sections

- group_vars/clients.yml.sample
- infrastructure-playbooks/untested-by-ci/cluster-os-migration.yml
- roles/ceph-client/defaults/main.yml
- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
The restart_osd_daemon.sh generated from the j2 template
contains a python call which uses 'print x' instead of
'print(x)'. Add the missing parentheses to make this call
compatible with both 2 and 3.
Also add parentheses to other python print calls found
in roles/ceph-client/defaults/main.yml and
infrastructure-playbooks/cluster-os-migration.yml.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1671721
Signed-off-by: John Fulton <fulton@redhat.com>
> Make python print statements python3 compatible

- roles/ceph-config/tasks/main.yml
Include tasks from create_ceph_initial_dirs earlier during ceph config role.
Fixes: #3568
> config: Create Ceph Initial Dirs earlier

- roles/ceph-osd/tasks/start_osds.yml
Follow up fix that 410abd7 missed.
Related: ceph#3561
Signed-off-by: John Fulton <fulton@redhat.com>
> Fix CNI error when net=host is not used on OSD calls

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Let's try again with the Nautilus release.
Closes: https://github.com/ceph/ceph-ansible/issues/1297
> osd: container remove --pid=host

- roles/ceph-iscsi-gw/tasks/deploy_ssl_keys.yml
Typical error:
```
fatal: [iscsi-gw0]: FAILED! =>
msg: 'an error occurred while trying to read the file ''/home/guits/ceph-ansible/tests/functional/all_daemons/fetch/e5f4ab94-c099-4781-b592-dbd440a9d6f3/iscsi-gateway.key'': [Errno 13] Permission denied: b''/home/guits/ceph-ansible/tests/functional/all_daemons/fetch/e5f4ab94-c099-4781-b592-dbd440a9d6f3/iscsi-gateway.key'''
```
`become: True` is not needed on the following task:
`copy crt file(s) to gateway nodes`.
Since it's already set in the main playbook (site.yml/site-container.yml)
The thing is that the files get generated in the 'fetch_directory' with
root user because there is a 'delegate_to' + we run the playbook with
`become: True` (from main playbook).
The idea here is to create files under ansible user so we can open them
later …
> iscsi: fix permission denied error

- roles/ceph-common/tasks/installs/install_debian_packages.yml
- roles/ceph-mds/tasks/non_containerized.yml
- roles/ceph-mgr/tasks/pre_requisite.yml
When {{omit}} is concatenated with another string, it expands to something
like __omit_place_holder__63eea0d96dd6ed867b95405e11d87dddf61f448d.
However, in these use-cases we need an empty string.
Regression introduced in d53f55e807e.
Signed-off-by: Leah Neukirchen <leah.neukirchen@mayflower.de>
> Fix uses of default(omit) with string concatenation

- roles/ceph-infra/tasks/setup_ntp.yml
The task setup chronyd called the handler disable chronyd, which of
course defeats the purpose.
Changing the task to disable ntpd instead fixes the issue of chronyd
being disabled after it got enabled.
Fixes: #3582
Signed-off-by: Patrick C. F. Ernzer pcfe@redhat.com
> setup_ntp: call handler to disable ntpd if chronyd used

- roles/ceph-mon/tasks/deploy_monitors.yml
167 is the ceph uid for Red Hat based system, thus trying to deploy a
monitor on Debian fail since the ceph user id on that system is 64045.
This commit uses the ceph_uid variable which contains the right uid
based on system/container detection.
Closes: https://github.com/ceph/ceph-ansible/issues/3589
> mon: do not hardcode ceph uid

- roles/ceph-infra/tasks/setup_ntp.yml
- roles/ceph-validate/tasks/main.yml
Since Atomic doesn't allow any installations and NTPd is not present
on Atomic image we are using, abort when ntp_daemon_type is set to ntpd.
https://github.com/ceph/ceph-ansible/issues/3572
> don't install NTPd on Atomic

- roles/ceph-validate/tasks/main.yml
Since it's already confusing whether ntp_daemon_type should be "ntp" or
"ntpd", fix the mistake in the title of the task that aborts if
ntp_daemon_type is set to "ntpd" and OS being used is Atomic.
> fix mistake in task that aborts when ntpd is chosen on Atomic

- library/ceph_key.py
Removing bytes literals since rstrip only supports type String or None.
Backporting f5c2ca37 to stable 3.2
Fixes  #3565
> ceph_key: fix rstrip for python 3

- ansible.cfg
Ceph module path needs to be configured if we want to avoid issues
like:
```console
no action detected in task. This often indicates a misspelled module
name, or incorrect module path
```
Currently the ansible-lint command in Travis CI complains about that.
> ansible.cfg: Add library path to configuration

- Makefile
- ceph-ansible.spec.in
Fedora and RHEL 8 have Python 3, so we must require Python 2 on RHEL 7 and Python 3 on RHEL 8.
Update the Makefile to use an "el8" dist for consistency, since many of the upcoming ceph-ansible builds will be based on RHEL 8.
> [skip ci] build: add RHEL 8 + Fedora support

- roles/ceph-mon/tasks/ceph_keys.yml
Otherwise keys get scattered over the mons.
Also, create all keys on the first mon and copy those to the other mons to be
consistent.
> delegate key creation to first mon

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/openstack_config.yml
introduce two new variables to make the check that 'wait for all osd to
be up' configurable.
It's possible that for some deployments, OSDs can take longer to be seen
as UP and IN.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1676763
> osd: make the 'wait for all osd to be up' task configurable

- roles/ceph-common/tasks/main.yml
We shouldn't reset `ceph_release` with `ceph_stable_release` when
`ceph_repository` is `rhcs`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1645379
> common: do not override ceph_release when ceph_repository is 'rhcs'

- roles/ceph-infra/handlers/main.yml
- roles/ceph-infra/tasks/configure_firewall.yml
There's no need to restart firewalld service when a new rule is
added due to the usage of the immediate flag.
> ceph-infra: Remove restart firewalld handler

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- raw_install_python.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
Add a new `osd_auto_discovery_exclude` to give the possibility of
excluding some devices in auto_discovery scenario.
> osd: add possibility to exclude device in osd_auto_discovery

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
the previous approach was wrong.
checking if `item.key` is in `osd_auto_discovery_exclude` (`['dm-',
'loop']`) is incorrect because it will obviously not match. Therefore,
the condition will return `True` whatever the device we are checking.
> facts: fix auto_discovery exclude

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
As discussed in #3617 we don't need to use the container `--memory` flag on the OSD when using bluestore.
> ceph-osd: Drop memory flag with bluestore

- site-container.yml.sample
- site.yml.sample
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/hosts-ubuntu
- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/hosts-switch-to-containers
- tests/functional/all_daemons/hosts-ubuntu
- tests/functional/all_daemons/vagrant_variables.yml
Let's bootstrap mgrs on monitors only if there's no mgrs section in
inventory hostfile.
Closes: #3613
> site.yml: do not bootstrap mgrs on monitors by default

- roles/ceph-mon/tasks/deploy_monitors.yml
Set directories to 755 and files to 644 to /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }} recursively instead of setting files and directories to 755 recursively. The ceph mon process writes files to this path with permissions 644. This update stops ansible from updating the permissions in /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }} every time ceph mon writes a file and increases idempotency.
> Set permissions on monitor directory to u=rwX,g=rX,o=rX recursive

- roles/ceph-mon/tasks/ceph_keys.yml
- tests/functional/collocation/group_vars/all
there's no need to generate mgr keyrings 'mgr.monX' when mgrs aren't
collocated with monitors.
> mon: do not create unnecessarily mgr keyrings

- group_vars/mons.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
The administrator keyring needs full capabilities on mds like mon,
osd and mgr.
Whithout this, the client.admin key won't be able to run commands
against mds (like ceph tell mds.0 session ls)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1672878
> mon: Add mds permissions to client.admin

- roles/ceph-rgw/templates/ceph-radosgw.service.j2
Added to the ceph-radosgw service template the ca-trust volume avoiding to expose useless information.
This bug is referred to the following bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1683290
Signed-off-by: fpantano <fpantano@redhat.com>
> ceph-radosgw bz#1683290

- library/ceph_volume.py
- library/test_ceph_volume.py
- tests/functional/bs-lvm-osds/container/hosts
- tests/functional/bs-lvm-osds/container/vagrant_variables.yml
- tests/functional/bs-lvm-osds/hosts
- tests/functional/bs-lvm-osds/vagrant_variables.yml
- this is needed to properly handle semaphore synchronization for udev
actions via dmcrypt/cryptsetup.
- add lvm+bluestore+dmcrypt testing in the CI
- update ceph-volume tests
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1683770
> [skip ci] cv: expose host ipc namespace to ceph-volume container

- .mergify.yml
This will avoid merging PR with 1 approval + [skip ci]
> mergify: need 2 approvals to merge a 'skip ci' PR

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- tox.ini
in addition to 15812970f033206b8680cc68351952d49cc18314
> osd: add ipc=host in systemd template for containers

- roles/ceph-osd/tasks/start_osds.yml
The "get osd ids" statement only registers the osd_ids_non_container variable. Running "ls /var/lib/ceph/osd/ | sed 's/.*-//'" should never produce a change on the system. Adding changed_went: false prevents irrelevant change messages from Ansible.
> Add changed_when: false to the "get osd ids" statement

- roles/ceph-validate/tasks/check_devices.yml
- roles/ceph-validate/tasks/main.yml
Tuned name of a task and error message to make it more user understandable
Fixes BZ 1648168 - ceph-validate : devices are not validated in non-collocated and lvm_batch scenario
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1648168
> Extends check_devices tasks to non-collocated an lvm-batch scenarios

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-osd/tasks/openstack_config.yml
ansible-lint reports:
[206] Variables should have spaces after {{ and before }}
> lint: Fix spaces before and after variables

- infrastructure-playbooks/purge-cluster.yml
using `shell` module seems to be the only way to make this task working
on rhel based distribution AND debian based distributions.
on ubuntu, using `command` ansible module fails like following
(not due to `sudo` usage or not):
```
ok: [osd1] => changed=false
cmd: command -v ceph-volume
failed_when_result: false
msg: '[Errno 2] No such file or directory: ''command'': ''command'''
rc: 2
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1653307
> purge: fix purge of lvm devices

- infrastructure-playbooks/add-osd.yml
- tests/requirements.txt
- tox.ini
otherwise, it will end up with error like following:
```
FAILED! => {"msg": "'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'"}
```
because facts won't have been gathered.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1670663
> add-osd: gather facts in second part of playbook

- tests/functional/collocation/group_vars/all
- tests/functional/collocation/hosts
ceph_origin and ceph_repository are mandatory variables.
> tests: fix collocation scenario

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-defaults/vars/main.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-osd/tasks/openstack_config.yml
Let user decide what min_size a pool should have.
```
kuberbd:
name: "kuberbd"
size: "2"
min_size: "1"
pg_num: "64"
pgp_num: "64"
rule_name: "replicated_rack"
type: 1
erasure_profile: ""
expected_num_objects: ""
application: "rbd"
```
Change is for any kind of pool 
openstack_pools
cephfs_data, cephfs_metadata
client.pools(clients.yml) - like kuberbd example
> Customize pools min_size

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-osd/tasks/openstack_config.yml
b8d580b3f48c69ba9882df773c4d144b73d01c95 introduced a bug when
`min_size` isn't set (default to 0).
Typical error:
```
Error EINVAL: pool min_size must be between 1 and 1
```
> fix pool min_size customization

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-osd/tasks/openstack_config.yml
After b8d580b and e9e5d5a we could have either item.min_size or
osd_pool_default_min_size using string instead of int causing the
condition to be true when it's false.
As a result, the task could try to set the pool min_size value to
0 which leads to:
Error EINVAL: pool min_size must be between 1 and 1
> Force osd pool min_size value to integer

- library/ceph_key.py
Because the client name is part of the client key path we can reuse
the user variable to build this path.
Also remove a duplicate user variable declaration.
> ceph_key: Use client name to build key path

- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
Instead of using subscription-manager with command module we can use
the rhsm_repository ansible module.
This module already uses repos list feature to determine if a
repository is enabled or not. That way this module is idempotent so
we don't need changed_when: false anymore.
> common: Use rhsm_repository module for RHCS

- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-osd/templates/ceph-osd.service.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
We don't need to set After=docker.service when the container_binary
variable isn't set to docker.
It doesn't break anything currently but it could be confusing when
using podman.
> systemd/service: Set docker.service conditionally

- infrastructure-playbooks/add-osd.yml
The check_devices task fails if the ceph-validate role isn't executed
as a privileged user (Permission denied).
failed: [osd0] (item=/dev/sdb) => {"changed": false, "err": "Error:
Error opening /dev/sdb: Permission denied\n", "item": "/dev/sdb",
"msg": "Error while getting device information with parted script:
'/sbin/parted -s -m /dev/sdb -- unit 'MiB' print'", "out": "", "rc": 1}
> add-osd.yml: Add become flag for ceph-validate

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/osds.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
This commit adds OSD containers activate with numactl support.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1684146
> osd: support numactl options on OSD activate

- roles/ceph-osd/tasks/main.yml
With 3e32dce we can run OSD containers with numactl support.
When using numactl command in a containerized deployment we need to
be sure that the corresponding package is installed on the host.
The package installation is only executed when the
ceph_osd_numactl_opts variable isn't empty.
> ceph-osd: Install numactl package when needed

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/vars/main.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-mon/tasks/crush_rules.yml
Currently the default crush rule value is added to the ceph config
on the mon nodes as an extra configuration applied after the template
generation via the ansible ini module.
This implies two behaviors:
1/ On each ceph-ansible run, the ceph.conf will be regenerated via
ceph-config+template and then ceph-mon+ini_file. This leads to a
non necessary daemons restart.
2/ When other ceph daemons are collocated on the monitor nodes
(like mgr or rgw), the default crush rule value will be erased by
the ceph.conf template (mon -> mgr -> rgw).
This patch adds the osd_pool_default_crush_rule config to the ceph
template and only for the monitor nodes (like crush_rules.yml).
The default crush rule id is read (if exist) from the current ceph
configuration.
The default configuration is -1 (ceph …
> Set the default crush rule in ceph.conf

- library/ceph_key.py
- library/ceph_volume.py
- library/test_ceph_key.py
- tests/functional/tests/osd/test_osds.py
**First issue fixed by fixed by PR -**
In most places os.path.join() is passed single string -
```
os.path.join(pathcomponent1 + pathcomponent2 + pathcomponent3 + ...)
```
The way to use it is -
```
os.path.join(pathcomponent1, pathcomponent2, pathcomponent3 + ...)
```
Passing a single string doesn't lead to any checks.
**Second issue fixed by this PR -**
Instances like the ones below doesn't need any check from `os.path.join()`, since there's only 1 path component.
```
os.path.join('--entrypoint=' + binary),
````
There were 2 of them; I've deleted both.
**Third issue fixed by this PR -**
Appending strings during the call makes it *very probable* that an incorrect way of calling (like above) might be missed. It's difficult to figure in following call whether strings are being appended to …
> fix how os.path.join() is being used

- roles/ceph-common/tasks/installs/redhat_community_repository.yml
When using community repository we need to set the priority on the
ceph repositories because we could have some conflict with EPEL
packages.
In order to set the priority on the ceph repositories, we need to
install the yum-plugin-priorities package.
http://docs.ceph.com/docs/master/install/get-packages/#rpm-packages
> ceph-common: Install yum plugin priorities

- roles/ceph-mon/tasks/docker/start_docker_monitor.yml
- roles/ceph-restapi/tasks/docker/start_docker_restapi.yml
Addressing "populate kv_store with custom ceph.conf":
Unsupported parameters for (docker_container) module. Looking at
https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
shows that the correct parameter is network_mode, not network.
Signed-off-by: Gregory Orange <gregoryo2014@users.noreply.github.com>
> Change docker_container parameter network to network_mode

- roles/ceph-osd/tasks/start_osds.yml
- roles/ceph-osd/vars/main.yml
Since all files in container image have moved to `/opt/ceph-container`
this check must look for new AND the old path so it's backward
compatible. Otherwise it could end up by templating an inconsistent
`ceph-osd-run.sh`.
> osd: backward compatibility with old disk_list.sh location

- library/ceph_volume.py
Since the same effect as described in #3565 also applies to ceph_volume it would be nice if this could be backported to stable-3.2 (in master this was already changed in a96e910114529aba0fe29edb11b314ae742ece45).
> ceph_volume: fix rstrip for python 3

- library/ceph_crush.py
Removing bytes literals since rstrip only supports type String or None.
Please backport to stable-3.2 as discussed in #3725
> ceph_crush: fix rstrip for python 3

- roles/ceph-osd/tasks/main.yml
When using osd_scenario lvm, we never check if the lvm2 package is
present on the host.
When using containerized deployment and docker on CentOS/RedHat this
package will be automatically installed as a dependency but not for
Ubuntu distribution.
OSD deployed via ceph-volume require the lvmetad.socket to be active
and running.
Resolves: #3728
> ceph-osd: Ensure lvm2 is installed

- group_vars/all.yml.sample
- group_vars/nfss.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-nfs/defaults/main.yml
Since nautilus has been released, it's now the latest stable release, it
means the tag `latest` now refers to nautilus.
`stable-3.2` isn't intended to deploy nautilus, therefore, we should
change the default value for this variable to the latest release
stable-3.2 is able to deploy (mimic).
Closes: #3734
> defaults: change default value for ceph_docker_image_tag

- infrastructure-playbooks/rolling_update.yml
- library/ceph_key.py
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-handler/handlers/main.yml
- roles/ceph-iscsi-gw/tasks/container/containerized.yml
- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
- roles/ceph-mds/tasks/containerized.yml
- roles/ceph-mds/tasks/main.yml
- roles/ceph-mds/tasks/non_containerized.yml
- roles/ceph-mgr/tasks/start_mgr.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-mon/tasks/start_monitor.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-osd/tasks/start_osds.yml
- roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
- roles/ceph-rbd-mirror/tasks/start_rbd_mirror.yml
- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
- roles/ceph-rgw/tasks/main.yml
- roles/ceph-rgw/tasks/start_radosgw.yml
- tox-update.ini
This PR adds the nautilus upgrade support.
A couple of fixes were required:
- ceph_key module: don't fail in the `lookup_ceph_initial_entities()` when the expected keyring list doesn't match what is found in the cluster during the rolling_update sequence,
- mask the systemd unit services to prevent the packaging from restarting services,
- introduce msgr2 protocol support,
- ensure mgrs are upgraded after ALL monitors,
- do not trigger handlers when running rolling_update since we manager stop/start of services in the playbook.
This commit also split the tox file to be more readable since it's became too big.
> add luminous/mimic to nautilus upgrade support

- plugins/actions/validate.py
Ubuntu cloud archive is configurable via ceph_repository variable but
the uca choice isn't accepted.
This commit fixes this issue and also validates the associated uca
repository variables.
Resolves: #3739
> Add uca to ceph_repository choices validation

- .travis.yml
The galaxy-lint-rules github repository isn't used anymore and has
been archived.
All the rules are now part of the ansible-lint project.
https://github.com/ansible/galaxy-lint-rules
https://github.com/ansible/ansible-lint
> travis: Remove galaxy lint rules repository

- infrastructure-playbooks/rolling_update.yml
The systemd unit regex doesn't handle nvme devices (/dev/nvmeXn1).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1687828
> rolling_update: Update systemd unit regex for nvme

- tox.ini
On containerized CI jobs the playbook executed is purge-cluster.yml
but it should be set to purge-docker-cluster.yml
> tox: Fix container purge jobs

- tests/functional/reboot.yml
Ansible 2.7 introduces the reboot module so we don't need to use the
shell/reboot + wait_for tasks.
https://docs.ansible.com/ansible/latest/modules/reboot_module.html
> tests/functional: Use the ansible reboot module

- roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
When installing python-minimal on Ubuntu bionic, this will add the
/usr/bin/python symlink to the default python interpreter.
On bionic, this isn't python2 but python3.
$ /usr/bin/python --version
Python 3.6.7
The python docker library is only installed for python2 which causes
issues when running the purge-docker-cluster playbook. This playbook
uses the ansible docker modules and requires to have python bindings
installed on the remote host.
Without the bindings we can see python error reported by the docker
module.
msg: Failed to import docker or docker-py - No module named 'docker'.
Try `pip install docker` or `pip install docker-py` (Python 2.6)
> container: Add python3-docker on Ubuntu bionic

- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/hosts-switch-to-containers
- tests/functional/all_daemons/hosts-ubuntu
- tests/functional/all_daemons/vagrant_variables.yml
- tests/functional/shrink_osd/hosts
- tests/functional/shrink_osd/vagrant_variables.yml
remove the 'ceph-' prefix in order to have the same names in all
branches.
> tests: rename all nodes name
