ceph/ceph-ansible

- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/vagrant_variables.yml
even not used, we need to fire up those VMs to be able to perform the
upgrade in the CI.
> tests: add mgr and nfs nodes in all_daemons

- infrastructure-playbooks/purge-docker-cluster.yml
The systemd ceph-osd@.service file used for starting the ceph osd
containers is used in all osd_scenarios.
Currently purging a containerized deployment using the lvm scenario
didn't remove the ceph-osd systemd service.
If the next deployment is a non-containerized deployment, the OSDs
won't be online because the file is still present and override the
one from the package.
> purge-docker-cluster: Remove ceph-osd service

- tests/functional/lvm-auto-discovery/container/group_vars/all
- tox-update.ini
- tox.ini
On stable-4.0 branch we don't want to use dev setup but stable
release (nautilus).
Also update the container image tag to reflect this change.
> tox: Set nautilus as default release

- roles/ceph-osd/tasks/docker/start_docker_osd.yml
- roles/ceph-osd/vars/main.yml
Since all files in container image have moved to `/opt/ceph-container`
this check must look for new AND the old path so it's backward
compatible. Otherwise it could end up by templating an inconsistent
`ceph-osd-run.sh`.
(cherry picked from commit 987bdac963cee8d8aba1f10659f23bb68c2b1d1b)
> [backport] osd: backward compatibility with old disk_list.sh location (stable-3.1)

- roles/ceph-config/tasks/main.yml
- roles/ceph-osd/tasks/scenarios/lvm-batch.yml
- roles/ceph-osd/tasks/scenarios/lvm.yml
- tox.ini
there's no need to test this on all scenarios.
testing idempotency on all_daemons should be enough and allow us to save
precious resources for the CI.
> tests: test idempotency only on all_daemons job

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
`lvm_volumes` and/or `devices` variable(s) can be undefined depending on
the scenario chosen.
These tasks should be run only if these variable are defined, otherwise
it ends up with undefined variable errors.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1653307
> purge: fix lvm-batch purge osd

- tests/scripts/vagrant_up.sh
- tox.ini
Add a script to retry several times to fire up VMs to avoid vagrant
failures.
Co-authored-by: Andrew Schoen <aschoen@redhat.com>
> tests: retry to fire up VMs on vagrant failure

- tox.ini
the wrong image version was used to run shrink_osd playbook.
in stable-3.1 we should use a luminous image, not nautilus which doesn't
have ceph-disk binary anymore.
> tests: fix shrink_osd scenario (stable-3.1)

- tox.ini
since the node names have changed recently (the 'ceph-' prefix has been
removed), we must change the name in the shrink_mon playbook command
here.
> tests: fix shrink_mon scenario (stable-3.1)

- roles/ceph-mon/tasks/ceph_keys.yml
According to rdo testing https://review.rdoproject.org/r/#/c/18721
a check on the output of the ceph_health value is added to
allow the playbook to make several attempts (according to the
retry/delay variables) when waiting the cluster quorum or
when the container bootstrap is not ended.
It avoids the failure of the command execution when it doesn't
receive a valid json object to decode (because cluster is too
slow to boostrap compared to ceph-ansible task execution).
Signed-off-by: fpantano <fpantano@redhat.com>
> Check ceph_health_raw.stdout value as string during mon bootstrap

- tests/requirements.txt
- tox.ini
looks like newer version of pytest-xdist requires pytest>=4.4.0
> tests: pin pytest-xdist to 1.27.0

- tox.ini
deploying ceph@master in stable-3.2 is not possible.
> tests: do not deploy ceph@master in rgw_multisite

- group_vars/rgws.yml.sample
- roles/ceph-rgw/defaults/main.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
In containerized deployment the default radosgw quota is too low
for production environment.
This is causing performance degradation compared to bare-metal.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1680171
> radosgw: Raise cpu limit to 8

- tox.ini
otherwise ceph-osd fails:
```
ceph-volume lvm prepare: error: Unable to proceed with non-existing device: test_group/data-lv2
```
> tests: run lvm_setup.yml on secondary cluster

- infrastructure-playbooks/add-osd.yml
- tests/functional/add-osds/container/vagrant_variables.yml
Instead of hardcoding group names, import ceph-defaults earlier. Also,
rectify a minor mistake in vagrant_varaibles.yml for containerized
version of add_osds.
> add-osds: don't hardcode group names

- tox-update.ini
jenkins sets `CEPH_ANSIBLE_BRANCH` to `stable-4.0`, this makes all
nightly job failing.
> tests: fix update job

- roles/ceph-mgr/tasks/main.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
When mgrs are implicitly collocated on monitors (no mgrs in mgrs group).
That include was skipped because of this condition :
`inventory_hostname == groups[mgr_group_name][0]`
> mgr: wait for all mgr to be available

- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
Hi,
According to my tests (in branch stable-4.0 with the docker image ceph/daemon:v4.0.0rc1-stable-4.0-nautilus-centos-7-x86_64), this PR fixes a problem of paths which depend on the cluster name. Here is the `all.yml` I have used to make a deployment:
```yml
containerized_deployment: true
ceph_docker_registry: 'docker.io'
ceph_docker_image: 'ceph/daemon'
ceph_docker_image_tag: 'v4.0.0rc1-stable-4.0-nautilus-centos-7-x86_64'
cluster: 'ceph-m'
public_network: '10.111.222.0/24'
cluster_network: '10.111.222.0/24'
osd_objectstore: 'bluestore'
osd_scenario: 'lvm'
lvm_volumes:
- db_vg: 'vg-ssd'
db: 'blockdb'
data_vg: 'vg-osd'
data: 'data'
ceph_conf_overrides:
global:
mon_allow_pool_delete: 'true'
osd_pool_default_size: 1
osd_pool_default_min_size: 1
osd_crush_update_on_start: 'true' …
```
> ceph-rgw: Fix bad paths which depend on the cluster name

- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
When using monitor_address_block or radosgw_address_block variables
to configure the mon/rgw address we're getting the first ip address
from the ansible facts present in that cidr.
When there's VIP on that network the first filter could return the
wrong value.
This seems to affect only IPv6 setup because the VIP addresses are
added to the ansible facts at the beginning of the list. This is the
opposite (at the end) when using IPv4.
This causes the mon/rgw processes to bind on the VIP address.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1680155
> mon/rgw: use last ipv6 address

- roles/ceph-mon/tasks/main.yml
Let's use a condition to run this task only on the first mon.
> mon: remove useless delegate_to

- roles/ceph-facts/tasks/facts.yml
- tests/functional/lvm-batch/container/group_vars/all
- tests/functional/lvm-batch/group_vars/all
ceph-volume didn't work when the devices where passed by path.
Since it now support it, let's allow this feature in ceph-ansible
Closes: #3812
> osds: allow passing devices by path

- infrastructure-playbooks/rolling_update.yml
if mgr group isn't defined in inventory, that task will fail with
undefined error.
> update: fix undefined error when no mgr group is declared

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
e6bfb84 introduced a regression in the switch from non containerized
to container deployment.
We need to stop all previous OSDs services. We just don't need the
ceph-disk pattern in the regex.
> switch-from-non-containerized: stop all osds

- roles/ceph-mon/tasks/ceph_keys.yml
With a large and/or busy cluster, it can take significantly more than
30s for a restarted monitor to get to the point where
`ceph-create-keys` returns successfully. A recent upgrade of our
production cluster failed here because it took a couple of minutes for
the newly-upgraded `mon` to be ready. So increase the timeout
significantly.
This patch is applied to stable-3.2, because the affected code is
refactored in stable-4.0 and ceph-create-keys is no longer called, 
there or in master.
> ceph-mon: increase timeout waiting for admin and bootstrap keys

- docs/source/index.rst
[rgw] isn't a valide section.
[client.rgw.{instance_name] should be used instead.
Resolves: #3841
> docs: Update ceph.conf supported section

- infrastructure-playbooks/purge-cluster.yml
When using purge-cluster playbook with nautilus, there's still the
python-ceph-argparse package installed on the host preventing to
reinstall a ceph cluster with a different version (like luminous or
mimic)
> purge-cluster: remove python-ceph-argparse package

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/install_on_debian.yml
- roles/ceph-common/tasks/installs/install_redhat_packages.yml
- roles/ceph-defaults/defaults/main.yml
These packages aren't needed anymore.
They were needed for ceph-init-detect but as of ceph-init-detect doesn't exist
anymore.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1683885
> defaults: remove some package dependencies

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/install_on_debian.yml
- roles/ceph-common/tasks/installs/install_redhat_packages.yml
- roles/ceph-defaults/defaults/main.yml
Because 5c98e361df5241fbfa5bd0a2ae1317219b7e1244 could be seen as a non
backward compatible change this commit reverts it and bring back package
dependencies installation support. Let's just change the default value instead.
> defaults: refact package dependencies installation.

- tests/functional/tests/mon/test_mons.py
Since nautilus and msgr2 the monitors also bind on port 3300 in
addition of 6789.
This patch updates test_mons to reflect that change.
> test_mons: test mon listening on port 3300

- tests/functional/setup.yml
- tests/requirements.txt
In the CI jobs we can change the mount options of the main partition
to avoid extra operations on disk.
> tests/functional/setup: change mount options

- roles/ceph-agent/meta/main.yml
- roles/ceph-client/meta/main.yml
- roles/ceph-common/meta/main.yml
- roles/ceph-config/meta/main.yml
- roles/ceph-container-common/meta/main.yml
- roles/ceph-defaults/meta/main.yml
- roles/ceph-validate/tasks/check_system.yml
Currently we only support ansible 2.7
We plan to use 2.8 when it will be release so we have to support both
2.7 and 2.8.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1700548
> allow using ansible 2.8

- tests/functional/tests/osd/test_osds.py
Since there's only only scenario available we don't need lvm_scenario
and no_lvm_scenario.
Also add missing assert for ceph-volume tests.
> test_osds: remove scenario leftover

- infrastructure-playbooks/rolling_update.yml
- roles/ceph-config/tasks/main.yml
- roles/ceph-osd/tasks/main.yml
- tests/functional/migrate_ceph_disk_to_ceph_volume/Vagrantfile
- tests/functional/migrate_ceph_disk_to_ceph_volume/group_vars/all
- tests/functional/migrate_ceph_disk_to_ceph_volume/hosts
- tests/functional/migrate_ceph_disk_to_ceph_volume/vagrant_variables.yml
- tox.ini
When upgrading to nautlius run ``ceph-volume simple scan`` and
``ceph-volume simple activate --all`` to migrate any running
ceph-disk osds to ceph-volume.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1656460
> rolling_update: migrate ceph-disk osds to ceph-volume

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/rolling_update.yml
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
this commit refact the msgr2 protocol introduction.
If it's a fresh install, let's go with v2 only.
If we upgrade to nautilus, we should go with v2+v1 syntax to ensure
nothing breaks.
> update: refact msgr2 migration

- group_vars/rgws.yml.sample
- roles/ceph-rgw/defaults/main.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
1/ The OSD already supports cpuset to be used for containerized deployments
through the use of the ceph_osd_docker_cpuset_cpus variable. This adds similar
support to the RGW service for containerized deployments by setting a new
variable named ceph_rgw_docker_cpuset_cpus. Like the OSD, there are times where
using distinct cores has advantages over using the CFS in kernel scheduler.
ceph_rgw_docker_cpuset_cpus accepts a comma delimited set of CPU ids
2/ Add support for specifying --cpuset-mem variable to restrict the cgroup's memory
allocations to a particular numa node, which should typically correspond with
the cpu ids of that numa node that were provided with --cpuset-cpus. To ensure
the correct cpu ids are used one can run `numactl --hardware`  to list the nodes
and which cpu ids …
> rgw: add cpuset support

- roles/ceph-mds/tasks/create_mds_filesystems.yml
this task has nothing to do in stable-4.0 and after.
Let's remove it since stable-4.0 and after aren't intended to deploy
luminous.
Closes: #3873
> mds: remove legacy task

- docs/source/index.rst
I noticed today that stable-4.0 has been branched, but that the documentation hadn't yet been updated to include that fact. So I put together what I _think_ is the correct combination of supported Ceph versions and Ansible versions for each branch. If I got something wrong, please correct me!
> doc: update index.rst with current information for stable-4.0

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
Allow pools  cephfs_data, cephfs_metadata to be created with specific rule_name.
example group_vars/all.yml
```
##########
##########
cephfs: cephfs # name of the ceph filesystem
cephfs_data: cephfs_data # name of the data pool for a given filesystem
cephfs_metadata: cephfs_metadata # name of the metadata pool for a given filesystem
cephfs_data_pool:
name: "{{cephfs_data}}"
pg_num: "64"
pgp_num: "64"
rule_name: "replicated_rack"
type: 1
erasure_profile: ""
expected_num_objects: ""
cephfs_metadata_pool:
name: "{{cephfs_metadata}}"
pg_num: "64"
pgp_num: "64"
rule_name: "replicated_rack"
type: 1
erasure_profile: ""
expected_num_objects: ""
cephfs_pools:
- "{{ cephfs_data_pool }}"
- "{{ cephfs_metadata_pool }}"
```
> mds: allow cephFS pool to be created with specific rule_name

- plugins/actions/validate.py
Typical error:
```
AttributeError: 'Invalid' object has no attribute 'message'
```
As of python 2.6, `BaseException.message` has been deprecated.
When using python3, it fails because it has been removed.
Let's use `str(error)` instead so we don't hit this error when using
python3.
> validate: fix notario error

- plugins/actions/validate.py
5aa27794615e7d4521b1dbf1444b61388aacb852 introduced a typo.
> validate: fix a typo

- infrastructure-playbooks/rolling_update.yml
Currently only rbd-target-gw service is restarted during an update.
We also need to restart tcmu-runner and rbd-target-api services
during the ceph iscsi upgrade.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1659611
> rolling_update: restart all ceph-iscsi services

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
b2f2426 didn't use the generate_group_vars_sample.sh script so we
currently have a difference between the content in group_vars and the
ceph-defaults/defaults directories.
> Update group_vars according to defaults

- tox.ini
update scenario is now handled by tox-update.ini file so we shoudn't
have update reference in tox.ini file.
> tox: Remove update scenario reference

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
- tests/functional/tests/iscsi/test_iscsi.py
- tests/functional/tests/mds/test_mds.py
- tests/functional/tests/mon/test_mons.py
- tests/functional/tests/nfs/test_nfs_ganesha.py
- tests/functional/tests/osd/test_osds.py
- tests/functional/tests/rbd-mirror/test_rbd_mirror.py
- tests/functional/tests/rgw/test_rgw.py
- tests/functional/tests/test_install.py
Instead of creating a dedicated test and using the same testinfra
module we can group them into a single test to avoid multiple ansible
connections and testinfra module execution.
This patch also adds parametrize pytest decorator when possible.
Finally fixing some flake minor issue.
> tests: group and parametrize tests

- plugins/actions/validate.py
This adds missing configuration options and corrects a typo error when
the 'custom' repository is used.
Signed-off-by: Jugwan Eom <zugwan@gmail.com>
> validate: check custom repository config options

- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
In containerized deployment the default osd cpu quota is too low
for production environment using NVMe devices.
This is causing performance degradation compared to bare-metal.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1695880
> ceph-osd: Increase cpu limit to 4

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
The PR #3916 was merged automatically by mergify even if there was a
confict in the ceph-osd-run.sh.j2 template.
This commit resolves the conflict.
> ceph-osd: Fix merge conflict from mergify

- group_vars/mdss.yml.sample
- roles/ceph-mds/defaults/main.yml
- roles/ceph-mds/templates/ceph-mds.service.j2
In containerized deployment the default mds cpu quota is too low
for production environment.
This is causing performance degradation compared to bare-metal.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1695850
> ceph-mds: Increase cpu limit to 4

- docs/source/osds/scenarios.rst
- group_vars/osds.yml.sample
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/scenarios/non-collocated.yml
We only need to set the wal dedicated device when there's three tiers
of storage used.
Currently the block.wal partition will also be created on the same
device than block.db.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1685253
> osd: set default bluestore_wal_devices empty

- infrastructure-playbooks/shrink-osd.yml
- library/ceph_volume.py
- library/test_ceph_volume.py
This requires ceph-volume zap by osd_fsid feature that isn't available in ceph prior to 12.2.11.
RHCS 3.2z2 will ship with ceph luminous 12.2.8 so shrink-osd is broken.
Since these commits introduced a regression for 3.2z2 we should revert them and introduce them back for RHCS 3.3 once 3.2z2 is GA.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1702311
> revert osd_fsid zapping in shrink osd

- roles/ceph-osd/tasks/main.yml
- site-container.yml.sample
This will be removed in ansible 2.8 and breaks the playbook execution
with this release.
> ansible: remove private and static attribute

- roles/ceph-facts/tasks/facts.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
Adds "check_mode: no" to commands which register cluster state in a
variable and don't modify anything. These commands have to run in order
to support running the playbook in check mode.
> Fix check mode support

- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-osd/tasks/openstack_config.yml
Except for some corner case, it's not correct to access some other
node's copy of variable docker_exec_cmd. Therefore replace
`hostvars[groups[mon_group_name][0]]['docker_exec_cmd']`by
`docker_exec_cmd`.
> don't access other node's docker_exec_cmd variable

- roles/ceph-facts/tasks/facts.yml
running an external ceph cluster deployment with (obviously) no
monitors defined in inventory breaks with an undefined error because
`_monitor_addresses` never get defined.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1707460
> facts: fix external cluster bug

- roles/ceph-facts/tasks/facts.yml
- tests/functional/lvm-batch/container/group_vars/all
- tests/functional/lvm-batch/group_vars/all
ceph-volume didn't work when the devices where passed by path.
Since it now support it, let's allow this feature in ceph-ansible
Closes: #3812
(cherry picked from commit 8f2c45dfd3d1d3875a480247ca047aa52d7cd1b1)
> [backport] osds: allow passing devices by path

- infrastructure-playbooks/shrink-osd.yml
- library/ceph_volume.py
- library/test_ceph_volume.py
This PR reapply the patches that were reverted for the 3.2z2 release.
This is to make ceph-ansible shrink-osd playbook handling the ceph-volume zap by osd_fsid feature.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1686306
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1572933
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1569413
> reapply shrink-osds patches to handle the ceph-volume zap by osd_fsid feature

- roles/ceph-mds/tasks/create_mds_filesystems.yml
ceph-mds: do not delegate tasks individually
ceph-mds: group similar tasks in `create_mds_filesystem.yml` using block keyword
> refactor role ceph-mds

- infrastructure-playbooks/rolling_update.yml
We must stop tcmu-runner after the other rbd-target-* services because
they may need to interact with tcmu-runner during shutdown. There is
also a bug in some kernels where IO can get stuck in the kernel and by
stopping rbd-target-* first we can make sure all IO is flushed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1659611
Signed-off-by: Mike Christie <mchristi@redhat.com>
> igw: Fix rolling update service ordering

- roles/ceph-rgw/tasks/main.yml
Set the application to rgw for pools created from rgw_create_pools. On Ceph Nautilus the heath is set to HEALTH_WARN with the message "application not enabled on X pool(s)" if an application isn't specified for a pool.
> Set the rgw_create_pools pools application to rgw

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- rhcs_edits.txt
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- roles/ceph-defaults/defaults/main.yml
RHCS 4 will be based on Nautilus and only usable on RHEL 8.
Updated the default ceph_rhcs_version to 4 and update the rhcs
repositories to rhcs 4 with RHEL 8.
> Update RHCS version with Nautilus

- roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
The old condition would resolve to
```
"when": "nfs_ganesha_stable - ceph_repository == 'community'"
```
now it is
```
"when": [
"nfs_ganesha_stable",
"ceph_repository == 'community'"
]
```
Please backport to stable-4.0
> ceph-nfs: fixed condition for "stable repos specific tasks"

- infrastructure-playbooks/gather-ceph-logs.yml
The shell module doesn't have a stdout_lines attributes. Instead of
using the shell module, we can use the find modules.
Also adding `become: false` to the local tmp directory creation
otherwise we won't have enough right to fetch the files into this
directory.
Resolves: #3966
> gather-ceph-logs: fix logs list generation

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
If we do this in one line we get the error described in #3968
fixes #3968
Please backport to stable-4.0
> ceph-nfs: fixed with_items

- roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
- roles/ceph-container-common/vars/RedHat-8.yml
Currently podman installation is very tied to RHEL 8 even if we're
able to install it on Debian/Ubuntu distribution.
This patch changes the way we are starting or not the (fat) container
daemon. Before the condition was based on the distribution release
and now on the container_service_name variable.
> container-common: allow podman for other distros

- infrastructure-playbooks/purge-docker-cluster.yml
We never clean the content of /var/lib/docker so we can still have
some data present in this directory after run the purge playbook.
Pip isn't used anymore.
Also update the docker package name (especially the python binding
one).
> purge-docker-cluster: remove docker data

- tests/functional/dev_setup.yml
c907ec41ae0698b7627ebcbe97f1c293611d41d7 introduced a typo.
noticed it with this warning:
```
[WARNING]: While constructing a mapping from /home/guits/ceph-ansible/tests/functional/dev_setup.yml, line 21, column 9, found a duplicate dict key (replace). Using last defined value only.
```
> tests: fix a typo in dev_setup.yml

- site-container.yml.sample
This moves the call to ceph-node-exporter role after
ceph-container-common, otherwise it will try to run container before
docker or podman are installed.
> dashboard: move the call to ceph-node-exporter

- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
When using a minimal Debian/Ubuntu distribution there's no
ca-certificates and gpg packages installed so the apt modules will
fail:
Failed to find required executable gpg in paths:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
apt.cache.FetchFailedException:
W:https://download.ceph.com/debian-luminous/dists/bionic/InRelease:
No system certificates available. Try installing ca-certificates.
Resolves: #3994
> common: install dependencies for apt modules

- roles/ceph-config/templates/ceph.conf.j2
As of nautilus, if you set `ms bind ipv6 = True` you must explicitly set
`ms bind ipv4 = False` too, otherwise OSDs will still try to pick up an
IPv4 address.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710319
> config: fix ipv6

- roles/ceph-prometheus/tasks/main.yml
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
- remove trailing double quotes in jinja templates
- add jinja filename without .j2 suffix
Resolves: #4011
> ceph-prometheus: fix error in templates

- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
gpg package isn't available for all Debian/Ubuntu distribution but
gnupg is.
> common: use gnupg instead of gpg

- roles/ceph-mgr/tasks/pre_requisite.yml
The ceph mgr dashboard requires routes python library to be installed
on the system.
Resolves: #3995
> ceph-mgr: install python-routes for dashboard

- tests/requirements.txt
- tox-dashboard.ini
- tox-update.ini
- tox.ini
This commit adds `pytest-rerunfailures` in requirements.txt so we can
retry failing test in testinfra to avoid false positive. (eg: sometimes it
can happen for some reason a service takes too much time to start)
> tests: add retries on failing tests in testinfra

- roles/ceph-facts/tasks/facts.yml
The fsid generation is done via a python command. When the ansible
controller node only have python3 available (like RHEL 8) then the
python command isn't necessarily present causing the fsid generation
to fail.
We already do some resource creation (like ceph keyring secret) with
the python command too but from the mon node so we should do the same
for fsid.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1714631
> ceph-facts: generate fsid on mon node

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-nfs/tasks/common.yml
- roles/ceph-nfs/tasks/main.yml
- roles/ceph-nfs/tasks/pre_requisite_container.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-validate/tasks/check_nfs.yml
- roles/ceph-validate/tasks/main.yml
This commits allows to deploy an internal ganesha with an external ceph cluster.
This requires to define `external_cluster_mon_ips` with a comma
separated list of external monitors.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710358
> nfs: support internal ganesha with external ceph cluster

- roles/ceph-grafana/tasks/configure_grafana.yml
- roles/ceph-infra/tasks/configure_firewall.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
- roles/ceph-mgr/tasks/pre_requisite.yml
- site-container.yml.sample
- site.yml.sample
when `dashboard_enabled` is `True`, let's append `dashboard` and
`prometheus` modules to `ceph_mgr_modules` so they are automatically
loaded.
Closes: #4026
Closes: #4023
> dashboard: append mgr modules to ceph_mgr_modules

- roles/ceph-nfs/tasks/start_nfs.yml
789cef7 introduces a regression in the ganesha configuration file
generation. The new config_template module version broke it.
But the ganesha.conf file isn't an ini file and doesn't really
need to use the config_template module. Instead we can use the
classic template module.
Resolves: #4045
> ceph-nfs: use template module for configuration

- group_vars/all.yml.sample
- group_vars/iscsigws.yml.sample
- group_vars/mdss.yml.sample
- group_vars/mgrs.yml.sample
- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- group_vars/rbdmirrors.yml.sample
- group_vars/rgws.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-iscsi-gw/defaults/main.yml
- roles/ceph-mds/defaults/main.yml
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mon/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
- roles/ceph-rbd-mirror/defaults/main.yml
- roles/ceph-rgw/defaults/main.yml
The RHCS documentation mentionned in the default values and
group_vars directory are referring to RHCS 2.x while it should be
3.x.
Revolves: https://bugzilla.redhat.com/show_bug.cgi?id=1702732
> update default rhcs values and docs

- infrastructure-playbooks/purge-cluster.yml
We currently only purge rh_storage yum repository file but depending
on the ceph_repository value we are using, the ceph repository file
could have a different name.
Resolves: #4056
> purge-cluster: clean all ceph repo files

- roles/ceph-grafana/templates/grafana-server.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-node-exporter/templates/node_exporter.service.j2
- roles/ceph-osd/templates/ceph-osd.service.j2
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
When using podman, the systemd unit scripts don't have a dependency
on the network. So we're not sure that the network is up and running
when the containers are starting.
With docker this behaviour is already handled because the systemd
unit scripts depend on docker service which is started after the
network.
> podman: Add systemd dependency on network.target

- ceph-ansible.spec.in
This can be seen as a regression for customers who were used to deploy
in offline environment with custom repositories.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1673254
> spec: bring back possibility to install ceph with custom repo

- roles/ceph-node-exporter/tasks/setup_container.yml
- roles/ceph-node-exporter/templates/node_exporter.service.j2
Instead of using the modprobe command from the path in the systemd
unit script, we can use the modprobe ansible module.
That way we don't have to manage the binary path based on the linux
distribution.
Resolves: #4072
> ceph-node-exporter: use modprobe ansible module

- roles/ceph-node-exporter/templates/node_exporter.service.j2
069076b introduced a bug in the systemd unit script template. This
commit fixes the options used by the node-exporter container.
> ceph-node-exporter: Fix systemd template

- roles/ceph-dashboard/tasks/configure_dashboard.yml
This setting must be set to something resolvable.
See: ceph/ceph-ansible/issues/4085 for details
Fixes: #4085
> dashboard: fix dashboard_url setting

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-grafana/templates/grafana.ini.j2
Add a variable to support the allow_embedding support.
See ceph/ceph-ansible/issues/4084 for details.
Fixes: #4084
> dashboard: add allow_embedding support

- tests/functional/ooo-collocation/hosts
ceph-ansible@master isn't intended to deploy luminous.
Let's use latest-master on ceph-ansible@master branch
> tests: update docker image tag used in ooo job

- roles/ceph-mon/tasks/deploy_monitors.yml
since this task is designed to be always run on the first monitor, let's
enforce the container name accordingly otherwise it could fail like
following:
```
fatal: [mon1 -> mon0]: FAILED! => changed=true
cmd:
- docker
- exec
- ceph-mon-mon1
- ceph
- --cluster
- ceph
- --name
- mon.
- -k
- /var/lib/ceph/mon/ceph-mon0/keyring
- auth
- get-key
- mon.
delta: '0:00:00.085025'
end: '2019-06-12 06:12:27.677936'
msg: non-zero return code
rc: 1
start: '2019-06-12 06:12:27.592911'
stderr: 'Error response from daemon: No such container: ceph-mon-mon1'
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
```
> mon: enforce mon0 delegation for initial_mon_key register

- roles/ceph-handler/tasks/check_socket_non_container.yml
We're using fuser command to see if a process is using a ceph unix
socket file. But the fuser command runs through every PID present in
/proc/<PID> to see if one of them is using the file.
On a system running thousands processes, the fuser command can take
a long time to finish.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1717011
> ceph-handler: replace fuser by /proc/net/unix

- tox-dashboard.ini
We don't need to use dev_setup playbook on stable branch. We also
need to remove the dev container image variables and update the
value to match nautilus.
> tox-dashboard: update for nautilus

- roles/ceph-iscsi-gw/tasks/common.yml
- tests/functional/all_daemons/group_vars/all
if we don't assign the rbd application tag on this pool,
the cluster will get `HEALTH_WARN` state like following:
```
HEALTH_WARN application not enabled on 1 pool(s)
POOL_APP_NOT_ENABLED application not enabled on 1 pool(s)
application not enabled on pool 'rbd'
```
> iscsi: assign application (rbd) to pool 'rbd'

- roles/ceph-infra/tasks/main.yml
Ubuntu-based CI jobs often fail with error code 404 while installing
NTP daemons. Updating cache beforehand should fix the issue.
> ceph-infra: update cache for Ubuntu

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-infra/tasks/setup_ntp.yml
Since timesyncd is not available on RHEL-based OSs, change the default
to chronyd.
Fixes: https://github.com/ceph/ceph-ansible/issues/3628
> ceph-infra: make chronyd default NTP daemon

- tests/functional/all_daemons/container/group_vars/all
CI is facing issues where docker pull reach the timeout, let's increase
this to avoid CI failures.
> tests: increase docker pull timeout

- ansible.cfg
- roles/ceph-config/tasks/create_ceph_initial_dirs.yml
- tox-dashboard.ini
- tox-podman.ini
- tox-update.ini
- tox.ini
Because we're using vagrant, a ssh config file will be created for
each nodes with options like user, host, port, identity, etc...
But via tox we're override ANSIBLE_SSH_ARGS to use this file. This
remove the default value set in ansible.cfg.
Also adding PreferredAuthentications=publickey because CentOS/RHEL
servers are configured with GSSAPIAuthenticationis enabled for ssh
server forcing the client to make a PTR DNS query.
> tests: Update ansible ssh_args variable

- site-container.yml.sample
- site.yml.sample
ceph-dashboard should be deployed on either a dedicated mgr node or a
mon if they are collocated.
> dashboard: fix hosts sections in main playbook

- contrib/push-roles-to-ansible-galaxy.sh
- infrastructure-playbooks/gather-ceph-logs.yml
- tests/functional/lvm-auto-discovery/container/vagrant_variables.yml
- tests/functional/lvm-batch/container/vagrant_variables.yml
- tests/functional/lvm-osds/container/vagrant_variables.yml
- tests/functional/rgw-multisite/container/secondary/vagrant_variables.yml
- tests/functional/rgw-multisite/container/vagrant_variables.yml
The ceph restapi configuration was only available until Luminous
release so we don't need those leftovers for nautilus+.
> remove ceph restapi references

- plugins/callback/installer_checkpoint.py
- site-container.yml.sample
- site.yml.sample
This commits adds the support of the installer phase for dashboard,
grafana and node-exporter roles.
> Add installer phase for dashboard roles

- roles/ceph-common/tasks/installs/configure_redhat_local_installation.yml
- roles/ceph-iscsi-gw/tasks/container/containerized.yml
- roles/ceph-mgr/tasks/start_mgr.yml
- roles/ceph-mon/tasks/start_monitor.yml
- roles/ceph-nfs/tasks/pre_requisite_container.yml
- roles/ceph-nfs/tasks/start_nfs.yml
- roles/ceph-osd/tasks/start_osds.yml
- roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
- roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
We already set the become flag to true at a play level in the site*
playbooks so we don't need to set it at a task level.
> roles: Remove useless become (true) flag

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Otherwise content in /run/udev is mislabeled and prevent some services
like NetworkManager from starting.
(cherry picked from commit 80875adba791b732713f686a4e4eba182758dc9d)
> ceph-osd: do not relabel /run/udev in containerized context

- roles/ceph-facts/tasks/facts.yml
sometimes it can happen the following task fails:
```
TASK [ceph-facts : get current fsid] *******************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-dev-centos-container-update/roles/ceph-facts/tasks/facts.yml:78
Wednesday 19 June 2019  18:12:49 +0000 (0:00:00.203)       0:02:39.995 ********
fatal: [mon2 -> mon1]: FAILED! => changed=true
cmd:
- timeout
- --foreground
- -s
- KILL
- 600s
- docker
- exec
- ceph-mon-mon1
- ceph
- --cluster
- ceph
- daemon
- mon.mon1
- config
- get
- fsid
delta: '0:00:00.239339'
end: '2019-06-19 18:12:49.812099'
msg: non-zero return code
rc: 22
start: '2019-06-19 18:12:49.572760'
stderr: 'admin_socket: exception getting command descriptions: [Errno 2] No such file or directory'
stderr_lines: <omitted>
stdout: …
```
> facts: add a retry on get current fsid task

- library/ceph_volume.py
- library/test_ceph_volume.py
- roles/ceph-osd/tasks/start_osds.yml
The ceph-volume lvm list command takes ages to complete when having
a lot of LV devices on containerized deployment.
For instance, with 25 OSDs on a node it takes 3 mins 44s to list the
OSD.
Adding the max open files limit to the container engine cli when
executing the ceph-volume command seems to improve a lot thee
execution time ~30s.
This was impacting the OSDs creation with ceph-volume (both filestore
and bluestore) when using multiple LV devices.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1702285
> ceph-volume: Set max open files limit on container

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
As per [bz1718981](https://bugzilla.redhat.com/show_bug.cgi?id=1718981), this commit adds higher values to check the quorum status.
This is helpful for several OSP deployments that fail during the scale up.
Signed-off-by: fpantano <fpantano@redhat.com>
> Add higher retry/delay defaults to check the quorum status.

- infrastructure-playbooks/rolling_update.yml
3a100cfa5265b3a5327ef6a8d382a8059391b903 introduced an early check to
fail if the cluster isn't `HEALTH_OK`, this might be seen as a too aggressive
check. Passing `accept_health_warn=True` as an extra var makes it
possible to override this behavior.
> upgrade: add the possibility to upgrade even when HEALTH_WARN

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/debian_community_repository.yml
- roles/ceph-common/tasks/installs/debian_custom_repository.yml
- roles/ceph-common/tasks/installs/debian_dev_repository.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
- roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
The ansible_lsb fact is based on the lsb package (lsb-base,
lsb-release or redhat-lsb-core).
If the package isn't installed on the remote host then the fact isn't
populated.
```
"ansible_lsb": {},
```
Switching to the ansible_distribution_release fact instead.
> Change ansible_lsb by ansible_distribution_release

- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
There's two big issues with the current OSD restart script.
1/ We try to test if the ceph osd daemon socket exists but we use a
wildcard for the socket name : /var/run/ceph/*.asok.
This fails because we usually have multiple ceph osd sockets (or
other ceph daemon collocated) present in /var/run/ceph directory.
Currently the test fails with:
```console
bash: line xxx: [: too many arguments
```
But it doesn't stop the script execution.
Instead we can specify the full ceph osd socket name because we
already know the OSD id.
2/ The container filter pattern is wrong and could matches multiple
containers resulting the script to fail.
We use the filter with two different patterns. One is with the device
name (sda, sdb, ..) and the other one is with the OSD id (ceph-osd-0,
ceph-osd-15, ..).
In …
> ceph-handler: Fix OSD restart script

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/vagrant_variables.yml
This tries to first unmount any cephfs/nfs-ganesha mount point on client
nodes, then unmap any mapped rbd devices and finally it tries to remove
ceph kernel modules.
If it fails it means some resources are still busy and should be cleaned
manually before continuing to purge the cluster.
This is done early in the playbook so the cluster stays untouched until
everything is ready for that operation, otherwise if you try to redeploy
a cluster it could end up by getting confused by leftover from previous
deployment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1337915
> purge: ensure no ceph kernel thread is present

- roles/ceph-osd/tasks/scenarios/collocated.yml
- roles/ceph-osd/tasks/scenarios/non-collocated.yml
Same behaviour than ceph-volume (b987534). The ceph-disk command runs
faster when using ulimit nofile with container cli.
> ceph-disk: Set max open files limit on container

- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/hosts
This was removed because of broken repositories which made the CI
failing. That doesn't make sense anymore so adding back it
> tests: add nfs-ganesha testing

- infrastructure-playbooks/add-osd.yml
ceph-facts should be run before we play ceph-validate since it has
reference to facts that are set in ceph-facts role.
> add-osd: fix error in validate execution role

- plugins/actions/validate.py
Alphabetized ceph_repository_uca keys due to errors validating when
using UCA/queens repository on Ubuntu 16.04
An exception occurred during task execution. To see the full
traceback, use -vvv. The error was:
SchemaError: -> ceph_stable_repo_uca  schema item is not
alphabetically ordered
Closes: #4154
Signed-off-by: Gabriel Ramirez <gabrielramirez1109@gmail.com>
> validate.py: Fix alphabetical order on uca

- roles/ceph-facts/tasks/facts.yml
As the [bz1721914](https://bugzilla.redhat.com/show_bug.cgi?id=1721914) describes, the grafana_server_addr
fact is not defined if ip_version used is ipv6.
This commit adds the ip_version condition to set
correctly this fact.
> Set grafana_server_addr fact for ipv6 scenarios.

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
This environment variable was added in cb381b4 but was removed in
4d35e9e.
This commit reintroduces the change.
> ceph-osd: Add CONTAINER_IMAGE env variable

- site-container.yml.sample
- site.yml.sample
Even if dashboard feature is disabled then the installer status will
still report dashboard, grafana and node-exporter roles timing.
```console
INSTALLER STATUS **********************************
Install Ceph Monitor           : Complete (0:01:21)
Install Ceph Manager           : Complete (0:00:49)
Install Ceph Dashboard         : Complete (0:00:00)
Install Ceph Grafana           : Complete (0:00:02)
```
When need to set the dashboard_enabled condition on those installer
phase pre/post tasks.
> Add condition on dashboard installer phase

- tox-podman.ini
The first py.test call didn't have the reruns option. The commit
fixes it.
> tox-podman.ini: add missing reruns option

- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Since Mimic the radosgw socket has two extra fields in the socket
name (before the .asok suffix): <pid>.<ctid>
Before:
/var/run/ceph/ceph-client.rgw.cephaio-1.asok
After:
/var/run/ceph/ceph-client.rgw.cephaio-1.16913.23928832.asok
The radosgw restart script doesn't handle this and could fail during
an upgrade.
If the SOCKETS variable isn't defined in the script then the test
command won't fail because the return code is 0
$ test -S
$ echo $?
0
There multiple issues in that script:
- The default SOCKETS value isn't defined due to a typo
SOCKET vs SOCKETS.
- Because the socket name uses the pid then we need to check the
socket name after the service restart.
- After restarting the radosgw service we need to wait few seconds
otherwise the socket won't be created.
- Update the wget parameters …
> ceph-handler: Fix rgw socket in restart script

- tox.ini
adding back a sleep 30s after nodes have rebooted before running
testinfra.
This was removed accidentally by d5be83e
> tests: wait 30sec before running testinfra

- roles/ceph-mon/tasks/deploy_monitors.yml
The ability to add nodes with the monitor role to an existing cluster
whose name differs from the default name is fixed.
Signed-off-by: ilyashestopalov <usr.tester@yandex.ru>
> ceph-mon: Fix cluster name parameter

- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
The rgw restart script set the RGW_IP variable depending on ansible
variables:
- radosgw_address
- radosgw_address_block
- radosgw_interface
Those variables have default values defined in ceph-defaults role:
radosgw_interface: interface
radosgw_address: 0.0.0.0
radosgw_address_block: subnet
But in the rgw restart script we always use the radosgw_address value
instead of the radosgw_interface when defined because we aren't testing
the right default value.
As a consequence, the RGW_IP variable will be set to 0.0.0.0 even if
the ip address associated to the radosgw_interface variable is set
correctly. This causes the check_rest function to fail.
> ceph-handler: Fix radosgw_address default value

- roles/ceph-iscsi-gw/tasks/container/containerized.yml
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
On containerized deployment we need to bind mount the ceph-iscsi
directory to avoid writing the logs in the container.
The /var/log/ceph directory isn't use by rbd-targe-api/gw services
because they have their own log directories.
> ceph-iscsi-gw: Update log directories bind mount

- roles/ceph-grafana/tasks/configure_grafana.yml
According to the OSP pattern, we need the package-install tag
to control what is installed on the host. This commit just add
the missing tag to meet the TripleO requirements.
See: /issues/4197 for details
Fixes: #4197
> add tag on ceph-grafana-dashboards package.

- infrastructure-playbooks/shrink-osd-ceph-disk.yml
- shrink-osd should remove the prepare container to avoid a leftover preventing from redeploying an OSD after it has been removed.
- remove the gpt header on devices so if osds are redeployed with ceph-volume it will no complain because of this.
NOTE: this hasn't been backported from master because ceph-disk doesn't exist anymore as of stable-4.0
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1613735
> shrink-osd: (ceph-disk only) ease ceph-volume migration

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
We are currently using incorrect dashboard default port. The upstream
uses 8443 instead of 8234 by default. This should get us closer to the
upstream project.
> dashboard: Use upstream default port

- roles/ceph-dashboard/tasks/configure_dashboard.yml
Some dashboard_rgw_api_* variables are using the bool filter but those
variables are strings with an empty string as default value.
So we should test the variable against an empty string instead of a
bool.
```yaml
dashboard_rgw_api_host: ''
dashboard_rgw_api_port: ''
dashboard_rgw_api_scheme: ''
dashboard_rgw_api_admin_resource: ''
```
Resolves: #4179
> ceph-dashboard: remove bool filter for rgw vars

- tox.ini
This commit fixes the purge_* scenario names in stable-3.1
> tests: fix purge scenarios names

- roles/ceph-validate/tasks/check_devices.yml
The message prints the whole content of the registered variable in the
playbook, this is not needed and makes the message pretty unclear and
unreadable.
```
"msg": "{'_ansible_parsed': True, 'changed': False, '_ansible_no_log': False, u'err': u'Error: Could not stat device /dev/sdf - No such file or directory.\\n', 'item': u'/dev/sdf', '_ansible_item_result': True, u'failed': False, '_ansible_item_label': u'/dev/sdf', u'msg': u\"Error while getting device information with parted script: '/sbin/parted -s -m /dev/sdf -- unit 'MiB' print'\", u'rc': 1, u'invocation': {u'module_args': {u'part_start': u'0%', u'part_end': u'100%', u'name': None, u'align': u'optimal', u'number': None, u'label': u'msdos', u'state': u'info', u'part_type': u'primary', u'flags': None, u'device': u'/dev/sdf', u'unit': …
```
> validate: improve message printed in check_devices.yml

- roles/ceph-handler/handlers/main.yml
since everything is already in a block with the same condition, it's not
needed to leave all of them on these tasks.
> handler: remove legacy condition

- roles/ceph-infra/tasks/configure_firewall.yml
The Prometheus porrt 9090 isn't open in the firewall configuration.
Also the dashboard task on the grafana node was not required because
it's already present on the mgr node.
> ceph-infra: Open prometheus port

- roles/ceph-infra/handlers/main.yml
Both ntp and chrony daemon use variable for the service name because it
could be different depending on the GNU/Linux distribution.
This has been update in 9d88d3199 for chrony but only for the start part
not for the handler.
The commit fixes this for both ntp and chrony.
> ceph-infra: update handler with daemon variable

- tox-dashboard.ini
- tox-update.ini
- tox.ini
this setting is not needed here since we explicitely set it for
container and non container context.
> tests: remove useless setting

- roles/ceph-validate/tasks/check_devices.yml
ceph-volume will complain if gpt headers are found on devices.
This commit checks whether a gpt header is present on devices passed in
`devices` variable and fail early.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1730541
> validate: fail if gpt header found on unprepared devices

- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
fbf4ed42aee8fa5fd18c4c289cbb80ffeda8f72e introduced a bug when
container binary is podman.
podman doesn't support ps -f using regular expression, the container id
is never set in the restart script causing the handler to fail.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1721536
> handler: fix bug in osd handlers

- roles/ceph-mds/tasks/create_mds_filesystems.yml
Previously cephfs_pools items used to have a pgs: key but not
pgp_num: nor pg_num:
> Fix backward compat with old cephfs_pools format

- tests/functional/all_daemons/group_vars/nfss
in stable-4.0, nfs-ganesha 2.8 should be used.
> tests: bump nfs-ganesha version

- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/hosts
- tox-update.ini
nfs-ganesha repositories @ dev are broken, this commit disables the
nfs-ganesha deployment so the CI isn't stuck.
> tests: disable nfs-ganesha deployment

- infrastructure-playbooks/shrink-mgr.yml
- infrastructure-playbooks/shrink-rbdmirror.yml
Use facility built-in in Ansible to check whether a command was executed
successfully rather looking at its return value.
> infra-playbooks: rewite a condition for better readability

- roles/ceph-osd/tasks/start_osds.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-osd/templates/systemd-device-to-id.sh.j2
When using containerized deployment we have to create the systemd
service unit based on a template.
The current implementation with ceph-disk is using the device name
as paramater to the systemd service and for the container name too.
```console
$ systemctl start ceph-osd@sdb
$ docker ps --filter 'name=ceph-osd-*'
CONTAINER ID IMAGE                        NAMES
065530d0a27f ceph/daemon:latest-luminous  ceph-osd-strg0-sdb
```
This is the only scenario (compared to non containerized or
ceph-volume based deployment) that isn't using the OSD id.
```console
$ systemctl start ceph-osd@0
$ docker ps --filter 'name=ceph-osd-*'
CONTAINER ID IMAGE                        NAMES
d34552ec157e ceph/daemon:latest-luminous  ceph-osd-0
```
Also if the device mapping doesn't persist to system reboot (ie sdb …
> ceph-osd: use OSD id with systemd ceph-disk

- tests/functional/ooo-collocation/hosts
- tests/functional/tests/osd/test_osds.py
- tox.ini
The ooo-collocation scenario was still using an old container image and
doesn't match the requirement on latest stable-3.2 code. We need to use
at least the container image v3.2.5.
Also updating the OSD tests to reflect the changes introduced by the
commit bedc0ab because we don't have the OSD systemd unit script using
device name anymore.
> tests: Update ooo-collocation scenario

- roles/ceph-dashboard/tasks/configure_dashboard.yml
- tests/functional/podman/hosts
- tests/functional/podman/vagrant_variables.yml
For some reason, this is making the playbook failing like following:
```
TASK [ceph-dashboard : create radosgw system user] ************************************************************************************************************************************************************************************************************************************************************************
************************************************************************************************************
task path: /home/guits/ceph-ansible/roles/ceph-dashboard/tasks/configure_dashboard.yml:106
Tuesday 30 July 2019  10:04:54 +0200 (0:00:01.910)       0:11:22.319 **********
FAILED - RETRYING: create radosgw system user (3 retries left).
FAILED - RETRYING: create radosgw system user (2 retries left). …
```
> dashboard: fix timeout usage on rgw user creation command

- tests/functional/shrink_rgw/container/group_vars/all
- tests/functional/shrink_rgw/group_vars/all
The shrink_rgw scenario has been merge just after the PR about enable
ceph dashboard by default.
So right now the shrink_rgw scenrio doesn't have nodes in the grafana
group and fails.
We just need to set dashboard_enabled to false.
> tests/shrink_rgw: Disable dashboard

- site.yml.sample
in non-containerized deployment, we can't deploy dashboard on Debian
based distribution since the package `ceph-grafana-dashboards` isn't
available.
> dashboard: do not deploy on Debian based OS/non-containerized

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
Allow to configure the rgw beast frontend in addition to civetweb
(default value).
Add rgw_thread_pool_size variable with 512 as default value and keep
backward compatibility with num_threads option when using civetweb.
Update radosgw_civetweb_num_threads to reflect rgw_thread_pool_size
change.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1733406
(cherry picked from commit d17b1b48b6d4259f88445a0752e1c13b4522ced0)
> rgw: add beast frontend

- roles/ceph-grafana/tasks/configure_grafana.yml
- roles/ceph-grafana/tasks/setup_container.yml
We don't need to create a grafana system user (in fact we even don't
set the righ uid to this user) because we're using a container setup.
Instead we just need to be sure to set the owner/group to 472 (grafana
user/group from the container) like we do for ceph/167.
We don't need to set the user/group recursively on /etc/grafana
directory in a dedicated task.
Also on Ubuntu system, the ceph-grafana-dashboards isn't present so on
non containerized deployment we won't have the
/etc/grafana/dashboards/ceph-dashboard directory present (coming with
the package) so we need to be sure it exists.
> ceph-grafana: Set grafana uid/gid on files

- roles/ceph-infra/tasks/configure_firewall.yml
We don't have a reason to not apply firewall rules on the host when
using a containerized deployment.
The TripleO environments already manage the ceph firewall rules outside
ceph-ansible and set the configure_firewall variable to false.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1733251
> ceph-infra: Apply firewall rules with container

- roles/ceph-validate/tasks/check_system.yml
Current behaviour will fail on openSUSE Leap 15.0 and 15.1, that are way newer than openSUSE Leap 42.x, as unfortunately openSUSE switched from 42.x to 15.x to match SLES15 development.
Successfully tested on Leap 15.1 using this `group_vars/all.yml`:
```
---
ceph_origin: distro
ceph_stable_release: nautilus
#
public_network: 0.0.0.0/0
monitor_address_block: 10.11.12.0/24
cluster_network: 10.11.13.0/24
```
> openSUSE: support newer Leap releases

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/dashboard.yml
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-defaults/defaults/main.yml
Because we need to execute commands from a monitor node (the first one 
in the mons list) we are using delegate_to option.
If there's multiple nodes running the ceph-dashboard role then the 
delegated task will be executed multiple times.
Also remove a mgr config-key option not present for nautilus+ releases.
> ceph-dashboard: Add run_once on delegate tasks

- infrastructure-playbooks/shrink-osd-ceph-disk.yml
Since bedc0ab we now manage ceph-osd systemd unit scripts based on ID
instead of device name but it was not present in the shrink-osd
playbook (ceph-disk version).
To keep backward compatibility on deployment that didn't do yet the
transition on OSD id then we should stop unit scripts for both device
and ID.
This commit adds the ulimit nofile container option to get better
performance on ceph-disk commands.
It also fixes an issue when the OSD id matches multiple OSD ids with
the same first digit.
```console
$ ceph-disk list | grep osd.1
/dev/sdb1 ceph data, prepared, cluster ceph, osd.1, block /dev/sdb2
/dev/sdg1 ceph data, prepared, cluster ceph, osd.12, block /dev/sdg2
```
Finally removing the shrinked OSD directory.
> shrink-osd: Stop ceph-disk container based on ID

- roles/ceph-mgr/tasks/mgr_modules.yml
There's no need to use `shell` module here.
Instead of using `| python -c`, let's use `from_json` filter.
> mgr: refact 'wait for all mgr to be up' task

- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/hosts
- tox-update.ini
This reverts commit 83940e624bc4faf6bc7bb1a7637711556d6b3e8c.
Because nfs-ganesha@master (2.9-dev) build has been fixed by [1] then
we can test nfs-ganesha in the CI for master/octopus.
[1] https://github.com/ceph/ceph-build/pull/1346
> Revert "tests: disable nfs-ganesha deployment"

- tox.ini
Fix bad paths for infra_lv_create
(issue: #4311)
command` tox -e infra_lv_create` fails
solution: change paths inside tox.ini file
Signed-off-by: Bogomolov Igor <igor95n@gmail.com>
> [skip ci] tests: fix wrong paths for lv-create in tox.ini

- roles/ceph-osd/tasks/start_osds.yml
Otherwise it will fail when running rolling_update.yml playbook because
of `serial: 1` usage.
The task which copies the script is run against the current node being
played only whereas the task which runs the script is run against all
nodes in a loop, it ends up with the typical error:
```
2019-08-08 17:47:05,115 p=14905 u=ubuntu |  failed: [magna023 -> magna030] (item=magna030) => {
"changed": true,
"cmd": [
"/usr/bin/env",
"bash",
"/tmp/systemd-device-to-id.sh"
],
"delta": "0:00:00.004339",
"end": "2019-08-08 17:46:59.059670",
"invocation": {
"module_args": {
"_raw_params": "/usr/bin/env bash /tmp/systemd-device-to-id.sh",
"_uses_shell": false,
"argv": null,
"chdir": null,
"creates": null,
"executable": null,
"removes": null,
"stdin": null,
"warn": true
}
},
"item": "magna030",
"msg": …
```
> osd: copy systemd-device-to-id.sh on all osd nodes before running it

- infrastructure-playbooks/rolling_update.yml
we must use the ids instead of device names in the tasks executed in
`post_tasks` for the osd rolling update otherwise it ends up with old
systemd units enabled.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1739209
> update: use ids to restart osds instead of device name

- infrastructure-playbooks/shrink-mon.yml
- raw_install_python.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-handler/templates/restart_mon_daemon.sh.j2
- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-osd/tasks/openstack_config.yml
- tests/functional/tests/mgr/test_mgr.py
- tox.ini
This PR gathers various fixes and improvements:
- refacts the raw installation of python,
- replaces some `shell` module with `command`
- get rid of complex tests using a combination of bash commands redirected in python in order to parse json data where we can use the `from_json` filter,
- update some functional tests given the json data structure returned by `ceph -s` has changed in octopus.
> various fixes and improvements

- CONTRIBUTING.md
Only maintainers can set labels on PRs, so let's clarify that point in
the doc which says something confusing at the moment.
> doc: update backport section

- .mergify.yml
automatic merging by mergify is failing for a while now.
Until we can figure out what's wrong, let's disable it on master so we don't merge "failing" PRs although they passed all scenarios.
> mergify: disable automatic merging on master

- roles/ceph-osd/tasks/openstack_config.yml
just like `ceph_osd_pool_default_size`, a pool size might change after initial deployment.
Having this condition prevents from customizing the pool in that case.
This is not needed so let's remove it.
> osd: remove useless condition

- plugins/actions/validate.py
we shouldn't validate these two variables when `osd_auto_discovery` is
set.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1644623
> validate: do not validate devices/lvm_volumes in osd_auto_discovery case

- RELEASE-NOTE.md
In `stable-4.0`, the group name `iscsi-gws` will go away and some rgw
systemd service names will disappear as well
(`ceph-rgw@<hostname>.service`, `ceph-radosgw@<hostname>.service`,
`ceph-radosgw@radosgw.<hostname>.service`,
`ceph-radosgw@radosgw.gateway.service`)
> [skip ci] release-note: add two deprecations warning and removal

- roles/ceph-common/tasks/installs/install_on_suse.yml
roles/ceph-common/tasks/installs/install_on_suse.yml: remove the task that
installs the dependencies, as this is done later in install_suse_packages.yml
See the original discussion [here](https://github.com/ceph/ceph-ansible/pull/4324#discussion_r315541367).
> common: remove duplicate task installing suse dependencies

- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Otherwise rgw handler ends up with an error when using https.
> handler: do not validate the server certificate against the CA

- roles/ceph-mds/tasks/non_containerized.yml
install packages on SUSE/openSUSE distributions, using the same logic as on RedHat-based distributions.
Fixes #4340
> install ceph-mds packages on SUSE/openSUSE

- roles/ceph-validate/tasks/check_nfs.yml
`roles/ceph-nfs/tasks/pre_requisite_non_container.yml`: fail on openSUSE Leap using `ceph_origin = distro`, as the ganesha packages are not available from the distribution repositories
Fixes #4342  in that that is desired behaviour.
> validate: fail on openSUSE Leap using distro packages

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
By changing the set ownership command from using the file module in combination with a with_items loop to a raw chown command, we can achieve a 98% performance increase here.
On a ceph cluster with a significant amount of directories and files in /var/lib/ceph, the file module has to run checks on ownership of all those directories and files to determine whether a change is needed.
In this case, we just want to explicitly set the ownership of all these directories and files to the ceph_uid
Signed-off-by: Kevin Jones kevinjones@redhat.com
> Set proper ownership command performance improvement

- library/ceph_volume.py
- library/test_ceph_volume.py
- roles/ceph-osd/tasks/start_osds.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
On containerized deployment, the OSD entrypoint runs some ceph-volume
commands (lvm/simple scan and/or activate) which perform badly without
the ulimit option.
This option was added for all previous ceph-volume commands but not on
the ceph-osd container startup.
Also updating hard limit value to 4096 to reflect default baremetal
value.
> ceph-osd: Add ulimit nofile on container start

- roles/ceph-mgr/tasks/main.yml
This can't be backported from master since there was too many
modifications meantime.
When mgr aren't all ready, sometimes the following error can show up:
```
stderr: 'Error ENOENT: all mgr daemons do not support module ''status'', pass --force to force enablement'
```
This commit adds a check so all mgr are available when we try to enable
modules.
> mgr: add a check task for all mgr to be up

- roles/ceph-validate/tasks/check_system.yml
Fail if SUSE distributions other than 15.x are found, similar to what we have for openSUSE
> roles/ceph-validate/tasks/check_system.yml: fail on unsupported SUSE versions

- raw_install_python.yml
- roles/ceph-common/tasks/installs/install_on_suse.yml
- roles/ceph-common/tasks/installs/install_suse_packages.yml
- roles/ceph-infra/tasks/configure_firewall.yml
- roles/ceph-mds/tasks/non_containerized.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
As SUSE 15.x and openSUSE Leap 15.x share the same base, make it clear that both are targeted by the respective tasks
> fix SUSE/openSUSE naming

- roles/ceph-config/tasks/main.yml
The "run 'ceph-volume lvm batch --report' to see how many osds are to be
created" and "run 'ceph-volume lvm list' to see how many osds have already been
created" statements only register the lvm_batch_report and lvm_list variables.
Running those ceph-volume commands should never produce a change on the system.
Adding changed_when: false prevents irrelevant change messages from Ansible.
> ceph-config: Set changed_when to false on fact gathering statements

- roles/ceph-common/tasks/installs/install_on_suse.yml
- roles/ceph-validate/tasks/main.yml
Fixes: #4362
There are two valid combinations of `ceph_origin` and `ceph_repository` on
SUSE/openSUSE:
- ceph_origin == 'distro'
- ceph_origin == 'repository' and ceph_repository == 'obs'
The current when condition would fail even in the valid second combination,
as ceph_origin != distro would be true then
Signed-off-by: Johannes Kastl <kastl@b1-systems.de>
> fix when-syntax in roles/ceph-common/tasks/installs/install_on_suse.yml

- plugins/actions/validate.py
- Allow `obs` as a value for `ceph_repository`
- Validate that ceph_obs_repo is defined if `ceph_repository` is set to `obs`
- Validate that `ansible_distribution` is set to `openSUSE Leap` if `ceph_repository` is set to `obs`
Todo:
> Allow 'obs' as a value for ceph_repository 

- roles/ceph-config/tasks/main.yml
- roles/ceph-mds/tasks/common.yml
- roles/ceph-mgr/tasks/common.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
- roles/ceph-osd/tasks/common.yml
- roles/ceph-rgw/tasks/common.yml
This PR adds parametrization of directory mode when creating some basic directories for ceph.
This includes 2 most important from corporate security standpoint:
- /etc/ceph
- /var/lib/ceph
In next steps this can be further improved (by eg. moving `ceph_directories_mode` to group_vars or some role defaults).
This is solution for problem described in
https://github.com/ceph/ceph-ansible/issues/2920
> corporate security does not like 0755 mode on directories

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/osds.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-defaults/defaults/main.yml
The "osd blacklist" isn't an osd caps but should be used with mon caps.
Also the correct caps for this is: 'allow command "osd blacklist"'.
The current change is breaking the openstack and clients keyrings.
By using the profile rbd (which is already used) we already rely on the
ability to blacklist dead client.
Resolves: #4385
> Remove osd blacklist from osd caps

- roles/ceph-mon/templates/ceph-mon.service.j2
On containerized deployment, the mon container sometimes needs to
access to the radosgw endpoint (via the radosgw-admin command). When
using TLS on the radosgw with self-signed certificates then we need to
access to the CA certification from the mon container.
The CA certificate needs to be added on the host and then the directory
will be bind mount on the container.
Resolves: #4358
> ceph-mon: Bind mount the ca-trust directory

- roles/ceph-facts/tasks/facts.yml
If the user has set the `ansible_python_interpreter`, ansible will not try to discover python, so `discovered_python_interpreter` will not be set.
Solution: Use `ansible_python_interpreter` as fallback, if `discovered_python_interpreter` is unset.
> generating cluster fsid failed if ansible_python_interpreter is set

- roles/ceph-common/tasks/installs/suse_obs_repository.yml
roles/ceph-common/tasks/installs/suse_obs_repository.yml:
ansible's zypper_repository module does not know a parameter 'uri', this is called 'repo' instead
> fix openSUSE OBS repo creation

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Instead of hardcoding `luminous`, use the `ceph_stable_release` variable to point to the correct repository.
Uncomment this in `roles/ceph-defaults/defaults/main.yml` to be avaible, as it is only used if `ceph_repository` is set to `obs`.
Could not be tested due to #4361.
> openSUSE OBS repository using ceph_stable_release

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/osds.yml.sample
- group_vars/rhcs.yml.sample
- plugins/actions/validate.py
- roles/ceph-common/tasks/installs/debian_custom_repository.yml
- roles/ceph-common/tasks/installs/redhat_custom_repository.yml
- roles/ceph-defaults/defaults/main.yml
Currently custom repo doesn't have apt or rpm key defined,
so apt update gonna be failed.
This PR should fix that.
> Fix debian custom repo

- roles/ceph-grafana/tasks/configure_grafana.yml
- roles/ceph-grafana/templates/datasources-ceph-dashboard.yml.j2
- roles/ceph-grafana/templates/grafana.ini.j2
- roles/ceph-prometheus/templates/prometheus.yml.j2
We have no reason to make grafana container
listen on *, so this change adds the
http_addr option to the grafana config file
and adds the related option on the wait_for
tasks.
> Add http_addr option to grafana config

- tests/functional/all_daemons/container/hosts-ubuntu
- tests/functional/all_daemons/hosts-switch-to-containers
- tests/functional/all_daemons/hosts-ubuntu
5b29144 change the mgr node to a dedicated node instead of the first
monitor node.
But the change didn't update the switch-to-containers inventory which
cause this playbook to fail.
Also update the ubuntu inventory to have the same configuration.
> tests: update dedidated mgr node all_daemons

- roles/ceph-facts/tasks/facts.yml
This change fixes the discovered_interpreter_python variable
name that was "discovered_python_interpreter" and caused a
failure in OSP deployments.
> Fix discovered_interpreter_python variable

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
We should pin down the versions of downstream container for dashboard
instead of using upstream containers.
Please let me know if there is a better/any other way of overriding the downstream versions of these containers.
> rhcs: Pin downstream containers

- group_vars/rbdmirrors.yml.sample
- roles/ceph-rbd-mirror/defaults/main.yml
- roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
- roles/ceph-rbd-mirror/tasks/main.yml
The rbd mirror configuration was only available for non containerized
deployment and was also imcomplete.
We now enable the mirroring on the pool and add the remote peer in both
scenarios.
The default mirroring mode is set to 'pool' but can be configured via
the ceph_rbd_mirror_mode variable.
This commit also fixes an issue on the rbd mirror command if the ceph
cluster name isn't using the default value (ceph) due to a missing
--cluster parameter to the command.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1665877
> rbd-mirror: configure pool and peer

- tox.ini
The ANSIBLE_CONFIG value wasn't set correctly for two scenarios. This
environment variable doesn't use '-F'.
> tox: Fix incorrect ANSIBLE_CONFIG value

- roles/ceph-infra/tasks/configure_firewall.yml
ceph.conf supports a comma separated list of
subnet CIDR's for the public_network and the
cluster network. ceph-ansible should support
setting up the firewall for this configuration.
Closes: #4425
Related: #4333
https://docs.ceph.com/docs/nautilus/rados/configuration/network-config-ref/#network-config-settings
Signed-off-by: Harald Jensås <hjensas@redhat.com>
> Support comma-delimited subnets in firewall

- roles/ceph-handler/tasks/check_running_containers.yml
- roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
- roles/ceph-nfs/tasks/main.yml
Ganesha cannot be operated active/active, in those deployments
where it is managed by pacemaker the container name can be
different than the default.
This change uses "ceph_nfs_service_suffix" where previously
missing to ensure tasks will work with customized names.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1750005
Signed-off-by: Giulio Fidente <gfidente@redhat.com>
> Look for additional names when checking ceph-nfs container status

- tox-update.ini
During an upgrade we're installation the platform with the stable-3.2
branch. But the ansible configuration is still using the file from the
current branch which could have some differences.
Instead we can override the ANSIBLE_CONFIG environment variable with
the stable-3.2 commands.
> tox-update: set the ansible.cfg path before update

- roles/ceph-rbd-mirror/tasks/common.yml
- roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
The admin keyring isn't present by default on the rbd mirror nodes so
the rbd commands related to the mirroring confguration will fail.
Instead we can use the rbd mirror client keyring.
> rbd-mirror: Use the rbd mirror client keyring

- roles/ceph-handler/handlers/main.yml
In containerized deployment, the restart OSD handler couldn't be
triggered in most ansible execution.
This is due to the usage of run_once + a condition on the inventory
hostname and the last filter.
The run_once is triggered first so ansible will pick a node in the
osd group to execute the restart task. But if this node isn't the
last one in the osd group then the task is ignored. There's more
probability that the task will be ignored than executed.
> ceph-handler: Fix osd restart condition

- tests/functional/tests/rgw/test_rgw_tuning.py
Since the pg_autoscaler has been enabled recently in ceph, this check
should stick to validate the requested pools are well created only.
> tests: do not rely on pg_num to validate rgw_tuning_pools

- infrastructure-playbooks/shrink-mon.yml
If we're looking at the mon hostname in the ceph status output then
there's some scenarios where this could be true.
If we collocate some services (mons, mgrs, etc..) then the hostname of
the monitor to shrink will still be present in the ceph status (like
in mgrs or other).
Instead we should check the hostame only in the mon part of the output.
> shrink-mon: search mon in the quorum_names list

- raw_install_python.yml
On RHEL 8 system we should check the /usr/libexec/platform-python path
instead of installing python36 package.
[DEPRECATION WARNING]: Distribution redhat 8.0 on host xxxxx should use
/usr/libexec/platform-python, but is using /usr/bin/python for backward
compatibility with prior Ansible releases. A future Ansible release will
default to using the discovered platform python for this host.
> rhel8: add default python bin path

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- rhcs_edits.txt
- roles/ceph-container-common/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
The registry.redhat.io regsitry requires authentication so before pulling
the RHCS 4 container images from the registry we need to do the login
step.
This is done via the new ceph_docker_registry_auth variable. The
default value is false but true for RHCS setup.
When set to true, you need to provide the username and password
for the registry via the associated variables.
This patch also updates the ceph_docker_registry value for RHCS setup.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1748911
> container: Allow to use registry authentication

- infrastructure-playbooks/shrink-rgw.yml
the confirmation play's name should confirm removing rgw instead of
monitor
signed-off-by: Mehdy Khoshnoody <mehdy.khoshnoody@gmail.com>
> shrink-rgw.yml: fix confirmation play's name

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Since we change the way to run the OSD containers with the ID instead
of the device name, we lost the ability to use loop devices.
Loop devices are like nvme or cciss devices because the partitions are
referenced with an extra 'p' before the partition number.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1749097
> ceph-osd: handle loop devices with containers

- roles/ceph-mon/tasks/docker/main.yml
This commit replaces a `command` task with `ceph_key` in order to create
mgr keyrings.
This allows us to use `mode` parameter to set the right mode on
generated keys.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1734513
> mon: use ceph_key module for containerized mgr keyring creation

- Vagrantfile
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-facts/tasks/facts.yml
This change just adds the task to inject from the
ceph dashboard mgr module the required layouts
to show all the cluster metrics on the grafana
instance.
> Inject ceph grafana dashboard layouts

- group_vars/nfss.yml.sample
- roles/ceph-nfs/defaults/main.yml
- roles/ceph-nfs/templates/ganesha.conf.j2
Depending on the infrastruture (w/o kerberos auth) then the SecType
value could be different.
Currently this value is hardcoded in the NFS Ganesha template. Instead
we can use a variable.
The default value is still the same to avoid breaking the backward
compatibility.
Closes: #4459
> ceph-nfs: Allow to configure SecType value

- roles/ceph-common/vars/main.yml
Currently, ceph package only an meta-package that do not contain
actual software, but simply depend on other packages. It's been few
release since debian stretch (official), ubuntu bionic (official),
ubuntu uca repository and upstream debian-jewel.
As we only support nautilus and higher release for master branch,
I propose to drop ceph package and use ceph-base instead for repository
model other than rhcs so debian ceph install will be more minimalis.
Signed-off-by: Anthony Rusdi <33247310+antrusd@users.noreply.github.com>
> ceph-common: install only necesarry ceph-* packages on debian

- roles/ceph-dashboard/tasks/configure_dashboard.yml
The set-prometheus-api-host ceph dashboard subcommand was missing in
ceph-dashboard role. Only grafana and alermanager were present.
This commit also remove the trailing slash at the end of the host/url
values.
Closes: #4453
> ceph-dashboard: Add prometheus api host

- .travis.yml
- ansible.cfg
- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
- plugins/filter/ipaddrs_in_ranges.py
- plugins/filter/test_ipaddrs_in_ranges.py
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-facts/tasks/set_monitor_address.yml
- roles/ceph-facts/tasks/set_radosgw_address.yml
- roles/ceph-validate/tasks/check_ipaddr_mon.yml
- tox-podman.ini
- tox-update.ini
- tox.ini
Replace ipaddr() with ips_in_ranges()
This change implements a filter_plugin that is used in the
ceph-facts, ceph-validate roles and infrastucture-playbooks.
The new filter plugin will return a list of all IP address
that reside in any one of the given IP ranges. The new filter
replaces the use of the ipaddr filter.
ceph.conf already support a comma separated list of CIDRs
for the public_network and cluster_network options.
Changes: [1] and [2] introduced a regression in ceph-ansible
where public_network can no longer be a comma separated list
of cidrs.
With this change a comma separated list of subnet CIDRs can
also be used for monitor_address_block and radosgw_address_block.
NOTE:
* This change also updates the RPM spec file so that
the filter_plugins are copied to the buildroot.
* Add …
> Replace ipaddr() with ips_in_ranges()

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- raw_install_python.yml
- roles/ceph-defaults/defaults/main.yml
The package python-xml is needed for ansible's zypper module to interact with
the zypper package management tool.
roles/ceph-defaults/defaults/main.yml:
Remove python-xml from variable suse_package_dependencies to only
install python-xml on SUSE/openSUSE if python is not found.
raw_install_python.yml already contains all the logic needed to check
if there is a valid python installation, so this is better suited there.
openSUSE Leap 15.x / SLES 15.x do no longer have /usr/bin/python,
only /usr/bin/python3, which already contains the xml module, so
nothing needs to be installed in that case.
> move python-xml to raw_install_python.yml

- infrastructure-playbooks/rolling_update.yml
after all mon are upgraded, let's reset mon_host which is used in the
rest of the playbook for setting `container_exec_cmd` so we are sure to
use the right value.
Typical error:
```
failed: [mds0 -> mon0] (item={u'path': u'/var/lib/ceph/bootstrap-mds/ceph.keyring', u'name': u'client.bootstrap-mds', u'copy_key': True}) => changed=true
ansible_loop_var: item
cmd:
- docker
- exec
- ceph-mon-mon2
- ceph
- --cluster
- ceph
- auth
- get
- client.bootstrap-mds
delta: '0:00:00.016294'
end: '2019-09-27 13:54:58.828835'
item:
copy_key: true
name: client.bootstrap-mds
path: /var/lib/ceph/bootstrap-mds/ceph.keyring
msg: non-zero return code
rc: 1
start: '2019-09-27 13:54:58.812541'
stderr: 'Error response from daemon: No such container: ceph-mon-mon2'
stderr_lines: <omitted>
stdout: ''
stdout_lines: …
```
> update: reset mon_host after mons upgrade

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- rhcs_edits.txt
- roles/ceph-defaults/defaults/main.yml
We are hitting several issues when deploying downstream (and with downstream images). We need to change the floating tags for the ose containers since these changed when we switched from unauthenticated registry to registry.redhat.io.
The downstream grafana container is also a lot less user-friendly and you need to handle all the options and plugin installation manually instead. We also need to make sure the container is run with uid 472 and that all the configurations paths are correct.
> dashboard: fix downstream deployment of the dashboard

- roles/ceph-common/vars/main.yml
This reverts commit 58b27ef0b3bbd64d8a66da24d702f3ff761fe6ec.
This is breaking debian based OS deployments.
> Revert "ceph-common: install only necesarry ceph-* packages on debian"

- tests/functional/all_daemons/ceph-override.json
This was added for debugging purpose.
It's generating very large log output, let's remove this now.
> tests: remove debug log verbosity

- .github/stale.yml
enable stale bot in order to close PR with no recent activity.
> repo: enable stalebot

- roles/ceph-config/tasks/main.yml
CEPH_CONTAINER_IMAGE should be None if containerized_deployment
is False.
Resolves: #4498
(cherry picked from commit 70a4368bc5a58f198b23751f8478f2d79bc5e9f4)
> ceph-config: do not always assume containers when calculating num_osds

- roles/ceph-facts/tasks/facts.yml
e695efc hasn't been updated with the changes introduced in 9bb11c7 so
the ips_in_ranges filter isn't used for an external grafana instance.
> ceph-facts: update external grafana fact filter

- roles/ceph-validate/tasks/check_devices.yml
Check for gpt header when osd scenario is lvm or lvm batch.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1731310
> validate: fix gpt header check

- roles/ceph-facts/tasks/facts.yml
During the rolling_update scenario, the fsid value is retrieve from the
current ceph cluster configuration via the ceph daemon config command.
This command tries first to resolve the admin socket path via the
ceph-conf command.
Unfortunately this command won't work if you have a duplicate key in the
ceph configuration even if it only produces a warning. As a result the
task will fail.
Can't get admin socket path: unable to get conf option admin_socket for
mon.xxx: warning: line 13: 'osd_memory_target' in section 'osd' redefined
Instead of using ceph daemon we can use the --admin-daemon option
because we already know what the socket admin path value based on the
ceph cluster and mon hostname values.
Closes: #4492
> ceph-facts: use --admin-daemon to get fsid

- roles/ceph-client/tasks/pre_requisite.yml
- roles/ceph-iscsi-gw/tasks/common.yml
- roles/ceph-mds/tasks/common.yml
- roles/ceph-mgr/tasks/common.yml
- roles/ceph-nfs/tasks/pre_requisite_container.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
- roles/ceph-osd/tasks/common.yml
- roles/ceph-osd/tasks/openstack_config.yml
- roles/ceph-rbd-mirror/tasks/common.yml
- roles/ceph-rgw/tasks/common.yml
There is no need to get n * number of nodes the different keyrings.
Adding a `run_once: true` here avoid running a ceph command too many
times which could be impacting large cluster deployment.
> common: improve keyrings generation

- Vagrantfile
because of the current ip address assignation, it's not possible to
deploy more than 9 nodes per daemon type.
This commit refact a bit and allows us to get around this limitation.
> Vagrantfile: support more than 9 nodes per daemon type

- roles/ceph-facts/tasks/set_radosgw_address.yml
e695efc introduced a regression in the _radosgw_address fact when using
the radosgw_address_block variable.
There's no item there because we don't use the items lookup. This is
only used for _monitor_address with monitor_address_block.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1758099
> ceph-facts: fix _radosgw_address with block

- roles/ceph-handler/handlers/main.yml
When using the ansible --limit option on one or few OSD nodes and if the
handler is triggered then we will restart the OSD service on all OSDs
nodes instead of the hosts limited by the limit value.
Even if the play is limited by the --limit value we are using all OSD
nodes from the OSD group.
```yaml
with_items: '{{ groups[osd_group_name] }}'
```
Instead we should iterate only on the nodes present in both OSD group and
limit list.
> ceph-handler: don't restart all OSDs with limit

- roles/ceph-osd/tasks/openstack_config.yml
let's use `until` instead of doing test in bash using python oneliner
also, use `command` instead of `shell`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1603551
(cherry picked from commit c76cd5ad844b71a41d898febafda326ad067cc05)
> osd: refact 'wait for all osd to be up' task

- infrastructure-playbooks/dashboard.yml
The block section were used with the dashboard_enabled condition when
the code was included in the main playbooks.
Because this condition isn't present in the dashboard playbook anymore
we can remove the block section.
> dashboard: remove useless block section

- group_vars/mgrs.yml.sample
- group_vars/mons.yml.sample
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/tasks/common.yml
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/tasks/ceph_keys.yml
Add code in ceph-mgr for creating a keyring for manager in so that
managers can be deployed on a separate node too.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1552210
(cherry picked from commit 56bfec7c58407e269f6e6fa7b4c8a5928953dc6f)
> ceph-mgr: create keys for MGRs

- roles/ceph-dashboard/tasks/configure_dashboard.yml
The ceph dashboard tasks didn't use the cluster option if the cluster
name isn't the default value.
Closes: #4529
> ceph-dashboard: add cluster parameter to ceph cmd

- roles/ceph-handler/tasks/main.yml
This commit adds some missing `| bool` filters.
> handler: followup on #4519

- site-container.yml.sample
- site.yml.sample
Add missing tag on ceph-handler role call.
Otherwise, we can't use `--tags='ceph_update_config'` for updating the
ceph configuration file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1754432
> playbook: add missing tags

- tests/functional/rgw-multisite/container/hosts
- tests/functional/rgw-multisite/container/secondary/hosts
- tests/functional/rgw-multisite/container/secondary/vagrant_variables.yml
- tests/functional/rgw-multisite/hosts
- tests/functional/rgw-multisite/secondary/hosts
- tests/functional/rgw-multisite/secondary/vagrant_variables.yml
- tox.ini
The secondary vagrant variables didn't have the grafana vm variable
set which create an vagrant error.
```console
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.
```
This patch also changes the ssh-extra-args parameter to ssh-common-args
to get the same values for ssh/sftp/scp. Otherwise we can see warnings
from ansible and some tasks are failing.
```console
[WARNING]: sftp transfer mechanism failed on [mon0]. Use ANSIBLE_DEBUG=1
to see detailed information
```
It also updates the ssh-common-args value for the rgw-multisite scenario
to reflect the ANSIBLE_SSH_ARGS environment variable value.
Finally changing the IP addresses due to the Vagrant refact done in the
commit …
> tests: fix rgw multisite vagrant variables

- infrastructure-playbooks/add-mon.yml
- infrastructure-playbooks/docker-to-podman.yml
- infrastructure-playbooks/rolling_update.yml
- site-container.yml.sample
- site.yml.sample
This commit excludes client nodes from facts gathering, they are not
needed and can speed up this task.
> main: exclude client nodes from facts gathering

- roles/ceph-dashboard/tasks/configure_dashboard.yml
This patch moves the https dashboard configuration into a dedicated
block to avoid the multiple occurence of the dashboard_protocol
condition.
It also fixes the dashboard certificate and key variables handling in
the condition introduced by ab54fe2. Those variables aren't boolean but
strings so we can test them via the length filter.
> ceph-dashboard: Improve https configuration

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-defaults/defaults/main.yml
We don't need to have dedicated variables for the RGW integration into
the Ceph Dashboard and need to be manually filled.
Instead we can use the current values from the RGW nodes by using the
IP and port from the first RGW instance of the first RGW node via the
radosgw_address and radosgw_frontend_port variables.
We don't need to specify all RGW nodes, this will be done automatically
with one node.
The RGW api scheme is using the radosgw_frontend_ssl_certificate variable
to determine if the value is http or https. This variable is also reuse
as a condition for the ssl verify task.
> dashboard: remove rgw api host,port,scheme

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-facts/tasks/facts.yml
As per https://github.com/ceph/ceph-ansible/pull/4323#issuecomment-538420164
using `find` command should be faster.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1757400
Co-Authored-by: Giulio Fidente <gfidente@redhat.com>
> switch_to_containers: optimize ownership change

- roles/ceph-mgr/tasks/common.yml
556052b changed the way the mgr keyring are created but the ceph_key
module need the containerized parameter when the deployment is using
containers.
This module doesn't support CEPH_CONTAINER_[BINARY|IMAGE] environment
variables.
Closes: #4547
> ceph-mgr: fix ceph_key module with container

- infrastructure-playbooks/shrink-osd.yml
- roles/ceph-config/tasks/main.yml
9e7972a introduced a regression via the container_binary variable
which is undefined.
The CEPH_CONTAINER_BINARY environment variable isn't used at all.
> ceph-config: remove container_binary variable

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
When switching from a baremetal deployment to a containerized deployment
we only umount the OSD data partition.
If the OSD is encrypted (dmcrypt: true) then there's an additional
partition (part number 5) used for the lockbox and mount in the
/var/lib/ceph/osd-lockbox/ directory.
Because this partition isn't umount then the containerized OSD aren't
able to start. The partition is still mount by the system and can't be
remount from the container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1616159
> switch_to_containers: umount osd lockbox partition

- .mergify.yml
We don't have one global pipeline anymore reporting the jenkins job
status. So we need to match the  CI scenario name.
This also add the Travis CI status as a condition.
> mergify: Update condition on status success

- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/group_vars/all
- tests/functional/collocation/container/group_vars/all
- tests/functional/collocation/group_vars/all
- tests/functional/lvm-auto-discovery/container/group_vars/all
- tests/functional/lvm-auto-discovery/group_vars/all
- tests/functional/lvm-batch/container/group_vars/all
- tests/functional/lvm-batch/group_vars/all
- tests/functional/lvm-osds/container/group_vars/all
- tests/functional/lvm-osds/group_vars/all
- tests/functional/podman/group_vars/all
We don't need to have high handler delay in the CI so reducing to
10 seconds.
> tests: reduce handler mon and osd delay

- roles/ceph-dashboard/tasks/configure_dashboard.yml
If the mgr dashboard doesn't restart fast enough then the inject
dashboard task will fail with a HTTP error 400.
```console
Error EINVAL: Traceback (most recent call last):
File "/usr/share/ceph/mgr/mgr_module.py", line 914, in _handle_command
return self.handle_command(inbuf, cmd)
File "/usr/share/ceph/mgr/dashboard/module.py", line 450, in handle_command
push_local_dashboards()
File "/usr/share/ceph/mgr/dashboard/grafana.py", line 132, in push_local_dashboards
retry()
File "/usr/share/ceph/mgr/dashboard/grafana.py", line 89, in call
result = self.func(*self.args, **self.kwargs)
File "/usr/share/ceph/mgr/dashboard/grafana.py", line 127, in push
grafana.push_dashboard(body)
File "/usr/share/ceph/mgr/dashboard/grafana.py", line 54, in push_dashboard
response.raise_for_status()
File …
```
> dashboard: update layouts before the restart

- infrastructure-playbooks/dashboard.yml
If no host is available, let's just skip these plays.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1759917
> dashboard: do not fail in case of external ceph cluster

- roles/ceph-validate/tasks/check_devices.yml
This commit adds a validation task to prevent from installing an OSD on
the same disk as the OS.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1623580
> validate: prevent from installing OSD on same disk as the OS

- infrastructure-playbooks/dashboard.yml
This is already done in the main playbooks but absent in the dashboard
playbook.
The facts are already gathered during the first play of the main
playbooks so we don't need to doing twice.
> dashboard: disable facts gathering

- roles/ceph-handler/handlers/main.yml
- roles/ceph-handler/tasks/handler_mdss.yml
- roles/ceph-handler/tasks/handler_mgrs.yml
- roles/ceph-handler/tasks/handler_mons.yml
- roles/ceph-handler/tasks/handler_nfss.yml
- roles/ceph-handler/tasks/handler_osds.yml
- roles/ceph-handler/tasks/handler_rbd_target_api.yml
- roles/ceph-handler/tasks/handler_rbd_target_gw.yml
- roles/ceph-handler/tasks/handler_rbdmirrors.yml
- roles/ceph-handler/tasks/handler_rgws.yml
- roles/ceph-handler/tasks/handler_tcmu_runner.yml
We are using multiple listen topics with the handlers. That means that
we are notifying 4 tasks for each handler.
Instead we can group the listen on an include_tasks and based on the
group condition.
Before:
```console
NOTIFIED HANDLER ceph-handler : set _mon_handler_called before restart for mon0
NOTIFIED HANDLER ceph-handler : copy mon restart script for mon0
NOTIFIED HANDLER ceph-handler : restart ceph mon daemon(s) for mon0
NOTIFIED HANDLER ceph-handler : set _mon_handler_called after restart for mon0
NOTIFIED HANDLER ceph-handler : set _osd_handler_called before restart for mon0
NOTIFIED HANDLER ceph-handler : copy osd restart script for mon0
NOTIFIED HANDLER ceph-handler : restart ceph osds daemon(s) for mon0
NOTIFIED HANDLER ceph-handler : set _osd_handler_called after restart for …
```
> ceph-handler: group listen topics and condition

- .travis.yml
- roles/ceph-common/tasks/installs/configure_redhat_local_installation.yml
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-mon/tasks/ceph_keys.yml
- roles/ceph-osd/tasks/main.yml
- roles/ceph-prometheus/meta/main.yml
- roles/ceph-rgw-loadbalancer/meta/main.yml
```console
[303] mktemp used in place of tempfile module
[602] Don't compare to empty string
[701] No 'galaxy_info' found
[702] Use 'galaxy_tags' rather than 'categories'
```
This patch also changes the ansible log_path value via the
ANSIBLE_LOG_PATH environment variable in the travis configuration to
avoid warnings.
[WARNING]: log file at /home/travis/ansible/ansible.log is not writeable
and we cannot create it, aborting
> lint: fix error [303,602,701,702]

- roles/ceph-mgr/tasks/common.yml
There is no need to loop over all mgr nodes to set this fact, it's even
breaking deployments because it tries to copy all mgr keyring on all
mgr.
Closes: #4602
> mgr: do not copy all keyrings on all mgr

- site-container.yml.sample
- site.yml.sample
The is_atomic and container_binary facts are already defined in the
ceph-facts role so we don't need to have dedicated tasks for that
before the ceph-facts role exectution.
> playbook: remove duplicate facts

- infrastructure-playbooks/dashboard.yml
- site-container.yml.sample
- site.yml.sample
The common roles don't need to be executed again on each group plays
(like mons, osds, etc..).
We only need to execute them during the first play. That wat, we will
apply the changes on all nodes in parallel instead of doing it once per
group.
> Execute common roles once on all nodes

- roles/ceph-nfs/tasks/main.yml
this task is a leftover and no longer needed.
It even causes bug when collocating nfs with mon.
Closes: #4609
> nfs: remove unnecessary set_fact in main.yml

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
When using python3 the name of the rtslib rpm is python3-rtslib. The
packages that use rtslib already have code that detects the python
version and distro deps, so drop it from the ceph iscsi gw task list and
let the ceph-iscsi rpm dependency handle it.
Signed-off-by: Mike Christie <mchristi@redhat.com>
> iscsi-gw: Fix rtslib installation

- tests/functional/lvm_setup.yml
The commit replaces the pv/vg/lv commands used with the ansible command
module by the lvg and lvol modules.
This also fixes the size of the second data LV because we were only using
50% of the remaining space instead of 100%.
With a 50G device, the result was:
- data-lv1 25G
- data-lv2 12.5G
Instead of:
- data-lv1 25G
- data-lv2 25G
> tests: fix the size on the second data LV

- roles/ceph-common/tasks/main.yml
Otherwise it fails like following:
```
TASK [ceph-mds : allow multimds] **************************************************************************************************************************************************
Monday 22 July 2019  16:37:38 +0800 (0:00:03.269)       0:13:25.651 ***********
fatal: [rhel7u6clone1]: FAILED! => {"msg": "The conditional check 'ceph_release_num[ceph_release] == ceph_release_num.luminous' failed. The error was: error while evaluating conditional (ceph_release_num[ceph_release] == ceph_release_num.luminous): 'dict object' has no attribute u'dummy'\n\nThe error appears to have been in '/usr/share/ceph-ansible/roles/ceph-mds/tasks/create_mds_filesystems.yml': line 43, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe …
```
> common: do not override ceph_release when using custom repo

- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/group_vars/all
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/hosts-switch-to-containers
- tests/functional/all_daemons/hosts-ubuntu
- tests/functional/all_daemons/vagrant_variables.yml
- tox-update.ini
This commit makes the all_daemons scenario deploying 3 mds in order to
cover the multimds case.
> tests: add multimds coverage

- infrastructure-playbooks/rolling_update.yml
- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/hosts-ubuntu
- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/group_vars/all
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/hosts-switch-to-containers
- tests/functional/all_daemons/hosts-ubuntu
- tests/functional/all_daemons/vagrant_variables.yml
upgrade: fix standby_mdss group creation
This commit fixes the standby_mdss group creation by using `{{ item }}`.
> upgrade: fix standby_mdss group creation

- .travis.yml
- roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
If ansible-lint reports an error then it's skipped. We should fail in
this case.
This patch also fixes the pipefail lint in the rbd mirror role
[306] Shells that use pipes should set the pipefail option
> travis: fail on ansible-lint errors

- roles/ceph-validate/tasks/main.yml
This task is failing when `ceph_docker_registry_auth` is enabled and
`ceph_docker_registry_username` is undefined with an ansible error
instead of the expected message.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1763139
> validate: fix credentials validation

- tests/conftest.py
- tests/functional/ooo-collocation/hosts
- tox.ini
It doesn't make sense to test the old 3.0.x container images with
nautilus+ ceph releases.
Also disable the dashboard deployment.
> tests: update container tag for ooo_collocation

- dashboard.yml
- roles/ceph-container-common/tasks/main.yml
- roles/ceph-container-common/tasks/registry.yml
When deploying with packages then the ceph-container-common role isn't
executed so the registry authentication task is ignored.
Closes: #4636
> container/dashboard: run the registry auth task

- infrastructure-playbooks/rolling_update.yml
Let's skip this part of the code if there's no mds node in the
inventory.
> update: skip mds deactivation when no mds in inventory

- roles/ceph-osd/tasks/openstack_config.yml
container_exec_cmd should be replace by docker_exec_cmd.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1765110
> openstack_config: fix docker exec command

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Add ceph_docker_registry_username and ceph_docker_registry_password
variables in ceph-defaults role so they will be present in the group_vars
samples but commented.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1763139
> defaults: add user/pass auth registry variables

- infrastructure-playbooks/rolling_update.yml
This must be consistent with what is used in `name` parameter.
> update: use right node when creating active mds group

- infrastructure-playbooks/add-mon.yml
- infrastructure-playbooks/add-osd.yml
The ceph-container-engine role is missing from both playbooks so the
container engine (docker, podman) isn't install resulting in a failure
on the added nodes.
```console
fatal: [xxxxx]: FAILED! => changed=false
cmd: docker --version
msg: '[Errno 2] No such file or directory'
rc: 2
```
Closes: #4634
> add-{mon,osd}: add ceph-container-engine role

- infrastructure-playbooks/rolling_update.yml
mon_host should use the inventory hostname and not the node hostname.
Fix creates an issue when the inventory and node hostname are different.
Closes: #4670
> rolling_update: fix reset mon_host variable

- infrastructure-playbooks/add-mon.yml
Without the become flag set to true, we can't executed the roles
successfully.
> add-mon: add missing become flag

- .travis.yml
- plugins/filter/ipaddrs_in_ranges.py
- tests/library/test_ceph_crush.py
- tests/library/test_ceph_key.py
- tests/library/test_ceph_volume.py
- tests/plugins/filter/test_ipaddrs_in_ranges.py
To avoid unnecessary ansible warnings during playbook execution we can
move the library and plugins test files under a different directory.
```console
[WARNING]: Skipping plugin (plugins/filter/test_ipaddrs_in_ranges.py) as
it seems to be invalid:
cannot import name 'ipaddrs_in_ranges'
```
Closes: #4656
> move library/plugins tests files under tests dir

- infrastructure-playbooks/rolling_update.yml
The active mds host should be based on the inventory hostname and not on
the ansible hostname.
The value returns under the mdsmap structure is based on the OS hostname
so we need to find the right node in the inventory with this value when
doing operation on inventory nodes.
Othewise we could see error like:
```console
The task includes an option with an undefined variable. The error was:
"hostvars[foobar]" is undefined
```
> rolling_update: fix active mds host value

- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Since nfs-ganesha V3.0-rc4 and [1] we need to explicitly install the
nfs-ganesha-rados-grace package.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/0fea990
> ceph-nfs: add nfs-ganesha-rados-grace explicitly

- infrastructure-playbooks/rolling_update.yml
This commit adds a default value in the `with_dict` because when using
python 2.7, if a task using a `with_dict` has a condition, it is
evaluated anyway whereas in python 3 it isn't.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1766499
> update: add default values when setting fact

- roles/ceph-mon/tasks/crush_rules.yml
A default crush rule is inserted into the daemon via the ceph daemon config
command. This command tries to resolve the admin socket path and fails if you
have a duplicate key in the ceph configuration.
This PR uses the `--admin-daemon` option to prevent the task from failling.
This is related to #4492 (which has been fixed with #4507)
Signed-off-by: Mihai Plasoianu <m.plasoianu@vertical.de>
> ceph-mon: use --admin-daemon to set default crush rule

- Makefile
Curently, the dist and mock configurations are hardcoded in the
Makefile to be el8 and epel-7-x86_64, respectively. This commit
allows the user to override those settings using the DIST and
MOCK_CONFIG environment variables, falling back to the current
defaults if not set.
This provides additional flexibility when building the RPM directly
from the repository.
> Allow setting dist and mock configuration in Makefile

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Even if this improves ceph-disk/ceph-volume performances then it also
impact the ceph-osd process.
The ceph-osd process shouldn't use 1024:4096 value for the max open
files.
Removing the ulimit option from the container engine and doing this kind
of change on the container side [1].
[1] https://github.com/ceph/ceph-container/pull/1497
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1702285
> ceph-osd: Remove ulimit nofile on container start

- group_vars/all.yml.sample
- roles/ceph-defaults/defaults/main.yml
The latest grafana container tag is using grafana 6.x release which could
cause issue with the ceph dashboard integration.
Considering that the grafana container in RHCS 3 is based on 5.x then we
should use the same version.
$ docker run --rm rhceph/rhceph-3-dashboard-rhel7:3 -v
Version 5.2.4 (commit: unknown-dev)
> ceph-defaults: pin grafana container tag to 5.2.4

- tests/requirements.txt
The ansible ssh connections are now using the ssh backend instead of
paramiko starting testinfra 3.1 and persistent connections too.
pytest 4.6 is the latest release to be supported by python 2.
> tests/requirements: bump testinfra and pytest

- roles/ceph-osd/tasks/system_tuning.yml
[1] introduced a regression on the fs.aio-max-nr sysctl value condition.
The enable key isn't a boolean but a string because the expression isn't
evaluated.
This string output "(osd_objectstore == 'bluestore')" is always true
because item.enable condition only matches non empty string. So the
sysctl value was applyied for both filestore and bluestore backend.
[2] added the bool filter to the condition but the filter always returns
false on string and the sysctl wasn't applyed at all.
This commit fixes the enable key value by evaluating the value instead
of using the string.
[1] https://github.com/ceph/ceph-ansible/commit/08a2b58
[2] https://github.com/ceph/ceph-ansible/commit/ab54fe2
> ceph-osd: fix fs.aio-max-nr sysctl condition

- infrastructure-playbooks/add-mon.yml
- infrastructure-playbooks/add-osd.yml
If the new mon/osd node doesn't have python installed then we need to
execute the tasks from raw_install_python.yml.
Closes: #4368
> add-{mon,osd}: run raw install python tasks

- roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
If for some reason, there's an old rgw socket file present in the
/var/run/ceph/ directory then the test command could fail with
```console
test: xxxxxxxxx.asok: binary operator expected
```
```console    
$ ls -hl /var/run/ceph/
total 0
srwxr-xr-x. ceph-client.rgw.rgw0.rgw0.68.94153614631472.asok
srwxr-xr-x. ceph-client.rgw.rgw0.rgw0.68.94240997655088.asok
```
We can check the radosgw socket in /proc/net/unix to avoid using wildcard
in the socket name.
> ceph-handler: Use /proc/net/unix for rgw socket

- roles/ceph-validate/tasks/check_rbdmirror.yml
- roles/ceph-validate/tasks/main.yml
When ceph_rbd_mirror_configure is set to true we need to ensure that
the required variables aren't empty.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1760553
> ceph-validate: add rbdmirror validation

- infrastructure-playbooks/purge-docker-cluster.yml
- tests/functional/rbd_map_devices.yml
- tox.ini
in containerized context, using the binary provided in atomic os won't
work because it's an old version provided by ceph-common based on
10.2.5.
Using a container could be an idea but for large cluster with hundreds
of client nodes, that would require to pull the image of each of them
just to unmap the rbd devices.
Let's use the sysfs method in order to avoid any issue related to ceph
version that is shipped on the host.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1766064
> purge: use sysfs to unmap rbd devices

- Makefile
- Set default mock configuration to epel-8-x86_64, to match the
default dist value.
- Add support for alpha tags, like the recently added v5.0.0alpha1
> Fixes for Makefile

- infrastructure-playbooks/rolling_update.yml
It might be possible at some point even with osd flags `noout` and
`norebalance` set the PGs states can change depending on the amount of data
written meantime. It means the check for PGs state will fail.
This commit changes the way we set those flags:
we set them before an OSD node upgrade and unset them before the PGs
state check so they can recover.
Fixes: #3961
> update: reset flags before and after each osd node upgrade

- library/ceph_key.py
when `import_key` is enabled, if the key already exists, it will only be
fetched using ceph cli, if the mode specified in the `ceph_key` task is
different from what is applied by the ceph cli, the mode isn't restored because
we don't call `module.set_fs_attributes_if_different()` before
`module.exit_json(**result)`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1734513
> ceph_key: restore file mode after a key is fetched

- roles/ceph-validate/tasks/main.yml
ceph_repository_type was being validated in containerized scenario which results in unnecessary failure of site-docker.yml. This commit makes respective task to be avoided in containerized scenario.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1769760
> fixes failure of site-docker.yml due to unnecessary validation of ceph_repository_type

- group_vars/all.yml.sample
- roles/ceph-defaults/defaults/main.yml
In addition to the grafana container tag change, we need to do the same
for the prometheus container stack based on the release present in the
OSE 4.1 container image.
```console
$ docker run --rm openshift4/ose-prometheus-node-exporter:v4.1 --version
node_exporter, version 0.17.0
build user:       root@67fee13ed48f
build date:       20191023-14:38:12
go version:       go1.11.13
$ docker run --rm openshift4/ose-prometheus-alertmanager:4.1 --version
alertmanager, version 0.16.2
build user:       root@70b79a3f29b6
build date:       20191023-14:57:30
go version:       go1.11.13
$ docker run --rm openshift4/ose-prometheus:4.1 --version
prometheus, version 2.7.2
build user:       root@12da054778a3
build date:       20191023-14:39:36
go version:       go1.11.13
```
Signed-off-by: Dimitri …
> ceph-defaults: pin prometheus container tags

- group_vars/mons.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-mon/tasks/main.yml
- roles/ceph-osd/tasks/crush_rules.yml
- roles/ceph-osd/tasks/main.yml
- tests/functional/all_daemons/container/group_vars/mons
- tests/functional/all_daemons/group_vars/mons
- tests/functional/podman/group_vars/mons
This adds device class support to crush rules when using the class key
in the rule dict via the create-replicated sub command.
If the class key isn't specified then we use the create-simple sub
command for backward compatibility.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1636508
> ceph-osd: add device class to crush rules

- site-container.yml.sample
If we execute the site-container.yml playbook with specific tags (like
ceph_update_config) then we need to be sure to gather the facts otherwise
we will see error like:
The task includes an option with an undefined variable. The error was:
'ansible_hostname' is undefined
This commit also adds missing 'gather_facts: false' to mons plays.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1754432
> container: add always tag on gather fact tasks

- roles/ceph-mds/tasks/common.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
Configuration of cephfs with an existing cluster using --limit used to fail
at different tasks while running with site-docker.yml
This commit addresses both of those tasks
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1773489
> Fixes failure of cephfs configuration using --limit while running purge-docker.yml 

- roles/ceph-container-engine/tasks/main.yml
- roles/ceph-container-engine/vars/CentOS-8.yml
- tox-podman.ini
Switch the podman scenario from atomic centos 7 to centos 8 (not atomic)
> tox-podman: use centos 8 vagrant image

- infrastructure-playbooks/rolling_update.yml
1. set noout and nodeep-scrub flags,
2. upgrade each OSD node, one by one, wait for active+clean pgs
3. after all osd nodes are upgraded, unset flags
Co-authored-by: Rachana Patel <racpatel@redhat.com>
> upgrade: use flags noout and nodeep-scrub only

- infrastructure-playbooks/rolling_update.yml
On non containerized deployment the ceph-mon hostname/fqdn systemd
service are stopped at the beginning of the mon upgrade.
But the parameter enabled is set to true for both task so even if we're
not using the fqdn then it will enabled the systemd unit based on it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1649617
> rolling_update: don't enable ceph-mon unit

- .travis.yml
Add both python 3.7 and 3.8 in the travis matrix testing.
> travis: add python 3.7 and 3.8

- Vagrantfile
This commit reverts the following change:
https://github.com/ceph/ceph-ansible/pull/4510/commits/fcf181342a70b78a355d1c985699028012326b5f#diff-23b6f443c01ea2efcb4f36eedfea9089R7-R14
this is causing CI failures so this commit is intended to unlock the CI.
> tests: revert vagrant_variable file name detection

- roles/ceph-grafana/tasks/configure_grafana.yml
The wait_for ansible module doesn't support the backets on IPv6 address
so need to remove them.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1769710
> ceph-grafana: remove ipv6 brakets on wait_for

- roles/ceph-osd/tasks/main.yml
- roles/ceph-osd/tasks/openstack_config.yml
When creating crush rules with device class parameter we need to be sure
that all OSDs are up and running because the device class list is
is populated with this information.
This is now enable for all scenario not openstack_config only.
> ceph-osd: wait for all osd before crush rules

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
- infrastructure-playbooks/purge-iscsi-gateways.yml
- infrastructure-playbooks/rolling_update.yml
This was introduced in 3.1 and marked as deprecation
We can definitely drop it in stable-4.0
> purge/update: remove backward compatibility legacy

- roles/ceph-dashboard/tasks/main.yml
This commit makes the ceph-dashboard role only printing ceph-dashboard
URL of the nodes present in grafana-server group
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1762163
> dashboard: only print dashboard url of the grafana-server node

- roles/ceph-facts/tasks/facts.yml
When using `osd_auto_discovery`, `devices` is built multiple times due
to multiple runs of `ceph-facts` role. It end up with duplicate
instances of a same device in the list.
Using `unique` filter when building the list fixes this issue.
> facts: avoid duplicated element in devices list

- roles/ceph-osd/tasks/main.yml
cf8c6a3 moves the 'wait for all osds' task from openstack_config to the
main tasks list.
But the openstack_config code was executed only on the last OSD node.
We don't need to do this check on all OSD node so we need to add set
run_once to true on that task.
> ceph-osd: wait for all osds once

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
When a container is already running on a non containerized node then the
umount ceph partition task is skipped.
This is due to the container ps command which always returns 0 even if
the filter matches nothing.
We should run the umount task when:
1/ the container command is failing (not installed) : rc != 0
2/ the container command reports running ceph-osd containers : rc == 0
Also we should not fail on the ceph directory listing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1616159
> switch_to_containers: fix umount ceph partitions

- infrastructure-playbooks/docker-to-podman.yml
- roles/ceph-handler/handlers/main.yml
We must import this role in the first play otherwise the first call to
`client_group_name`fails.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1777829
> docker2podman: various fixes

- group_vars/rgwloadbalancers.yml.sample
- roles/ceph-rgw-loadbalancer/defaults/main.yml
- roles/ceph-rgw-loadbalancer/templates/haproxy.cfg.j2
Currently RGW HAproxy configuration does not support SSL termination or passthrough. If SSL cert is setup along with HAproxy,  individual RGW instances will be set as SSL endpoints.
This PR will address this issue by setting HAproxy as a SSL endpoint instead of each individual RGW instance.
Signed-off-by: Stanley Lam <stanleylam_604@hotmail.com>
> ceph-rgw-loadbalancer: add option for haproxy ssl frontend

- infrastructure-playbooks/purge-docker-cluster.yml
- roles/ceph-facts/tasks/container_binary.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-node-exporter/templates/node_exporter.service.j2
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
All containers are removed when systemd stops them.
There is no need to call this module in purge container playbook.
This commit also removes all docker_image task and remove all container
images in the final cleanup play.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1776736
> purge: add podman support

- roles/ceph-prometheus/templates/alertmanager.yml.j2
When using the shortname, the URL for active alert launches with short
hostname and fails to connect to the server.
This commit changes the template in order to use the fqdn.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1765485
> dashboard: use fqdn url for active alert

- infrastructure-playbooks/purge-docker-cluster.yml
ceph/ceph-ansible#4805 introduced a symlink to
purge-container-cluster.yml playbook which is broken.
> purge: fix symlink to purge-container-cluster

- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/group_vars/all
Having max_mds value equals to the number of mds nodes generates a
warning in the ceph cluster status:
```console
cluster:
id:     6d3e49a4-ab4d-4e03-a7d6-58913b8ec00a'
health: HEALTH_WARN'
insufficient standby MDS daemons available'
(...)
services:
mds:     cephfs:3 {0=mds1=up:active,1=mds0=up:active,2=mds2=up:active}'
```
Let's use 2 active and 1 standby mds.
> tests: reduce max_mds from 3 to 2

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-container-cluster.yml
The podman support was added to the purge-container-cluster playbook but
containers are always used for the dashboard even on non containerized
deployment.
This commits adds the podman support on purging the dashboard resources
in the purge-cluster playbook.
> purge-cluster: add podman support

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
The md devices (RAID software) aren't excluded from the devices list in
the auto discovery scenario.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1764601
> ceph-defaults: exclude md devices from discovery

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/rolling_update.yml
- roles/ceph-defaults/defaults/main.yml
when upgrading from RHCS 3, dashboard has obviously never been deployed
and it forces us to deploy it later manually.
This commit adds the dashboard deployment as part of the upgrade to
RHCS 4.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1779092
> upgrade: add dashboard deployment

- roles/ceph-facts/tasks/facts.yml
- roles/ceph-infra/tasks/setup_ntp.yml
The ntp/chrony facts are only used in the ceph-infra role so we don't
really need to set them in the ceph-facts roles.
> ceph-facts: move ntp/chrony facts to ceph-infra

- roles/ceph-validate/tasks/check_iscsi.yml
- roles/ceph-validate/tasks/check_system.yml
- roles/ceph-validate/tasks/main.yml
It doesn't make sense to start validating configuration if the ansible
version isn't the good one.
This commit moves the check_system task as the first task in the
ceph-validate role.
The ansible version test tasks are moved at the top of this file.
Also moving the iscsi kernel tests from check_system to check_iscsi
file.
> ceph-validate: start with ansible version test

- roles/ceph-node-exporter/templates/node_exporter.service.j2
Typical error:
```
type=AVC msg=audit(1575367499.582:3210): avc:  denied  { search } for  pid=26680 comm="node_exporter" name="1" dev="proc" ino=11528 scontext=system_u:system_r:container_t:s0:c100,c1014 tcontext=system_u:system_r:init_t:s0 tclass=dir permissive=0
```
node_exporter needs to be run as privileged to avoid avc denied error
since it gathers lot of information on the host.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1762168
> dashboard: run node_export as privileged container

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
just like site.yml and rolling_update, let's exclude clients node from
the fact gathering.
> switch_to_containers: exclude clients nodes from facts gathering

- infrastructure-playbooks/shrink-osd.yml
When using fqdn in inventory, that playbook fails because of some tasks
using the result of ceph osd tree (which returns shortname) to get
some datas in hostvars[].
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1779021
> shrink-osd: support fqdn in inventory

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
This commit isolates and adds an explicit comment about variables not
intended to be modified by the user.
Fixes: #4828
> defaults: add a comment

- ansible.cfg
There's no need to enforce PreferredAuthentications by default.
Users can still choose to override the ansible.cfg with any additional
parameter like this one to fit their infrastructure.
Fixes: #4826
> ansible.cfg: do not enforce PreferredAuthentications

- roles/ceph-facts/tasks/facts.yml
- roles/ceph-validate/tasks/check_iscsi.yml
We don't need to set the use_new_ceph_iscsi fact on other nodes than
those present in the iscsigws group.
Also remove the duplicate iscsi_gw_group_name condition already present
on the include_task.
Finally validate the ansible distribution as the first task.
> ceph-facts: set use_new_ceph_iscsi on iscsi nodes

- roles/ceph-osd/templates/ceph-osd.service.j2
The systemd unit script wasn't updated with the new container name
format (without the hostname).
We now have the same start/stop docker commands for all scenarios.
During the device to id OSD migration we need to be sure that the
old container with the hostname are stopped.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1780688
> ceph-osd: update systemd unit script

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/set_monitor_address.yml
- roles/ceph-facts/tasks/set_radosgw_address.yml
- roles/ceph-validate/tasks/main.yml
To avoid confusion, let's change the default value from `0.0.0.0` to
`x.x.x.x`.
Users might think setting `0.0.0.0` will make the daemon binding on all
interfaces.
Fixes: #4827
> defaults: change monitor|radosgw_address default value

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
The RBD devices aren't excluded from the devices list in the LVM auto
discovery scenario.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1783908
> ceph-defaults: exclude rbd devices from discovery

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
In fc02fc9 the group_vars samples have been generated but only for
monitor_address variable not radosgw_address.
> ceph-defaults: regenerate group_vars samples

- roles/ceph-infra/tasks/configure_firewall.yml
- roles/ceph-infra/tasks/dashboard_firewall.yml
When there's no mgr group defined in the ansible inventory then the
mgrs are deployed implicitly on the mons nodes.
If the dashboard is enabled then we need to open the dashboard port on
the node that is running the ceph mgr process (mgr or mon).
The current code only allow to open that port on the mgr nodes when they
are present explicitly in the inventory but not implicitly.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1783520
> ceph-infra: open dashboard port on monitor

- infrastructure-playbooks/filestore-to-bluestore.yml
When an OSD is stopped, it leaves partitions mounted.
We must umount them before zapping them, otherwise error like "Device is
busy" will show up.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1729267
> filestore-to-bluestore: umount partitions before zapping them

- roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
- roles/ceph-rgw-loadbalancer/templates/keepalived.conf.j2
Currently the keepalived template only works when system hostnames exactly match the Ansible inventory name. If these are different, all generated templates become `BACKUP` without a `MASTER` assigned. Using the `inventory_hostname` in the template file resolves this issue.
Signed-off-by: Stanley Lam stanleylam_604@hotmail.com
> ceph-rgw-loadbalancer: Modify keepalived master selection

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/purge-container-cluster.yml
- infrastructure-playbooks/rolling_update.yml
- roles/ceph-common/tasks/installs/redhat_community_repository.yml
- roles/ceph-common/tasks/installs/redhat_dev_repository.yml
- roles/ceph-container-engine/tasks/main.yml
- roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
- roles/ceph-container-engine/vars/CentOS-8.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
- roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
- roles/ceph-osd/tasks/main.yml
- tests/conftest.py
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/vagrant_variables.yml
- tests/functional/rbd_map_devices.yml
- tests/functional/rgw_multisite.yml
- tests/functional/setup.yml
- tox-filestore_to_bluestore.ini
- tox-podman.ini
- tox-update.ini
- tox.ini
Ceph octopus only supports CentOS 8.
This commit adds CentOS 8 support:
- update vagrant image in tox configurations.
- add CentOS 8 repository for el8 dependencies.
- CentOS 8 container engine is podman (same than RHEL 8).
- don't use the epel mirror on sepia because it's epel7 only.
Co-authored-by: Dimitri Savineau <dsavinea@redhat.com>
> common: add centos8 support

- library/ceph_volume.py
This commit adds the filestore to bluestore migration support in
ceph_volume module.
We must append to the executed command only the relevant options
according to what is passed in `osd_objectostore`
> ceph_volume: support filestore to bluestore migration

- infrastructure-playbooks/purge-iscsi-gateways.yml
When using the ceph dashboard with iscsi gateways nodes we also need to
remove the nodes from the ceph dashboard list.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786686
> purge-iscsi-gateways: remove node from dashboard

- roles/ceph-nfs/templates/ceph-nfs.service.j2
This reverts commit d06158e9d9ab4a706ca72a4940e7acb5fc25697d.
Otherwise ganesha consumers can't dynamically update exports using dbus.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784562
> Revert "nfs: do not run privileged nfs container"

- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
Force fqdn to be used in external url for prometheus and alertmanager.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1765485
> dashboard: use fqdn in external url

- infrastructure-playbooks/shrink-mds.yml
We only need to set `container_binary`.
Let's use `tasks_from` option.
> shrink-mds: do not play ceph-facts entirely

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
- tests/functional/all_daemons/hosts
This commit adds the support of the ceph-iscsi stable repository when
use ceph_repository community instead of always using the devel
repositories.
We're still using the devel repositories for rtslib and tcmu-runner in
both cases (dev and community).
> ceph-iscsi: add ceph-iscsi stable repositories

- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-iscsi-gw/tasks/common.yml
Only the ipv4 addresses from the nodes running the dashboard mgr module
were added to the trusted_ip_list configuration file on the iscsigws
nodes.
This also add the iscsi gateways with ipv6 configuration to the ceph
dashboard.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1787531
> ceph-iscsi: manage ipv6 in trusted_ip_list

- roles/ceph-rgw/tasks/main.yml
RadosGW pools can be created by setting
```yaml
rgw_create_pools:
.rgw.root:
pg_num: 512
size: 2
```
for instance. However, doing so would create pools of size
`osd_pool_default_size` regardless of the `size` value. This was due to
the fact that the Ansible task used
```
{{ item.size | default(osd_pool_default_size) }}
```
as the pool size value, but `item.size` is always undefined; the
correct variable is `item.value.size`.
> ceph-rgw: Fix custom pool size setting

- roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
Since RHEL 8.1 we need to add the ganesha_t type to the permissive
SELinux list.
Otherwise the nfs-ganesha service won't start.
This was done on RHEL 7 previously and part of the nfs-ganesha-selinux
package on RHEL 8.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786110
(cherry picked from commit d75812529069244734732d05cc5aa3ddbc99b7c5)
> ceph-nfs: add ganesha_t type to selinux

- roles/ceph-handler/tasks/handler_mdss.yml
- roles/ceph-handler/tasks/handler_mgrs.yml
- roles/ceph-handler/tasks/handler_mons.yml
- roles/ceph-handler/tasks/handler_nfss.yml
- roles/ceph-handler/tasks/handler_osds.yml
- roles/ceph-handler/tasks/handler_rbdmirrors.yml
- roles/ceph-handler/tasks/handler_rgws.yml
411bd07d54fc3f585296b68f2fd04484328399b5 introduced a bug in handlers
using `handler_*_status` instead of `hostvars[item]['handler_*_status']`
causes handlers to be triggered in anycase even though
`handler_*_status` was set to `False` on a specific node.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1622688
> handler: fix bug

- roles/ceph-facts/tasks/facts.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
We must pick up a mon which actually exists in ceph-facts in order to
detect if a cluster is running. Otherwise, it will state no cluster is
already running which will end up deploying a new monitor isolated in a
new quorum.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1622688
> mon: support replacing a mon

- infrastructure-playbooks/shrink-rgw.yml
Instead of running the ceph roles against localhost we should do it
on the first mon.
The ansible and inventory hostname of the rgw nodes could be different.
Ensure that the rgw instance to remove is present in the cluster.
Fix rgw service and directory path.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1677431
> shrink-rgw: refact global workflow

- infrastructure-playbooks/rolling_update.yml
There's some tasks using the new container image during the rolling
upgrade playbook that needs to execute the registry login first otherwise
the nodes won't be able to pull the container image.
```console
Unable to find image 'xxx.io/foo/bar:latest' locally
Trying to pull repository xxx.io/foo/bar ...
/usr/bin/docker-current: Get https://xxx.io/v2/foo/bar/manifests/latest:
unauthorized
```
> rolling_update: run registry auth before upgrading

- roles/ceph-config/tasks/main.yml
We must exclude the devices already used and prepared by ceph-disk when
doing the lvm batch report. Otherwise it fails because ceph-volume
complains about GPT header.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786682
> config: exclude ceph-disk prepared osds in lvm batch report

- infrastructure-playbooks/purge-iscsi-gateways.yml
We only need to have the container_binary fact. Because we're not
gathering the facts from all nodes then the purge fails trying to get
one of the grafana fact.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786686
> purge-iscsi-gateways: don't run all ceph-facts

- roles/ceph-validate/tasks/check_system.yml
The Ceph Octopus release is only supported on CentOS 8
Closes: #4918
> ceph-validate: fail on CentOS 7

- tests/functional/setup.yml
The nobarrier mount flag doesn't exist anymoer on XFS in the EL 8
kernel. That's why the task wasn't working on those systems.
We can still use the other options instead of skipping the task.
> tests/setup: update mount options on EL 8

- infrastructure-playbooks/add-osd.yml
- roles/ceph-handler/tasks/handler_osds.yml
- roles/ceph-osd/tasks/main.yml
- tox.ini
This commit removes the add-osd.yml infrastructure playbook, same
operation can be achieved by running main playbook with --limit option.
> osd: remove add-osd.yml infra playbook

- roles/ceph-mds/tasks/create_mds_filesystems.yml
We need to explicitly enable the allow_dirfrags flag on cephfs pool
after upgrading to Luminous.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1776233
> [stable-3.2] ceph-mds: allow directory fragmentation

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The ceph lockbox partition (part number 5) used with non lvm scenarios
and in non containerized deployment don't have a valid PARTUUID.
The value is set to 00000000-0000-0000-0000-000000000000 for each OSD
devices.
```console
$ blkid -t PARTLABEL="ceph lockbox" -o value -s PARTUUID
00000000-0000-0000-0000-000000000000
00000000-0000-0000-0000-000000000000
00000000-0000-0000-0000-000000000000
00000000-0000-0000-0000-000000000000
00000000-0000-0000-0000-000000000000
```
When switching to containerized deployment we manually mount the lockbox
partition by using the PARTUUID.
Unfortunately because we have most of the time multiple OSD on the same
node we can't have the right symlink in /dev/disk/by-partuuid because it
will point to only one partition.
```console …
```
> [stable-3.2] switch_to_containers: set GUID on lockbox part

- roles/ceph-osd/tasks/start_osds.yml
This commit refact the condition in the loop of that task so all
potential osd ids found are well started.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790212
> osd: ensure osd ids collected are well restarted

- dashboard.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-facts/tasks/grafana.yml
We don't need to execute the grafana fact everytime but only during
the dashboard deployment.
Especially for ceph-grafana, ceph-prometheus and ceph-dashboard roles.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790303
> ceph-facts: move grafana fact to dedicated file

- roles/ceph-facts/tasks/facts.yml
d6da508a9b6829d2d0633c7200efdffce14f403f broke the osp/ceph external use case.
We must skip these tasks when no monitor is present in the inventory.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790508
> facts: fix osp/ceph external use case

- roles/ceph-osd/tasks/scenarios/lvm-batch.yml
since fd1718f3796312e29cd5fd64fcc46826741303d2, we must use `_devices`
when deploying with lvm batch scenario.
> osd: use _devices fact in lvm batch scenario

- roles/ceph-iscsi-gw/tasks/common.yml
The trusted_ip_list parameter for the rbd-target-api service doesn't
support ipv6 address with bracket.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1787531
> ceph-iscsi: don't use bracket with trusted_ip_list

- roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
- roles/ceph-osd/tasks/main.yml
Before this patch, the lvm2 package installation was done during the
ceph-osd role.
However we were running ceph-volume command in the ceph-config role
before ceph-osd. If lvm2 wasn't installed then the ceph-volume command
fails:
```console
error checking path "/run/lock/lvm": stat /run/lock/lvm: no such file or
directory
```
This wasn't visible before because lvm2 was automatically installed as
docker dependency but it's not the same for podman on CentOS 8.
(cherry picked from commit de8f2a9f83194e465d10207c7ae0569700345b9c)
> container: move lvm2 package installation

- infrastructure-playbooks/shrink-mds.yml
the new ceph status registered in `ceph_status` will report `fsmap.up` =
0 when it's the last mds given that it's done after we shrink the mds,
it means the condition is wrong.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1787543
> shrink-mds: fix condition on fs deletion

- .travis.yml
Since python2 is EOL we can drop it from travis CI matrix.
> travis: drop python2 support

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/templates/ceph.conf.j2
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
- roles/ceph-validate/tasks/main.yml
This has been deprecated in the previous releases. Let's drop it.
> drop use_fqdn variables

- tests/scripts/vagrant_up.sh
- tox-filestore_to_bluestore.ini
- tox-update.ini
- tox.ini
The CentOS cloud infrastructure storing the vagrant CentOS 8 image
changed the directory path and remove the old 8.0 image so the vagrant
box add centos/8 fails returning a 404 http error.
As a workaround we can pull the image from CentOS instead of letting
vagrant doing the resolution.
> vagrant: temp workaround for CentOS 8 cloud image

- roles/ceph-mgr/tasks/common.yml
- roles/ceph-mgr/tasks/main.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
Iterating over all monitors in order to delegate a `
{{ container_binary }}` fails when collocating mgrs with mons, because
ceph-facts reset `container_exec_cmd` to point to the first member of
the monitor group.
The idea is to force `container_exec_cmd` to be reset in ceph-mgr.
This commit also removes the `container_exec_cmd_mgr` fact.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1791282
> remove container_exec_cmd_mgr fact

- infrastructure-playbooks/docker-to-podman.yml
- roles/ceph-container-common/tasks/main.yml
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
When using docker 1.13.1, the current condition:
```
{% if (container_binary == 'docker' and ceph_docker_version.split('.')[0] is version_compare('13', '>=')) or container_binary == 'podman' -%}
```
is wrong because it compares the first digit (1) whereas it should
compare the second one.
It means we always use `--cpu-quota` although documentation recommend
using `--cpus` when docker version is 1.13.1 or higher.
From the doc:
> --cpu-quota=<value>	Impose a CPU CFS quota on the container. The number of
> microseconds per --cpu-period that the container is limited to before
> throttled. As such acting as the effective ceiling.
> If you use Docker 1.13 or higher, use --cpus instead.
> containers: use --cpus instead --cpu-quota

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
There's no need to define a variable via a fact if we can do it via a
default value. Using a fact could be interesseting to override the
default value on some condition.
- ceph_uid could be set to 167 by default because it's only different on
non containerized deployment on Debian/Ubuntu.
- rbd_client_directory_{owner,group,mode} could be set to ceph,ceph,0770
by default install of null as we are doing in the facts.
> ceph-facts: move facts to defaults value

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
RBD is invalid application for cephfs pools, so it was change to cephfs.
Signed-off-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>
> Fix application for openstack_cephfs pools

- roles/ceph-mgr/tasks/common.yml
Since commit [1] running_mon introduced, it can be not defined
which results in fatal error [2]. This patch defines default value which
was used before patch [1]
[1] https://github.com/ceph/ceph-ansible/commit/8dcbcecd713b0cd7769d3b4d04ef5c2f15881377
[2] https://zuul.opendev.org/t/openstack/build/c82a73aeabd64fd583694ed04b947731/log/job-output.txt#14011
Signed-off-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>
> Fix undefined running_mon

- roles/ceph-handler/tasks/handler_osds.yml
- roles/ceph-nfs/tasks/pre_requisite_container.yml
- roles/ceph-osd/tasks/main.yml
When unsetting the noup flag, we must call container_exec_cmd from the
delegated node (first mon member)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792320
> fix `container_exec_cmd` calls for --limit runs

- roles/ceph-rgw/tasks/main.yml
In 3c31b19ab39f297635c84edb9e8a5de6c2da7707, I fixed the `customize pool
size` task by replacing `item.size` with `item.value.size`. However, I
missed the same issue in the `when` condition.
> ceph-rgw: Fix customize pool size "when" condition

- roles/ceph-osd/tasks/container_options_facts.yml
- roles/ceph-osd/tasks/main.yml
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
Because we need to manage legacy ceph-disk based OSD with ceph-volume
then we need a way to know the osd_objectstore in the container.
This was done like this previously with ceph-disk so we should also
do it with ceph-volume.
Note that this won't have any impact for ceph-volume lvm based OSD.
Rename docker_env_args fact to container_env_args and move the container
condition on the include_tasks call.
Remove OSD_DMCRYPT env variable from the ceph-osd template because it's
now included in the container_env_args variable.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792122
> ceph-osd: set container objectstore env variables

- infrastructure-playbooks/filestore-to-bluestore.yml
- tests/functional/filestore-to-bluestore/container/hosts
- tests/functional/filestore-to-bluestore/container/vagrant_variables.yml
- tests/functional/filestore-to-bluestore/hosts
- tests/functional/filestore-to-bluestore/vagrant_variables.yml
- tests/functional/lvm_setup.yml
- tox-filestore_to_bluestore.ini
We still need --destroy when using a raw device otherwise we won't be
able to recreate the lvm stack on that device with bluestore.
```console
Running command: /usr/sbin/vgcreate -s 1G --force --yes ceph-bdc67a84-894a-4687-b43f-bcd76317580a /dev/sdd
stderr: Physical volume '/dev/sdd' is already in volume group 'ceph-b7801d50-e827-4857-95ec-3291ad6f0151'
Unable to add physical volume '/dev/sdd' to volume group 'ceph-b7801d50-e827-4857-95ec-3291ad6f0151'
/dev/sdd: physical volume not initialized.
--> Was unable to complete a new OSD, will rollback changes
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792227
> filestore-to-bluestore: --destroy with raw devices

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-config/tasks/main.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mds/tasks/common.yml
- roles/ceph-mgr/tasks/common.yml
- roles/ceph-mon/tasks/deploy_monitors.yml
- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
- roles/ceph-osd/tasks/common.yml
- roles/ceph-rgw/tasks/common.yml
Since this variable makes it possible to customize the mode for ceph
directories, let's make it a bit more explicit by adding a default value
in ceph-defaults.
> common: add a default value for ceph_directories_mode

- infrastructure-playbooks/filestore-to-bluestore.yml
- tests/functional/filestore-to-bluestore/container/hosts
- tests/functional/filestore-to-bluestore/container/vagrant_variables.yml
- tests/functional/filestore-to-bluestore/hosts
- tests/functional/filestore-to-bluestore/vagrant_variables.yml
When osd_auto_discovery is set then we need to refresh the
ansible_devices fact between after the filestore OSD purge
otherwise the devices fact won't be populated.
Also remove the gpt header on ceph_disk_osds_devices because
the devices is empty at this point for osd_auto_discovery.
Adding the bool filter when needed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1729267
> filestore-to-bluestore: fix osd_auto_discovery

- infrastructure-playbooks/rolling_update.yml
When upgrading from RHCS 3.x where ceph-metrics was deployed on a
dedicated node to RHCS 4.0, it fails like following:
```
fatal: [magna005]: FAILED! => changed=false
gid: 0
group: root
mode: '0755'
msg: 'chown failed: failed to look up user ceph'
owner: root
path: /etc/ceph
secontext: unconfined_u:object_r:etc_t:s0
size: 4096
state: directory
uid: 0
```
because we are trying to run `ceph-config` on this node, it doesn't make
sense so we should simply run this play on all groups except
`[grafana-server]`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1793885
> rolling_update: support upgrading 3.x + ceph-metrics on a dedicated node

- site-container.yml.sample
On HCI environment the OSD and Client nodes are collocated. Because we
aren't running the ceph-container-common role on the client nodes except
the first one (for keyring purpose) then the ceph-role execution fails
due to undefined variables.
Closes: #4970
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1794195
> site-container: don't skip ceph-container-common

- roles/ceph-facts/tasks/facts.yml
fact 'running_mon' is set once 'grep' successfully exits with 'rc == 0'
Fixes: [#4977](https://github.com/ceph/ceph-ansible/issues/4977)
Signed-off-by: Vytenis Sabaliauskas <vytenis.sabaliauskas@protonmail.com>
> ceph-facts: Fix for 'running_mon is undefined' error

- roles/ceph-handler/tasks/handler_osds.yml
Given that we delegate to the first monitor, we must read the value of
`container_exec_cmd` from this node.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792320
> handler: read container_exec_cmd value from first mon

- roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Some ganesha packages do not create ganesha log directories
while it's expected to be created while changing it's permissions.
Additionally it's no much sense in doing that as a separate task,
so directory is created as correct permissions are set with creation of
the rest required directories.
Signed-off-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>
> nfs: refact ganesha log directory creation

- infrastructure-playbooks/filestore-to-bluestore.yml
When the PV is already removed from the devices then we should not fail
to avoid errors like:
stderr: No PV found on device /dev/sdb.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1729267
> filestore-to-bluestore: don't fail when with no PV

- infrastructure-playbooks/filestore-to-bluestore.yml
If the OSD node is already using bluestore OSDs then we should skip
all the remaining tasks to avoid purging OSD for nothing.
Instead we warn the user.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790472
> filestore-to-bluestore: skip bluestore osd nodes

- infrastructure-playbooks/filestore-to-bluestore.yml
- tox-filestore_to_bluestore.ini
If the playbook is used on a host running bluestore OSDs then the
osd_fsid_list won't be filled because the bluestore OSDs are reported
with 'type: block' via ceph-volume lvm list command but we are looking
for 'type: data' (filestore).
```console
TASK [zap ceph-volume prepared OSDs] *********
fatal: [xxxxx]: FAILED! =>
msg: '''osd_fsid_list'' is undefined
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1729267
> filestore-to-bluestore: fix undefine osd_fsid_list

- roles/ceph-facts/tasks/facts.yml
When using different name between the inventory_hostname and the
ansible_hostname then the _container_exec_cmd fact will get a wrong
value based on the inventory_hostname instead of the ansible_hostname.
This happens when the ceph cluster is already running (update/upgrade).
Later the container exec commands will fail because the container name
is wrong.
We should always set the _container_exec_cmd based on the
ansible_hostname fact.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1795792
> ceph-facts: fix _container_exec_cmd fact value

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-validate/tasks/main.yml
- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/group_vars/all
- tests/functional/collocation/container/group_vars/all
- tests/functional/collocation/group_vars/all
- tests/functional/docker2podman/group_vars/all
- tests/functional/migrate_ceph_disk_to_ceph_volume/group_vars/all
- tests/functional/podman/group_vars/all
validate: fail if dashboard|grafana_admin_password aren't set
This commit adds a task to make sure the user set a custom password for
`grafana_admin_password` and `dashboard_admin_password` variables.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1795509
> validate: fail if dashboard|grafana_admin_password aren't set

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
The [rgw] section in the ceph.conf file or via the ceph_conf_overrides
variable doesn't exist and has no effect.
To apply overrides to all radosgw instances we should use either the
[global] or [client] sections.
Overrides per radosgw instance should still use the
[client.rgw.{instance-name}] section.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1794552
> ceph-defaults: remove rgw from ceph_conf_overrides

- roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
Since de8f2a9 the lvm2 package installation has been moved from ceph-osd
role to ceph-container-engine role.
But the scope wasn't limited to the OSD nodes only.
This commit fixes this behaviour.
> ceph-container-engine: lvm2 on OSD nodes only

- infrastructure-playbooks/rolling_update.yml
These tasks should have been removed with backport #4756
Note:
This should have been backported from master but it's not possible
because of too many change between master and stable-3.2
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1740463
> [stable-3.2] update: remove legacy tasks

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- roles/ceph-defaults/defaults/main.yml
RHCS 4 is available for both RHEL 7 and 8 so we should also enable the
cdn repositories for that distribution.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1796853
> ceph-common: rhcs 4 repositories for rhel 7

- roles/ceph-validate/tasks/check_system.yml
This commit allows ceph-ansible 3.2 to be run against ansible 2.7
However, note that this might break the playbook, only ansible 2.6 is
officially supported.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1781635
> validate: allow running ceph-ansible 3.2 against ansible 2.7

- roles/ceph-iscsi-gw/tasks/main.yml
- roles/ceph-iscsi-gw/tasks/non-container/postrequisites.yml
- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
During a rolling update we will run the ceph iscsigw tasks that start
the daemons then run the configure_iscsi.yml tasks which can create
iscsi objects like targets, disks, clients, etc. The problem is that
once the daemons are started they will accept confifguration requests,
or may want to update the system themself. Those operations can then
conflict with the configure_iscsi.yml tasks that setup objects and we
can end up in crashes due to the kernel being in a unsupported state.
This could also happen during creation, but is less likely due to no
objects being setup yet, so there are no watchers or users accessing the
gws yet. The fix in this patch works for both update and initial setup.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1795806
Signed-off-by: Mike Christie …
> iscsi: Fix crashes during rolling update

- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-container-cluster.yml
fix purge cluster failed when container images does not exist
Signed-off-by: wujie1993 <qq594jj@gmail.com>
> purge: fix purge cluster failed when container images does not exist

- infrastructure-playbooks/rolling_update.yml
These tasks should have been removed with backport #4756
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1793564
> update: remove legacy tasks

- roles/ceph-facts/tasks/facts.yml
This was used before the CentOS 8 requirement when using CentOS 7
atomic which has both docker and podman installed.
> ceph-facts: remove is_podman fact

- roles/ceph-facts/tasks/facts.yml
We only need to set the devices fact with osd_auto_discovery on OSD
nodes.
> ceph-facts: set devices osd_auto_discovery on OSDs

- tests/functional/add-mgrs/container/group_vars/all
- tests/functional/add-mgrs/group_vars/all
- tests/functional/add-mons/container/group_vars/all
- tests/functional/add-mons/group_vars/all
- tests/functional/add-rbdmirrors/container/group_vars/all
- tests/functional/add-rbdmirrors/group_vars/all
- tests/functional/add-rgws/container/group_vars/all
- tests/functional/add-rgws/group_vars/all
- tests/functional/shrink_mds/group_vars/all
- tests/functional/shrink_rbdmirror/group_vars/all
- tests/functional/shrink_rgw/group_vars/all
As of stable-4.0 most of these references aren't needed anymore.
> tests: remove legacy `osd_scenario` variable

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
The RHCS 4 container image is rhceph/rhceph-4
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1797743
> rhcs: update container image name

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
This wasn't necesarry. The container image was fixed on the
RedHat's registry
This reverts commit 3bd250c7422a6eaaffb2d8c6a4750b232e6b1c7e.
> Revert "rhcs: update container image name"

- roles/ceph-mon/templates/ceph-aliases.sh.j2
When using ceph aliases with commands that require manual intervention
to stop then the command will keep running inside the container (like
using Ctrl+c).
For handling this, we should use the interactive session option (-it)
with the docker commands.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1797874
> ceph-mon: use interactive session with aliases

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-defaults/defaults/main.yml
This commit increases the default values for the following variable
consumed in switch-from-non-containerized-to-containerized-ceph-daemons.yml
playbook.
This also moves these variables in `ceph-defaults` role so the user can
set different values if needed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1783223
> switch_to_containers: increase health check values

- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-dashboard/tasks/configure_grafana_layouts.yml
- roles/ceph-facts/tasks/grafana.yml
When using multiple grafana hosts then we push set the grafana and
prometheus URL and push the dashboard layout to a single node.
grafana_server_addrs is the list of all grafana nodes and used during
the ceph-dashboard role (on mgr/mon nodes).
grafana_server_addr is the current grafana node used during the
ceph-grafana and ceph-prometheus role (on grafana-server nodes).
We don't have the grafana_server_addr fact duplication code between
external vs collocated nodes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1784011
> dashboard: allow configuring multiple grafana host

- roles/ceph-validate/tasks/main.yml
We already stop the upgrade playbook (rolling_update.yml) if there's
no mgr node present so we should also do the same for initial
deployment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1788644
> ceph-validate: fail if no mgr host is present

- roles/ceph-grafana/templates/grafana-server.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-node-exporter/templates/node_exporter.service.j2
- roles/ceph-osd/templates/ceph-osd.service.j2
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
Because we are relying on docker|podman for managing containers then we
don't need systemd to manage the process (like kill).
> containers: add KillMode=none to systemd templates

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-infra/tasks/dashboard_firewall.yml
- roles/ceph-prometheus/templates/alertmanager.service.j2
When using multiple alertmanager nodes (via the grafana-server group)
then we need to specify the other peers in the configuration.
https://prometheus.io/docs/alerting/alertmanager/#high-availability
https://github.com/prometheus/alertmanager#high-availability
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792225
> ceph-prometheus: add alertmanager HA config

- roles/ceph-grafana/tasks/configure_grafana.yml
The grafana_{crt,key} aren't boolean variables but strings. The default
value is an empty string so we should do the conditional on the string
length instead of the bool filter
Closes: #5053
> ceph-grafana: fix grafana_{crt,key} condition

- group_vars/mons.yml.sample
- group_vars/osds.yml.sample
- roles/ceph-mon/defaults/main.yml
- roles/ceph-osd/defaults/main.yml
- roles/ceph-osd/tasks/crush_rules.yml
- roles/ceph-osd/tasks/main.yml
Since ed36a11 we move the crush rules creation code from the ceph-mon to
the ceph-osd role.
To keep the backward compatibility we kept the possibility to set the
crush variables on the mons side but we didn't move the default values.
As a result, when using crush_rule_config set to true and wanted to use
the default values for crush_rules then the crush rule ansible task
creation will fail.
```console
"msg": "'ansible.vars.hostvars.HostVarsVars object' has no attribute 'crush_rules'"
```
This patch move the default crush variables from ceph-mon to ceph-osd
role but also use those default values when nothing is defined on the
mons side.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1798864
> ceph-{mon,osd}: move default crush variables

- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Since nfs-ganesha 2.8.3 the rados-urls library has been move to a
dedicated package.
> ceph-nfs: add nfs-ganesha-rados-urls package

- roles/ceph-nfs/tasks/main.yml
The ceph_nfs_ceph_user variable is a string for the ceph-nfs role but a
list in ceph-client role.
6a6785b introduced a confusion between both variable type in the ceph-nfs
role for external ceph with ganesha.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1801319
> ceph-nfs: fix ceph_nfs_ceph_user variable

- roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Using ceph_dev_branch and ceph_dev_sha1 for configuring ceph-iscsi
repositories from shaman doesn't make sense because the ceph devel
branches and sha1 aren't compatible with ceph-iscsi devel.
Instead we could rely on the master branch and the latest sha1.
Currently it's not possible to using a custom ceph branch/sha1 value
with iscsi setup otherwise the repository setup will fail.
> ceph-iscsi: don't use ceph_dev_xxx variables

- tests/functional/rgw_multisite.yml
The s3cmd package should only be installed on non containerized
deployment.
> tests: don't install s3cmd on containerized setup

- roles/ceph-client/tasks/create_users_keys.yml
Client configuration with --limit fails without this patch
because certain tasks are only done to the first host in the
_filtered_clients list and it's likely that first host will
not be included in what's sepcified with --limit. To fix this
the _filtered_clients list should be built from all clients
in the inventory that are also in the running play.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1798781
Signed-off-by: John Fulton <fulton@redhat.com>
> The _filtered_clients list should intersect with ansible_play_batch

- tests/scripts/vagrant_up.sh
The CentOS 8 vagrant image download is now fixed.
This reverts commit a5385e104884a3692954e4691f3348847a35c7fa.
> Revert "vagrant: temp workaround for CentOS 8 cloud image"

- infrastructure-playbooks/purge-cluster.yml
We only support python3 so renaming all ceph python packages.
Some ceph packages were missing from the list (ceph-mon, ceph-osd or
rbd-mirror) or didn't exist anymore (ceph-fs-common, libcephfs1).
> purge-cluster: update package list to remove

- roles/ceph-dashboard/tasks/configure_dashboard.yml
The rgw user creation for the Ceph dashboard integration shouldn't be
created on secondary rgw zones.
Closes: #4707
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1794351
> rgw: don't create user on secondary zones

- roles/ceph-rgw-loadbalancer/templates/haproxy.cfg.j2
The ad7a5da commit introduced a regression when using TLS on haproxy
via the haproxy_frontend_ssl_certificate variable.
This cause the "stats socket" and the "tune.ssl.default-dh-param"
parameters to be on the same line resulting haproxy failing to start.
[ALERT] 351/140240 (21388) : parsing [xxxxx] : 'stats socket' : unknown
keyword 'tune.ssl.default-dh-param'. Registered
[ALERT] 351/140240 (21388) : Fatal errors found in configuration.
Fixes: #4869
Signed-off-by: Florian Faltermeier <florian.faltermeier@uibk.ac.at>
> ceph-rgw-loadbalancer: Fix SSL newline issue

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Both bootstrap_dirs_owner and bootstrap_dirs_group variables aren't
used anymore in the code.
> ceph-defaults: remove bootstrap_dirs_xxx vars

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-rgw/tasks/common.yml
Allow SSL certificate & key contents to be written to the path
specified by radosgw_frontend_ssl_certificate. This permits a
certificate to be deployed & renewal of expired certificates
through ceph-ansible.
Signed-off-by: Sam Choraria <sam.choraria@bbc.co.uk>
> ceph-rgw: Allow SSL certificate content to be supplied

- tests/functional/all_daemons/container/group_vars/rgws
- tests/functional/all_daemons/group_vars/rgws
- tests/functional/bs-osds/container/group_vars/rgws.yml
- tests/functional/bs-osds/group_vars/rgws.yml
- tests/functional/collocation/container/group_vars/rgws
- tests/functional/collocation/group_vars/rgws
- tests/functional/fs-osds/container/group_vars/rgws.yml
- tests/functional/fs-osds/group_vars/rgws.yml
This patch changes the pg_num value of the rgw pools foo and bar to be
a power of two number.
> [skip ci] tests: pg num should be a power of two number

- tests/functional/all_daemons/container/group_vars/rgws
- tests/functional/all_daemons/group_vars/rgws
- tests/functional/collocation/container/group_vars/rgws
- tests/functional/collocation/group_vars/rgws
- tests/functional/rgw-multisite/container/group_vars/rgws
- tests/functional/rgw-multisite/container/secondary/group_vars/rgws
- tests/functional/rgw-multisite/group_vars/rgws
- tests/functional/rgw-multisite/secondary/group_vars/rgws
This patch changes the pg_num value of the rgw pools foo and bar to be
a power of two number.
> tests: pg num should be a power of two number

- roles/ceph-dashboard/tasks/configure_dashboard.yml
- tests/functional/tests/rgw/test_rgw_tuning.py
Since [1] if a rgw user already exists then the radosgw-admin user create
command will return an error instead of modifying the current user.
We were already doing separated tasks for create and get operation but
only for multisite configuration but it's not enough.
Instead we should do the get task first and depending on the result
execute the create.
This commit also adds missing run_once and delegate_to statement.
[1] https://github.com/ceph/ceph/commit/269e9b9
> ceph-dashboard: update create/get rgw user tasks

- infrastructure-playbooks/shrink-osd.yml
In `shrink-osd.yml`, only become root on the host we delegate Ceph
commands to. This is useful when running the playbook from a host where
one isn't allowed to become root.
> infrastructure-playbooks: Run shrink-osd tasks on monitor

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-prometheus/templates/prometheus.service.j2
This change introduces a new set of tasks to configure the
ceph dashboard backend and listen just on the mgr related
subnet (and not on '*'). For the same reason the proper
server address is added in both prometheus and alertmanger
systemd units.
This patch also adds the "dashboard_frontend_vip" parameter
to make sure we're able to support the HA model when multiple
grafana instances are deployed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1792230
> Configure ceph dashboard backend and dashboard_frontend_vip

- infrastructure-playbooks/README.md
We don't need to copy the infrastructure playbooks in the root
ceph-ansible directory.
> doc: update infra playbooks statements

- infrastructure-playbooks/filestore-to-bluestore.yml
If the filestore configuration was using a dedicated journal with either
a partition or a LV/VG then we need to reuse this for bluestore DB.
When filestore is using a raw devices then we shouldn't destroy
everything (data + journal) but only data otherwise the journal
partition won't exist anymore.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790479
> filestore-to-bluestore: reuse dedicated journal

- infrastructure-playbooks/shrink-osd.yml
shrink-osd: support shrinking ceph-disk prepared osds
This commit adds the ceph-disk prepared osds support
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1796453
> shrink-osd: support shrinking a legacy ceph-disk prepared osd with ceph-volume

- infrastructure-playbooks/purge-container-cluster.yml
- infrastructure-playbooks/rolling_update.yml
- roles/ceph-handler/templates/restart_osd_daemon.sh.j2
purge-container-cluster: support OSDs with 3 digits
When running environment with OSDs having ID with more than 2 digits,
this task doesn't match the system units and therefore, fails the playbook.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1805643
> common: support OSDs with more than 2 digits

- library/ceph_volume.py
- roles/ceph-osd/tasks/scenarios/lvm-batch.yml
- tests/library/test_ceph_volume.py
This commit adds the journal option to the ceph_volume call when
scenario is lvm batch
> osd: add journal option in ceph_volume call (batch)

- roles/ceph-validate/tasks/main.yml
If the user provides manually the key value for a specific keyring then
there's not valation on the content which could lead to unexpected
failures in the ceph_key module.
Closes: #5104
> ceph-validate: add key format validation

- infrastructure-playbooks/shrink-mds.yml
- infrastructure-playbooks/shrink-mgr.yml
- infrastructure-playbooks/shrink-mon.yml
- infrastructure-playbooks/shrink-osd.yml
- infrastructure-playbooks/shrink-rbdmirror.yml
- tox.ini
The ceph-facts are running on localhost so if this node is using a
different OS/release that the ceph node we can have a mismatch between
docker/podman container binary.
This commit also reduces the scope of the ceph-facts role because we only
need the container_binary tasks.
> shrink: don't use localhost node

- tests/functional/lvm-batch/container/group_vars/all
- tests/functional/lvm-batch/container/hosts
- tests/functional/lvm-batch/container/vagrant_variables.yml
- tests/functional/lvm-batch/hosts
- tests/functional/lvm-batch/vagrant_variables.yml
This commit adds an OSD node in lvm-batch scenario in order to test
filestore backend.
> tests: add lvm batch filestore testing

- group_vars/all.yml.sample
- group_vars/clients.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-client/defaults/main.yml
- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-osd/tasks/openstack_config.yml
- roles/ceph-validate/tasks/check_pools.yml
- tests/functional/all_daemons/container/group_vars/all
- tests/functional/all_daemons/container/hosts
- tests/functional/all_daemons/container/vagrant_variables.yml
- tests/functional/all_daemons/group_vars/all
- tests/functional/all_daemons/hosts
- tests/functional/all_daemons/vagrant_variables.yml
- tests/functional/ooo-collocation/hosts
This commit adds the pg autoscaler support.
The structure for pool definition has now two additional attributes
`pg_autoscale_mode` and `target_size_ratio`, eg:
```
test:
name: "test"
pg_num: "{{ osd_pool_default_pg_num }}"
pgp_num: "{{ osd_pool_default_pg_num }}"
rule_name: "replicated_rule"
application: "rbd"
type: 1
erasure_profile: ""
expected_num_objects: ""
size: "{{ osd_pool_default_size }}"
min_size: "{{ osd_pool_default_min_size }}"
pg_autoscale_mode: False
target_size_ratio: 0.1
```
when `pg_autoscale_mode` is `True` user has to set a decent value in
`target_size_ratio`.
Given that it's a new feature, it's still disabled by default.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1782253
> osd: add pg autoscaler support

- roles/ceph-client/tasks/main.yml
There's no need to run this part of the role when upgrading clients
node. Let's skip it when rolling_update.yml is being run.
> client: skip create_users_keys.yml when rolling_update

- tests/functional/all_daemons/container/hosts-upgrade-to-nautilus
- tests/functional/all_daemons/hosts-upgrade-to-nautilus
This inventory is intended to be used in the upgrade scenario in
stable-4.0 branch.
> [skip ci] tests: add inventory host for 4.0 upgrade job

- roles/ceph-rgw/tasks/rgw_create_pools.yml
Sometimes, these task can timeout for some reason.
Adding these retries can help to avoid unexcepted failures.
> rgw: add retry/until on pools tasks

- docs/source/index.rst
In the Demo part of the Document, for both Vagrant and Bare metal the description was mentioned as "Deployment from scratch on bare metal machines".
Changed "bare metal" to "vagrant" for Vagrant section
Signed-off-by: Nizamudeen <nia@redhat.com>
> doc: Fixed a minor typo in the document

- tests/requirements.txt
3.4 is the latest testinfra release available but python2 is dropped
starting 4.0.
> tests/requirements: bump testinfra

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Instead of volumes as a static string the openstack_cinder_pool.name
variable should be used as with the other keys.
> openstack_keys: use openstack_cinder_pool.name

- roles/ceph-infra/tasks/configure_firewall.yml
This commit make that task retrying 5 times to start the service
firewalld to avoid failure like following:
```
TASK [ceph-infra : start firewalld] ********************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-purge/roles/ceph-infra/tasks/configure_firewall.yml:22
Monday 09 March 2020  08:58:48 +0000 (0:00:00.963)       0:02:16.457 **********
fatal: [osd4]: FAILED! => changed=false
msg: |-
Unable to enable service firewalld: Created symlink from /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service to /usr/lib/systemd/system/firewalld.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/firewalld.service to /usr/lib/systemd/system/firewalld.service.
Failed to execute operation: Connection reset by …
```
> infra: add retries/until on firewalld start task

- roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
This commit fixes a typo.
`s/realms/secondary_realms`
> rgw: fix a typo in create_realm_zonegroup_zone_lists

- infrastructure-playbooks/purge-container-cluster.yml
This commit removes a register which isn't used in this playbook.
> purge-container: clean legacy code

- roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
This commit fixes a typo.
`s/realms/secondary_realms`
(cherry picked from commit b3bbd6bb774de5281f117efd146557ca691aa69c)
> rgw: fix a typo in create_realm_zonegroup_zone_lists (bp #5136)

- roles/ceph-config/templates/ceph.conf.j2
This option has been deprecated (As of 0.51).
By the way, ceph-ansible already sets the
auth_{service,client,cluster}_required variables.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1623586
> config: remove legacy option in ceph.conf.j2

- group_vars/rhcs.yml.sample
- rhcs_edits.txt
We are planning to release updated grafana image for ceph dashboard in
RHCS 4.1. We need to update the rhcs edut to point to the new image
then.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786107
> rhcs_edits: Update grafana version

- roles/ceph-facts/tasks/set_radosgw_address.yml
This commit fixes the system_secret_key variable not substitued by the 
right value and always using the 'system_secret_key' string instead.
```console
$ egrep 'system_(access|secret)_key' group_vars/all.yml
system_access_key: foofoofoofoofoofoofo
system_secret_key: barbarbarbarbarbarbarbarbarbarbarbarbarb
```
```console
$ ansible-playbook -vv -i hosts site.yml.sample -e rgw_multisite=true
(...)
- hostname: storage0
endpoint: http://192.168.100.42:8080
instance_name: rgw0
radosgw_address: 192.168.50.3
radosgw_frontend_port: 8085
rgw_realm: canada
rgw_zone: montreal
rgw_zone_user: justin.trudeau
rgw_zone_user_display_name: Justin Trudeau
rgw_zonegroup: quebec
system_access_key: foofoofoofoofoofoofo
system_secret_key: system_secret_key
```
Fixes …
> ceph-facts: Fix system_secret_key variable handling

- group_vars/all.yml.sample
- roles/ceph-defaults/defaults/main.yml
Since 8e8aa73 we're using grafana 5.4.3 in RHCS 4.1 via [1].
We should also update the grafana container tag from docker.io when
using the community release.
[1] registry.redhat.io/rhceph/rhceph-4-dashboard-rhel8:4
> ceph-defaults: update grafana container tag

- group_vars/all.yml.sample
- roles/ceph-defaults/defaults/main.yml
We don't use the registry name when using the community dashboard
container images (grafana, prometheus, alertmanager & node exporter).
This commit adds the docker.io registry explicitly in the default
dashboard container image name values.
> ceph-defaults: add registry name on dashboard vars

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-defaults/defaults/main.yml
- tests/functional/collocation/container/group_vars/all
- tests/functional/collocation/group_vars/all
This commit allows one to set the role for the admin user as read-only.
This can be controlled via the dashboard_admin_user_ro variable but the
default value is false for backward compatibility.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1810176
> dashboard: allow to set read-only admin user

- roles/ceph-osd/tasks/crush_rules.yml
Let's default to `False` for the `default` attribute in `crush_rules`
variable.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1797774
> osd: add a default value for 'default' in crush_rules

- tests/conftest.py
- tests/functional/tests/grafana/test_grafana.py
- tests/functional/tests/mgr/test_mgr.py
- tests/functional/tests/node-exporter/test_node_exporter.py
- tests/pytest.ini
This commit adds basic tests for grafana, prometheus, node-exporter and
ceph mgr dashboard services.
> tests: add dashboard testinfra configuration

- tests/functional/tests/mgr/test_mgr.py
Since 15ed9ee the ceph-mgr daemon binds on the IP address on the public
network instead of binding on all addresses.
This commit updates the testinfra code to reflect that change.
> tests: update mgr dashboard socket listening test

- ceph-ansible.spec.in
- docs/source/index.rst
- requirements.txt
- roles/ceph-validate/tasks/check_system.yml
- tests/requirements.txt
Add testing against ansible 2.9 on master branch.
This commit also updates the documentation.
> doc/tests: bump to ansible 2.9 on master

- roles/ceph-facts/tasks/set_radosgw_address.yml
The rgw_instances_all fact is supposed to be the list of all radosgw
instances from all rgw nodes.
But the fact is always using the local rgw_instances variable so this
won't work on multiple nodes.
> ceph-facts: fix rgw_instances_all fact

- .github/ISSUE_TEMPLATE/bug_report.md
This commit updates the 'issue report template' to ask for full
ceph-ansible log.
> github: update issue report template

- roles/ceph-facts/tasks/set_radosgw_address.yml
The rgw_instances_all fact is supposed to be the list of all radosgw
instances from all rgw nodes.
But the fact is always using the local rgw_instances variable so this
won't work on multiple nodes.
(cherry picked from commit 0487d21938c91d4f3a48cb7157aa9b9a00f21f8f)
> ceph-facts: fix rgw_instances_all fact (bp #5184)

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
Since octopus the ceph_stable_redhat_distro variable should be set to
el8 instead of el7.
> ceph-defaults: update ceph_stable_redhat_distro

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
This is no longer true, let's remove this comment given that this option
is not ignored in containerized deployments.
> defaults: remove legacy comment

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
With Ceph Nautilus release we should use nfs-ganesha 2.8
> ceph-defaults: update ganesha to 2.8

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- rhcs_edits.txt
- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- roles/ceph-defaults/defaults/main.yml
RHCS 5 will be based on Ceph Octopus release and only supported on
RHEL 8.
> rhcs: update release to 5 for octopus

- RELEASE-NOTE.md
This adds a release not for the Ceph Nautilus release used in the
stable-4.0 branch.
> Add a release note

- library/ceph_volume.py
- tests/library/test_ceph_volume.py
When using the lvm batch ceph-volume subcommand with dedicated devices
for filestore (journal) or bluestore (db/wal) then the list of devices
is convert to a string instead of being extended via an iterable.
This was working with only one dedicated device but starting with more
then the ceph_volume module fails.
```console
TASK [ceph-osd : use ceph-volume lvm batch to create bluestore osds] **
fatal: [xxxxxx]: FAILED! => changed=true
cmd:
- ceph-volume
- --cluster
- ceph
- lvm
- batch
- --bluestore
- --yes
- --prepare
- --osds-per-device
- '4'
- /dev/nvme2n1
- /dev/nvme3n1
- /dev/nvme4n1
- /dev/nvme5n1
- /dev/nvme6n1
- --db-devices
- /dev/nvme0n1 /dev/nvme1n1
- --report
- --format=json
msg: non-zero return code
rc: 2
stderr: |2-
stderr: lsblk: /dev/nvme0n1 /dev/nvme1n1: not a block device …
```
> ceph_volume: fix multiple db/wal/journal devices

- infrastructure-playbooks/filestore-to-bluestore.yml
- infrastructure-playbooks/shrink-osd.yml
- library/ceph_volume.py
- roles/ceph-osd/tasks/start_osds.yml
- tests/library/test_ceph_volume.py
Since Ceph Octopus is python3 only we don't need to specify the max open
files anymore with the container engine.
> container: remove ulimit nofile parameter

- group_vars/all.yml.sample
- roles/ceph-defaults/defaults/main.yml
The latest Ceph stable release is now Octopus so the "latest" container
image tag is pointing to Octopus and not Nautilus anymore.
This commit updates the ceph_docker_image_tag with "latest-nautilus".
> ceph-defaults: update container tag for nautilus

- infrastructure-playbooks/purge-container-cluster.yml
Adding `--all` to the `systemctl list-units` command in order to get
*all* osds id on the node (including stoppped osds). Otherwise, it will
purge the cluster but there will be leftover after that.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1814542
> purge-container: get *all* osds id

- roles/ceph-osd/tasks/crush_rules.yml
Creating crush rules even with no crush hierarchy configuration is a
valid scenario so we shouldn't be bound to the first task result (which
configure crush hierarchy) to be able to add new crush rules.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1816989
> osd: support changing default rule even without osd_crush_location

- library/ceph_key.py
- tests/library/test_ceph_key.py
With this change, the state `present` is enough to update a keyring.
If the keyring already exist, it will be updated if caps or secret
passed to the module are different.
If the keyring doen't exist, it will be created.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1808367
> ceph_key: remove 'update' state

- infrastructure-playbooks/docker-to-podman.yml
We must call `ceph-osd` role from `container_options_facts.yml` because
ceph-osd-run.sh.j2 needs variables set in this file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1819681
> docker2podman: call `container_options_facts.yml` on osd nodes

- tests/scripts/vagrant_up.sh
The current centos/8 vagrant image (libvirt) is still using the
CentOS 8.0 release (1905) while the 8.1 release (1911) is already
available since few months.
Using an update CentOS 8 release fixes slow ceph-volume/lvm commands.
> vagrant: force centos 8.1 libvirt image

- tests/functional/shrink_mon/container/hosts
- tests/functional/shrink_mon/hosts
Since 306ce82 we explicitly fail when there's no mgr node preent in the
inventory.
```console
fatal: [mon0]: FAILED! => {
"changed": false
}
MSG:
Please add a mgr host to your inventory.
```
> tests: add mgr nodes to shrink_mon inventory

- tox-docker2podman.ini
The current docker to podman scenario is using the nautilus container
image tag instead of master.
> tox-docker2podman: update container image tag

- tox.ini
The add-mgrs scenario is still using the testinfra command instead of
pytest so the tests exectution are failling.
```console
ERROR: InvocationError for command could not find executable testinfra
```
This also adds the missing `--ssh-config` option to testinfra.
> tox: replace testinfra by pytest for add-mgrs

- library/ceph_key.py
With this change, the state `present` is enough to update a keyring.
If the keyring already exist, it will be updated if caps or secret
passed to the module are different.
If the keyring doen't exist, it will be created.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1808367
(cherry picked from commit 553584cbd0d014429e665f998776e8d198f72d2b)
> ceph_key: remove 'update' state (backport of PR #5157)

- roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- roles/ceph-mgr/tasks/pre_requisite.yml
The dashboard SSO mgr module requires the saml python library to be
installed. This is only a valid scenario for RHCS deployment because
the saml python library isn't available in other classic repositories.
This package is present in RHCS Tools repository so we also need to
enable it on the mgr nodes.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1820233
> ceph-mgr: add saml python lib for dashboard SSO

- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
When setting/unsetting osd flags, we can use `tasks_from` when importing
`ceph-facts` role to save some times given that we only need this role
for setting `container_binary`
> update: use tasks_from when including ceph-facts

- roles/ceph-handler/handlers/main.yml
- roles/ceph-handler/tasks/handler_mdss.yml
- roles/ceph-handler/tasks/handler_mgrs.yml
- roles/ceph-handler/tasks/handler_mons.yml
- roles/ceph-handler/tasks/handler_nfss.yml
- roles/ceph-handler/tasks/handler_osds.yml
- roles/ceph-handler/tasks/handler_rbd_target_api_gw.yml
- roles/ceph-handler/tasks/handler_rbdmirrors.yml
- roles/ceph-handler/tasks/handler_rgws.yml
- roles/ceph-handler/tasks/handler_tcmu_runner.yml
Make a tempfile directory and copy the restart scripts there (and then
execute them from there), rather than using insecure known filenames
in /tmp/
This is a partial fix for ceph/ceph-ansible#2937
> Use a tempfile to store restart scripts

- infrastructure-playbooks/add-osd.yml
- roles/ceph-handler/handlers/main.yml
- roles/ceph-osd/tasks/main.yml
this commit fixes a bug when using `add-osd.yml` playbook.
`noup` flag is set early but it never got unset before the "wait for pgs
clean" check, so the playbook always fails because OSDs aren't never
seen UP.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1816023
> add-osd: unset noup flag after last osd is deployed

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-dashboard/tasks/configure_grafana_layouts.yml
- roles/ceph-defaults/defaults/main.yml
Setting up a TLS dashboard currently causes some issues, as initially reported in #5053. Problems were partially fixed by #5055, but some issues remain:
- Setting `dashboard_protocol` to `https` causes the dashboard to try accessing Prometheus API though https too. However, Prometheus [does not](https://prometheus.io/docs/guides/tls-encryption/) support TLS natively. Setting up a reverse proxy such as nginx would be needed for this. For now, we just fix the protocol as plain http, which is what Prometheus supports.
- People are currently using `ceph dashboard set-grafana-api-ssl-verify False` as a workaround to get Grafana to work with TLS. In order to get the certificate to validate correctly, we can allow the user to override `grafana_server_addr` with a FQDN listed in the certificate's …
> Fix for TLS dashboard

- roles/ceph-facts/tasks/facts.yml
This commit fixes a bug when trying to scale out osd nodes with
`crush_rule_config` is enabled.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1822599
> osd: fix monitor_name error when scaling out OSDs

- roles/ceph-validate/tasks/check_system.yml
We were not testing the right ansible_distribution fact value for RHEL
distribution.
This commit also updates the minial RHEL version supported by RHCS.
> ceph-validate: update RHEL requirement for RHCS

- roles/ceph-facts/tasks/facts.yml
This is a manual backport of pull request #5261 done by Mergify
---
<details>
<br />
- `@Mergifyio rebase` will rebase this PR
</details>
> osd: fix monitor_name error when scaling out OSDs (bp #5261)

- roles/ceph-nfs/tasks/main.yml
- roles/ceph-nfs/tasks/start_nfs.yml
This commit creates an empty rados index object even when deploying
standalone nfs-ganesha.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1822328
> nfs: create empty rados index object for nfs standalone

- library/ceph_volume.py
Error message were moved to from stdout in stderr here -
https://github.com/ceph/ceph/commit/b8d6dcbe9f803c96c0af68da54f1262e9b6a9e77#diff-20f7c578a4e69ec61a5869d706567a24R137.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1793542
> library/ceph_volume: look for error messages in stderr

- roles/ceph-common/tasks/release-rhcs.yml
- roles/ceph-container-common/tasks/release.yml
- roles/ceph-validate/tasks/check_system.yml
This was removed in Ansible 2.9.
```console
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of
using `result|version_compare` use `result is version_compare`. This
feature will be removed in version 2.9. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
```
Rename 'version_compare' to the function 'version'.
version_compose was renamed to version since ansible 2.5
Signed-off-by: abaird-rh <abaird@redhat.com>
> Updated use of deprecated filter

- infrastructure-playbooks/filestore-to-bluestore.yml
When using skipped variables with from_json filter and python2 then we
need to have a default value otherwise the skipped task will fail.
Unexpected templating type error occurred on
({{ (ceph_volume_lvm_list.stdout | from_json) }}): expected string or
buffer
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1790472
> filestore-to-bluestore: fix py2 on skipped tasks

- roles/ceph-common/tasks/release-rhcs.yml
- roles/ceph-container-common/tasks/release.yml
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-osd/templates/ceph-osd-run.sh.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
- roles/ceph-validate/tasks/check_system.yml
This is a manual backport of pull request #5284 done by Mergify
---
<details>
<br />
</details>
> Updated use of deprecated filter (bp #5284)

- docs/source/day-2/osds.rst
- docs/source/day-2/purge.rst
- docs/source/index.rst
This commit is the first of a serie in order to describe all day-2 operations
that are possible via ceph-ansible using a set of playbook provided in
`infrastructure-playbooks` directory.
Fixes: #5061
> doc: add day-2 operations documentation

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
this commit removes the task which enable application on cephfs pools.
See: https://tracker.ceph.com/issues/43761
Fixes: #5278
> mds: don't enable application pool on cephfs pools

- roles/ceph-container-engine/vars/CentOS-8.yml
This adds CentOS 8 support for containerized deployment allowing podman
installation as the default container engine for this distribution.
Closes: #5130
> ceph-container-engine: add CentOS 8 support

- RELEASE-NOTE.md
This commit mentions:
- Debian support from RHCS deployment removal
> [skip ci] doc: update release note

- group_vars/all.yml.sample
- group_vars/mgrs.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-common/tasks/installs/redhat_community_repository.yml
- roles/ceph-common/tasks/installs/redhat_dev_repository.yml
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-mgr/defaults/main.yml
- roles/ceph-mgr/tasks/mgr_modules.yml
- roles/ceph-mgr/tasks/pre_requisite.yml
- roles/ceph-validate/tasks/check_system.yml
- tests/conftest.py
- tests/functional/docker2podman/group_vars/all
- tests/functional/docker2podman/hosts
The CentOS 7 distribution could still be used be deploying ceph if
- it's a containerized deployment
- it's a non containerized deployment without the dashboard (due to
missing python3 libraries).
The ceph_stable_redhat_distro variable has been remove because we can
rely on the ansible_distribution_major_version fact instead.
The copr el8 repository configuration is only applied for CentOS 8.
The ceph-mgr-dashboard package is only installed when the
dashboard_enabled variable is set to true.
> Readd CentOS 7 with conditions

- roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
15ed9ee introduced a regression for the mgr dashboard daemon using
IPv6 since the mgr dashboard configuration doesn't support brackets.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1827299
> ceph-dashboard: fix mgr dashboard IPv6 fact

- roles/ceph-dashboard/tasks/configure_dashboard.yml
This change allows the operator to refresh the
ceph dashboard admin role on multiple ceph-ansible
executions.
In the current state the role is set only when the
user is created, and there's no way to change it if
the user exists.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1826002
> Refresh ceph dashboard user role

- roles/ceph-client/tasks/create_users_keys.yml
This commit moves the dummy container creation task right before the
cephx keys creation task so it can't be run out of time.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1828105
> clients: move dummy container creation

- roles/ceph-facts/tasks/set_radosgw_address.yml
When using radosgw_interface and IPv6 setup then the _radosgw_address
fact doesn't use square brackets compared to the radosgw_address and
radosgw_address_block configuration.
Closes: #5325
> ceph-facts: fix IPv6 _radosgw_address interface

- tox-update.ini
The update container tag value should be set to latest-octopus and not
latest-master.
Also we don't need the `UPDATE_CEPH_DEV_*` environment variables.
> tox-update: fix update container tag value

- roles/ceph-nfs/tasks/main.yml
- roles/ceph-nfs/tasks/start_nfs.yml
The condition is missing an index here which makes the playbook failing.
Typical error:
```
The conditional check 'not item.get('skipped', False)' failed. The error was: error while evaluating conditional (not item.get('skipped', False)): 'list object' has no attribute 'get'",
```
Also, adds the missing '/keyring' on the `exec_cmd_nfs` fact.
Fix the condition on the keyring copy task that prevent the ganesha
keyring to be created in the /var/lib/ceph directory.
Also ensure that the directory exists first.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1831342
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1831285
> nfs: fix external ganesha keyring issues

- roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
The '==' jinja2 operator (or 'equalto') has been introduced in jinja2
2.8.
On EL7, jinja2 version is 2.7 so the operator isn't present creating
templating error like:
The error was: TemplateRuntimeError: no test named '=='
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1747206
> ceph-rgw: use match instead of equalto from jinja2

- roles/ceph-validate/tasks/check_system.yml
The `dashboard_enabled` condition used a `true` filter (which doesn't exist)
instead of the `bool` filter.
> ceph-validate: Fix "fail on unsupported CentOS release"

- roles/ceph-rgw/tasks/rgw_create_pools.yml
- roles/ceph-validate/tasks/check_rgw_pools.yml
It is common to set templated pool names in `rgw_create_pools`, e.g.
```yaml
rgw_create_pools:
"{{ rgw_zone }}.rgw.buckets.index":
pg_num: 16
size: 3
type: replicated
```
This worked fine with Ansible 2.8, but broke in Ansible 2.9 due to a change in
the way `with_dict` works [1].
This commit replaces the use of `with_dict` with
```yaml
loop: "{{ rgw_create_pools | dict2items }}"
```
which works as intended and expands the template in the pool name.
[1]: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html#loops
Closes #5348
> ceph-rgw: Make sure pool name templates are expanded

- roles/ceph-nfs/templates/ceph-nfs.service.j2
The current ganesha log directory is only present in the container
and not bind mount on the host.
> ceph-nfs: bind mount ganesha log directory

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-dashboard/tasks/configure_dashboard.yml
- roles/ceph-defaults/defaults/main.yml
When using an untrusted TLS certificate (like self-signed) on grafana
then the grafana dashboards update subcommand will fail.
One solution could be to trust the TLS certificate.
The other one is to disable the TLS verification on the grafana API.
Closes: #5324
> dashboard: allow disabling grafana api ssl verify

- infrastructure-playbooks/rolling_update.yml
The rbdmirror group name was using the wrong variable definition.
> rolling_update: fix rbdmirror group name

- infrastructure-playbooks/docker-to-podman.yml
- roles/ceph-grafana/tasks/setup_container.yml
- roles/ceph-grafana/tasks/systemd.yml
- roles/ceph-node-exporter/tasks/setup_container.yml
- roles/ceph-node-exporter/tasks/systemd.yml
- roles/ceph-prometheus/handlers/main.yml
- roles/ceph-prometheus/tasks/setup_container.yml
- roles/ceph-prometheus/tasks/systemd.yml
- tests/functional/docker2podman/group_vars/all
- tests/functional/docker2podman/hosts
- tox-docker2podman.ini
The docker2podman playbook only installs the podman package and updates
the systemd units with the right container_binary value.
We never pull the container image so if one service is restarted then
the container image will be pulled first before the service can start
which could cause longer downstream.
To avoid to download the container image from internet again we can just
pull it from the local docker daemon.
The container_{binding,package,service}_name variables are removed
because they are only used in the ceph-container-engine role which
isn't call in this playbook.
> docker2podman: pull images from docker daemon

- tox.ini
Otherwise it might try to use the system installed version of ansible
when there's one available.
> test: set sitepackages=false in tox

- tox.ini
We should use  `latest-master-devel` for switch_to_containers job.
Otherwise it might happen we actually downgrade the ceph version when
the image used is older than the rpm initially used for installing ceph.
> tests: force using the more recent build

- tests/library/test_ceph_volume.py
In containerized deployment, the ceph_volume module will always uses
the same container command prefix for all actions.
Instead of duplicate this code in all container tests we can define it
once.
This adds the objectstore testing for both filestore and bluestore on
the ceph_volume module.
> tests: improve ceph-volume testing

- roles/ceph-facts/tasks/facts.yml
always set these facts on monitor nodes whatever we run with `--limit`.
Otherwise, playbook will fail when using `--limit` on nodes where these
facts are used on a delegated task to monitor.
> facts: always set ceph_run_cmd and ceph_admin_command

- roles/ceph-client/tasks/create_users_keys.yml
- roles/ceph-mds/tasks/create_mds_filesystems.yml
- roles/ceph-osd/tasks/openstack_config.yml
The condition on this task is wrong, we have to check whether
`target_size_ratio` is set in the pool definition instead.
> common: fix target_size_ratio task enablement

- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
When using the stable nfs ganesha repository, we need have both arch
and noarch repositories enabled.
Currently the noarch repository is missing which cause the non
containerized deployment to fail.
Closes: #5375
> ceph-nfs: add stable noarch repository

- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
When using the stable nfs ganesha repository, we need have both arch
and noarch repositories enabled.
Currently the noarch repository is missing which cause the non
containerized deployment to fail.
Closes: #5375
Backport: #5377
(cherry picked from commit 44e1ebaaff61b5317bae0a3483f5d485c12bd18b)
> ceph-nfs: add stable noarch repository (bp #5377)

- RELEASE-NOTE.md
This adds a release note for the Ceph Octopus release used in the
stable-5.0 branch.
> [skip ci] doc: Add a release note

- roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
The vrrp_instances variable is using a loop with index but the index_var
wasn't defined.
As a result, the fact task was failing on this undefined index variable.
The task includes an option with an undefined variable. The error was:
'index' is undefined
Closes: #5395
Signed-off-by: Florian Faltermeier <florian.faltermeier@uibk.ac.at>
> rgwloadbalancer undefined index variable

- infrastructure-playbooks/docker-to-podman.yml
The docker commands should be based on the container_binary variable
otherwise running the playbook on a host without docker (like podman
only) will failed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1829985
> docker-to-podman: conditional docker commands

- infrastructure-playbooks/docker-to-podman.yml
- roles/ceph-grafana/tasks/setup_container.yml
- roles/ceph-grafana/tasks/systemd.yml
- roles/ceph-node-exporter/tasks/setup_container.yml
- roles/ceph-node-exporter/tasks/systemd.yml
- roles/ceph-prometheus/handlers/main.yml
- roles/ceph-prometheus/tasks/setup_container.yml
- roles/ceph-prometheus/tasks/systemd.yml
- tests/functional/docker2podman/hosts
- tox-docker2podman.ini
This is a manual backport of pull request #5280 done by Mergify
---
<details>
<br />
</details>
> docker2podman: pull images from docker daemon (bp #5280)

- .mergify.yml
This rule will probably never be applyied and at the moment this is
creating a cancelled job in the CI status.
> mergify: remove merge on skip ci

- roles/ceph-rgw/tasks/multisite/master.yml
We were only adding the endpoints to the master zone but not to the
zonegroup.
This patch fixes the issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1839228
> rgw multisite: add master zone endpoints to zonegroup

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The systemd LOAD and ACTIVE fileds could have more than one space between
both values.
This update the systemd regex the same way we're using it in different
part of the code.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1843500
> switch_to_container: fix osd systemd regex

- roles/ceph-container-common/tasks/fetch_image.yml
When a container image managed by podman isn't tag anymore then the
RepoDigests field when inspecting the image doesn't return any value.
This is different from docker workflow and it breaks the ceph-ansible
container upgrade when collocated multiple services and using a non
fix container tag (like latest or 4).
```console
$ podman images
REPOSITORY              TAG      IMAGE ID       CREATED        SIZE
docker.io/ceph/daemon   latest   680c9c0d38c3   8 days ago     957 MB
<none>                  <none>   011ee108bfc9   2 months ago   1.01 GB
```
```console
$ podman inspect 680c9c0d38c3 | jq .[0].RepoDigests[0]
"docker.io/ceph/daemon@sha256:20cf789235e23ddaf38e109b391d1496bb88011239d16862c4c106d0e05fea9e"
$ podman inspect 011ee108bfc9 | jq .[0].RepoDigests[0]
null
```
Because this field …
> container: inspect Id field instead of RepoDigests

- tests/functional/lvm_setup.yml
This fixes a long standing fail in ceph-volumes lvm test suite.
Otherwise the default behaviour should not change.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
> lvm_setup: lookup device from inventory, default to /dev/sd* names

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-osd/tasks/main.yml
We shouldn't set this flag when running switch_to_containers playbook.
Otherwise the playbook fails waiting for pgs to be clean.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1843569
> switch_to_containers: don't set noup flag

- roles/ceph-common/tasks/installs/debian_uca_repository.yml
- roles/ceph-handler/handlers/main.yml
The "update apt cache" in the ceph-handler role was never called and the
handler trigger after adding the uca repository doesn't exist at all.
Instead of using a handler for that we can just set the update_cache
parameter to true like the other apt_repository tasks.
> [skip ci] debian/uca: remove the handler notification

- library/ceph_pool.py
The name parameter is required.
> library/ceph_pool: set name parameter as required

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The workflow in this playbook should be the same than in rolling_update,
we should first set noout and nodeep-scrub flags before migrating the
first osd and unset osd flags after the last osd is migrated.
(cherry picked from commit 2cfaa056e020615bb99eb9db1520a977e5ac3ef4)
> switch-to-containers: set and unset osd flags

- RELEASE-NOTE.md
This updates the release note for ceph_pool module.
> [skip ci] Update release note

- requirements.txt
- tests/requirements.txt
ansible 2.9.10 seems to have introduced a bug.
See https://github.com/ansible/ansible/issues/70168
This commit excludes this version from ceph-ansible requirements
> requirements: exclude ansible 2.9.10

- .travis.yml
Explicitly install ansible-lint pytest pytest-cov via pip results of a
specific pytest version (4.3.1) which is not supported for pytest-cov
(2.10).
Because we are already defining a specific pytest version in the tests
requirements then we can install all the python dependencies from that
file and remove this from the pip install command.
> travis: use tests/requirements.txt

- infrastructure-playbooks/docker-to-podman.yml
This commit makes the images pulling skipped if podman isn't installed
on the machine.
In OSP context, the podman installation is done later in the workflow,
it means all `podman pull` commands will fail.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1849559
> docker2podman: make images pulling optional

- roles/ceph-grafana/templates/grafana-server.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-node-exporter/templates/node_exporter.service.j2
- roles/ceph-osd/templates/ceph-osd.service.j2
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
When using docker container engine then the systemd unit scripts only
use a dependency on the docker daemon via the After parameter.
But if docker is restarted on a live system then the ceph systemd units
should wait for the docker daemon to be fully restarted.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1846830
> [skip ci] docker: Add Requires on docker service

- library/ceph_volume.py
- tests/library/test_ceph_volume.py
This commit makes the zap function idempotent, especially when using
lvm_volumes variable.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1845668
> ceph_volume: make zap function idempotent

- roles/ceph-grafana/templates/grafana-server.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
- roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
- roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
- roles/ceph-mds/templates/ceph-mds.service.j2
- roles/ceph-mgr/templates/ceph-mgr.service.j2
- roles/ceph-mon/templates/ceph-mon.service.j2
- roles/ceph-nfs/templates/ceph-nfs.service.j2
- roles/ceph-node-exporter/templates/node_exporter.service.j2
- roles/ceph-osd/templates/ceph-osd.service.j2
- roles/ceph-prometheus/templates/alertmanager.service.j2
- roles/ceph-prometheus/templates/prometheus.service.j2
- roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
This changes the way we are running the podman containers via systemd.
They are now in dettached mode and Type/PIDFile set.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1834974
> podman: Add Type and PIDFile value to unit files

- roles/ceph-dashboard/tasks/configure_dashboard.yml
This commit makes the playbook copying self-signed generated certificate
to monitors.
When mons and mgrs are deployed on dedicated nodes the playbook will
fail when trying to import certificate and key files since they are
generated on mgrs whereas we try to import them from a monitor.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1846995
> dashboard: copy self-signed generated crt to mons

- roles/ceph-dashboard/tasks/configure_dashboard.yml
We need to set the mgr dashboard server ip address before restarting the
dashboard module otherwise we can try to bind the dashboard module on an
already used address.
We already do this configuration for the dashboard port value and ssl
setup so we should do the same for server address too.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1851455
> dashboard: configure mgr backend before restart

- infrastructure-playbooks/cephadm-adopt.yml
The commit adds a new playbook for converting an existing ceph cluster
deployed by ceph-ansible to the cephadm orchestrator.
> [skip ci] Add playbook for converting cluster to cephadm

- infrastructure-playbooks/rolling_update.yml
If a failure occurs in ceph-validate, the upgrade playbook keeps running
where we expect it to fail.
> rolling_update: add any_errors_fatal

- library/ceph_volume.py
See https://github.com/ceph/ceph/pull/34740 for the batch changes.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
Note that this is backwards compatible. Intention is to backport this to stable-4.0 and newer.
> ceph-volume.py: add support for batch refactored code

- tests/scripts/vagrant_up.sh
CentOS 8.2 (2004) has been relesed so we should switch to this image
when using vagrant.
> vagrant: update centos image to 8.2

- tests/requirements.txt
This commit enforces the pytest-rerunfailures installed so it's <9.0
This is to avoid the following error:
```
ERROR: pytest-rerunfailures 9.0 has requirement pytest>=5.0, but you'll have pytest 4.6.11 which is incompatible.
```
latest version of pytest-rerunfailures isn't compatible with the version
of pytest we are using.
> tests: enforce pytest-rerunfailures version

- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- roles/ceph-config/tasks/main.yml
- roles/ceph-config/tasks/rgw_systemd_environment_file.yml
- roles/ceph-rgw/tasks/common.yml
- roles/ceph-rgw/tasks/start_docker_rgw.yml
When rgw and osd are collocated, the current workflow prevents from
scaling out the radosgw_num_instances parameter when rerunning the
playbook.
The environment file used in the rgw systemd template is rendered when
executing the `ceph-rgw` role but during a new run of the playbook (in
order to scale out rgw instances), handlers are triggered from `ceph-osd`
role which is run before `ceph-rgw`, therefore it tries to start the new
rgw daemon whereas its corresponding environment file hasn't been
rendered yet and fails like following:
```
ceph-radosgw@rgw.ceph4osd3.rgw1.service failed to run 'start-pre' task: No such file or directory
```
This commit moves the tasks generating this file in `ceph-config` role
so it is generated early.
Closes: …
> rgw: fix multi instances scaleout

- roles/ceph-config/tasks/rgw_systemd_environment_file.yml
- roles/ceph-rgw/templates/ceph-radosgw.service.j2
This variable isn't consumed by the container so we can remove it.
> radosgw: remove INST_PORT environment variable

- infrastructure-playbooks/add-mon.yml
- infrastructure-playbooks/add-osd.yml
- infrastructure-playbooks/cephadm-adopt.yml
- infrastructure-playbooks/docker-to-podman.yml
- infrastructure-playbooks/filestore-to-bluestore.yml
- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-container-cluster.yml
- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/shrink-rgw.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- site-container.yml.sample
- site.yml.sample
By default, ansible gathers facts from facter and ohai if installed on
the remote nodes, given we don't need them, let's exclude these facts
from our facts gathering
> facts: explicitly disable facter and ohai

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
nfs-ganesha 3.3 is the latest 3.x release available for octopus so we
should update to this version.
https://download.ceph.com/nfs-ganesha/rpm-V3.3-stable/octopus
This will also match the version used in RHCS 5.
Ceph container already uses that version too.
> [skip ci] ceph-defaults: update nfs-ganesha to 3.3

- docs/source/day-2/upgrade.rst
Typical error:
```
Warning, treated as error:
/home/jenkins-build/build/workspace/ceph-ansible-docs-pull-requests/docs/source/day-2/upgrade.rst:2:Title underline too short.
```
> doc: fix warning treated as an error

- docs/source/index.rst
- docs/source/installation/containerized.rst
- docs/source/installation/methods.rst
- docs/source/installation/non-containerized.rst
This PR adds two minor updates to the documentation:
- Add a note about containerized context
- Add a note about deprecated branches of ceph-ansible
> doc: minor updates

- tests/functional/all_daemons/group_vars/nfss
not really needed in master, commit intended to be backported in octopus
branch.
> [skip ci] tests: update nfs-ganesha to V3.3-stable

- tests/functional/all_daemons/group_vars/nfss
not really needed in master, commit intended to be backported in octopus
branch.
(cherry picked from commit 5b6f5486f7aa71ab9ca7dcab37d9156e597c5cb1)
> tests: update nfs-ganesha to V3.3-stable

- tests/functional/all_daemons/group_vars/nfss
We don't need to override this variable in the group_vars but use the
default value instead.
> [skip ci] tests: remove nfs_ganesha_stable_branch variable

- roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
The download.nfs-ganesha.org source for nfs-ganesha on CentOS isn't
available anymore.
Let's switch back to shaman since we have builds available now.
> [skip ci] ceph-nfs: change ganesha devel source

- docs/source/index.rst
This commit adds the missing stable-5.0 details about what it is
supported in this branch regarding ceph/ansible.
Fixes: #5519
> doc: add stable-5.0 note in release section

- roles/ceph-osd/templates/ceph-osd-run.sh.j2
When using collocated or non-collocated osd_scenarios (ceph-disk) and
trying to deterime the OSD_DEVICE from the OSD_ID passed to the systemd
unit then we can be in a situation where the OSD hasn't been activated
but the OSD ID exists.
This means the data partition isn't in activate state and the ceph-disk
list command won't show the OSD ID on the data partition.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1850377
> ceph-osd: exit gracefully when no data partition

- infrastructure-playbooks/add-osd.yml
- infrastructure-playbooks/purge-cluster.yml
- infrastructure-playbooks/purge-docker-cluster.yml
- infrastructure-playbooks/rolling_update.yml
- infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
- site-docker.yml.sample
- site.yml.sample
By default, ansible gathers facts from facter and ohai if installed on
the remote nodes, given we don't need them, let's exclude these facts
from our facts gathering
Backport: #5486
(cherry picked from commit c95adc564b8be6f9f9b1ba8568072daf39da7a2c)
> facts: explicitly disable facter and ohai (bp #5486)

- README-MULTISITE.md
The automatic backport [1] done by mergify has merged the backport PR
even if a conflict was present in the documentation.
[1] https://github.com/ceph/ceph-ansible/pull/3803
> README-MULTISITE: fix old conflict

- infrastructure-playbooks/gather-ceph-logs.yml
- site-container.yml.sample
- site.yml.sample
It's time to remove this old group name.
> play: remove backward compatibility group name

- group_vars/all.yml.sample
- group_vars/rhcs.yml.sample
- roles/ceph-defaults/defaults/main.yml
- roles/ceph-facts/tasks/facts.yml
There's no need to set this fact with a `set_fact`
We can achieve this in `ceph-defaults`
> facts: refact `ceph_uid` fact
