ceph/ceph-ansible

tox-docker2podman.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-update.ini, tox.ini
This commit makes all jobs authenticating to docker hub in order to
avoid the rate limit.
(cherry picked from commit 40307f810c76f22b7152cb1f4113089a22a84274)
=> [backport stable-5.0] tests: add docker hub authentication in jobs

group_vars/rgws.yml.sample, roles/ceph-rgw/defaults/main.yml
This commit changes the container memory limit for rgw daemons.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1707488
=> rgw: set container memory limit to 4g

infrastructure-playbooks/cephadm-adopt.yml
It's better to use the --placement parameter when using ceph orch apply
commands to avoid confusion in the parameters.
=> [skip ci] cephadm-adopt: use placement parameter

tox-docker2podman.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-update.ini, tox.ini
This commit makes all jobs authenticating to docker hub in order to
avoid the rate limit.
(cherry picked from commit 40307f810c76f22b7152cb1f4113089a22a84274)
=> [Backport stable-4.0] tests: add docker hub authentication in jobs

infrastructure-playbooks/cephadm-adopt.yml
This is a partial revert of b38019e because we don't want to execute
the whole play on the monitor otherwise if we have some empty group
like rgws or mdss then the orchestrator commands will still be
executed.
Instead we should keep the real target group name at play level and
delegate the orchestator commands to the monitor. The whole play
will be skipped is the group is empty.
=> [skip ci] cephadm-adopt: delegate task for orch apply

roles/ceph-dashboard/tasks/configure_dashboard.yml
The ceph-dashboard role is executed on the mgr nodes so the TLS cert/key
files are copied to those nodes.
But we are running importing the cert/key files into the ceph
configuration on the monitor.
Closes: #5557
=> ceph-dashboard: copy TLS cert/key on monitor

roles/ceph-facts/tasks/facts.yml
This commit fixes these tasks when --limit is used.
It makes sure the fact is set on right nodes even when the playbook is
run with `--limit`
=> facts: fix broken facts when using --limit

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-config/tasks/main.yml, roles/ceph-config/tasks/rgw_systemd_environment_file.yml, roles/ceph-rgw/tasks/common.yml, roles/ceph-rgw/tasks/start_docker_rgw.yml, roles/ceph-rgw/templates/ceph-radosgw.service.j2
When rgw and osd are collocated, the current workflow prevents from
scaling out the radosgw_num_instances parameter when rerunning the
playbook.
The environment file used in the rgw systemd template is rendered when
executing the `ceph-rgw` role but during a new run of the playbook (in
order to scale out rgw instances), handlers are triggered from `ceph-osd`
role which is run before `ceph-rgw`, therefore it tries to start the new
rgw daemon whereas its corresponding environment file hasn't been
rendered yet and fails like following:
```
ceph-radosgw@rgw.ceph4osd3.rgw1.service failed to run 'start-pre' task: No such file or directory
```
This commit moves the tasks generating this file in `ceph-config` role
so it is generated early.
Closes: …
=> backport stable-4.0 of: rgw: fix multi instances scaleout

library/ceph_volume.py
do not skip zapping if osd_fsid is passed
(cherry picked from commit f402ab2b87813f0f9c3fba661a52f5afebc19723)
=> [backport stable-4.0] ceph_volume: fix regression

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml
Set the cephadm cmd as a fact instead of rewriting the same command
over and over.
This also fix an issue when using docker as container engine because
the --docker cephadm parameter should be use before the subcommand
not after.
=> [skip ci] cephadm: set the command as a fact

roles/ceph-facts/tasks/facts.yml
This commit fixes these tasks when --limit is used.
It makes sure the fact is set on right nodes even when the playbook is
run with `--limit`
(cherry picked from commit f8a951f50c6a64ab3d60a1bf66ca9d2db2f6bc35)
=> facts: fix broken facts when using --limit (bp #5544)

group_vars/all.yml.sample, group_vars/nfss.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-nfs/defaults/main.yml
These variables aren't consummed anywhere else than in ceph-nfs role so
there is no need to have them in `ceph-defaults`'s defaults
=> defaults: remove legacy

infrastructure-playbooks/docker-to-podman.yml, infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/purge-container-cluster.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-container-common/tasks/fetch_image.yml, roles/ceph-crash/meta/main.yml, roles/ceph-crash/tasks/main.yml, roles/ceph-crash/tasks/systemd.yml, roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-handler/handlers/main.yml, roles/ceph-handler/tasks/check_running_containers.yml, roles/ceph-handler/tasks/check_socket_non_container.yml, roles/ceph-handler/tasks/handler_crash.yml, roles/ceph-handler/tasks/main.yml, site-container.yml.sample, site.yml.sample, tests/conftest.py, tests/functional/tests/test_install.py
This commit introduces a new role `ceph-crash` in order to deploy
everything needed for the ceph-crash daemon.
=> ceph-crash: introduce new role ceph-crash

roles/ceph-crash/templates/ceph-crash.service.j2
We should ensure the container is removed in `ExecPreStart` even when
`{{ container_binary }}` is docker.
=> [skip ci] crash: rm container in ExecPreStart even with docker

roles/ceph-handler/handlers/main.yml, roles/ceph-handler/tasks/check_running_containers.yml, roles/ceph-handler/tasks/check_socket_non_container.yml
The ceph-crash tasks present in the ceph-handler role don't need to be
executed on all nodes.
=> ceph-handler: add missing condition on ceph-crash

tests/functional/lvm_setup.yml
when rerunning lvm_setup.yml on existing cluster with OSDs already
deployed, it fails like following:
```
fatal: [osd0]: FAILED! => changed=false
msg: Sorry, no shrinking of data-lv2 to 0 permitted.
```
because we are asking `lvol` module to create a volume on an empty VG
with size extents = `100%FREE`.
The default behavior of `lvol` is to shrink the volume if the LV's current
size is greater than the requested size.
Given the requested size is calculated like this:
`size_requested = size_percent * this_vg['free'] / 100`
in our case, it is similar to:
`size_requested = 100 * 0 / 100` which basically means `0`
So the current LV size is well greater than the requested size which
leads the module to attempt to shrink it to 0 which isn't obviously now
allowed.
Adding `shrink: false` to the …
=> tests: (lvm_setup.yml), don't shrink lvol

tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-update.ini, tox.ini
since we've dropped ubuntu testing on PRs and nightlies, we don't need
these references anymore in tox files.
=> tox: remove ubuntu references

roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
In case of failure, the systemd ExecStop isn't executed so the container
isn't removed. After a reboot of a failed node, the container doesn't
start because the old container is still present in created state.
We should always try to remove the container in ExecStartPre for this
situation.
A normal reboot doesn't trigger this issue and this also doesn't affect
nodes running containers via docker.
This behaviour was introduced by d43769d.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1858865
=> podman: always remove container on start

roles/ceph-handler/handlers/main.yml, roles/ceph-handler/tasks/handler_rbd_target_api_gw.yml, roles/ceph-handler/tasks/handler_tcmu_runner.yml, roles/ceph-handler/templates/restart_rbd_target_api.sh.j2, roles/ceph-handler/templates/restart_rbd_target_gw.sh.j2, roles/ceph-handler/templates/restart_tcmu_runner.sh.j2
The iscsigws restart scripts for tcmu-runner and rbd-target-{api,gw}
services only call the systemctl restart command.
We don't really need to copy a shell script to do it when we can use
the ansible service module instead.
=> ceph-handler: remove iscsigws restart scripts

roles/ceph-facts/tasks/facts.yml, roles/ceph-handler/templates/restart_mds_daemon.sh.j2, roles/ceph-mds/tasks/common.yml, roles/ceph-mds/tasks/non_containerized.yml
The mds_name fact always gets the ansible_hostname value so we don't
need to have a dedicated fact for this and use the ansible_hostname fact
instead.
=> [skip ci] ceph-facts: remove mds_name fact

roles/ceph-handler/tasks/handler_rbd_target_api_gw.yml, roles/ceph-handler/tasks/handler_tcmu_runner.yml, roles/ceph-handler/templates/restart_rbd_target_api.sh.j2, roles/ceph-handler/templates/restart_rbd_target_gw.sh.j2, roles/ceph-handler/templates/restart_tcmu_runner.sh.j2
The iscsigws restart scripts for tcmu-runner and rbd-target-{api,gw}
services only call the systemctl restart command.
We don't really need to copy a shell script to do it when we can use
the ansible service module instead.
Backport: #5574
(cherry picked from commit cbe79428e687e383f9764668a56171e5582451be)
=> ceph-handler: remove iscsigws restart scripts (bp #5574)

infrastructure-playbooks/rolling_update.yml
During the daemon upgrade we're
- stopping the service when it's not containerized
- running the daemon role
- start the service when it's not containerized
- restart the service when it's containerized
This implementation has multiple issue.
1/ We don't use the same service workflow when using containers
or baremetal.
2/ The explicity daemon start isn't required since we'are already
doing this in the daemon role.
3/ Any non backward changes in the systemd unit template (for
containerized deployment) won't work due to the restart usage.
This patch refacts the rolling_update playbook by using the same service
stop task for both containerized and baremetal deployment at the start
of the upgrade play.
It removes the explicit service start task because it's already included
in the dedicated …
=> rolling_update: stop/start instead of restart

infrastructure-playbooks/rolling_update.yml
During the daemon upgrade we're
- stopping the service when it's not containerized
- running the daemon role
- start the service when it's not containerized
- restart the service when it's containerized
This implementation has multiple issue.
1/ We don't use the same service workflow when using containers
or baremetal.
2/ The explicity daemon start isn't required since we'are already
doing this in the daemon role.
3/ Any non backward changes in the systemd unit template (for
containerized deployment) won't work due to the restart usage.
This patch refacts the rolling_update playbook by using the same service
stop task for both containerized and baremetal deployment at the start
of the upgrade play.
It removes the explicit service start task because it's already included
in the dedicated …
=> rolling_update: stop/start instead of restart (bp #5572)

infrastructure-playbooks/rolling_update.yml
The dashboard upgrade workflow should do the same process than the ceph
upgrade otherwise any systemd unit modification won't be apply on the
monitoring/dashboard stack.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1859173
(cherry picked from commit a6209bd957e40c9c42370eab73ae99e73d53c8a4)
=> rolling_update: refact dashboard workflow (bp #5572)

tests/requirements.txt
The pytest-forked 1.3.0 release isn't compatible with the pytest release
we are using in that branch.
-----------------------
pytest-forked 1.3.0 requires pytest>=3.10, but you'll have pytest 3.6.1
which is incompatible.
-----------------------
=> tests: pin pytest-forked to 1.2.0

tests/functional/setup.yml
Due to [1], ceph-volume has now a dependency on pyyaml but it's not
installed by default via the package dependency.
This patch only add the required package on non containerized
deployment and as temporary workaround for the CI.
[1] https://tracker.ceph.com/issues/46759
=> tests: install pyyaml on osd nodes

infrastructure-playbooks/rolling_update.yml
In addition of 155e2a2, the active mds daemons isn't stop/start
correctly as opposed as the other services so that daemon doesn't come
back after the upgrade.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1861688
=> [skip ci] rolling_update: restart active mds after the upgrade

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-grafana/tasks/configure_grafana.yml
When using TLS on the ceph dashboard or grafana services, we can provide
the TLS certificate and key.
Those files should be present on the ansible controller and they will be
copyied to the right node(s).
In some situation, the TLS certificate and key could be already present
on the target node and not on the ansible controller.
For this scenario, we just need to copy the files locally (on each remote
host).
This patch adds the dashboard_tls_external variable (with default to
false) to allow users to achieve this scenario when configuring this
variable to true.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1860815
=> dashboard: allow remote TLS cert/key copy

roles/ceph-config/templates/ceph.conf.j2
there's no need to add each rgw section on all rgw nodes.
With this commit, only related rgw section are rendered.
=> config: only add related rgw section

tests/functional/lvm-osds/container/group_vars/all, tests/functional/lvm-osds/container/vagrant_variables.yml
This commit changes the subnets in container-lvm_osds scenario.
=> tests: change subnet in lvm_osds container scenario

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Remove /usr/lib/systemd/system/ceph-radosgw.target when switching to containerize daemons
=> [skip ci] Remove ceph-radosgw.target when switching to containerize daemons

infrastructure-playbooks/shrink-osd.yml
This handles missing /etc/ceph/osd, by ensuring we actually found files in
`/etc/ceph/osd` before trying to slurp their content.
This also add a missing `| default(False)` to avoid fowlloing error:
```
fatal: [ceph01]: FAILED! =>
msg: |-
The conditional check 'ceph_osd_data_json[item.2]['encrypted'] | bool' failed. The error was: error while evaluating conditional (ceph_osd_data_json[item.2]['encrypted'] | bool): 'dict object' has no attribute 'encrypted'
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1862416
=> shrink-osd: various fixes

infrastructure-playbooks/purge-cluster.yml
There is no need to use `shell` here.
=> purge-cluster: replace shell by command in a task

roles/ceph-osd/tasks/start_osds.yml, roles/ceph-osd/templates/ceph-osd-run.sh.j2
This commit makes the bindmount a bit more generic, otherwise it
currently makes the OSDs failing to start in an OSP FFU upgrade
(with RHEL7 > RHEL8 OS upgrade).
docker2podman playbook is run from ceph-ansible stable-3.2 branch
against RHEL7 nodes where `/var/run/lvmetad.socket` exists but once the
system is upgraded to RHEL8, this socket doesn't exist anymore and
prevent OSDs from starting after the reboot.
As a workaround we can make this bindmount a bit more generic like what
is done in `stable-4.0` branch by mounting `/run/lvm` instead.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1866252
=> osd: change lvm bindmount

tests/pytest.ini
Otherwise we see some pytest warning.
PytestUnknownMarkWarning: Unknown pytest.mark.ceph_crash - is this a typo?
You can register custom marks to avoid this warning - for details,
see https://docs.pytest.org/en/latest/mark.html
=> [skip ci] pytest: register ceph_crash mark

infrastructure-playbooks/purge-cluster.yml
When running `infrastructure-playbooks/purge-cluster.yml` twice, it fails the
second time on the `ensure rbd devices are unmapped` task, because `rbdmap`
isn't installed anymore at that point.
This commit adds a check that ensures `rbdmap` is available, and skips the
`ensure rbd devices are unmapped` task if it isn't.
=> purge-cluster: check if rbdmap exists

tox.ini
There's no need to call `sleep 30` for other job than `all_daemons` and
`all_in_one`.
=> tox: only wait 30sec for right jobs

roles/ceph-nfs/tasks/pre_requisite_non_container.yml
This keyring shouldn't be copied when `nfs_obj_gw` is `True` if the
cluster doesn't contain a rgw node, which can be the case given we are
using `nfs_obj_gw` instead of `nfs_file_gw` (cephfs vs. object), the
deployment will fail trying to copy a key that doesn't exist.
=> nfs: do not copy rgw keyring when `nfs_obj_gw` is true

roles/ceph-facts/tasks/set_radosgw_address.yml
…nstance,
Commit on behalf of Daniel Parkes
Change the radosgw_frontend_port to take in account more than 1 RGW instance, in it’s original form `'radosgw_frontend_port': radosgw_frontend_port | int` , it configured the 8080 port to all instances, with the following modification 'radosgw_frontend_port': radosgw_frontend_port | int + item|int we increase in 1 the port count.
Signed-off-by: raul <rmahique@redhat.com>
=> [skip ci] rgw: support 1+ rgw instance in `radosgw_frontend_port`

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/filestore-to-bluestore.yml, infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/purge-container-cluster.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/shrink-osd.yml, infrastructure-playbooks/storage-inventory.yml, roles/ceph-config/tasks/main.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-infra/tasks/main.yml, roles/ceph-infra/templates/logrotate.conf.j2, roles/ceph-osd/tasks/scenarios/lvm-batch.yml, roles/ceph-osd/tasks/scenarios/lvm.yml
This commit adds the log rotation support via logrotate in containerized
deployments.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1848388
=> infra: add log rotation support (containers)

tests/functional/all_daemons/hosts
This commit makes the ci using stable build for testing iscsigw in
stable-5.0
=> tests: test iscsigw against stable build

tests/functional/all_daemons/hosts
Since it is broken at the moment with dev repos, let's test against
stable builds so the CI is unlocked.
=> tests: test iscsigw against stable

roles/ceph-infra/tasks/main.yml
This commit adds the missing `with_pkg` tag on the logrotate
installation task.
=> [skip ci] infra: add missing tag

infrastructure-playbooks/purge-cluster.yml
This way we keep consistency with purge-container-cluster.yml playbook.
=> purge-cluster: use sysfs method for unmapping rbd devices

roles/ceph-facts/tasks/set_radosgw_address.yml
Allows rgws in a ceph cluster to be run with multisite and without multisite at the same time.
=> rgw: allow rgws can be run with or without multisite at the same

site-container.yml.sample
We only need the container engine to be installed on the first clients
node in order to execute the pools/keys operation. We already do the
same worflow with the ceph-container-common role which pull the ceph
container image.
=> [skip ci] container: don't install the engine on all clients

group_vars/rgws.yml.sample, roles/ceph-rgw/defaults/main.yml, roles/ceph-rgw/tasks/rgw_create_pools.yml
We already support specifiying a custom crush rule during pool creation
in ceph-osd role but not in ceph-rgw role.
This patch adds the missing code to implement this feature.
Note this is only available for replicated pool not erasure. The rule
must also exist prior the pool creation.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1855439
=> [skip ci] ceph-rgw: allow specifying crush rule on pool

.travis.yml
Let's pin to 4.2.0
(because of ansible/ansible-lint/issues/966)
=> [skip ci] travis: enforce ansible-lint 4.2.0

.travis.yml
Let's pin to 4.2.0
(because of ansible/ansible-lint/issues/966)
(cherry picked from commit 04d77dcaebb52734a1c6d1838ecfa669bf8f3c67)
=> [skip ci] travis: enforce ansible-lint 4.2.0 (bp #5676)

roles/ceph-infra/tasks/main.yml
For intsance, there is no need to install logrotate on clients nodes.
=> [skip ci] infra: only install logrotate on right nodes

roles/ceph-mgr/tasks/mgr_modules.yml
Otherwise, even though we set the pg autoscaler attribute on a pool, the
feature won't be working as expected.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1836431
=> mgr: enable pg_autoscaler by default

infrastructure-playbooks/shrink-mds.yml
When using fqdn in inventory host file, this task will fail because the
mds is registered with its shortname.
It means we must use `mds_to_kill_hostname` in this task.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1869837
=> [skip ci] shrink-mds: use mds_to_kill_hostname instead

roles/ceph-prometheus/tasks/main.yml
Regardless of the outcome of Ansible 2.9.12 issue 71200
we can set a default permission for these files.
Closes: https://github.com/ceph/ceph-ansible/issues/5677
Signed-off-by: John Fulton <fulton@redhat.com>
=> [skip ci] Set default permission for prometheus config files

roles/ceph-osd/tasks/start_osds.yml, roles/ceph-osd/tasks/systemd.yml
This commit moves the systemd rendering task into `systemd.yml` file.
Otherwise, when running docker to podman playbook, the systemd unit file
isn't updated as it should be.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1870141
=> osd: move systemd rendering task

tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/container/group_vars/clients, tests/functional/all_daemons/container/hosts, tests/functional/all_daemons/container/vagrant_variables.yml, tests/functional/all_daemons/group_vars/all, tests/functional/all_daemons/group_vars/clients, tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml, tests/functional/lvm-osds/container/group_vars/all, tests/functional/lvm-osds/group_vars/all
This commit moves the erasure pool creation testing from `all_daemons`
to `lvm_osds` so we can decrease the number of osd nodes we spawn so the
OVH Jenkins slaves aren't less overwhelmed when a `all_daemons` based
scenario is being tested.
=> tests: move erasure pool testing in lvm_osds

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
Since there is a check if ceph_custom_key is defined, there is no reason
to define it by default.
Signed-off-by: Rafał Wądołowski <rwadolowski@cloudferro.com>
=> [skip ci] Comment out ceph_custom_key

tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/container/group_vars/clients, tests/functional/all_daemons/container/hosts, tests/functional/all_daemons/container/vagrant_variables.yml, tests/functional/all_daemons/group_vars/all, tests/functional/all_daemons/group_vars/clients, tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml, tests/functional/lvm-osds/container/group_vars/all, tests/functional/lvm-osds/group_vars/all
This commit moves the erasure pool creation testing from `all_daemons`
to `lvm_osds` so we can decrease the number of osd nodes we spawn so the
OVH Jenkins slaves aren't less overwhelmed when a `all_daemons` based
scenario is being tested.
(cherry picked from commit 8476beb5b1f673d8b0925293d9273041c99a9bac)
=> [backport] tests: move erasure pool testing in lvm_osds

roles/ceph-dashboard/tasks/configure_dashboard.yml
This should reduce number of 'changed' tasks during convergence test.
=> [skip ci] Make 'disable ssl for dashboard task' idempotent.

tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml
This re-adds the nfs-ganesha testing in non containerized deployment.
=> [skip ci] tests: reenable nfs-ganesha testing

roles/ceph-facts/tasks/facts.yml
there's no need to run this task on all nodes.
This uses too much memory for nothing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1856981
=> facts: refact and optimize memory consumption

roles/ceph-dashboard/tasks/configure_dashboard.yml
this commit splits this task in order to avoid using a `shell` module.
=> [skip ci] dashboard: refact admin user creation task

roles/ceph-rgw-loadbalancer/templates/haproxy.cfg.j2
Fix the `httpchk` parameter to use valid HTTP verb.
Currently traffic will be forwarded to offline `radosgw` services. These changes resolve the issue.
Signed-off-by: Niko Smeds nikosmeds@gmail.com
=> Fix HAProxy httpchk parameter for Ceph RGW

tests/functional/all_daemons/container/hosts, tests/functional/all_daemons/container/vagrant_variables.yml, tests/functional/all_daemons/hosts
This re-adds the ceph-iscsi testing for both non containerized and
containerized deployment since the rados connection error on ceph
dev has been fixed [1].
[1] https://tracker.ceph.com/issues/47002
=> tests: reenable ceph-iscsi testing

infrastructure-playbooks/rolling_update.yml
On DCN environments, or when multiple ceph cluster are configured,
we need to specify the cluster name before running the command or
the rolling_update playbook will fail during minor updates.
Closes: https://bugzilla.redhat.com/1876447
=> Add --cluster option on ceph require-osd-release command

infrastructure-playbooks/rolling_update.yml
In the OSP context, during the rolling update the playbook fails
with the following error:
'''
ERROR! The field 'hosts' has an invalid value, which includes an
undefined variable. The error was: list object has no element 0
'''
This PR just change the hosts field providing a valid mons group
value.
Closes: https://bugzilla.redhat.com/1876803
=> [skip ci] Fix hosts field in rolling_update playbook when mds are processed

tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all, tests/functional/docker2podman/group_vars/all, tests/functional/podman/group_vars/all
This changes the grafana container image regitry from docker.io to
quay.io to avoid rate limit.
This also adds the missing container image values for docker2podman
and podman scenarios.
=> tests: use grafana from quay.io

roles/ceph-rgw/tasks/rgw_create_pools.yml
Since [1] we can use the ceph_pool module instead of using the command
module combined with ceph osd pool commands.
[1] bddcb439ce1b46735946e9fd5d147bc6604bcda3
=> ceph-rgw: use ceph_pool module

dashboard.yml, infrastructure-playbooks/rolling_update.yml, roles/ceph-facts/tasks/facts.yml, tox-external_clients.ini
When running the rolling_update playbook with an inventory without
monitor nodes defined (like external scenario) then we can't retrieve
the cluster fsid from the running monitor.
In this scenario we have to pass this information manually (group_vars
or host_vars).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1877426
=> ceph-facts: only get fsid when monitor are present

tests/functional/collocation/group_vars/all
Even if the non containerized collocation scenario deploys ceph with
RPMs then we also deploy the dashboard/monitoring but with containers.
This requires to set the registry variable to ceph's quay.
=> tests: add quay registry for collocation baremetal

roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-mds/tasks/create_mds_filesystems.yml, roles/ceph-osd/tasks/openstack_config.yml
The crush rule value was only set once during the pool creation. It was
not possible to update the crush rule value by updating the value in the
configuration.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1847166
=> Allow updating crush rule on existing pool

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-common/tasks/installs/redhat_community_repository.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml, tests/functional/setup.yml
We were only supporting CentOS 8 for containerized deployment.
Since Nautilus 14.2.10 we now have el8 rpm packages so we should be
able to deploy a nautilus ceph cluster with el8.
Note that the nfs-ganesha isn't supported because there's no el8 rpm
packages for nfs-ganesha V2.8.
=> [skip ci] Add CentOS 8 support for rpm deployment

roles/ceph-facts/tasks/facts.yml
there's no need to run this task on all nodes.
This uses too much memory for nothing.
Backport: #5663
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1856981
(cherry picked from commit f0fe193d8ec48414447aa4a7d50b1a9859c71295)
=> facts: refact and optimize memory consumption (bp #5663)

library/ceph_dashboard_user.py, roles/ceph-dashboard/tasks/configure_dashboard.yml, tests/library/test_ceph_dashboard_user.py
This adds the ceph_dashboard_user ansible module for replacing the
command module usage with the ceph dashboard ac-user-xxx command.
=> library: add ceph_dashboard_user module

library/ceph_pool.py, roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-iscsi-gw/tasks/common.yml, roles/ceph-mds/tasks/create_mds_filesystems.yml, roles/ceph-osd/tasks/openstack_config.yml
Most ansible module using a state parameter default to the present
value (when available) instead of using it as a mandatory option.
=> [skip ci] ceph_pool: set state as optional

dashboard.yml, roles/ceph-prometheus/templates/prometheus.yml.j2
We don't need to install node-exporter on client node because there's
no ceph services running on them.
This also makes sure we use the group name variables in the prometheus
service template instead of hardcoding the values.
=> [skip ci] node-exporter: exclude client nodes

roles/ceph-dashboard/tasks/configure_dashboard.yml
Instead of using run_once: true on each tasks in a block section, we
can use the run_once statement at the block level.
=> dashboard: use run_once at block level

tests/library/test_ceph_dashboard_user.py
Rename the test class with the right information.
=> [skip ci] tests/library: rename ceph_dashboard_user class

infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/purge-container-cluster.yml
This commit ensure we remove any socket left by ceph and the
`ceph-osd-run.sh` script.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1861755
=> [skip ci] purge: remove potential socket leftover

ceph-ansible.spec.in, requirements.txt, roles/ceph-validate/tasks/check_system.yml, tests/requirements.txt
Prior this commit we were supporting both ansible 2.8 and 2.9.
Let's drop 2.8 now.
Closes: #5459
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1879178
=> ansible: bump to ansible 2.9

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The `switch-from-non-containerized-to-containerized-ceph-daemons.yml` playbook is currently only used for switching from a RPM based deployment to containerized deployment.
When using a DEB based system then there's some differences in the packaging (systemd unit path) and other thing to fix.
=> [skip ci] switch2container: fixes for running containers on Debian based host

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-container-common/tasks/fetch_image.yml, roles/ceph-container-common/tasks/registry.yml, roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml, roles/ceph-container-engine/templates/docker-proxy.conf.j2, roles/ceph-defaults/defaults/main.yml
When using a http(s) proxy with either docker or podman we can rely on
the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables.
But with ansible, even if those variables are defined in a source file
then they aren't loaded during the container pull/login tasks.
This implements the http(s) proxy support with docker/podman.
Both implementations are different:
1/ docker doesn't rely en the environment variables with the CLI.
Thos are needed by the docker daemon via systemd.
2/ podman uses the environment variables so we need to add them to
the login/pull tasks.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1876692
=> container: add optional http(s) proxy option

roles/ceph-prometheus/files/ceph_dashboard.yml
Since [1] The bytes_used pool counter in prometheus has been renamed
to stored.
Closes: #5781
[1] https://github.com/ceph/ceph/commit/71fe9149
=> [skip ci] ceph-prometheus: update pool stat counter

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-container-common/tasks/fetch_image.yml, roles/ceph-container-common/tasks/registry.yml, roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml, roles/ceph-container-engine/templates/docker-proxy.conf.j2, roles/ceph-defaults/defaults/main.yml
When using a http(s) proxy with either docker or podman we can rely on
the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
But with ansible, even if those variables are defined in a source file
then they aren't loaded during the container pull/login tasks.
This implements the http(s) proxy support with docker/podman.
Both implementations are different:
1/ docker doesn't rely en the environment variables with the CLI.
Thos are needed by the docker daemon via systemd.
2/ podman uses the environment variables so we need to add them to
the login/pull tasks.
Backport: #5786
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1876692
(cherry picked from commit bda3581294c8f29eda598522c331a4c009243884)
=> container: add optional http(s) proxy option (bp #5786)

roles/ceph-infra/templates/logrotate.conf.j2, roles/ceph-iscsi-gw/tasks/containerized.yml, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
This commit adds the log rotation support for tcmu-runner.
ceph-container related PR: ceph/ceph-container#1726
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1873915
=> [skip ci] infra: support log rotation for tcmu-runner

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The switch-from-non-containerized-to-containerized-ceph-daemons.yml playbook is currently only used for switching from a RPM based deployment to containerized deployment.
When using a DEB based system then there's some differences in the packaging (systemd unit path) and other thing to fix.
Backport: #5785
=> switch2container: fixes for running containers on Debian based host (bp #5785)

tests/functional/all_daemons/container/hosts, tests/functional/all_daemons/container/vagrant_variables.yml
Looks like nfs-ganesha 3.3 and 4.-dev doesn't work with recent changes
in librgw 16.0.0.
The nfs-ganesha daemon is segfaulting and restart in a loop.
See https://tracker.ceph.com/issues/47520
=> tests: disable container nfs testing

roles/ceph-facts/tasks/set_radosgw_address.yml
the current condition doesn't work, as soon as the first iteration is
done the condition makes next iterations skip since `rgw_instances` got
set with the first iteration.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1859872
=> [skip ci] facts: fix 'set_fact rgw_instances with rgw multisite'

roles/ceph-container-common/tasks/registry.yml
When using a quote in the registry password then we have the following
error:
The error was: ValueError: No closing quotation
To fix this we need to use the quote filter.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1880252
=> [skip ci] container: quote registry password

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/facts.yml
There's no need to set this fact with a `set_fact`
We can achieve this in `ceph-defaults`
Backport: #5526
(cherry picked from commit bcc673f66c22364766beb4b5ebb971bd3f517693)
=> facts: refact `ceph_uid` fact (bp #5526)

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/facts.yml
There's no need to set this fact with a set_fact
We can achieve this in ceph-defaults
Backport: #4948
Backport: #5526
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1875058
Signed-off-by: Guillaume Abrioux gabrioux@redhat.com
(cherry picked from commit bcc673f)
=> facts: refact `ceph_uid` fact (bp #4948,#5526)

roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
libjemalloc1 package is not required neither for ganesha dependency nor
for the package build process. So this task can be simply dropped.
Signed-Off-By: Dmitriy Rabotyagov <noonedeadpunk@ya.ru>
=> [skip ci] Remove libjemalloc1 installation task

library/ceph_key.py
We don't need to show this information during the module execution.
=> [skip ci] library/ceph_key: set no_log on secret

ansible.cfg, infrastructure-playbooks/ansible.cfg
As of 2.10, group names containing a dash are invalid.
However, setting this option makes it still possible to use a dash in
group names and prevent this warning to show up.
It might need to be definitely addressed in a future ansible release.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1880476
=> ansible.cfg: set force_valid_group_names param

roles/ceph-config/templates/ceph.conf.j2
We don't use ceph_release variable in the ceph.conf jinja template.
=> [skip ci] ceph-config: remove ceph_release from ceph.conf.j2

infrastructure-playbooks/rolling_update.yml, roles/ceph-config/templates/ceph.conf.j2
In Pacific we're are sure that users already achieved the msgr2 because
that was introduced in Nautilus.
=> rolling_update: remove msgr2 migration

library/ceph_pool.py
When using the "absent" state on a non existing pool then the ceph_pool
module will fail and return a python traceback.
Instead we should check if the pool exit or not and execute the pool
deletion according to the result.
The state changed is now set when the pool is actually deleted.
This also disable add_file_common_args because we don't manipulate
files with this module.
=> [skip ci] ceph_pool: add idempotency to absent state

roles/ceph-rgw/tasks/rgw_create_pools.yml
Since the state is now optional and default values are handled in the
ceph_pool module itself.
=> [skip ci] ceph-rgw: remove ceph_pool state and default value

README-MULTISITE.md
Some parts of [README-MULTISITE.md](README-MULTISITE.md) didn't render properly, and [markdownlint](https://github.com/DavidAnson/markdownlint) (which is used by [GitHub's Super Linter](https://github.com/marketplace/actions/super-linter)) reported a bunch of syntax and style issues.
These commits fix those issues.
=> [skip ci] README-MULTISITE: Fix syntax issues reported by markdownlint

library/ceph_crush.py, library/ceph_key.py, library/ceph_pool.py, library/ceph_volume.py
Running the `ceph_crush.py`, `ceph_key.py` or `ceph_volume.py` modules in check
mode resulted in the following error:
```
New-style module did not handle its own exit
```
This was due to the fact that they simply returned a `dict` in that case,
instead of calling `module.exit_json()`.
=> library: Fix new-style modules check mode

roles/ceph-facts/tasks/facts.yml
This commit adds support for ansible to resolve using linux device alias names.
Signed-off-by: Tyler Bishop <tbishop@liquidweb.com>
=> facts: support device aliases for (dedicated|bluestore_wal)_devices

roles/ceph-mds/tasks/create_mds_filesystems.yml
Since af9f6684 the cephfs pool(s) creation don't use the fs_pools_created
variable anymore because the ceph_pool module is idempotent.
=> ceph-mds: remove unused block condition

roles/ceph-facts/tasks/facts.yml
delegate to its own host after checking mon socket to findout if mon socket is in-use or not.
=> ceph-facts: check for mon socket in its own host

roles/ceph-iscsi-gw/tasks/common.yml
af9f6684 introduced a regression on the ceph iscsi pool creation
because it was delegated to the first monitor node before that change.
This patch restores the initial worflow.
When the iscsi node doesn't have the admin keyring then the pool
creation fails.
This commit also ensures that the pool creation is only executed once
when having multiple iscsi nodes.
=> ceph-iscsi: create pool once from monitor

roles/ceph-handler/tasks/main.yml, roles/ceph-mon/tasks/main.yml
In non containerized deployment we check if the service is running
via the socket file presence.
This is done via the xxx_socket_stat variable that check the file
socket in the /var/run/ceph/ directory.
In some scenarios, we could have the socket file still present in
that directory but not used by any process.
That's why we have the xxx_stat variable which clean those leftovers.
The problem here is that we're set the variable for the handlers status
(like handler_mon_status) based on xxx_socket_stat instead of xxx_stat.
That means we will trigger the handlers if there's an old socket file
present on the system without any process associated.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1866834
=> ceph-handler: set handler on xxx_stat result

Vagrantfile, group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-osd/tasks/start_osds.yml, tests/functional/all-in-one/container/group_vars/all, tests/functional/all-in-one/group_vars/all, tests/functional/all_daemons/container/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all, tests/functional/docker2podman/group_vars/all, tests/functional/external_clients/container/inventory/group_vars/all, tests/functional/external_clients/inventory/group_vars/all, tests/functional/podman/group_vars/all, tests/functional/shrink_mds/container/group_vars/all, tests/functional/shrink_mgr/container/group_vars/all, tests/functional/shrink_mon/container/group_vars/all, tests/functional/shrink_osd/container/group_vars/all, tests/functional/shrink_rbdmirror/container/group_vars/all, tests/functional/shrink_rgw/container/group_vars/all
The `enable extras on centos` task just doesn't work when using the
variable ceph_docker_enable_centos_extra_repo to true.
fatal: [xxx]; FAILED! => {"changed": false, "msg": "Parameter
'baseurl', 'metalink' or 'mirrorlist' is required."}
The CentOS extras repository is enabled by default so it's pretty
safe to remove this task and the associated variable.
This also removes the ceph_docker_on_openstack variable as it's a
leftover and it is unused.
=> Remove unused centos docker tasks

roles/ceph-rgw/tasks/multisite/secondary.yml
Add a check that ensures a connection to the
endpoint the realm is being pulled from.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1731158
=> rgw multisite: check connection for realm endpoint

roles/ceph-facts/tasks/facts.yml
In case of deploying new monitor node to an existing cluster, osd_pool_default_crush_rule should be taken from running monitor because ceph-osd role won't be run and the new monitor will have different osd_pool_default_crush_role from other monitors.
=> ceph-facts: add get default crush rule from running monitor

infrastructure-playbooks/filestore-to-bluestore.yml
This commit adds the `osd_auto_discovery` scenario support in the
filestore-to-bluestore playbook.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1881523
Co-authored-by: Dimitri Savineau <dsavinea@redhat.com>
=> fs2bs: support `osd_auto_discovery` scenario

roles/ceph-mds/tasks/create_mds_filesystems.yml
This commit add the pg autoscaler enablement support on ceph-ansible
rerun.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1836431
=> mds: support enabling pg autoscaler on rerun

tox-cephadm.ini, tox-docker2podman.ini, tox-podman.ini, tox-shrink_osd.ini, tox.ini
Since we use the rerun plugin in tox, we shouldn't need to add these
`sleep` commands.
=> tests: remove sleep commands from tox ini files

tests/functional/all_daemons/container/hosts, tests/functional/all_daemons/container/vagrant_variables.yml, tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml
This reverts commit 7348e9a253518904724b05565c97fa1f35c47006.
Since the nfs-ganesha rpm build for CentOS 8 has been fixed.
=> Revert "tests: disable nfs-ganesha testing"

.github/workflows/flake8.yml, tests/library/test_ceph_crush.py, tests/library/test_ceph_dashboard_user.py, tests/library/test_ceph_key.py, tests/library/test_ceph_volume.py
drop ricardochaves/python-lint action and use `run` steps instead.
=> [skip ci] tests: refact flake8 workflow

library/ceph_volume.py, tests/functional/collocation/hosts, tests/functional/dev_setup.yml, tox.ini
ceph-volume recently introduced a breaking change because of a `lvm
batch` refactor.
when rerunning `lvm batch --report --format json` on existing OSDs, it
doesn't output a valid json on stdout.
=> ceph-volume: dirty hack

roles/ceph-osd/tasks/start_osds.yml
This commit drops nested jinja construction in this set_fact task.
It also rename it to `container_exec_start_osd`
=> ceph-osd: refact `docker_exec_start_osd`

library/ceph_key.py, roles/ceph-handler/tasks/main.yml, roles/ceph-rgw/tasks/pre_requisite.yml, tests/functional/all_daemons/ceph-override.json, tests/library/test_ceph_key.py, tox.ini
When rgw and osd are collocated, the current workflow prevents from
scaling out the radosgw_num_instances parameter when rerunning the
playbook in baremetal deployments.
When ceph-osd notifies handlers, it means rgw handlers are triggered
too. The issue with this is that they are triggered before the role
ceph-rgw is run.
In the case a scaleout operation is expected on `radosgw_num_instances`
it causes an issue because keyrings haven't been created yet so the new
instances won't start.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1881313
=> rgw: fix multi instances scaleout in baremetal

roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-osd/tasks/main.yml, roles/ceph-validate/tasks/main.yml
It's time to remove this backward compatibility. Users had enough time
to convert their openstack_keys and key values.
We now fail in ceph-validate if the caps key isn't set.
=> ceph_key: remove backward compatibility

.github/workflows/flake8.yml, tests/conftest.py, tests/functional/tests/test_install.py
tests/conftest.py and tests present in tests/functional/tests/ has been
missed from previous commit
=> [skip ci] flake8: fix pep8 syntax on tests/functional/tests/

.github/workflows/flake8.yml
We don't need to run flake8 on ansible modules and their tests if we
don't have any modifitions.
=> [skip ci] flake8: run the workflow conditionally

infrastructure-playbooks/rolling_update.yml, library/ceph_fs.py, roles/ceph-mds/tasks/create_mds_filesystems.yml, tests/library/test_ceph_fs.py
This adds the ceph_fs ansible module for replacing the command module
usage with the ceph fs command.
=> library: add ceph_fs module

tests/functional/all_daemons/ceph-override.json
`all_daemons` scenario can't handle pools with `size: 3` because we have
1 osd node in root=HDD and two nodes in root=default.
=> tests: change cephfs pool size

roles/ceph-crash/tasks/main.yml, roles/ceph-mgr/tasks/common.yml, roles/ceph-mgr/tasks/mgr_modules.yml, roles/ceph-mon/tasks/ceph_keys.yml, roles/ceph-osd/tasks/common.yml, roles/ceph-osd/tasks/main.yml, roles/ceph-rgw/tasks/common.yml, site.yml.sample
Make sure the `site.yml.sample` playbook can be run in check mode by skipping
tasks that try to read the output of commands that have been skipped.
Requires #5717.
=> Fix Ansible check mode for site.yml.sample playbook

roles/ceph-osd/templates/ceph-osd-run.sh.j2
90f3f61 introduced the docker-to-podman.yml playbook but the
ceph-osd-run.sh.j2 template still has some docker hardcoded instead
of using the container_binary variable.
=> ceph-osd: add missing container_binary

roles/ceph-osd/templates/ceph-osd-run.sh.j2
This adds some missing param to the container cli calls in
ceph-osd-run.sh.j2
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1885558
=> osd: add missing param to the container cli calls

roles/ceph-handler/tasks/check_socket_non_container.yml, roles/ceph-handler/tasks/main.yml
the `stat --printf=%n` returns something like following:
```
ok: [osd0] => changed=false
cmd: |-
stat --printf=%n /var/run/ceph/ceph-osd*.asok
delta: '0:00:00.009388'
end: '2020-10-06 06:18:28.109500'
failed_when_result: false
rc: 0
start: '2020-10-06 06:18:28.100112'
stderr: ''
stderr_lines: <omitted>
stdout: /var/run/ceph/ceph-osd.2.asok/var/run/ceph/ceph-osd.5.asok
stdout_lines: <omitted>
```
it makes the next task "check if the ceph osd socket is in-use" grep
like this:
```
ok: [osd0] => changed=false
cmd:
- grep
- -q
- /var/run/ceph/ceph-osd.2.asok/var/run/ceph/ceph-osd.5.asok
- /proc/net/unix
```
which will obviously fail because this path never exists. It makes the
OSD handler broken.
Let's use `find` module instead.
=> handler: refact check_socket_non_container

roles/ceph-mon/tasks/docker/main.yml
when using `monitor_interface`, if nodes don't have same interface names
this task will fail like following:
```
fatal: [argo010]: FAILED! => {
"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute u'ansible_enp1s0f0'\n\nThe error appears to have been in '/usr/share/ceph-ansible/roles/ceph-mon/tasks/docker/main.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: ipv4 - force peer addition as potential bootstrap peer for cluster bringup - monitor_interface\n  ^ here\n"
}
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1876551
=> mon: fix force peer addition task

roles/ceph-osd/tasks/start_osds.yml
Using the + operation on two lists doesn't filter out the duplicate
keys.
Currently each OSDs is started (via systemd) twice.
Instead we could use the union filter.
=> ceph-osd: don't start the OSD services twice

roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml, roles/ceph-container-engine/vars/Debian.yml, roles/ceph-container-engine/vars/RedHat-8.yml, roles/ceph-container-engine/vars/RedHat.yml, roles/ceph-container-engine/vars/Ubuntu-16.yml, roles/ceph-container-engine/vars/Ubuntu-18.yml, roles/ceph-container-engine/vars/Ubuntu-20.yml
The container_binding_name package was only mandatory when we were
using the docker modules (docker_image and docker_container) but since
we manage both docker and podman containers without using the dedicated
module then we can remove it.
=> container: remove container_binding_name variable

roles/ceph-osd/tasks/start_osds.yml
The service should be started after the ceph-osd systemd overrides has
been added, otherwise, the latter isn't considered.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1860739
=> ceph-osd: start osd after systemd overrides

roles/ceph-crash/tasks/main.yml
The current task installs the ceph-crash key to "most" hosts via
"delegate_to". This key is only used by the ceph-crash daemon and should
just be installed on all hosts targeted by this role. There is no need
for using a delegated task.
=> ceph-crash: Only deploy key to targeted hosts

roles/ceph-mon/tasks/deploy_monitors.yml, roles/ceph-osd/tasks/start_osds.yml
Skip tasks that depend on the output of commands that are not being run in check mode.
=> Fix Ansible check mode in ceph-mon and ceph-osd

library/ceph_volume.py
When running rhel8 containers on a rhel7 host, after zapping an OSD
there's a discrepancy with the lvmetad cache that needs to be refreshed.
Otherwise, the host still sees the lv and can makes the user confused.
If user tries to redeploy an OSD, it will fail because the LV isn't
present and need to be recreated.
ie:
```
stderr: lsblk: ceph-block-8/block-8: not a block device
stderr: blkid: error: ceph-block-8/block-8: No such file or directory
stderr: Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
usage: ceph-volume lvm prepare [-h] --data DATA [--data-size DATA_SIZE]
[--data-slots DATA_SLOTS] [--filestore]
[--journal JOURNAL]
[--journal-size JOURNAL_SIZE] [--bluestore]
[--block.db BLOCK_DB]
[--block.db-size BLOCK_DB_SIZE]
[--block.db-slots BLOCK_DB_SLOTS] …
```
=> ceph-volume: refresh lvm metadata cache

roles/ceph-crash/tasks/main.yml
there is no need to use `{{ }}` syntax here.
=> crash: refact caps definition

docs/source/testing/tox.rst, group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/purge-container-cluster.yml, roles/ceph-config/tasks/main.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/facts.yml, roles/ceph-fetch-keys/tasks/main.yml, tox-docker2podman.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-shrink_osd.ini, tox-update.ini, tox.ini
This commit cleans up the `main.yml` task file of `ceph-config`.
It drops the local ceph.conf generation.
=> ceph-config: ceph.conf rendering refactor

roles/ceph-iscsi-gw/tasks/common.yml
This file is currently deployed with '0644' ownership making this file
readable by any user on the system.
Since it contains sensitive information it should be readable by the
owner only.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1890119
=> iscsi: fix ownership on iscsi-gateway.cfg

roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
When using the curl command with ipv6 address and brackets then we need
to use the -g option otherwise the command fails.
```console
$ curl http://[fdc2:328:750b:6983::6]:8080
curl: (3) [globbing] error: bad range specification after pos 9
```
=> ceph-handler: fix curl ipv6 command with rgw

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
Since we've changed to podman configuration using the detach mode and
systemd type to forking then the container logs aren't present in the
journald anymore.
The default conmon log driver is using k8s-file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1890439
=> podman: force log driver to journald

roles/ceph-osd/tasks/openstack_config.yml
This was lost with commit ab370b6ad823e551cfc324fd9c264633a34b72b5.
=> openstack: omit mode on key if not set on item

infrastructure-playbooks/cephadm-adopt.yml, library/ceph_key.py, roles/ceph-client/tasks/pre_requisite.yml, roles/ceph-crash/tasks/main.yml, roles/ceph-iscsi-gw/tasks/common.yml, roles/ceph-mds/tasks/common.yml, roles/ceph-mds/tasks/non_containerized.yml, roles/ceph-mgr/tasks/common.yml, roles/ceph-mon/tasks/deploy_monitors.yml, roles/ceph-nfs/tasks/pre_requisite_container.yml, roles/ceph-nfs/tasks/pre_requisite_non_container.yml, roles/ceph-osd/tasks/common.yml, roles/ceph-osd/tasks/openstack_config.yml, roles/ceph-rbd-mirror/tasks/common.yml, roles/ceph-rgw/tasks/common.yml, tests/library/test_ceph_key.py
Whenever it's possible, use the ceph_key module instead of
- `ceph auth get` commands
- `ceph auth get-or-create` commands
This requires to modify the ceph_key module to handle the output format when using the info state.
=> Use ceph_key module when possible

library/ceph_dashboard_user.py, library/ceph_fs.py, library/ceph_key.py, library/ceph_pool.py, library/ceph_volume.py, library/radosgw_realm.py, library/radosgw_user.py, library/radosgw_zone.py, library/radosgw_zonegroup.py
Move the import at the top of the file and remove unused module import.
- E402 module level import not at top of file
- F401 'xxxx' imported but unused
This also removes the `# noqa E402` statement from the code.
=> library: remove unused module import

roles/ceph-mon/tasks/deploy_monitors.yml
After rolling updates performed with
`infrastructure-playbooks/rolling_updates.yml`, files located in
`/var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}` had mode 0755 (including
the keyring), making them world-readable.
This commit separates the task that configured permissions recursively on
`/var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}` into two separate tasks:
1. Set the ownership and mode of the directory itself;
2. Recursively set ownership in the directory, but don't modify the mode.
=> ceph-mon: Don't set monitor directory mode recursively

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/shrink-mon.yml, infrastructure-playbooks/shrink-rbdmirror.yml, infrastructure-playbooks/shrink-rgw.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-facts/tasks/facts.yml, roles/ceph-handler/templates/restart_mon_daemon.sh.j2, roles/ceph-osd/tasks/main.yml
We're running the ceph status command multiple time but we only use few part of this output.
Instead we should use the closest ceph command to reduce the data returned in the output.
This means using:
- ceph osd stat
- ceph pg stat
- ceph quorum_status
- ceph service dump
- ceph health
=> Avoid running full ceph status command

infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/shrink-mds.yml
bd611a7 introduced the new ceph_fs module but missed some tasks in
rolling_update and shrink-mds playbooks.
=> infrastructure: consume ceph_fs module

infrastructure-playbooks/rolling_update.yml
cec994b introduced a regression when a mgr is collocated with a mon.
During the mon upgrade, the mgr service is masked to avoid to be
restarted on packages update.
Then the start mgr task is failing because the service is still masked.
Instead we should unmask it.
Fixes: #5983
=> rolling_update: fix mgr start with mon collocation

roles/ceph-config/tasks/main.yml
If some OSDs are to be created and others already exist the calculation
only counted the to be created OSDs. This changes the calculation to
take all OSDs into account.
=> osd: Fix number of OSD calculation

infrastructure-playbooks/rolling_update.yml
There's no need to use a condition on the ceph release for the
ceph-volume simple commands.
=> rolling_update: always run cv simple scan/activate

site-container.yml.sample, site.yml.sample
There are some use cases where there's a need to skip the execution
of the ceph-ansible client role even though the client section of the
inventory isn't empty.
This can happen in contexts where the services are colocated or when
a all-in-one deployment is performed.
The purpose of this change is adding a 'ceph_client' tag to avoid
altering the ceph-ansible execution flow but at the same time be able
to include or exclude a set of tasks using this tag.
=> Add ceph_client tag to execute or skip the playbook

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, tox.ini
When deploying the ceph OSD via the packages then the ceph-osd@.service
unit is configured as enabled-runtime.
This means that each ceph-osd service will inherit from that state.
The enabled-runtime systemd state doesn't survive after a reboot.
For non containerized deployment the OSD are still starting after a
reboot because there's the ceph-volume@.service and/or ceph-osd.target
units that are doing the job.
```console
$ systemctl list-unit-files|egrep '^ceph-(volume|osd)'|column -t
ceph-osd@.service     enabled-runtime
ceph-volume@.service  enabled
ceph-osd.target       enabled
```
When switching to containerized deployment we are stopping/disabling
ceph-osd@XX.servive, ceph-volume and ceph.target and then removing the
systemd unit files.
But the new systemd units for containerized …
=> [skip ci] switch2container: disable ceph-osd enabled-runtime

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-config/templates/ceph.conf.j2, roles/ceph-defaults/defaults/main.yml
The osd_memory_target variable was only used if it was higher than the
calculated value based on the number of OSDs. This is changed to always
use the value if it is set in the configuration. This allows this value
to be intentionally set lower so that it does not have to be changed
when more OSDs are added later.
=> config: Always use osd_memory_target if set

roles/ceph-facts/tasks/facts.yml
The `osd_pool_default_crush_rule` is set based on `crush_rule_variable`, which
is the output of a `grep` command.
However, two consecutive tasks can set that variable, and if the second task is
skipped, it still overwrites the `crush_rule_variable`, leading the
`osd_pool_default_crush_rule` to be set to `ceph_osd_pool_default_crush_rule`
instead of the output of the first task.
This commit ensures that the fact is set right after the `crush_rule_variable`
is assigned, before it can be overwritten.
Closes #5912
=> ceph-facts: Fix osd_pool_default_crush_rule fact

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
This is a workaround to avoid error like following:
```
Error: error creating container storage: the container name "ceph-mgr-magna022" is already in use by "4a5f674e113f837a0cc561dea5d2cd55d16ca159a647b7794ab06c4c276ef701"
```
that doesn't seem to be 100% reproducible but it shows up after a
reboot. The only workaround we came up with at the moment is to run
`podman rm --storage <container>` before starting it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1887716
=> container: force rm --storage on ExecStartPre

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
fa2bb3a only fix the symlink owner/group issue in the OSD play. If the
OSDs are collocated with other services like MONs and MGRs then the
chown command will fail.
```console
$ find /var/lib/ceph/osd/ceph-0 -not -user 167 -execdir chown 167:167 {} +
chown: cannot dereference './block': Permission denied
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1896448
=> [skip ci] switch2container: chown symlink in mon/mgr plays

roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2
This commit changes the bind mount option for the mount point
`/var/lib/ceph` in the systemd template for mon and mgr containers. This
is needed in case of collocating mon/mgr with osds using dmcrypt
scenario.
Once mon/mgr got converted to containers, the dmcrypt layer sub mount is
still seen in `/var/lib/ceph`. For some reason it makes the
corresponding devices busy so any other container can't open/close it.
As a result, it prevents osds from starting properly.
Since it only happens on the nodes converted before the OSD play, the idea is
to bind mount `/var/lib/ceph` on mon and mgr with the `rshared` option
so once the sub mount is unmounted, it is propagated inside the
container so it doesn't see that mount point.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1896392 …
=> containers: modify bindmount option

roles/ceph-facts/tasks/facts.yml
We don't need to use run_once on that task when having running monitors
otherwise the read task could be skip and the set task will fail.
```console
The conditional check 'crush_rule_variable.rc == 0' failed. The error
was: error while evaluating conditional (crush_rule_variable.rc == 0):
'dict object' has no attribute 'rc'
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1898856
=> ceph-facts: fix read osd pool default crush fact

roles/ceph-osd/tasks/start_osds.yml
This commit ensures that the `/var/lib/ceph/osd/{{ cluster }}-{{ osd_id }}` is
present before starting OSDs.
This is needed specificly when redeploying an OSD in case of OS upgrade
failure.
Since ceph data are still present on its devices then the node can be
redeployed, however those directories aren't present since they are
initially created by ceph-volume. We could recreate them manually but
for better user experience we can ask ceph-ansible to recreate them.
NOTE:
this only works for OSDs that were deployed with ceph-volume.
ceph-disk deployed OSDs would have to get those directories recreated manually.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1898486
=> osd: ensure /var/lib/ceph/osd/{cluster}-{id} is present

roles/ceph-iscsi-gw/templates/iscsi-gateway.cfg.j2
When using a custom pool for iSCSI gateway then we need to set the pool
name in the configuration otherwise the default rbd pool name will be
used.
=> ceph-iscsi: set the pool name in the config file

infrastructure-playbooks/add-mon.yml, library/ceph_key.py, roles/ceph-mon/tasks/deploy_monitors.yml, tests/library/test_ceph_key.py
adding monitor is no longer possible because we generate a new mon
keyring each time the playbook is run.
Fixes: #5864
=> mon: refact initial keyring generation

infrastructure-playbooks/filestore-to-bluestore.yml, infrastructure-playbooks/rolling_update.yml, library/ceph_volume_simple_activate.py, library/ceph_volume_simple_scan.py, tests/library/test_ceph_volume_simple_activate.py, tests/library/test_ceph_volume_simple_scan.py
This adds ceph_volume_simple_{activate,scan} ansible modules for replacing
the command module usage with the ceph-volume simple activate/scan commands.
=> library: add ceph_volume_simple_{activate,scan}

library/ceph_volume.py
Since the action values are already defined as a list of choices in
ansible then we will never enter into this condition.
=> library: remove useless condition in ceph_volume

group_vars/rhcs.yml.sample, rhcs_edits.txt
Starting RHCS 5, only containerized deployment is available.
=> [skip ci] rhcs: default to containerized deployment

library/ceph_volume_simple_activate.py, library/ceph_volume_simple_scan.py, tests/library/test_ceph_volume_simple_activate.py, tests/library/test_ceph_volume_simple_scan.py
pr #6054 got merged but could have been updated to use `ca_common` for
`exit_module()` ...
=> library: use exit_module from ca_common

library/ceph_dashboard_user.py, library/ceph_ec_profile.py, library/ceph_fs.py, library/ceph_pool.py, module_utils/ca_common.py, tests/library/test_ca_common.py
module_utils: refactor
- update `generate_ceph_cmd()` so `user_key` is automatically built from
`cluster` and `user` params.
- update and add testing.
=> module_utils: refact generate_ceph_cmd

roles/ceph-prometheus/tasks/main.yml
Set the owner/group on alertmanager and prometheus directories and
files to nobody and nogroup (uid and gid 65534) to avoid permission
issues.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1901543
=> alertmanager/prometheus: fix owner/group

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
`ceph.target` should be disabled only. Otherwise, in collocation
scenario you stop other collocated services in the OSD play which isn't
what we want to do. Each daemon has its corresponding play for managing
the transition to container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1901865
=> switch2containers: do not stop ceph.target in osd play

.github/workflows/flake8.yml, .github/workflows/pytest.yml, plugins/filter/ipaddrs_in_ranges.py, tests/plugins/filter/test_ipaddrs_in_ranges.py
- The plugins/filter directory wasn't present in the flake8 workflow
configuration.
- Fix the flake8 syntax.
- Add the directory to PYTHONPATH environment variable for pytest
to avoid importing the plugin filter via sys.
- Add unittest on missing netaddr module import.
=> [skip ci] improve plugins/filter testing

infrastructure-playbooks/cephadm-adopt.yml, library/ceph_mgr_module.py, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-mgr/tasks/mgr_modules.yml, tests/library/test_ceph_mgr_module.py
This adds ceph_mgr_module ansible module for replacing the command module
usage with the ceph mgr module enable/disable commands.
=> library: add ceph_mgr_module module

infrastructure-playbooks/filestore-to-bluestore.yml, infrastructure-playbooks/shrink-osd.yml, library/ceph_osd.py, tests/library/test_ceph_osd.py
This adds ceph_osd ansible module for replacing the command module
usage with the ceph osd destroy/down/in/out/purge/rm commands.
=> library: add ceph_osd module

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
As of podman `2.0.5`, `--cap-add` and `--privileged` are exclusive
options.
```
Nov 30 13:56:30 magna089 podman[171677]: Error: invalid config provided: CapAdd and privileged are mutually exclusive options
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1902149
=> iscsigw: remove `--cap-add=all` from `podman run` cmd

infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, library/ceph_osd_flag.py, roles/ceph-handler/tasks/handler_osds.yml, roles/ceph-osd/tasks/main.yml, tests/library/test_ceph_osd_flag.py
This adds ceph_osd_flag ansible module for replacing the command module
usage with the ceph osd set/unset commands.
=> library: add ceph_osd_flag module

infrastructure-playbooks/cephadm.yml, library/cephadm_bootstrap.py, tests/functional/cephadm/group_vars/all, tests/library/test_cephadm_bootstrap.py
This adds cephadm_bootstrap ansible module for replacing the command module
usage with the cephadm bootstrap command.
=> library: add cephadm_bootstrap module

roles/ceph-client/tasks/create_users_keys.yml
Instead of iterate over all client nodes with a loop sequentially, we
can use the group_by ansible buildin.
=> ceph-client: use group_by instead of add_host

roles/ceph-osd/tasks/main.yml
This allows skipping this task if really desired.
Use it carefully. Use it at your own risk.
Fixes: #6073
=> [skip ci] osd: add tag on 'wait for all osd to be up' task

library/ceph_crush_rule.py, roles/ceph-facts/tasks/get_def_crush_rule_name.yml, roles/ceph-osd/tasks/crush_rules.yml, roles/ceph-rgw/tasks/rgw_create_pools.yml, tests/library/test_ceph_crush_rule.py
This adds ceph_crush_rule ansible module for replacing the command
module usage with the ceph osd crush rule commands.
This module can manage both erasure and replicated crush rules.
=> library: add ceph_crush_rule module

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/filestore-to-bluestore.yml, infrastructure-playbooks/shrink-osd.yml, roles/ceph-osd/tasks/start_osds.yml
We should always use the ceph_volume ansible module when possible.
This patch replace the ceph-volume inventory and lvm {list,zap} commands
called via the command/shell modules by the corresponding call with the
ceph_volume module.
=> consume ceph_volume module when possible

infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/rolling_update.yml, roles/ceph-osd/tasks/start_osds.yml
Let's discard the ansible lint error 306 and add a "# noqa 306" on tasks
where we don't need `set -o pipefail`
Fixes: #6090
=> common: do not use pipefail when not needed

infrastructure-playbooks/cephadm-adopt.yml, library/cephadm_adopt.py, tests/library/test_cephadm_adopt.py
This adds cephadm_adopt ansible module for replacing the command module
usage with the cephadm adopt command.
=> [skip ci] library: add cephadm_adopt module

roles/ceph-mon/tasks/deploy_monitors.yml
Since the backing generate_secret() just hands out urandom output,
running as privileged doesn't seem to be required. It's not
desireable to provide sudo in some Ansible runner environments.
=> ceph-mon: No become during gen mon initial keyring

rhcs_edits.txt
Since the fetch_directory variable has been dropped then we don't need
the override in rhcs file.
=> [skip ci] rhcs: drop fetch_directory override

infrastructure-playbooks/purge-container-cluster.yml, tests/scripts/vagrant_up.sh
This updates the CentOS libvirt box version to 8.3
=> tests/vagrant: update box version to CentOS 8.3

tests/functional/setup.yml
Since [1] has been resolved then we don't need to apply this workaround
anymore.
[1] https://tracker.ceph.com/issues/46759
=> [skip ci] tests: remove pyyaml workaround on OSD nodes

roles/ceph-facts/tasks/convert_grafana_server_group_name.yml, roles/ceph-facts/tasks/main.yml
The conversion fact task was only executed when the grafana_server_group_name
variable was explicitly set in the user configuration. If an user was using
the default value then the conversion wasn't executed.
This also adds back the default `grafana_server_group_name` value in case user
was using the default value and to avoid undefined variable error.
Instead of hardcoding the "monitoring" group name then we can reuse the
monitoring_group_name variable.
There's no need to override the `monitoring_group_name` variable, it's either
using the default value or the one defined by the user.
Finally removing the delegate_to statement on the add_host task since it's
always executed on the ansible controller.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1903732
Signed-off-by: Dimitri …
=> ceph-facts: fix grafana group conversion

roles/ceph-rgw/tasks/rgw_create_pools.yml
81233dd introduced a regression with the `ceph_ec_profile` module call in
the ceph-rgw role due the missing cluster module parameter.
=> ceph-rgw: add cluster parameter on ceph_ec_profile

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-grafana/tasks/configure_grafana.yml, roles/ceph-prometheus/tasks/main.yml
The alertmanager, grafana and prometheus configuration file are
generated with the template module which doesn't allow for using
config overrides.
Instead we could use the config_template plugin action and add a
new variable for overrides (one for each component).
With this patch, one should be able to add configuration to
prometheus with the following:
```yaml
---
alertmanager_conf_overrides:
global:
smtp_smarthost: 'localhost:25'
...
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1902999
=> monitoring: use config_template module for config

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-config/templates/ceph.conf.j2, roles/ceph-defaults/defaults/main.yml
This reverts commit 4d1fdd2b05d55f8028fb5593d41fa61dbddd7095.
This breaks the backward compatibility with previous osd_memory_target
calculation and we could have a value lower than the minimum value allowed
(896M) which causes some ceph commands to fail (like ceph assimilate-conf).
=> [skip ci] Revert "config: Always use osd_memory_target if set"

roles/ceph-osd/tasks/scenarios/lvm.yml
Use global `crush_device_class` variable if it's not set per OSD
=> ceph-osd: use global crush_device_class in lvm_volumes

tests/functional/rgw_multisite.yml, tests/scripts/vagrant_up.sh
Currently we create an object from the primary sites but we try to read
that object still from the master which doesn't make sense, we should
try to read it from a secondary site.
=> tests: rgw_multisite playbook test refactor

.mergify.yml
So we get backports against 4.2z1 branch (downstream related) automatically
created by mergify
=> [skip ci] mergify: add configuration for 4.2z1 branch

roles/ceph-config/tasks/main.yml
Since the major ceph-volume lvm batch refactoring, the report value
is different.
Before the refact, the report was a dict with the OSDs list to be created
under the "osds" key.
After the refact, the report is a list of dict.
=> ceph-config: fix ceph-volume lvm batch report

library/ceph_pool.py, roles/ceph-rgw/tasks/rgw_create_pools.yml, tests/library/test_ceph_pool.py
When creating a new pool, target_size_ratio is ignored by ansible module ceph_pool.py.
It's neither used in role ceph-rgw.
This PR fixes this 2 issues.
Signed-off-by: Fabien Brachere <fabien.brachere@celeste.fr>
=> library: add missing `target_size_ratio` parameter support in ceph_pool module

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml
Instead of iterate over the host list for adding the node/label to the
host orchestrator configuration then we can do it parallelly.
=> [skip ci] cephadm: remove loop on host add tasks

library/ceph_volume.py
The ceph-volume module relies on environment variables to determine if
the command should be executed within a container or not.
The containerized parameter isn't used anymore and we can remove it.
Fixes: #6153
=> [skip ci] library: remove containerized parameter from cv

roles/ceph-handler/tasks/main.yml, roles/ceph-rgw/tasks/multisite.yml
When collocating rgw with either a mon, mgr or osd, switching from
single site to a multisite rgw setup failed because of the handlers
triggered between the ansible play of the collocated daemon and the play
of the rgw. Since the multisite changes are not yet applied the handlers
fail.
The idea here is to ensure we run the multisite configuration from the
ceph-handler role before the restart happens, this way it won't complain
because of non existing multisite configuration.
(Note: this is also valid when simply changing a multisite configuration)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1888630
=> [skip ci] rgw: support switching from single-site to multisite

roles/ceph-crash/templates/ceph-crash.service.j2
The path where ceph.conf is located (/etc/ceph) missing in the Docker container bind mounts, this throws errors
=> [skip ci] Path for ceph config missing in crash template

ceph-ansible.spec.in
Since d7fd468 the ansible modules are using the common code shared in
the module_utils directory but that one wasn't added to the spec file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1910214
=> [skip ci] spec: add module_utils directory

library/ceph_dashboard_user.py, module_utils/ca_common.py, roles/ceph-dashboard/tasks/configure_dashboard.yml, tests/functional/all_daemons/group_vars/nfss, tests/library/test_ceph_dashboard_user.py
refact this module due to recent changes in ceph pacific.
The password must be passed with `-i` option.
=> library: refact ceph_dashboard_user

roles/ceph-osd/tasks/system_tuning.yml
Instead of using the command module for retrieving a sysctl value then
we can use the slurp module and read the value directly from /proc.
=> ceph-osd: replace sysctl command task by slurp

tests/functional/all_daemons/group_vars/nfss
This reverts commit ed9f0641eee3da314a66f5ed7c2722ac973481d3.
=> Revert "tests: temporarily use david's flavor"

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The current check makes no sense because it checks any of other monitor
than the one being played (either a previous one already converted or a
next that isn't yet converted) is present on the quorum.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1909011
=> [skip ci] switch2container: fix mon quorum check

roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml, roles/ceph-rgw-loadbalancer/templates/keepalived.conf.j2, roles/ceph-validate/tasks/main.yml
While 2ca33641 fixed a bug in the way the `keepalived.conf.j2` template matched
hostnames to set the VRRP `MASTER`/`BACKUP` states, it also introduced a
regression in the case where `virtual_ips` is a list of more than one IP
address.
The previous behavior would result in each host in the `rgwloadbalancers` group
to be `MASTER` for one of the `virtual_ips`, but the new behavior caused the
first host to be `MASTER` for all the IP address in `virtual_ips`.
This commit restores the original behavior.
=> ceph-rgw-loadbalancer: Fix keepalived master selection

infrastructure-playbooks/filestore-to-bluestore.yml
Since the default of `osd_objectstore` has changed as of 3.2, some
deployments might have a mix of filestore and bluestore OSDs on a same
node. In some specific cases, there's a possibility that a filestore OSD
shares a journal/db device with a bluestore OSD. We shouldn't try to
redeploy in this context because ceph-volume will complain. (either
because in lvm batch you can't pass partition or about gpt header).
The safest option is to skip the migration on the node when such a mix
is detected or force all osds including those already using bluestore
(option `force_filestore_to_bluestore=True` has to be passed as an extra var).
If all OSDs are using filestore, then they will be migrated to
bluestore.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1875777
Signed-off-by: Guillaume …
=> [skip ci] fs2bs: skip migration when a mix of fs and bs is detected

tests/library/test_ceph_dashboard_user.py
Remove duplicate fake_params parameter as it's already defined later
as a dict (instead of an empty list).
=> [skip ci] tests/library: remove duplicate parameter

module_utils/ca_common.py, tests/module_utils/test_ca_common.py
When executing a command via the run_command method and passing some
data with stdin then the default behavior is to add append a newline.
This breaks the value of password used by our modules.
=> module_utils: don't add newline to the data

roles/ceph-mon/tasks/deploy_monitors.yml
Due to missing condition on `cephx` variable, cephx disabled deployments
are broken.
This commit fixes this.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1910151
=> mon: fix cephx disabled deployment

library/ceph_dashboard_user.py, roles/ceph-dashboard/tasks/configure_dashboard.yml, tests/library/test_ceph_dashboard_user.py
Due to recent changes in ceph, the few dashboard passwors must be passed via `-i` either in the `ceph_dashboard_module` or in the `command` task.
This also adds backward compatibility for older ceph release manage by recent ceph-ansible version.
=> (stable-5.0) dashboard: configure passwords via stdin

infrastructure-playbooks/cephadm-adopt.yml
The grafana group conversion task wasn't present in the cephadm-adopt.yml
playbook.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1917530
=> cephadm-adopt: add grafana group conversion

group_vars/all.yml.sample, roles/ceph-defaults/defaults/main.yml
The "latest" ceph container tag references the latest stable release
(octopus at the moment). "latest" is an alias on "latest-octopus".
On the devel branch we should use "latest-master" tag instead.
=> ceph-defaults: change default ceph container tag

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, rhcs_edits.txt, roles/ceph-defaults/defaults/main.yml, tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all, tests/functional/docker2podman/group_vars/all, tests/functional/podman/group_vars/all
This update the grafana container tag to 6.7.4.
The RHCS version is now based on the RHCS 5 container image which is
also based on 6.7.4.
=> grafana: update container tag to 6.7.4

roles/ceph-handler/tasks/main.yml, roles/ceph-rgw/tasks/main.yml
since `ceph-rgw` may be called from `ceph-handler` in some contexts we
should avoid rerunning it unnecessarily.
=> rgw: avoid useless call to ceph-rgw

roles/ceph-mon/templates/ceph-mon.service.j2
We already do that in the other systemd templates (mgr, mds, etc..)
and would present to add workaround in other orchestration tool.
This change is for containerized deployment only.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1882724
=> ceph-mon: add ExecStartPre docker stop to systemd

infrastructure-playbooks/cephadm-adopt.yml, library/cephadm_adopt.py, library/radosgw_zone.py, library/radosgw_zonegroup.py, tests/library/test_cephadm_adopt.py, tests/library/test_radosgw_zone.py, tests/library/test_radosgw_zonegroup.py, tox.ini
- remove the container exec because the old containers won't exist anymore
- add idempotency to the cephadm_adopt module because the cephadm adopt command doesn't support it.
- test idempotency in the CI
- use radosgw modules for idempotency purpose
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1918424
=> make the cephadm-adopt.yml playbook idempotent

roles/ceph-facts/tasks/set_radosgw_address.yml
There's no need to set the rgw_instances_all fact for each node. We can
rely on run_once for that one.
=> ceph-facts: set rgw_instances_all fact once

roles/ceph-rgw/tasks/multisite/create_zone_user.yml
typical error:
```
2021-02-01 03:11:09,809 p=93834 u=cephuser n=ansible | TASK [ceph-rgw : check if the realm system user already exists] ***************************************************************************************************************************************************
2021-02-01 03:11:09,809 p=93834 u=cephuser n=ansible | Monday 01 February 2021  03:11:09 -0500 (0:00:00.084)       0:14:38.607 *******
2021-02-01 03:11:09,836 p=93834 u=cephuser n=ansible | fatal: [ceph-kvm-ms2-1611241931591-node7-rgw]: FAILED! =>
msg: |-
The task includes an option with an undefined variable. The error was: 'None' has no attribute 'realm'
```
This task should be skipped when `zone_users` is undefined.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1922998
Signed-off-by: Guillaume …
=> rgw: quick fix in create_zone_user.yml

infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/purge-container-cluster.yml
Those devices (db/wal) are never zapped in lvm batch deployment.
Iterating over `dedicated_devices` and `bluestore_wal_devices` fixes
this issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1922926
=> [skip ci] purge: zap and destroy db and wal devices for lvm batch

roles/ceph-osd/tasks/start_osds.yml, roles/ceph-osd/templates/ceph-osd-run.sh.j2
The task in charge of activating new osd is skipped because
`devices` is populated with the devices being added only.
It means it doesn't enter the condition since the length of `devices` is less
than the number of activated osds.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1906293
=> osd: support adding osd in auto discovery scenario

roles/ceph-osd/tasks/start_osds.yml
This commit adds the missing `--ulimit nofile=1024:4096` on this task.
=> [skip ci] osd: add missing '--ulimit' flag

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
There's no reason to still use http on download.ceph.com instead of
https.
=> ceph-defaults: use https for download.ceph.com

infrastructure-playbooks/purge-cluster.yml
Instead of doing some scripting via the shell module, we can use the
parted ansible module to check the boot flag on partitions.
=> purge-cluster: use parted ansible module

infrastructure-playbooks/cephadm-adopt.yml
There's no reason to not use the ceph_osd_flag module to set/unset osd
flags.
Also if there's no OSD nodes in the inventory then we don't need to
execute the set/unset play.
=> cephadm-adopt: use ceph_osd_flag module

library/ceph_mgr_module.py, tests/library/test_ceph_mgr_module.py
The ceph mgr command output is printed on stderr instead of stdout which
prevent to set the changed flag to false if the module is already enabled.
=> [skip ci] library: fix idempotency in ceph_mgr_module

tests/scripts/vagrant_up.sh
The CentOS 8 vagrant box has finally been updated [1] with a recent
version (the latest one 2011 which means CentOS 8.3).
We don't need to download the vagrant libvirt box with a direct url
anymore from the CentOS infrastructure.
[1] https://app.vagrantup.com/centos/boxes/8
=> vagrant: remove centos/8 workaround

dashboard.yml
Since eefe11d the grafana-server group has been renamed to monitoring
but the dashboard playbook wasn't updated.
This was still working due to the backward compatibility added in the
ceph-facts role.
=> dashboard: update with the new monitoring group

docs/source/index.rst
This updates the ansible release required to deploy nautilus with the
stable-4.0 branch.
=> docs: nautilus uses ansible 2.9

infrastructure-playbooks/rolling_update.yml
Since b105549 we don't install node-exporter on client nodes so we should
also exclude the client node from the node-exporter upgrade.
=> rolling_update: exclude clients from node-exporter

roles/ceph-rgw/tasks/multisite/main.yml, tests/functional/rgw-multisite/container/group_vars/all, tests/functional/rgw-multisite/container/secondary/group_vars/all, tests/functional/rgw-multisite/group_vars/all, tests/functional/rgw-multisite/secondary/group_vars/all
if `rgw_zonegroupmaster` is not defined at the rgw instance level in
`rgw_instances` it will fallback to a wrong variable (`rgw_zonemaster`).
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1925247
=> [skip ci] rgw: fix a typo in multisite

.github/workflows/ansible-lint.yml
This commit pins the ansible-lint version to 4.3.7 as ceph-ansible isn't
compatible with recent changes in 5.0.0
=> [skip ci] tests: pin ansible-lint version

infrastructure-playbooks/rolling_update.yml, roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
- enable rhcs tools repository on the monitoring node with non containerized deployment for the ceph-grafana-dashboards package.
- enforce ceph-container-engine installation during rolling_update execution to avoid having node without podman/docker installed and failing on the registry authentication.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1903504
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1918650
=> [skip ci] monitoring: add missing repository and requirements

infrastructure-playbooks/cephadm-adopt.yml
This was fixed by [1][2]
[1] https://tracker.ceph.com/issues/45120
[2] https://github.com/ceph/ceph/commit/252d4b30
=> cephadm-adopt: remove prometheus workaround

.mergify.yml
This adds the stable-6.0 backport configuration in mergify.
=> [skip ci] mergify: add stable-6.0 backport configuration

tests/functional/all-in-one/container/group_vars/all, tests/functional/all-in-one/group_vars/all, tests/functional/all_daemons/ceph-override.json, tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all
we aren't deploying enough OSD daemon, so it fails like following:
```
stderr: 'Error ERANGE: pool id 10 pg_num 256 size 2 would mean 1536 total pgs, which exceeds max 1500 (mon_max_pg_per_osd 250 * num_in_osds 6)'
```
Let's increase the value of `mon_max_pg_per_osd` in order to get around
this issue in the CI.
=> tests: increase `mon_max_pg_per_osd`

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
There's no need to slow down the playbook execution time by migrating
all the `ceph-crash` instances in a serial way. Let's remove the
`serial: 1` so the migration is achieved in a parallel way.
=> [skip ci] switch2container: do not serialize the ceph-crash migration

tests/functional/all_daemons/group_vars/nfss
This is the latest stable release available for octopus.
Let's use it instead of using master builds.
=> tests: use V3.3-stable branch for nfs-ganesha

infrastructure-playbooks/purge-container-cluster.yml
Since those files aren't removed by systemd and podman, purge playbooks
should remove them so we don't leave an environment with leftover.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1920900
=> purge: rm service-cid files

library/ceph_volume.py
When asking `ceph-volume` to report only in `lvm batch` context, there's
a bug described in bz1896803 [1] when `--yes` is passed (which by the
way isn't necessary with `--report`).
This commit ensure `--yes` isn't passed to `ceph-volume` when `--report`
is used.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1896803
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1896803
=> library: do not always add --yes in batch mode

requirements.txt, tests/requirements.txt
We've just noticed that deploying Nautilus with ceph-ansible stable-4.0 on Ubuntu Bionic breaks with:
```
Unexpected Exception, this is probably a bug: No module named 'six'
```
The fix looks pretty simple so here's a PR. :)
`config_template.py` relies on `six`, which isn't listed in the default `requirements.txt`. This previously frequently wasn't a problem, because `six` used to be a standard package being installed into a venv, and lots of other projects depended on it.
It also does get installed for unit and integration tests via `tests/requirements.txt`, so any broken dependency on `six` wouldn't be detected by `tox` runs.
However, as other projects and distributions have phased out Python 2.7 support the dependency on `six` becomes less common. To complicate matters further, *some* …
=> requirements.txt: Move the six dependency into the general requirements

group_vars/rhcs.yml.sample, rhcs_edits.txt
The current dashboard images deployed have a bad health index.
Updating to a newer version fixes this issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1925350
=> defaults: update rhcs dashboard images versions

infrastructure-playbooks/rolling_update.yml
This commit fixes two issues in rolling_update.yml:
- `container_exec_cmd_update_osd` is unset in the `complete osd upgrade`
play so it never runs the command in a container.
- the 'require-osd-release' task is never applied because the condition
looks for luminous release.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1930164
=> update: fix require-osd-release task

roles/ceph-dashboard/tasks/configure_dashboard.yml
the `ceph_cmd` fact is missing the `--net=host` parameter.
Some tasks consuming this fact can fail like following:
```
Error: error configuring network namespace for container b8ec913db1fb694ae683faf202680de7a59c714a004e533aba87e8503d29261f: Missing CNI default network
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1931365
=> dashboard: add missing parameter in `ceph_cmd`

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
http://docs.ceph.com/docs/nautilus/radosgw/frontends/ 404s so replace
it with a working Octopus docs link, and correct the spelling of
"additional" while I'm at it.
=> [skip ci] Fix typo and broken link for documenting RGW frontends

roles/ceph-common/tasks/installs/debian_uca_repository.yml, roles/ceph-handler/handlers/main.yml
This is a cherry-pick of 0f8a61a3ae08cc3b3f2b91968764eeecb565aab6 with the merge conflict resolved.
The "update apt cache" in the ceph-handler role was never called and the
handler trigger after adding the uca repository doesn't exist at all.
Instead of using a handler for that we can just set the update_cache
parameter to true like the other apt_repository tasks.
Justification for commit to a stable branch: this change was already made in master, but stable-5.0 is broken because it isn't applied there - failure log extract:
```
2021-02-25 15:03:50,357 p=4824 u=mv3 n=ansible | TASK [ceph-common : include debian_uca_repository.yml] *************************
2021-02-25 15:03:50,358 p=4824 u=mv3 n=ansible | Thursday 25 February 2021  15:03:50 +0000 (0:00:00.067)       0:01:48.924 ***** …
```
=> debian/uca: remove the handler notification (backport)

roles/ceph-common/tasks/installs/redhat_dev_repository.yml
Due to recent changes in shaman, there's a chance it returns the wrong
repository from architecture point of view.
We can query shaman and ask for the correct architecture to get around
this.
(cherry picked from commit 39649f0ce8dd1c7b911fb7442f16e141735685b0)
=> common: ensure shaman returns right repo

roles/ceph-facts/tasks/facts.yml
Just likve `devices`, this commit adds the support for linux device aliases for
`dedicated_devices` and `bluestore_wal_devices`.
Backports: #5584
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1919084
Signed-off-by: Tyler Bishop <tbishop@liquidweb.com>
(cherry picked from commit ee4b8804ae1260a84737b7db8de2e9d2eb3a5737)
=> facts: support device aliases for (dedicated|bluestore_wal)_devices (bp #5584)

docs/source/osds/scenarios.rst, roles/ceph-osd/tasks/scenarios/lvm-batch.yml
It's sometimes useful to be able to skip the OSD creation phase of a `ceph-ansible` run (see #1777 for example), and the lvm scenario already has a `prepare_osd` tag on the relevant play. This PR applies that tag to the equivalent play for the lvm-batch scenario, and documents the availability of this tag.
Could this be backported to (at least) stable-5 please?
=> ceph-osd: add prepare_osd tag to lvm-batch scenario, document usage

.github/stale.yml
This decreases the number of days of inactivity before an issue becomes
sstale.
=> [skip ci] stalebot: update config

roles/ceph-mon/tasks/deploy_monitors.yml
Skip the `get initial keyring when it already exists` task when both commands
whose `stdout` output it requires have been skipped (e.g. when running in check
mode).
This was previously fixed in #5946, but got lost in the refactoring from #6064.
The fix is also slightly different from the original, because the `ceph_key` module is now being used instead of `command`, and that task is not skipped in check mode, it just returns an empty `stdout`.
=> ceph-mon: Fix check mode for deploy monitor tasks

library/radosgw_realm.py, roles/ceph-rgw/tasks/multisite/secondary.yml, tests/library/test_radosgw_realm.py
This adds the realm pull operation to the current `radosgw_realm` module.
The pull operation requires the url, access/secret key variables.
=> library: add realm pull to radosgw_realm module

roles/ceph-config/tasks/main.yml
When collocating OSDs with other daemon, `num_osds` is incorrectly calculated
because `ceph-config` is called multiple times.
Indeed, the following code:
```
num_osds: "{{ lvm_list.stdout | default('{}') | from_json | length | int + num_osds | default(0) | int }}"
```
makes `num_osds` be incremented each time `ceph-config` is called.
We have to reset it in order to get the correct number of expected OSDs.
=> config: reset num_osds

infrastructure-playbooks/rolling_update.yml
If the legacy name `grafana-server` is still being used when upgrading
from Nautilus to Pacific, the task that sets the fact `rolling_update`
to `true` doesn't run on the node(s) included in that group. Indeed the
play where we set this fact (`rolling_update`) only runs on the group
`monitoring_group_name | default('monitoring')`.
As a workaround, we can run earlier the task which converts the
`grafana-server` group name to `monitoring`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1935554
=> [skip ci] update: convert legacy grafana-server groupname early

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-validate/tasks/main.yml, site-container.yml.sample, site.yml.sample, tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml, tests/functional/external_clients/container/vagrant_variables.yml, tests/functional/external_clients/vagrant_variables.yml
This commit updates the default version of nfs-ganesha to V3.5 which is the
latest version available upstream.
=> nfs: bump nfs-ganesha version

infrastructure-playbooks/cephadm-adopt.yml
This is a follow up on PR #6332
cephadm-adopt.yml playbook is affected by the same bug
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1938658
=> adopt: convert legacy grafana-server groupname early

roles/ceph-facts/tasks/facts.yml
These tasks shouldn't be run when at least 1 monitor isn't present in
the inventory.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1937997
=> facts: fix nfs/external cluster scenario

infrastructure-playbooks/cephadm-adopt.yml
This commit makes the playbook fetch the minimal current ceph
configuration and write it later on monitoring nodes so `cephadm` can
proceed with the adoption.
When a monitoring stack was deployed on a dedicated node, it means no
`ceph.conf` file was written, `cephadm` requires a `ceph.conf` in order
to adopt the daemon present on the node.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1939887
=> [skip ci] cephadm_adopt: fetch and write ceph minimal config

infrastructure-playbooks/rolling_update.yml
if for some reason the playbook fails after the service was
stopped, disabled and masked and before it got restarted, enabled and
unmasked, the playbook leaves the service masked and which can make users
confused and forces them to unmask the unit manually.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1917680
=> [skip ci] rolling_update: unmask monitor service after a failure

infrastructure-playbooks/docker-to-podman.yml, infrastructure-playbooks/purge-cluster.yml
`command -v` is a bash script which needs a shell to run.
Fixes: #6325
=> [skip ci] fix 'command -v' tasks

roles/ceph-common/tasks/installs/debian_dev_repository.yml
We can end up with an arm only repo unless we are specific about the
architecture we require. Brings the deb code in line with the rpm
equivalent.
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
=> Make sure the repo url contains the correct arch

library/ceph_volume.py, roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml, tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all, tests/functional/docker2podman/group_vars/all, tests/functional/podman/group_vars/all, tests/functional/tests/nfs/test_nfs_ganesha.py, tests/functional/tests/rgw/test_rgw.py
This function makes the `ceph_volume` module be not idempotent in
containerized context because it tries to run a container and bindmount
directories that no longer exist.
In that case, the `lvs` command being executed returns something
different than `0` so we can't call `json.loads(out)['report'][0]['lv']`
since it might throw a python error.
The idea is to return `True` only if `rc` is equal to `0` and
`len(result)` is greater than `0`, which means the command matched an
LV.
Fixes: #6284
=> ceph_volume: fix bug in `is_lv()`

site-container.yml.sample, site.yml.sample
commit f6a0e95e51798316fce5e82b2463ff62396a681a reverted the change made
by a7f2fa73e63e69dba2e41aaac9732397eec437c9.
This commit bring back this change.
=> main: use `ansible_facts` for `architecture`

ansible.cfg, roles/ceph-facts/tasks/facts.yml
As a continuation of a7f2fa73e63e69dba2e41aaac9732397eec437c9, this
change switches fact injection to off by default in the provided
ansible.cfg.
=> Disable facts by default in ansible.cfg

group_vars/nfss.yml.sample, group_vars/osds.yml.sample, roles/ceph-facts/tasks/facts.yml, roles/ceph-nfs/defaults/main.yml, roles/ceph-osd/defaults/main.yml
This converts some missed calls to `ansible_*` that were missed in initial PR #6312
=> convert some missed `ansible_*`` calls to `ansible_facts['*']`

README-MULTISITE.md
This commit fixes some typos in MULTISITE documentation.
Signed-off-by: Ken Dreyer <ktdreyer@redhat.com>
=> [skip ci] README-MULTISITE: fix typos

README-MULTISITE.md
Docs reflect that each instance of `rgw_instances`
can now take rgw_zonemaster, rgw_zonesecondary,
rgw_zonegroupmaster, rgw_multisite_proto.
=> [skip ci] docs: rgw multisite docs with new rgw_instances config

.github/workflows/ansible-lint.yml
0.17.0 which was released yesterday breaks ansible-lint execution
=> [skip ci] tests: pin ruamel.yaml version

roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
rbd-mirroring is not configured as adding peer is getting skipped.
Peer addition should not get skipped if its not added already
Closes - https://bugzilla.redhat.com/show_bug.cgi?id=1942444
=> Peer addition won't be skipped if remote is not in peer

infrastructure-playbooks/rolling_update.yml
This adds the missing service stop task for ceph-crash upgrade workflow.
It should have been added through commit
`15872e3db1e342238636bc9c8e1aef6bd1d3dcd8` in stable-4.0 but at the time
we backported this patch ceph-crash wasn't implemented yet so the
ceph-crash related content in this patch was removed. Then, ceph-crash
has been implemented later so we are still missing this part of the patch in
stable-4.0.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1943471
=> update: stop ceph-crash service before upgrading

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml
This adds the possibility to deploy the dashboard with igw nodes using
a dedicated subnet.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1926170
=> dashboard: support igw nodes with dedicated subnet

infrastructure-playbooks/rolling_update.yml
Playbook must fail anyway, the `rescue` block has been introduced for
unmasking the unit after the playbook has failed.
=> [skip ci] update: followup on 07029e1

roles/ceph-common/tasks/installs/debian_dev_repository.yml, roles/ceph-common/tasks/installs/redhat_dev_repository.yml, roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
In commits 39649f0 and bf8cdad we switch from using the shaman /repos endpoint
to the /search endpoint for using the architecture filter.
In fact that filter is also available with the /repos endpoint, which requires
less ansible tasks.
This also adds back a condition remove in 5801171 on the ceph-iscsi
repository and that repository doesn't need to filter on the architecture
because the ceph-iscsi project is noarch.
Both ceph-iscsi and tcmu-runner shaman URLs were using the ceph_dev_branch
and ceph_dev_sha1 variables which doesn't make sense. Those variables are
only useful for the ceph core repository.
=> common,iscsi: don't use the shaman search endpoint

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
This add a quick documentation in ceph-defaults about `igw_network`
=> [skip ci] defaults: add a comment about `igw_network`

roles/ceph-rgw/tasks/rgw_create_pools.yml
Support enabling/disabling the pg autoscaler for rgw pools.
=> rgw: supports pg_autoscale_mode option for pool creation

group_vars/nfss.yml.sample, roles/ceph-nfs/defaults/main.yml, roles/ceph-nfs/tasks/start_nfs.yml, roles/ceph-nfs/templates/ganesha.conf.j2, roles/ceph-nfs/templates/idmap.conf.j2
Currently NFS Ganesha (ceph-nfs) consumes /etc/idmapd.conf, which
controls mapping of user/owner identities under NFSv4+. With
containerized service deployment, this file is an immutable part of the
container image and cannot be modified.
Here we provide group variables, and a taskk and templates for the
ceph-nfs role, to set the path of the idmap configuration file and
to make the most common adjustment to the contents of that file --
namely to set the 'Domain'. We default the path to /etc/ganesha/idmap.conf
so that we will not conflict with /etc/idmapd.conf on the controller nodes
where ganesha runs. NFSv4 clients, as used for example by the Cinder NFS
driver, consume /etc/idmapd.conf and may require different settings than
what is wanted for NFS Ganesha. Additionally, because we …
=> nfs: set idmap config for Ceph-NFS

roles/ceph-container-common/tasks/registry.yml
Pass the password variable via stdin for the registry login
authentication.
This allows to remove the no_log statement and see the task output
without displaying the password value.
=> container/registry: use password from stdin

roles/ceph-osd/tasks/start_osds.yml
8a17433312641fb6fa2f3184849b3d696a774156 introduced a regression for
containerized deployments.
When deploying with `osd_auto_discovery: false` the osds never got
activated.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1947072
=> osd: fix bug in osd activation (container)

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
This adds the iscsigws migration to containers.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1946987
=> [skip ci] switch_to_containers: support iscsigws migration

infrastructure-playbooks/docker-to-podman.yml, roles/ceph-facts/tasks/container_binary.yml, roles/ceph-handler/tasks/main.yml
when running docker-to-podman playbook, there's no need to call
`ceph-config` and `ceph-rgw` from the role `ceph-handler`.
It can even have side effects when coming from a baremetal cluster that
was previously migrated using the switch-to-containers playbook. Indeed
it might complain about missing .target systemd unit since they are
removed during that migration.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1944999
=> docker2podman: skip some role imports from handler

infrastructure-playbooks/docker-to-podman.yml
this adds a small documentation in the header of the playbook in order
to explain what is the goal of this playbook.
=> [skip ci] docker2podman: add documentation/header

roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
`configure_mirroring.yml` is called right after the daemon is started.
Sometimes, it can happen the first task in `configure_mirroring.yml` is
run while the daemon isn't yet ready, adding a retries/until on that
task should help to avoid causing the playbook to fail.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1944996
=> [skip ci] rbdmirror: add retries/until when configuring mirroring

infrastructure-playbooks/filestore-to-bluestore.yml
This removes the fact `skipped_nodes` which is useless when we run with
`--limit` since it gets reset when a new iteration is made.
Instead, let's print within a final play which node has been skipped
reusing the `skip_this_node` fact.
=> [skip ci] fs2bs: add a final play

roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
This adds a `ExecStartPre=-/usr/bin/mkdir -p /var/log/ceph` in all
systemd service templates for all ceph daemon.
This is specific to RHCS after a Leapp upgrade is done. Indeed, the
`/var/log/ceph` seems to be removed after the upgrade.
In order to work around this issue let's ensure the directory is present
before trying to start the containers with podman.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1949489
=> container/systemd: ensure /var/log/ceph exists

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
When collocating daemons, if we chown all files under `/var/lib/ceph` it
can cause issues for the collocated daemons that wouldn't have been
migrated yet.
This commit makes the playbook chown only the files corresponding to the
daemon being migrated.
=> [skip ci] switch-to-containers: only chown corresponding files

roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
The `set_fact rgw_ports` task was failing due to a templating error, because
`hostvars[item].rgw_instances` is a list, but it was treated as if it was a
dictionary.
Another issue was the fact that the `unique` filter only applied to the list
being appended to `rgw_ports` instead of the entire list, which means it was
possible to have duplicate items.
Lastly, `rgw_ports` would have been a list of integers, but the `seport` module
expects a list of strings.
This commit fixes all of the issues above, allowing the `ceph-rgw-loadbalancer`
role to work on systems with SELinux enabled.
This should be backported to the stable branches as well.
=> [skip ci] ceph-rgw-loadbalancer: Fix rgw_ports fact

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml
When VIPs are provided, all the monitoring services should be
configured using the related VIP. For this reason a  new VIP
variable is added for both prometheus and alertmanager: we're
already able to properly config the grafana frontend vip using
the dashboard_frontend_vip variable.
This change adds the same variable for both prometheus and
alertmanager.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1949391
=> Config the monitoring stack components api urls using a VIP

roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-mds/tasks/create_mds_filesystems.yml, roles/ceph-osd/tasks/openstack_config.yml
We shouldn't prevent from setting target_size_ratio when the autoscaler
is set to 'warn'.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1906305
=> osd: always allow setting target_size_ratio

docs/source/index.rst
Since 839fac8 we now use ansible 2.10 on the master branch.
=> [skip ci] docs: update ansible version for master

group_vars/all.yml.sample, group_vars/nfss.yml.sample
It looks like the `generate_group_vars_sample.sh` script wasn't executed
during previous PRs that were modifying the default values.
=> [skip ci] group_vars: fix default values

infrastructure-playbooks/cephadm-adopt.yml
When migrating from a cluster with no MDS nodes deployed,
`{{ cephfs_data_pool.name }}` doesn't exist so we need to create a pool
for storing nfs export objects.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1950403
=> [skip ci] cephadm_adopt: create a 'nfs-ganesha' pool

roles/ceph-mon/tasks/deploy_monitors.yml
=> ceph-mon: Fix check mode for deploy monitor tasks (backport #6301)

infrastructure-playbooks/cephadm-adopt.yml
ceph-ansible leaves a ceph-crash container in containerized deployment.
It means we end up with 2 ceph-crash containers running after the
migration playbook is complete.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1954614
=> [skip ci] cephadm_adopt: fix ceph-crash migration

roles/ceph-common/tasks/main.yml, roles/ceph-osd/templates/ceph-osd.service.j2
`TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES` is for both bluestore and filestore
=> ceph-osd: allow to use ceph_tcmalloc_max_total_thread_cache for bluestore

roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml, roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
We need to filter with the OS architecture in order to fetch the right
dev repository in shaman
=> ceph-nfs: fix dev repo task

infrastructure-playbooks/rolling_update.yml
This is a workaround for an issue in ansible.
When trying to stop/mask/disable this service in one task, the stop
didn't actually happen, the task doesn't fail but for some reason the
container is still present and running.
Then the task starting the service in the role ceph-crash fails because
it can't start the container since it's already running with the same
name.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1955393
=> [skip ci] update: fix ceph-crash stop task

roles/ceph-rgw/tasks/rgw_create_pools.yml
The pg_autoscale_mode for rgw pools introduced in 9f03a52 was wrong
and was missing a `value` keyword because `rgw_create_pools` is a
dict.
Fixes: #6516
=> ceph-rgw: fix pg_autoscale_mode for pool

roles/ceph-nfs/tasks/pre_requisite_container.yml
Since we need to revert 33bfb10, this is an alternative to initial approach.
We can avoid maintaining this file since it is present in container
image. The idea is to simply get it from the image container and write
it to the host.
Fixes: #6501
=> [skip ci] nfs: get org.ganesha.nfsd.conf from container

infrastructure-playbooks/rolling_update.yml
There's no benefit in gathering facts again on each play in
rolling_update.yml
=> [skip ci] update: do not gather facts on each play

tests/scripts/vagrant_up.sh
temporary work around vagrant cloud issue which seems broken at the time
of pushing this commit.
Let's pull images from cloud.centos.org for now since vagrant cloud
hosted images return a 403 error.
=> tests: pull images from cloud.centos.org

tests/scripts/vagrant_up.sh
This commit rewrites the deprecated syntax used in vagrant_up.sh
=> vagrant_up: fix bash legacy syntax

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-container-common/tasks/prerequisites.yml, roles/ceph-defaults/defaults/main.yml
Enabling lvmetad in containerized deployments on el7 based OS might
cause issues.
This commit make it possible to disable this service if needed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1955040
=> container: conditionnally disable lvmetad

roles/ceph-prometheus/templates/prometheus.yml.j2
When osd nodes are collocated in the clients group (HCI context for
instance), the current logic will exclude osd nodes since they are
present in the client group.
The best fix would be to exclude clients node only when they are not
member of another group but for now, as a workaround, we can enforce
the addition of osd nodes to fix this specific case.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1947695
=> prometheus: enforce osd nodes in templates

infrastructure-playbooks/filestore-to-bluestore.yml
using 'match' filter in that task will lead to bad behavior if I have
the following node names for instance:
- node1
- node11
- node111
with `selectattr('name', 'match', inventory_hostname)` it will match
'node1' along with 'node11' and 'node111'.
using 'equalto' filter will make sure we only match the target node.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1963066
=> [skip ci] fs2bs: fix wrong filter when setting osd_ids

infrastructure-playbooks/filestore-to-bluestore.yml
0990ae41099d8b9d678f546fc8790033f421711f changed the filter in
selectattr() from 'match' to 'equalto' but due to an incompatibility with
the Jinja2 version for python 2.7 on el7 we must stick to using 'match'
filter.
=> fs2bs: use match filter in selectattr()

roles/ceph-crash/tasks/main.yml, tests/scripts/vagrant_up.sh
ceph-crash deployments is broken when ceph-ansible playbook is called
with --limit in containerized contexts since we don't set
`container_exec_cmd` on the first monitor.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1964835
=> crash: fix --limit deployments (containers)

infrastructure-playbooks/rolling_update.yml, roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
during backport of c8b92deba10c0b6e0ebcb0e31315b1e6174fdc0c the pattern
should have been s/monitoring_group_name/grafana_server_group_name/
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1964907
=> dashboard: fix typo introduced during backport

roles/ceph-dashboard/tasks/configure_dashboard.yml
When deploying dashboard in a cluster with rgw multisite deployed.
Due to the last rgw multisite refactor, we now expect the variable
`rgw_zonemaster` to be defined in the dict `rgw_instances`.
The idea here is to create that user on the cluster as soon as we have 1
`rgw_zonemaster` set to `true` in `rgw_instances`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1964995
=> dashboard: fix rgw user creation

roles/ceph-grafana/templates/grafana.ini.j2, tests/functional/tests/mgr/test_mgr.py
When using grafana behind https `cookie_secure` should be set to `true`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1966880
=> dashboard: set cookie_secure in grafana

tests/functional/tests/mgr/test_mgr.py
This reverts commit 2e19d1705efa8ef247eecb540357195d5142da77.
A new build of ceph@master including the fix is available so
this is not needed anymore.
=> Revert "tests: disable test_mgr_dashboard_is_listening"

roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-client/tasks/pre_requisite.yml, roles/ceph-crash/tasks/main.yml, roles/ceph-iscsi-gw/tasks/common.yml, roles/ceph-mds/tasks/common.yml, roles/ceph-mgr/tasks/common.yml, roles/ceph-nfs/tasks/main.yml, roles/ceph-nfs/tasks/pre_requisite_container.yml, roles/ceph-nfs/tasks/pre_requisite_non_container.yml, roles/ceph-osd/tasks/common.yml, roles/ceph-osd/tasks/openstack_config.yml, roles/ceph-rbd-mirror/tasks/common.yml, roles/ceph-rgw/tasks/common.yml
Set **no_log: true** for all the updated files , so that sensitive information are not logged out in the ansible output, thereby increasing security and privacy.
Fixes: #6529
Signed-off-by: Neelaksh Singh <neelaksh48@gmail.com>
=> Sensitive key data now hidden in output log

tests/scripts/vagrant_up.sh
CentOS 8.4 vagrant image is available at https://cloud.centos.org
let's use it.
=> tests: use CentOS 8.4 image

roles/ceph-handler/tasks/main.yml
When monitors and rgw are collocated with multisite enabled, the
rolling_update playbook fails because during the workflow, we run some
radosgw-admin commands very early on the first mon even though this is
the monitor being upgraded, it means the container doesn't exist since
it was stopped.
This block is relevant only for scaling out rgw daemons or initial
deployment. In rolling_update workflow, it is not needed so let's skip
it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1970232
=> rolling_update: fix mon+rgw/multisite collocation

tests/functional/all-in-one/container/vagrant_variables.yml, tests/functional/all-in-one/vagrant_variables.yml
Since we fire up much less VMs than other job, we can affoard allocating
more memory here for this job.
Each VM hosts more daemon so 1024Mb can be too few.
=> tests: allocate more memory for all_in_one job

infrastructure-playbooks/cephadm-adopt.yml
When no `[mgrs]` group is defined in the inventory, mgr daemon are
implicitly collocated with monitors.
This task currently relies on the length of the mgr group in order to
tell cephadm to deploy mgr daemons.
If there's no `[mgrs]` group defined in the inventory, it will ask
cephadm to deploy 0 mgr daemon which doesn't make sense and will throw
an error.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1970313
=> [skip ci] cephadm-adopt: fix mgr placement hosts task

library/ceph_key.py, roles/ceph-mon/tasks/deploy_monitors.yml
When calling the `ceph_key` module with `state: info`, if the ceph
command called fails, the actual error is hidden by the module which
makes it pretty difficult to troubleshoot.
The current code always states that if rc is not equal to 0 the keyring
doesn't exist.
`state: info` should always return the actual rc, stdout and stderr.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1964889
=> ceph_key: handle error in a better way

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-container-common/tasks/prerequisites.yml, roles/ceph-defaults/defaults/main.yml
Enabling lvmetad in containerized deployments on el7 based OS might
cause issues.
This commit make it possible to disable this service if needed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1955040
=> [skip ci] container: conditionnally disable lvmetad

roles/ceph-nfs/tasks/pre_requisite_container.yml
There's no need to copy this keyring when using nfs with mds
=> nfs: do no copy client.bootstrap-rgw when using mds

roles/ceph-nfs/tasks/pre_requisite_container.yml, tests/conftest.py, tests/functional/all_daemons/container/group_vars/nfss, tests/functional/all_daemons/group_vars/nfss, tests/functional/tests/nfs/test_nfs_ganesha.py
needed for the update job in stable-6.0 branch.
the upgrade from either nautilus or octopus to pacific isnt supported
when nfs/rgw is deployed.
=> tests: use nfs/mds instead of nfs/rgw

infrastructure-playbooks/rolling_update.yml, tests/conftest.py, tests/functional/tests/nfs/test_nfs_ganesha.py, tox-update.ini
This is an unsupported configuration.
There are issues with RGW+NFS upgraded from Nautilus to Pacific.
This approach might be seen as a bit aggressive but it is preferable
to wait before upgrading in that case.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1970003
=> update: block upgrade when nfs+rgw is deployed

roles/ceph-facts/tasks/set_radosgw_address.yml
When running the switch-to-containers playbook with multisite enabled,
the fact "rgw_instances" is only set for the node being processed
(serial: 1), the consequence of that is that the set_fact of
'rgw_instances_all' can't iterate over all rgw node in order to look up
each 'rgw_instances_host'.
Adding a condition checking whether hostvars[item]["rgw_instances_host"]
is defined fixes this issue.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967926
=> multisite: fix bug during switch2containers

infrastructure-playbooks/cephadm-adopt.yml
We need to support rgw multisite deployments.
This commit makes the adoption playbook support this kind of deployment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967455
=> [skip ci] cephadm-adopt: support rgw multisite adoption

roles/ceph-prometheus/files/ceph_dashboard.yml
It was requested for us to update our alerting definitions to include a
slow OSD Ops health check.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1951664
=> dashboard: Add new prometheus alert

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
This adds the ceph-validate role before starting the switch to a containerized
deployment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1968177
=> [skip ci] switch2container: run ceph-validate role

infrastructure-playbooks/cephadm-adopt.yml
If multi-realms were deployed with several instances belonging to the same
realm and zone using the same port on different nodes, the service id
expected by cephadm will be the same and therefore only one service will
be deployed. We need to create a service called
`<node>.<realm>.<zone>.<port>` to be sure the service name will be unique
and well deployed on the expected node in order to preserve backward
compatibility with the rgws instances that were deployed with
ceph-ansible.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967455
=> [skip ci] cephadm-adopt/rgw: add host target in svc_id

infrastructure-playbooks/shrink-mgr.yml, tests/functional/shrink_mgr/hosts-2
Do not rely on the inventory aliases in order to check if the selected
manager to be removed is present.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967897
=> [skip ci] shrink-mgr: modify existing mgr check

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-common/tasks/configure_memory_allocator.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2, site.yml.sample
All ceph daemons need to have the TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES
environment variable set to 128MB by default in container setup.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1970913
=> container: set tcmalloc value by default

roles/ceph-prometheus/templates/prometheus.yml.j2
The prometheus service isn't binding on localhost.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1933560
=> [skip ci] prometheus: fix prometheus target url

infrastructure-playbooks/purge-container-cluster.yml
This adds the monitoring group in the "final cleanup play" so any cid
files generated are well removed when purging the cluster.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1974536
=> [skip ci] purge: add monitoring group in final cleanup play

infrastructure-playbooks/cephadm-adopt.yml
Add any_errors_fatal: true in cephadm-adopt playbook.
We should stop the playbook execution when a task throws an error.
Otherwise, it can lead to unexpected behavior.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1976179
=> [skip ci] cephadm_adopt: add any_errors_fatal on play

plugins/callback/installer_checkpoint.py, site-container.yml.sample, site.yml.sample
The ceph crash insatll checkpoint callback was missing in the main
playbooks.
=> [skip ci] ceph-crash: add install checkpoint

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-dashboard/tasks/configure_dashboard_backends.yml, roles/ceph-defaults/defaults/main.yml
This introduces a new variable `dashboard_network` in order to support
deploying the dashboard on a different subnet.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1927574
=> [skip ci] dashboard: support dedicated network for the dashboard

.github/workflows/ansible-lint.yml
The dashboard.yml playbook was missing from the ansible-lint workflow.
=> [skip ci] workflow: add dashboard playbook to ansible-lint

infrastructure-playbooks/rolling_update.yml
After an upgrade, the presence of straw buckets will produce the
following warning (HEALTH_WARN):
```
crush map has legacy tunables (require firefly, min is hammer)
```
because straw bucket is a firefly feature it needs to be converted to
straw2.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967964
=> [skip ci] update: convert straw bucket

infrastructure-playbooks/rolling_update.yml
It's better to fail the playbook so the user is aware the straw2
migration has failed.
=> [skip ci] update: fail the playbook if straw2 conversion failed

infrastructure-playbooks/rolling_update.yml
If one a the monitor is out of the quorum then nothing prevents the upgrade
playbook to run.
We only check if we have at least three monitor nodes but we should also
check if those monitor nodes are correctly present in the quorum.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1952571
=> [skip ci] rolling_update: check quorum state before upgrade

infrastructure-playbooks/cephadm-adopt.yml
This enables the osd_memory_target_autotune option on HCI environment.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1973149
=> [skip ci] cephadm-adopt: enable osd memory autotune for HCI

library/ceph_volume.py, tests/library/test_ceph_volume.py
This commit adds the support for zapping an osd by osd_id in the
ceph_volume module.
=> lib/ceph-volume: support zapping by osd_id

group_vars/nfss.yml.sample, roles/ceph-nfs/defaults/main.yml, roles/ceph-nfs/templates/ganesha.conf.j2
We already have config override variables for existing block (like
ganesha_ceph_export_overrides, ganesha_log_overrides, etc...) or a
global one (ganesha_conf_overrides) but redefining the NFS_CORE_PARAM
block in that variable will erase all previous values (currently only
Bind_Addr).
```yaml
ganesha_core_param_overrides: |
Enable_UDP = false;
NFS_Port = 2050;
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1941775
=> [skip ci] ceph-nfs: allow overriding NFS_CORE_PARAM

roles/ceph-mgr/tasks/common.yml, roles/ceph-mgr/tasks/main.yml, roles/ceph-mgr/tasks/mgr_modules.yml
Populating the ceph_mgr_modules list in the mgr_modules doesn't make sense
since that file is only executed if the list isn't empty or we're using the
dashboard.
=> [skip ci] ceph-mgr: move mgr module list to common

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-facts/tasks/facts.yml, roles/ceph-handler/tasks/handler_osds.yml
The PG autoscaler can disrupt the PG checks so the idea here is to
disable it and re-enable it back after the restart is done.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1982054
=> common: disable/enable pg_autoscaler

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-handler/tasks/handler_osds.yml
When using python 2 and the task with a loop is skipped then it generates
an error.
Unexpected templating type error occurred on
({{ (pool_list.stdout | from_json)['pools'] }}): expected string or buffer
=> common: fix py2 pool_list from_json when skipped

infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
1303611 introduced tasks for disabling the pg_autoscaler on pools and
the balancer but thoses tasks are already executed on the first monitor
node so we don't need to add the `run_once` statement.
=> [skip ci] common: remove unnecessary run_once statements

roles/ceph-rgw/tasks/multisite/main.yml
When the `rgw_multisite_proto` variable is set to https then we shoudn't use
the IP address in the zone endpoints list but the node FQDN to match the
TLS certificate CN.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1965504
=> [skip ci] multisite: use node fqdn for endpoints when https

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-prometheus/templates/alertmanager.yml.j2
When using self-signed/untrusted CA certificates, alertmanager displays
an error in logs. With this commit this should make those messages
disappear.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1936299
Co-authored-by: Guillaume Abrioux <gabrioux@redhat.com>
=> [skip ci] alertmanager: allow disable dashboard tls verify

group_vars/mgrs.yml.sample, roles/ceph-mgr/defaults/main.yml, roles/ceph-mgr/tasks/pre_requisite.yml
This is a partial backport of 2547ab60.
We are currently installing the ceph-mgr-dashboard package even if the
dashboard_enabled variable is set to false.
=> ceph-mgr: don't install dashboard pkg by default

infrastructure-playbooks/rolling_update.yml
Check early which Ceph release is going to be deployed and fail if it
doesn't correspond to the ceph-ansible version being used.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1978643
=> [skip ci] update: check the ceph release

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
The radosgw-sync-overview and rbd-details grafana dashboars were missing
from the list.
Closes: #6758
=> [skip ci] ceph-defaults: add missing grafana dashboards

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
We currently download the grafana dashboars from the ceph@master branch
for all ceph releases.
We should use the right ceph branch according to the ceph release.
=> [skip ci][stable-6.0] ceph-defaults: update grafana dashboards source

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml
We currently download the grafana dashboars from the ceph@master branch
for all ceph releases.
We should use the right ceph branch according to the ceph release.
=> [skip ci][stable-5.0] ceph-defaults: update grafana dashboards source

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-handler/tasks/handler_osds.yml
Run the Ceph commands that only gather information (without making any changes
to the cluster) when running Ansible in check mode.
This allows the tasks that depend on the variables set by those tasks to
succeed in check mode.
=> [skip ci] ceph-handler: Fix osd handler in check mode

infrastructure-playbooks/rolling_update.yml
eec3878 introduced a regression for upgrade scenarios where there's no
monitor nodes at all (like ganesha standalone, external clients, etc..)
```console
TASK [get the ceph release being deployed] ************************************
task path: infrastructure-playbooks/rolling_update.yml:121
Thursday 29 July 2021  15:55:29 +0000 (0:00:00.484)       0:00:15.802 *********
fatal: [client0]: FAILED! =>
msg: '''dict object'' has no attribute ''mons'''
```
=> [skip ci] rolling_update: get ceph version when mons exist

library/ceph_dashboard_user.py, tests/library/test_ceph_dashboard_user.py
When the ceph dashboard user creation fails then the issue is hidden
as we don't check the return code and don't print the error message
in the module output.
This ends up with a failure on the ceph dashboard set roles command saying
that the user doesn't exist.
By failing on the user creation, we will have an explicit explaination of
the issue (like weak password).
Closes: #6197
=> [skip ci] library: exit on user creation failure

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, roles/ceph-handler/tasks/handler_osds.yml
The ceph osd pool ls detail command is a subset of the ceph osd dump
command.
```console
$ ceph osd dump --format json|wc -c
10117
$ ceph osd pool ls detail --format json|wc -c
4740
```
=> [skip ci] osds: use osd pool ls instead of osd dump command

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-validate/tasks/main.yml
`radosgw_civetweb_xxx` variables are legacy variables and users should
have switched to `radosgw_frontend_xxx` variables instead.
=> ceph-defaults: remove radosgw_civetweb_ variables

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
Description of problem:
RGW container fails to start (on a RHEL8 setup) with:
```console
Jul 15 14:20:43 servera kernel: cgroup: fork rejected by pids controller in /machine.slice/libpod-54832992fcbbbf92b0d10d0491f7ff987728bec87c1c55b79cb3921c6f503f49.scope
Jul 15 14:20:43 servera conmon[34853]: terminate called after throwing an instance of 'std::system_error'
Jul 15 14:20:43 servera conmon[34853]:  what():  Resource temporarily unavailable
Jul 15 14:20:43 servera conmon[34853]: *** Caught signal (Aborted) **
Jul 15 14:20:43 servera conmon[34853]: in thread 7f5d605e1280 
```
The podman default pids-limit is set to 2048. 
```console
$ grep . sys/fs/cgroup/pids/machine.slice/libpod-*/pids.max
sys/fs/cgroup/pids/machine.slice/libpod-9336707e04da464b9128b7c57a0ee9b70efc5acb5207ea03ab413583c22 …
```
=> [skip ci] container: add pids limit parameter

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
The balancer status is registered during the cephadm-adopt, rolling_update
and swith2container playbooks. But it is also used in the ceph-handler role
which is included in those playbooks too.
Even if the ceph-handler tasks are skipped for rolling_update and
switch2container, the balancer_status variable is erased with the skip task
result.
play1:
register: balancer_status
play2:
register: balancer_status <-- skipped
play3:
when: (balancer_status.stdout | from_json)['active'] | bool
This leads to issue like:
```console
The conditional check '(balancer_status.stdout | from_json)['active'] | bool'
failed. The error was: Unexpected templating type error occurred on
({% if (balancer_status.stdout | from_json)['active'] | bool %} True
{% else %} False {% endif %}): expected string or buffer. …
```
=> [skip ci] infra: use dedicated variables for balancer status

infrastructure-playbooks/cephadm-adopt.yml
This has been removed from the code (orch apply name).
The default pool name is now .nfs
=> [skip ci] cephadm-adopt: remove nfs pool and namespace

infrastructure-playbooks/cephadm-adopt.yml
Without this, when rgw is managed by cephadm, it fails to start because
the ssl certificate isn't present in the kv store.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1987010
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1988404
=> [skip ci] adopt: import rgw ssl certificate into kv store

roles/ceph-dashboard/tasks/configure_dashboard.yml
the current way the variable is built results in:
```
2021-08-03 04:18:23,020 - ceph.ceph - INFO - ok: [ceph-sangadi-4x-indpt6-node1-installer] => changed=false
ansible_facts:
subj_alt_names: |-
subjectAltName=ceph-sangadi-4x-indpt6-node1-installer/subjectAltName=10.0.210.223/subjectAltName=ceph-sangadi-4x-indpt6-node1-installersubjectAltName=ceph-sangadi-4x-indpt6-node2/subjectAltName=10.0.210.252/subjectAltName=ceph-sangadi-4x-indpt6-node2/
```
which is incorrect.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1978869
=> [skip ci] dashboard: subj_alt_names fact refactor

infrastructure-playbooks/rgw-add-users-buckets.yml
Fixes typo in infrastructure-playbooks/rgw-add-users-buckets.yml  playbook
=> [skip ci] Fixes typo in rgw-add-users-buckets playbook

infrastructure-playbooks/add-osd.yml
Because we're delegating the task to the first monitor node, we need to be
sure that the container_exec_cmd fact is the one from that node too otherwise
we could have a mismatch on the ceph-mon container name.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1990772
=> add-osd: use container_exec_cmd fact from mon host

roles/ceph-dashboard/tasks/configure_dashboard.yml
With OpenSSL version prior 1.1.1 (like CentOS 7 with 1.0.2k), the -addext
doesn't exist.
As a solution, this uses the default openssl.cnf configuration file as a
template and add the subjectAltName in the v3_ca section. This temp openssl
configuration file is removed after the TLS certificate creation.
This patch also move the run_once statement at the block level.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1978869
=> ceph-dashboard: fix TLS cert openssl generation

roles/ceph-rgw/tasks/rgw_create_pools.yml
If the `pg_num` value specified in `rgw_create_pools` is different from the
actual value in the cluster, apply it with `ceph osd pool set`.
This corresponds to the behavior of the `ceph_pool` module used in Ceph Ansible
5.0 onward.
Also avoid setting the pool application if it's already done.
=> ceph-rgw: Set pg_num on RGW pool if required

roles/ceph-mon/tasks/deploy_monitors.yml
We don't want to display the keyring in the ansible log.
=> [skip ci] ceph-mon: do not log monitor keyring

tox.ini
for unlocking the ci.
this is intended to be reverted.
=> tests: use old build of ceph@master

library/ceph_volume.py, tests/library/test_ceph_volume.py
When using ceph-volume lvm create/prepare/batch then the keyring of each
OSD created is displayed in the output.
Let's replace those by some '*' chars.
=> ceph-volume: hide OSD keyring during creation

roles/ceph-dashboard/tasks/configure_dashboard.yml
Since [1] multiple ceph dashboard commands have been removed and this is
breaking the current ceph-ansible dashboard with RGW automation.
This removes the following dashboard rgw commands:
- ceph dashboard set-rgw-api-access-key
- ceph dashboard set-rgw-api-secret-key
- ceph dashboard set-rgw-api-host
- ceph dashboard set-rgw-api-port
- ceph dashboard set-rgw-api-scheme
Which are replaced by `ceph dashboard set-rgw-credentials`
The RGW user creation task is also removed.
Finally moving the delegate_to statement from the rgw tasks at the block
level.
[1] https://github.com/ceph/ceph/pull/42252
=> ceph-dashboard: fix object gateway integration

roles/ceph-iscsi-gw/tasks/systemd.yml, roles/ceph-mds/tasks/systemd.yml, roles/ceph-mgr/tasks/systemd.yml, roles/ceph-mon/tasks/systemd.yml, roles/ceph-nfs/tasks/systemd.yml, roles/ceph-rbd-mirror/tasks/systemd.yml, roles/ceph-rgw/tasks/systemd.yml
pr #4319 introduced some uesless `become: true` on systemd tasks.
=> [skip ci] roles: remove leftover from pr #4319

infrastructure-playbooks/cephadm-adopt.yml
Use cephadm_ssh_user to set custom user (not root) for cephadm to ssh to the hosts
=> cephadm-adopt: use cephadm_ssh_user for ssh user

Vagrantfile
When using a vagrant command from the root directory of the repo, it
throws an error if no 'vagrant_variables.yml' file is present.
```
Message: Errno::ENOENT: No such file or directory @ rb_sysopen - /home/guits/workspaces/ceph-ansible/vagrant_variables.yml
```
=> [skip ci] Vagrantfile: fallback on 'varant_variables.yml.sample'

infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/purge-cluster.yml, roles/ceph-container-common/files/ceph.target, roles/ceph-container-common/tasks/main.yml, roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-mds/files/ceph-mds.target, roles/ceph-mds/tasks/containerized.yml, roles/ceph-mds/tasks/systemd.yml, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/files/ceph-mgr.target, roles/ceph-mgr/tasks/start_mgr.yml, roles/ceph-mgr/tasks/systemd.yml, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/files/ceph-mon.target, roles/ceph-mon/tasks/systemd.yml, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-osd/files/ceph-osd.target, roles/ceph-osd/tasks/systemd.yml, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-rbd-mirror/files/ceph-rbd-mirror.target, roles/ceph-rbd-mirror/tasks/systemd.yml, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/files/ceph-radosgw.target, roles/ceph-rgw/tasks/systemd.yml, roles/ceph-rgw/templates/ceph-radosgw.service.j2
This adds ceph-*.target systemd unit files support for containerized
deployments.
This also fixes a regression introduced by PR #6719 (rgw and nfs systemd
units not getting purged)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1962748
=> [skip ci] containers: introduce target systemd unit

infrastructure-playbooks/cephadm-adopt.yml
This systemd target doesn't exist at all.
=> [skip ci] cephadm-adopt: remove ceph-nfs.target

group_vars/iscsigws.yml.sample, roles/ceph-iscsi-gw/defaults/main.yml, roles/ceph-iscsi-gw/tasks/common.yml, roles/ceph-iscsi-gw/templates/iscsi-gateway.cfg.j2
It restricts access to the iSCSI API.
It can be left empty if the API isn't going to be access from outside the
gateway node
Even though this seems to be a limited use case, it's better to leave it
empty by default than having a meaningless default value.
We could make this variable mandatory but that would be a breaking
change. Let's just add a logic in the template in order to set this
variable in the configuration file only if it was specified by users.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1994930
=> [skip ci] iscsi: don't set default value for trusted_ip_list

tox.ini
This reverts commit 47a451426a8308a4ea80e0a1e4d867e9dd290fe5.
This build isn't available on shaman anymore.
=> Revert "tests: use old build of ceph@master"

roles/ceph-container-common/tasks/fetch_image.yml
We don't pull the monitoring container images (alertmanager, prometheus,
node-exporter and grafana) in a dedicated task like we're doing for the
ceph container image.
This means that the container image pull is done during the start of the
systemd service.
By doing this, pulling the image behind a proxy isn't working with podman.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1995574
=> [skip ci] container: explicitly pull monitoring images

infrastructure-playbooks/purge-dashboard.yml
This adds the service cid file cleanup as supported in the classic purge
playbook since b9dd253
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1786691
=> [skip ci] purge-dashboard: remove cid files

group_vars/all.yml.sample, roles/ceph-defaults/defaults/main.yml
Because the ceph container images are now only pushed to the quay.io
registry then this updates the default registry value.
The docker.io registry can still be used but doesn't receive updated
container images.
=> [skip ci] ceph-defaults: set quay.io as the default registry

infrastructure-playbooks/purge-cluster.yml
`container_binary` isn't set anymore in the purge osd play because of a
regression introduced by 60aa70a.
The CI didn't catch it because the play purging node-exporter sets this
variable for all nodes before we run the purge osd play.
This commit fixes this regression.
=> [skip ci] purge: add container_binary needed for zap osds

tests/conftest.py, tests/functional/tests/monitoring/test_monitoring.py
Since the grafana-server group has been renamed to monitoring then
changing the associated tests.
=> tests: rename grafana to monitoring

tests/conftest.py, tests/functional/tests/grafana/test_grafana.py
This reverts commit a36586a7777dc34cb977f81dc2d5bdfa2bebd4b6.
=> [skip ci] Revert "tests: rename grafana to monitoring"

infrastructure-playbooks/cephadm-adopt.yml
registry login info needs to be stored in cluster for cephadm and future hosts
Signed-off-by: Daniel Pivonka <dpivonka@redhat.com>
=> [skip ci] cephadm-adopt: set cephadm registry login info

tests/functional/cephadm/group_vars/all
add missing variable `containerized_deployment` in group_vars
=> [skip ci] tests: fix container-cephadm job

tests/functional/all_daemons/ceph-override.json, tests/functional/all_daemons/container/group_vars/all, tests/functional/all_daemons/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/collocation/group_vars/all
Otherwise the clients won't be able to reconnect after the reboot in the
all_daemons and collocation jobs.
=> tests: auth_allow_insecure_global_id_reclaim false

infrastructure-playbooks/cephadm-adopt.yml
If old containers are still running, it can make tcmu-runner process
unable to open devices and there's nothing else to do than restarting
the container.
Also, as per discussion with iscsi experts, iscsi should be migrated before
OSDs. (the client should be closed before the server)
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2000412
=> adopt: stop iscsi services in the first place

infrastructure-playbooks/cephadm-adopt.yml
Let's add a `no_log: true` on the `cephadm registry-login` task.
=> [skip ci] cephadm-adopt: add no_log: true

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml
Unconfigured dashboard features can lead to empty tabs in the dashboard
containing no meaningful content. Allow users to disable dashboard features
they know will not be used.
A list of features to be disabled allows the user to define a streamlined
dashboard as standard across deployments. Defaults to disabling no features,
ensuring that users are sure they do not need the dashboard feature before
disabling it.
Signed-off-by: Alex Lambert <lamberta@microsoft.com>
=> dashboard: allow disabling of unused features

tests/functional/collect-logs.yml
in order to gather rgw logs, we need rgw_instances to be set.
=> tests: set rgw_instances in collect-logs.yml

docs/source/index.rst, docs/source/installation/containerized.rst, docs/source/installation/non-containerized.rst, docs/source/testing/tox.rst, group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, tests/conftest.py, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-shrink_osd.ini, tox-update.ini, tox.ini
ceph_stable_release is a legacy from the time where a single branch of ceph-ansible supported more than one release of ceph
=> ceph-defaults: set ceph_stable_release default to the stable branch release

infrastructure-playbooks/cephadm.yml
This is needed if you want a copy of the admin keyring on the admin
nodes.
=> cephadm: add admin label on mon nodes

infrastructure-playbooks/cephadm.yml
Use cephadm_ssh_user to set custom user (not root) for cephadm to ssh to the hosts
=> [skip ci] cephadm: use cephadm_ssh_user for ssh user

infrastructure-playbooks/rolling_update.yml
ceph-facts roles makes decisions based on the fact `rolling_update` so
it must be called before we run this role.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2014304
=> [skip ci] update: move a set_fact

infrastructure-playbooks/cephadm-adopt.yml
cephadm uses its own logrotate configuration file so ceph-ansible needs
to remove that custom file during the cephadm-adopt playbook.
Closes: #6944
=> [skip ci] cephadm-adopt: remove logrotate configuration

roles/ceph-mgr/tasks/common.yml
otherwise the osd play in rolling_update can fail when it tries to
disable it before upgrading osd nodes.
(cherry picked from commit 45a1d634d850ad971c71dbe9191b97caa3068b5a)
=> mgr: append balancer module to ceph_mgr_modules

roles/ceph-validate/tasks/main.yml
since a variable encrypted with vault is no longer a string but a
encrypted object we can't use the filter | length, we have to convert it
to a string before.
Fixes: #6991
=> validate: fix bug when using vault

infrastructure-playbooks/cephadm-adopt.yml
This is overriding those variables because the precedence at the 'block
var' level is greater than the group_vars/host_vars.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2026861
=> [skip ci] adopt: fix ceph_origin and ceph_repository defaults

infrastructure-playbooks/cephadm-adopt.yml, library/ceph_volume.py, tests/library/test_ceph_volume.py
cephadm-adopt: bindmount /var/lib/ceph with 'ro'
When collocating osds with iscsigw daemons, cephadm bindmounts the
following:
```
-v /var/lib/ceph/6126c064-6a9e-4092-8a64-977930df0843/iscsi.rbd.ceph-ameenasuhani-4fs3bq-node5.vomtqb/configfs:/sys/kernel/config
```
this prevents cephadm-adopt playbook from running container and bindmounting `/var/lib/ceph:/var/lib/ceph:z`
since 'ro' is enough in this playbook, let's replace the ':z' option on
this bindmount with ':ro'
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2027411
=> cephadm-adopt: bindmount /var/lib/ceph with 'ro'

library/ceph_ec_profile.py, roles/ceph-rgw/tasks/rgw_create_pools.yml, tests/library/test_ceph_ec_profile.py
The `crush_device_class` option of the `ceph_ec_profile` module was documented
but not implemented.
=> library/ceph_ec_profile.py: Support CRUSH device class

infrastructure-playbooks/purge-cluster.yml
Otherwise any ceph directories are left over on client nodes
after the purge.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2024815
=> [skip ci] purge: remove ceph directories on client nodes

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/grafana.yml
currently the grafana server is implicitly tied to the public network, this should be a separate configurable variable in case a user wants to have it on another interface /  network.
=> make grafana network configurable option

infrastructure-playbooks/cephadm-adopt.yml
When deploying the monitoring stack on a dedicated node, the directory
`/etc/ceph` has never been created. Therefore, the play for adopting the
monitoring stack fails because it can't write the minimal config file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2029697
=> [skip ci] cephadm-adopt: ensure /etc/ceph is present on monitoring node

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-grafana/templates/grafana-server.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2, roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2, roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-node-exporter/templates/node_exporter.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-prometheus/templates/alertmanager.service.j2, roles/ceph-prometheus/templates/prometheus.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
Update `After=` and `Wants=` parameters in container systemd units
and make them be aligned with the systemd units that come
from the packaging.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2027440
=> container: align systemd units with rpm

infrastructure-playbooks/rolling_update.yml
There's no need to run this play.
The client role only deploys keys and creates pools.
On large cluster deployment, this is time consuming for nothing.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2019831
=> [skip ci] update: speed up client play

roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
As of rhceph-5, those repositories don't longer exist.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2032790
=> [skip ci] common: remove legacy repositories

roles/ceph-dashboard/tasks/configure_dashboard.yml
The radosgw system user creation will fail when `rgw_instances`
is set at the host_var level because this variable won't bet set
on monitor nodes, given that this is where the tasks is delegated, it fails.
The idea here is to check over all rgw instances that are defined and set a
boolean fact in order to check if at least one instance has `rgw_zonemaster` set
to `True`
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2034595
=> dashboard: fix radosgw system user creation

tests/functional/all_daemons/hosts, tests/functional/all_daemons/vagrant_variables.yml
This commit [1] seems to have broken a selinux policy preventing nfs-ganesha from
starting properly.
Since we can't address the issue in ceph-ansible, let's disable temporarily nfs-ganesha testing.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/dae2da63d58ae6bfe9ee813b5a59bc40102d7b8d
=> tests: temporarily disable nfs-ganesha

roles/ceph-handler/handlers/main.yml, roles/ceph-handler/tasks/handler_mdss.yml, roles/ceph-handler/tasks/handler_mgrs.yml, roles/ceph-handler/tasks/handler_mons.yml, roles/ceph-handler/tasks/handler_nfss.yml, roles/ceph-handler/tasks/handler_osds.yml, roles/ceph-handler/tasks/handler_rbdmirrors.yml, roles/ceph-handler/tasks/handler_rgws.yml
When running in check mode with one or more Ceph daemons that need to be
restarted, the `tmpdirpath.path` variable that several handlers rely on is
undefined, leading to fatal errors.
This commit ensures the tasks that require `tmpdirpath.path` are skipped when
it's undefined.
=> ceph-handler: Fix check mode

infrastructure-playbooks/cephadm-adopt.yml
In order to avoid breaking changes, let's use named argument
instead of positional argument syntax in the command line
used to create rgw export.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2037691
=> [skip ci] cephadm-adopt: use named args in rgw export creation

library/cephadm_bootstrap.py
When you had ```ceph.conf``` and you want to overwrite your config  you'll get 
```stderr: 'ERROR: /etc/ceph/ceph.conf already exists; delete or pass --allow-overwrite to overwrite'```
Signed-off-by: yasinlachiny <yasin.lachiny@gmail.com>
=> [skip ci] cephadm: set allow_overwrite at bootstrap step

.github/workflows/ansible-lint.yml
Ansible-lint prior to v5.3.1 has issue with reach version >=11.0.0.
In order to cherry-pick fix to stable branches we fix rich version.
This should be reverted with ansible-lint version bump.
Signed-off-by: Dmitriy Rabotyagov <noonedeadpunk@ya.ru>
=> Fix rich version for ansible-lint

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
Let's use ppa repositories in order to deploy nfs-ganesha on Debian based OS.
Fixes: #7031
=> nfs-ganesha: fix debian based OS deployments

infrastructure-playbooks/cephadm-adopt.yml
The current implementation is wrong.
ceph-ansible lists all existing buckets and try to create
an export for each of them.
Instead, it's easier to create the export at the user level.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2037691
=> [skip ci] adopt: create nfs exports at the user level

tests/functional/cephadm/vagrant_variables.yml, tests/scripts/vagrant_up.sh, tox-cephadm.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-shrink_osd.ini, tox-subset_update.ini, tox-update.ini, tox.ini
CentOS 8 is EOL as of December 2021.
Let's use CentOS stream 8 instead.
=> tests: use centos stream-8 instead of centos 8

infrastructure-playbooks/cephadm-adopt.yml
In the OpenStack context we let the integration tool (TripleO)
deal with repositories and packages.
This change just adds the with_pkg tag to allow TripleO skipping
both the repositories and packages installation during the cephadm
adoption process.
=> [skip ci] Add with_pkg tag on package related tasks

roles/ceph-facts/tasks/get_def_crush_rule_name.yml, roles/ceph-osd/tasks/crush_rules.yml, roles/ceph-osd/tasks/start_osds.yml
This construct doesn't work as intended since ansible/ansible#74212:
```
item.stdout | default('{}') | from_json
```
That PR made the `command` module return `stdout` even in check mode (setting
it to the empty string), so `default()` has no effect in that case and
`from_json()` fails to parse an empty string.
Instead, `default()` needs to be invoked with its second argument set to
`True`, so that it replaces any `False` value (such as an empty string) with
its first argument:
```
item.stdout | default('{}', True) | from_json
```
=> Fix check mode in ceph-facts and ceph-osd

infrastructure-playbooks/cephadm-adopt.yml
This commit makes the cephadm-adopt playbook fail if the cluster
has the `POOL_APP_NOT_ENABLED` warning raised.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2040243
=> [skip ci] adopt: check for POOL_APP_NOT_ENABLED warning

infrastructure-playbooks/cephadm-adopt.yml
We can't use `{{ cephadm_cmd }}` here because the monitors aren't yet adopted.
We must use `{{ ceph_cmd }}` instead.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1967440
=> [skip ci] adopt: fix rbd-mirror adoption

library/ceph_pool.py
Before, creating a pool by providing *only* `pg_num` would result in an
error as it would produce `--pgp-num null`.
This commit fix this behavior by defaulting `pgp_num` value to `pg_num`.
As described in Ceph documentation, when creating a pool `pgp_num` and `pg_num` should be equal.
=> library/ceph_pool: Fix potential null value when creating pools

Makefile, ceph-ansible.spec.in
This fixes a couple of issues:
- ansible 2.10 isn't packaged.
- MOCK_CONFIG variable is wrong (centos 8 is EOL)
=> [skip ci] rpm: fix packaging

library/radosgw_caps.py, module_utils/ca_common.py, tests/library/test_radosgw_caps.py
This PR add `radosgw_caps` module to be able to manage RadosGW users capabilities.
Usage from the module's documentation:
```YAML
- name: add users read write and all buckets capabilities
radosgw_caps:
name: foo
state: present
caps:
- users=read,write
- buckets=*
- name: remove usage write capabilities
radosgw_caps:
name: foo
state: absent
caps:
- usage=write
```
This module support check mode by simulating the original `radosgw-admin` behavior when adding capabilities.
=> library: Add radosgw_caps to manage capabilities

roles/ceph-facts/tasks/devices.yml
Ignore disks with active mountpoint when osd_auto_discovery is true
=> ceph-facts: ignore mounted disks on osd auto discovery

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
This playbook doesn't support less than 3 monitors present in the inventory.
Just like the rolling_update playbook, let's fail if less than
3 monitors are present.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2049132
=> [skip ci] switch2containers: fail if less than 3 monitors

infrastructure-playbooks/purge-cluster.yml
This fixes the service file removal and makes the playbook
call `systemctl reset-failed` on the service because in Ceph
Nautilus, ceph-crash doesn't handle `SIGTERM` signal.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2055992
=> [skip ci] purge: ceph-crash purge fixes

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/cephadm-adopt.yml, roles/ceph-defaults/defaults/main.yml
By default cephadm uses root account to connect remotely
to other nodes in the cluster. This change allows to choose
another account.
=> [skip ci] adopt: various fixes

roles/ceph-container-common/tasks/prerequisites.yml, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
Initially MONs and RGW binded /etc/pki/ca-trust/extracted using the :z flag
(introduced to solve an OSP TripleO issue on RHEL - #3638) but using
this flag prevents local services (like sssd) running on the host from accessing
the certificates/files in that folder.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2026953
=> Turn off SELinux separation for containers MON and RGW

infrastructure-playbooks/rolling_update.yml, tests/functional/setup.yml
With this commit, upgrading a cluster from Nautilus to Pacific with
active rgw multisite replication will be blocked.
This is because a lot of bugs are currently present in Pacific regarding
RGW multisite.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2063702
=> upgrade: block upgrade when rgw multisite is active

infrastructure-playbooks/add-osd.yml, roles/ceph-facts/tasks/facts.yml, roles/ceph-osd/tasks/main.yml, roles/ceph-validate/tasks/check_devices.yml
`devices` has a default value set in `ceph-defaults` which is `[]`
it makes check_devices fail.
See details in corresponding BZ
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2068353
=> [skip ci] validate: fix wrong conditions

roles/ceph-dashboard/tasks/configure_dashboard.yml
When running the playbook with `--limit`, if the play targeted doesn't match
hosts present in the mgr group the playbook can fail.
=> dashboard: always set `dashboard_server_addr`

roles/ceph-facts/tasks/facts.yml, roles/ceph-osd/tasks/main.yml, roles/ceph-validate/tasks/check_devices.yml
This fixes a regression introduced in 3.2.57 and the check_devices step.
When lvm_volumes is defined with data and data_vg (vg/lv format) it goes
to the second part of the condition which throws an undefined error given
that `devices` isn't defined.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2069491
=> [skip ci] validate: fix check_devices

roles/ceph-infra/tasks/main.yml
When deploying with --skip-tags=package-install (when there is no access to a repository), the playbook is still trying to update the package cache, which makes the playbook fail.
This change prevents the playbook to try to update the cache when the package-install tag is skipped.
=> do not update Debian cache when package-install is disabled

roles/ceph-infra/tasks/main.yml
When deploying with --skip-tags=package-install (when there is no access to a repository), the playbook is still trying to update the package cache, which makes the playbook fail.
This change prevents the playbook to try to update the cache when the package-install tag is skipped.
Signed-off-by: Florent CARLI <florent.carli@rte-france.com>
(cherry picked from commit 63f20f59418a668261c91e408ad7ae5ac67a63d1)
=> do not update Debian cache when package-install is disabled (backport #7127)

roles/ceph-facts/tasks/facts.yml, roles/ceph-osd/tasks/main.yml
This ensures `docker_exec_cmd` is always set on the first monitor.
Otherwise, when running the playbook with `--limit`, it fails on tasks
calling `docker_exec_cmd` with a delegate_to on the first monitor since
it was not set.
=> facts: always set `docker_exec_cmd`

roles/ceph-validate/tasks/check_system.yml
Since the ISO install method removal, ceph-ansible isn't able
to detect wheter the user is deploying in a 'disconnected environment'.
By the way, given that ceph-ansible is available only for upgrading to RHCS 5,
this check doesn't make sense anymore, let's drop it.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2062147
=> validate: drop a check

roles/ceph-facts/tasks/devices.yml
This commit fixes templating error that occurs when using auto osd discovery. Getting the len before converting the result to a list causes "object of type generator has no len()" error in some conditions.
Signed-off-by: pinotelio <ahmadreza.mollapour@gmail.com>
=> ceph-facts: fix ansible templating error for auto osd discovery

roles/ceph-node-exporter/templates/node_exporter.service.j2
This commit makes podman bindmount `/:/rootfs:ro` so the container can
collect data from the host.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2028775
=> [skip ci] dashboard: allow collecting stats from the host

roles/ceph-validate/tasks/check_iscsi.yml
As AlmaLinux and Rocky are EL Distros you can deploy the iscsi gateway with ceph-ansible
Signed-off-by: Ingo Ebel <ingo.ebel@desy.de>
=> added AlmaLinux and Rocky for iscsi deploy

roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-facts/tasks/set_radosgw_address.yml
When the following conditions are met:
- rgw is deployed,
- dashboard is deployed,
- playbook is called with --limit,
- a node being processed is collocated on either a mon or mgr.
The playbook fails because `rgw_instances` is undefined.
The idea here is to make sure this variable is always defined.
=> dashboard: support --limit execution with rgw

roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-facts/tasks/set_radosgw_address.yml
When the following conditions are met:
- rgw is deployed,
- dashboard is deployed,
- playbook is called with --limit,
- a node being processed is collocated on either a mon or mgr.
The playbook fails because `rgw_instances` is undefined.
The idea here is to make sure this variable is always defined.
(cherry picked from commit aa0cc9381d8491c30a47d27b395f58e776c5ef0b)
=> backport (stable-5.0): dashboard: support --limit execution with rgw

roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-facts/tasks/set_radosgw_address.yml
When the following conditions are met:
- rgw is deployed,
- dashboard is deployed,
- playbook is called with --limit,
- a node being processed is collocated on either a mon or mgr.
The playbook fails because `rgw_instances` is undefined.
The idea here is to make sure this variable is always defined.
(cherry picked from commit aa0cc9381d8491c30a47d27b395f58e776c5ef0b)
=> backport (stable-4.0): dashboard: support --limit execution with rgw

roles/ceph-client/tasks/create_users_keys.yml, roles/ceph-mds/tasks/create_mds_filesystems.yml, roles/ceph-osd/tasks/openstack_config.yml
The current implementation doesn't allow to disable the pg autoscaler
on created pools. This allows only 'on' or 'warn'.
With this commit, this is now possible to disable it.
Valid values would be ['on', 'yes', 'true', 'off', 'no', 'false']
```
openstack_glance_pool:
name: "images"
pg_num: 128
pgp_num: 128
rule_name: "replicated_rule"
type: 1
application: "rbd"
size: 3
pg_autoscale_mode: off
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2062621
=> common: support setting pg autoscaler to off

roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-facts/tasks/facts.yml
introduced by ceph/ceph-ansible/pull/7150
when no rgw is present, it fails.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2076192
(cherry picked from commit 1a56fd6a21b3e39c8acd4d3d20451df9b96754d2)
=> dashboard: fix regression

tests/functional/setup.yml
The mirrors provided by CentOS' mirrorlists are super slow
Signed-off-by: David Galloway <dgallowa@redhat.com>
=> tests/setup: Use local mirror of centos 8 stream repo

roles/ceph-facts/tasks/set_radosgw_address.yml
when these variables are defined in the inventory host file,
all tasks are skipped then because the node being played isn't
aware about the values from the rgw nodes.
=> facts: follow up on aa0cc93

README.rst, site-container.yml.sample, site.yml.sample
The official installer is now cephadm.
=> Warn about ceph-ansible deprecation

infrastructure-playbooks/cephadm-adopt.yml
When this directory is left after the osd adoption, it leads to the following error:
```
[WRN] CEPHADM_REFRESH_FAILED: failed to probe daemons or devices
host axdesec2ocs1n002.ecommerce.inditex.grp `cephadm ceph-volume` failed: cephadm exited with an error code: 1, stderr:Inferring config /var/lib/ceph/41555360-e96b-4b16-a37c-873e0c940091/mon.axdesec2ocs1n002/config
ERROR: [Errno 2] No such file or directory: '/var/lib/ceph/41555360-e96b-4b16-a37c-873e0c940091/mon.axdesec2ocs1n002/config'.
```
this is because of an unexpected behavior regarding 'config inferring' when a legacy directory is present in /var/lib/ceph.
Note: this doesn't fix the root cause, this is a workaround.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2075510
=> [skip ci] cephadm-adopt: remove legacy directory after adoption

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml, requirements.yml, roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/grafana.yml, roles/ceph-facts/tasks/set_monitor_address.yml, roles/ceph-facts/tasks/set_radosgw_address.yml, tests/requirements.txt, tox-external_clients.ini, tox-subset_update.ini
Otherwise `cephadm` can't be installed during cephadm-adopt.yml
playbook execution.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2073480
=> [skip ci] common: config rhcs tools repo on all nodes

infrastructure-playbooks/purge-cluster.yml
This ensures we always reset-failed the ceph-crash service.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2055992
=> [skip ci] purge: reset-failed ceph-crash

infrastructure-playbooks/rolling_update.yml
When the upgrade from Ceph 4 to 5 is performed in the OpenStack context,
ceph-ansible triggers the rolling_update playbook, which is supposed to
rollout new Ceph containers.  The ceph-infra role tries to take care
about firewall, ntp config and logrotate; however, TripleO manages them
through tripleo-heat-templates.  This patch just add an additional tag
to skip the ceph-infra role in the OpenStack context.
Closes: https://bugzilla.redhat.com/2090456
=> [skip ci] Add ceph_infra tag to rolling_update

infrastructure-playbooks/cephadm-adopt.yml
This adds a task that sets `autotune_memory_target_ratio` depending on the
value of `is_hci`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2028693
=> cephadm_adopt: set autotune_memory_target_ratio

docs/source/index.rst
This updates the documentation regarding the Ansible version
requirement for `stable-6.0` branch.
=> [skip ci] doc: update ansible version requirement

.gitignore, docs/source/index.rst, group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml, requirements.txt, requirements.yml, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/grafana.yml, roles/ceph-facts/tasks/set_monitor_address.yml, roles/ceph-facts/tasks/set_radosgw_address.yml, tests/requirements.txt, tox-external_clients.ini, tox-subset_update.ini, tox.ini
ansible.netcommon.ipwrap is deprecated and is not being redirected with ansible 2.9.*
=> ansible: use ansible.utils.ipwrap instead of ansible.netcommon.ipwrap

infrastructure-playbooks/backup-and-restore-ceph-files.yml
Typo introduced during initial implementation.
=> [skip ci] backup-and-restore: fix a typo

infrastructure-playbooks/backup-and-restore-ceph-files.yml
Typical failure:
```
fatal: [localhost]: FAILED! =>
msg: |-
The conditional check 'mode not in ['backup', 'restore']' failed. The error was: error while evaluating conditional (mode not in ['backup', 'restore']): 'mode' is undefined
```
=> [skip ci] backup-and-restore: fix check on 'mode' variable

infrastructure-playbooks/backup-and-restore-ceph-files.yml
If the user doesn't pass a valid name (present in the inventory)
the playbook will fail like following:
```
fatal: [localhost -> {{ target_node }}]: FAILED! =>
msg: |-
The task includes an option with an undefined variable. The error was: "hostvars['10.70.46.40']" is undefined
```
=> [skip ci] backup-and-restore: fix check on 'target_node' variable

tox-shrink_osd.ini, tox.ini
Otherwise vgs/lvs are not created and ceph-validate complains as expected.
=> [skip ci] tests: drop shrink_osd from tox.ini

roles/ceph-facts/tasks/facts.yml, roles/ceph-facts/tasks/set_radosgw_address.yml
Deployments when radosgws don't have the same names for
network interface.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2095605
=> [skip ci] facts: fix deployments with different net interface names

roles/ceph-facts/tasks/facts.yml, roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
use `include_tasks` instead of `import_tasks`.
Given that with `import_tasks` statements are preprocessed
and the tasks that defines it hasn't been run yet, it will fail
and complain like following:
```
The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute '_interface'
```
Using `include_tasks` instead fixes this.
=> facts: fix set_radosgw_address.yml

.github/workflows/pytest.yml
since the bump to ansible-core 2.12, we have to drop
testing against py36 and py37 given that ansible 2.12 requires python
>=3.8
=> [skip ci] pytest: drop test against py <3.8

infrastructure-playbooks/rolling_update.yml
s/pre-quincy/pre-pacific
s/quincy-only/pacific-only
=> [skip ci] update: fix a typo

infrastructure-playbooks/shrink-osd.yml
If the physical disk to device path mapping has changed since the
last ceph-volume simple scan (e.g. addition or removal of disks),
a wrong disk could be deleted.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2071035
=> [skip ci] Refresh /etc/ceph/osd json files content before zapping the disks

roles/ceph-config/tasks/main.yml, roles/ceph-osd/tasks/main.yml
Add missing `--cluster {{ cluster }}` on task
`set osd_memory_target` in the main.yml file of the
ceph-config role.
=> config: followup on 8a5628b51

.readthedocs.yaml, docs/source/conf.py
This is needed to enforce the python version.
=> [skip ci] doc: update readthedoc settings

infrastructure-playbooks/purge-dashboard.yml
When using the legacy group name 'grafana-server', this playbook will run but
won't remove properly all monitoring resources as expected.
Fixes: #7265
=> [skip ci] purge-dashboard: check for legacy group name 'grafana-server'

tox-rbdmirror.ini
do not call dev_setup.yml so we don't use dev repo
=> tests: update tox config file for rbd-mirror scenario

infrastructure-playbooks/rolling_update.yml, tox-cephadm.ini, tox-docker2podman.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-shrink_osd.ini, tox-subset_update.ini, tox-update.ini, tox.ini
When Ansible collections are installed, they should be isolated.
Otherwise, they will be shared in any scheduled job.
This might cause issues when running different branch versions for instance.
=> tests: isolate ansible collections

requirements.yml
Signed-off-by: Sven Kieske <s.kieske@mittwald.de>
=> requirements: update ansible requirements

infrastructure-playbooks/rolling_update.yml, tests/functional/add-mgrs/group_vars/all, tests/functional/add-mons/group_vars/all, tests/functional/lvm-auto-discovery/container/group_vars/all, tests/functional/shrink_mgr/group_vars/all, tests/functional/shrink_rgw/group_vars/all, tests/functional/subset_update/group_vars/all, tox-cephadm.ini, tox-docker2podman.ini, tox-external_clients.ini, tox-filestore_to_bluestore.ini, tox-podman.ini, tox-shrink_osd.ini, tox-subset_update.ini, tox-update.ini, tox.ini
=> stable-7.0: backport of #7264

roles/ceph-config/tasks/main.yml
When 'osd_memory_target' is overridden in ceph_conf_overrides.
The task that sets the fact `osd_memory_target` in the ceph-config role
should be skipped.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2056675#c11
=> config: do not always set _osd_memory_target

roles/ceph-config/tasks/main.yml
otherwise it's impossible to override `osd_memory_target`
via `ceph_conf_overrides`.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2056675
=> config: use osd_memory_target value from ceph_conf_overrides if defined

roles/ceph-facts/tasks/set_radosgw_address.yml
When we come from configure_dashboard.yml, this fact should be set if
`rgw_instances` is defined in group_vars/host_vars. Otherwise, the next
task that set the fact `rgw_instances` will be run as it will assume it
wasn't user defined.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2117294
=> facts: set is_rgw_instances_defined from configure_dashboard

roles/ceph-config/tasks/main.yml
Typical failure:
```
"    The conditional check 'item > osd_memory_target' failed. The error was: Unexpected templating type error occurred on ({% if item > osd_memory_target %} True {% else %} False {% endif %}): '>' not supported between instances of 'str' and 'int'"
```
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2118544
=> ceph-config: allow overriding osd_memory_target

ceph-ansible.spec.in, group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/cephadm.yml, requirements.txt, roles/ceph-dashboard/tasks/configure_dashboard.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-facts/tasks/grafana.yml, roles/ceph-facts/tasks/set_monitor_address.yml, roles/ceph-facts/tasks/set_radosgw_address.yml, roles/ceph-validate/tasks/check_system.yml, tests/requirements.txt
RHCS 5.3 supports 2.9 only.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2120187
=> ansible: require 2.9 for downstream

roles/ceph-crash/templates/ceph-crash.service.j2
add cluster name to CEPH_ARGS env var to support custom cluster name
this can change as an arg to ceph-crash when https://github.com/ceph/ceph/pull/47836 released
=> ceph-crash: add support cluster name

roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
This `run_once: true` breaks multiple rbd-mirror daemons support as it would make all rbd-mirror daemons use the same keyring. Each rbd-mirror daemon needs its own keyring in order to start.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2037646
=> [skip ci] rbd-mirror: fix multiple rbd-mirror daemon support

README-MULTISITE.md
I update the parameters according to this PR: #7315 In addition, where rgw_zonesecondary: True and rgw_zonemaster: False,
I change rgw_zonegroupmaster to be False as those lines below:
https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L396 https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L417 https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L520 https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L535 Add note at line 205 here https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L205
Signed-off-by: quangln94 <ngocquang.ptit@gmail.com>
=> [skip ci] doc: update README-MULTISITE.md

group_vars/all.yml.sample, group_vars/rhcs.yml.sample, infrastructure-playbooks/rolling_update.yml, roles/ceph-common/tasks/release-rhcs.yml, roles/ceph-container-common/tasks/release.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-validate/tasks/check_repository.yml, tests/conftest.py, tox-filestore_to_bluestore.ini, tox-subset_update.ini, tox-update.ini
align with https://github.com/ceph/ceph/pull/47458 since it has been merged.
=> common: v18/reef kickoff

roles/ceph-config/tasks/main.yml, roles/ceph-config/templates/ceph.conf.j2, roles/ceph-osd/tasks/main.yml
- ceph-osd: remove unused ceph config set for osd_memory_target
- As the conf is always being set in the config file there is no need to set it in with `ceph config`.
- Also this will make it hard to run the playbook with the `ceph_update_config` tag as it won't run and will create an inconsistency between the config managements of the cluster
- ceph-config: fix overriding osd_memory_target
- When the value is overriding in `ceph_conf_overrides`, there is no need to calculate and set `osd_memory_target` again as we wanted to override the conf by our desired value.
- ceph-config: don't check for devices on existing osds
- When osd_auto_discovery is true the `devices` var will be empty (as the disks have holders).
- Also in general there is no need to check for devices to list the devices …
=> OSD memory target improvements/fixes

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
`--state=enabled` isn't a valid filter so the unit from the packaging never gets removed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2134917
=> switch-to-containers: fix rbd-mirror migration

infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
There might be cases where it can break idempotency.
=> [skip ci] switch-to-containers: ignore errors when stopping service

roles/ceph-dashboard/tasks/configure_dashboard.yml
Changed the when condition to only execute that fact setting on RGW nodes while before it was run on all nodes and failed if the node was not on the same network range as the RGW.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2131150
=> Setting fact _radosgw_address fail when RGW is on a different network than other nodes

infrastructure-playbooks/cephadm-adopt.yml
The recent rbdmirror refactor introduced a regression in the cephadm-adopt playbook.
Given that the rbd-mirror peer addition is now done by using the monitor config-key store method during the cluster deployment, we can drop this play from the cephadm-adopt.yml playbook.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2140569
=> [skip ci] cephadm-adopt: fix rbd-mirror adoption

library/ceph_crush_rule.py, library/ceph_dashboard_user.py, library/ceph_ec_profile.py, library/ceph_fs.py, library/ceph_key.py, library/ceph_mgr_module.py, library/ceph_osd.py, library/ceph_osd_flag.py, library/ceph_pool.py, module_utils/ca_common.py, tests/library/test_ceph_key.py, tests/library/test_ceph_pool.py, tests/module_utils/test_ca_common.py
When creating a RBD pool it needs to be initialized as per documentation[1] Modified (pre_)generate_ceph_cmd to make it usable with rbd command as well
[1]https://docs.ceph.com/en/latest/rbd/rados-rbd-cmds/#create-a-block-device-pool
=> Initialize rbd pool at pool creation

roles/ceph-config/tasks/main.yml
We need to make sure `rgw_instances` is set before `ceph.conf` is rendered. Otherwise, the `ceph-crash` play in the main playbook updates (via ceph-handler) the `ceph.conf` on rgw nodes and removes rgw instances sections.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2141604
=> ceph-config: make sure rgw_instances is set

roles/ceph-crash/templates/ceph-crash.service.j2, roles/ceph-mds/templates/ceph-mds.service.j2, roles/ceph-mgr/templates/ceph-mgr.service.j2, roles/ceph-mon/templates/ceph-mon.service.j2, roles/ceph-nfs/templates/ceph-nfs.service.j2, roles/ceph-osd/templates/ceph-osd.service.j2, roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2, roles/ceph-rgw/templates/ceph-radosgw.service.j2
With podman version podman-3:4.2.0-4.module+el8.7.0+17064+3b31f55c and later, when mgr fails to start if mon is already running. This is a workaround until podman is fixed.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2169767
Closes:  #7365
Signed-off-by: Teoman ONAY <tonay@ibm.com>
=> Collocated mgr with mon fails to start on RHEL 8.7

roles/ceph-facts/tasks/devices.yml
Exclude disks were defined in dedicated_devices and bluestore_wal_devices on osd_auto_discovery enabled.
=> devices: exclude db disks on osd_auto_discovery enabled

roles/ceph-facts/tasks/devices.yml
If a disk has a symlink it will be re-added to the devices lists one with resolved path and the other with a defined path. We can rebuild the list from the readlink output cause readlink always return the correct path for all disks.
=> devices: remove duplicated disks after the readlink resolve

roles/ceph-nfs/templates/ceph-nfs.service.j2
Due to podman selinux relabeling issue,  added -security-opt label=disable to the nfs unit template
=> Fixes selinux relabeling issue for nfs container

infrastructure-playbooks/shrink-osd.yml
ceph-volume simple scan cannot be executed as it is meant to be run inside the OSD container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2164414
=> shrink-osd fails when the OSD container is stopped

infrastructure-playbooks/shrink-osd.yml
ceph-volume simple scan cannot be executed as it is meant to be run inside the OSD container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2164414
=> [skip ci] Shrink osd

roles/ceph-mgr/tasks/common.yml
Enabling installation of the admin key to mgr nodes by setting "copy_admin_key: true" is broken. This is because the variable is not referenced correctly (using inline Jinja2 templating).
This is an old bug. It exists in stable-6.0 and stable-7.0 and probably earlier versions as well.
=> ceph-mgr: Fix reference to copy_admin_key variable

roles/ceph-config/tasks/main.yml, roles/ceph-facts/tasks/devices.yml
* Exclude device from lvm_volumes while osd_auto_discovery is true
* Sum num_osds on both lvm_volumes and devices list
* Exclude lvm_volumes defined disks from existing osds while it has been counted by the "count number of osds for lvm scenario" task.
=> devices: allow using lvm_volumes with devices 

tests/functional/setup.yml
Due to a bug with the rpm version present in the current stream8 vagrant image, we have to make sure it is first upgraded to the latest version.
=> tests: force rpm pkg upgrade

infrastructure-playbooks/cephadm-adopt.yml
Instead of checking ip_version variable we should check the input address for ip version and select code path based on that.
This solves ceph adoption with mixed ipv6 and ipv4 networks.
Resolves: rhbz#2186226
=> Replace ip_version check with ansible test

library/ceph_key.py, tests/library/test_ceph_key.py
This parameter is not used anywhere in this function, so we can drop it.
=> ceph_key: drop unused result parameter

roles/ceph-config/tasks/main.yml
As it's always being set in ceph.conf template, it leads to having duplicated osd_memory_target keys in rendered ceph conf while defining one in ceph_conf_overrides.
=> ceph-config: drop osd_memory_target from ceph_conf_overrides

group_vars/all.yml.sample, roles/ceph-defaults/defaults/main.yml, tests/functional/add-mdss/container/group_vars/all, tests/functional/add-mgrs/container/group_vars/all, tests/functional/add-mons/container/group_vars/all, tests/functional/add-osds/container/group_vars/all, tests/functional/add-rbdmirrors/container/group_vars/all, tests/functional/add-rgws/container/group_vars/all, tests/functional/all-in-one/container/group_vars/all, tests/functional/all_daemons/container/group_vars/all, tests/functional/collocation/container/group_vars/all, tests/functional/docker2podman/group_vars/all, tests/functional/external_clients/container/inventory/group_vars/all, tests/functional/lvm-auto-discovery/container/group_vars/all, tests/functional/lvm-batch/container/group_vars/all, tests/functional/lvm-osds/container/group_vars/all, tests/functional/podman/group_vars/all, tests/functional/rbdmirror/container/group_vars/all, tests/functional/rbdmirror/container/secondary/group_vars/all, tests/functional/rgw-multisite/container/group_vars/all, tests/functional/rgw-multisite/container/secondary/group_vars/all, tests/functional/shrink_mds/container/group_vars/all, tests/functional/shrink_mgr/container/group_vars/all, tests/functional/shrink_mon/container/group_vars/all, tests/functional/shrink_osd/container/group_vars/all, tests/functional/shrink_rbdmirror/container/group_vars/all, tests/functional/shrink_rgw/container/group_vars/all, tests/functional/subset_update/container/group_vars/all, tox.ini
let's use quay.io/ceph/daemon-base in every tests instead of `ceph/daemon` since it's not supposed to be built anymore soon.
=> tests: updates functional tests with new image

infrastructure-playbooks/cephadm-adopt.yml
When radosgw_address_block was defined, it was not taken into account during rgw adoption process
depends on: https://tracker.ceph.com/issues/62185
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2224351
=> [skip ci]cephadm-adopt: Add --networks parameter support to ceph orch apply rgw

library/ceph_crush.py
doc:
```yaml
containerized:
description:
- Weither or not this is a containerized cluster. The value is
assigned or not depending on how the playbook runs.
required: false
default: None
```
fixes:
```python
failed: [mon1.example.com] (item=Set bucket placement for: osd1.example.com) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "osd1.example.com", "rack": "rack1"}, "msg": "missing required arguments: containerized"}
```
Also delete couple of rudiments in `main()`
=> library: ceph_crush: set containerized param to false to respect docstrings

library/radosgw_zone.py, tests/library/test_radosgw_zone.py
When trying to run a playbook adding multiple zones+zonegroups to a cluster with ceph built from main branch, I found that it would fail in an unexpected way:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: StopIteration
failed: [XXX -> XXX] (item={'realm': 'my-new-realm', 'zonegroup': 'my-new-zonegroup', 'zone': 'my-new-zone-a' 'is_master': 'true', 'system_access_key': 'XXX', 'system_secret_key': 'XXX'}) => changed=false
ansible_loop_var: item
item:
is_master: 'true'
realm: my-new-realm
system_access_key: XXX
system_secret_key: XXX
zone: my-new-zone-a
zonegroup: my-new-zonegroup
module_stderr: |-
Traceback (most recent call last):
File "<stdin>", line 107, in <module>
File "<stdin>", line 99, in _ansiballz_main
File "<stdin>", line 48, …
```
=> Specify the zone when requesting zonegroup information.

infrastructure-playbooks/cephadm-adopt.yml
The tasks "manage nodes with cephadm - ipv4/6" are skipped when cephadm_mgmt_network contains more than one ip network which prevent cephadm from managing the host.
=> cephadm-adopt: Fixes hosts addition to be managed by cephadm

roles/ceph-common/tasks/configure_repository.yml, roles/ceph-mgr/tasks/pre_requisite.yml
When deploying with --skip-tags=package-install (when there is no access to a repository), the playbook is still trying to update the package cache, or to install ceph-mgr packages, which makes the playbook fail.
This change prevents the playbook to try to update the cache or install ceph-mgr packages when the package-install tag is skipped.
=> do not use update debian cache or try to install packages when package-install is disabled

library/ceph_crush_rule.py, roles/ceph-facts/tasks/get_def_crush_rule_name.yml, tests/library/test_ceph_crush_rule.py
With ansible-core 2.15 it is not possible to pass argument of unexpected
type, as otherwise module will fail with:
`'None' is not a string and conversion is not allowed`
With that we want to only get all existing crush rules, so we can simply
supply an empty string as a name argument, which would satisfy
requirements and have same behaviour for previous ansible versions.
Alternative approach would be to stop making `name` as a required
argument to the module and use empty string as default value
when info state is used.
=> Do not pass NoneType as argument to ceph_crush_rule

README.rst
Mark the project as deprecated.
See https://docs.ceph.com/en/latest/cephadm/ for ``cephadm`` documentation.
=> doc: project deprecation

roles/ceph-facts/tasks/facts.yml
This can help to define custom rgw_instances with custom names and ports and addresses.
=> ceph-facts: make set_radosgw_address optional

site-container.yml.sample, site.yml.sample
If mgr is meant to be installed on the mon host it needs to be installed in the same playbook as restart handlers might failed because of non-existance mgr
=> site: install mgrs with mons if sharing the same host

roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
404 is the status code returned by rgw when it is serving website api. This needs to be consider as a healthy status for rgw.
=> ceph-handler: accept 404 as a success status for rgw restart

library/radosgw_zonegroup.py
The returned payload from rgw has `is_master` as a boolean. By having `master` as a string it would always report a change and try to modify the zonegroup.
=> radosgw_zonegroup: support check mode

library/radosgw_user.py
The returned payload from rgw has them as a boolean. By having them as a string it would always report a change and try to modify the user.
=> radosgw_user: add support check mode

library/ceph_config.py
Check the current value and asked both in low case as the asked one might be in capital as it should be.
=> ceph_config: compare current vals in low

.github/workflows/stale.yml
`ubuntu-18.04` environment is deprecated, let's switch to ubuntu-22.04.
=> github: update stale github workflow

roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
If rgw is configured to only operate admin api - this is the status code it will return for GET on no path.
=> ceph-handler: allow 405 as a success restart for rgw

roles/ceph-config/tasks/main.yml, site-container.yml.sample, site.yml.sample
so you don't have to implement a similar play on your own if not using main (sample) playbooks.
=> ceph-config: move `ceph_config` module call to ceph-config role

roles/ceph-config/tasks/main.yml, roles/ceph-mon/tasks/main.yml
ba7eb62a1bcbd925b053cbd737012f034568a6f7 broke deployments where mgrs are not collocated with mons.
=> [skip ci] ceph-mon: move the ceph_config call to ceph-mon role

library/radosgw_user.py
Set return code to 0 on check mode when the user doesn't exists and it will fail the module.
=> radosgw_user: handle non-existence user on check mode

.gitignore, group_vars/all.yml.sample, group_vars/rgws.yml.sample, infrastructure-playbooks/cephadm-adopt.yml, infrastructure-playbooks/purge-cluster.yml, infrastructure-playbooks/rolling_update.yml, infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml, profiles/rgw-keystone-v2, profiles/rgw-keystone-v3, profiles/rgw-radosgw-static-website, profiles/rgw-usage-log, roles/ceph-config/tasks/main.yml, roles/ceph-config/tasks/rgw_systemd_environment_file.yml, roles/ceph-defaults/defaults/main.yml, roles/ceph-handler/tasks/check_running_containers.yml, roles/ceph-handler/templates/restart_rgw_daemon.sh.j2, roles/ceph-rgw/defaults/main.yml, roles/ceph-rgw/handlers/main.yml, roles/ceph-rgw/tasks/common.yml, roles/ceph-rgw/tasks/pre_requisite.yml, roles/ceph-rgw/tasks/start_docker_rgw.yml, roles/ceph-rgw/tasks/start_radosgw.yml, roles/ceph-rgw/templates/ceph-radosgw.service.j2, tests/functional/collect-logs.yml, tests/functional/tests/rgw/test_rgw.py, tox.ini
This is needed by ceph-exporter as it is parsing the socket by the number of dots. Although the rgw_zone variable is only used for constructing the client name and has nothing to do with multisiting.
Reference: https://github.com/ceph/ceph/pull/52698
=> ceph-rgw: introduce rgw zone to the name schema

tests/functional/all_daemons/container/group_vars/clients
Fixes cephadm-adopt test scenario by configuring rbd application on test and test2 pools. Otherwise cephadm-adopt failed at task "Check pools have an application enabled"
=> Fix cephadm-adopt test scenario

group_vars/all.yml.sample, roles/ceph-container-common/tasks/prerequisites.yml, roles/ceph-defaults/defaults/main.yml, tests/functional/collect-logs.yml
To avoid mixup permissions on host and ceph-crash runs as `ceph` which can't send crash reports generated by others with root user.
=> ceph-defaults: use ceph as user and group

infrastructure-playbooks/cephadm-adopt.yml, library/ceph_orch_apply.py, module_utils/ca_common.py, tests/requirements.txt
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2262133
=> ceph_orch_spec: Add ceph orch apply spec feature

library/ceph_orch_apply.py
As is idempotency does not work as the ceph orch
output does contain more attributes than the expected spec.
=> ceph_orch_apply: fix idempotency

group_vars/all.yml.sample, roles/ceph-defaults/defaults/main.yml, roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
RGW currently restarts without waiting for existing connections to close. By adjusting the HAProxy weight before the restart, we can ensure that no active connections are disrupted during the restart process.
=> ceph-handler: use haproxy maintenance for rgw restarts

infrastructure-playbooks/cephadm-adopt.yml
Alertmanager was bind to default * network instead of grafana_server_addr as it was before. Now on if grafana_server_addr is defined, it will be bind to that network.
=> cephadm-adopt: Fixes binding network for alertmanager

infrastructure-playbooks/cephadm-adopt.yml
networks was at the wrong level in the spec file. Failed with "got an unexpected keyword argument 'networks'"
=> cephadm-adopt: fix "Update the placement of radosgw hosts" task

roles/ceph-facts/tasks/devices.yml
In some scenarios with NVMe, a device might be identified by Ansible but could actually be a multipath device rather than an actual device. We need to exclude these as Ceph cannot create OSDs on them.
=> devices: test devices before collecting on auto discovery

library/ceph_pool.py, tests/library/test_ceph_pool.py
Support updating crush rule of the pool via crush rule name.
=> ceph-pool: add support updating crush rule of the pool

library/radosgw_user.py, tests/library/test_radosgw_user.py
Supporting adding/removing caps on the user.
=> radosgw_user: support caps on user

infrastructure-playbooks/cephadm-adopt.yml
Some clusters have customized ssh config, to adopt these clusters we need to set ssh config for cephadm.
=> cephadm-adopt: add cephadm ssh config option

roles/ceph-common/tasks/installs/configure_redhat_repository_installation.yml, tox.ini
this is needed in order to make some libraries available when running on RockyLinux
Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
(cherry picked from commit 867be7c35c1f10080f842c3c6bdd51062cfd788a)
=> common: configure epel repository (rockylinux)

infrastructure-playbooks/cephadm-adopt.yml
cephadm_adopt does not keep Prometheus custom port during adoption
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2242346
=> Bz2242346 prometheus port

roles/ceph-facts/tasks/devices.yml
Right now, under certain OS and Ansible versions, ie Rocky Linux and
ansible-core 2.17, `devices_check` variable is getting defined even if
task was skipped.
That results in set_fact to fail, as resulting variable has no `results`
key in it.
Structure of such variable looks like that:
```
"devices_check": {
"changed": false,
"false_condition": "osd_auto_discovery | default(False) | bool",
"skip_reason": "Conditional result was False",
"skipped": true
}
```
Checking for task not being skipped solves such issues.
Signed-Off-By: Dmitriy Rabotyagov <noonedeadpunk@gmail.com>
=> Don't try to set devices fact when osd_auto_discovery was skipped

infrastructure-playbooks/ceph-keys.yml, infrastructure-playbooks/cephadm-adopt.yml, library/ceph_crush_rule.py, library/ceph_crush_rule_info.py, library/ceph_key.py, library/ceph_key_info.py, roles/ceph-client/tasks/pre_requisite.yml, roles/ceph-crash/tasks/main.yml, roles/ceph-exporter/tasks/main.yml, roles/ceph-facts/tasks/get_def_crush_rule_name.yml, roles/ceph-mds/tasks/common.yml, roles/ceph-mgr/tasks/common.yml, roles/ceph-mon/tasks/deploy_monitors.yml, roles/ceph-nfs/tasks/pre_requisite_container.yml, roles/ceph-nfs/tasks/pre_requisite_non_container.yml, roles/ceph-osd/tasks/common.yml, roles/ceph-osd/tasks/crush_rules.yml, roles/ceph-rbd-mirror/tasks/configure_mirroring.yml, roles/ceph-rgw/tasks/common.yml, roles/ceph-rgw/tasks/pre_requisite.yml, tests/library/test_ceph_crush_rule.py, tests/library/test_ceph_key.py
Validate modules test fails with:
Argument state includes get, list or info as a choice. Functionality should be in an _info or (if further conditions apply) _facts module.
on modules ceph_crush_rule and ceph_key
With Ansible 2.8 and onwards best practice requires that modules gathering info to be put in a separate module named _info[1]
[1]https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module
=> modules: Add _info modules

.readthedocs.yaml
Deprecation of projects using Sphinx without an explicit configuration file
[1] https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> [skip ci] doc: CI readthedocs job fails

infrastructure-playbooks/cephadm-adopt.yml
rgw daemons fail to start as they were looking for ssl certificates while none were available.
=> cephadm-adopt: fix ssl condition in rgw placement task

infrastructure-playbooks/rolling_update.yml
This patch is necessary to migrate older clusters which were deployed when custom names were supported.
Follow up to 3cda8e31c4da81efeade9009b2fc9a1e379f2c66
=> Pass cluster in rolling_update call to ceph_config

infrastructure-playbooks/cephadm-adopt.yml, library/ceph_orch_apply.py
This PR contains the following commits which patch TASK "Update the placement of radosgw hosts" in the playbook cephadm-adopt.yml.
- Handle adoption when radosgw_address_block is comma delimited list
- Handle radosgw hosts placement with non-default cluster name
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2339149
=> Handle RGW hosts placement during adoption of older clusters with multiple subnets

infrastructure-playbooks/cephadm-adopt.yml
The networks list in a spec is usually a range not a single IP. grafana_server_addr is a fact created from grafana_network so it is a more appropriate parameter to pass.
Follow up to 770a527a9ee6b34091798c6120235026ad1ecfa9
=> Adopt with grafana_network not grafana_server_addr

group_vars/all.yml.sample, roles/ceph-defaults/defaults/main.yml
It is not necessary anymore as this behavior became the default one.
Ceph Ref. https://github.com/ceph/ceph/pull/50344
=> common/container: drop CEPH_USE_RANDOM_NONCE env var

library/radosgw_realm.py, tests/library/test_radosgw_realm.py
radosgw-admin supports the default flag to set the pulled realm as default if requested.
=> radosgw-realm: support default flag for pull

roles/ceph-infra/templates/logrotate.conf.j2
We had an Issue in Logrotation of the RGW ops logs With This Error:
```
error: Compressing program wrote the following message to stderr when compressing log /var/log/ceph/rgw_ops_rgw.default.si1-cstorage4010.rgw0.log.1:
gzip: stdin: file size changed while zipping
error: Compressing program wrote the following message to stderr when compressing log /var/log/ceph/rgw_ops_rgw.default.si1-cstorage4010.rgw1.log.1:
gzip: stdin: file size changed while zipping
```
Rgws doesn't change inode of log files to write when they get SIGHUP so I Added this option to rotate the logs properly
=> Add copytruncate option In Logrotate for heavily log operations

requirements.txt
I see no more six usage in this project.
Six is also removed from library/ceph_volume.py [since 2019](https://github.com/ceph/ceph-ansible/pull/4234).
=> Remove six from requirements.txt

library/ceph_pool.py, tests/library/test_ceph_pool.py
The pg_autoscale_mode parameter has three possible values 'on', 'off', and 'warn'. In case of 'warn' it should be possible to pass the number of placement groups (pg_num) to the create_pool function. Nothing is lost by allowing this. The health check will still warn if the value needs adjustment.
The evaluation of target_size_ratio works as before.
Add a test iterating through possible value combinations of the parameters target_size_ratio, pg_num and pg_autoscale_mode.
=> ceph-pool: pass pg_num for pg_autoscale_mode warn
